@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 20663617
TI  == microbial communities in the tonsils of healthy pigs.
AB  == the tonsils of mammals such as humans and pigs are colonized with an extensive microbiota and are frequently the site for asymptomatic carriage of bacterial pathogens. the goal of this study was to determine the composition of the microbial community of the tonsils in healthy pigs. tonsils were collected from eight pigs from two different healthy herds. samples of the tonsils from each pig were used for culture dependent and culture independent identification of the microbial community. aerobic cultivation identified pasteurella multocida, actinobacillus spp., staphylococcus aureus, staphylococcus epidermidis, streptococcus suis, streptococcus dysgalactiae, and escherichia coli from >/= 50% of the pigs in both herds. for culture independent studies, microbial community members were identified by 16s rrna sequences using the ribosomal database project pipeline programs developed at michigan state university. dominant genera identified by 16s rrna analysis in pigs from both herds included actinobacillus,  haemophilus, pasteurella, porphyromonas, fusobacterium, bacteroides, and prevotella. these genera were detected in nearly every pig regardless of herd. in contrast, there was an asymmetric distribution of minor genera between the two herds, suggesting herd-specific differences in the microbial communities. in addition, we demonstrated primer bias between two frequently used forward primers when targeting the tonsillar community. our results suggest that the major bacterial community members found in porcine tonsils are the same regardless of herd, while the minor species are unique to each herd. this is the first analysis using 16s rrna sequence libraries of the composition of microbial communities in  the porcine upper respiratory tract.
TIHT== 
ABHT== 

PMID== 8953533
TI  == interpretive criteria for antimicrobial susceptibility testing of ceftiofur against bacteria associated with swine respiratory disease.
AB  == ceftiofur, an extended-spectrum cephalosporin, is active against a variety of animal pathogens, including organisms associated with swine respiratory disease.  however, minimum inhibitory concentration (mic) breakpoint and disk diffusion interpretive criteria have not been established for swine pathogens. susceptibility tests were performed by broth microdilution mic and disk diffusion methods on 246 bacterial species that cause swine respiratory disease. ceftiofur  was active against salmonella sp., pasteurella multocida, actinobacillus pleuropneumoniae, streptococcus suis, and escherichia coli but was not active against bordetella bronchiseptica measured by mic. based on pharmacokinetic studies of ceftiofur in swine after a single intramuscular injection of 3 or 5 mg/kg body weight of ceftiofur and on the mic and disk diffusion data, we recommend mic breakpoints and disk diffusion distances, respectively, of < or = 2 micrograms/ml and > or = 21 mm for susceptible, 4 micrograms/ml and 18-20 mm for  intermediate, and > or = 8 micrograms/ml and > or = 17 mm for resistant classification for swine pathogens. when these breakpoints were applied to data from a previous study using bovine pathogens, only 1 minor interpretive error occurred.
TIHT== 
ABHT== 

PMID== 8828126
TI  == evaluation of a pcr for detection of actinobacillus pleuropneumoniae in mixed bacterial cultures from tonsils.
AB  == a pcr for the detection of actinobacillus pleuropneumoniae was evaluated. all of  102 field, isolates of a, pleuropneumoniae reacted in the pcr by amplification of a 985 bp product. no pcr amplification product was observed when examining strains of a. ureae, a. capsulatus, a. hominis, a. equuli, a, rossii, a. suis, escherichia coli, bordetella bronchiseptica. streptococcus suis, pasteurella haemolytica, pasteurella multocida, haemophilus parasuis, haemophilus taxon minor group, haemophilus taxon d/e and haemophilus taxon f. amplification of a 985 bp product was, however, observed when testing strains of a. lignieresii. the lower  detection limit of the pcr test was 10(3) a. pleuropneumoniae cfu/pcr test tube and was not affected by addition of 10(6) e. coli cfu/pcr test tube. mixed bacterial cultures from tonsils of 101 pigs from 9 different herds were tested by culture and by pcr using four different bacteriological media. while 65% reacted  positive in the pcr only 23% were positive by culture, thereby suggesting a superior sensitivity of the pcr test to that of culture. the use of selective media, large inoculum and incubation for 48 h gave the highest number of positive pcr reactions from mixed bacterial cultures. tonsil cultures from 50 pigs from an a. pleuropneumoniae-negative herd did not react in the pcr. the results show that pcr on mixed bacterial cultures from tonsils may be a highly sensitive method for the detection of a. pleuropneumoniae in pig herds.
TIHT== 
ABHT== 

PMID== 8501242
TI  == evaluation of the rapid nh system for identification of haemophilus somnus, pasteurella multocida, pasteurella haemolytica, and actinobacillus pleuropneumoniae isolated from cattle and pigs with respiratory disease.
AB  == haemophilus somnus, pasteurella haemolytica, pasteurella multocida, and actinobacillus pleuropneumoniae from cattle and pigs with respiratory disease were used to evaluate the rapid nh system (innovative diagnostics, atlanta, ga.). minor modifications of the rapid nh system to include animal source and growth requirements would permit the identification of all isolates tested.
TIHT== 
ABHT== 

PMID== 1548238
TI  == phylogeny of 54 representative strains of species in the family pasteurellaceae as determined by comparison of 16s rrna sequences.
AB  == virtually complete 16s rrna sequences were determined for 54 representative strains of species in the family pasteurellaceae. of these strains, 15 were pasteurella, 16 were actinobacillus, and 23 were haemophilus. a phylogenetic tree was constructed based on sequence similarity, using the neighbor-joining method.  fifty-three of the strains fell within four large clusters. the first cluster included the type strains of haemophilus influenzae, h. aegyptius, h. aphrophilus, h. haemolyticus, h. paraphrophilus, h. segnis, and actinobacillus actinomycetemcomitans. this cluster also contained a. actinomycetemcomitans fdc y4, atcc 29522, atcc 29523, and atcc 29524 and h. aphrophilus nctc 7901. the second cluster included the type strains of a. seminis and pasteurella aerogenes  and h. somnus ovcg 43826. the third cluster was composed of the type strains of pasteurella multocida, p. anatis, p. avium, p. canis, p. dagmatis, p. gallinarum, p. langaa, p. stomatis, p. volantium, h. haemoglobinophilus, h. parasuis, h. paracuniculus, h. paragallinarum, and a. capsulatus. this cluster also contained  pasteurella species a ccug 18782, pasteurella species b ccug 19974, haemophilus taxon c capm 5111, h. parasuis type 5 nagasaki, p. volantium (h. parainfluenzae)  nctc 4101, and p. trehalosi nctc 10624. the fourth cluster included the type strains of actinobacillus lignieresii, a. equuli, a. pleuropneumoniae, a. suis, a. ureae, h. parahaemolyticus, h. parainfluenzae, h. paraphrohaemolyticus, h. ducreyi, and p. haemolytica. this cluster also contained actinobacillus species strain ccug 19799 (bisgaard taxon 11), a. suis atcc 15557, h. ducreyi atcc 27722  and hd 35000, haemophilus minor group strain 202, and h. parainfluenzae atcc 29242. the type strain of p. pneumotropica branched alone to form a fifth group.  the branching of the pasteurellaceae family tree was quite complex. the four major clusters contained multiple subclusters. the clusters contained both rapidly and slowly evolving strains (indicated by differing numbers of base changes incorporated into the 16s rrna sequence relative to outgroup organisms).  while the results presented a clear picture of the phylogenetic relationships, the complexity of the branching will make division of the family into genera a difficult and somewhat subjective task. we do not suggest any taxonomic changes at this time.
TIHT== 
ABHT== 

