@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 26018307
TI  == antimicrobial and cytotoxic effects of phosphoric acid solution compared to other root canal irrigants.
AB  == phosphoric acid has been suggested as an irrigant due to its effectiveness in removing the smear layer. objectives: the purpose of this study was to compare the antimicrobial and cytotoxic effects of a 37% phosphoric acid solution to other irrigants commonly used in endodontics. material and methods: the substances 37% phosphoric acid, 17% edta, 10% citric acid, 2% chlorhexidine (solution and gel), and 5.25% naocl were evaluated. the antimicrobial activity was tested against candida albicans, staphylococcus aureus, enterococcus faecalis, escherichia coli, actinomyces meyeri, parvimonas micra, porphyromonas gingivalis, and prevotella nigrescens according to the agar diffusion method. the cytotoxicity of the irrigants was determined by using the mtt assay. results: phosphoric acid presented higher antimicrobial activity compared to the other tested irrigants. with regard to the cell viability, this solution showed results similar to those with 5.25% naocl and 2% chlorhexidine (gel and solution), whereas 17% edta and 10% citric acid showed higher cell viability compared to other irrigants. conclusion: phosphoric acid demonstrated higher antimicrobial activity and cytotoxicity similar to that of 5.25% naocl and 2% chlorhexidine (gel and solution).
TIHT== 
ABHT== 

PMID== 25107981
TI  == axenic culture of a candidate division tm7 bacterium from the human oral cavity and biofilm interactions with other oral bacteria.
AB  == the diversity of bacterial species in the human oral cavity is well recognized, but a high proportion of them are presently uncultivable. candidate division tm7  bacteria are almost always detected in metagenomic studies but have not yet been  cultivated. in this paper, we identified candidate division tm7 bacterial phylotypes in mature plaque samples from around orthodontic bonds in subjects undergoing orthodontic treatment. successive rounds of enrichment in laboratory media led to the isolation of a pure culture of one of these candidate division tm7 phylotypes. the bacteria formed filaments of 20 to 200 mum in length within agar plate colonies and in monospecies biofilms on salivary pellicle and exhibited some unusual morphological characteristics by transmission electron microscopy, including a trilaminated cell surface layer and dense cytoplasmic deposits. proteomic analyses of cell wall protein extracts identified abundant polypeptides predicted from the tm7 partial genomic sequence. pleiomorphic phenotypes were observed when the candidate division tm7 bacterium was grown in dual-species biofilms with representatives of six different oral bacterial genera. the tm7 bacterium formed long filaments in dual-species biofilm communities with actinomyces oris or fusobacterium nucleatum. however, the tm7 isolate grew as short rods or cocci in dual-species biofilms with porphyromonas gingivalis, prevotella intermedia, parvimonas micra, or streptococcus gordonii, forming notably robust biofilms with the latter two species. the ability to cultivate tm7 axenically should majorly advance understanding of the physiology,  genetics, and virulence properties of this novel candidate division oral bacterium.
TIHT== 
ABHT== 

PMID== 24923267
TI  == antimicrobial susceptibility of clinical isolates of anaerobic bacteria in ontario, 2010-2011.
AB  == the local epidemiology of antimicrobial susceptibility patterns in anaerobic bacteria is important in guiding the empiric treatment of infections. however, susceptibility data are very limited on anaerobic organisms, particularly among non-bacteroides organisms. to determine susceptibility profiles of clinically-significant anaerobic bacteria in ontario canada, anaerobic isolates from sterile sites submitted to public health ontario laboratory (phol) for identification and susceptibility testing were included in this study. using the  e-test method, isolates were tested for various antimicrobials including, penicillin, cefoxitin, clindamycin, meropenem, piperacillin-tazobactam and metronidazole. the mic results were interpreted based on guidelines published by  clinical and laboratory standards institute. of 2527 anaerobic isolates submitted to phol, 1412 were either from sterile sites or bronchial lavage, and underwent susceptibility testing. among bacteroides fragilis, 98.2%, 24.7%, 1.6%, and 1.2%  were resistant to penicillin, clindamycin, piperacillin-tazobactam, and metronidazole, respectively. clostridium perfringens was universally susceptible  to penicillin, piperacillin-tazobactam, and meropenem, whereas 14.2% of other clostridium spp. were resistant to penicillin. among gram-positive anaerobes, actinomyces spp., parvimonas micra and propionibacterium spp. were universally susceptible to beta-lactams. eggerthella spp., collinsella spp., and eubacterium  spp. showed variable resistance to penicillin. among gram-negative anaerobes, fusobacterium spp., prevotella spp., and veillonella spp. showed high resistance  to penicillin but were universally susceptible to meropenem and piperacillin-tazobactam. the detection of metronidazole resistant b. fragilis is  concerning as occurrence of these isolates is extremely rare. these data highlight the importance of ongoing surveillance to provide clinically relevant information to clinicians for empiric management of infections caused by anaerobic organisms.
TIHT== 
ABHT== 

PMID== 24862703
TI  == microbial evaluation of traumatized teeth treated with triple antibiotic paste or calcium hydroxide with 2% chlorhexidine gel in pulp revascularization.
AB  == introduction: revascularization outcome depends on microbial elimination because  apical repair will not happen in the presence of infected tissues. this study evaluated the microbial composition of traumatized immature teeth and assessed their reduction during different stages of the revascularization procedures performed with 2 intracanal medicaments. methods: fifteen patients (7-17 years old) with immature teeth were submitted to the revascularization procedures; they were divided into 2 groups according to the intracanal medicament used: tap group (n = 7), medicated with a triple antibiotic paste, and chp group (n = 8), dressed with calcium hydroxide + 2% chlorhexidine gel. samples were taken before any treatment (s1), after irrigation with 6% naocl (s2), after irrigation with 2% chlorhexidine (s3), after intracanal dressing (s4), and after 17% edta irrigation (s5). cultivable bacteria recovered from the 5 stages were counted and identified by means of polymerase chain reaction assay (16s rrna). results: both groups had  colony-forming unit counts significantly reduced after s2 (p < .05); however, no  significant difference was found between the irrigants (s2 and s3, p = .99). no difference in bacteria counts was found between the intracanal medicaments used (p = .95). the most prevalent bacteria detected were actinomyces naeslundii (66.67%), followed by porphyromonas endodontalis, parvimonas micra, and fusobacterium nucleatum, which were detected in 33.34% of the root canals. an average of 2.13 species per canal was found, and no statistical correlation was observed between bacterial species and clinical/radiographic features. conclusions: the microbial profile of infected immature teeth is similar to that  of primarily infected permanent teeth. the greatest bacterial reduction was promoted by the irrigation solutions. the revascularization protocols that used the tested intracanal medicaments were efficient in reducing viable bacteria in necrotic immature teeth.
TIHT== 
ABHT== 

PMID== 24345204
TI  == the effects of different orthodontic appliances upon microbial communities.
AB  == objectives: orthodontic appliances can promote accumulation of dental plaque, with associated enamel decalcification or gingival inflammation. the aim of this  study was to examine longer-term microbiological changes during orthodontic treatment with fixed appliances. materials and methods: twenty-four orthodontic patients aged 11-14 years undergoing fixed appliance therapy were recruited into  the study. each was randomized for cross-mouth assignment of molar bands and bonded molar tubes to contralateral quadrants of the mouth. all patients received self-ligating brackets, but again using randomization, one upper lateral incisor  bracket (left or right) also received an elastomeric ligature. plaque samples from the molars and upper lateral incisors were obtained at intervals during treatment and up to 1 year after appliance removal. denaturing gradient gel electrophoresis and 16s rdna microarray were used to compare plaque microbial fingerprints. results: plaque populations changed within 3 months of commencing treatment at all sites. the greatest differences in plaque composition were seen  with self-ligating brackets with an elastomeric ligature. post-treatment plaque associated with both types of molar attachment contained increased levels of periodontal pathogens porphyromonas gingivalis, tannerella forsythia, and eubacterium nodatum, while campylobacter rectus, parvimonas micra, and actinomyces odontolyticus were also elevated with bonds. conclusions: the results suggest that orthodontic treatment may cause sustained changes in plaque microbiotas and that molar bond-associated plaque may have raised disease potential.
TIHT== 
ABHT== 

PMID== 24278920
TI  == analysis of bacterial flora associated with peri-implantitis using obligate anaerobic culture technique and 16s rdna gene sequence.
AB  == purpose: to analyze and characterize the predominant bacterial flora associated with peri-implantitis by using culture techniques under obligate anaerobic conditions and 16s rdna gene sequences. materials and methods: subgingival bacterial specimens were taken from 30 patients: control (n = 15), consisting of  patients with only healthy implants; and test (n = 15), consisting of patients with peri-implantitis. in both groups, subgingival bacterial specimens were taken from the deepest sites. an anaerobic glove box system was used to cultivate bacterial strains. the bacterial strains were identified by 16s rdna genebased polymerase chain reaction and comparison of the gene sequences. results: peri-implantitis sites had approximately 10-fold higher mean colony forming units (per milliliter) than healthy implant sites. a total of 69 different bacterial species were identified in the peri-implantitis sites and 53 in the healthy implant sites. the predominant bacterial species in the peri-implantitis sites were eubacterium nodatum, e. brachy, e. saphenum, filifactor alocis, slackia exigua, parascardovia denticolens, prevotella intermedia, fusobacterium nucleatum, porphyromonas gingivalis, centipeda periodontii, and parvimonas micra. the predominant bacteria in healthy implant sites apart from streptococcus were pseudoramibacter alactolyticus, veillonella species, actinomyces israelii, actinomyces species, propionibacterium acnes, and parvimonas micra. conclusion: these results suggest that the environment in the depths of the sulcus showing peri-implantitis is well suited for growth of obligate anaerobic bacteria. the present study demonstrated that the sulcus around oral implants with peri-implantitis harbors high levels of asaccharolytic anaerobic gram-positive rods (aagprs) such as e. nodatum, e. brachy, e. saphenum, filifactor alocis, slackia exigua, and gram-negative anaerobic rods, suggesting that conventional periodontopathic bacteria are not the only periodontal pathogens active in peri-implantitis, and that aagprs may also play an important role.
TIHT== 
ABHT== 

PMID== 24144271
TI  == microbial analysis of subgingival plaque samples compared to that of whole saliva in patients with periodontitis.
AB  == background: the detection of special bacterial species in patients with periodontitis is considered to be useful for clinical diagnosis and treatment. the collection of subgingival plaque samples is the common way for the determination of periodontopathic bacteria. however, recently, salivary analysis  has been discussed as an advantageous future diagnostic method for periodontitis  because it offers simple quantitative sampling and the possibility to assess various bacteria. the aim of this cross-sectional study is to investigate whether there is a correlation between the results of different bacterial species in saliva and subgingival plaque samples from individuals with aggressive periodontitis (agp) and chronic periodontitis (cp). methods: whole saliva and subgingival plaque samples from the deepest pocket of each quadrant were collected from 43 patients with cp and 33 patients with agp. twenty different bacterial species from both samplings were determined by the 16s ribosomal rna-based polymerase chain reaction with microarray technique. results: all bacterial species were detected in salivary and subgingival plaque samples. for aggregatibacter actinomycetemcomitans, porphyromonas gingivalis, treponema denticola, and tannerella forsythia, as well as actinomyces viscosus, campylobacter rectus/showae, prevotella intermedia, parvimonas micra, eubacterium nodatum, and campylobacter gracilis, a significant positive correlation between salivary and subgingival plaque samples was detected in patients with both types  of periodontitis. there were no significant differences in bacteria in salivary and subgingival plaque samples between agp and cp. conclusion: salivary analysis  might be discussed as a potential alternative to subgingival plaque sampling for  microbiologic analysis in both agp and cp.
TIHT== 
ABHT== 

PMID== 23784124
TI  == a consortium of aggregatibacter actinomycetemcomitans, streptococcus parasanguinis, and filifactor alocis is present in sites prior to bone loss in a  longitudinal study of localized aggressive periodontitis.
AB  == aggregatibacter actinomycetemcomitans-induced localized aggressive periodontitis  (lap) in african-american adolescents has been documented but is poorly understood. two thousand fifty-eight adolescents aged 11 to 17 years were screened for their periodontal status and the presence of a. actinomycetemcomitans in their oral cavity. seventy-one a. actinomycetemcomitans-negative and 63 a. actinomycetemcomitans-positive periodontally healthy subjects were enrolled, sampled, examined, and radiographed yearly for 3 years. gingival and periodontal pocket depth and attachment levels were recorded. disease presentation was characterized by bone loss (bl). subgingival sites were sampled every 6 months to assess (i) the role of a. actinomycetemcomitans in bl and (ii) the association of a. actinomycetemcomitans  and other microbes in their relationships to bl. sixteen of 63 subjects with a. actinomycetemcomitans developed bl (the other 47 subjects with a. actinomycetemcomitans had no bl). no a. actinomycetemcomitans-negative subjects developed bl. human oral microbe identification microarray (homim) was used for subgingival microbial assessment. on a subject level, pooled data from a. actinomycetemcomitans-positive subjects who remained healthy had higher prevalences of streptococcus and actinomyces species, while a. actinomycetemcomitans-positive subjects with bl had higher prevalences of parvimonas micra, filifactor alocis, a. actinomycetemcomitans, and peptostreptococcus sp. human oral taxon 113 (hot-113). at vulnerable sites, a. actinomycetemcomitans, streptococcus parasanguinis, and f. alocis levels were elevated prior to bl. in cases where the three-organism consortium (versus a. actinomycetemcomitans alone) was detected, the specificity for detecting sites of future bl increased from 62% to 99%, with a sensitivity of 89%. we conclude that  detecting the presence of a. actinomycetemcomitans, s. parasanguinis, and f. alocis together indicates sites of future bl in lap. a synergistic interaction of this consortium in lap causation is possible and is the subject of ongoing research.
TIHT== 
ABHT== 

PMID== 23659237
TI  == effect of metalloporphyrins on red autofluorescence from oral bacteria.
AB  == the aim of this study was to assess the red autofluorescence from bacterial species related to dental caries and periodontitis in the presence of different nutrients in the growth medium. bacteria were grown anaerobically on tryptic soy  agar (tsa) supplemented with nutrients, including magnesium-porphyrins from spinach and iron-porphyrins from heme. the autofluorescence was then assessed at  405 nm excitation. on the tsa without additives, no autofluorescence was observed from any of the species tested. on the tsa containing sheep blood, red autofluorescence was observed only from parvimonas micra. when the tsa was supplemented with blood, hemin, and vitamin k, red autofluorescence was observed  from actinomyces naeslundii, bifidobacterium dentium, and streptococcus mutans. finally, on the tsa supplemented with spinach extract, red autofluorescence was observed from aggregatibacter actinomycetemcomitans, a. naeslundii, enterococcus  faecalis, fusobacterium nucleatum, lactobacillus salivarius, s. mutans, and veillonella parvula. we conclude that the bacteria related to dental caries and periodontal disease exhibit red autofluorescence. the autofluorescence characteristics of the tested strains depended on the nutrients present, such as  metalloporphyrins, suggesting that the metabolic products of the oral biofilm could be responsible for red autofluorescence.
TIHT== 
ABHT== 

PMID== 22335194
TI  == microbiologic profile of endodontic infections from hiv- and hiv+ patients using  multiple-displacement amplification and checkerboard dna-dna hybridization.
AB  == objective: to compare the microbiota of endodontic infections in necrotic pulp from hiv-negative and hiv-positive subjects. materials and methods: root canal samples from necrotic pulp were collected from 40 hiv- and 20 hiv+ subjects. pulps were amplified using multiple displacement amplification (mda). then, checkerboard dna-dna hybridization was employed to assess the levels of 107 microbial taxa. the percentage of dna probe count and the percentage of teeth colonized by each test species were investigated. significant differences between groups regarding proportions of taxa and prevalence of the test species were sought using the mann-whitney test and the chi-square analysis, respectively. results: the most prevalent taxa detected were dialister pneumosintes, stenotrophomonas maltophilia, streptococcus sobrinus, corynebacterium diphteriae, and helicobacter pylori among hiv- subjects and d. pneumosintes, prevotella tannerae, porphyromonas gingivalis, parvimonas micra, prevotella nigrescens, and  corynebacterium diphtheriae among hiv+ individuals. d. pneumosintes, c. diphtheria, and c. albicans were the most abundant species in the hiv- group, whereas the predominant taxa in hiv+ samples were p. tannerae, d. pneumosintes and olsenella uli. p. tannerae, o. uli, veilonella dispar, bacteroides fragilis,  and actinomyces meyeri were significantly more abundant in hiv+ samples. conclusions: there were significant differences in the prevalence and proportions of specific microbial taxa between hiv- and hiv+ individuals. the root canal microbiota may represent a reservoir of important oral and medical pathogens, mainly in hiv+ individuals.
TIHT== 
ABHT== 

PMID== 22099908
TI  == persistent extraradicular infection in root-filled asymptomatic human tooth: scanning electron microscopic analysis and microbial investigation after apical microsurgery.
AB  == introduction: procedural accidents have a negative effect on healing and might contribute to the persistence of infections in inaccessible apical areas, requiring surgical intervention. this report describes a case of persistent apical periodontitis of a lower left first molar associated with the sinus tract  and a periapical lesion that required nonsurgical endodontic retreatment and apical surgery for resolution. methods: the tooth had received endodontic treatment 3 years ago and had to be retreated using the crown-down technique with chemical auxiliary substance (2% chlorhexidine gel), foramen patency, and enlargement and was filled in a single appointment. the occlusal access cavity was immediately restored with composite resin. after 1 month, it could be observed that the sinus tract persisted and, radiographically, the lesion remained unaltered. therefore, endodontic microsurgery was indicated. apical microsurgery was performed under magnification with the use of a dental operating microscope including apicectomy, root end with ultrasound, and sealing with mineral trioxide aggregate. a microbiological sample was collected from the apical lesion. the resected distal root apex was observed by scanning electron microscopy. results: the following species were detected: actinomyces naeslundii  and actinomyces meyeri, propionibacterium propionicum, clostridium botullinum, parvimonas micra, and bacteroides ureolyticus; scanning electron microscopic analysis revealed bacterial biofilm surrounding the apical foramen and external radicular surface. gutta-percha overfilling at the apex because of a zip caused during initial endodontic treatment could be observed. a 6-month follow-up showed apparent radiographic periapical healing, which progressed after 24 months. conclusion: gram-positive anaerobic bacteria and extraradicular biofilm seem to participate in the maintenance of persistent periapical pathology, and endodontic retreatment followed by periapical microsurgery proved to be a successful alternative in the resolution of persistent extraradicular infections.
TIHT== 
ABHT== 

PMID== 21605286
TI  == detection of nine microorganisms from the initial carious root lesions using a taqman-based real-time pcr.
AB  == objective: the purpose of this study was to quantify nine selected cariogenic bacteria in plaque from sound root surfaces and initial carious root lesions using taqman pcr and to analyse a putative dependence on the kind of initial periodontal treatment. material and methods: fifty-four subjects with generalized chronic periodontitis were randomly allocated to one of the following initial periodontal therapies: full-mouth disinfection, full-mouth scaling and root planing or scaling and root planing within 7 days. plaque samples were taken before and after periodontal treatment and analysed by taqman pcr. results: the quantity of the cariogenic bacteria actinomyces spp., streptococcus mutans, streptococcus sobrinus, lactobacilllus spp., rothia dentocariosa, parvimonas micra, propionibacterium acnes and neisseria mucosa were significantly higher, while the quantity of veillonella parvula was significantly lower on initial carious lesions than on the sound surfaces both before and after periodontal therapy. no significant differences could be found in any of the tested bacteria  except p. micra on initial carious lesions and sound surfaces for both examinations between the groups. conclusion: all the nine species analysed were found to be present in initial carious root lesions as well as sound root surfaces but in different quantities, independent of the different periodontal therapies.
TIHT== 
ABHT== 

PMID== 21492236
TI  == influence of topography and hydrophilicity on initial oral biofilm formation on microstructured titanium surfaces in vitro.
AB  == objectives: the aim of this study was to analyse the influence of the microtopography and hydrophilicity of titanium (ti) substrates on initial oral biofilm formation. materials and methods: nine bacterial species belonging to the normal oral microbiota, including: aggregatibacter actinomycetemcomitans, actinomyces israelii, campylobacter rectus, eikenella corrodens, fusobacterium nucleatum, parvimonas micra, porphyromonas gingivalis, prevotella intermedia, and streptococcus sanguinis were tested on ti surfaces: pretreatment (pt [r(a) <0.2 mum]), acid-etched (a [r(a) <0.8 mum]), a modified to be hydrophilic (moda), sand-blasted/acid-etched (sla [r(a) =4 mum]), and hydrophilic sla (modsla). disks were incubated for 24 h in anaerobic conditions using a normal culture medium (cm) or human saliva (hs). the total counts of bacteria and the proportion of each bacterial species were analysed by checkerboard dna-dna hybridization. results: higher counts of bacteria were observed on all surfaces incubated with cm compared with the samples incubated with hs. pt, sla, and modsla exhibited higher numbers of attached bacteria in cm, whereas sla and modsla had a significant increase in bacterial adhesion in hs. the proportion of the species in the initial biofilms was also influenced by the surface properties and the media used: sla and modsla increased the proportion of species like a. actinomycetemcomitans and s. sanguinis in both media, while the adhesion of a. israelii and p. gingivalis on the same surfaces was affected in the presence of saliva. conclusions: the initial biofilm formation and composition were affected  by the microtopography and hydrophilicity of the surface and by the media used.
TIHT== 
ABHT== 

PMID== 21410554
TI  == clustering of subgingival microbial species in adolescents with periodontitis.
AB  == it has become increasingly recognized that groups of microorganisms interact within the subgingival plaque of adult subjects with periodontitis. it is much less clear, however, whether the consortia of microorganisms associated with periodontitis are different in early and more advanced cases of periodontitis. to investigate this point further, subgingival plaque was collected from six sites in 87 adolescents with periodontitis and 73 controls and the samples were analyzed for the detection of 18 microbial species using the dna-dna hybridization technique. actinomyces oris accounted for the highest proportion of the flora and was more predominant among controls. prevotella nigrescens, prevotella intermedia, porphyromonas gingivalis, and tannerella forsythia were present at higher levels among the subjects with periodontitis. factor analyses identified one factor characterized by highly positive loadings for t. forsythia, campylobacter rectus, p. gingivalis, p. intermedia, p. nigrescens, parvimonas micra, and treponema denticola, and another factor characterized by highly positive loadings of a. oris, capnocytophaga ochracea, eikenella corrodens, streptococcus intermedius, selenomonas noxia, streptococcus oralis, streptococcus sanguinis, and veillonella parvula. aggregatibacter actinomycetemcomitans and streptococcus mutans did not load on any of the two factors, while fusobacterium  nucleatum loaded on both. these findings confirm the occurrence of clustering of  subgingival bacteria according to case status also among young individuals.
TIHT== 
ABHT== 

PMID== 19931851
TI  == microbial profile of ligature-induced periodontitis in rats.
AB  == objective: the aim of this study was to evaluate the composition of the biofilm accumulated around ligatures in rats by checkerboard dna-dna hybridization using  probes made from human oral bacterial species. methods: 12 wistar rats were selected for this study. one of the mandibular first molars of each animal received a ligature, while the contralateral tooth was left unligated to be used  as a control. forty-two days later, the ligatures and one sample of biofilm from  each unligated teeth were analyzed by checkerboard dna-dna hybridization for 40 human periodontal species. the area of bone loss in the furcation area was determined histometrically. results: the unligated teeth did not present any of the bacterial species tested. twenty five species were detected in the ligatures. streptococcus- and actinomyces-like species were found in high mean counts, followed by fusobacterium-, prevotella nigrescens- and parvimonas micra-like species and porphyromonas gingivalis- and aggregatibacter actinomycetemcomitans-like species. greater bone loss was observed in the furcation area of the ligated than of the unligated group (p<0.0001). conclusion: at 42 days, the ligature biofilm in rats presents various bacterial species that  hybridize to probes of periodontal bacterial species commonly observed in human.
TIHT== 
ABHT== 

PMID== 19722792
TI  == comparisons of subgingival microbial profiles of refractory periodontitis, severe periodontitis, and periodontal health using the human oral microbe identification microarray.
AB  == background: this study compared the subgingival microbiota of subjects with refractory periodontitis (rp) to those in subjects with treatable periodontitis (grs = good responders) or periodontal health (ph) using the human oral microbe identification microarray (homim). methods: at baseline, subgingival plaque samples were taken from 47 subjects with periodontitis and 20 individuals with ph and analyzed for the presence of 300 species by homim. the subjects with periodontitis were classified as having rp (n = 17) based on mean attachment loss (al) and/or more than three sites with al >or=2.5 mm after scaling and root planing, surgery, and systemically administered amoxicillin and metronidazole or  as grs (n = 30) based on mean attachment gain and no sites with al >or=2.5 mm after treatment. significant differences in taxa among the groups were sought using the kruskal-wallis and chi(2) tests. results: more species were detected in patients with disease (gr or rp) than in those without disease (ph). subjects with rp were distinguished from grs or those with ph by a significantly higher frequency of putative periodontal pathogens, such as parvimonas micra (previously peptostreptococcus micros or micromonas micros), campylobacter gracilis, eubacterium nodatum, selenomonas noxia, tannerella forsythia (previously t. forsythensis), porphyromonas gingivalis, prevotella spp., treponema spp., and eikenella corrodens, as well as unusual species (pseudoramibacter alactolyticus,  tm7 spp. oral taxon [ot] 346/356, bacteroidetes sp. ot 272/274, solobacterium moorei, desulfobulbus sp. ot 041, brevundimonas diminuta, sphaerocytophaga sp. ot 337, shuttleworthia satelles, filifactor alocis, dialister invisus/pneumosintes,  granulicatella adiacens, mogibacterium timidum, veillonella atypica, mycoplasma salivarium, synergistes sp. cluster ii, and acidaminococcaceae [g-1] sp. ot 132/150/155/148/135) (p <0.05). species that were more prevalent in subjects with ph than in patients with periodontitis included actinomyces sp. ot 170, actinomyces spp. cluster i, capnocytophaga sputigena, cardiobacterium hominis, haemophilus parainfluenzae, lautropia mirabilis, propionibacterium propionicum, rothia dentocariosa/mucilaginosa, and streptococcus sanguinis (p <0.05). conclusion: as determined by homim, patients with rp presented a distinct microbial profile compared to patients in the gr and ph groups.
TIHT== 
ABHT== 

PMID== 19416446
TI  == the microbiota on different oral surfaces in healthy children.
AB  == introduction: knowledge of the early oral colonization patterns could provide a better understanding of oral biofilm development and disease initiation that in turn could be the basis for early preventive programmes. methods: microbial samples were collected from five different oral habitats from a total of 93 children (age 3-12 years), attending the dental school of the university of athens, who were split into three age groups. a total of 38 microbial species were sought out by the checkerboard dna-dna hybridization technique. results: all of the test species, except parvimonas micra and porphyromonas gingivalis, differed significantly among sample locations providing quite distinct microbial  profiles for the different oral surfaces. supragingival and subgingival plaque had similar profiles and exhibited higher proportions of actinomyces species and  green complex while soft tissue samples were dominated by streptococci of the yellow complex. the profiles of the tongue dorsum and saliva were also similar. many of the species were in similar proportions in all three age groups for a given location. periodontal pathogens showed increases in proportions with increasing age. specifically, the red complex species (tannerella forsythia, p. gingivalis, treponema denticola) showed a significant increase in proportion with age (p < 0.05) in all sample locations. conclusions: the results showed a pattern of colonization in children similar to that previously found in adults. differences in the profile between age groups suggest a gradual maturation of the oral microbiota, with it being made up of an increasing number of orange and red  complex species.
TIHT== 
ABHT== 

PMID== 18547832
TI  == pcr-based identification of selected pathogens associated with endodontic infections in deciduous and permanent teeth.
AB  == objective: the aim of the present study was to evaluate the presence of the selected pathogens in samples from deciduous and permanent tooth root canals by using pcr method and to determine the association of these organisms with clinical symptoms. study design: a total of 145 children, 5 to 13 years old, were involved in this study. the presence of selected pathogens (actinomyces israelii, candida albicans, enterococcus faecalis, fusobacterium nucleatum, porphyromonas endodontalis, porphyromonas gingivalis, prevotella intermedia, streptococcus intermedius, treponema denticola, parvimonas micra, tannerella forsythensis, enterococcus faecium, prevotella melaninogenica) in infected root canals was studied using pcr. results: t. denticola (p = .012, .02) and e. faecalis (p = .012, .04) were highly associated with periapical radiolucency and previous pain, while p. gingivalis was associated with tenderness to percussion in both deciduous and permanent teeth (p = .01, .015). conclusion: the results of the present study confirm that certain species of microorganisms are associated with  clinical signs and symptoms of endodontic disease in both deciduous and permanent teeth.
TIHT== 
ABHT== 

PMID== 18081862
TI  == subgingival microbial profiles in chronic periodontitis patients from chile, colombia and spain.
AB  == aim: to investigate the subgingival microbiota of distinct periodontitis patient  populations, in chile, colombia and spain, using identical clinical and bacteriological methods. material and methods: in this multicentre study, 114 chronic periodontitis patients were selected. patients were examined using an identical clinical protocol and pooled subgingival samples were obtained from each patient. samples were processed in the three laboratories by means of culturing under identical clinical and microbiological protocols. total anaerobic counts and frequency of detection and proportions of nine periodontal pathogens were calculated. variables were analysed by means of anova, chi(2), kruskal-wallis and dunn's multiple comparison tests. results: the colombian population demonstrated greater severity of periodontitis, with significantly deeper mean probing pocket depth, and had a significantly lower percentage of current smokers. when comparing samples from the three patient populations, the total counts were significantly higher in the colombian patients. the numbers of  putative pathogens differed among groups. tannerella forsythia was found less frequently in chilean samples, while parvimonas micra and enteric rods differed significantly among the three population groups. conclusion: significant differences among chile, colombia and spain existed regarding the frequency and proportions of specific periodontal pathogens in the subgingival microbiota of periodontitis patients.
TIHT== 
ABHT== 

