@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 15316299
TI  == [coryneform bacteria: their clinical significance and resistance patterns during  a three-year study].
AB  == we report data concerning our experience during three years (1998-2001) about isolation, identification and susceptibility towards antimicrobial agents of coryneform bacteria in infections of hospitalized/at risk patients. we isolated 54 corynebacterium spp., with prevalence of c. striatum (8 strains) and c. amycolatum (7 strains), and 1 strain of oerskovia spp. and 1 strain of actinomyces neuii. 31 strains were isolated from the "exit-site" and 6 from peritoneal fluid of capd patients. vancomycin and teicoplanin were always "in vitro" efficacious. resistance rates towards other antibiotics were the following: 11% for minocycline, 12.5% for tetracycline, 20% for gentamicin and netilmicin, 61% for erythromycin and chloramphenicol, 66% for penicillin.
TIHT== 
ABHT== 

PMID== 12499210
TI  == in vitro activities of daptomycin, vancomycin, quinupristin- dalfopristin, linezolid, and five other antimicrobials against 307 gram-positive anaerobic and  31 corynebacterium clinical isolates.
AB  == the activities of daptomycin, a cyclic lipopeptide, and eight other agents were determined against 338 strains of gram-positive anaerobic bacteria and corynebacteria by the nccls reference agar dilution method with supplemented brucella agar for the anaerobes and mueller-hinton agar for the corynebacteria. the daptomycin mics determined on ca(2+)-supplemented (50 mg/liter) brucella agar plates were one- to fourfold lower than those determined in unsupplemented media. daptomycin was highly active (mics, <or=2 microg/ml) against many strains including 36 of 37 peptostreptococci, 37 of 48 isolates of the eubacterium group, and all strains of propionibacterium spp., clostridium perfringens, clostridium difficile, and other clostridium spp. it was fourfold or greater more active than vancomycin against clostridium innocuum and 16 of 34 strains of vancomycin-resistant lactobacilli. three strains of c. difficile for which quinupristin-dalfopristin and linezolid mics were >8 microg/ml were inhibited by  <1 microg of daptomycin per ml. daptomycin mics were >or=4 microg/ml for most strains of clostridium clostridioforme, clostridium paraputrificum, clostridium tertium, and clostridium ramosum; the isolates were generally more resistant to other antimicrobials. daptomycin was two- to fourfold less active against actinomyces spp. than vancomycin, quinupristin-dalfopristin, or linezolid. twenty-nine of 31 strains of corynebacterium spp., including corynebacterium jeikeium, corynebacterium amycolatum, and corynebacterium pseudodiphtheriticum, were inhibited by <or=0.25 microg of daptomycin per ml. for two strains of "corynebacterium aquaticum," 8 microg of daptomycin per ml was required for inhibition. daptomycin demonstrated very good activities against a broad range of gram-positive organisms including vancomycin-resistant c. innocuum and lactobacillus strains and quinupristin-dalfopristin- and linezolid-resistant c. difficile strains.
TIHT== 
ABHT== 

PMID== 9754261
TI  == [bacteriological and clinical aspects of corynebacterium].
AB  == the microbiologists use the term corynebacteria to describe aerobically growing,  asporogenous, irregularly sharped gram-positive rods. they comprise strictly aerobic bacteria isolated from environment as well as preferentially anaerobic bacteria found in clinical specimens. a large part of these bacteria is considered as commensal of skin and mucous membranes. this group of organisms has recently been subjected to considerable taxonomic revisions, which have resulted  in the proposal of several new species, many of them representing previous centers for diseases control coryneform groups. moreover, recent investigations demonstrated the existence of a pathogenic role for some of them. these bacteria  comprise well-known pathogens such as c. diphtheriae responsible for diphtheria,  actinomyces spp. responsible for actinomycosis and arcanobacterium haemolyticum recovered from pharyngitis, but other corynebacteria were related to particular infections. for example, the lipophilic and antibiotics multiresistant species corynebacterium urealyticum and c. jeikeium were found to be responsible for urinary tract infections and septicemias, respectively. the recently described species turicella otitidis was found to be implicated in otitis media and c. seminale were recovered from genital specimens of male patients. implantation of  material devices, use of broad-spectrum antibiotics led to an increase of sepsis  due to the species c. jeikeium and c. amycolatum. many of the new actinomyces species grow well under aerobic conditions and are often implicated in various abscesses. moreover an increase of immunocompromised patients led to the development of infections due to the aerobic actinomycete rhodococcus equi. the association of some corynebacteria with particular diseases should prompt the microbiologist to identify these bacteria when they are encountered in a pathogenic situation. identification of the major part of corynebacteria isolated from clinical specimens can now be achieved by using recent schemes.
TIHT== 
ABHT== 

