@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25380369
TI  == aerobic bacterial microbiota isolated from the cloaca of the european pond turtle (emys orbicularis) in poland.
AB  == we conducted a comparative analysis of the aerobic cloacal bacteria of european pond turtles (emys orbicularis) living in their natural environment and juvenile  turtles reared under controlled conditions in a breeding center. we included 130  turtles in the study. the aerobic bacteria isolated from the cloaca of the juvenile turtles were less diverse and more prevalent than the bacteria isolated  from free-living adults. we isolated 17 bacterial species from juvenile captive turtles, among which the dominant species were cellulomonas flavigena (77/96), enterococcus faecalis (96/96), escherichia coli (58/96), and proteus mirabilis (41/96). from the adult, free-living turtles, we isolated 36 bacterial species, some of which are a potential threat to public health (e.g., salmonella enterica  serovars newport, daytona, and braenderup; listeria monocytogenes; yersinia enterocolitica; yersinia ruckeri; klebsiella pneumoniae; vibrio fluvialis; and serratia marcescens), and pathogens that are etiologic agents of diseases of ectothermic animals (e.g., aeromonas sobria, aeromonas caviae, hafnia alvei, edwardsiella tarda, and citrobacter braakii; the last two species were isolated from both groups of animals). the cloacal bacterial biota of the european pond turtle was characterized by numerous species of bacteria, and its composition varied with turtle age and environmental conditions. the small number of isolated bacteria that are potential human pathogens may indicate that the european pond turtle is of relatively minor importance as a threat to public health.
TIHT== 
ABHT== 

PMID== 21771453
TI  == in vitro antibacterial effect of aqueous and ethanolic moringa leaf extracts.
AB  == objective: to evaluate the antibacterial effect of aqueous and ethanolic moringa  leaf extracts (moringa oleifera) on the growth of gram-positive and negative bacteria. methods: paper disks were soaked with 100, 200, 300 and 400 mul of extract at 20 g/180 ml and 10 g/190 ml. all extracts were tested against escherichia coli (atcc25922), staphylococcus aureus (atcc25923), vibrio parahaemolyticus, enterococcus faecalis (atcc29212), pseudomonas aeruginosa (atcc27853), salmonella enteritidis (ih) and aeromonas caviae. the susceptibility tests were performed using the modified disk diffusion method. results: the strains e. coli, p. aeruginosa and s. enteritidis (ih) were resistant to all treatments. in general, disks with 400 mul extract were the most efficient against s. aureus, v. parahaemolyticus, e. faecalis and a. caviae. conclusions: the study indicates a promising potential for aqueous and ethanolic moringa leaf  extracts as alternative treatment of infections caused by the tested strains.
TIHT== 
ABHT== 

PMID== 7989335
TI  == the vertebrate peptide antibiotics dermaseptins have overlapping structural features but target specific microorganisms.
AB  == the physiological significance of the occurrence of sequence similar antimicrobial peptides in frog skin, as the bombinins in bombina, the magainins in xenopus, and the dermaseptins in phyllomedusa, is a major unanswered question. dermaseptins s1, s2, s3, s4, and s5, a family of cationic (lysine-rich), amphipathic antifungal peptides of 28-34 residues were thus synthesized, purified to homogeneity, and evaluated for their growth-inhibition activity in vitro against various pathogenic microorganisms. although all five of these peptides shared a similar spectrum of lytic activity against the filamentous fungi that are responsible for opportunistic lethal infections that follow the immunodeficiency syndrome or the use of immunosuppressive agents, they exhibited  marked differences in their potencies to arrest the growth of gram-positive and gram-negative pathogenic bacteria and yeasts. likewise, whereas dermaseptins s1 and s5 were devoid of hemolytic activity, dermaseptin s4 caused lysis of erythrocytes at micromolar concentrations. the dermaseptins exhibited dramatic synergy of action upon combination, resulting in some cases in a 100-fold increase in antibiotic activity of the mixture over the activity of the peptides  separately. shortening the peptide chain of dermaseptin s3 to dermaseptin s3-(1-16)-nh2 did not affect the antimicrobial potency of the peptide. further reduction of the chain length yielded peptide derivatives gradually showing reduced activity. surprisingly, however, analogs of dermaseptin s3 as shorter as  10-12 residues in length remained fully active against enterococcus faecalis, cryptococcus neoformans, and against aeromonas caviae, the causal agent of red-leg disease in amphibians. overall, these results suggest that, despite 40% sequence similarities, the dermaseptins have distinct spectra of anti-microbial activity and may act in concert to circumvent host invasion by providing frogs with a better shielding against a broad array of microorganisms. they also demonstrate the potential usefulness of short analogs of these peptides as potential candidates for biorational design of germicides.
TIHT== 
ABHT== 

PMID== 2111407
TI  == effects of incorporating ampicillin, bile salts and carbohydrates in media on the recognition and selection of aeromonas spp. from faeces.
AB  == the effects of incorporating ampicillin, some bile salts and sugars into media on the primary recognition and selection of aeromonads from faeces were examined. most (88%) of the 101 aeromonas strains examined had an ampicillin mic of greater than or equal to 40 mg/l, and would be isolated on blood agar containing ampicillin 30 mg/l. the strains with an ampicillin mic of less than 40 mg/l were  all of human origin and predominantly a. caviae. although ampicillin at 10, 20 or 30 mg/l in blood agar inhibited faecal bacteria, the ability to detect aeromonas  strains with a high ampicillin mic was less when the lower concentrations of ampicillin were used, without any improvement in the isolation of those strains with a low ampicillin mic. thirty-seven strains were tested for sensitivity to several different bile salts and found to be at least as resistant to them as escherichia coli nctc 10418. bile salt sensitivity was not related to the species or source of a strain. there were minor differences in sensitivity to bile salts  between some strains which related to whether strains had been isolated originally in the presence of bile salt or not. the effects of the presence of e. coli, klebsiella spp. and enterococcus faecalis on the growth of aeromonas strains in mixed culture on media with and without carbohydrate were examined. the colony size of some aeromonas strains was reduced in mixed culture but colony counts were not affected with any aeromonas strains.(abstract truncated at 250 words)
TIHT== 
ABHT== 

