@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23671105
TI  == cross-talk between akkermansia muciniphila and intestinal epithelium controls diet-induced obesity.
AB  == obesity and type 2 diabetes are characterized by altered gut microbiota, inflammation, and gut barrier disruption. microbial composition and the mechanisms of interaction with the host that affect gut barrier function during obesity and type 2 diabetes have not been elucidated. we recently isolated akkermansia muciniphila, which is a mucin-degrading bacterium that resides in the mucus layer. the presence of this bacterium inversely correlates with body weight in rodents and humans. however, the precise physiological roles played by this bacterium during obesity and metabolic disorders are unknown. this study demonstrated that the abundance of a. muciniphila decreased in obese and type 2 diabetic mice. we also observed that prebiotic feeding normalized a. muciniphila  abundance, which correlated with an improved metabolic profile. in addition, we demonstrated that a. muciniphila treatment reversed high-fat diet-induced metabolic disorders, including fat-mass gain, metabolic endotoxemia, adipose tissue inflammation, and insulin resistance. a. muciniphila administration increased the intestinal levels of endocannabinoids that control inflammation, the gut barrier, and gut peptide secretion. finally, we demonstrated that all these effects required viable a. muciniphila because treatment with heat-killed cells did not improve the metabolic profile or the mucus layer thickness. in summary, this study provides substantial insight into the intricate mechanisms of bacterial (i.e., a. muciniphila) regulation of the cross-talk between the host and gut microbiota. these results also provide a rationale for the development of a treatment that uses this human mucus colonizer for the prevention or treatment  of obesity and its associated metabolic disorders.
TIHT== 
ABHT== 

PMID== 23538004
TI  == faecal levels of bifidobacterium and clostridium coccoides but not plasma lipopolysaccharide are inversely related to insulin and homa index in women.
AB  == background & aims: the abundance of specific microbes might be associated with plasma lipopolysaccharide and insulin levels. the aims were to quantify the abundance of specific microbes and plasma lps in females and assess their association with anthropometric, body composition and biochemical measurements. methods: seventeen lean (bmi 19-24.99 kg/m(2)) and fifteen obese females (bmi > 30 kg/m(2)) participated. anthropometry, body composition, food intake and biochemical analyses were assessed. bacterial groups in faeces were analysed by qpcr method. results: lactobacillus plantarum prevalence was higher (p = 0.005) and its counts tended to be higher in lean vs. obese group (p = 0.06). bifidobacterium genus, bifidobacterium longum, clostridium coccoides and clostridium leptum counts were higher in lean women (p < 0.05); prevalence and counts of akkermansia muciniphila tended to be higher in lean group (p = 0.09, p  = 0.06, respectively). plasma lps levels were similar between the study groups (p > 0.05). no association was found between lps and bacterial levels or insulin. bifidobacteria and c. coccoides counts were inversely associated with insulin and homa index. conclusions: abundance of specific microbes is distinct between obese and lean women, but is not associated with lps level. bifidobacterial and c. coccoides levels are associated with insulin sensitivity. these bacterial groups  may be capable of modulating insulin action.
TIHT== 
ABHT== 

PMID== 21904534
TI  == modulation of mucosal immune response, tolerance, and proliferation in mice colonized by the mucin-degrader akkermansia muciniphila.
AB  == epithelial cells of the mammalian intestine are covered with a mucus layer that prevents direct contact with intestinal microbes but also constitutes a substrate for mucus-degrading bacteria. to study the effect of mucus degradation on the host response, germ-free mice were colonized with akkermansia muciniphila. this anaerobic bacterium belonging to the verrucomicrobia is specialized in the degradation of mucin, the glycoprotein present in mucus, and found in high numbers in the intestinal tract of human and other mammalian species. efficient colonization of a. muciniphila was observed with highest numbers in the cecum, where most mucin is produced. in contrast, following colonization by lactobacillus plantarum, a facultative anaerobe belonging to the firmicutes that  ferments carbohydrates, similar cell-numbers were found at all intestinal sites.  whereas a. muciniphila was located closely associated with the intestinal cells,  l. plantarum was exclusively found in the lumen. the global transcriptional host  response was determined in intestinal biopsies and revealed a consistent, site-specific, and unique modulation of about 750 genes in mice colonized by a. muciniphila and over 1500 genes after colonization by l. plantarum. pathway reconstructions showed that colonization by a. muciniphila altered mucosal gene expression profiles toward increased expression of genes involved in immune responses and cell fate determination, while colonization by l. plantarum led to  up-regulation of lipid metabolism. these indicate that the colonizers induce host responses that are specific per intestinal location. in conclusion, we propose that a. muciniphila modulates pathways involved in establishing homeostasis for basal metabolism and immune tolerance toward commensal microbiota.
TIHT== 
ABHT== 

