@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25434931
TI  == altered microbiota associated with abnormal humoral immune responses to commensal organisms in enthesitis-related arthritis.
AB  == introduction: prior studies have established altered microbiota and immunologic reactivity to enteric commensal organisms in inflammatory bowel disease (ibd). since intestinal inflammation is present in a subset of patients with both pediatric and adult spondyloarthritis (spa), we hypothesized that spa patients may also have altered microbiota and immune responsiveness to enteric organisms.  methods: stool and blood specimens were collected from children with enthesitis-related arthritis (era) and non-inflammatory controls. dna purified from stool was subject to pcr amplification and sequencing of the variable iv region from the 16s rdna gene. iga and igg enzyme-linked immunosorbent assays (elisas) were performed on select species of bacteria in most subjects. results:  twenty-five children with era and 13 controls were included. the era patients had less faecalibacterium prausnitzii (3.8% versus 10%, p = 0.008) and lachnospiraceae family (12 versus 7.0%, p = 0.020), a statistically significant increase in bifidobacterium (1.8% versus 0%, p = 0.032) and a non-statistically significant increase in bacteroides (21% versus 11%, p = 0.150). akkermansia muciniphila was abundant (>2%) in 7/27 era patients but none of the controls (p = 0.072.) cluster analysis revealed two clusters of era patients: cluster one (n =  8) was characterized by high levels of bacteroides genus, while a second (n = 15) cluster had similar levels as the controls. seven of 17 (41%) of the era subjects in cluster 2 compared to 0/8 of the subjects in cluster 1 had abundant akkermansia muciniphila (p = 0.057). serum iga and igg antibody levels against f. prausnitzii and b. fragilis were similar between patients and controls, whereas the two groups showed divergent responses when the fecal relative abundances of f. prausnitzii and bacteroides were compared individually against iga antibody levels recognizing f. prausnitzii and b. fragilis, respectively. conclusion: the  abundance of f. prausnitzii in the stool among patients with era is reduced compared to controls, and bacteroides and a. muciniphila are identified as associative agents in subsets of era patients. differences in the humoral responses to these bacteria may contribute to disease.
TIHT== 
ABHT== 

