@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 17949342
TI  == evaluation of the microbiota of primary endodontic infections using checkerboard  dna-dna hybridization.
AB  == background/aims: the aim of this study was to evaluate the composition of the microbiota of primary endodontic infections in 111 selected cases of single-rooted teeth with necrotic pulp. methods: samples were collected from the  root canals using #15 hedstroen-type files and two sterile paper points, which were introduced 1 mm short of the apical foramen. the presence, levels, and proportions of 40 different bacterial species in each sample were determined using dna probes and checkerboard dna-dna hybridization techniques. results: the  mean number of species per sample was 22. enterococcus faecalis (89.3%), campylobacter gracilis (89.3%), leptotrichia buccalis (89.3%), neisseria mucosa (87.5%), prevotella melaninogenica (86.6%), fusobacterium nucleatum ssp. vincentii (85.7%), eubacterium saburreum (75.9%), streptococcus anginosus (75%),  and veillonella parvula (74.1%) were the most prevalent species. the species found in highest mean counts (over 10(5)) were f. nucleatum ssp. vincentii (13.14 x 10(5)), e. saburreum (5.67 x 10(5)), e. faecalis (5.38 x 10(5)), n. mucosa (4.19 x 10(5)), v. parvula (3.63 x 10(5)), c. gracilis (3.46 x 10(5)), treponema  socranskii (3.34 x 10(5)), porphyromonas endodontalis (2.96 x 10(5)), porphyromonas gingivalis (2.85 x 10(5)), micromonas micros (2.81 x 10(5)), prevotella nigrescens (2.68 x 10(5)) and fusobacterium nucleatum ssp. nucleatum (2.64 x 10(5)). most of these species were also found in high proportions. conclusions: our results suggest that several bacterial species considered to be  oral pathogens seem to be implicated in the etiology of primary endodontic infections.
TIHT== 
ABHT== 

PMID== 12877258
TI  == positive and negative bacterial associations involving dialister pneumosintes in  primary endodontic infections.
AB  == dialister pneumosintes is an anaerobic gram-negative rod that has been recently implicated as a candidate endodontic pathogen. in this study, samples taken from  abscessed teeth and infected root canals associated with asymptomatic or symptomatic periradicular lesions were examined for the occurrence of bacterial associations involving d. pneumosintes. dna was extracted from the samples, and the presence of d. pneumosintes and 16 other bacterial species was determined by  means of species-specific nested polymerase chain reaction. positive and negative associations involving d. pneumosintes were investigated by computing the odds ratio of d. pneumosintes being found in a sample from endodontic infection in co-infection with one of the other target species. the association between the pairs containing d. pneumosintes and the occurrence of pain also was evaluated. d. pneumosintes was always detected in mixed infections with at least two of the  other target species. d. pneumosintes was positively associated with treponema denticola, porphyromonas endodontalis, fusobacterium nucleatum, peptostreptococcus micros, campylobacter rectus, prevotella intermedia, t. pectinovorum, and t. vincentii. negative associations were observed with bacteroides forsythus, p. gingivalis, and actinomyces israelii. no pair containing d. pneumosintes was found to be significantly associated with symptomatic cases (p > 0.01). the findings of this study lend considerable support to the notion of d. pneumosintes being an important endodontic pathogen,  usually in a mixed infection. positive associations of this species with other highly prevalent species, such as t. denticola and p. endodontalis, suggest that  bacterial synergism can occur and thereby play an important role in the pathogenesis of different forms of periradicular lesions.
TIHT== 
ABHT== 

PMID== 11350499
TI  == relationship of cigarette smoking to the subgingival microbiota.
AB  == background: the relationship of cigarette smoking to the composition of the subgingival microbiota is not clear. some studies indicated higher levels of certain species in smokers, while other studies failed to detect differences in the microbiota between subjects with different smoking histories. thus, the purpose of the present investigation was to examine the prevalence, proportions and levels of the subgingival species in adult subjects who were current, past or never smokers. method: 272 adult subjects ranging in age from 20-86 years with at least 20 teeth were recruited for study. smoking history was obtained using a questionnaire. clinical measures were taken at 6 sites per tooth at all teeth excluding third molars at a baseline visit. subgingival plaque samples were taken from the mesial surface of all teeth excluding third molars in each subject at baseline and assayed individually for counts of 29 subgingival species using checkerboard dna-dna hybridization. subjects were subset according to smoking history into never (n=124), past (n=98) and current smokers (n=50). uni-variate and multi-variate analyses were used to seek associations between smoking category and the counts, proportions and prevalence of subgingival species. results: greater differences were observed for the prevalence (% of sites colonized) of the test species in the 3 smoking groups than were observed for counts or proportions of total counts. members of the orange and red complexes including e. nodatum, f. nucleatum ss vincentii, p. intermedia, p. micros, p. nigrescens, b. forsythus, p. gingivalis and t. denticola were significantly more  prevalent in current smokers than in the other 2 groups. the difference in prevalence between smokers and non-smokers was due to greater colonization at sites with pocket depth <4 mm. stepwise multiple linear regression analysis indicated that combinations of the prevalence of 5 microbial species and pack years accounted for 44% of the variance for mean pocket depth (p<0.000001), while the prevalence of 3 microbial taxa along with age, pack years, current smoking and gender accounted for 31% of the variance in mean attachment level (p<0.000001). the difference in prevalence between current and never smokers of all members of the red complex and 8 of 12 members of the orange complex was significantly greater in the maxilla than in the mandible. conclusions: the major difference between the subgingival microbiota in subjects with different smoking  history was in the prevalence of species rather than counts or proportions. the greater extent of colonization in smokers appeared to be due to greater colonization at pocket depths <4 mm. differences in colonization patterns between current and never smokers were greater in the maxilla than in the mandible.
TIHT== 
ABHT== 

