@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25666178
TI  == purification and identification of an antibacterial protein from the symbiotic bacteria associated with novel entomopathogenic nematode, rhabditis (oscheius) sp.
AB  == entomopathogenic nematodes (epn) belonging to the families steinernematidae and heterorhabditidae and their symbiotic bacteria xenorhabdus and photorhabdus are well-known as biological control agents and are found to produce a wide range of  bioactive secondary metabolites. studies carried out at the central tuber crops research institute (ctcri) on entomopathogenic nematodes resulted in the identification of novel epn belonging to the family rhabditidae. this study reports the purification of a high molecular weight antibacterial protein from culture filtrates of a bacterium (bacillus cereus) symbiotically associated with  a novel entomopathogenic nematode rhabditis (oscheius) species, maintained at ctcri laboratory. fermentation conditions were standardized and optimum antibacterial activity was observed in tryptic soy broth after 48 h incubation at 30 degrees c. the aqueous extracts yielded antibacterial proteins which were purified by ammonium sulfate precipitation followed by ion exchange chromatography and size exclusion chromatography. native gel electrophoresis indicated an active protein of molecular mass 220kda which resolved into a major  band of 90 kda and a minor band of about 40 kda on sds-page. the 90 kda protein showed antibacterial activity and was further analysed by maldi tof-ms/ms. the protein was identified as a tqxa (threonine-glutamine dipeptide) domain containing protein from bacillus cereus. the protein was found to be active against bacillus subtilis mtcc2756, staphylococus aureus mtcc902 and escherichia  coli mtcc 2622 and was thermally stable.
TIHT== 
ABHT== 

PMID== 24002058
TI  == yaxab, a yersinia enterocolitica pore-forming toxin regulated by rova.
AB  == the transcriptional regulator rova positively regulates transcription of the yersinia enterocolitica virulence gene inv. invasin, encoded by inv, is important for establishment of y. enterocolitica infection. however, a rova mutant is more  attenuated for virulence than an inv mutant, implying that rova regulates additional virulence genes. when the y. enterocolitica rova regulon was defined by microarray analysis, ye1984 and ye1985 were among the genes identified as being upregulated by rova. since these genes are homologous to xenorhabdus nematophila cytotoxin genes xaxa and xaxb, we named them yaxa and yaxb, respectively. in this work, we demonstrate the effects of yaxab on the course of  infection in the murine model. while a yaxab mutant (deltayaxab) is capable of colonizing mice at the same level as the wild type, it slightly delays the course of infection and results in differing pathology in the spleen. further, we found  that yaxab encode a probable cytotoxin capable of lysing mammalian cells, that both yaxa and yaxb are required for cytotoxic activity, and that the two proteins associate. yaxab-mediated cell death occurs via osmotic lysis through the formation of distinct membrane pores. in silico tertiary structural analysis identified predicted structural homology between yaxa and proteins in pore-forming toxin complexes from bacillus cereus (hbl-b) and escherichia coli (hlye). thus, it appears that yaxab function as virulence factors by inducing cell lysis through the formation of pores in the host cell membrane. this characterization of yaxab supports the hypothesis that rova regulates expression  of multiple virulence factors in y. enterocolitica.
TIHT== 
ABHT== 

