@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 12174052
TI  == characterization of a bacteriocin produced by a newly isolated bacillus sp. strain 8 a.
AB  == aims: the aim of this research was to investigate the production of bacteriocins  by bacillus spp. isolated from native soils of south of brazil. methods and results: a bacteriocin produced by the bacterium bacillus cereus 8 a was identified. the antimicrobial activity was produced starting at the exponential growth phase, although maximum activity was at stationary growth phase. a crude bacteriocin obtained from culture supernatant fluid was inhibitory to a broad range of indicator strains, including listeria monocytogenes, clostridium perfringens, and several species of bacillus. clinically relevant bacteria such as streptococcus bovis and micrococcus luteus were also inhibited. bacteriocin was stable at 80 degrees c, but the activity was lost when the temperature reached 87 degrees c. it was resistant to the proteolytic action of trypsin and papain, but sensitive to proteinase k and pronase e. bacteriocin activity was observed in the ph range of 6.0-9.0. conclusions: a bacteriocin produced by bacillus cereus 8 a was characterized, presenting a broad spectrum of activity and potential for use as biopreservative in food. significance and impact of study: the identification of a bacteriocin with large activity spectrum, including pathogens and spoilage microorganisms, addresses an important aspect of food safety.
TIHT== 
ABHT== 

PMID== 9266665
TI  == aspects of the pharmacokinetics of doxycycline given to healthy and pneumonic east african dwarf goats by intramuscular injection.
AB  == the effect of experimentally induced pasteurella haemolytica pneumonia on the pharmacokinetics of doxycycline (doxycen retard) administered intramuscularly was studied in seven east african dwarf goats. the study was conducted in two consecutive phases, separated by a washout period of four weeks. the experimental infection, induced by intratracheal administration of 5 ml of 10(7) to 10(9) cfu/ml of pasteurella haemolytica, produced a temperature rise, depression and laboured breathing within 6-12 days after inoculation. the concentrations of doxycycline in the serum were determined by a quantitative microbiological assay  using an agar-gel diffusion method employing bacillus cereus var mycoides (atcc 11778) as the test organism, with a level of detectability of approximately 0.05  micrograms/ml. the concentration-time curve of doxycycline in the serum after intramuscular injection of 20 mg/kg bodyweight of the long-acting formulation before and after experimental infection was adequately described by a one-compartment open model. the maximum serum concentrations (cmax) of doxycycline were lower in pneumonic goats than in healthy goats (3.87 +/- 0.52 and 5.56 +/- 0.213 micrograms/ml, respectively), suggesting an increased distribution volume in the peripheral compartment. the mean +/- sem absorption rate (ka) before infection (1.13 +/- 0.02 h-1) was smaller than the after infection (8.23 +/- 3.81 h-1), but the difference was not significant. the apparent elimination half-life (t 1/2 beta) (24.51 +/- 0.02 h) after infection was significantly increased (p < 0.05), while the corresponding rate constant (beta) was decreased (p < 0.01). the absorption half-life (t 1/2(alpha)) (0.137 +/- 0.03 h) was significantly decreased (p < 0.01) after infection. the distribution volume (vd(beta)) was significantly increased after infection (p < 0.05). it is concluded that, although experimental infection had an effect on the disposition kinetics of doxycycline, this was not sufficiently pronounced to require alteration of the dosage during disease.
TIHT== 
ABHT== 

