@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25559405
TI  == crosstalk between the microbiome and cancer cells by quorum sensing peptides.
AB  == to date, the precise role of the human microbiome in health and disease states remains largely undefined. complex and selective crosstalk systems between the microbiome and mammalian cells are also not yet reported. research up till now mainly focused on bacterial synthesis of virulence factors, reactive oxygen/nitrogen species (ros/rns) and hydrogen sulphide, as well as on the activation of exogenous mutagen precursors by intestinal bacteria. we discovered  that certain quorum sensing peptides, produced by bacteria, interact with mammalian cells, in casu cancer cells: phr0662 (bacillus sp.), entf-metabolite (enterococcus faecium) and edf-derived (escherichia coli) peptides initiate hct-8/e11 colon cancer cell invasion, with phr0662 also promoting angiogenesis. our findings thus indicate that the human microbiome, through their quorum sensing peptides, may be one of the factors responsible for cancer metastasis.
TIHT== 
ABHT== 

PMID== 24571273
TI  == spiromastixones a-o, antibacterial chlorodepsidones from a deep-sea-derived spiromastix sp. fungus.
AB  == fifteen new depsidone-based analogues named spiromastixones a-o (1-15) were isolated from the fermentation broth of a deep-sea spiromastix sp. fungus. their  structures were elucidated on the basis of extensive nmr and mass spectroscopic analysis in association with chemical conversion. spiromastixones a-o are classified into two subtypes based on the orientation of ring c relative to ring  a, while the n-propyl substituents on rings a and c are rarely seen in natural products. most analogues are substituted by various numbers of chlorine atoms. all compounds exhibited significant inhibition against gram-positive bacteria including staphylococcus aureus, bacillus thuringiensis, and bacillus subtilis with mic values ranging from 0.125 to 8.0 mug/ml. in addition, compounds 6-10 displayed potent inhibitory effects against methicillin-resistant bacterial strains of s. aureus (mrsa) and s. epidermidis (mrse), while 10 also inhibited the growth of the vancomycin-resistant bacteria enterococcus faecalis and e. faecium (vre). the structure-activity relationships are discussed.
TIHT== 
ABHT== 

PMID== 23952642
TI  == effects of dietary supplementation of bacillus amyloliquefaciens cect 5940 and enterococcus faecium cect 4515 in adult healthy dogs.
AB  == the aim of this study was to evaluate the effect of a probiotic preparation consisting of two probiotic strains, bacillus amyloliquefaciens cect 5940 and enterococcus faecium cect 4515 (each 5 . 10(8) cfu/g feed), on faecal consistency, faecal microbiology and nutrient digestibility in adult healthy dogs. sixteen beagles (eight males and eight females) were divided into two groups: the control group (con), which was fed the basal diet, and the probiotic  group (pro), which received the basal diet supplemented daily with 1 . 10(8) cfu  for 39 consecutive days. faecal score was assessed before (bs) and throughout the supplementation period (sp). fresh faecal samples were collected before supplementation, before finishing the supplementation period and after 6 days of  withdrawal for microbial enumeration and ph measurement. during the supplementation period, a digestibility trial was performed. there were no differences in faecal scores or the digestibility coefficients between groups. between groups no statistical differences were found in most microbiota analysed  or in faecal ph. however, during the supplementation period, pathogenic clostridia dropped significantly in group pro (5.64 vs. 2.94 +/- 0.53 cfu/g faeces; p < 0.001), when compared with the period bs. the use of the probiotic preparation had no impact on nutrient digestibility by adult healthy dogs; however, it could stabilise faecal microbiota by decreasing pathogenic clostridia.
TIHT== 
ABHT== 

PMID== 23678816
TI  == a new antimicrobial and anticancer peptide producing by the marine deep sediment  strain "paenibacillus profundus" sp. nov. sl 79.
AB  == a new linear glyceryl acid derived heptapeptide (1), together with known isocoumarin antibiotic, y-05460m-a (2), were isolated from the culture of the deep sea sediment strain si 79 classified as "paenibacillus profundus" sp. nov. their structures were determined by 1d- and 2d- nmr techniques and esi-ms/ms experiments. hplc analysis of the marfey derivatives in comparison to their analogs of authentic amino acids revealed that all amino acids in peptide 1, with an exception of val, have the d-configuration. the compound 1 showed inhibitory activity against staphylococcus aureus, staphylococcus epidermidis, bacillus subtilis, enterococcus faecium as well as cytotoxic and moderate colony growth inhibitory activity against sk-mel-28 cell line.
TIHT== 
ABHT== 

PMID== 20696489
TI  == bacterial species associated with traditional starter cultures used for fermented bamboo shoot production in manipur state of india.
AB  == soidon is a non-salted acidic fermented food prepared from the succulent bamboo shoot tip of schizostachyum capitatum munro by using a traditional liquid starter called "soidon mahi" in manipur state of india. in this study, 163 bacterial isolates associated with this starter samples were identified and their population distribution was investigated by amplified ribosomal dna restriction analysis (ardra), 16s rdna sequencing and randomly amplified polymorphic dna (rapd) analysis. this acidic starter (ph 4.5+/-0.15) was dominated by a characteristic association of bacillus and lactic acid bacteria (lab) together. the population distribution of dominant species were bacillus subtilis 29.3%, bacillus cereus 35.7%, bacillus pumilus 2.6%, lactobacillus brevis 9.6%, lactobacillus plantarum 5.1%, carnobacterium sp. 11.9%, enterococcus faecium 1.2% and pseudomonas fluorescens 4.6%. alarming population load (10(6)-10(7)cfu/ml) of b. cereus in 87% of starter samples studied should raise concern regarding biosafety of soidon consumption. pcr amplification of 16s-23s rdna intergenic transcribed spacer (its) region and its-rflp profiles revealed a high diversity with eight subgroups in b. subtilis, five subgroups in b. cereus and three subgroups in l. brevis isolates. the most abundant b. subtilis subgroup ib.1 distributed in most of the samples showed very less clonal variability during rapd analysis. the molecular methods used in this study identified the dominant strains of bacillus and lab distributed in most of the starter samples. these dominant strains of b. subtilis, l. brevis and l. plantarum would allow for developing a defined starter culture for the production of quality soidon.
TIHT== 
ABHT== 

PMID== 20688411
TI  == microorganisms associated with maari, a baobab seed fermented product.
AB  == a microbiological study was carried out on baobab fermented seeds (maari) obtained from 4 different production sites in burkina faso (mansila, toulfe, ouagadougou and gorgadji). a total of 390 representative isolates comprising 251  aerobic mesophilic bacteria (amb) and 139 lactic acid bacteria (lab) were isolated and identified to species level using a combination of pheno- and genotypic methods including conventional morphological analysis, carbohydrate fermentation profiling, rep-pcr ((gtg)(5)-fingerprinting) and 16s rrna gene sequencing. the fermentation of baobab seeds was initiated by the amb identified  as bacillus subtilis (82% of amb isolates) and staphylococcus sciuri (18% of amb  isolates). no lactic acid bacteria were isolated at the beginning of the process. after 24h fermentation time, enterococcus faecium appeared in the fermenting seeds and remained until the end of the fermentation, as the predominant lab. in  maari collected from retail outlets the amb count ranged from 6.7log10cfu/g to 10log10cfu/g while the lab load ranged from 4.4log10cfu/g to 9.9log10cfu/g. the amb were identified as belonging to genus bacillus (12 species), staphylococcus (3 species) and one species of aerococcus, macrococcus, leifsonia, kurthia, proteus, acinetobacter and globicatella, respectively. a putatively novel, previously undescribed corynebacterium sp. was also found. e. faecium was the dominant lab in all investigated retail samples except one sample dominated by pediococcus acidilactici.
TIHT== 
ABHT== 

PMID== 20600863
TI  == isolation, characterization and phylogeny of sponge-associated bacteria with antimicrobial activities from brazil.
AB  == bacteria associated with marine sponges represent a rich source of bioactive metabolites. the aim of this study was to isolate and characterize bacteria with  antimicrobial activities from brazilian sponges. a total of 158 colony-forming units were isolated from nine sponge species. among these, 12 isolates presented  antimicrobial activities against pathogenic bacteria. based on comparative sequence analysis of their 16s rrna genes, the sponge-associated bacterial strains could be subdivided into three phylogenetically different clusters. five  strains were affiliated with firmicutes (genera bacillus and virgibacillus), three with alpha-proteobacteria (pseudovibrio sp.) and four with gamma-proteobacteria (genera pseudomonas and stenotrophomonas). the sponge-associated bacterial strains pseudomonas fluorescens h40 and h41 and pseudomonas aeruginosa h51 exhibited antimicrobial activity against both gram-negative and gram-positive bacteria, including strains such as vancomycin-resistant enterococcus faecium and multiresistant klebsiella pneumoniae. bacillus pumilus pc31 and pc32, pseudovibrio ascidiaceicola pm31 and  ca31 and pseudovibrio denitrificans mm37 strains were more effective against gram-positive bacteria. these findings suggest that the identified strains may contribute to the search for new sources of antimicrobial substances, an important strategy for developing alternative therapies to treat infections caused by multidrug-resistant bacteria.
TIHT== 
ABHT== 

PMID== 24031466
TI  == antimicrobial activity of enterococcus faecium fair-e 198 against gram-positive pathogens.
AB  == this study investigated the antimicrobial activity of enterococcus faecium fair-e 198 against bacillus cereus, listeria monocytogenes and staphylococcus aureus. using the critical-dilution method, the bacteriocin produced by e. faecium fair-e 198 inhibited all l. monocytogenes strains evaluated (1,600 to 19,200 au ml(-1)). however, none of the b. cereus and s. aureus strains investigated were inhibited. the maximum activity of this bacteriocin (800 au ml(-1)) was observed in mrs broth, while the activity in milk was 100 au ml(-1). in the co-cultivation test in milk, b. cereus k1-b041 was reduced to below the detection limit (1.00 log cfu ml(-1)) after 48 h. e. faecium reduced the initial l. monocytogenes scott a population by 1 log cfu ml(-1) after 3 h at 35 degrees c, however, the pathogen regained growth, reaching 3.68 log cfu ml(-1) after 48 h. e. faecium did not influence the growth of s. aureus atcc 27154 during the 48 h of co-cultivation, therefore, it can be concluded that the effectiveness of the antimicrobial activity of e. faecium fair-e 198 is strictly related to the species and strain of the target microorganism and to the culture medium.
TIHT== 
ABHT== 

PMID== 19957209
TI  == antilisterial activity of a broad-spectrum bacteriocin, enterocin lr/6 from enterococcus faecium lr/6.
AB  == enterocin lr/6, a purified bacteriocin, exhibited broad inhibitory spectrum both  against related as well as some food-borne pathogens such as listeria monocytogenes, yersinia enterocolitica, aeromonas sp., shigella sp., and bacillus licheniformis. in this investigation, we have focused on l. monocytogenes as the  target organism, as it is not only an important pathogen but can also survive over a wide range of environmental conditions such as refrigeration temperature,  low ph, and high-salt concentration. this allows the pathogen to overcome many food preservation and safety barriers and poses a potential risk to human health. the enterocin lr/6 showed a bactericidal action against l. monocytogenes and completely inhibited the growth on agar plates, supplemented with 200 au/ml of enterocin lr/6. the effectiveness of enterocin lr/6 in completely killing a population of acid-adapted (ph 5.2, 2 h) l. monocytogenes exposed to different temperatures (4-37 degrees c), ph (2.5-8.0), and osmotic (up to 30% nacl) stress  is reported here. this paper focuses on the key issue of killing of the acid-adapted l. monocytogenes cells under adverse environmental conditions.
TIHT== 
ABHT== 

PMID== 14982790
TI  == interactions between penicillin-binding proteins (pbps) and two novel classes of  pbp inhibitors, arylalkylidene rhodanines and arylalkylidene iminothiazolidin-4-ones.
AB  == several non-beta-lactam compounds were active against various gram-positive and gram-negative bacterial strains. the mics of arylalkylidene rhodanines and arylalkylidene iminothiazolidin-4-ones were lower than those of ampicillin and cefotaxime for methicillin-resistant staphylococcus aureus mi339 and vancomycin-resistant enterococcus faecium ef12. several compounds were found to inhibit the cell wall synthesis of s. aureus and the last two steps of peptidoglycan biosynthesis catalyzed by ether-treated cells of escherichia coli or cell wall membrane preparations of bacillus megaterium. the effects of the arylalkylidene rhodanines and arylalkylidene iminothiazolidin-4-one derivatives on e. coli pbp 3 and pbp 5, streptococcus pneumoniae pbp 2xs (pbp 2x from a penicillin-sensitive strain) and pbp 2xr (pbp 2x from a penicillin-resistant strain), low-affinity pbp 2a of s. aureus, and the actinomadura sp. strain r39 and streptomyces sp. strain r61 dd-peptidases were studied. some of the compounds exhibited inhibitory activities in the 10 to 100 microm concentration range. the  inhibition of pbp 2xs by several of them appeared to be noncompetitive. the dissociation constant for the best inhibitor (ki = 10 microm) was not influenced  by the presence of the substrate.
TIHT== 
ABHT== 

PMID== 12588562
TI  == partial characterization of bacteriocins produced by environmental strain enterococcus faecium ek13.
AB  == aims: the partial characterization of bacteriocins produced by an environmental strain enterococcus faecium ek13, isolated from cattle dung water. methods and results: a bacteriocin was partially purified by ammonium sulphate precipitation, followed by a sp-sepharose column, reverse-phase chromatography and n-terminal region sequenced. the anti-microbial substance produced was found to be a heat-stable polypeptide with molecular mass 4.83 kda, which was determined by n-terminal amino acid sequencing to be enterocin a. a second substance was specified by pcr as enterocin p. bacteriocins were stable at 4 and -20 degrees c  for long storage periods. the optimum of bacteriocin production was observed in the range of ph 5.0-6.5 at 30 and 37 degrees c. the most active substances are produced by strain ek13 in logarithmic growth phase and bacteriocins are produced after 1 h of fermentation. the highest activity detected in fermentation experiments was 51 200 au ml(-1) and the most sensitive indicator strain was found to be listeria innocua lmg 13568. differences in bacteriocin activity against two indicators could be explained by more than one type of enterocin production by strain ek13, or with different mode of action or in different sensitivity of strains. conclusion: enterococcus faecium strain ek13 isolated from cattle dung water produces two bacteriocins, enterocin a and p, with an inhibitory effect against the strain of the genera enterococcus, leuconostoc, lactobacillus, streptococcus, staphylococcus, bacillus and listeria (in different origin). significance and impact of the study: enterococcus faecium ek13 environmental strain is a new producer of enterocin a and p. the e. faecium ek13, isolated from cattle dung water, is presented with the further aim to utilize it  for waste treatment by biotechnological processes.
TIHT== 
ABHT== 

PMID== 11966910
TI  == widespread distribution of the bacteriocin-producing lactic acid cocci in miso-paste products.
AB  == aims: a survey was conducted on the ecological distribution of bacteriocin-producing lactic acid bacteria in miso-pastes, a typical fermented food in japan. methods and results nine miso-pastes were sampled for isolation of bacteriocin-producers. almost all isolated enterococcal strains produced bacteriocins but no isolated tetragenococci did so. the bacteriocin-producing isolates were divided into nine groups by phenotypic tests. as the phenotypic characters were highly diverse, these strains could not be identified to species  level on the basis of their phenotypes. the nine representative strains from each group were identified by 16s rrna analysis. these bacteriocin-producers with one  exception (lactococcus sp.) were identified as strains of the enterococcus faecium 'species group'. the bacteriocins of the nine strains were classified into five types according to their antibacterial spectral patterns and their sds-page profiles. the bacteriocins inhibited undesirable bacteria in miso-pastes, such as bacillus subtilis, but did not inhibit the useful tetragenococcus halophila. conclusions: the bacteriocin-producing lactic acid cocci were widespread at high frequencies in miso-pastes. they were considered to play an important role in preventing the growth of undesirable bacteria. significance and impact of the study: this study suggests that bacteriocin-producers act effectively as safe biopreservatives and may contribute to the biopreservation in miso-pastes.
TIHT== 
ABHT== 

PMID== 11302155
TI  == isolation and characterization of enterocin se-k4 produced by thermophilic enterococci, enterococcus faecalis k-4.
AB  == enterococcus sp. k-4, with a bacteriocin-like activity against e. faecium, was isolated from grass silage in thailand. morphological, physiological, and phylogenetic studies clearly identified strain k-4 as a strain of e. faecalis. strain k-4 produced a maximal amount of bacteriocin at 43-45 degrees c. we purified, for the first time, the bacteriocin produced at high temperature by e.  faecalis to homogeneity, using adsorption on cells of the producer strain and reversed-phase liquid chromatography. the bacteriocin, designated enterocin se-k4, is a peptide of about 5 kda as measured by sds-page, and mass spectrometry analysis found the molecular mass of 5356.2, which is in good agreement. the amino acid sequencing of the n-terminal end of enterocin se-k4 showed apparent sequence similarity to class iia bacteriocins. enterocin se-k4 was active against e. faecium, e. faecalis, bacillus subtilis, clostridium beijerinckii, and listeria monocytogenes. enterocin se-k4 is very heat stable.
TIHT== 
ABHT== 

PMID== 11152243
TI  == synthesis and antimicrobial activity of new adamantane derivatives ii.
AB  == a series of new derivatives of adamantane was synthesised. the new compound 4-(adamant-1-ylethylenoxycarbonyl)phthalanhydride obtained from 1-adamantaneethanol and trimellitic anhydride chloride, as well as 4-(adamant-1-ylmethylenoxycarbonyl)phthalanhydride, appeared very useful for preparation of a number of n-substituted phthalimides. antimicrobial activity of  newly obtained derivatives such as, for example, 4-(adamant-1-ylethylenoxycarbonyl)-n-(l-phenylalanyl)phthalimide or 4-(adamant-1-ylmethylenoxycarbonyl)-n-(l-leucyl)-phthalimide was tested against staphylococcus aureus, bacillus sp., micrococcus flavus and enterococcus faecium. the minimal inhibitory concentrations for these compounds against bacillus cereus were 15 and 8 microg/ml, respectively.
TIHT== 
ABHT== 

PMID== 10961681
TI  == synthesis and antimicrobial activity of new adamantane derivatives i.
AB  == a series of fourteen derivatives of adamantane was synthesised. the new compound  4-(adamant-1-ylmethoxycarbonyl)phthalanhydride obtained from 1-adamantane-methanol and trimellitic anhydride chloride appeared very useful for preparation of a number of n-substituted phthalimides. antimicrobial activity of  the newly obtained derivatives such as, for example, 4-(adamant-1-ylmethoxycarbonyl)-n-(5-carboxypentamethylene)p hthalimide or 4-(adamant-1-ylmethoxycarbonyl)-n-(l-alanyl)phthalimide was tested against staphylococcus aureus, bacillus sp., micrococcus flavus and enterococcus faecium. the minimal inhibitory concentration (mic) for these compounds against s. aureus  were 0.022 and 0.05 microg/ml, respectively.
TIHT== 
ABHT== 

PMID== 10349723
TI  == the influence of bacterial inoculants on the microbial ecology of aerobic spoilage of barley silage.
AB  == the aerobic decomposition of barley silage treated with two inoculants (laca and  lacb) containing mixtures of lactobacillus plantarum and enterococcus faecium was investigated over a 28-day period. initially, yeast and bacterial populations were larger in silage inoculated with laca than in silage treated with lacb or water alone (control). differences in the succession of yeasts in silage treated  with laca were observed relative to the other two treatments. from silage treatment with laca, issatchenkia orientalis was the most prevalent yeast taxon over all of the sample times, and the filamentous fungus microascus brevicaulis was also frequently isolated at later sample dates (> or = 14 days). in contrast, saccharomyces exiguus was the most prominent yeast recovered from silage treated  with lacb and water alone on days 2 and 4, although it was supplanted by i. orientalis at later sample times. successional trends of bacteria were similar for all three treatments. lactobacillus spp. were initially the most prevalent bacteria isolated, followed by bacillus spp. (primarily bacillus pumilus). however, the onset of bacillus spp. prominence was faster in laca silage, and klebsiella planticola was frequently recovered at later sample times (> or = 14 days). more filamentous fungi were recovered from laca silage on media containing carboxylmethylcellulose, pectin, or xylan. the most commonly isolated taxa were absidia sp., aspergillus flavus, aspergillus fumigatus, byssochlamys nivea, monascus ruber, penicillium brevicompactum, pseudoallescheria boydii, and m. brevicaulis. the results of this study indicated that the two bacterial inoculants incorporated into barley at the time of ensilage affected the microbial ecology of silage decomposition following exposure to air. however, neither of the microbial inoculants effectively delayed aerobic spoilage of barley silage, and the rate of decomposition of silage treated with one of the inoculants (laca) was actually enhanced.
TIHT== 
ABHT== 

PMID== 7501585
TI  == in vitro fructooligosaccharide utilization and inhibition of salmonella spp. by selected bacteria.
AB  == in vitro experiments were conducted to determine: 1) inhibitory capacities of potential direct-fed microbial bacteria against salmonella serotypes; and 2) the  ability of bifidobacterium bifidum, enterococcus faecium, lactobacillus casei, lactococcus lactis, pediococcus sp., and salmonella spp. to grow in media containing fructooligosaccharides (fos-50 or fos pure formulation) as the only carbohydrate source. thirteen bacteria (two strains of bacillus coagulans, bacillus licheniformis, bacillus subtilis, b. bifidum, e. faecium, two strains of lactobacillus acidophilus, l. casei, pediococcus sp., propionibacterium acidopropionici, p. jensenii, and propionibacterium sp.) were tested for inhibition of six salmonella serotypes (s. california, s. enteritidis, s. heidelberg, s. mission, s. senftenberg, and s. typhimurium) using a spot-the-lawn technique. bifidobacterium bifidum, e. faecium, all lactobacilli, and pediococcus sp. clearly inhibited growth of all salmonella serotypes. in the growth experiments, e. faecium, l. lactis, and pediococcus sp. grew in media with either fos-50 or the pure formulation of fos as the sole carbohydrate source. all tested salmonella serotypes utilized fos-50 for growth; however growth varied among the  serotypes. in contrast, none of the salmonella serotypes grew in media containing the pure formulation of fos as the only carbohydrate source.
TIHT== 
ABHT== 

PMID== 24420029
TI  == bacillus fermentation of soybeans.
AB  == kinema fermentations of indian and canadian no. 1 soybeans by bacillus sp. dk-w1  and by mixed cultures of bacillus sp. dk-w1 and enterococcus faecium dk-c1 were essentially identical. the viable cell count of bacillus increased from an initial 10(5) to 10(10) c.f.u./g wet wt after 48 h incubation at 37 degrees c. the ph of the fermentation dropped from an initial 6.9 to about 6.4 after 8 h and then rose to 8.6 after 32 h, with a coincident increase in proteolytic activity and ammonia concentration. the fermentations containing e. faecium and bacillus exhibited a greater initial ph decline and a slightly retarded subseqent increase in ph compared with fermentations with bacillus only. the presence of e. faecium  had no detectable effects on growth of the bacillus, proteolytic activity, ammonia production or the final ph of the fermentations.
TIHT== 
ABHT== 

