@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 19053926
TI  == microbiological findings in subjects with asymptomatic oral lichen planus: a cross-sectional comparative study.
AB  == background: the bacterial colonization of the oral mucosa was evaluated in patients with asymptomatic oral lichen planus (olp) and compared to the microbiologic status in mucosally healthy subjects. methods: bacteria from patients with clinically and histopathologically diagnosed olp from the stomatology service, department of oral surgery and stomatology, school of dental medicine, university of bern, were collected with a non-invasive swab system. samples were taken from olp lesions on the gingiva and from non-affected sites on the contralateral side of the mouth. the control population did not have olp and  was recruited from the student clinic. all samples were processed with the checkerboard dna-dna hybridization method using well-defined bacterial species for the analysis. results: significantly higher bacterial counts of bacteroides ureolyticus (p = 0.001), dialister species (sp.) (p = 0.006), staphylococcus haemolyticus (p = 0.007), and streptococcus agalactiae (p = 0.006) were found in  samples taken from olp lesions compared to sites with no clinical evidence of olp. significantly higher bacterial counts were found for capnocytophaga sputigena, eikenella corrodens, lactobacillus crispatus, mobiluncus curtisii, neisseria mucosa, prevotella bivia, prevotella intermedia, and s. agalactiae at sites with lesions in subjects with olp compared to sites in control subjects (p  <0.001). conclusions: microbiologic differences were found between sites with olp and sites in subjects without a diagnosis of olp. specifically, higher counts of  staphylococci and s. agalactiae were found in olp lesions.
TIHT== 
ABHT== 

PMID== 18422583
TI  == microbiological evaluation of primary endodontic infections in teeth with and without sinus tract.
AB  == aim: to examine the microbiological status of primary endodontic infections in teeth with and without a sinus tract. methodology: samples were collected by means of a size 15 h-type file and two sterile paper points from 30 cases of primary endodontic infections with (n = 15) or without (n = 15) a sinus tract. the presence of 40 bacterial species was determined by the checkerboard dna-dna hybridization method. results: the species found at the highest levels and prevalence were fusobacterium nucleatum sp. vincentii, porphyromonas gingivalis,  veillonella parvula, enterococcus faecalis, campylobacter gracilis and neisseria  mucosa. total bacterial counts were similar between teeth with (44 x 10(5)) and without (50 x 10(5)) a sinus tract (t-test: p > 0.05). e. faecalis, streptococcus anginosus, capnocytophaga sputigena and capnocytophaga gingivalis had significantly higher counts in the absence of sinus tract (mann-whitney test, p < 0.05). higher levels of p. gingivalis and fusobacterium nucleatum sp. nucleatum were observed in cases with a sinus tract. leptotrichia buccalis (or = 1.83; ci 95%) and porphyromonas endodontalis (or = 2.15; ci 95%) were associated with an increased chance of subjects having a sinus tract. conclusions: primary endodontic infections were associated with a large variety of bacterial species.  specific differences between the composition of the microbiota of primary root canal infections were observed in cases with or without a sinus tract.
TIHT== 
ABHT== 

