@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25946126
TI  == oral microbiota shift after 12-week supplementation with lactobacillus reuteri dsm 17938 and pta 5289; a randomized control trial.
AB  == background: lactobacillus spp. potentially contribute to health by modulating bacterial biofilm formation, but their effects on the overall oral microbiota remain unclear. methods and findings: oral microbiota was characterized via 454-pyrosequencing of the 16s rdna hypervariable region v3-v4 after 12 weeks of daily lactobacillus reuteri dsm 17938 and pta 5289 consumption. forty-four adults were assigned to a test group (n = 22) that received lactobacilli lozenges (108 cfu of each strain/lozenge) or a control group that received placebo (n = 22). presence of l. reuteri was confirmed by cultivation and species specific pcr. tooth biofilm samples from 16 adults before, during, and after exposure were analyzed by pyrosequencing. a total of 1,310,292 sequences were quality filtered. after removing single reads, 257 species or phylotypes were identified at 98.5% identity in the human oral microbiome database. firmicutes, bacteroidetes, fusobacteria, proteobacteria, and actinobacteria were the most abundant phyla. streptococcus was the most common genus and the s. oralis/s. mitis/s. mitis bv2/s. infantis group comprised the dominant species. the number of observed species was unaffected by l. reuteri exposure. however, subjects who had consumed l. reuteri were clustered in a principal coordinates analysis relative to scattering at baseline, and multivariate modeling of pyrosequencing microbiota, and culture and pcr detected l. reuteri separated baseline from 12-week samples in test subjects. l. reuteri intake correlated with increased s. oralis/s. mitis/s. mitis bv2/s. infantis group and campylobacter concisus, granulicatella adiacens, bergeyella sp. hot322, neisseria subflava, and sr1 [g-1] sp. hot874 detection and reduced s. mutans, s. anginosus, n. mucosa, fusobacterium periodicum, f. nucleatum ss vincentii, and prevotella maculosa detection. this effect had disappeared 1 month after exposure was terminated. conclusions: l. reuteri consumption did not affect species richness but induced a shift in the oral microbiota composition. the biological relevance of this remains to be elucidated. trial registration: clinicaltrials.gov nct02311218.
TIHT== 
ABHT== 

PMID== 24972711
TI  == development of an in vitro periodontal biofilm model for assessing antimicrobial  and host modulatory effects of bioactive molecules.
AB  == background: inflammation within the oral cavity occurs due to dysregulation between microbial biofilms and the host response. understanding how different oral hygiene products influence inflammatory properties is important for the development of new products. therefore, creation of a robust host-pathogen biofilm platform capable of evaluating novel oral healthcare compounds is an attractive option. we therefore devised a multi-species biofilm co-culture model  to evaluate the naturally derived polyphenol resveratrol (rsv) and gold standard  chlorhexidine (chx) with respect to anti-biofilm and anti-inflammatory properties. methods: an in vitro multi-species biofilm containing s. mitis, f. nucleatum, p. gingivalis and a. actinomycetemcomitans was created to represent a  disease-associated biofilm and the oral epithelial cell in okf6-tert2. cytotoxicity studies were performed using rsv and chx. multi-species biofilms were either treated with either molecule, or alternatively epithelial cells were  treated with these prior to biofilm co-culture. biofilm composition was evaluated and inflammatory responses quantified at a transcriptional and protein level. results: chx was toxic to epithelial cells and multi-species biofilms at concentrations ranging from 0.01-0.2%. rsv did not effect multi-species biofilm composition, but was toxic to epithelial cells at concentrations greater than 0.01%. in co-culture, chx-treated biofilms resulted in down regulation of the inflammatory chemokine il-8 at both mrna and protein level. rsv-treated epithelial cells in co-culture were down-regulated in the release of il-8 protein, but not mrna. conclusions: chx possesses potent bactericidal properties, which may impact downstream inflammatory mediators. rsv does not appear to have bactericidal properties against multi-species biofilms, however it did appear to  supress epithelial cells from releasing inflammatory mediators. this study demonstrates the potential to understand the mechanisms by which different oral hygiene products may influence gingival inflammation, thereby validating the use  of a biofilm co-culture model.
TIHT== 
ABHT== 

PMID== 24866802
TI  == the periodontal pathogen porphyromonas gingivalis induces expression of transposases and cell death of streptococcus mitis in a biofilm model.
AB  == oral microbial communities are extremely complex biofilms with high numbers of bacterial species interacting with each other (and the host) to maintain homeostasis of the system. disturbance in the oral microbiome homeostasis can lead to either caries or periodontitis, two of the most common human diseases. periodontitis is a polymicrobial disease caused by the coordinated action of a complex microbial community, which results in inflammation of tissues that support the teeth. it is the most common cause of tooth loss among adults in the  united states, and recent studies have suggested that it may increase the risk for systemic conditions such as cardiovascular diseases. in a recent series of papers, hajishengallis and coworkers proposed the idea of the "keystone-pathogen" where low-abundance microbial pathogens (porphyromonas gingivalis) can orchestrate inflammatory disease by turning a benign microbial community into a dysbiotic one. the exact mechanisms by which these pathogens reorganize the healthy oral microbiome are still unknown. in the present manuscript, we present  results demonstrating that p. gingivalis induces s. mitis death and dna fragmentation in an in vitro biofilm system. moreover, we report here the induction of expression of multiple transposases in a streptococcus mitis biofilm when the periodontopathogen p. gingivalis is present. based on these results, we  hypothesize that p. gingivalis induces s. mitis cell death by an unknown mechanism, shaping the oral microbiome to its advantage.
TIHT== 
ABHT== 

PMID== 24288439
TI  == the influence of oral bacteria on epithelial cell migration in vitro.
AB  == oral ulcerations often arise as a side effect from chemo- and radiation therapy.  in a previous clinical study, porphyromonas gingivalis was identified as a positive predictor for oral ulcerations after hematopoetic stem cell transplantation, possibly incriminating p. gingivalis in delayed healing of the ulcerations. therefore, it was tested whether p. gingivalis and its secreted products could inhibit the migration of oral epithelial cells in an in vitro scratch assay. to compare, the oral bacteria prevotella nigrescens, prevotella intermedia, tannerella forsythia, and streptococcus mitis were included. a standardized scratch was made in a confluent layer of human oral epithelial cells. the epithelial cells were challenged with bacterial cells and with medium  containing secretions of these bacteria. closure of the scratch was measured after 17 h using a phase contrast microscope. p. gingivalis, p. nigrescens, and secretions of p. gingivalis strongly inhibited cell migration. a challenge with 1000 heat-killed bacteria versus 1 epithelial cell resulted in a relative closure of the scratch of 25% for p. gingivalis and 20% for p. nigrescens. weaker inhibitory effects were found for the other bacteria. the results confirmed our hypothesis that the oral bacteria may be involved in delayed wound healing.
TIHT== 
ABHT== 

PMID== 24080530
TI  == a tissue-dependent hypothesis of dental caries.
AB  == current understanding of dental caries considers this disease a demineralization  of the tooth tissues due to the acid produced by sugar-fermenting microorganisms. thus, caries is considered a diet- and ph-dependent process. we present here the  first metagenomic analysis of the bacterial communities present at different stages of caries development, with the aim of determining whether the bacterial composition and biochemical profile are specific to the tissue affected. the data show that microbial composition at the initial, enamel-affecting stage of caries  is significantly different from that found at subsequent stages, as well as from  dental plaque of sound tooth surfaces. although the relative proportion of streptococcus mutans increased from 0.12% in dental plaque to 0.72% in enamel caries, streptococcus mitis and streptococcus sanguinis were the dominant streptococci in these lesions. the functional profile of caries-associated bacterial communities indicates that genes involved in acid stress tolerance and  dietary sugar fermentation are overrepresented only at the initial stage (enamel  caries), whereas other genes coding for osmotic stress tolerance as well as collagenases and other proteases enabling dentin degradation are significantly overrepresented in dentin cavities. the results support a scenario in which ph and diet are determinants of the disease during the degradation of enamel, but in dentin caries lesions not only acidogenic but also proteolytic bacteria are involved. we propose that caries disease is a process of varying etiology, in which acid-producing bacteria are the vehicle to penetrate enamel and allow dentin degrading microorganisms to expand the cavity.
TIHT== 
ABHT== 

PMID== 23714165
TI  == the cultivable human oral gluten-degrading microbiome and its potential implications in coeliac disease and gluten sensitivity.
AB  == coeliac disease is characterized by intestinal inflammation caused by gluten, proteins which are widely contained in the western diet. mammalian digestive enzymes are only partly capable of cleaving gluten, and fragments remain that induce toxic responses in patients with coeliac disease. we found that the oral microbiome is a novel and rich source of gluten-degrading organisms. here we report on the isolation and characterization of the cultivable resident oral microbes that are capable of cleaving gluten, with special emphasis on the immunogenic domains. bacteria were obtained by a selective culturing approach and enzyme activities were characterized by: (i) hydrolysis of paranitroanilide-derivatized gliadin-derived tripeptide substrates; (ii) gliadin  degradation in-gel (gliadin zymography); (iii) gliadin degradation in solution; (iv) proteolysis of the highly immunogenic alpha-gliadin-derived 33-mer peptide.  for selected strains ph activity profiles were determined. the culturing strategy yielded 87 aerobic and 63 anaerobic strains. species with activity in at least two of the four assays were typed as: rothia mucilaginosa hot-681, rothia aeria hot-188, actinomyces odontolyticus hot-701, streptococcus mitis hot-677, streptococcus sp. hot-071, neisseria mucosa hot-682 and capnocytophaga sputigena  hot-775, with rothia species being active in all four assays. cleavage specificities and substrate preferences differed among the strains identified. the approximate molecular weights of the enzymes were ~75 kd (rothia spp.), ~60 kd (a. odontolyticus) and ~150 kd (streptococcus spp.). in conclusion, this study identified new gluten-degrading microorganisms in the upper gastrointestinal tract. a cocktail of the most active oral bacteria, or their isolated enzymes, may offer promising new treatment modalities for coeliac disease.
TIHT== 
ABHT== 

PMID== 22939371
TI  == assessing the oral microbiota of healthy and alcohol-treated rats using whole-genome dna probes from human bacteria.
AB  == objective: this study aimed to evaluate the capacity of whole-genome dna probes prepared from human oral bacteria to cross-react with bacteria from the oral cavity of rats, and to assess the influence of alcohol ingestion on the animals'  oral biofilm. design: twenty four mature wistar rats were equally divided in two  groups. one group (control) was fed balanced diet of rat pellets and water. the alcohol-treated group (at) received the same diet and 20% ethanol solution. upon  euthanasia after 30 days, bacterial samples from the oral biofilm covering the animals' teeth were collected using microbrushes. bacteria identification and quantification were performed using the dna checkerboard hybridization method with 33 probes prepared from human oral bacteria. signals corresponding to bacterial genome counts and percentages were compared using a mann-whitney u test with a significance level <0.05. results: cross-reaction for all targeted species, except streptococcus mutans and streptococcus mitis-like species, occurred in the control group. escherichia coli, pseudomonas aeruginosa, porphyromonas endodontalis, and veillonella parvula-like species only produced detectable signals in the at group. significantly more signals were detected in the control group compared to the at group (p=0.001). the percentage of e. coli-like species was highest in both groups. conclusions: whole-genome dna probes prepared from human oral bacteria can cross-react with rats' oral bacterial species. alcohol consumption is associated with lower levels and diversity of bacterial species in the oral cavity of rats.
TIHT== 
ABHT== 

PMID== 22520388
TI  == using high throughput sequencing to explore the biodiversity in oral bacterial communities.
AB  == high throughput sequencing of 16s ribosomal rna gene amplicons is a cost-effective method for characterization of oral bacterial communities. however, before undertaking large-scale studies, it is necessary to understand the technique-associated limitations and intrinsic variability of the oral ecosystem. in this work we evaluated bias in species representation using an in vitro-assembled mock community of oral bacteria. we then characterized the bacterial communities in saliva and buccal mucosa of five healthy subjects to investigate the power of high throughput sequencing in revealing their diversity  and biogeography patterns. mock community analysis showed primer and dna isolation biases and an overestimation of diversity that was reduced after eliminating singleton operational taxonomic units (otus). sequencing of salivary  and mucosal communities found a total of 455 otus (0.3% dissimilarity) with only  78 of these present in all subjects. we demonstrate that this variability was partly the result of incomplete richness coverage even at great sequencing depths, and so comparing communities by their structure was more effective than comparisons based solely on membership. with respect to oral biogeography, we found inter-subject variability in community structure was lower than site differences between salivary and mucosal communities within subjects. these differences were evident at very low sequencing depths and were mostly caused by  the abundance of streptococcus mitis and gemella haemolysans in mucosa. in summary, we present an experimental and data analysis framework that will facilitate design and interpretation of pyrosequencing-based studies. despite challenges associated with this technique, we demonstrate its power for evaluation of oral diversity and biogeography patterns.
TIHT== 
ABHT== 

PMID== 22443543
TI  == comparison of microbial changes in early redeveloping biofilms on natural teeth and dentures.
AB  == background: surfaces and fluids can affect oral bacterial colonization. the aim of this study is to compare redeveloping biofilms on natural teeth and dentures.  methods: supragingival plaque samples were taken from 55 dentate individuals and  the denture teeth of 62 edentulous individuals before and after professional cleaning. also, samples from seven "teeth" (samples included dentures) in randomly selected quadrants were collected after 1, 2, 4, and 7 days of no oral hygiene. samples were analyzed using checkerboard dna-dna hybridization. counts and proportions of 41 bacterial taxa were determined at each time point, and significant differences were determined using the mann-whitney u test. ecological succession was determined using a modified moving window analysis. results: mean  total dna probe counts were similar precleaning but were higher in dentate individuals at all post-cleaning visits (p <0.01). precleaning edentate biofilms  had higher counts and proportions of streptococcus mitis, streptococcus oralis, and streptococcus mutans, whereas dentate individuals had higher proportions of tannerella forsythia, selenomonas noxia, and neisseria mucosa. by day 2, mean counts of all taxa were higher in natural teeth, and most remained higher at day  7 (p <0.01). succession was more rapid and complex in dentate individuals. both groups demonstrated increased proportions of s. mitis and s. oralis by day 1. n.  mucosa, veillonella parvula, and eikenella corrodens increased in both groups, but later in samples from edentate individuals. conclusions: "mature" natural and denture teeth biofilms have similar total numbers of bacteria but different species proportions. post-cleaning biofilm redevelopment is more rapid and more complex on natural teeth than on denture teeth.
TIHT== 
ABHT== 

PMID== 22182466
TI  == surface properties of titanium and zirconia dental implant materials and their effect on bacterial adhesion.
AB  == objectives: zirconia ceramic material has been widely used in implant dentistry.  in this in vitro study the physiochemical properties of titanium and zirconia materials were investigated and the affinity of different bacteria to different materials was compared. methods: disc samples with different surface states were  used: polished partially stabilized zirconia (pz), titanium blasted with zirconia (tbz), titanium blasted with zirconia then acid etched (tbza), and polished titanium (pt) as a control. surface topography was examined using scanning electron microscopy and profilometry. contact angle, surface free energy (sfe), surface microhardness and chemical composition were determined. disc samples were separately incubated with streptococcus mitis and prevotella nigrescens, either with or without pre-coating with human saliva, for 6h and the surface area covered by bacteria was calculated from fluorescence microscope images. results:  pz and tbz exhibited lower surface free energy and lesser surface wettability than pt. also, pz and tbz surfaces showed lower percentage of bacterial adhesion  compared with control pt surface. conclusions: the zirconia material and titanium blasted with zirconia surface (tbz surface) showed superior effect to titanium material in reducing the adhesion of the experimented bacteria especially after coating with saliva pellicle. modifying titanium with zirconia lead to have the same surface properties of pure zirconia material in reducing bacterial adhesion. sfe appears to be the most important factors that determine initial bacterial adhesion to smooth surface.
TIHT== 
ABHT== 

PMID== 21895662
TI  == early microbial succession in redeveloping dental biofilms in periodontal health  and disease.
AB  == background and objective: the development of dental biofilms after professional plaque removal is very rapid. however, it is not clear whether most bacterial species return at similar rates in periodontally healthy and periodontitis subjects or if there are differences in bacterial recolonization between supragingival and subgingival biofilms in periodontal health and disease. material and methods: supragingival and subgingival plaque samples were taken separately from 28 teeth in 38 healthy and 17 periodontitis subjects immediately  after professional cleaning. samples were taken again from seven teeth in randomly selected quadrants after 1, 2, 4 and 7 d of no oral hygiene and analyzed using checkerboard dna-dna hybridization. the percentage of dna probe counts were averaged within subjects at each time-point. ecological succession was determined using a modified moving-window analysis. results: succession in supragingival biofilms from subjects with periodontitis and from healthy individuals was similar. at 1 d, streptococcus mitis and neisseria mucosa showed increased proportions, followed by capnocytophaga gingivalis, eikenella corrodens, veillonella parvula and streptococcus oralis at 1-4 d. at 4-7 d, campylobacter rectus, campylobacter showae, prevotella melaninogenica and prevotella nigrescens became elevated. subgingival plaque redevelopment was slower and very different from supragingival plaque redevelopment. increased proportions were first observed for s. mitis, followed by v. parvula and c. gingivalis and, at 7 d, by capnocytophaga sputigena and p. nigrescens. no significant increase in the proportions of periodontal pathogens was observed in any of the clinical groups or locations. conclusion: there is a defined order in bacterial species succession in early supragingival and subgingival biofilm redevelopment after professional cleaning.
TIHT== 
ABHT== 

PMID== 21401748
TI  == prunus mume extract exhibits antimicrobial activity against pathogenic oral bacteria.
AB  == objectives: prunus mume is a common fruit in asia, which has been used in traditional chinese medicine. in this study, we focused on the antimicrobial properties of prunus mume extract against oral pathogens related to dental caries and periodontal diseases. study design: a total of 15 oral pathogens including streptococcus mutans, s. sobrinus, s. mitis, s. sanguinis, lactobacillus acidophilus, p. gingivalis, aggregatibacter actinomycetemcomitans, and candida species were included in the study. initially, agar diffusion assay was performed to screen the antimicrobial activities of prunus mume extract. minimum inhibitory concentration (mic) and minimum bactericidal concentration (mbc) were then determined for sensitive species. effect of prunus mume extract on human oral keratinocytes (hok) viability was also tested. result: in the agar diffusion assay, drug suspension of 2 g/ml was able to inhibit all the bacterial species tested, but not the fungal species. mic and mbc range of prunus mume extract against the oral bacteria was 0.15625-0.0003 g/ml and p. gingivalis being the most susceptible species. prune extract did not cause any detrimental effect on hok. conclusion: prunus mume extract may be a potential candidate for developing  an oral antimicrobial agent to control or prevent dental diseases associated with oral pathogenic bacteria.
TIHT== 
ABHT== 

PMID== 20955352
TI  == oxygen tension modulates the cytokine response of oral epithelium to periodontal  bacteria.
AB  == background: there is an inverse relationship between pocket depth and pocket oxygen tension with deep pockets being associated with anaerobic bacteria. however, little is known about how the host tissues respond to bacteria under differing oxygen tensions within the periodontal pocket. aim: to investigate the  effect of different oxygen tensions upon nuclear factor-kappa b (nf-kappab) activation and the inflammatory cytokine response of oral epithelial cells when exposed to nine species of oral bacteria. materials and methods: h400 oral epithelial cells were equilibrated at 2%, 10% or 21% oxygen. cells were stimulated with heat-killed oral bacteria at multiplicity of infection 10:1, escherichia coli lipopolysaccharide (15 mug/ml) or vehicle control. interleukin-8 (il-8) and tumour necrosis factor-alpha (tnf-alpha) levels were measured by enzyme-linked immunosorbent assay and nf-kappab activation was measured by reporter vector or by immunohistochemical analysis. results: tannerella forsythensis, porphyromonas gingivalis and prevotella intermedia elicited the greatest epithelial nf-kappab activation and cytokine responses. an oxygen-tension-dependent trend in cytokine production was observed with the highest il-8 and tnf-alpha production observed at 2% oxygen and lowest at 21% oxygen. conclusions: these data demonstrate a greater pro-inflammatory host response and cell signalling response to bacteria present in more anaerobic conditions, and hypersensitivity of epithelial cells to pro-inflammatory stimuli  at 2% oxygen, which may have implications for disease pathogenesis and/or therapy.
TIHT== 
ABHT== 

PMID== 20881394
TI  == amplification of minute amounts of oral bacterial dna for real-time quantitative  pcr analysis.
AB  == background: high-throughput technologies for typing caries or health-associated bacterial populations including pcr, dna microarrays and next-generation sequencing techniques require significant amounts of bacterial dna. in clinical settings, the amount of sampled dna is often limited and amplification is therefore essential. protocols should be able to reproducibly amplify sequences in order to maintain initial sequence ratios and should not bias the representation of particular dna sequence types. methods: a linear amplification  protocol using dna polymerase i was modified to permit the amplification and subsequent analysis of small amounts of bacterial dna. the protocol was tested on human oral bacterial biofilms from different sources, including carious dentine and plaque, and compared to amplification by degenerate pcr of 16s rdna sequences. real-time quantitative pcr of 24 bacterial species was used as a readout system to test amplified dna against unamplified dna. results: the amplification protocol reliably yielded 5-10 mug dna from as little as 12.5 ng of template dna. correlation coefficients between real-time quantitative pcr results from amplified and unamplified dna were between 0.78 and 0.98. conclusion: the optimized protocol consistently produced amplification products from minute amounts of bacterial dna from caries and plaque; the amplification products are suitable for downstream genetic analyses.
TIHT== 
ABHT== 

PMID== 20555421
TI  == mechanisms of oral bacteria-induced platelet activation.
AB  == the oral cavity is inhabited by over 500 different bacterial species that normally exist in ecological balance both with each other and with the host. when this equilibrium is disturbed, an overgrowth of individual organisms can occur, which, in turn, can lead to the onset of pathological processes, notably dental caries and periodontitis. generally, bacteraemias occur more frequently in individuals with periodontal disease, and these bacteraemias have been implicated in the development of a range of systemic diseases, including atherothrombotic disorders. the mechanism underlying this relationship remains to be precisely defined, although studies have shown a link between bacteria of oral origin and platelet activation. several orally derived species of bacteria interact with platelets, including those of the streptococcus (streptococcus sanguinis, streptococcus mutans, streptococcus agalactiae, streptococcus pyogenes, streptococcus gordonii, streptococcus pneumoniae, streptococcus mitis) and staphylococcus (staphylococcus epidermidis, staphylococcus capitis) genera, as well as pseudomonas aeruginosa and porphyromonas gingivalis. in addition, some members of both the streptococcus and the staphylococcus genera, as well as porphyromonas gingivalis, can activate platelets in vitro. the current review describes the heterogeneous mechanisms of platelet activation employed by individual bacterial species. the pathological and clinical implications of platelet activation by orally derived bacteria are discussed.
TIHT== 
ABHT== 

PMID== 20418062
TI  == antimicrobial activity of chinese medicine herbs against common bacteria in oral  biofilm. a pilot study.
AB  == twenty traditional chinese medicines (tcm) were evaluated for their antimicrobial activity against four common oral bacteria. tcms were tested for sensitivity against streptococcus mitis, streptococcus sanguis, streptococcus mutans and porphyromonas gingivalis. aliquots of suspension of each bacterial species were inoculated onto a horse blood agar plate with tcms soaked separately on 6mm paper disks. the plates were incubated for 48h anaerobically and the mean diameters of  growth inhibition of three different areas obtained. 0.2% (w/v) chlorhexidine was used as a positive control. broth microdilution assay was used to determine minimum inhibitory concentration and minimum bactericidal concentration. fructus  armeniaca mume was effective against all four bacteria. thirteen tcms demonstrated antimicrobial activity against porphyromonas gingivalis, including cortex magnoliae officinalis, cortex phellodendri, flos caryophylli, flos lonicerae japonicae, fructus armeniaca mume, fructus forsythiae suspensae, herba  cum radice violae yedoensitis, herba menthae haplocalycis, pericarpium granati, radix et rhizoma rhei, radix gentianae, ramulus cinnamomi cassia and rhizoma cimicifugae. cortex phellodendri showed antimicrobial activity against streptococcus mutans, while radix et rhizoma rhei was effective against streptococcus mitis and streptococcus sanguis. fructus armeniaca mume had inhibitory effects against streptococcus mitis, streptococcus sanguis, streptococcus mutans and porphyromonas gingivalis in vitro.
TIHT== 
ABHT== 

PMID== 19416446
TI  == the microbiota on different oral surfaces in healthy children.
AB  == introduction: knowledge of the early oral colonization patterns could provide a better understanding of oral biofilm development and disease initiation that in turn could be the basis for early preventive programmes. methods: microbial samples were collected from five different oral habitats from a total of 93 children (age 3-12 years), attending the dental school of the university of athens, who were split into three age groups. a total of 38 microbial species were sought out by the checkerboard dna-dna hybridization technique. results: all of the test species, except parvimonas micra and porphyromonas gingivalis, differed significantly among sample locations providing quite distinct microbial  profiles for the different oral surfaces. supragingival and subgingival plaque had similar profiles and exhibited higher proportions of actinomyces species and  green complex while soft tissue samples were dominated by streptococci of the yellow complex. the profiles of the tongue dorsum and saliva were also similar. many of the species were in similar proportions in all three age groups for a given location. periodontal pathogens showed increases in proportions with increasing age. specifically, the red complex species (tannerella forsythia, p. gingivalis, treponema denticola) showed a significant increase in proportion with age (p < 0.05) in all sample locations. conclusions: the results showed a pattern of colonization in children similar to that previously found in adults. differences in the profile between age groups suggest a gradual maturation of the oral microbiota, with it being made up of an increasing number of orange and red  complex species.
TIHT== 
ABHT== 

PMID== 18942189
TI  == streptococcus cristatus attenuates fusobacterium nucleatum-induced interleukin-8  expression in oral epithelial cells.
AB  == background and objective: oral epithelial cells may be invaded by a polymicrobial intracellular flora, including pathogens together with commensals. various oral pathogens can induce the production of interleukin-8, a potent neutrophil chemotractant, in oral epithelial cells. evidence from the gut suggests that commensal species may modulate inflammatory responses to pathogens. the aim of this study was to examine the interleukin-8 responses of oral epithelial cells to an oral pro-inflammatory species, fusobacterium nucleatum, in combination with an oral commensal, streptococcus cristatus. material and methods: kb, tert-2, tr146  and scc15 cells were cocultured with f. nucleatum and s. cristatus, either alone  or in combination, at 37 degrees c in 5% co2 under various conditions. the mrna expression of interleukin-8 was analyzed by reverse transcription-polymerase chain reaction and protein secretion was measured by enzyme-linked immunosorbent  assay. results: f. nucleatum alone evoked a potent interleukin-8 response, whereas s. cristatus alone did not induce significant interleukin-8 expression in oral epithelial cells. when present together, s. cristatus attenuated the f. nucleatum-induced interleukin-8 production in the four oral epithelial cell lines to varying degrees. the inhibitory effect of s. cristatus was independent of its  viability and its co-aggregation with f. nucleatum, was not related to soluble bacterial products and appeared to require bacterial contact with epithelial cells. similar effects were seen with several other species of oral streptococci. conclusion: our data suggest that s. cristatus may exert immunomodulatory effects on the interleukin-8 response of oral epithelial cells to f. nucleatum challenge.
TIHT== 
ABHT== 

PMID== 18477431
TI  == assessment of the microbiota in root canals of human primary teeth by checkerboard dna-dna hybridization.
AB  == purpose: the purpose of this study was to evaluate in vivo the prevalence of microorganisms in root canals of human primary teeth, by checkerboard dna-dna hybridization. methods: fifty-five root canals of primary teeth with irreversible pulpitis (group 1) and 51 root canals of teeth with pulp necrosis and apical periodontitis (group 2) were selected. microbiological samples were collected and submitted to checkerboard dna-dna hybridization using 34 genomic dna probes. the  results were analyzed statistically by mann-whitney u-test at a 5% significance level. results: the most prevalent species in group 1 were: (1) campylobacter rectus (87%); (2) gemella morbilorum (78%); (3) streptococcus gordonii (71%); (4) capnocytophaga ochracea (69%); (5) treponema denticola (58%); and (6) streptococcus intermedius (49%). the most prevalent species in group 2 were: (1)  c. rectus (90%); (2) t. denticola (88%); (3) s. intermedius (77%); (4) g. morbilorum (73%); (5) streptococcus oralis (67%); (6) c. ochracea (63%); (7) s. gordonii (55%); (8) streptococcus mitis (51%); and (9) leptotrichia buccalis (51%). except for peptostreptococcus micros and actinomyces israelii, the most prevalent bacterial strains in the root canals with apical periodontitis were also those found in larger numbers (p<.05). groups 1 and 2 differed significantly (p<.05) regarding the total number of bacterial cells detected in the root canal  samples, with group 2 showing remarkably larger bacterial cell numbers. conclusions: root canals of primary teeth have a great bacterial diversity, characterizing a polymicrobial endodontic infection with presence of: (1) anaerobic and facultative micro organisms; (2) black-pigmented rods; and (3) streptococci. a large number of anaerobic species were detected in teeth with necrotic pulp and apical periodontitis, and a significantly smaller number of bacterial cells were found in teeth with irreversible pulpitis.
TIHT== 
ABHT== 

PMID== 18173797
TI  == reduction of periodontal pathogens adhesion by antagonistic strains.
AB  == introduction: periodontitis results from a shift in the subgingival microflora into a more pathogenic direction with porphyromonas gingivalis, prevotella intermedia, and actinobacillus actinomycetemcomitans considered as periodontopathogens. in many cases, treatment procures only a temporary shift towards a less pathogenic microflora. an alternative treatment could be the deliberate colonization of pockets with antagonistic microorganisms to control the adhesion of periodontopathogens. the aim of this study was to identify bacterial strains that reduce adhesion of periodontopathogens to surfaces. methods: streptococcus sanguinis, streptococcus crista, streptococcus salivarius, streptococcus mitis, actinomyces naeslundii, and haemophilus parainfluenzae were  evaluated as potential antagonists against p. gingivalis atcc 33277, p. intermedia atcc 49046, and a. actinomycetemcomitans atcc 43718 as periodontopathogens. adhesion of periodontopathogens to the bottom plate of a parallel plate flow chamber was studied in the absence (control) and the presence of pre-adhering antagonistic strains up to a surface coverage of 5%. results: the largest reduction caused by antagonistic strains was observed for p. gingivalis.  all antagonistic strains except s. crista atcc 49999 inhibited the adhesion of p. gingivalis by at least 1.6 cells per adhering antagonist, with the largest significant reduction observed for a. naeslundii atcc 51655 (3.8 cells per adhering antagonist). adhering antagonists had a minimal effect on the adhesion of a. actinomycetemcomitans atcc 43718. intermediate but significant reductions were perceived for p. intermedia, most notably caused by s. mitis bms. conclusion: the adhesion of p. gingivalis was inhibited best by antagonistic strains, while s. mitis bms appeared to be the most successful antagonist.
TIHT== 
ABHT== 

PMID== 17600533
TI  == bacterial diversity in aphthous ulcers.
AB  == introduction: recurrent aphthous ulcers are common lesions of the oral mucosa of  which the etiology is unknown. this study aimed to estimate the bacterial diversity in the lesions and in control mucosa in pooled samples using a culture-independent molecular approach. methods: samples were collected from ten  healthy individuals and ten individuals with a clinical history of recurrent aphthous ulcers. after dna extraction, the 16s ribosomal rna bacterial gene was amplified by polymerase chain reaction with universal primers; amplicons were cloned, sequenced and matched to the genbank database. results: a total of 535 clones were analyzed, defining 95 bacterial species. we identified 62 putative novel phylotypes. in recurrent aphthous ulcer lesions 57 phylotypes were detected, of which 11 were known species. control samples had 38 phylotypes, five of which were already known. only three species or phylotypes were abundant and common to both groups (gemella haemolysans, streptococcus mitis strain 209 and streptococcus pneumoniae r6). one genus was found only in recurrent aphthous ulcer samples (prevotella) corresponding to 16% of all lesion-derived clones. conclusion: the microbiota found in recurrent aphthous ulcers and in the control  groups diverged markedly and the rich variety of genera found can provide a new starting point for individual qualitative and quantitative analyses of bacteria associated with this oral condition.
TIHT== 
ABHT== 

PMID== 16907740
TI  == expression of the short fimbriae of porphyromonas gingivalis is regulated in oral bacterial consortia.
AB  == the mfa1 protein of porphyromonas gingivalis is the structural subunit of the short fimbriae and mediates coadhesion between p. gingivalis and streptococcus gordonii. we utilized a promoter-lacz reporter construct to examine the regulation of mfa1 expression in consortia with common oral plaque bacteria. promoter activity of mfa1 was inhibited by s. gordonii, streptococcus sanguinis and streptococcus mitis. in contrast, streptococcus mutans, streptococcus cristatus, actinomyces naeslundii, actinobacillus actinomycetemcomitans and fusobacterium nucleatum did not affect mfa1 expression. expression of sspa/b, the streptococcal receptor for mfa1, was not required for regulation of mfa1 promoter activity. proteinaceous molecule(s) in oral streptococci may be responsible for regulation of mfa1 expression. porphyromonas gingivalis is capable of detecting heterologous organisms, and responds to selected organisms by specific gene regulation.
TIHT== 
ABHT== 

PMID== 16475455
TI  == effect of a stannous fluoride dentifrice on the sulcular microbiota: a prospective cohort study in subjects with various levels of periodontal inflammation.
AB  == objectives: to assess the effects of an experimental 0.454% stannous fluoride (snf2) dentifrice on the oral sulcular microbiota in patients with various stages of oral diseases using checkerboard dna-dna hybridization. material and methods:  in the present one-month, single center, single product, prospective cohort trial, 37 adults (mean age 37.6) were assigned to one of four oral health condition cohorts with seven to 10 subjects each: 1. mild gingivitis, 2. marked generalized gingivitis to moderate periodontitis, 3. caries-prone and 4. treated  moderate to advanced chronic periodontitis in supportive periodontal care. all four groups were asked to use the test dentifrice and a power toothbrush twice a  day for one minute during a four-week test period. before and after the trial period, plaque indices (pii, silness and loe, 1964) and gingival indices (gi, loe and silness, 1963) were recorded. subgingival plaque samples were collected from  all patients at baseline, as well as after two and four weeks. these samples were analyzed for content of 40 bacterial species using checkerboard dna-dna hybridization. results: as a result of the only one minute brushing with the stannous fluoride dentifrice, the mean pii at baseline was significantly lower (p < 0.05) from the mean pii at four weeks. no statistically significant differences were found between premolar and molar mean values. moreover, no statistically significant differences were found between the mean gi at baseline and at four weeks. the microbiological analysis showed that at baseline subjects in groups 2  and 4 had significantly higher bacterial loads of bacteria than groups 1, and 3 (i.e. a. actinomyctemcomitans p. gingivalis, t. forsythia, and t. denticola. over the study period, the total bacterial load did not change in groups 2, 3 and 4. in groups 1 and 3, however, an increase in the loads of streptococci spp. were noticed (p < 0.05) including s. mitis, s. intermedius, and s. sanguis (p < 0.01)  suggesting an increase in the presence of early colonizing and health associated  bacteria. conclusion: one minute brushing with a 0.454% stannous fluoride dentifrice did--after four weeks--not affect the subgingival microbial profiles in patients with moderate periodontitis and treated moderate to advanced periodontitis. however, the sulcular microbial profiles of mild gingivitis and caries-prone patients were affected, indicating a shift towards a gingival health associated microbiota in the sulcular region of patients not affected by attachment loss. running head: effect of stannous fluoride on sulcular microbiota.
TIHT== 
ABHT== 

PMID== 16390334
TI  == commensal oral bacteria antigens prime human dendritic cells to induce th1, th2 or treg differentiation.
AB  == in various immunopathologic conditions, bacterial flora induce an immune response which results in inflammatory manifestations, e.g. periapical granuloma. dendritic cells provide the main orchestration of specific immune responses. the  aim of our study was to test the capacity of distinct oral bacterial antigens (prepared from streptococcus mitis, propionibacterium acnes, and bacteroides spp.) to prime human dendritic cells for stimulation of the t-lymphocyte response. to assess the t-lymphocyte response, the expression of cd25, cd69, intracellular interferon gamma (cifn-gamma), and intracellular interleukin 4 (cil-4) was determined. dendritic cells were prepared from leukocyte buffy coat from healthy blood donors. monocytes were stimulated with il-4 and gm-csf and dendritic cells activated with bacterial lysates. cell suspensions contained up to 90% dendritic cells, which represented 2-12% of the initial number of mononuclear cells. lymphocyte subsets that developed in lymphocyte cultures after 1 week of stimulation were analyzed by flow cytometry. dendritic cells, primed with antigens of bacteroides fragilis have shown significantly higher activation  and expression of intercellular ifn-gamma by t lymphocytes compared to negative controls. the dendritic cells primed with antigens of p. acnes had no effect on t-lymphocyte activation or cytokine production; instead they induced differentiation of t lymphocytes into cd25bright cells (regulatory t cells) with  a potentially inhibitory effect on immune response. dendritic cells primed with antigens of s. mitis induced increased expression of cil-4. we conclude that commensal oral bacteria antigens prepared from b. fragilis, s. mitis, and p. acnes prime human dendritic cells to induce th1, th2, and t(reg) differentiation, respectively. this may advance our understanding of immunopathologic manifestations in the oral cavity and offer new possibilities for redirecting immune responses in mucosal vaccination.
TIHT== 
ABHT== 

PMID== 15987522
TI  == the salivary microbiota as a diagnostic indicator of oral cancer: a descriptive,  non-randomized study of cancer-free and oral squamous cell carcinoma subjects.
AB  == background: the purpose of the present investigation was to determine if the salivary counts of 40 common oral bacteria in subjects with an oral squamous cell carcinoma (oscc) lesion would differ from those found in cancer-free (oscc-free)  controls. methods: unstimulated saliva samples were collected from 229 oscc-free  and 45 oscc subjects and evaluated for their content of 40 common oral bacteria using checkerboard dna-dna hybridization. dna counts per ml saliva were determined for each species, averaged across subjects in the 2 subject groups, and significance of differences between groups determined using the mann-whitney  test and adjusted for multiple comparisons. diagnostic sensitivity and specificity in detection of oscc by levels of salivary organisms were computed and comparisons made separately between a non-matched group of 45 oscc subjects and 229 controls and a group of 45 oscc subjects and 45 controls matched by age,  gender and smoking history. results: counts of 3 of the 40 species tested, capnocytophaga gingivalis, prevotella melaninogenica and streptococcus mitis, were elevated in the saliva of individuals with oscc (p < 0.001). when tested as  diagnostic markers the 3 species were found to predict 80% of cancer cases (sensitivity) while excluding 83% of controls (specificity) in the non-matched group. diagnostic sensitivity and specificity in the matched group were 80% and 82% respectively. conclusion: high salivary counts of c. gingivalis, p. melaninogenica and s. mitis may be diagnostic indicators of oscc.
TIHT== 
ABHT== 

PMID== 14622345
TI  == susceptibility of oral bacteria to melaleuca alternifolia (tea tree) oil in vitro.
AB  == the in vitro activity of melaleuca alternifolia (tea tree) oil against 161 isolates of oral bacteria from 15 genera was determined. minimum inhibitory concentrations (mic) and minimum bactericidal concentrations (mbc) ranged from 0.003 to 2.0% (v/v). mic90 values were 1.0% (v/v) for actinomyces spp., lactobacillus spp., streptococcus mitis and streptococcus sanguis, and 0.1% (v/v) for prevotella spp. isolates of porphyromonas, prevotella and veillonella had the lowest mics and mbcs, and isolates of streptococcus, fusobacterium and lactobacillus had the highest. time kill studies with streptococcus mutans and lactobacillus rhamnosus showed that treatment with > or = 0.5% tea tree oil caused decreases in viability of >3 log colony forming units/ml after only 30 s,  and viable organisms were not detected after 5 min. these studies indicate that a range of oral bacteria are susceptible to tea tree oil, suggesting that tea tree  oil may be of use in oral healthcare products and in the maintenance of oral hygiene.
TIHT== 
ABHT== 

PMID== 12060423
TI  == salivary microbiota levels in relation to periodontal status, experience of caries and miswak use in sudanese adults.
AB  == objectives: the purpose of the present investigation was to assess the salivary levels of 25 oral bacteria in relation to periodontal status and experience of caries, and to compare the levels of these bacteria between habitual miswak and toothbrush users in adult sudanese subjects. material and methods: the study subjects consisted of 56 individuals with age range 19-53 years (mean 35.2 years) and included 30 miswak and 26 toothbrush users. the periodontal status and presence of dental caries were assessed clinically. whole saliva was collected from all subjects, and the levels of 25 selected bacterial species in saliva were assessed by the checkerboard dna-dna hybridization method using whole genomic dna probes. results: a high percentage of the subjects had detectable levels (> or =  105 bacterial cells) of several bacterial species in saliva. between 12% and 16%  of the subjects showed high (> or = 106 cells) salivary levels of the periodontitis-associated bacteria a. actinomycetemcomitans, p. melaninogenica, p. intermedia, c. rectus and e. corrodens, whereas only two (3.6%) and four (7.1%) subjects had high levels of p. gingivalis and f. nucleatum, respectively. there were no significant differences in the levels of all or most bacterial species by age group, gender or periodontal status. presence of > or = 105 l. acidophilus bacterial cells in saliva was associated with high caries scores (p = 0.02). there were significantly higher levels of a. actinomycetemcomitans, p. melaninogenica, c. rectus, p. micros, v. parvula, s. mutans, s. anginosus, a. israelii, c. sputigena, and c. gingivalis, and significantly lower levels of p. intermedia, f. nucleatum, s. sputigena, e. corrodens, l. acidophilus, s. sanguis, s. salivarius, s. oralis, and s. mitis in the miswak than in the toothbrush group. conclusions: : the findings suggest that miswak may have a selective inhibitory effect on the level of certain bacteria in saliva, particularly several oral streptococci species. this is the first report that the checkerboard dna-dna hybridization method can be useful for assessing the levels of a wide range of bacterial taxa in saliva.
TIHT== 
ABHT== 

PMID== 12059913
TI  == bacterial and fungal microleakage of ah26 and ah plus root canal sealers.
AB  == aim: to evaluate the penetration of candida albicans alone and a combination of bacteria through root canals filled with gutta-percha and one or other root canal sealers, ah26 and ah plus. methodology: eighty teeth were randomly divided into two groups of 40 teeth each and obturated with gutta-percha using either ah26 or  ah plus sealer. a further 10 teeth served as negative controls and 10 as positive controls. the external surface of each root, except the apical 2 mm, was covered  with two layers of nail varnish. the teeth were inserted into eppendorf plastic tubes and suspended in glass bottles containing sterile schaedler broth. streptococcus mutans, streptococcus mitis, prevotella melaninogenica and lactobacillus acidophilus were placed in the access cavities of 20 teeth filled with ah26 and 20 with ah plus. candida albicans was placed in the access cavities of the other teeth. the culture medium with microorganisms was changed every 7 days. every 72 h bacterial or fungal growth in the broth was tested up to a period of 90 days. results: leakage in the experimental teeth occurred between 14 and 87 days. leakage was present in 47% of all samples. from the samples with ah26, 45% leaked bacteria and 60% leaked fungi; whilst from the samples with ah plus, 50% leaked bacteria and 55% fungi. there was no statistically significant difference in penetration of bacteria and fungi between the sealers. conclusion:  in this in vitro study, gutta-percha and the sealers ah26 and ah plus allowed leakage of bacteria and fungi.
TIHT== 
ABHT== 

PMID== 11686813
TI  == efficacy of manual and powered toothbrushes (ii). effect on microbiological parameters.
AB  == background/aim: the purpose of the present investigation was to determine the effect of self-performed supragingival plaque removal using either manual (crest  complete) or power (braun 3d plaque remover) toothbrushing on supra and subgingival plaque composition. methods: 47 periodontal maintenance subjects completed this single-blind 6 month longitudinal study. at baseline, samples of supra and separately subgingival plaque were taken from the mesial aspect of each tooth in each subject using sterile curettes and individually analyzed for their  content of 18 bacterial taxa using checkerboard dna-dna hybridization. after random assignment to groups receiving either a manual (n=25) or power toothbrush  (n=22), subjects received instruction in oral hygiene and used their assigned toothbrush 2x daily for 6 months. clinical monitoring and microbiological sampling were repeated at 3 and 6 months. significant differences in microbiological measures over time were sought using the quade test and between brushing groups at each time point using the mann-whitney test. results: mean total counts were significantly reduced for supra- and subgingival plaque samples in the manual group and subgingival samples in the powered brushing group. actinomyces naeslundii and actinomyces israelii/gerencseriae were the most numerous organisms detected at baseline and showed the greatest reductions in counts in both brushing groups. streptococcus constellatus/intermedius was significantly reduced in both groups, while streptococcus mitis/oralis/sanguis was significantly reduced in the manual toothbrushing group. mean counts of species were more markedly altered in subgingival plaque. major reductions occurred in both groups for a. naeslundii, a. israelii/gerencseriae, peptostreptococcus micros, veillonella parvula, prevotella intermedia/nigrescens, s. mitis/oralis/sanguis and s. constellatus/intermedius. all taxa examined were reduced in prevalence (% of sites colonized) in the subgingival plaque samples for both brushing groups. the reductions in prevalence were greater for a. naeslundii, s. constellatus/intermedius, v. parvula, a. israelii/gerencseriae, s. mitis/oralis/sanguis, p. micros, streptococcus mutans and p. intermedia/nigrescens. mean prevalence was decreased more for porphyromonas gingivalis, campylobacter rectus/showae, treponema denticola and bacteroides forsythus in supragingival plaque than subgingival plaque. conclusions: the major finding was the effect of supragingival plaque removal on the composition of the  subgingival microbiota. counts and prevalence of most taxa examined were markedly decreased in both toothbrushing groups. this reduction should translate to a decreased risk of periodontal disease initiation or recurrence. further, the decreased prevalence of periodontal pathogens in supragingival plaque lowers potential reservoirs of these species.
TIHT== 
ABHT== 

PMID== 11472519
TI  == evaluation of co-aggregation among streptococcus mitis, fusobacterium nucleatum and porphyromonas gingivalis.
AB  == aims: to develop a semi-quantitative method for evaluating co-aggregation reactions among three bacterial species, and to examine the influence of fusobacterium nucleatum on the adherence of porphyromonas gingivalis. methods and results: the method involves coating hydroxyapatite (hap) discs with streptococcal cells and treatment with radio-labelled bacterial cell suspensions. the sensitivity of the method was estimated by comparison with a turbidometric co-aggregation assay. results from the two methods were in close agreement. streptococcus mitis-coated hap discs were immersed in a 3h-labelled fus. nucleatum cell suspension and then a 14c-labelled p. gingivalis cell suspension.  the discs were then pyrolysed to recover and quantify the released 3h and 14c radioactivity. the number of fus. nucleatum cells on the discs increased with immersion time and this, in turn, resulted in elevated adherence of p. gingivalis. conclusion: the data indicate that the method closely reflects co-aggregation characters, and that fus. nucleatum has a positive effect on the adherence of p. gingivalis. significance and impact of the study: the present method, which is designed to mimic the oral environment, should prove useful in the semi-quantitative evaluation of co-aggregation reactions.
TIHT== 
ABHT== 

PMID== 11155173
TI  == profile of subgingival microbiota in children with mixed dentition.
AB  == a diversity of microbial species has been detected in children's oral flora at an early age. to investigate the composition of the subgingival microbiota of different groups of teeth in children with mixed dentition, 40 systemically healthy children, aged 7-8 years, randomly chosen, were examined. subgingival plaque samples were taken from the mesiobuccal sites of 21, 41, 16 and 36 permanent teeth and 53, 73, 64 and 84 deciduous teeth. the samples were cultured  for bacterial isolation anaerobically and in 10% co2 plus air using selective and nonselective media. forty-five different microbial species were isolated from both permanent and deciduous teeth. streptococcus sanguis (79-70%), streptococcus mitis (66-65%), prevotella melaninogenica (51-57%), eikenella corrodens (51-52%), capnocytophaga gingivalis (46-34%), capnocytophaga ochracea (45-45%), actinomyces naeslundii (39-60%) and prevotella intermedia (42-35%) were among the most frequently detected species in permanent and deciduous teeth respectively. several suspected periodontal pathogens, such as porphyromonas gingivalis, prevotella loescheii, campylobacter gracilis, bacteroides forsythus, campylobacter concisus, peptostreptococcus micros and selenomonas sputigena, albeit less frequently detected, were present in the microbiota of these children. the bacterial species streptococcus constellatus, peptostreptococcus micros, pseudoramibacter alactolyticus, e. corrodens and fusobacterium nucleatum  were associated with non-bleeding permanent and deciduous teeth whereas streptococcus intermedius, c. concisus, p. intermedia and p. loescheii were associated with bleeding.
TIHT== 
ABHT== 

PMID== 11054158
TI  == the formation of mixed culture biofilms of oral species along a gradient of shear stress.
AB  == a chemostat mixed culture system was used to produce two distinct ecological states, state-1 (caries-like microcosm) and state-2 (periodontal-like microcosm). eleven bacterial species (streptococcus gordonii, strep. mitis i, strep. mutans,  strep. oralis, actinomyces naeslundii, lactobacillus casei, neisseria subflava, fusobacterium nucleatum, porphyromonas gingivalis, prevotella nigrescens, veillonella dispar) were used to inoculate the planktonic system. a flow cell, designed to produce convergent flow with increasing shear stress, was attached to the chemostat system, and the resultant biofilms developed from the state-1 and state-2 microcosms along the shear stress gradient were examined and compared using image analysis and viable counts. the biofilm produced from state-1 showed  a lower shear stress tolerance (0.146 pa) than the state-2 biofilm (0.236 pa). the biofilm compositions did not vary along the gradient of shear stress and were dependent on the initial inoculum conditions. gram-positive species were predominant in the state-1 biofilm, while gram-negative species were predominant  in state-2.
TIHT== 
ABHT== 

PMID== 9402505
TI  == comparison of the subgingival microbiota of periodontally healthy and diseased adults in northern cameroon.
AB  == our study is the 1st report on subgingival microbiota in adult cameronians. the aim was to investigate, using the checkerboard dna-dna hybridization technique, the prevalence of 18 oral species in subgingival plaque samples obtained from sex- and age-matched cameronian adults with and without periodontal destruction.  we also compared cultivation and the affirm dp test with the checkerboard technique in their capability to detect some selected species among the 18. 21 adult periodontitis patients and 21 periodontally healthy subjects were examined  and the results were compared statistically. each periodontitis patient had at least 4 pockets of > or = 6 mm depth, while the healthy subjects had no sites more than 3 mm deep. results of the checkerboard analysis showed that significantly (p < 0.05) more periodontitis patients tested positive for most of  the 18 bacterial species. the gram-positive species actinomyces naeslundii, streptococcus mitis and streptococcus sanguis, known as microbiota of healthy sites, were detected significantly more frequently in the healthy group. cultivation demonstrated p. gingivalis, b. forsythus, a. actinomycetemcomitans, p. intermedia and f. nucleatum in significantly lower %s of patients as compared  to the checkerboard technique. furthermore, the affirm dp test detected p. gingivalis and b. forsythus in significantly fewer patients than did the checkerboard technique. a. actinomycetemcomitans was detected in 52.3% of the patients by the latter technique while the affirm dp test failed to detect the bacterium in any of the samples. overall, the results of the present study confirm the importance of the screening method and indicate that the prevalences  of the investigated putative periodontal pathogens and beneficial species in the  healthy and diseased adult cameronians were similar to those reported for adults  in the west and in some developing countries.
TIHT== 
ABHT== 

PMID== 9249633
TI  == the relationship between gingivitis and the serum antibodies to the microbiota associated with periodontal disease in children with down's syndrome.
AB  == gingival inflammation in down's syndrome children (ds) develops earlier and is more rapid and extensive than in non-ds children. abnormalities in host response  to the oral flora have been proposed as etiological factors of this gingival inflammation. however, the relationship between gingivitis and the host response  to oral microorganisms in ds by age has not been determined. the objective of this study was to clarify this relationship. sera were obtained from 75 ds subjects (aged 2 to 18 years) and their gingival health assessed using a modified pma index (m-pma). antibody titers to porphyromonas gingivalis (pg), prevotella intermedia (pi), treponema denticola (td), fusobacterium nucleatum (fn), selenomonas sputigena (sel), actinobacillus actinomycetemcomitans (aa), and streptococcus mitis (mi) were determined using the micro-elisa. ds subjects under 4 years old were found to have significantly more gingival inflammation than did  normal children the same age. a significant positive correlation (r = 0.548, p <  0.0001) existed in the relationship between m-pma score and plaque score for subjects in the g1 age group (deciduous dentition). at g1, the average antibody titers to aa, mi, and fn exceeded those of the normal adult reference serum pool. in addition, igg antibody titers to pg, aa, fn, sel, and mi correlated significantly with the m-pma scores in the g1 age group. there was a correlation  between age (2 to 18 years) and these antibody titers. igg antibody titers to pg, aa, sel, and mi increased significantly with increasing m-pma score. furthermore, the igg antibody titers to pg were higher (p < 0.05) in the most extensive disease group compared to the ds no-disease group. the igg antibody titers to pg  at g3 (early puberty) were significantly higher when compared to g1 (preschool children). the igm antibody titers to aa at g3 were higher (p < 0.05) when compared to g1. this study suggests that colonization by aa and fn are closely associated with the onset of gingival inflammation in ds patients under 5 years old. colonization by pg, aa, sel, and mi in ds appears to be associated with gingivitis at puberty.
TIHT== 
ABHT== 

PMID== 9467400
TI  == pathogenicity of prevotella intermedia and prevotella nigrescens isolates in a wound chamber model in rabbits.
AB  == the pathogenicity of 14 isolates identified as prevotella intermedia or prevotella nigrescens by serogrouping using monoclonal antibodies was compared in a tissue cage model in rabbits. seven strains from periodontal abscesses, 5 strains from deep periodontal pockets and 2 strains from gingivitis were tested in the animal model comprising 6 teflon tissue cages implanted on the back each of 34 rabbits. a total of 10(5)-10(8) cells of p. intermedia or p. nigrescens strains were inoculated alone or together with either actinobacillus actinomycetemcomitans or streptococcus mitis. five strains of porphyromonas gingivalis were used as a reference. the infectivity was recorded as pus formation and log viable count in aspirated material for 3, 7 and 14 days. none of the prevotella strains inoculated in monoculture survived more than 3 days, and they had no capacity to produce abscess. p. intermedia or p. nigrescens strains in combination with a. actinomycetemcomitans produced abscesses in 33-100% and with s. mitis in 42-100%. no difference in abscess formation or log viable count in samples after 14 days was recorded between serogroup i (p. intermedia) and serogroup ii and iii (p. nigrescens). the infectivity of p. intermedia or p. nigresceas strains did not differ whether they were isolated from periodontal abscess, periodontal pocket or gingivitis. p. intermedia and p.  nigrescens strains produced abscesses in combination with a facultative anaerobic strain and appears to have a similar pathogenicity in the wound chamber model in  rabbits.
TIHT== 
ABHT== 

PMID== 8703443
TI  == the interference of gingival cell cultures with growth of selected bacteria.
AB  == the aim of the present study was to analyze the interference of oral tissue cells or cell lines (effector cells) with growth of reference bacteria, and furthermore to investigate whether cells derived from different individuals differ in such activity. the reference bacteria were staphylococcus aureus, staphylococcus epidermidis, streptococcus mitis, actinobacillus actinomycetemcomitans, porphyromonas gingivalis, and fusobacterium nucleatum. the effector cells used were gingival fibroblasts (gf) from 21 periodontally involved persons, gingival epithelial cells (e) from 2 such persons, hela cells (hela), and an amnion cell line (amnion). the cells were cultivated and their supernatants tested for antibacterial activity in a bioscreen robot analyzer (labsystems, finland). results suggest that the antibacterial activity of each tested primary cell line  of tissue had its own profile depending on cell type and donor, and that the composition of oral microbiota was influenced by oral cells, which might, in turn, contribute to the variations in the pathogenesis of periodontal diseases.
TIHT== 
ABHT== 

PMID== 8747674
TI  == effect of titanium on selected oral bacterial species in vitro.
AB  == titanium granules were tested for their antibacterial effect on strains of streptococcus sanguis, streptococcus mitis, actinomyces naeslundii, haemophilus parainfluenzae, fusobacterium spp. and prevotella intermedia in comparison with amalgam and two of its components, copper and tin. glass beads were used as controls. the number of viable bacteria was estimated in samples exposed to the various materials for 1, 3, 6 and 24 h, respectively, and the viable counts were  related to the baseline value. titanium showed low antibacterial effect on the species tested. copper and amalgam showed an expressed toxicity to all species and differed significantly from titanium and glass particles. gram positive streptococcus spp. and a. naeslundii showed a lower susceptibility to the metals  than the gram negative species. the antibacterial effect of copper and amalgam test particles on s. sanguis and p. intermedia was significantly decreased in the presence of serum. this study showed that some metals have a toxic effect in vitro on oral bacteria, a fact that may play a role in plaque formation when these materials are used for dental restorations. titanium did not have a similar antibacterial effect.
TIHT== 
ABHT== 

PMID== 7868248
TI  == immunopathological activities of extracellular products of streptococcus mitis, particularly a superantigenic fraction.
AB  == previously, we prepared extracellular products, fractions f-1 and f-2 of streptococcus mitis 108, an isolate from the tooth surface of an infant, and showed that f-1 exhibited inflammatory cytokine-inducing activities. in the present study, we present evidence that fraction f-2 induced human t-cell proliferation in the presence of irradiated human peripheral blood mononuclear cells and selectively activated t cells bearing v beta 2 and v beta 5.1 in the t-cell receptor. f-1, on the other hand, stimulated human gingival fibroblasts to support the t-cell proliferation in the same way as human gamma interferon or prevotella intermedia lipopolysaccharide (lps). fraction f-1 also primed gingival fibroblasts to support the production of interleukin-2 and gamma interferon by the t cells upon stimulation with f-2. human gingival fibroblasts stimulated with fraction f-1, like those stimulated by p. intermedia lps and human gamma interferon, exhibited human leukocyte antigen (hla)-dr mrna expression and cell surface hla-dr molecules as detected by enzyme-linked immunosorbent assay. an anti-hla-dr monoclonal antibody inhibited t-cell proliferation in response to f-2, probably through inactivating the accessory function of hla-dr-bearing fibroblasts. t cells activated with f-2 in the presence of irradiated peripheral  blood mononuclear cells exhibited definite cytotoxic effects against fibroblasts  and squamous carcinoma cells originating from human oral tissues. these findings  are strongly suggestive of an association of extracellular products of viridans streptococci with pathogenesis of oral mucosal diseases, particularly those disorders in gingiva which are accompanied by heavy infiltration of t cells.
TIHT== 
ABHT== 

PMID== 7799211
TI  == cytotoxicity in bacterial cultures: interaction and cell-specificity, possible factors in periodontal disease.
AB  == cytotoxicity in culture media of various growing bacterial strains was estimated  by cr-51 release of labelled target-cells. interaction studies were made by adding each of the different uv-killed bacteria to the medium with viable bacteria. the reference oral bacterial strains were: actinobacillus actinomycetemcomitans y4, porphyromonas gingivalis, fusobacterium nucleatum and streptococcus mitis, which were compared with the reference bacteria staphylococcus aureus 209 and staphylococcus epidermidis. the target cells were:  gingival fibroblasts (gf), periodontal membrane fibroblasts (pmf), pulpal fibroblasts (pf), hela-cells (hela), and lymphoid neoplasm cells (ln). synergistic, as well as antagonistic, effects on target cells were observed. the  cytotoxicity of a. actinomycetemcomitans in presence of p. gingivalis is neutralized while in presence of s. aureus it was increased. bacterial interactions with f. nucleatum and p. gingivalis cytotoxicity were observed. the  cytotoxicity of f. nucleatum was increased when cultured together with a. actinomycetemcomitans. each cell type reacted differently to the toxicity of the  supernatant of growth medium in which the same bacterial strain had been cultivated, which indicates cell specificity of the toxins.
TIHT== 
ABHT== 

PMID== 7936717
TI  == changes in root canal microbiota during the development of rat periapical lesions.
AB  == periapical lesions are reproducibly induced in rats by pulp exposure and infection from the oral cavity. lesions expand rapidly between day 7 and day 15-20 (active phase), with slowed expansion thereafter. in the present study we characterized the root canal microbiota present during the active phase of lesion development in this system. the mandibular first molars of sprague-dawley rats were exposed on day 0. the teeth were extracted after 7 days (n = 10 animals) and 15 days (n = 10), and the microbiota present in roots was isolated and characterized. the number of colonies isolated per tooth was similar on day 7 (1.53 +/- 0.64 colony-forming units x 10(3)) and day 15 (1.49 +/- 0.37 colony-forming units x 10(3)). no colonies were isolated from unexposed control teeth. anaerobic bacteria increased significantly between day 7 (24.3 +/- 5.7%) and day 15 (47.3 +/- 7.5%), and the proportion of gram-negative organisms increased from day 7 (24.3 +/- 6.1) to day 15 (46.9 +/- 6.8). the predominant bacteria included, on day 7: streptococcus and bacteroides species; on day 15: species of streptococcus, bacteroides, prevotella, neisseria and peptostreptococcus. streptococcus oralis, streptococcus mitis, streptococcus rattus, bacteroides pneumosintes and bacteroides ureolyticus were frequently isolated at both points. although approximately the same mean number of different species (approximately 3.5) was isolated per tooth on both day 7 and 15, the overall diversity of the isolates increased on day 15.(abstract truncated at 250  words)
TIHT== 
ABHT== 

PMID== 1328995
TI  == characterization of the adherence of porphyromonas gingivalis to oral streptococci.
AB  == adherence of porphyromonas gingivalis to strains of streptococcus sanguis and streptococcus mitis deposited on nitrocellulose paper was investigated. a variety of laboratory strains and clinical isolates of p. gingivalis bound to both s. sanguis and s. mitis. binding of p. gingivalis to all but one of the streptococci was not inhibited by salivary molecules. pretreatment of p. gingivalis with periodate and pretreatment of s. sanguis and s. mitis with pronase decreased binding, suggesting that adherence may be mediated by a protein on the streptococci interacting with a carbohydrate on p. gingivalis. binding was not inhibited by a selection of simple sugars. the ability to adhere to early plaque  bacteria such as s. sanguis and s. mitis may be important in the colonization of  the mouth by p. gingivalis.
TIHT== 
ABHT== 

PMID== 1528638
TI  == isolation and properties of the capnocytophaga ochracea bacteriocin.
AB  == a bacteriocin from a subgingival plaque isolate of capnocytophaga ochracea was purified and characterized. it was isolated from cell extract and had a molecular weight of 100,000. streptococcus sanguis, streptococcus mitis, streptococcus mutans and propionibacterium acnes were susceptible to the bacteriocin.
TIHT== 
ABHT== 

PMID== 1528619
TI  == enumeration of subgingival species on primary isolation plates using colony lifts.
AB  == this study evaluated the feasibility of using a colony lift method and dna probes to enumerate bacterial species cultured on primary isolation plates. fourteen digoxigenin-labeled whole chromosomal dna probes representing 12 subgingival species were validated by hybridization with colony lifts prepared from 249 reference strains of 51 species grown on trypticase soy agar plates supplemented  with 5% sheep blood. colonies of reference strains were lifted onto nytran filters from plates and treated to lyse cells, remove cellular proteins, denature and fix microbial dna to the filters. positive reactions were detected with an anti-digoxigenin antibody conjugated to alkaline phosphatase and revealed by bromo-chloro-indolyl phosphate and nitroblue tetrazolium. cross-reactions were not observed for 13/14 probes, but 2 strains of streptococcus mitis reacted with  the probe to streptococcus sanguis ii. subgingival plaque samples were taken by means of a sterile curette from mesiobuccal surfaces of teeth present in each of  26 subjects with differing periodontal disease states. samples were dispersed, diluted, plated and incubated anaerobically for 7 d at 35 degrees c. colonies were lifted as described above. filters were cut into sections and hybridized with the 14 digoxigenin-labeled dna probes. the probes were used to enumerate the test species and the total number of isolates was determined in 711 plaque samples. the colony lift method and dna probes provided a sensitive, economical and quantitative method for enumerating cultivable microbial species in subgingival plaque samples. in addition, the amplification provided by growing the organisms on agar plates facilitated determination of numbers of organisms in small plaque samples, such as those from healthy sites.
TIHT== 
ABHT== 

PMID== 2384623
TI  == inhibitory effect of human plasma and saliva on co-aggregation between bacteroides gingivalis and streptococcus mitis.
AB  == the effect of human plasma and saliva on co-aggregation between bacteroides gingivalis and streptococcus mitis was studied by means of a turbidimetric assay. the co-aggregation activity was obtained from the maximum slope of the absorbance vs. time curve. its dependence on ph, temperature, and ionic strength was examined, and the number of bacteroides cells in relation to the number of streptococcus cells resulting in optimal co-aggregation was established. co-aggregation inhibition experiments showed that the co-aggregation activity was inhibited by l-arginine and l-lysine, although the activity was unaffected by the sugars tested. human plasma and saliva were able to inhibit the co-aggregation in a dose-dependent reaction. plasma exhibited the most potent inhibitory activity in these fluids. fibrinogen was the most potent inhibitor of the plasma-derived proteins tested. these data suggest the possibility that the oral fluids may modulate the attachment of b. gingivalis to gram-positive bacteria in periodontal pockets.
TIHT== 
ABHT== 

PMID== 2195840
TI  == effect of tif4 solutions on bacterial growth in vitro and on tooth surfaces.
AB  == the purpose of this study was to assess the antimicrobial effect of tif4 as compared with equimolar solutions of naf, apf, and snf2 and to evaluate the effect, if any, on bacterial growth on topically treated tooth surfaces. in an in vitro study, paper discs impregnated with 20 microliters of equimolar solutions of snf2, naf, apf, and tif4 were placed on blood agar plates seeded with streptococcus mutans and bacteroides gingivalis. sterile saline was used as control. similar growth inhibition zones were found for all fluorides. in the second part of the study six volunteers carried intraoral appliances containing enamel and root surface specimens treated with 1% tif4 and untreated specimens for 18 h. scanning electron microscopic examination of the experimental tooth surfaces showed great variation in bacterial growth between subjects, but no systematic difference between fluoride-treated and untreated specimens. bacteria  from test and control specimens were grown under aerobic and anaerobic conditions on blood agar and on mitis salivarius agar. colony-forming unit counts showed great interindividual variations, but no differences could be observed between treated and untreated enamel or root surfaces. thus, the hypothesis that the presence of a ti-rich coating may influence bacterial colonization on tif4-treated tooth surfaces could not be substantiated.
TIHT== 
ABHT== 

PMID== 2141877
TI  == selective modulation of bacterial attachment to oral epithelial cells by enzyme activities associated with poor oral hygiene.
AB  == the present investigation explored the hypothesis that elevated levels of certain enzymes in the gingival crevicular environment of individuals with poor oral hygiene and/or gingival inflammation may modify the surfaces of epithelial cells  and thereby modulate the types of bacteria which attach and colonize. buccal epithelial cells treated with neuraminidase and certain proteases were used as a  model for study. bacteria studied included streptococcus sanguis and streptococcus mitis which have been associated with gingival health, actinomyces  species which are increased in plaque associated with developing gingivitis, and  bacteroides gingivalis, bacteroides intermedius, and actinobacillus actinomycetemcomitans which are associated with destructive periodontal diseases. treatment of epithelial cells with the enzymes studied produced selective effects on their receptivity for bacteria. neuraminidase treatment of epithelial cells greatly reduced the attachment of all strains of s. sanguis and s. mitis studied. in contrast, the number of actinomyces viscosus, a. naeslundii and a. israelii cells which attached was significantly increased. neuraminidase treatment also appeared to enhance attachment of b. intermedius and b. gingivalis. treatment of  buccal cells with trypsin, chymotrypsin or papain also selectively affected bacterial attachment. such protease treatment greatly reduced the numbers of streptococci and a. viscosus cells which attached, while the numbers of b. gingivalis and b. intermedius were significantly increased. treatment of epithelial cells with preparations of lysosomal enzymes derived from human pmns produced similar selective effects. the changes in bacterial adhesion observed by the enzyme treatments studied are consistent with the shifts in the composition of the gingival crevice flora which occur when oral hygiene is terminated and gingivitis develops.
TIHT== 
ABHT== 

PMID== 3163351
TI  == use of percoll density gradients for studying the attachment of bacteria to oral  epithelial cells.
AB  == an assay for studying the attachment of bacteria to oral epithelial cells has been developed which utilizes percoll density gradient centrifugation to separate bacteria and epithelial cells. 3h-thymidine-labeled bacteria were incubated with  suspensions of buccal epithelial cells in microtitration plates for 2.5 hr at 35  degrees c. the mixtures were then subjected to density gradient centrifugation in 50% percoll. epithelial cells with attached bacteria formed a band near the top of the tube, while unattached bacteria formed a band near the bottom. the epithelial cells were collected on membrane filters, and the number of attached bacteria was determined by scintillation counting. binding of s. mitis c5 was found to increase with time, and equilibrium was attained within two hr. saturation of available binding sites occurred when 10(7) s. mitis cells were incubated with 1.5 x 10(4) buccal epithelial cells. the numbers of streptococci which attached as determined with this assay were in good agreement with values obtained by direct microscopic counts. adsorption of s. mitis c5 cells was adequately described by a langmuir isotherm (correlation coefficient 0.998). this permitted calculation of estimates of the number of binding sites and the affinity of the organism. the assay proved reliable even when as few as 1000 epithelial cells were used. treating the epithelial cells with neuraminidase or trypsin significantly decreased the number of s. mitis c5 cells which attached. in contrast, binding of a. naeslundii 12104 to neuraminidase-treated cells was increased, and attachment of b. gingivalis 381 was also enhanced, especially to epithelial cells which had been treated with trypsin.
TIHT== 
ABHT== 

PMID== 3422291
TI  == an in vitro model to study bacterial invasion of periodontal tissues.
AB  == in periodontal disease, the abilities of bacteria to adhere to and degrade in vivo basement membranes should be considered as two of the rate-limiting steps for the potential active or passive invasion of gingival connective tissues. to study these mechanisms in greater detail, we used the pf hr-9 basement-membrane-like matrix to establish an in vitro model of bacterial invasion and degradation. three gram-negative anaerobic periodontopathic organisms, bacteroides gingivalis, fusobacterium nucleatum, and actinobacillus actinomycetemcomitans, bound in considerably higher numbers to the hr-9 matrix than did 6 strains of gram-positive facultative organisms typically associated with periodontal health. in a further experiment with b. gingivalis, the organism rapidly degraded type iv collagen, the major macromolecular component constituting the hr-9 matrix. streptococcus mitis, the nonperiodontopathic bacterium tested, did not degrade this model matrix. this study provides evidence that b. gingivalis, a periodontopathic bacterium, is able to adhere to and degrade basement membranes, whereas nonperiodontopathic organisms appear not to share in these abilities.
TIHT== 
ABHT== 

PMID== 3018251
TI  == coagglutination reactions between candida albicans and oral bacteria.
AB  == an agglutination assay for detecting intermicrobial adherence between the cells of candida albicans and various oral bacteria is described. strains of streptococcus sanguis, s. salivarius, s. mutans, s. mitis, fusobacterium nucleatum and actinomyces viscosus all coagglutinated with c. albicans. no interaction could be demonstrated between the cells of bacteroides melaninogenicus and those of c. albicans. preliminary investigations of these interactions suggest that binding of f. nucleatum and a. viscosus to c. albicans  is mediated by bacterial proteins, possibly lectins. other mechanisms must account for the binding of oral streptococci to c. albicans. the possible implications of these findings in relation to oral mucosal colonisation and oral  candidal clearance are discussed.
TIHT== 
ABHT== 

PMID== 3861843
TI  == lactic acid production by oral streptococcus mitis inhibits the growth of oral capnocytophaga.
AB  == various relationships including inhibition or stimulation of growth have been demonstrated among the bacteria present in dental plaque, both in vitro and in vivo. a large number of these relationships involved oral streptococci. an earlier study found that strains of streptococcus mitis inhibited the growth of potential periodontopathic microorganisms, such as actinobacillus actinomycetemcomitans, capnocytophaga and species of bacteroides and fusobacterium. the present investigation showed that this inhibitory effect resulted primarily from lactic acid production.
TIHT== 
ABHT== 

PMID== 6133836
TI  == coaggregation of human oral cytophaga species and actinomyces israelii.
AB  == a total of 19 strains of oral cytophaga sp. obtained from subgingival plaque deposits were tested for their ability to coaggregate with strains of actinomyces israelii, a. viscosus, a. naeslundii, streptococcus sanguis, s. mutans, s. salivarius, and s. mitis. coaggregation was observed only with a. israelii. based on their coaggregation patterns with eight a. israelii strains, the cytophaga strains were distributed among three distinct groups: those that coaggregated with a. israelii pk16 but not with a. israelii w1011 (atcc 29322), those that coaggregated with a. israelii atcc 29322 but not with a. israelii pk16, and those that coaggregated with none of the eight a. israelii strains. in each of the coaggregations, prior heat treatment (85 degrees c, 30 min) of the cytophaga cells prevented coaggregation, whereas identical treatment of the a. israelii cells had no effect. the ability of a. israelii pk16 to form adherent plaque on a tooth surface previously coated with cytophaga plaque was tested with one of the  coaggregating cytophaga strains. white patches of a. israelii plaque were found covering both the amber-colored cytophaga plaque on the cementum surface as well  as the enamel surface to which cytophaga strains do not adhere. electron micrographs of thin-sectioned mixed-plaque material revealed both cell types in close proximity. in addition, electron micrographs of negatively stained coaggregated cells showed interbacterial adherence between surface fimbrae on a.  israelii and outer membrane blebs on the gram-negative cytophaga sp. the kinetics of binding of a. israelii to spheroidal hydroxyapatite and to root powder were indicative of a high-affinity binding system with comparatively large numbers of  available binding sites on both substrata. these results indicate the highly specific nature of cytophaga sp.--a. israelii recognition. the contribution of such recognition toward the mechanisms that are responsible for the indigenous nature of these oral bacteria is discussed.
TIHT== 
ABHT== 

PMID== 6281193
TI  == enzymatic modification of bacterial receptors on saliva-treated hydroxyapatite surfaces.
AB  == certain properties of experimental pellicles formed by the adsorption of salivary components on hydroxyapatite surfaces change over time. to determine whether enzymes likely to be present in the oral environment could induce such changes, pellicles were treated with saliva which had been incubated for 18 h at 35 degrees c to promote the elaboration of microbial enzymes. this treatment markedly reduced the numbers of streptococcus mutans mt3 and jbp and s. sanguis fc-1 and c5 cells which attached, but it had little or no effect on the attachment of s. mitis re7, actinomyces viscosus ly7 and ck-8, bacteroides gingivalis 381, or b. melaninogenicus subsp. intermedius 581. heating the incubated saliva at 60 degrees c for 30 min partially reduced its pellicle-modifying activity, whereas heating at 80 degrees c for 30 min or 100 degrees c for 15 min completely eliminated such activity. this indicated that the saliva contained heat-labile substances, presumably enzymes, which could affect the pellicle receptors involved in the attachment of s. mutans and s. sanguis. treatment of saliva-treated hydroxyapatite with commercially obtained enzyme preparations also affected bacterial attachment. thus, treatment with galactose oxidase reduced the numbers of the s. mutans strains which attached, whereas treatment with neuraminidase reduced the adsorption of s. sanguis fc-1 but not that of s. sanguis c5. treatment with beta-glucosidase preparations derived from  almonds significantly reduced the attachment of all of the streptococcal strains  studied, but, when subjected to isoelectric fractionation, the adherence-inhibiting activity did not correlate directly with beta-glucosidase activity. treatment of the pellicles with trypsin or eight other glycosidases did not affect streptococcal attachment. exposure of the enzymatically modified pellicles to fresh saliva did not restore the streptococcal receptors. collectively, the data suggest that some bacterial receptors in the pellicle coating of teeth can be modified by enzymes likely to be present in the oral environment, and these interactions may affect oral bacterial ecology.
TIHT== 
ABHT== 

PMID== 551241
TI  == inhibitory activity of streptococcus mitis against oral bacteria.
AB  == the antagonistic properties of three strains of streptococcus mitis were investigated. they were found to inhibit a wide range of oral bacteria; gram-positive and gram-negative, facultative and anaerobic species being susceptible. the s. mitis strains were shown to be producing hydrogen peroxide, this being partially responsible for the aerobic inhibitory activity. a second inhibitory factor(s) was also produced, aerobically and anaerobically, although this could not be isolated. a limited characterization of this factor was undertaken using plate cultures.
TIHT== 
ABHT== 

PMID== 24002
TI  == attachment of bacteroides melaninogenicus subsp. asaccharolyticus to oral surfaces and its possible role in colonization of the mouth and of periodontal pockets.
AB  == this investigation examined the ability of cells of bacteroides melaninogenicus subsp. asaccharolyticus 381 to adhere to surfaces that might be important for its initial colonization of the mouth and its subsequent colonization in periodontal  pockets. of 48 asaccharolytic strains of b. melaninogenicus, 47 agglutinated human erythrocytes, whereas none of 20 fermentative strains, which included reference cultures of the subspecies intermedius and melaninogenicus, were active. electron microscopy indicated that both asaccharolytic and fermentative strains possessed pili; hence, the presence of pili did not correlate with the hemagglutinating activities of b. melaninogenicus strains. both asaccharolytic and fermentative b. melaninogenicus strains suspended in phosphate-buffered saline adhered in high numbers to buccal epithelial cells and to the surfaces of  several gram-positive bacteria tested, including actinomyces viscosus, a. naeslundii, a. israelii, streptococcus sanguis, and s. mitis. b. melaninogenicus  subsp. asaccharolyticus 381 also attached, but in comparatively low numbers, to untreated and to saliva-treated hydroxyapatite. addition of clarified whole saliva to suspensions of strain 381 almost completely eliminated adherence to buccal epithelial cells and to hydroxyapatite surfaces, but saliva had no detectable effect on attachment to gram-positive plaque bacteria. both fermentative and nonfermentative strains of b. melaninogenicus also attached in high numbers to crevicular epithelial cells derived from human periodontal pockets, but normal human serum strongly inhibited attachment. serum also inhibited attachment of strain 381 to saliva- and serum-treated hydroxyapatite, but it had little effect upon attachment to gram-positive bacteria. these observations suggested that salivary and serum components would strongly inhibit  the attachment of b. melaninogenicus cells to several oral surfaces, but not to the surfaces of certain gram-positive bacteria commonly present in human dental plaque. this was confirmed by an in vivo experiment in which streptomycin-labeled cells of b. melaninogenicus 381-r were introduced into the mouths of two volunteers. after 10 min, several hundred-fold higher numbers of the organism were recovered from preformed bacterial plaque present on teeth than from clean tooth surfaces or from the buccal mucosa and tongue dorsum. high numbers of b. melaninogenicus cells were also recovered from preformed plaque after 150 min, but virtually no cells of the organism were recovered from the other surfaces studied. these data suggest that the presence of dental plaque containing actinomyces and other gram-positive bacteria may be essential for the attachment  and colonization of b. melaninogenicus cells after their initial introduction into the mouth. similarly, the presence of subgingival plaque containing gram-positive bacteria may be necessary for its secondary colonization in periodontal pockets.
TIHT== 
ABHT== 

