@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23688097
TI  == antibiotic resistance in human chronic periodontitis microbiota.
AB  == background: patients with chronic periodontitis (cp) may yield multiple species of putative periodontal bacterial pathogens that vary in their antibiotic drug susceptibility. this study determines the occurrence of in vitro antibiotic resistance among selected subgingival periodontal pathogens in patients with cp.  methods: subgingival biofilm specimens from inflamed deep periodontal pockets were removed before treatment from 400 adults with cp in the united states. the samples were cultured, and selected periodontal pathogens were tested in vitro for susceptibility to amoxicillin at 8 mg/l, clindamycin at 4 mg/l, doxycycline at 4 mg/l, and metronidazole at 16 mg/l, with a post hoc combination of data for  amoxicillin and metronidazole. gram-negative enteric rods/pseudomonads were subjected to ciprofloxacin disk-diffusion testing. results: overall, 74.2% of the patients with cp revealed subgingival periodontal pathogens resistant to at least one of the test antibiotics. one or more test species, most often prevotella intermedia/nigrescens, streptococcus constellatus, or aggregatibacter actinomycetemcomitans, were resistant in vitro to doxycycline, amoxicillin, metronidazole, or clindamycin, in 55%, 43.3%, 30.3%, and 26.5% of the patients with cp, respectively. fifteen percent of patients harbored subgingival periodontal pathogens resistant to both amoxicillin and metronidazole, which were mostly either s. constellatus (45 individuals) or ciprofloxacin-susceptible strains of gram-negative enteric rods/pseudomonads (nine individuals). conclusions: patients with cp in the united states frequently yielded subgingival periodontal pathogens resistant in vitro to therapeutic concentrations of antibiotics commonly used in clinical periodontal practice. the wide variability  found in periodontal pathogen antibiotic-resistance patterns should concern clinicians empirically selecting antibiotic treatment regimens for patients with  cp.
TIHT== 
ABHT== 

PMID== 22324467
TI  == impact of periodontal therapy on the subgingival microbiota of severe periodontitis: comparison between good responders and individuals with refractory periodontitis using the human oral microbe identification microarray.
AB  == background: this study compares the changes to the subgingival microbiota of individuals with "refractory" periodontitis (rp) or treatable periodontitis (good responders [gr]) before and after periodontal therapy by using the human oral microbe identification microarray (homim) analysis. methods: individuals with chronic periodontitis were classified as rp (n = 17) based on mean attachment loss (al) and/or >3 sites with al >/=2.5 mm after scaling and root planing, surgery, and systemically administered amoxicillin and metronidazole or as gr (n  = 30) based on mean attachment gain and no sites with al >/=2.5 mm after treatment. subgingival plaque samples were taken at baseline and 15 months after  treatment and analyzed for the presence of 300 species by homim analysis. significant differences in taxa before and post-therapy were sought using the wilcoxon test. results: the majority of species evaluated decreased in prevalence in both groups after treatment; however, only a small subset of organisms was significantly affected. species that increased or persisted in high frequency in  rp but were significantly reduced in gr included bacteroidetes sp., porphyromonas endodontalis, porphyromonas gingivalis, prevotella spp., tannerella forsythia, dialister spp., selenomonas spp., catonella morbi, eubacterium spp., filifactor alocis, parvimonas micra, peptostreptococcus sp. ot113, fusobacterium sp. ot203,  pseudoramibacter alactolyticus, streptococcus intermedius or streptococcus constellatus, and shuttlesworthia satelles. in contrast, capnocytophaga sputigena, cardiobacterium hominis, gemella haemolysans, haemophilus parainfluenzae, kingella oralis, lautropia mirabilis, neisseria elongata, rothia  dentocariosa, streptococcus australis, and veillonella spp. were more associated  with therapeutic success. conclusion: persistence of putative and novel periodontal pathogens, as well as low prevalence of beneficial species was associated with chronic refractory periodontitis.
TIHT== 
ABHT== 

PMID== 18975591
TI  == [treatment-refractory-dental-extraction-associated pyothorax involving infection  by 2 species of oral originated bacteria requires surgical debridement by video assisted thoracoscopic surgery (vats)].
AB  == cases of septic pulmonary embolism (spe) diagnosed clinically by ct after dental  extraction rarely include verification of bacteria from the local infection site. we report the case of a 70-year-old man without background disease suffering severe pyothrax after dental extraction. we detected two species of oral bacteria from his pleural effusion. treatment was so difficult that it required surgical debridement by video assisted thoracoscopic surgery (vats), even after the appropriate administration of antibiotics. according to the american heart association (aha) prophylaxis guidelines for preventing infective endocarditis indicate that it is uncommon to prescribe antibiotics to patients without background disease after dental extraction. no appropriate japanese guidelines exist considering the prevention of spe causing severe pyothorax as in our case.  the hematogenous spread of bacteria such as spe caused by sepsis after tooth extraction thus requires more attended careful consideration in clinical practice if patients are to be properly protected against potentially serious complications.
TIHT== 
ABHT== 

PMID== 17982605
TI  == streptococcus constellatus and prevotella bivia penile abscess.
AB  == streptococcus constellatus (s. constellatus) is known to cause abscesses in the oral, genitourinary, and gastrointestinal tracts, frequently in association with  anaerobic bacteria. we report a rare case of s. constellatus and prevotella bivia (p. bivia) causing a penile abscess, which was successfully treated with surgical drainage and antibiotic treatment.
TIHT== 
ABHT== 

PMID== 16945032
TI  == microbiota of the dorsum of the tongue after plaque accumulation: an experimental study in humans.
AB  == background: the purpose of the present investigation was to determine the effect  of the absence of tongue hygiene on the microbiota of the dorsum of the tongue. methods: ten volunteers (aged 19 to 22 years) entered the study at baseline and were instructed to abstain from tongue cleaning for 7 days, followed by a period  of 3 days without any kind of oral hygiene. subsequently, a period of 21 days of  washout was employed, and this protocol was repeated three times. microbiological samples were obtained from the dorsum of the tongue at baseline and at the end of the period of coating accumulation and analyzed using the checkerboard dna-dna hybridization technique. results: the species found in highest mean counts at baseline and day 10 were prevotella melaninogenica and veillonella parvula. the mean bacterial total counts enhanced significantly during the study (from 17.1x10(6) to 33.7x10(6)). proportions of red and blue complexes and levels of 18 species also increased after the period of coating accumulation, including several periodontal pathogens, such as prevotella intermedia, prevotella nigrescens, streptococcus constellatus, tannerella forsythensis, porphyromonas gingivalis, treponema denticola, and p. melaninogenica. conclusion: the tongue surface could be an important reservoir for periodontal pathogens and may play a  role in the recolonization of tooth surfaces and in the etiology of oral halitosis.
TIHT== 
ABHT== 

PMID== 15793117
TI  == phototargeting oral black-pigmented bacteria.
AB  == we have found that broadband light (380 to 520 nm) rapidly and selectively kills  oral black-pigmented bacteria (bpb) in pure cultures and in dental plaque samples obtained from human subjects with chronic periodontitis. we hypothesize that this killing effect is a result of light excitation of their endogenous porphyrins. cultures of prevotella intermedia and p. nigrescens were killed by 4.2 j/cm2, whereas p. melaninogenica required 21 j/cm2. exposure to light with a fluence of  42 j/cm2 produced 99% killing of p. gingivalis. high-performance liquid chromatography demonstrated the presence of various amounts of different porphyrin molecules in bpb. the amounts of endogenous porphyrin in bpb were 267 (p. intermedia), 47 (p. nigrescens), 41 (p. melaninogenica), and 2.2 (p. gingivalis) ng/mg. analysis of bacteria in dental plaque samples by dna-dna hybridization for 40 taxa before and after phototherapy showed that the growth of the four bpb was decreased by 2 and 3 times after irradiation at energy fluences  of 4.2 and 21 j/cm2, respectively, whereas the growth of the remaining 36 microorganisms was decreased by 1.5 times at both energy fluences. the present study suggests that intraoral light exposure may be used to control bpb growth and possibly benefit patients with periodontal disease.
TIHT== 
ABHT== 

PMID== 15562909
TI  == efficacy of antibiotics against periodontopathogenic bacteria within epithelial cells: an in vitro study.
AB  == background: periodontopathogenic bacteria can invade and survive within epithelial cells, but susceptibility of intracellular infection to antibiotics used in periodontitis treatment has not been studied to date. methods: kb cells were infected by actinobacillus actinomycetemcomitans, strain nctc 9710; porphyromonas gingivalis, strains atcc 33277 and jh16-1; or streptococcus constellatus, strain j012b. after 2, 4, and 12 hours the bactericidal effect of antibiotics (clindamycin, doxycycline, metronidazole, and moxifloxacin) on intracellular microorganisms was tested at a concentration up to the 100-fold minimum inhibitory concentration (mic) determined separately on planktonic bacteria. results: the p. gingivalis strains differed in their invasiveness and atcc 33277 was 100-fold more invasive than jh16-1. doxycycline and clindamycin at a concentration 10-fold mic had no effect, but p. gingivalis intercellular infection was significantly reduced by metronidazole at 10-fold mic after 2 and 4 hours. moxifloxacin was effective, but a 100-fold mic concentration was necessary to reduce p. gingivalis strains intracellular growth to 7% of the control. other  bacterial species grown inside the kb cells were more susceptible to antibiotics. clindamycin at 10-fold mic reduced the number of intracellular s. constellatus after 4 and 12 hours. this bacterium was eliminated by moxifloxacin at 50-fold mic. intracellular a. actinomycetemcomitans was killed by 10-fold mic of doxycycline and moxifloxacin after 4 hours incubation. conclusions: moxifloxacin  was the most efficient antibiotic to treat intracellular infection. however, taking into account the mic values and the levels of antibiotics in gingival fluid, elimination of intracellular bacteria by antibiotics alone seems to be questionable.
TIHT== 
ABHT== 

PMID== 15086620
TI  == efficacy of antibiotics to strains of periodontopathogenic bacteria within a single species biofilm - an in vitro study.
AB  == objectives: this study examined differences in the efficacy of antibiotics against a single strain of three periodontal pathogens grown in an artificial biofilm. methods: single species biofilms were established with artificial saliva and one of the following bacterial strains: actinobacillus actinomycetemcomitans  y4, streptococcus constellatus 384b (a clinical isolate) and porphyromonas gingivalis atcc 33277. the efficacy of the antibiotics clindamycin, doxycycline,  metronidazole, and moxifloxacin to these bacteria was determined using concentrations up to 100-fold minimal inhibitory concentration (mic) to planctonic bacteria over 48 h. results: the ability of the bacteria to form a biofilm varied. the biofilms of s. constellatus 384b and a. actinomycetemcomitans y4 contained more viable bacteria and showed a larger thickness in sem photographs than those of p. gingivalis atcc 33277. the antibiotics tested showed different efficacy for the different strains. moxifloxacin was the most efficient antibiotic: onefold mic was sufficient to eliminate a. actinomycetemcomitans y4 and p. gingivalis atcc 33277 after 48 h. however, only the 50-fold mic completely eradicated s. constellatus 384b. sem photographs underlined the damaging effect of moxifloxacin on the biofilm structure. conclusion: the complete removal of bacteria by the use of antibiotics alone seems to be impossible when taking into  account mic values and the level of antibiotics in gingival fluid.
TIHT== 
ABHT== 

PMID== 11686813
TI  == efficacy of manual and powered toothbrushes (ii). effect on microbiological parameters.
AB  == background/aim: the purpose of the present investigation was to determine the effect of self-performed supragingival plaque removal using either manual (crest  complete) or power (braun 3d plaque remover) toothbrushing on supra and subgingival plaque composition. methods: 47 periodontal maintenance subjects completed this single-blind 6 month longitudinal study. at baseline, samples of supra and separately subgingival plaque were taken from the mesial aspect of each tooth in each subject using sterile curettes and individually analyzed for their  content of 18 bacterial taxa using checkerboard dna-dna hybridization. after random assignment to groups receiving either a manual (n=25) or power toothbrush  (n=22), subjects received instruction in oral hygiene and used their assigned toothbrush 2x daily for 6 months. clinical monitoring and microbiological sampling were repeated at 3 and 6 months. significant differences in microbiological measures over time were sought using the quade test and between brushing groups at each time point using the mann-whitney test. results: mean total counts were significantly reduced for supra- and subgingival plaque samples in the manual group and subgingival samples in the powered brushing group. actinomyces naeslundii and actinomyces israelii/gerencseriae were the most numerous organisms detected at baseline and showed the greatest reductions in counts in both brushing groups. streptococcus constellatus/intermedius was significantly reduced in both groups, while streptococcus mitis/oralis/sanguis was significantly reduced in the manual toothbrushing group. mean counts of species were more markedly altered in subgingival plaque. major reductions occurred in both groups for a. naeslundii, a. israelii/gerencseriae, peptostreptococcus micros, veillonella parvula, prevotella intermedia/nigrescens, s. mitis/oralis/sanguis and s. constellatus/intermedius. all taxa examined were reduced in prevalence (% of sites colonized) in the subgingival plaque samples for both brushing groups. the reductions in prevalence were greater for a. naeslundii, s. constellatus/intermedius, v. parvula, a. israelii/gerencseriae, s. mitis/oralis/sanguis, p. micros, streptococcus mutans and p. intermedia/nigrescens. mean prevalence was decreased more for porphyromonas gingivalis, campylobacter rectus/showae, treponema denticola and bacteroides forsythus in supragingival plaque than subgingival plaque. conclusions: the major finding was the effect of supragingival plaque removal on the composition of the  subgingival microbiota. counts and prevalence of most taxa examined were markedly decreased in both toothbrushing groups. this reduction should translate to a decreased risk of periodontal disease initiation or recurrence. further, the decreased prevalence of periodontal pathogens in supragingival plaque lowers potential reservoirs of these species.
TIHT== 
ABHT== 

PMID== 11328836
TI  == a microbiological study of papillon-lefevre syndrome in two patients.
AB  == aim: to analyse the microflora of subgingival plaque from patients with papillon-lefevre syndrome (pls), which is a very rare disease characterised by palmar-plantar hyperkeratosis with precocious periodontal destruction. methods: bacterial isolates were identified using a combination of commercial identification kits, traditional laboratory tests, and gas liquid chromatography. some isolates were also subjected to partial 16s rdna sequencing. plaque samples  were also assayed for the presence of porphyromonas gingivalis, prevotella intermedia, and actinobacillus actinomycetemcomitans in a quantitative enzyme linked immunosorbent assay (elisa) using monoclonal antibodies. results: the culture results showed that most isolates were capnophilic and facultatively anaerobic species-mainly capnocytophaga spp and streptococcus spp. the latter included s. constellatus, s. oralis, and s. sanguis. other facultative bacteria belonged to the genera gemella, kingella, leuconostoc, and stomatococcus. the aerobic bacteria isolated were species of neisseria and bacillus. anaerobic species included prevotella intermedia, p. melaninogenica, and p. nigrescens, as  well as peptostreptococcus spp. elisa detected p gingivalis in one patient in all sites sampled, whereas a. actinomycetemcomitans was detected in only one site from the other patient. prevotella intermedia was present in low numbers. conclusions: patients with pls have a very complex subgingival flora including recognised periodontal pathogens. however, no particular periodontopathogen is invariably associated with pls.
TIHT== 
ABHT== 

PMID== 11202881
TI  == assessment of periradicular microbiota by dna-dna hybridization.
AB  == in the present study the "checkerboard" dna-dna hybridization technique was used  to identify bacteria in periapical endodontic lesions of asymptomatic teeth. thirty-four patients with root-filled teeth and apical periodontitis were divided into two groups, each containing 17 patients. in group 1, a marginal incision was performed during surgery to expose the lesion, and in group 2, a submarginal incision was applied. the gingiva and mucosa were swabbed with an 0.2% chlorhexidine gluconate solution prior to surgery. bacterial dna was identified in all samples from the two groups using 40 different whole genomic probes. the mean number (+/- sd) of species detected was 33.7 +/- 3.3 in group 1 and 21.3 +/- 6.3 in group 2 (p < 0.001). the majority of the probe-detected bacteria were present in more lesions from group 1 than from group 2. the differences were most notable for campylobacter gracilis, porphyromonas endodontalis, propionibacterium acnes, capnocytophaga gingivalis, fusobacterium nucleatum ssp. nucleatum, fusobacterium nucleatum ssp. polymorphum, prevotella intermedia, treponema denticola, streptococcus constellatus and actinomyces naeslundii i. bacterial species such as actinobacillus actinomycetemcomitans and bacteroides forsythus were detected in more than 60% of the lesions from both groups. also, p. endodontalis was abundant in periapical tissue. the data supported the idea that  following a marginal incision, bacteria from the periodontal pocket might reach the underlying tissues by surgeon-released bacteremia. the study provided solid evidence that bacteria invade the periapical tissue of asymptomatic teeth with apical periodontitis. the detection of much more bacteria with the "checkerboard" dna-dna hybridization method than has previously been recovered by anaerobic culture indicated that the endodontic (and periodontal) microfloras should be redefined using molecular methods.
TIHT== 
ABHT== 

PMID== 11155173
TI  == profile of subgingival microbiota in children with mixed dentition.
AB  == a diversity of microbial species has been detected in children's oral flora at an early age. to investigate the composition of the subgingival microbiota of different groups of teeth in children with mixed dentition, 40 systemically healthy children, aged 7-8 years, randomly chosen, were examined. subgingival plaque samples were taken from the mesiobuccal sites of 21, 41, 16 and 36 permanent teeth and 53, 73, 64 and 84 deciduous teeth. the samples were cultured  for bacterial isolation anaerobically and in 10% co2 plus air using selective and nonselective media. forty-five different microbial species were isolated from both permanent and deciduous teeth. streptococcus sanguis (79-70%), streptococcus mitis (66-65%), prevotella melaninogenica (51-57%), eikenella corrodens (51-52%), capnocytophaga gingivalis (46-34%), capnocytophaga ochracea (45-45%), actinomyces naeslundii (39-60%) and prevotella intermedia (42-35%) were among the most frequently detected species in permanent and deciduous teeth respectively. several suspected periodontal pathogens, such as porphyromonas gingivalis, prevotella loescheii, campylobacter gracilis, bacteroides forsythus, campylobacter concisus, peptostreptococcus micros and selenomonas sputigena, albeit less frequently detected, were present in the microbiota of these children. the bacterial species streptococcus constellatus, peptostreptococcus micros, pseudoramibacter alactolyticus, e. corrodens and fusobacterium nucleatum  were associated with non-bleeding permanent and deciduous teeth whereas streptococcus intermedius, c. concisus, p. intermedia and p. loescheii were associated with bleeding.
TIHT== 
ABHT== 

PMID== 10906266
TI  == characterization of bacterial orofacial infections using a new murine model.
AB  == we devised a new murine orofacial infection model using bacteria from odontogenic infection origins and characterized the experimental infections. in this model, bacteria were injected into the submandible of mice. streptococcus constellatus and peptostreptococcus micros produced a single abscess at the injection site and their abscess-forming and lethal abilities were low: the median abscess-forming dose (af(50)) of s. constellatus and p. micros were 10(8.5-10.7)and 10(10.2-10.6)cfu/mouse, and their median lethal dose (ld(50)) were >11 and 10(10.6-11)cfu/mouse, respectively. prevotella oralis and fusobacterium nucleatum produced multiple abscesses and their abscess-forming and lethal abilities were strong: af(50)of p. oralis and f. nucleatum were 10(6.0-6.4)and 10(7. 0-8.7)cfu/mouse, and their ld(50)were 10(7.0-7.7)and 10(8.3-9. 9)cfu/mouse, respectively. ld(50)of p. intermedia and p. gingivalis were 10(9.4->11)and 10(8.9-9.1)cfu/mouse, respectively. prevotella intermedia and porphyromonas gingivalis generated a necrotizing lesion, which progressed rapidly. we conclude  that this murine model could reflect human orofacial odontogenic infections and is useful to investigate the pathogenicity of causative bacteria of such infections.
TIHT== 
ABHT== 

PMID== 9696261
TI  == serum antibodies reacting with subgingival species in refractory periodontitis subjects.
AB  == the purpose of this investigation was to compare the levels of serum igg antibody to 85 subgingival species in 32 refractory periodontitis, 56 successfully treated, and 33 periodontally healthy subjects. refractory subjects showed mean full mouth attachment loss and/or >3 sites showing attachment loss >2.5 mm within 1 year after 2 treatment modalities, scaling and root planing and surgery plus systemically administered tetracycline. successfully-treated subjects showed mean attachment level gain and no sites with attachment loss >2.5 mm, 1 year post-therapy. periodontally healthy subjects exhibited no pocket or attachment level >3 mm, and no evidence of progressing attachment loss during 1 year of monitoring. baseline serum was obtained from each subject and tested against 85 subgingival species, including reference strains and strains isolated from refractory subjects, using checkerboard immunoblotting. significance of differences in levels of serum antibody among groups were sought using the kruskal-wallis test. refractory subjects constituted a heterogeneous group based  on their serum antibody response to subgingival species. some individuals had antibody reactions to many subgingival species, while other subjects showed fewer or low numbers of responses. on average, refractory subjects exhibited higher numbers and levels of serum antibody reactions to a wide range of subgingival species than successfully treated or periodontally healthy subjects. differences  in serum antibody among clinical groups were more striking at higher threshold levels of antibody (>50 microg/ml and > 100 microg/ml). the data showed that a subject was 10.1 x more likely to be refractory if the subject exhibited antibody reactions with >9 subgingival species at >50 microg/ml (p<0.001, after adjusting  for multiple comparisons). serum antibody to a subset of the test species differed among the clinical groups. porphyromonas gingivalis, bacteroidesforsythus, and some strains isolated from refractory subjects (a novel neisseria sp., enterococcus faecalis, prevotella loescheii and prevotella oulora) elicited high serum antibody in the successfully treated and refractory subjects. high levels of serum antibody to a microbacterium lacticum-like organism, streptococcus oralis, streptococcus constellatus, actinobacillus actinonmycetemcomitans serotype c and haemophilus aphrophilus significantly increased the likelihood of a subject being refractory to conventional periodontal therapy.
TIHT== 
ABHT== 

PMID== 19186419
TI  == immunobiological activities of bacteria isolated from the root canals of postendodontic teeth with persistent periapical lesions.
AB  == although intraradicular bacteria are widely considered to be the primary etiological agents of periapical lesions, the immunobiological properties of the  species in question are not adequately known. the aim of this study, therefore, was to investigate the pathobiological properties of the 10 most frequently isolated endodontopathic bacterial species. using cellular components of the pathogens obtained by sonic extraction, we have investigated their ability to induce monocyte migration, interleukin 1 production, mitogenic responses of lymphocytes, and the polyclonal activation of b lymphocytes. it was found that all of the tested species enhanced the migration of monocytes and induced mitogenesis in b lymphocytes. the polyclonal activation of b cells and the induction of interleukin 1 by monocytes were found to be stronger in gram-negative anaerobes. furthermore, all of the tested species excluding bacteroides oralis were poor t cell mitogens. these findings show that a wide range of pathobiological properties are attributable to the most frequently isolated endodontic pathogens. it thus seems plausible that a battery of complex  immunological responses induced by such microbes lead to the formation of persistent periapical lesions.
TIHT== 
ABHT== 

