@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23538004
TI  == faecal levels of bifidobacterium and clostridium coccoides but not plasma lipopolysaccharide are inversely related to insulin and homa index in women.
AB  == background & aims: the abundance of specific microbes might be associated with plasma lipopolysaccharide and insulin levels. the aims were to quantify the abundance of specific microbes and plasma lps in females and assess their association with anthropometric, body composition and biochemical measurements. methods: seventeen lean (bmi 19-24.99 kg/m(2)) and fifteen obese females (bmi > 30 kg/m(2)) participated. anthropometry, body composition, food intake and biochemical analyses were assessed. bacterial groups in faeces were analysed by qpcr method. results: lactobacillus plantarum prevalence was higher (p = 0.005) and its counts tended to be higher in lean vs. obese group (p = 0.06). bifidobacterium genus, bifidobacterium longum, clostridium coccoides and clostridium leptum counts were higher in lean women (p < 0.05); prevalence and counts of akkermansia muciniphila tended to be higher in lean group (p = 0.09, p  = 0.06, respectively). plasma lps levels were similar between the study groups (p > 0.05). no association was found between lps and bacterial levels or insulin. bifidobacteria and c. coccoides counts were inversely associated with insulin and homa index. conclusions: abundance of specific microbes is distinct between obese and lean women, but is not associated with lps level. bifidobacterial and c. coccoides levels are associated with insulin sensitivity. these bacterial groups  may be capable of modulating insulin action.
TIHT== 
ABHT== 

PMID== 22683836
TI  == molecular monitoring of the development of intestinal microbiota in japanese infants.
AB  == the faecal microbiota of 166 healthy japanese newborns was analysed periodically  from day 1 after birth until the age of 3 years by using the reverse transcription-quantitative pcr. faecal ph and the organic acid concentration were also examined. colonisation by both facultative anaerobes and strict anaerobes was confirmed in 95% of the meconium tested. bifidobacterium-predominant microbiota was established subsequently in most of the infants by 3 months after  birth. bifidobacterium breve, bifidobacterium longum, bifidobacterium infantis, bifidobacterium catenulatum group and bifidobacterium bifidum were the species mainly detected. intergroup correlation analysis revealed that the bifidobacterial population levels, but not other strict anaerobe groups, were found to be negatively correlated with those of the enterobacteriaceae from 7 days until 3 months after birth. faecal ph was maintained at about 6 until 6 months after birth and reached 6.6 at 3 years after birth. the initial concentration of faecal organic acids (19 mum/g of faeces) just after birth increased until 3 years after birth to the level of 111 mum/g of faeces. early start of feeding formula milk promoted colonisation by obligate anaerobes such as the clostridium coccoides group, the clostridium leptum subgroup, prevotella, and atopobium cluster during the 3 months after birth. population levels of the bifidobacteria until 1 month after birth and those of the bacteroides fragilis group until 6 months after birth were lower in infants delivered by caesarean section than in those delivered normally. the results suggested that both earlier start of feeding of formula milk and the mode of infant delivery were found to be important in the development of intestinal microbiota in early infancy.
TIHT== 
ABHT== 

PMID== 19390523
TI  == interplay between weight loss and gut microbiota composition in overweight adolescents.
AB  == the aim of this study was to determine the influence of an obesity treatment program on the gut microbiota and body weight of overweight adolescents. thirty-six adolescents (13-15 years), classified as overweight according to the international obesity task force bmi criteria, were submitted to a calorie-restricted diet (10-40%) and increased physical activity (15-23 kcal/kg body weight/week) program over 10 weeks. gut bacterial groups were analyzed by quantitative real-time pcr before and after the intervention. a group of subjects (n=23) experienced >4.0 kg weight loss and showed significant bmi (p=0.030) and bmi z-score (p=0.035) reductions after the intervention, while the other group (n=13) showed <2.0 kg weight loss. no significant differences in dietary intake were found between both groups. in the whole adolescent population, the intervention led to increased bacteroides fragilis group (p=0.001) and lactobacillus group (p=0.030) counts, and to decreased clostridium coccoides group (p=0.028), bifidobacterium longum (p=0.031), and bifidobacterium adolescentis (p=0.044) counts. in the high weight-loss group, b. fragilis group and lactobacillus group counts also increased (p=0.001 and p=0.007, respectively), whereas c. coccoides group and b. longum counts decreased (p=0.001 and p=0.044, respectively) after the intervention. total bacteria, b. fragilis group and clostridium leptum group, and bifidobacterium catenulatum group counts  were significantly higher (p<0.001-0.036) while levels of c. coccoides group, lactobacillus group, bifidobacterium, bifidobacterium breve, and bifidobacterium  bifidum were significantly lower (p<0.001-0.008) in the high weight-loss group than in the low weight-loss group before and after the intervention. these findings indicate that calorie restriction and physical activity have an impact on gut microbiota composition related to body weight loss, which also seem to be  influenced by the individual's microbiota.
TIHT== 
ABHT== 

PMID== 16085863
TI  == genetic diversity of viable, injured, and dead fecal bacteria assessed by fluorescence-activated cell sorting and 16s rrna gene analysis.
AB  == a novel approach combining a flow cytometric in situ viability assay with 16s rrna gene analysis was used to study the relationship between diversity and activity of the fecal microbiota. simultaneous staining with propidium iodide (pi) and syto bc provided clear discrimination between intact cells (49%), injured or damaged cells (19%), and dead cells (32%). the three subpopulations were sorted and characterized by denaturing gradient gel electrophoresis (dgge) of 16s rrna gene amplicons obtained from the total and bifidobacterial communities. this analysis revealed that not only the total community but also the distinct subpopulations are characteristic for each individual. cloning and sequencing of the dominant bands of the dgge patterns showed that most of clones  retrieved from the live, injured, and dead fractions belonged to clostridium coccoides, clostridium leptum, and bacteroides. we found that some of the butyrate-producing related bacteria, such as eubacterium rectale and eubacterium  hallii, were obviously viable at the time of sampling. however, amplicons affiliated with bacteroides and ruminococcus obeum- and eubacterium biforme-like  bacteria, as well as butyrivibrio crossotus, were obtained especially from the dead population. furthermore, some bacterial clones were recovered from all sorted fractions, and this was especially noticeable for the clostridium leptum cluster. the bifidobacterial phylotypes identified in total samples and sorted fractions were assigned to bifidobacterium adolescentis, bifidobacterium longum,  bifidobacterium infantis, bifidobacterium pseudocatenulatum, and bifidobacterium  bifidum. phylogenetic analysis of the live, dead, and injured cells revealed a remarkable physiological heterogeneity within these bacterial populations; b. longum and b. infantis were retrieved from all sorted fractions, while b. adolescentis was recovered mostly from the sorted dead fraction.
TIHT== 
ABHT== 

PMID== 12477438
TI  == development of a membrane-array method for the detection of human intestinal bacteria in fecal samples.
AB  == a membrane-array method was developed for the detection of human intestinal bacteria in fecal samples without using the expensive microarray-arrayer and laser-scanner. the 16s rdna sequences of 20 predominant human intestinal bacterial species were used to design oligonucleotide probes. three 40-mer oligonucleotides specific for each bacterial species (total 60 probes) were synthesized and applied to nitrocellulose membranes. digoxigenin (dig)-labeled 16s rdnas were amplified by polymerase chain reaction (pcr) from human fecal samples or pure cultured bacteria using two universal primers, and were hybridized to the membrane-array. hybridization signals were read by nbt/bcip color development. the 20 intestinal bacterial species tested were bacteroides thetaiotaomicron, b. vulgatus, b. fragilis, b. distasonis, clostridium clostridiiforme, c. leptum, fusobacterium prausnitzii, peptostreptococcus productus, ruminococcus obeum, r. bromii, r. callidus, r. albus, bifidobacterium  longum, b. adolescentis, b. infantis, eubacterium biforme, e. aerofaciens, lactobacillus acidophilus,escherichia coli, and enterococcus faecium. the two universal primers were able to amplify full size 16s rdna from all of the 20 bacterial species tested. the hybridization results indicated that the membrane-array method is a reliable technique for the detection of predominant human intestinal bacteria in the fecal samples. the result was also confirmed by  using specific pcr methods for these bacteria.
TIHT== 
ABHT== 

PMID== 12167534
TI  == design and evaluation of oligonucleotide-microarray method for the detection of human intestinal bacteria in fecal samples.
AB  == an oligonucleotide-microarray method was developed for the detection of intestinal bacteria in fecal samples collected from human subjects. the 16s rdna  sequences of 20 predominant human intestinal bacterial species were used to design oligonucleotide probes. three 40-mer oligonucleotides specific for each bacterial species (total 60 probes) were synthesized and applied to glass slides. cyanine5 (cy5)-labeled 16s rdnas were amplified by polymerase chain reaction (pcr) from human fecal samples or bacterial dna using two universal primers and were hybridized to the oligo-microarray. the 20 intestinal bacterial species tested were bacteroides thetaiotaomicron, bacteroides vulgatus, bacteroides fragilis, bacteroides distasonis, clostridium clostridiiforme, clostridium leptum, fusobacterium prausnitzii, peptostreptococcus productus, ruminococcus obeum, ruminococcus bromii, ruminococcus callidus, ruminococcus albus, bifidobacterium longum, bifidobacterium adolescentis, bifidobacterium infantis, eubacterium biforme, eubacterium aerofaciens, lactobacillus acidophilus, escherichia coli, and enterococcus faecium. the two universal primers were able to amplify full size 16s rdna from all of the 20 bacterial species tested. the hybridization results indicated that the oligo-microarray method developed in this study is a reliable method for the detection of predominant human intestinal bacteria in the fecal samples.
TIHT== 
ABHT== 

