@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 18312575
TI  == interactions between salivary bifidobacterium adolescentis and other oral bacteria: in vitro coaggregation and coadhesion assays.
AB  == coaggregation assays were performed to investigate interactions between oral bifidobacterium adolescentis and other oral bacterial species. bifidobacterium adolescentis olb6410 isolated from the saliva of healthy humans did not coaggregate with actinomyces naeslundii jcm8350, streptococcus mitis ols3293, streptococcus sanguinis jcm5708, veillonella parvula atcc17745 or porphyromonas gingivalis ob7124, but it did coaggregate with fusobacterium nucleatum jcm8532. subsequent examination of biofilm formation on saliva-coated hydroxyapatite discs using fish revealed that b. adolescentis olb6410 could not directly adhere to the coated discs. it did, however, adhere to biofilms of a. naeslundii, v. parvula, and f. nucleatum, although it did not coaggregate with a. naeslundii nor with v.  parvula. these results suggest that the adhesion of b. adolescentis to tooth surfaces is mediated by other oral bacteria. heat- or proteinase k-treated f. nucleatum could not coaggregate with b. adolescentis. similarly, the coaggregation and coadhesion of proteinase k-treated b. adolescentis were strongly inhibited. it is therefore probable that proteinaceous factors on the cellular surface of b. adolescentis and f. nucleatum are involved in their interaction. the data presented in this study add to our understanding of bifidobacterial colonization in the human oral cavity.
TIHT== 
ABHT== 

PMID== 12438343
TI  == innate immune responses of human neonatal cells to bacteria from the normal gastrointestinal flora.
AB  == the hygiene hypothesis postulates that the prevalence of allergy has increased due to decreased microbial stimulation early in life, leading to delayed maturation of the immune system. the aim of this study was to examine the cytokine pattern produced from cord blood mononuclear cells relative to adult cells after stimulation with bacterial strains from the normal flora. mononuclear cells from cord and adult blood samples were stimulated with the following bacteria: bifidobacterium adolescentis, enterococcus faecalis, lactobacillus plantarum, streptococcus mitis, corynebacterium minutissimum, clostridium perfringens, bacteroides vulgatus, escherichia coli, pseudomonas aeruginosa, veillonella parvula, and neisseria sicca. the levels of interleukin 12 (il-12), tumor necrosis factor alpha (tnf-alpha), il-10, and il-6 were measured by enzyme-linked immunosorbent assay. the tnf-alpha production was also analyzed after blocking cd14, toll-like receptor 2 (tlr-2), and tlr-4 prior to stimulation with bacteria. the levels of il-12 and tnf-alpha were similar in cord and adult cells. gram-positive bacteria induced considerably higher levels of il-12 and tnf-alpha than gram-negative bacteria in both cord and adult cells. the levels of il-6 were significantly higher in newborns than in adults, whereas the levels of  il-10 were similar in newborns and adults. gram-negative and gram-positive bacteria induced similar levels of il-6 and il-10 in cord cells. l. plantarum bound or signaled through cd14, tlr-2, and tlr-4, whereas e. coli acted mainly through cd14 and tlr-4. these results indicate that the innate immune response in newborns to commensal bacteria is strong and also suggest that different bacterial strains may have differential effects on the maturation of the immune system of infants.
TIHT== 
ABHT== 

