@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23548007
TI  == effect of probiotic species on irritable bowel syndrome symptoms: a bring up to date meta-analysis.
AB  == background and objectives: immune system alteration in irritable bowel syndrome (ibs) patients may be modulated by probiotics. we assessed the efficacy of some probiotic species in alleviating characteristic ibs symptoms. material and methods: a meta-analysis of all identified randomized controlled trials comparing probiotics with placebo in treating ibs symptoms was performed with continuous data summarized using standardized mean differences (smds) with 95% confidence intervals (95% cis), where appropriate. the random-effects model was employed in  cases of heterogeneity; otherwise, fixed-effects models were used. results: meta-analysis was performed with 10 of 24 studies identified as suitable for inclusion. probiotics improved pain scores if they contained bifidobacterium breve (smd, - 0.34; 95% ci, - 0.66; -0.02), bifidobacterium longum (smd, -0.48; 95% ci, - 0.91; -0.06), or lactobacillus acidophilus (smd, -0.31; 95% ci, -0.61;  -0.01) species. distension scores were improved by probiotics containing b. breve (smd, -0.45; 95% ci, -0.77; -0.13), bifidobacterium infantis, lactobacillus casei, or lactobacillus plantarum (smd, -0.53; 95% ci, -1.00; -0.06) species. all probiotic species tested improved flatulence: b. breve (smd, -0.42; 95% ci, -0.75;- 0.10), b. infantis, l. casei, l. plantarum (smd, -0.60; 95% ci, -1.07; -0.13), b. longum, l. acidophilus, lactobacillus bulgaricus, and streptococcus salivarius ssp. thermophilus (smd, -0.61; 95% ci, -1.01; -0.21). there was not a  clear positive effect of probiotics concerning the quality of life. conclusions:  some probiotics are an effective therapeutic option for ibs patients, and the effects on each ibs symptom are likely species-specific. future studies must focus on the role of probiotics in modulating intestinal microbiota and the immune system while considering individual patient symptom profiles.
TIHT== 
ABHT== 

PMID== 17718835
TI  == in vitro inhibition activity of nisin a, nisin z, pediocin pa-1 and antibiotics against common intestinal bacteria.
AB  == aims: to evaluate the sensitivity of 21 common intestinal bacteria to six antibiotics and three broad-spectrum bacteriocins (nisins z and a and pediocin pa-1). methods and results: neutralized cell-free culture supernatants containing active bacteriocins, and antibiotics were tested with the agar diffusion test and the disc-diffusion method, respectively. the tested intestinal strains showed high sensitivity to most antibiotics except for streptomycin and oxacillin. nisins a and z (8 mug per well) had similar activity spectra and inhibited all gram-positive intestinal bacteria at different levels (except streptococcus salivarius), with bifidobacteria (except bifidobacterium breve and bif. catenulatum), collinsella aerofaciens and eubacterium biforme being the most sensitive strains, but they were not active against gram-negative bacteria. surprisingly, none of the tested strains were inhibited by pediocin pa-1 (16 mug  per well). conclusion: pediocin pa-1 which is very active against listeria spp. and other food pathogens did not inhibit major intestinal species in the human intestine in contrast to both nisins a and z. significance and impact of the study: our data suggest that pediocin pa-1 has potential to inhibit listeria within the intestinal microbiota without altering commensal bacteria.
TIHT== 
ABHT== 

PMID== 17263590
TI  == spotlight on vsl#3 probiotic mixture in chronic inflammatory bowel diseases.
AB  == vsl#3 (vsl#3) is a high-concentration probiotic preparation of eight live freeze-dried bacterial species that are normal components of the human gastrointestinal microflora, including four strains of lactobacilli (lactobacillus casei, l. plantarum, l. acidophilus, and l. delbrueckii subsp. bulgaricus), three strains of bifidobacteria (bifidobacterium longum, b. breve, and b. infantis), and streptococcus salivarius subsp. thermophilus. data from noncomparative trials suggest that vsl#3 has clinical potential in the treatment  of active mild to moderate ulcerative colitis and as maintenance therapy for patients with ulcerative colitis in remission. in addition, a randomized, open-label, multicenter trial showed that vsl#3 in combination with low-dose balsalazide (a prodrug of mesalazine [mesalamine; 5-aminosalicylic acid]) was more effective than standard doses of basalazide or mesalazine monotherapy in the treatment of acute mild to moderate ulcerative colitis. randomized, double-blind, placebo-controlled studies have shown vsl#3 is effective in preventing the onset  of acute pouchitis in patients with newly formed surgical pouches, and in maintaining remission following antibacterial treatment of acute pouchitis in patients with a history of refractory or recurrent pouchitis. treatment guidelines from the us and the uk include vsl#3 as a therapeutic option for the prevention of pouchitis relapse in patients with chronic pouchitis. in general, vsl#3 was well tolerated in clinical trials. large, well designed, controlled confirmatory clinical trials will further determine the place of vsl#3 in the treatment of ulcerative colitis.
TIHT== 
ABHT== 

PMID== 16903771
TI  == vsl#3 probiotic mixture: a review of its use in chronic inflammatory bowel diseases.
AB  == vsl#3 (vsl#3) is a high-concentration probiotic preparation of eight live freeze-dried bacterial species that are normal components of the human gastrointestinal microflora, including four strains of lactobacilli (lactobacillus casei, l. plantarum, l. acidophilus and l. delbrueckii subsp. bulgaricus), three strains of bifidobacteria (bifidobacterium longum, b. breve and b. infantis) and streptococcus salivarius subsp. thermophilus. data from noncomparative trials suggest that vsl#3 has clinical potential in the treatment  of active mild to moderate ulcerative colitis and as maintenance therapy for patients with ulcerative colitis in remission. in addition, a randomised, open-label, multicentre trial showed that vsl#3 in combination with low-dose balsalazide (a prodrug of mesalazine [mesalamine; 5-aminosalicylic acid]) was more effective than standard doses of basalazide or mesalazine monotherapy in the treatment of acute mild to moderate ulcerative colitis. randomised, double-blind, placebo-controlled studies have shown vsl#3 is effective in preventing the onset  of acute pouchitis in patients with newly formed surgical pouches, and in maintaining remission following antibacterial treatment of acute pouchitis in patients with a history of refractory or recurrent pouchitis. treatment guidelines from the us and the uk include vsl#3 as a therapeutic option for the prevention of pouchitis relapse in patients with chronic pouchitis. in general, vsl#3 was well tolerated in clinical trials. large, well designed, controlled confirmatory clinical trials will further determine the place of vsl#3 in the treatment of ulcerative colitis.
TIHT== 
ABHT== 

PMID== 10985745
TI  == nucleotide sequence, expression and transcriptional analysis of the bifidobacterium longum mb 219 lacz gene.
AB  == the gene encoding beta-galactosidase was isolated by functional complementation of escherichia coli from bifidobacterium longum mb219, which exhibited the highest activity among ten bifidobacterium strains tested of the species b. longum, b. breve, b. adolescentis, b. indicum, b. animalis and b. cuniculi. the nucleotide sequence of the 5.0-kb fragment conferring the positive beta-galactosidase phenotype to e. coli revealed the presence of a lacz-type gene encoding a 1023-amino-acid protein that was preceded by a ribosome binding site.  a sequence showing 72% identity with the proline trna of bacillus subtilis and a  gene probably encoding the dna-3-methyladenine glycosydase i were located downstream from the lacz gene, after a gap of 30-50 unsequenced base pairs. by primer-extension analysis, the transcription start site of the lacz gene was mapped 65 nt upstream from the start codon, and it enabled identification of the  -10 region of the putative promoter. the nucleotide sequence of lacz and its deduced amino acid sequence were compared with those of beta-galactosidase genes  and enzymes from other microorganisms. high similarity was demonstrated between the b. longum beta-galactosidase and its counterparts in lactobacillus delbruckii subsp. bulgaricus, streptococcus salivarius subsp. thermophilus, e. coli, clostridium acetobutylicum, leuconostoc lactis, klebsiella pneumoniae and kluyveromyces marxianus var. lactis, all belonging to the lacz family. the b. longum mb219 lacz gene was cloned in bifidobacterium and its expression was observed in strains with otherwise low levels of endogenous activity. the expression increased by factors of 1.5-50 and enabled those strains that do not grow on lactose to use this sugar as sole carbon source.
TIHT== 
ABHT== 

PMID== 7814703
TI  == absence of cholic acid 7 alpha-dehydroxylase activity in the strains of lactobacillus and bifidobacterium.
AB  == to investigate the presence of 7 alpha-dehydroxylase activity on bile acids in the bacterial strains of fermented milk products, 46 strains of lactobacillus casei, lactobacillus paracasei, lactobacillus rhamnosus, lactobacillus acidophilus, lactobacillus gasseri, bifidobacterium adolescentis, bifidobacterium bifidum, bifidobacterium breve, bifidobacterium infantis, bifidobacterium longum, lactococcus lactis spp. lactis, and streptococcus salivarius spp. thermophilus were tested for their ability to produce deoxycholic acid from cholic acid. the production of deoxycholic acid was quantitatively measured by radiochromatographic analysis in anaerobically prepared washed whole resting cells and by hplc analysis in growing cultures. resting whole cells from a positive control strain, eubacterium lentum-like strain c-25, converted 81.7% of  .2 mm cholic acid to deoxycholic acid and 3.7% to 7-keto-deoxycholic acid, when the cell suspension was incubated anaerobically at a concentration of 2 mg of protein/ml for 4 h at ph 7.3. however, none of the test strains investigated in this study was able to transform cholic acid under the same conditions. in growing cultures, 91.5% of 150 micrograms/ml of cholic acid was transformed to deoxycholic acid and 1.1% to 7-keto-deoxycholic acid by e. lentum-like c-25 after a 7-d anaerobic incubation. none of the test strains showed production of either  deoxycholic acid or 7-keto-deoxycholic acid as growing cultures.
TIHT== 
ABHT== 

