@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25572742
TI  == probiotic bacteria lactobacillus and bifidobacterium attenuate inflammation in dextran sulfate sodium-induced experimental colitis in mice.
AB  == it is widely accepted that inflammatory bowel disease (ibd) arises from a dysregulated mucosal immune response to the enteric microbiota in the gut of a genetically susceptible individual. no definitive therapies are available for this inflammatory disorder. therefore it became imperative to develop new strategies for treating this disease. probiotics have emerged as a potential new  therapeutic strategy for ibd, however their exact mechanisms of action is still poorly defined. in this study, we address the potential effect of a probiotic cocktail (ultrabiotique(r)) composed of four live bacterial strains (l. acidophilus, l. plantarum, b. lactis and b.breve) to promote recovery from acute  colitis. probiotic was given to mice by oral gavage after the onset of colitis and the establishment of dextran sulfate sodium (dss)-induced intestinal injury.  clinical parameters were monitored daily, histological scores of colitis and the  production of nitric oxide (no) and interferon-&#947; (ifn-&#947;) were determined. in addition, tlr4, nf-&#954;b and inos colonic expression were examined. probiotic treatment ameliorated clinical symptoms and histological scores. no and ifn-&#947; production in plasma were decreased by probiotic. these results were associated with reduced tlr4, inos and nf-&#1082;b expression in colonic tissue. in conclusion, probiotic exerted anti-inflammatory effects and contributed to a rapid recovery of dss-induced acute colitis.
TIHT== 
ABHT== 

PMID== 25059277
TI  == a novel multi-strain probiotic and synbiotic supplement for prevention of clostridium difficile infection in a murine model.
AB  == the protective effect of a multi-strain probiotic and synbiotic formulation was evaluated in c57bl/6 mice infected with clostridium difficile (cd) nap1/027. antibiotic-treated mice were divided into the following four groups: group 1, fed with a synbiotic formulation consisting of lactobacillus plantarum f44, l. paracasei f8, bifidobacterium breve 46, b. lactis 8:8, galacto-oligosaccharides,  isomalto-oligosaccharides, and resistant starch; group 2, fed with the same four  probiotic strains as group 1; group 3, fed with the same prebiotic supplements as group 1 for 7 days before cd infection; and group 4 (control group) antibiotic treated and infected with nap1/027 strain. feces and cecal contents were collected for microbial cell viability, quantitative pcr (qpcr), toxin analyses and histopathology. synbiotics- and probiotics-fed mice showed a significant increase in total bifidobacteria (p < 0.05). the total lactobacilli count was increased in group 1. tests for cecal toxins were negative in group 2 mice, whereas one sample each from group 1 and 3 was positive. qpcr of cecal contents showed significant reduction in nap1/027 dna copies in groups 1 and 2 and significantly higher numbers of b. breve 46, l. plantarum f44, and l. paracasei f8 in groups 1 and 2 (p < 0.05); these changes were much less pronounced in groups 3 and 4. our findings indicate that the newly developed synbiotic or multi-strain probiotic formulation confers protection against nap1/027 infection  in c57bl/6 mice. this holds promise for performing human studies.
TIHT== 
ABHT== 

PMID== 25045346
TI  == survival and synergistic growth of mixed cultures of bifidobacteria and lactobacilli combined with prebiotic oligosaccharides in a gastrointestinal tract simulator.
AB  == background: probiotics, especially in combination with non-digestible oligosaccharides, may balance the gut microflora while multistrain preparations may express an improved functionality over single strain cultures. in vitro gastrointestinal models enable to test survival and growth dynamics of mixed strain probiotics in a controlled, replicable manner. methods: the robustness and compatibility of multistrain probiotics composed of bifidobacteria and lactobacilli combined with mixed prebiotics (galacto-, fructo- and xylo-oligosaccharides or galactooligosaccharides and soluble starch) were studied using a dynamic gastrointestinal tract simulator (gits). the exposure to acid and bile of the upper gastrointestinal tract was followed by dilution with a continuous decrease of the dilution rate (de-celerostat) to simulate the descending nutrient availability of the large intestine. the bacterial numbers and metabolic products were analyzed and the growth parameters determined. results: the most acid- and bile-resistant strains were lactobacillus plantarum f44 and l. paracasei f8. bifidobacterium breve 46 had the highest specific growth rate and, although sensitive to bile exposure, recovered during the dilution phase in most experiments. b. breve 46, l. plantarum f44, and l. paracasei f8 were selected as the most promising strains for further studies. conclusions: de-celerostat cultivation can be applied to study the mixed bacterial cultures under defined conditions of decreasing nutrient availability to select a compatible set of strains.
TIHT== 
ABHT== 

PMID== 24471378
TI  == in vitro anti-inflammatory activity of selected oxalate-degrading probiotic bacteria: potential applications in the prevention and treatment of hyperoxaluria.
AB  == oxalate (ox) is a very common component of the human diet, capable to collect in  the renal tissue and bind calcium to form calcium oxalate (caox) crystals. a supersaturation of caox crystal may cause nephrocalcinosis and nephrolithiasis. the inflammation derived from the caox crystal accumulation, together with innate or secondary renal alterations, could strongly affect the renal function. in this case a consumption of probiotics with either oxalate-degrading activity at intestinal level and systemic anti-inflammatory activity could be an alternative  approach to treat the subjects with excess of urinary oxalate excretion. 11 strains of lactic acid bacteria (lactobacilli and bifidobacteria), already included in the list of bacteria safe for the human use, were investigated for their capability to degrade oxalate by mean of rp-hplc-uv method and modulate inflammation in an in vitro model system based on peripheral blood mononuclear cells. four promising bacterial strains (lactobacillus plantarum pbs067, lactobacillus acidophilus la-14, bifidobacterium breve pbs077, bifidobacterium longum pbs078) were identified as innovative biological tools for the prevention  and the therapeutic treatment of hyperoxaluria and the inflammatory events associated to the ox accumulation. practical application: the oxalate-degrading activity of some probiotics and their capability to modulate the release of inflammation mediators could be exploited as a new nutraceutical and therapeutic  approach for the treatment of oxalate accumulation and the related inflammatory state.
TIHT== 
ABHT== 

PMID== 24411490
TI  == the effects of co-administration of probiotics with herbal medicine on obesity, metabolic endotoxemia and dysbiosis: a randomized double-blind controlled clinical trial.
AB  == background & aims: probiotics help maintain balance in composition of the gut microbiota, and have been considered as a potential treatment for obesity. this study was conducted in order to assess the effects of probiotics when combined with herbal medicine in treatment of obesity. probiotics were tested for the ability to modulate gut microbiota, gut permeability, and endotoxin level, which  may have correlation with factors involved in obesity. methods: a randomized, double-blind, placebo controlled study was conducted, in which patients with higher bmi (>25 kg/m(2)) and waist circumference (>85 cm) were enrolled and randomly assigned to receive bofutsushosan with either probiotics or placebo capsules for a period of eight weeks. assessment of body composition parameters,  metabolic biomarkers, endotoxin level, gut permeability, and fecal bacteria in stool was performed at baseline and at week 8. the study was registered at the clinical research information service, approved by the korea national institute of health (kct0000386). results: although both groups showed a significant reduction in weight and waist circumference (p = 0.000), no significant differences in body composition and metabolic markers were observed. in correlation analysis, change in body composition showed positive correlation with endotoxin level (r = 0.441, p < 0.05 for bw; and r = 0.350, p < 0.05 for fat mass) and the population of gut lactobacillus plantarum (r = 0.425, p < 0.05 for  bw; and r = 0.407, p < 0.05 for bmi). the gram negative bacterial population in gut also exhibited positive correlation with changes in body composition (wc) and total cholesterol level (r = 0.359, and 0.393, for the former and later parameters, respectively, p < 0.05 for both). while, the profile of gut bifidobacterium breve population showed negative correlation with endotoxin level (r = -0.350, p < 0.05). conclusions: correlations between gut microbiota and change in body composition indicate that probiotics may influence energy metabolism in obesity. correlation between endotoxin level and weight reduction indicates that probiotics may play an important role in prevention of endotoxin production, which can lead to gut microbiota dysbiosis associated with obesity.
TIHT== 
ABHT== 

PMID== 24158048
TI  == mechanisms of cholesterol-lowering effects of lactobacilli and bifidobacteria strains as potential probiotics with their bsh gene analysis.
AB  == the bile salt hydrolase (bsh) enzyme activities of human-derived lactic acid bacteria and bifidobacteria were evaluated. the highest enzyme activity was identified as 1.76 +/- 0.23 u/mg protein for bifidobacterium breve a26 and 1.42 +/- 0.11 u/mg protein for lactobacillus plantarum la3. the bile salt deconjugation ability of the 6 isolates representing the highest bsh enzyme activity was calculated as the release of cholic acid and was between the range of 2.03 +/- 0.22 and 1.05 +/- 0.25 mm. the strains with high bsh enzyme activity  also showed high deconjugation ability (p < 0.01). the effect of increasing bile  concentrations on the growth of bacteria and their cholesterol removal abilities  based on cholesterol precipitation were determined. cholesterol removal in control medium was between 22.6 +/- 0.4 and 26.5 +/- 0.4%. the highest value was  recorded at a 0.2% bile concentration. as the biliary concentration increased, a  decrease in cholesterol removal and viability of the bacteria was noted in all strains. the percent of similarity of the bsh gene region between different genes was specified. the results may throw some light on proving the ability of these probiotics either as a novel alternative or as adjuvants to chemical drugs in treating hypercholesterolemia.
TIHT== 
ABHT== 

PMID== 23638770
TI  == beneficial role of the probiotic mixture ultrabiotique on maintaining the integrity of intestinal mucosal barrier in dss-induced experimental colitis.
AB  == the etiology of inflammatory bowel diseases which include ulcerative colitis (uc) and crohn disease has not yet been clarified. several hypotheses suggest a change in composition of gut microflora along with an impaired mucosal barrier that lead to excessive mucosal immunologic responses. increased production of nitric oxide  (no) contributes greatly to the tissue injury caused by chronic inflammation. evidence indicates that the mucus layer covering the epithelium is altered during uc and experimental colitis. our aim in this study was to investigate the potential therapeutic effect of probiotic during dss-induced colitis by modulating the immune system and colonic mucus production. for that purpose, the  probiotic formulation ultrabiotique((r)) (lactobacillus acidophilus, bifidobacterium lactis, lactobacillus plantarum and bifidobacterium breve) was administered daily for 7 d to mice with colitis. probiotic supplementation improved clinical symptoms and histological alterations observed during dss induced colitis. ultrabiotique((r)) treatment down regulated the no production by peritoneal macrophages of dss-treated mice and enhanced mucus production in both  dss-treated and healthy mice. in conclusion, the modification of microflora by the ultrabiotique((r)) played a beneficial role in maintaining the integrity of the intestinal mucosal barrier and promoted tissue repair.
TIHT== 
ABHT== 

PMID== 23548007
TI  == effect of probiotic species on irritable bowel syndrome symptoms: a bring up to date meta-analysis.
AB  == background and objectives: immune system alteration in irritable bowel syndrome (ibs) patients may be modulated by probiotics. we assessed the efficacy of some probiotic species in alleviating characteristic ibs symptoms. material and methods: a meta-analysis of all identified randomized controlled trials comparing probiotics with placebo in treating ibs symptoms was performed with continuous data summarized using standardized mean differences (smds) with 95% confidence intervals (95% cis), where appropriate. the random-effects model was employed in  cases of heterogeneity; otherwise, fixed-effects models were used. results: meta-analysis was performed with 10 of 24 studies identified as suitable for inclusion. probiotics improved pain scores if they contained bifidobacterium breve (smd, - 0.34; 95% ci, - 0.66; -0.02), bifidobacterium longum (smd, -0.48; 95% ci, - 0.91; -0.06), or lactobacillus acidophilus (smd, -0.31; 95% ci, -0.61;  -0.01) species. distension scores were improved by probiotics containing b. breve (smd, -0.45; 95% ci, -0.77; -0.13), bifidobacterium infantis, lactobacillus casei, or lactobacillus plantarum (smd, -0.53; 95% ci, -1.00; -0.06) species. all probiotic species tested improved flatulence: b. breve (smd, -0.42; 95% ci, -0.75;- 0.10), b. infantis, l. casei, l. plantarum (smd, -0.60; 95% ci, -1.07; -0.13), b. longum, l. acidophilus, lactobacillus bulgaricus, and streptococcus salivarius ssp. thermophilus (smd, -0.61; 95% ci, -1.01; -0.21). there was not a  clear positive effect of probiotics concerning the quality of life. conclusions:  some probiotics are an effective therapeutic option for ibs patients, and the effects on each ibs symptom are likely species-specific. future studies must focus on the role of probiotics in modulating intestinal microbiota and the immune system while considering individual patient symptom profiles.
TIHT== 
ABHT== 

PMID== 23535766
TI  == efficacy of different probiotic combinations on death and necrotizing enterocolitis in a premature rat model.
AB  == objective: the aim of the present study was to investigate the most effective probiotic combinations to prevent death and necrotizing enterocolitis (nec) in a  premature rat model. methods: one hundred fifty-eight premature sprague-dawley premature rats were enrolled. probiotic strains bifidobacterium bifidum, b longum, lactobacillus acidophilus, l plantarum, and b breve were fed as a single  strain or mixture with 2 or 3 strains for a total of 9 study groups; control groups received no exogenous probiotic supplement. fecal samples were collected for 72 hours to detect probiotic strains and pathologic strains by real-time polymerase chain reaction. colony counts of probiotic strains escherichia coli and klebsiella were compared between groups before and after 36 hours of the study period. the incidence of death and nec were compared via fisher exact test  between groups. results: the results demonstrated that l plantarum alone (p = 0.0026) and b bifidum with b longum together (p = 0.0017) were more effective in  reducing nec as compared with the control group. all of the study groups except b breve and b bifidum with b breve definitely prevented death compared with controls. b bifidum and b longum together had significantly lower mortality than  the control group (p < 0.0001). colony counts of e coli and klebsiella in stool samples were significantly decreased in the b bifidum, b longum, and l plantarum  group compared with the other study and control groups after 36 hours. conclusions: administration of a mixture of probiotic strains with b bifidum and  b longum was most effective in preventing death and nec in this animal model, and these observations provide an evidence-based strategy for designing further neonatal clinical trials.
TIHT== 
ABHT== 

PMID== 22955353
TI  == assessment of the in vitro inhibitory activity of specific probiotic bacteria against different escherichia coli strains.
AB  == background: lactobacilli and bifidobacteria are often associated with health-promoting effects. these live microorganisms, defined as probiotics, are commonly consumed as part of fermented foods, such as yoghurt and fermented milks, or as dietary supplements. escherichia coli is a gram-negative, rod-shaped bacterium commonly found in the lower intestine of warm-blooded organisms. as a part of the normal gut microbiota, this microorganism colonizes the gastrointestinal tract of animals and humans within a few hours after birth. all  e. coli strains can produce a wide variety of biogenic amines responsible for potentially harmful systemic intoxications. enterohemorrhagic e. coli serotype o157:h7 is a pathotype of diarrhoeagenic strains with a large virulence plasmid po157 able to produce 1 or more shiga toxins. methods: the overall aim of this study was to determine the inhibitory effects of different strains of probiotics  on e. coli serotypes, including e. coli o157:h7 (cq9485). in particular, the antagonistic activity of 4 bifidobacterium strains (probiotical spa, italy) and 16 lactic acid bacteria, more specifically 14 lactobacillus spp. and 2 streptococcus spp., was assessed against selected e. coli biotypes (atcc 8739, atcc 10536, atcc 35218, and atcc 25922). the diarrhoeagenic serotype o157:h7 was  also tested. results: the experimental data collected demonstrated an in vitro significant inhibitory effect of 6 lactobacillus strains, namely l. rhamnosus lr04, l. rhamnosus lr06, l. plantarum lp01, l. plantarum lp02, l. pentosus lps01, and l. delbrueckii subsp. delbrueckii ldd01, and 2 bifidobacterium strains, b. breve br03 and b. breve b632. the inhibiting extent was slightly different among  these strains, with l. delbrueckii subsp. delbrueckii ldd01 showing the highest activity on e. coli o157:h7. conclusions: most of the probiotics studied are able to antagonize the growth of the 5 strains of e. coli tested, including the o157:h7 biotype, well known for their characteristic to produce a wide variety of biogenic amines considered responsible for dangerous systemic intoxications.
TIHT== 
ABHT== 

PMID== 22452835
TI  == effects of probiotics and antibiotics on the intestinal homeostasis in a computer controlled model of the large intestine.
AB  == background: antibiotic associated diarrhea and clostridium difficile infection are frequent complications of broad spectrum antibiotic therapy. probiotic bacteria are used as therapeutic and preventive agents in these disorders, but the exact functional mechanisms and the mode of action are poorly understood. the effects of clindamycin and the probiotic mixture vsl#3 (containing the 8 bacterial strains streptococcus thermophilus, bifidobacterium breve, bifidobacterium longum, bifidobacterium infantis, lactobacillus acidophilus, lactobacillus plantarum, lactobacillus paracasei and lactobacillus delbrueckii subsp. bulgaricus) consecutively or in combination were investigated and compared to controls without therapy using a standardized human fecal microbiota in a computer-controlled in vitro model of large intestine. microbial metabolites (short chain fatty acids, lactate, branched chain fatty acids, and ammonia) and the intestinal microbiota were analyzed. results: compared to controls and combination therapy, short chain fatty acids and lactate, but also ammonia and branched chain fatty acids, were increased under probiotic therapy. the metabolic pattern under combined therapy with antibiotics and probiotics had the most beneficial and consistent effect on intestinal metabolic profiles. the intestinal microbiota showed a decrease in several indigenous bacterial groups under antibiotic therapy, there was no significant recovery of these groups when the antibiotic therapy was followed by administration of probiotics. simultaneous application of anti- and probiotics had a stabilizing effect on the intestinal microbiota with increased bifidobacteria and lactobacilli. conclusions: administration of vsl#3 parallel with the clindamycin therapy had a beneficial and stabilizing effect on the intestinal metabolic homeostasis by decreasing toxic metabolites and protecting the endogenic microbiota from destruction. probiotics could be a reasonable strategy in prevention of antibiotic associated  disturbances of the intestinal homeostasis and disorders.
TIHT== 
ABHT== 

PMID== 22157240
TI  == the effect of a multispecies probiotic mixture on the symptoms and fecal microbiota in diarrhea-dominant irritable bowel syndrome: a randomized, double-blind, placebo-controlled trial.
AB  == background: the clinical effect of probiotics on irritable bowel syndrome (ibs) is still controversial. aims: we aimed to evaluate the effects of a probiotic mixture on ibs symptoms and the composition of fecal microbiota in patients with  diarrhea-dominant ibs (d-ibs). methods: fifty patients with d-ibs were randomized into placebo or probiotic mixture (lactobacillus acidophilus, lactobacillus plantarum, lactobacillus rhamnosus, bifidobacterium breve, bifidobacterium lactis, bifidobacterium longum, and streptococcus thermophilus 1.0x10 cfu) groups. treatment was taken daily for 8 weeks. the primary outcome was adequate relief (ar) of overall ibs symptoms, which was assessed weekly for 10 weeks. a responder was defined as a patient who experienced ar for at least half of the 10-week study period. secondary outcomes included the effects on individual symptoms, stool parameters, and ibs quality of life. the fecal flora compositions were analyzed by polymerase chain reaction denaturing gradient gel electrophoresis (dgge). results: the proportion of ar was consistently higher in  the probiotics group than in the placebo group throughout the 10-week period (p<0.05). the proportion of responders was significantly higher in the probiotics group than in the placebo group (48% vs. 12%, p=0.01). stool consistency improved significantly in the probiotics group compared with the placebo group. percent changes in individual symptom scores were similar in the 2 groups, but ibs quality of life improvement tended to be higher in the probiotics group. comparison of denaturing gradient gel electrophoresis profiles of fecal flora showed that the concordance rate between bacterial compositions before and after  treatment was significantly higher in the probiotics group than in the placebo group (69.5% vs. 56.5%, p=0.005). conclusions: the probiotic mixture was effective in providing ar of overall ibs symptoms and improvement of stool consistency in d-ibs patients, although it had no significant effect on individual symptoms. the therapeutic effect of probiotics is associated with the  stabilization of intestinal microbiota.
TIHT== 
ABHT== 

PMID== 21986357
TI  == in vitro assessment of the immunomodulatory effects of multispecies probiotic formulations for management of allergic diseases.
AB  == modulation of the composition of the intestinal microbiota with probiotics could  possibly offer a way of prevention or management of allergic diseases. the objective of this study was to determine the immunomodulating effects of various  multispecies probiotic combinations in vitro, as preamble to application in vivo. multispecies probiotic combinations were formulated and tested for their effects  on in vitro cytokine production by human mononuclear cells and were compared to products that already have shown beneficial effects in vivo. all 4 tested combinations of probiotics showed a 40-71% decrease of th2 cytokine production (il-4, il-5, and il-13) and a variable increase of th1 (ifn-gamma) and treg cytokine (il-10) production compared to the medium. a specific probiotic mixture  that contained bifidobacterium breve w25, bifidobacterium lactis atcc sd 5219, b. lactis atcc sd 5220, lactobacillus plantarum w62, lactobacillus salivarius w57 and lactococcus lactis w19 was superior in its stimulating effect on il-10 production (significant better than the other tested combinations; p=0.001). modulation of in vitro cytokine production profiles can be used to differentiate  between selected probiotic formulations for their immunomodulatory properties. in the future it should be demonstrated whether the immunomodulatory capacities from the multispecies probiotic formulation with the desired profile will be effective in vivo (in adolescents, followed by application in children).
TIHT== 
ABHT== 

PMID== 21839384
TI  == effect of grape polyphenols on lactic acid bacteria and bifidobacteria growth: resistance and metabolism.
AB  == food polyphenols are able to selectively modify the growth of susceptible micro-organisms. this study describes the effect of a flavan-3-ol enriched grape  seed extract (gse) on the growth of several lactic acid bacteria (lab) and bifidobacteria and the ability of the resistant strains to metabolize these compounds. streptococcus thermophilus, lactobacillus fermentum, lactobacillus acidophilus and lactobacillus vaginalis strains showed a remarkable sensitivity to the phenolic extracts assayed, including a gse fraction consisting mainly in (+)-catechin and (-)-epicatechin (gse-m). on the other hand, lactobacillus plantarum, lactobacillus casei, and lactobacillus bulgaricus strains reached maximal growth with the gse fractions, including a rich-oligomeric (gse-o) fraction. within bifidobacteria, bifidobacterium lactis bb12 showed the highest sensitivity to the phenolic extracts assayed, whereas bifidobacterium breve 26m2  and bifidobacterium bifidum hdd541 reached maximum growth in presence of gse-o and gse-m fractions. metabolism of flavan-3-ols by lab and bifidobacteria resistant strains was investigated in vitro. the results revealed that only l. plantarum ifpl935 was able to metabolize the polyphenols studied by means of galloyl-esterase, decarboxylase and benzyl alcohol dehydrogenase activities that  led to the formation of gallic acid, pyrogallol and catechol, respectively. an unknown metabolite that does not exhibit a phenolic-acid-type structure was also  detected, which suggests a new enzyme activity in l. plantarum ifpl935 able to degrade flavan-3-ol monomers.
TIHT== 
ABHT== 

PMID== 20697291
TI  == the use of probiotics in healthy volunteers with evacuation disorders and hard stools: a double-blind, randomized, placebo-controlled study.
AB  == background: evacuation disorders and hard stools are common in industrialized countries, affecting on average 12% to 17% of the adult healthy population at any age. dietary supplementation with probiotic microorganisms may be useful in reducing the disorder. methods: we performed a double-blind, randomized, placebo-controlled study to evaluate the effectiveness of 2 different probiotic blends, either mixed lactobacillus plantarum lp01 (lmg p-21021) and bifidobacterium breve br03 (dsm 16604) or bifidobacterium animalis subspecies lactis bs01 (lmg p-21384), in the management of evacuation disorders and intestinal discomfort. in a period of 5 years (2003 to 2008), the study involved  300 healthy volunteers (151 males and 149 females; age 24 to 71 y) with evacuation disorders and hard stools. in particular, subjects were divided into 3 groups: 80 subjects in the group a received placebo, 110 subjects in the group b  received mixed l. plantarum lp01 and b. breve br03 (2.5 x 10 colony-forming units/d of each strain), and 110 subjects in the group c received b. animalis subsp. lactis bs01 (5 x 10 colony-forming units/d) for 30 days. at the beginning  of the observational study, the healthy status of volunteers was evaluated by a complete, laboratory and ultrasound study of the abdomen. the physical examination was repeated after 15 and 30 days. in particular, the main troubles typically associated with evacuation disorders and hard stools as well as abdominal bloating were considered as parameters of interest. exclusion criteria  were items of gastrointestinal diseases and antibiotics intake. results: subjects treated with the mixed probiotic strains l. plantarum lp01 and b. breve br03 or b. animalis subsp. lactis bs01 reported a significant improvement in the number of weekly bowel movements and in the main troubles associated with evacuations, particularly consistency of feces and ease of expulsion. discomfort items such as abdominal bloating and anal itching, burning, or pain also registered a relevant  improvement in the active groups receiving probiotics. conclusions: the intake of an effective amount of mixed l. plantarum lp01 and b. breve br03 or b. animalis subsp. lactis bs01 for 30 days is able to significantly relieve the evacuation disorders and hard stools, thus providing a useful tool for the management of such condition, which is particularly widespread in industrialized countries at any age.
TIHT== 
ABHT== 

PMID== 20697290
TI  == evaluation of the intestinal colonization by microencapsulated probiotic bacteria in comparison with the same uncoated strains.
AB  == background: beneficial findings concerning probiotics are increasing day by day.  however, one of the most important parameter which affects the probiotic activity of a microorganism is its survival during the gastroduodenal transit. some microencapsulation techniques could be applied to bacterial cells to improve this parameter. methods: a comparison between the intestinal colonization by microencapsulated bacteria and the same not microencapsulated strains has been conducted in a double blind, randomized, cross-over study. the study (april to july 2005) involved 44 healthy volunteers. in particular, participants were divided into 2 groups: group a (21 participants) received a mix of probiotic strains lactobacillus plantarum lp01 (lmg p-21021) and bifidobacterium breve br03 (dsm 16604) in an uncoated form, group b (23 participants) was given the same strains microencapsulated with a gastroresistant material. the not microencapsulated strains were administered at 5 x 10(9) colony forming units/strain/d for 21 days, whereas the microencapsulated bacteria were given at  1 x 10(9) colony forming units/strain/d for 21 days. at the end of the first period of treatment with probiotics a 3 weeks washout phase has been included in  the study protocol. at the end of the washout period the groups were crossed: in  detail, group a had the microencapsulated and group b the uncoated bacteria. the  administered amounts of each strain were the same as the first treatment. the quantitative evaluation of intestinal colonization by strains microencapsulated or not microencapsulated was made by fecal samples examination at the beginning of the clinical trial, after 10 and 21 days of each treatment period. in particular, fecal heterofermentative lactobacilli and bifidobacteria have been counted. results: a statistically significant increase in the fecal amounts of lactobacilli and bifidobacteria was recorded in both groups at the end of each treatment compared with d0 or d42 (p<0.0001 and p<0.0001 at d21, p<0.0001 and p<0.0001 at d63 for lactobacilli and bifidobacteria, respectively), confirming the ability of the 2 strains to colonize the human gut, either in a gastroprotected form or not. participants treated with the microencapsulated bacteria reported a kinetics of intestinal colonization quite similar to participants who received not coated strains. conclusions: probiotics are able to exert many different beneficial effects on the human host. these effects are mediated by the number of viable cells which reach the gut. the microencapsulation technique used in this study is a valid strategy to significantly improve gastroresistance of strains, thus enhancing their probiotic activity and allowing the use of a 5 times lower amount.
TIHT== 
ABHT== 

PMID== 19752564
TI  == oral treatment with probiotics reduces allergic symptoms in ovalbumin-sensitized  mice: a bacterial strain comparative study.
AB  == background/aim: evidence demonstrating an important role of the intestinal microbiota in the incidence of allergic disorders has led to the concept of using probiotics as possible antiallergic therapy. this study aimed to select a bacterial strain with the best antiallergic treatment effects from a panel of 6 bacterial strains in a mouse model of ovalbumin(ova)-allergic asthma. methods: ova-sensitized balb/c mice were orally administered the bacterial strains bifidobacterium breve m-16v, b. infantis numres251, b. animalis numres252 and numres253, lactobacillus plantarum numres8 and l. rhamnosus numres6. after challenge by ova inhalation in the lungs, the response to methacholine was measured. pulmonary inflammation was assessed by analyzing bronchoalveolar lavage fluid for the presence of eosinophils, neutrophils, macrophages and lymphocytes and for interleukin 4, interleukin 5, interleukin 10 and interferon-gamma. ova-specific ige, igg1 and igg2a were measured in serum. next, the effect on acute allergic skin reaction was measured after treatment with b. breve m-16v and l. plantarum numres8. results: of the panel of 6 strains, b. breve m-16v and l. plantarum numres8 inhibited (1) the response to methacholine, (2) reduced the number of eosinophils in the bronchoalveolar lavage fluid, (3) reduced both ova-specific ige and (4) ova-specific igg1, whereas the other strains did not affect all these parameters simultaneously. b. breve m-16v but not l. plantarum numres8 reduced interleukin 4, interleukin 5 and interleukin 10. furthermore, b.  breve m-16v but not l. plantarum numres8 reduced acute allergic skin reactions to ova. conclusion: b. breve m-16v was identified as the most potent antiallergic strain.
TIHT== 
ABHT== 

PMID== 19118369
TI  == mechanism of conjugated linoleic acid and vaccenic acid formation in human faecal suspensions and pure cultures of intestinal bacteria.
AB  == faecal bacteria from four human donors and six species of human intestinal bacteria known to metabolize linoleic acid (la) were incubated with la in deuterium oxide-enriched medium to investigate the mechanisms of conjugated linoleic acid (cla) and vaccenic acid (va) formation. the main cla products in faecal suspensions, rumenic acid (cis-9,trans-11-cla; ra) and trans-9,trans-11-cla, were labelled at c-13, as were other 9,11 geometric isomers. traces of trans-10,cis-12-cla formed were labelled to a much lower extent. in pure culture, bifidobacterium breve ncfb 2258 formed labelled ra and trans-9,trans-11-cla, while butyrivibrio fibrisolvens 16.4, roseburia hominis a2-183t, roseburia inulinivorans a2-192t and ruminococcus obeum-like strain a2-162 converted la to va, labelled in a manner indicating that va was formed via c-13-labelled ra. propionibacterium freudenreichii subsp. shermanii dsm 4902t, a  possible probiotic, formed mainly ra with smaller amounts of trans-10,cis-12-cla  and trans-9,trans-11-cla, labelled the same as in the mixed microbiota. ricinoleic acid (12-oh-cis-9-18 : 1) did not form cla in the mixed microbiota, in contrast to cla formation described for lactobacillus plantarum. these results were similar to those reported for the mixed microbiota of the rumen. thus, although the bacterial genera and species responsible for biohydrogenation in the rumen and the human intestine differ, and a second route of ra formation via a 10-oh-18 : 1 is present in the intestine, the overall labelling patterns of different cla isomers formation are common to both gut ecosystems. a hydrogen-abstraction enzymic mechanism is proposed that may explain the role of a 10-oh-18 : 1 intermediate in 9,11-cla formation in pure and mixed cultures.
TIHT== 
ABHT== 

PMID== 17263590
TI  == spotlight on vsl#3 probiotic mixture in chronic inflammatory bowel diseases.
AB  == vsl#3 (vsl#3) is a high-concentration probiotic preparation of eight live freeze-dried bacterial species that are normal components of the human gastrointestinal microflora, including four strains of lactobacilli (lactobacillus casei, l. plantarum, l. acidophilus, and l. delbrueckii subsp. bulgaricus), three strains of bifidobacteria (bifidobacterium longum, b. breve, and b. infantis), and streptococcus salivarius subsp. thermophilus. data from noncomparative trials suggest that vsl#3 has clinical potential in the treatment  of active mild to moderate ulcerative colitis and as maintenance therapy for patients with ulcerative colitis in remission. in addition, a randomized, open-label, multicenter trial showed that vsl#3 in combination with low-dose balsalazide (a prodrug of mesalazine [mesalamine; 5-aminosalicylic acid]) was more effective than standard doses of basalazide or mesalazine monotherapy in the treatment of acute mild to moderate ulcerative colitis. randomized, double-blind, placebo-controlled studies have shown vsl#3 is effective in preventing the onset  of acute pouchitis in patients with newly formed surgical pouches, and in maintaining remission following antibacterial treatment of acute pouchitis in patients with a history of refractory or recurrent pouchitis. treatment guidelines from the us and the uk include vsl#3 as a therapeutic option for the prevention of pouchitis relapse in patients with chronic pouchitis. in general, vsl#3 was well tolerated in clinical trials. large, well designed, controlled confirmatory clinical trials will further determine the place of vsl#3 in the treatment of ulcerative colitis.
TIHT== 
ABHT== 

PMID== 16903771
TI  == vsl#3 probiotic mixture: a review of its use in chronic inflammatory bowel diseases.
AB  == vsl#3 (vsl#3) is a high-concentration probiotic preparation of eight live freeze-dried bacterial species that are normal components of the human gastrointestinal microflora, including four strains of lactobacilli (lactobacillus casei, l. plantarum, l. acidophilus and l. delbrueckii subsp. bulgaricus), three strains of bifidobacteria (bifidobacterium longum, b. breve and b. infantis) and streptococcus salivarius subsp. thermophilus. data from noncomparative trials suggest that vsl#3 has clinical potential in the treatment  of active mild to moderate ulcerative colitis and as maintenance therapy for patients with ulcerative colitis in remission. in addition, a randomised, open-label, multicentre trial showed that vsl#3 in combination with low-dose balsalazide (a prodrug of mesalazine [mesalamine; 5-aminosalicylic acid]) was more effective than standard doses of basalazide or mesalazine monotherapy in the treatment of acute mild to moderate ulcerative colitis. randomised, double-blind, placebo-controlled studies have shown vsl#3 is effective in preventing the onset  of acute pouchitis in patients with newly formed surgical pouches, and in maintaining remission following antibacterial treatment of acute pouchitis in patients with a history of refractory or recurrent pouchitis. treatment guidelines from the us and the uk include vsl#3 as a therapeutic option for the prevention of pouchitis relapse in patients with chronic pouchitis. in general, vsl#3 was well tolerated in clinical trials. large, well designed, controlled confirmatory clinical trials will further determine the place of vsl#3 in the treatment of ulcerative colitis.
TIHT== 
ABHT== 

PMID== 16702308
TI  == bioproduction of conjugated linoleic acid by probiotic bacteria occurs in vitro and in vivo in mice.
AB  == probiotics have been shown to reduce the incidence of colon cancer in animal models. the mechanisms responsible for this activity are poorly defined. conjugated linoleic acids (cla) are a group of isomers of linoleic acid (la) possessing anti-inflammatory and anticarcinogenic properties, which can be produced from la by certain bacterial strains. in this study, the ability of probiotic bacteria to exert anticarcinogenic effects through the production of cla was assessed. incubation of probiotic bacteria (vsl3, lactobacillus acidophilus, l. bulgaricus, l. casei, l. plantarum, bifidobacterium breve, b. infantis, b. longum, and streptococcus thermophilus) in the presence of la yielded cla production as measured by gas chromatography. conditioned medium, containing probiotic-produced cla, reduced viability and induced apoptosis of ht-29 and caco-2 cells, as assessed by mtt assay and dna laddering, respectively. western blotting demonstrated an increased expression of ppargamma in cells treated with conditioned medium compared with la alone. incubation of murine feces with la after administering vsl3 yielded 100-fold more cla than feces collected prior to vsl3 feeding. this study supports a role for supplemental probiotics as a strategy both for attenuating inflammation and for preventing colon cancer.
TIHT== 
ABHT== 

PMID== 15220671
TI  == probiotics in the treatment of irritable bowel syndrome.
AB  == irritable bowel syndrome (ibs) may be diagnosed on the presence of symptoms, according to rome ii criteria, [corrected] and some studies have shown that abnormal colonic fermentation may be an important factor in the development of symptoms in some patients with ibs. since the fermentation [corrected] of substrates by the intestinal flora may play a key role in the use of probiotics in the treatment of ibs, seventy [corrected] patients (31 [corrected] males, 39 [corrected] females), mean age 40 years (range = 26-64 years) with ibs, according to rome ii criteria, were enrolled into the study after informed consensus. patients were randomly assigned to receive for 4 weeks [corrected] either the active preparation containing lactobacillus plantarum lp 01 [corrected] and bifidobacterium breve br 03 [corrected] or lactobacillus plantarum lp 01 and lactobacillus acidophilus la 02, all strains at concentrations of 5 x 10(9) cfu/g) [corrected] or placebo powder containing starch identical to the study product [corrected] to evaluate treatment efficacy two different scores were considered [corrected] pain score in different abdominal locations after treatment decreased in probiotics groups a and b 42% and 49% versus 25% [corrected] (p < 0.05) in [corrected] placebo group after 14 days and 45% and 49% versus 29.5% [corrected] (p < 0.001) after 28 days. the severity score of characteristic ibd symptoms significantly decreased in probiotic groups a and b [corrected] versus placebo group after 14 days, 49.3% and 55.6% [corrected] versus 8% [corrected] (p < 0.001), and these data were confirmed after 28 days (56% and 55.6% versus 14.4% [corrected] p < 0.001). in conclusion, short-term therapy with lactobacillus plantarum lp 01 and bifidobacterium breve br 03 or lactobacillus plantarum lp 01 and lactobacillus acidophilus la 02 [corrected] may be considered a promising approach for ibs therapy [corrected]
TIHT== 
ABHT== 

PMID== 9721649
TI  == growth-inhibitory effects of galla rhois-derived tannins on intestinal bacteria.
AB  == the growth-inhibitory activity of galla rhois-derived materials towards 17 intestinal bacteria was evaluated using an impregnated paper disc method. the biologically active components of galla rhois were characterized as the tannins methyl gallate (mg) and gallic acid (ga) by spectral analysis. the growth responses varied with bacterial strain tested. in the test using 10 mg disc-1, mg and ga produced a clear inhibitory effect on harmful bacteria such as clostridium perfringens, cl. paraputrificum, eubacterium limosum, bacteroides fragilis, staphylococcus aureus and escherichia coli. methyl gallate showed no growth-inhibitory activity towards bifidobacterium adolescentis or b. longum whereas the growth of b. bifidum, b. breve, b. infantis, b. animalis, b. thermophilum, lactobacillus acidophilus, lact. plantarum and streptococcus faecalis was slightly affected. however, ga did not adversely affect the growth of the bifidobacteria and lactobacilli. at 5 mg disc-1, mg significantly inhibited the growth of cl. perfringens and cl. paraputrificum but did not affect the growth of the bifidobacteria and lactobacilli. at 1 mg disc-1, mg greatly inhibited the growth of cl. perfringens alone. these results may be an indication of at least one of the pharmacological actions of galla rhois.
TIHT== 
ABHT== 

PMID== 8364525
TI  == analysis of intestinal flora of a patient with congenital absence of the portal vein.
AB  == a 14-year-old female patient, admitted for a closer examination of liver tumour (hepatocellular adenoma), was diagnosed as having a congenital absence of the portal vein. the blood ammonia level (approximately 120 micrograms dl-1) in the superior mesenteric vein was markedly low compared to the normal value of 300-350 micrograms dl-1 in the portal vein. the decreased ammonia concentration and urease activity of the patient's faeces were demonstrated. the dominant intestinal flora in the faeces of the patient, before operation, was bifidobacterium sp., bifidobacterium breve, bifidobacterium lonqum, lactobacillus plantarum, and after the operation bacteroides vulgatus, veillonella parvula, peptococcus magnus bifidobacterium longum. in contrast, bifidobacterium bifidum,  bacteroides ureolyticus, bacteroides ovatus and bacteroides distasonis, b. ovatus, bifidobacterium adolescentis were dominant flora in the faeces of two healthy volunteers, respectively. among microorganisms isolated from the patient, morganella morganii, candida sp., eubacterium aerofacience and eubacterium rectale were strongly positive in urease activity in vitro; streptococcus mitior, staphylococcus intermedius, micrococcus kristinae, selenomonas ruminantum, bacteroides ureolyticus and lactobacillus casei ss. pseudoplantarum from the healthy volunteers. these results imply the homeostatic regulation system of faecal ammonia concentration by urease-producing microorganisms in the patient.
TIHT== 
ABHT== 

PMID== 1716036
TI  == [the range of antigenic specificity of bifidobacterium peptidoglycan].
AB  == the antigenic relationships of bifidobacterium bifidum 1 peptidoglycans with different strains of this species (lva-3, 791, go-4), bifidobacteria of other species (b. adolescentis go-13, b. breve 79-38, b. lactentis 79-41, b. longum go-3) and bacteria of remote taxonomic groups (streptococcus faecalis 6-3. staphylococcus aureus com 885, s. epidermidis com 2124. lactobacillus plantarum 1, escherichia coli m-17) were studied on the basis of a highly sensitive test system permitting the registration of normal human antibodies to peptidoglycans.  the level of cross reactions with staphylococci and streptococci correspond to intraspecific and antigenic affinity to l. plantarum and e. coli was considerably less pronounced. copying a number of epitopes of bifidobacteria, s. aureus peptidoglycan seems to possess additional antigenic determinants which participate in the formation of immunological responsiveness in man.
TIHT== 
ABHT== 

