@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 22343308
TI  == ruminococcus bromii is a keystone species for the degradation of resistant starch in the human colon.
AB  == the release of energy from particulate substrates such as dietary fiber and resistant starch (rs) in the human colon may depend on the presence of specialist primary degraders (or 'keystone species') within the microbial community. we have explored the roles of four dominant amylolytic bacteria found in the human colon  in the degradation and utilization of resistant starches. eubacterium rectale and bacteroides thetaiotaomicron showed limited ability to utilize rs2- and rs3-resistant starches by comparison with bifidobacterium adolescentis and ruminococcus bromii. in co-culture, however, r. bromii proved unique in stimulating rs2 and rs3 utilization by the other three bacterial species, even in a medium that does not permit growth of r. bromii itself. having previously demonstrated low rs3 fermentation in vivo in two individuals with undetectable populations of r. bromii-related bacteria, we show here that supplementation of mixed fecal bacteria from one of these volunteers with r. bromii, but not with the other three species, greatly enhanced the extent of rs3 fermentation in vitro. this argues strongly that r. bromii has a pivotal role in fermentation of  rs3 in the human large intestine, and that variation in the occurrence of this species and its close relatives may be a primary cause of variable energy recovery from this important component of the diet. this work also indicates that r. bromii possesses an exceptional ability to colonize and degrade starch particles when compared with previously studied amylolytic bacteria from the human colon.
TIHT== 
ABHT== 

PMID== 21151493
TI  == resistant starches types 2 and 4 have differential effects on the composition of  the fecal microbiota in human subjects.
AB  == background: to systematically develop dietary strategies based on resistant starch (rs) that modulate the human gut microbiome, detailed in vivo studies that evaluate the effects of different forms of rs on the community structure and population dynamics of the gut microbiota are necessary. the aim of the present study was to gain a community wide perspective of the effects of rs types 2 (rs2) and 4 (rs4) on the fecal microbiota in human individuals. methods and findings: ten human subjects consumed crackers for three weeks each containing either rs2,  rs4, or native starch in a double-blind, crossover design. multiplex sequencing of 16s rrna tags revealed that both types of rs induced several significant compositional alterations in the fecal microbial populations, with differential effects on community structure. rs4 but not rs2 induced phylum-level changes, significantly increasing actinobacteria and bacteroidetes while decreasing firmicutes. at the species level, the changes evoked by rs4 were increases in bifidobacterium adolescentis and parabacteroides distasonis, while rs2 significantly raised the proportions of ruminococcus bromii and eubacterium rectale when compared to rs4. the population shifts caused by rs4 were numerically substantial for several taxa, leading for example, to a ten-fold increase in bifidobacteria in three of the subjects, enriching them to 18-30% of  the fecal microbial community. the responses to rs and their magnitudes varied between individuals, and they were reversible and tightly associated with the consumption of rs. conclusion: our results demonstrate that rs2 and rs4 show functional differences in their effect on human fecal microbiota composition, indicating that the chemical structure of rs determines its accessibility by groups of colonic bacteria. the findings imply that specific bacterial populations could be selectively targeted by well designed functional carbohydrates, but the inter-subject variations in the response to rs indicates that such strategies might benefit from more personalized approaches.
TIHT== 
ABHT== 

PMID== 19128319
TI  == linking phylogenetic identities of bacteria to starch fermentation in an in vitro model of the large intestine by rna-based stable isotope probing.
AB  == carbohydrates, including starches, are an important energy source for humans, and are known for their interactions with the microbiota in the digestive tract. largely, those interactions are thought to promote human health. using 16s ribosomal rna (rrna)-based stable isotope probing (sip), we identified starch-fermenting bacteria under human colon-like conditions. to the microbiota of the tim-2 in vitro model of the human colon 7.4 g l(-1) of [u-(13)c]-starch was added. rna extracted from lumen samples after 0 (control), 2, 4 and 8 h was subjected to density-gradient ultracentrifugation. terminal-restriction fragment  length polymorphism (t-rflp) fingerprinting and phylogenetic analyses of the labelled and unlabelled 16s rrna suggested populations related to ruminococcus bromii, prevotella spp. and eubacterium rectale to be involved in starch metabolism. additionally, 16s rrna related to that of bifidobacterium adolescentis was abundant in all analysed fractions. while this might be due to the enrichment of high-gc rna in high-density fractions, it could also indicate an active role in starch fermentation. comparison of the t-rflp fingerprints of experiments performed with labelled and unlabelled starch revealed ruminococcus bromii as the primary degrader in starch fermentation in the studied model, as it was found to solely predominate in the labelled fractions. lc-ms analyses of the  lumen and dialysate samples showed that, for both experiments, starch fermentation primarily yielded acetate, butyrate and propionate. integration of molecular and metabolite data suggests metabolic cross-feeding in the system, where populations related to ruminococcus bromii are the primary starch degrader, while those related to prevotella spp., bifidobacterium adolescentis and eubacterium rectale might be further involved in the trophic chain.
TIHT== 
ABHT== 

PMID== 17298367
TI  == selective colonization of insoluble substrates by human faecal bacteria.
AB  == insoluble plant polysaccharides and endogenous mucin are important energy sources for human colonic microorganisms. the object of this study was to determine whether or not specific communities colonize these substrates. using faecal samples from four individuals as inocula for an anaerobic in vitro continuous flow system, the colonization of wheat bran, high amylose starch and porcine gastric mucin was examined. recovered substrates were extensively washed and the  remaining tightly attached bacterial communities were identified using polymerase chain reaction-amplified 16s rrna gene sequences and fluorescent in situ hybridization. the substrate had a major influence on the species of attached bacteria detected. sequences retrieved from bran were dominated by clostridial cluster xiva bacteria, including uncultured relatives of clostridium hathewayi, eubacterium rectale and roseburia species. bacteroides species were also detected. the most abundant sequences recovered from starch were related to the cultured species ruminococcus bromii, bifidobacterium adolescentis, bifidobacterium breve and e. rectale. the most commonly recovered sequences from  mucin were from bifidobacterium bifidum and uncultured bacteria related to ruminococcus lactaris. this study suggests that a specific subset of bacteria is  likely to be the primary colonizers of particular insoluble colonic substrates. for a given substrate, however, the primary colonizing species may vary between host individuals.
TIHT== 
ABHT== 

PMID== 12477438
TI  == development of a membrane-array method for the detection of human intestinal bacteria in fecal samples.
AB  == a membrane-array method was developed for the detection of human intestinal bacteria in fecal samples without using the expensive microarray-arrayer and laser-scanner. the 16s rdna sequences of 20 predominant human intestinal bacterial species were used to design oligonucleotide probes. three 40-mer oligonucleotides specific for each bacterial species (total 60 probes) were synthesized and applied to nitrocellulose membranes. digoxigenin (dig)-labeled 16s rdnas were amplified by polymerase chain reaction (pcr) from human fecal samples or pure cultured bacteria using two universal primers, and were hybridized to the membrane-array. hybridization signals were read by nbt/bcip color development. the 20 intestinal bacterial species tested were bacteroides thetaiotaomicron, b. vulgatus, b. fragilis, b. distasonis, clostridium clostridiiforme, c. leptum, fusobacterium prausnitzii, peptostreptococcus productus, ruminococcus obeum, r. bromii, r. callidus, r. albus, bifidobacterium  longum, b. adolescentis, b. infantis, eubacterium biforme, e. aerofaciens, lactobacillus acidophilus,escherichia coli, and enterococcus faecium. the two universal primers were able to amplify full size 16s rdna from all of the 20 bacterial species tested. the hybridization results indicated that the membrane-array method is a reliable technique for the detection of predominant human intestinal bacteria in the fecal samples. the result was also confirmed by  using specific pcr methods for these bacteria.
TIHT== 
ABHT== 

PMID== 12167534
TI  == design and evaluation of oligonucleotide-microarray method for the detection of human intestinal bacteria in fecal samples.
AB  == an oligonucleotide-microarray method was developed for the detection of intestinal bacteria in fecal samples collected from human subjects. the 16s rdna  sequences of 20 predominant human intestinal bacterial species were used to design oligonucleotide probes. three 40-mer oligonucleotides specific for each bacterial species (total 60 probes) were synthesized and applied to glass slides. cyanine5 (cy5)-labeled 16s rdnas were amplified by polymerase chain reaction (pcr) from human fecal samples or bacterial dna using two universal primers and were hybridized to the oligo-microarray. the 20 intestinal bacterial species tested were bacteroides thetaiotaomicron, bacteroides vulgatus, bacteroides fragilis, bacteroides distasonis, clostridium clostridiiforme, clostridium leptum, fusobacterium prausnitzii, peptostreptococcus productus, ruminococcus obeum, ruminococcus bromii, ruminococcus callidus, ruminococcus albus, bifidobacterium longum, bifidobacterium adolescentis, bifidobacterium infantis, eubacterium biforme, eubacterium aerofaciens, lactobacillus acidophilus, escherichia coli, and enterococcus faecium. the two universal primers were able to amplify full size 16s rdna from all of the 20 bacterial species tested. the hybridization results indicated that the oligo-microarray method developed in this study is a reliable method for the detection of predominant human intestinal bacteria in the fecal samples.
TIHT== 
ABHT== 

PMID== 4595760
TI  == predominant gram-positive bacteria in human feces: numbers, variety, and persistence.
AB  == the predominant gram-positive bacteria in 47 fecal specimens from 10 healthy men  were studied by microscopic and cultural counts, by the characterization and tentative identification of isolates, and by the use of fluorescein isothiocyanate (fitc)-conjugated globulins prepared using some of the isolates. gram-positive bacteria averaged 10(10.5+/-0.4(sd)/g (wet weight) of feces with significant variation from host to host. characterization of 865 isolates, all strict anaerobes and carbohydrate fermenters, showed 12 to 39 distinguishable strains from each host and indicated that some strains were present the full period of about 18 months. sixty percent of the isolates belonged to one of five  types, tentatively identified with five species-bifidobacterium adolescentis, eubacterium aerofaciens, e. rectale, peptostreptococcus productus, and ruminococcus bromii. there was distinct host idiosyncrasy in the pattern of estimated counts of these five types. certain strains resembling b. adolescentis, e. aerofaciens, and p. productus, distinguished with fitc conjugates, were resident in their hosts for many months. in direct smears each strain constituted about 1% of the total bacteria.
TIHT== 
ABHT== 

