@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 21417626
TI  == antibacterial activity of the enniatin b, produced by fusarium tricinctum in liquid culture, and cytotoxic effects on caco-2 cells.
AB  == the enniatins (ens) are bioactive compounds of hexadepsipeptidic structure produced by several strains of fusarium sp. the en b was purified from extracts of fusarium tricinctum growth on liquid culture of potato dextrose broth (pdb), using a semipreparative liquid chromatography (lc) followed by an analytical lc.  the purity and the structure of the isolated compound were confirmed by the determination of the extinction coefficient and with electrospray ionization-mass spectrometry (esi-ms) study. the pure fraction of en b was utilized to determine  the antibiotic effects on several bacterial strains that are considered normally  pathogens of the intestinal tract: escherichia coli, enterococcus faecium, salmonella enterica, shigella dysenteriae, listeria monocytogenes, yersinia enterocolitica, clostridium perfringens, pseudomonas aeruginosa, and staphylococcus aureus, and to study the cytotoxic effects on caco-2 differentiated and undifferentiated cells. the results obtained demonstrated that in several antibiograms, en b induced the inhibition of the grown microorganisms  tested and no significant differences over control were detected when caco-2 cells were exposed to en b, at any of the concentrations used.
TIHT== 
ABHT== 

PMID== 16962743
TI  == effect of tea phenolics and their aromatic fecal bacterial metabolites on intestinal microbiota.
AB  == tea is rich in polyphenols and other phenolics that have been widely reported to  have beneficial health effects. however, dietary polyphenols are not completely absorbed from the gastrointestinal tract and are metabolized by the gut microflora so that they and their metabolites may accumulate to exert physiological effects. in this study, we investigated the influence of the phenolic components of a tea extract and their aromatic metabolites upon bacterial growth. fecal homogenates containing bacteria significantly catalyzed tea phenolics, including epicatechin, catechin, 3-o-methyl gallic acid, gallic acid and caffeic acid to generate aromatic metabolites dependent on bacterial species. different strains of intestinal bacteria had varying degrees of growth sensitivity to tea phenolics and metabolites. growth of certain pathogenic bacteria such as clostridium perfringens, clostridium difficile and bacteroides spp. was significantly repressed by tea phenolics and their derivatives, while commensal anaerobes like clostridium spp., bifidobacterium spp. and probiotics such as lactobacillus sp. were less severely affected. this indicates that tea phenolics exert significant effects on the intestinal environment by modulation of the intestinal bacterial population, probably by acting as metabolic prebiotics. our observations provide further evidence for the importance of colonic bacteria in the metabolism, absorption and potential activity of phenolics in human health and disease. the bioactivity of different phenolics may play an important role in the maintenance of gastrointestinal health.
TIHT== 
ABHT== 

PMID== 16819902
TI  == comparison of the concentrations of phenolic compounds in olive oils and other plant oils: correlation with antimicrobial activity.
AB  == the antimicrobial activity of different edible vegetable oils was studied. in vitro results revealed that the oils from olive fruits had a strong bactericidal  action against a broad spectrum of microorganisms, this effect being higher in general against gram-positive than gram-negative bacteria. thus, olive oils showed bactericidal activity not only against harmful bacteria of the intestinal  microbiota (clostridium perfringens and escherichia coli) also against beneficial microorganisms such as lactobacillus acidophilus and bifidobacterium bifidum. otherwise, most of the foodborne pathogens tested (listeria monocytogenes, staphylococcus aureus, salmonella enterica, yersinia sp., and shigella sonnei) did not survive after 1 h of contact with olive oils. the dialdehydic form of decarboxymethyl oleuropein and ligstroside aglycons, hydroxytyrosol and tyrosol,  were the phenolic compounds that statistically correlated with bacterial survival. these findings were confirmed by testing each individual phenolic compound, isolated by hplc, against l. monocytogenes. in particular, the dialdehydic form of decarboxymethyl ligstroside aglycon showed a potent antimicrobial activity. these results indicate that not all oils classified as "olive oil" had similar bactericidal effects and that this bioactivity depended on their content of certain phenolic compounds.
TIHT== 
ABHT== 

PMID== 16696680
TI  == antagonistic activity of probiotic lactobacilli and bifidobacteria against entero- and uropathogens.
AB  == aim: to develop in vitro assays for comparing the antagonistic properties and anti-oxidative activity of probiotic lactobacillus and bifidobacterium strains against various entero- and urinary pathogens. methods and results: the antagonistic activity of five probiotic lactobacilli (lactobacillus rhamnosus gg, lactobacillus fermentum me-3, lactobacillus acidophilus la5, lactobacillus plantarum 299v and lactobacillus paracasei 8700:2) and two bifidobacteria (bifidobacterium lactis bb12, bifidobacterium longum 46) against six target pathogens was estimated using different assays (solid and liquid media, anaerobic and microaerobic cultivation) and ranked (low, intermediate and high). bacterial  fermentation products were determined by gas chromatography, and the total anti-oxidative activity of probiotics was measured using linolenic acid test. pyelonephritic escherichia coli was highly suppressed by gg and both bifidobacteria strains. lactobacilli strains 8700:2, 299v and me-3 were the most  effective against salmonella enterica ssp. enterica in microaerobic while me-3 and both bifidobacteria expressed high activity against shigella sonnei in anaerobic milieu. lact. paracasei, lact. rhamnosus and lact. plantarum strains showed intermediate antagonistic activity against helicobacter pylori under microaerobic conditions on solid media. the highest anti-oxidative activity was characteristic for lact. fermentum me-3 (p < 0.05). no efficient antagonist against clostridium difficile was found. the positive correlations between the ph, lactic acid production and anti-microbial activity for all tested probiotics  were assessed. conclusions: developed experimental assays enable to compare the anti-microbial and -oxidative activity of lactobacillus and/or bifidobacterium probiotics, which have been claimed to possess the ability of suppressing the growth of various enteric and urinary pathogens. significance and impact of the study: screening lactobacillus and bifidobacterium sp. strains according to their activity in various environmental conditions could precede the clinical efficacy  studies for adjunct treatment with probiotics in cure of different gastrointestinal and urinary tract infections.
TIHT== 
ABHT== 

PMID== 12171400
TI  == regrowth and survival of indicator microorganisms on the surfaces of household containers used for the storage of drinking water in rural communities of south africa.
AB  == the present study covered two rural communities of south africa: ncera and ntselamanzi villages. raw water from ncera river is used by the community of ncera village for drinking, while the community of ntselamanzi receives their drinking water from alice purification system. treated water is supplied to the community by a public standpipe system. in rural communities of south africa, many households use polyethylene (pe) and galvanized steel (gs) containers for the storage of their drinking water. to investigate the regrowth and survival of  indicator microorganisms on the surface of household containers during the storage of drinking water, pe and gs slides were suspended in the appropriate household containers for a period of 48 h. this period of 48 h was chosen as the  study period because results from the questionnaire indicated that the largest percentage (62%) of households store their water for that length of time. the experiment was performed to test drinking water as it is collected and stored by  rural communities. no disinfection of household containers or slides was done during the study period. attached coliphages (f-rna (fp) and somatic phage (sp),  coliform bacteria (total coliform (tc), presumptive escherichia coli (ec), salmonella (sal) and clostridium perfringens (cp) were measured during the study  period. with the exception of cp, attached indicator microorganisms consisted of  tc, presumptive e. coli and salmonella, somatic and f-rna coliphages, although the yield (average count) for the last four groups (ec: < 1-3 cfu cm(-2), sal: <  1-15 cfu cm(-2), fp: < 1-7 pfu cm(-2), sp: < 1-7pfu cm(-2)) was lower than that of tc (3-183 cfu cm(-2)). however, the lowest yield of indicator microorganisms was noted for presumptive e. coli. whereas the occurrence and survival of tc was  noted on the surface of household containers during the entire period of the experimental study, other indicator microorganisms occurred from time to time. the regrowth of indicator microorganisms occurred 48 h after the exposure of slides to both types of test waters. this length of time mostly resulted in the regrowth of tc (with an increase in bacterial counts) while the persistence of other indicator organism groups on the surface of the slides was apparent. a comparison between pe and gs containers showed that more tc (average count) regrew on pe than on gs containers (for river water, pe: from 36 to 55 cfu cm(-2), gs: from 25 to 26 cfu cm(-2); for standpipe water, pe: from 147 to 183 cfu cm(-2), gs from 3 to 4 cfu cm(-2)). this study revealed that both types of household containers supported the growth and survival of indicator microorganisms due to the bad quality of the intake water before storage. the storage of drinking water for 48 h mainly resulted in the regrowth of tc. nevertheless, the persistence of other indicator microorganisms was observed on the surface of household containers.
TIHT== 
ABHT== 

PMID== 8990573
TI  == risk factors for outbreaks of infectious intestinal disease linked to domestic catering.
AB  == the epidemiology of general outbreaks of infectious intestinal disease associated with domestic catering for large numbers is described and compared with foodborne outbreaks in other settings. from 1 january 1992 to 31 december 1994, the phls communicable disease surveillance centre identified 101 foodborne general outbreaks of infectious intestinal disease associated with domestic catering in england and wales (16% of all foodborne outbreaks). salmonella species were associated with 77 of the 101 outbreaks and s. enteriditis phage type 4 accounted for 57. small round structured viruses were implicated in five outbreaks, clostridium perfringens in four, bacillus cereus in two, and campylobacter sp and escherichia coli in one each. no pathogen was identified in 11 outbreaks. outbreaks occurred most commonly in summer. the commonest vehicles implicated were poultry/eggs in 44 outbreaks, desserts in 13, and meat/meat products in nine. salad/vegetables, sauces, and fish/shellfish were each implicated in eight  outbreaks. raw shell eggs were implicated in a fifth of outbreaks. inappropriate  storage was the commonest fault, reported in association with 50 outbreaks (ambient temperature for long periods before serving in 29), inadequate heat treatment was reported in 35, cross contamination in 28, an infected food handler in 11, and other faults in 14. outbreaks associated with catering on domestic premises were independently more likely than outbreaks in other settings to be associated with salmonellas, inappropriate storage of food, and consumption of poultry, eggs, or sauces. public health services need to direct messages about the use, preparation, and storage of food to those who cater on domestic premises.
TIHT== 
ABHT== 

PMID== 8239135
TI  == increase of mannose residues, as salmonella typhimurium-adhering factor, on the cecal mucosa of germ-free chickens infected with eimeria tenella.
AB  == to study increase of the salmonella population in the cecum of chickens infected  with eimeria tenella, quantitative changes in mannose residues on the cecal mucosa were investigated. inhibition of s typhimurium adherence to the cecum by a 2% carbohydrate (d-mannose, d-galactose, l-fucose, alpha-methyl-d-glucoside) in phosphate-buffered saline solution was examined. only d-mannose had inhibitory effects. whereas, d-galactose had somewhat enhancing effects on adherence of s typhimurium to the cecal mucosa of uninfected germ-free chickens. in infected and uninfected chickens, d-mannose inhibited adherence of s typhimurium. d-mannose significantly (p < 0.05) increased adherence of bacteroides sp. in infected and uninfected chickens, d-mannose did not have any effect on adherence of clostridium perfringens and bifidobacterium thermophilum. under microscopic observation, only concanavalin a and lens culinaris agglutinin, of 8 lectins examined, were recognized as lectin-positive staining lines or spots in the cecal mucosa, indicating presence of mannose residues on the cecal mucosa. in e tenella-infected chickens, lectin-positive staining was seen strongly on the coarse surface of damaged cells and at the bottom of the crypts. these results indicate that coccidial infection may induce increase of mannose residues on the  intestinal surface and allow adhesion of more salmonellae to the intestine.
TIHT== 
ABHT== 

PMID== 1345079
TI  == [bacteria associated with diarrheic episodes in young camels in niger].
AB  == during diarrhoeic episodes of young camels in niger, bacteria such as salmonella  enteritidis, e. coli, staphylococcus sp., clostridium perfringens and other bacteria were isolated from stool samples. bacteria roll in this pathology is discussed, and a treatment is proposed, compared with antibiogram results.
TIHT== 
ABHT== 

PMID== 2197274
TI  == cloning, sequencing, and expression of the genes encoding the adenosylcobalamin-dependent ethanolamine ammonia-lyase of salmonella typhimurium.
AB  == ethanolamine ammonia-lyase is a bacterial enzyme that catalyzes the adenosylcobalamin-dependent conversion of certain vicinal amino alcohols to oxo compounds and ammonia. studies of ethanolamine ammonia-lyase from clostridium sp. and escherichia coli have suggested that the enzyme is a heterodimer composed of  subunits of mr approximately 55,000 and 35,000. using a partial sau3a salmonella  typhimurium library ligated into pbr328 and selecting by complementation of a mutant lacking ethanolamine ammonia-lyase activity, we have cloned the genes for  the 2 subunits of the s. typhimurium enzyme. the genes were localized to a 6.5-kilobase fragment of s. typhimurium dna, from which they could be expressed in e. coli under noninducing conditions. sequencing of a 2526-base pair portion of this 6.5-kilobase dna fragment revealed two open reading frames separated by 21 base pairs. the open reading frames encoded proteins of 452 and 286 residues whose derived n-terminal sequences were identical to the n-terminal sequences of  the 2 subunits of the e. coli ethanolamine ammonia-lyase, except that residue 16  of the large subunit was asparagine in the e. coli sequence and aspartic acid in  the s. typhimurium sequence.
TIHT== 
ABHT== 

