@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 21264064
TI  == small rnas in the genus clostridium.
AB  == the genus clostridium includes major human pathogens and species important to cellulose degradation, the carbon cycle, and biotechnology. small rnas (srnas) are emerging as crucial regulatory molecules in all organisms, but they have not  been investigated in clostridia. research on srnas in clostridia is hindered by the absence of a systematic method to identify srna candidates, thus delegating clostridial srna research to a hit-and-miss process. thus, we wanted to develop a method to identify potential srnas in the clostridium genus to open up the field  of srna research in clostridia. using comparative genomics analyses combined with predictions of rho-independent terminators and promoters, we predicted srnas in 21 clostridial genomes: clostridium acetobutylicum, c. beijerinckii, c. botulinum (eight strains), c. cellulolyticum, c. difficile, c. kluyveri (two strains), c. novyi, c. perfringens (three strains), c. phytofermentans, c. tetani, and c. thermocellum. although more than one-third of predicted srnas have shine-dalgarno (sd) sequences, only one-sixth have a start codon downstream of sd sequences; thus, most of the predicted srnas are noncoding rnas. quantitative reverse transcription-pcr (q-rt-pcr) and northern analysis were employed to test the presence of a randomly chosen set of srnas in c. acetobutylicum and several c. botulinum strains, leading to the confirmation of a large fraction of the tested  srnas. we identified a conserved, novel srna which, together with the downstream  gene coding for an atp-binding cassette (abc) transporter gene, responds to the antibiotic clindamycin. the number of predicted srnas correlated with the physiological function of the species (high for pathogens, low for cellulolytic,  and intermediate for solventogenic), but not with 16s rrna-based phylogeny.
TIHT== 
ABHT== 

PMID== 11041350
TI  == fermentation of 4-aminobutyrate by clostridium aminobutyricum: cloning of two genes involved in the formation and dehydration of 4-hydroxybutyryl-coa.
AB  == clostridium aminobutyricum ferments 4-aminobutyrate via succinic semialdehyde, 4-hydroxybutyrate, 4-hydroxybutyryl-coa and crotonyl-coa to acetate and butyrate. the genes coding for the enzymes that catalyse the interconversion of these intermediates are arranged in the order abfd (4-hydroxybutyryl-coa dehydratase),  abft (4-hydroxybutyrate coa-transferase), and abfh (nad-dependent 4-hydroxybutyrate dehydrogenase). the genes abfd and abft were cloned, sequenced  and expressed as active enzymes in escherichia coli. hence the insertion of the [4fe-4s]clusters and fad into the dehydratase required no additional specific protein from c. aminobutyricum. the amino acid sequences of the dehydratase and the coa-transferase revealed close relationships to proteins deduced from the genomes of clostridium difficile, porphyromonas gingivalis and archaeoglobus fulgidus. in addition the n-terminal part of the dehydratase is related to those  of a family of fad-containing mono-oxygenases from bacteria. the putative assignment in the databank of cat2 (orfz) from clostridium kluyveri as 4-hydroxybutyrate coa-transferase, which is thought to be involved in the reductive pathway from succinate to butyrate, was confirmed by sequence comparison with abft (57% identity). furthermore, an acetyl-coa:4-hydroxybutyrate coa-transferase activity could be detected in cell-free extracts of c. kluyveri.  in contrast to glutaconate coa-transferase from acidaminococcus fermentans, mutation studies suggested that the glutamate residue of the motive exg, which is conserved in many homologues of abft, does not form a coa-ester during catalysis.
TIHT== 
ABHT== 

