@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25264743
TI  == molecular modeling and mm-pbsa free energy analysis of endo-1,4-beta-xylanase from ruminococcus albus 8.
AB  == endo-1,4-beta-xylanase (ec 3.2.1.8) is the enzyme from ruminococcus albus 8 (r. albus 8) (xyn10a), and catalyzes the degradation of arabinoxylan, which is a major cell wall non-starch polysaccharide of cereals. the crystallographic structure of xyn10a is still unknown. for this reason, we report a computer-assisted homology study conducted to build its three-dimensional structure based on the known sequence of amino acids of this enzyme. in this study, the best similarity was found with the clostridium thermocellum (c. thermocellum) n-terminal endo-1,4-beta-d-xylanase 10 b. following the 100 ns molecular dynamics (md) simulation, a reliable model was obtained for further studies. molecular mechanics/poisson-boltzmann surface area (mm-pbsa) methods were used for the substrate xylotetraose having the reactive sugar, which was bound in the -1 subsite of xyn10a in the 4c1 (chair) and 2so (skew boat) ground state conformations. according to the simulations and free energy analysis, xyn10a binds the substrate with the -1 sugar in the 2so conformation 39.27 kcal.mol(-1) tighter than the substrate with the sugar in the 4c1 conformation. according to the xyn10a-2so xylotetraose (x4(sb) interaction energies, the most important subsite for the substrate binding is subsite -1. the results of this study indicate that the substrate is bound in a skew boat conformation with xyn10a and the -1 sugar subsite proceeds from the 4c1 conformation through 2so to the transition state. mm-pbsa free energy analysis indicates that asn187 and trp344 in subsite -1 may an important residue for substrate binding. our findings provide fundamental knowledge that may contribute to further enhancement of enzyme performance through molecular engineering.
TIHT== 
ABHT== 

PMID== 21362116
TI  == isolation and characterization of a ferulic acid esterase (fae1a) from the rumen  fungus anaeromyces mucronatus.
AB  == aims: a novel ferulic acid esterase gene from rumen fungus anaeromyces mucronatus was cloned, heteroexpressed in escherichia coli and characterized. methods and results: a total of 30 clones exhibiting activity on alpha-naphthyl acetate (alpha-na) were isolated from an a. mucronatus ye505 cdna library. sequence analysis revealed that these clones represented two esterase-coding sequences. the gene, fae1a, showed highest amino acid sequence identity to ce family 1 esterases from anaerobic micro-organisms such as orpinomyces sp., ruminococcus albus and clostridium thermocellum. the gene comprised 828 nucleotides encoding a polypeptide of 275 amino acids. the coding sequence was cloned into the pet30a expression vector and overexpressed in e. coli bl21 (de3). gene product fae1a was found to exhibit activity against a number of substrates including naphthyl fatty acid esters, p-nitrophenyl fatty acid esters and hydroxylcinnamic acid esters. conclusions: fae1a exhibited a lower k(m) and higher catalytic efficiency (k(cat) /k(m) ) on ferulic acid esters than on alpha-na or p-nitrophenyl acetate, suggesting that it has a higher affinity for ethyl and methyl ferulate than for the acetyl esters. it releases ferulic acid and p-coumaric acid from barley straw. activity of fae1a was inhibited by the serine-specific protease inhibitor, phenylmethylsulfonyl fluoride, indicating that a serine residue plays a role in its activity. significance and impact of the study: to our knowledge, this is the first report of characterization of carbohydrate esterase gene from the genus of  anaeromyces.
TIHT== 
ABHT== 

PMID== 17022659
TI  == unravelling carbon metabolism in anaerobic cellulolytic bacteria.
AB  == carbon metabolism in anaerobic cellulolytic bacteria has been investigated essentially in clostridium thermocellum, clostridium cellulolyticum, fibrobacter  succinogenes, ruminococcus flavefaciens, and ruminococcus albus. while cellulose  depolymerization into soluble sugars by various cellulases is undoubtedly the first step in bacterial metabolisation of cellulose, it is not the only one to consider. among anaerobic cellulolytic bacteria, c. cellulolyticum has been investigated metabolically the most in the past few years. summarizing metabolic  flux analyses in continuous culture using either cellobiose (a soluble cellodextrin resulting from cellulose hydrolysis) or cellulose (an insoluble biopolymer), this review aims to stress the importance of the insoluble nature of a carbon source on bacterial metabolism. furthermore, some general and specific traits of anaerobic cellulolytic bacteria trends, namely, the importance and benefits of (i) cellodextrins with degree of polymerization higher than 2, (ii) intracellular phosphorolytic cleavage, (iii) glycogen cycling on cell bioenergetics, and (iv) carbon overflows in regulation of carbon metabolism, as well as detrimental effects of (i) soluble sugars and (ii) acidic environment on  bacterial growth. future directions for improving bacterial cellulose degradation are discussed.
TIHT== 
ABHT== 

PMID== 15735965
TI  == wood adhesives prepared from lucerne fiber fermentation residues of ruminococcus  albus and clostridium thermocellum.
AB  == fermentation residues (consisting of incompletely fermented fiber, adherent bacterial cells, and a glycocalyx material that enhanced bacterial adherence) were obtained by growing the anaerobic cellulolytic bacteria ruminococcus albus 7 or clostridium thermocellum atcc 27405 on a fibrous fraction derived from lucerne (medicago sativa l.). the dried residue was able to serve as an effective co-adhesive for phenol-formaldehyde (pf) bonding of aspen veneer sheets to one another. testing of the resulting plywood panels revealed that the adhesive, formulated to contain 30% of its total dry weight as fermentation residue, displayed shear strength and wood failure values under both wet and dry conditions that were comparable with those of industry standards for pf that contained much smaller amounts of fillers or extenders. by contrast, pf adhesives prepared with 30% of dry weight as either unfermented lucerne fiber or conventional fillers or extenders rather than as fermentation residues, displayed poor performance, particularly under wet conditions.
TIHT== 
ABHT== 

PMID== 14679233
TI  == ruminococcus albus 8 mutants defective in cellulose degradation are deficient in  two processive endocellulases, cel48a and cel9b, both of which possess a novel modular architecture.
AB  == the cellulolytic bacterium ruminococcus albus 8 adheres tightly to cellulose, but the molecular biology underpinning this process is not well characterized. subtractive enrichment procedures were used to isolate mutants of r. albus 8 that are defective in adhesion to cellulose. adhesion of the mutant strains was reduced 50% compared to that observed with the wild-type strain, and cellulose solubilization was also shown to be slower in these mutant strains, suggesting that bacterial adhesion and cellulose solubilization are inextricably linked. two-dimensional polyacrylamide gel electrophoresis showed that all three mutants  studied were impaired in the production of two high-molecular-mass, cell-bound polypeptides when they were cultured with either cellobiose or cellulose. the identities of these proteins were determined by a combination of mass spectrometry methods and genome sequence data for r. albus 8. one of the polypeptides is a family 9 glycoside hydrolase (cel9b), and the other is a family 48 glycoside hydrolase (cel48a). both cel9b and cel48a possess a modular architecture, cel9b possesses features characteristic of the b(2) (or theme d) group of family 9 glycoside hydrolases, and cel48a is structurally similar to the processive endocellulases celf and cels from clostridium cellulolyticum and clostridium thermocellum, respectively. both cel9b and cel48a could be recovered  by cellulose affinity procedures, but neither cel9b nor cel48a contains a dockerin, suggesting that these polypeptides are retained on the bacterial cell surface, and recovery by cellulose affinity procedures did not involve a clostridium-like cellulosome complex. instead, both proteins possess a single copy of a novel x module with an unknown function at the c terminus. such x modules are also present in several other r. albus glycoside hydrolases and are phylogentically distinct from the fibronectin iii-like and x modules identified so far in other cellulolytic bacteria.
TIHT== 
ABHT== 

PMID== 12153721
TI  == molecular cloning and characterization of a novel glucocerebrosidase of paenibacillus sp. ts12.
AB  == we report here the molecular cloning and characterization of a glucocerebrosidase [ec 3.2.1.45] from paenibacillus sp. ts12. the open reading frame of the glucocerebrosidase gene consisted of 2,493 bp nucleotides and encoded 831 amino acid residues. the enzyme exhibited no sequence similarity with a classical glucocerebrosidase belonging to glycoside hydrolase (gh) family 30, but rather showed significant similarity with gh family 3 beta-glucosidases from clostridium thermocellum, ruminococcus albus, and aspergillus aculeateus. the recombinant enzyme, expressed in escherichia coli bl21(de3)plyss, had a molecular weight of 90.7 kda and hydrolyzed nbd-labeled glucosylceramide, but not galactosylceramide, gm1a or sphingomyelin. the enzyme was most active at ph 6.5, and its apparent km  and vmax values for nbd-labeled glucosylceramide and p-nitrophenyl-beta-glucopyranoside were 223 microm and 1.60 micromol/min/mg of protein, and 593 microm and 112 micromol/min/mg of protein, respectively. site-directed mutagenesis indicated that asp-223 is an essential amino acid for the catalytic reaction and possibly functions a catalytic nucleophile, as in gh family 3 beta-glucosidases. this is the first report of the molecular cloning and characterization of a glucocerebrosidase from a procaryote.
TIHT== 
ABHT== 

PMID== 11576305
TI  == subcellular distribution of glycanases and related components in ruminococcus albus sy3 and their role in cell adhesion to cellulose.
AB  == aims: to compare the subcellular distribution of glycanase-related components between wild-type ruminococcus albus sy3 and an adhesion-defective mutant, to identify their possible contribution to the adhesion process, and to determine their association with cellulosome-like complexes. methods and results: cell fractionation revealed that most of the cellulases and xylanases were associated  with capsular and cell-wall fractions. sds-page and gel filtration indicated that most of the bacterial enzyme activity was not integrated into cellulosome-like complexes. the adhesion-defective mutant produced significantly less (5- to 10-fold) overall glycanase activity, and the 'true cellulase activity' appeared to be entirely confined to the cell membrane fractions. antibodies specific for the cellulosomal scaffoldin of clostridium thermocellum recognized a single 240 kda band in r. albus sy3. conclusions: the adhesion-defective mutant appeared to  be blocked in exocellular transport of enzymes involved in true cellulase activity. a potential cellulosomal scaffoldin candidate was identified in r. albus sy3. significance and impact of the study: several glycanase-related proteins and more than one mechanism appear to be involved in the adhesion of r.  albus sy3 to cellulose.
TIHT== 
ABHT== 

PMID== 10737178
TI  == characterization of the cellulolytic complex (cellulosome) from ruminococcus albus.
AB  == the cellulolytic complex was isolated from the culture supernatant of ruminococcus albus strain f-40 grown on cellulose by a sephacryl s-300hr column chromatography. the molecular mass of the cellulolytic complex was found to be larger than 1.5 x 10(6) da. sodium dodecyl sulfate-polyacrylamide gel electrophoresis (sds-page) analysis indicated that the cellulolytic complex contained at least 15 proteins with molecular weights from 40kda to 250 kda. among them, 11 proteins showed endoglucanase and/or xylanase activities on the zymograms. immunological analysis using an antiserum raised against the dockerin  domain of endoglucanase vii of r. albus (docvii) suggested that at least 7 proteins in the cellulolytic complex contained a dockerin domain immunoreactive with the anti-doc-vii antiserum. furthermore, docvii was shown to specifically interact with a 40-kda protein of the cellulolytic complex by far-western blot analysis. these results strongly suggest that the cellulolytic complex produced by r. albus resembles the cellulosome specified for the cellulolytic complex of several clostridia such as clostridium thermocellum and respective components are assembled into the cellulosome by the mechanism common in all of the cellulolytic clostridia, i.e., the cellulosome is formed by the interaction between a dockerin domain of catalytic components and a cohesin domain of a scaffolding protein.
TIHT== 
ABHT== 

PMID== 1953672
TI  == characterization of hybrid proteins consisting of the catalytic domains of clostridium and ruminococcus endoglucanases, fused to pseudomonas non-catalytic cellulose-binding domains.
AB  == the n-terminal 160 or 267 residues of xylanase a from pseudomonas fluorescens subsp. cellulosa, containing a non-catalytic cellulose-binding domain (cbd), were fused to the n-terminus of the catalytic domain of endoglucanase e (ege') from clostridium thermocellum. a further hybrid enzyme was constructed consisting of the 347 n-terminal residues of xylanase c (xylc) from p. fluorescens subsp. cellulosa, which also constitutes a cbd, fused to the n-terminus of endoglucanase a (ega) from ruminococcus albus. the three hybrid enzymes bound to insoluble cellulose, and could be eluted such that cellulose-binding capacity and catalytic activity were retained. the catalytic properties of the fusion enzymes were similar to ege' and ega respectively. residues 37-347 and 34-347 of xylc were fused to the c-terminus of ege' and the 10 amino acids encoded by the multiple cloning sequence of pmtl22p respectively. the two hybrid proteins did not bind cellulose, although residues 39-139 of xylc were shown previously to constitute a functional cbd. the putative role of the p. fluorescens subsp. cellulosa cbd in cellulase action is discussed.
TIHT== 
ABHT== 

PMID== 1886616
TI  == sequence of a cellulase gene from the rumen anaerobe ruminococcus flavefaciens 17.
AB  == a cellulase gene (enda) was isolated from a library of ruminococcus flavefaciens  strain 17 dna fragments inserted in puc13. the enda product showed activity against acid-swollen cellulose, carboxymethyl-cellulose, lichenan, cellopentaose  and cellotetraose, but showed no activity against cellotriose or binding to avicel. nucleotide sequencing indicated an encoded product of 455 amino acids which showed significant sequence similarity (ranging from 56% to 61%) with three endoglucanases from ruminococcus albus, and with clostridium thermocellum endoglucanase e. little relatedness was found with a cellodextrinase previously isolated from r. flavefaciens fd1.
TIHT== 
ABHT== 

PMID== 2250649
TI  == nucleotide sequence of the ruminococcus albus sy3 endoglucanase genes cela and celb.
AB  == the complete nucleotide sequences of ruminococcus albus genes cela and celb coding for endoglucanase a (ega) and endoglucanase b (egb), respectively, have been determined. the cela structural gene consists of an open reading frame of 1095 bp. confirmation of the nucleotide sequence was obtained by comparing the predicted amino acid sequence with that derived by n-terminal analysis of purified ega. the celb structural gene consists of an open reading frame of 1227  bp; 7 bp upstream of the translational start codon of celb is a typical gram-positive shine-dalgarno sequence. the deduced n-terminal region of egb conforms to the general pattern for the signal peptides of secreted prokaryotic proteins. the complete celb gene, cloned into puc vectors, caused lethality in escherichia coli. in contrast, cela cloned in puc18, under the control of laczp,  directed high-level synthesis of ega in e. coli jm83. ega in cell-free extract, purified to near homogeneity by ion-exchange chromatography, had a mr of 44.5 kda. gene deletion and subcloning studies with cela revealed that ega hydrolysed  both cmc and xylan, and did not contain discrete functional domains. ega and egb  showed considerable homology with each other, in addition to exhibiting similarity with eg1 (r. albus), ege (clostridium thermocellum) and end (butyrivibrio fibrisolvens).
TIHT== 
ABHT== 

PMID== 2361940
TI  == cloning and sequencing of a bacteroides ruminicola b(1)4 endoglucanase gene.
AB  == bacteroides ruminicola b(1)4, a noncellulolytic rumen bacterium, produces an endoglucanase (carboxymethylcellulase [cmcase]) that is excreted into the culture supernatant. cultures grown on glucose, fructose, maltose, mannose, and cellobiose had high specific activities of cmcase (greater than 3 mmol of reducing sugar per mg of protein per min), but its synthesis was repressed by sucrose. b. rumincola did not grow on either ball-milled or acid-swollen cellulose even though the cmcase could hydrolyze swollen cellulose. the cmcase gene was cloned into escherichia coli, and its nucleotide sequence contained a single open reading frame coding for a protein of 40,481 daltons. the enzyme was  overproduced in e. coli under the control of the tac promoter and purified to homogeneity. the n-terminal sequence, amino acid composition, and molecular weight of the purified enzyme were similar to the values predicted from the open  reading frame of the dna sequence. however, the cmcase present in b. ruminicola was found to have a monomer molecular weight of 88,000 by western immunoblotting. this discrepancy appeared to have resulted from our having cloned only part of the cmcase gene into e. coli. the amino acid sequence of the cmcase showed homology to sequences of beta-glucanases from ruminococcus albus and clostridium  thermocellum.
TIHT== 
ABHT== 

PMID== 2687251
TI  == structure of a ruminococcus albus endo-1,4-beta-glucanase gene.
AB  == a chromosomal dna fragment encoding an endo-1,4-beta-glucanase i (eg i) gene from ruminococcus albus cloned and expressed in escherichia coli with puc18 was fully  sequenced by the dideoxy-chain termination method. the sequence contained a consensus promoter sequence and a structural amino acid sequence. the initial 43  amino acids of the protein were deduced to be a signal sequence, since they are missing in the mature protein (eg i). high homology was found when the amino acid sequence of the eg i was compared with that of endoglucanase e from clostridium thermocellum. codon usage of the gene was not biased. these results suggested that the properties of the eg i gene from r. albus was specified from the known beta-glucanase genes of the other organisms.
TIHT== 
ABHT== 

