@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25646759
TI  == diverse mechanisms regulate sporulation sigma factor activity in the firmicutes.
AB  == sporulation allows bacteria to survive adverse conditions and is essential to the lifecycle of some obligate anaerobes. in bacillus subtilis, the sporulation-specific sigma factors, sigma(f), sigma(e), sigma(g), and sigma(k), activate compartment-specific transcriptional programs that drive sporulation through its morphological stages. the regulation of these sigma factors was predicted to be conserved across the firmicutes, since the regulatory proteins controlling their activation are largely conserved. however, recent studies in (pepto)clostridium difficile, clostridium acetobutylicum, clostridium perfringens, and clostridium botulinum have revealed striking differences in the  order, activation, and function of sporulation sigma factors. these studies indicate that gene conservation does not necessarily predict gene function and that new mechanisms for controlling cell fate determination remain to be discovered in the anaerobic clostridia.
TIHT== 
ABHT== 

PMID== 25631287
TI  == the clostridium sporulation programs: diversity and preservation of endospore differentiation.
AB  == summary: bacillus and clostridium organisms initiate the sporulation process when unfavorable conditions are detected. the sporulation process is a carefully orchestrated cascade of events at both the transcriptional and posttranslational  levels involving a multitude of sigma factors, transcription factors, proteases,  and phosphatases. like bacillus genomes, sequenced clostridium genomes contain genes for all major sporulation-specific transcription and sigma factors (spo0a,  sigh, sigf, sige, sigg, and sigk) that orchestrate the sporulation program. however, recent studies have shown that there are substantial differences in the  sporulation programs between the two genera as well as among different clostridium species. first, in the absence of a bacillus-like phosphorelay system, activation of spo0a in clostridium organisms is carried out by a number of orphan histidine kinases. second, downstream of spo0a, the transcriptional and posttranslational regulation of the canonical set of four sporulation-specific sigma factors (sigma(f), sigma(e), sigma(g), and sigma(k)) display different patterns, not only compared to bacillus but also among clostridium organisms. finally, recent studies demonstrated that sigma(k), the last sigma factor to be activated according to the bacillus subtilis model, is involved in the very early stages of sporulation in clostridium acetobutylicum, c. perfringens, and c. botulinum as well as in the very late stages of spore maturation in c. acetobutylicum. despite profound differences in initiation, propagation, and orchestration of expression of spore morphogenetic components, these findings demonstrate not only the robustness of the endospore sporulation program but also the plasticity of the program to generate different complex phenotypes, some apparently regulated at the epigenetic level.
TIHT== 
ABHT== 

PMID== 22837302
TI  == lipid diversity among botulinum neurotoxin-producing clostridia.
AB  == clostridium botulinum has been classified into four groupings (groups i to iv) based on physiological characteristics and 16s rrna sequencing. we have examined  the lipid compositions of 11 representative strains of c. botulinum and a strain  of clostridium sporogenes by 2d-tlc and by ms. all strains contained phosphatidylglycerol (pg), cardiolipin (cl) and phosphatidylethanolamine (pe) in  both the all-acyl and the alk-1'-enyl (plasmalogen) forms. five strains in proteolytic group i, which are related to c. sporogenes, contained varying amounts of an ethanolamine-phosphate derivative of n-acetylglucosaminyl-diradylglycerol, which is also present in c. sporogenes. three strains in group ii, which are related to clostridium butyricum, clostridium beijerinckii and clostridium acetobutylicum, contained lipids characteristic of these saccharolytic species: a glycerol acetal and a pg acetal  of the plasmalogen form of pe. two group iii strains, which are related to clostridium novyi, contained amino-acyl derivatives of pg, which are also found in c. novyi. a strain in group iv had pe, pg and cl, but none of the distinguishing lipids. this work shows that the lipidome of c. botulinum is consistent with its classification by other methods.
TIHT== 
ABHT== 

PMID== 22139042
TI  == effects of different replicons in conjugative plasmids on transformation efficiency, plasmid stability, gene expression and n-butanol biosynthesis in clostridium tyrobutyricum.
AB  == clostridium tyrobutyricum atcc 25755 can produce butyric acid, acetic acid, and hydrogen as the main products from various carbon sources. in this study, c. tyrobutyricum was used as a host to produce n-butanol by expressing adhe2 gene under the control of a native thiolase promoter using four different conjugative  plasmids (pmtl82151, 83151, 84151, and 85151) each with a different replicon (pbp1 from c. botulinum nctc2916, pcb102 from c. butyricum, pcd6 from clostridium difficile, and pim13 from bacillus subtilis). the effects of different replicons  on transformation efficiency, plasmid stability, adhe2 expression and aldehyde/alcohol dehydrogenase activities, and butanol production by different mutants of c. tyrobutyricum were investigated. among the four plasmids and replicons studied, pmtl82151 with pbp1 gave the highest transformation efficiency, plasmid stability, gene expression, and butanol biosynthesis. butanol production from various substrates, including glucose, xylose, mannose, and mannitol were then investigated with the best mutant strain harboring adhe2 in pmtl82151. a high butanol titer of 20.5 g/l with 0.33 g/g yield and 0.32 g/l h productivity was obtained with mannitol as the substrate in batch fermentation with ph controlled at ~6.0.
TIHT== 
ABHT== 

PMID== 21815105
TI  == clostron-mediated engineering of clostridium.
AB  == the genus clostridium is a diverse assemblage of gram positive, anaerobic, endospore-forming bacteria. whilst certain species have achieved notoriety as important animal and human pathogens (e.g. clostridium difficile, clostridium botulinum, clostridium tetani, and clostridium perfringens), the vast majority of the genus are entirely benign, and are able to undertake all manner of useful biotransformations. prominent amongst them are those species able to produce the  biofuels, butanol and ethanol from biomass-derived residues, such as clostridium  acetobutylicum, clostridium beijerinkii, clostridium thermocellum, and clostridium phytofermentans. the prominence of the genus in disease and biotechnology has led to the need for more effective means of genetic modification. the historical absence of methods based on conventional strategies  for "knock-in" and "knock-out" in clostridium has led to the adoption of recombination-independent procedures, typified by clostron technology. the clostron uses a retargeted group ii intron and a retro-transposition-activated marker to selectively insert dna into defined sites within the genome, to bring about gene inactivation and/or cargo dna delivery. the procedure is extremely efficient, rapid, and requires minimal effort by the operator.
TIHT== 
ABHT== 

PMID== 21264064
TI  == small rnas in the genus clostridium.
AB  == the genus clostridium includes major human pathogens and species important to cellulose degradation, the carbon cycle, and biotechnology. small rnas (srnas) are emerging as crucial regulatory molecules in all organisms, but they have not  been investigated in clostridia. research on srnas in clostridia is hindered by the absence of a systematic method to identify srna candidates, thus delegating clostridial srna research to a hit-and-miss process. thus, we wanted to develop a method to identify potential srnas in the clostridium genus to open up the field  of srna research in clostridia. using comparative genomics analyses combined with predictions of rho-independent terminators and promoters, we predicted srnas in 21 clostridial genomes: clostridium acetobutylicum, c. beijerinckii, c. botulinum (eight strains), c. cellulolyticum, c. difficile, c. kluyveri (two strains), c. novyi, c. perfringens (three strains), c. phytofermentans, c. tetani, and c. thermocellum. although more than one-third of predicted srnas have shine-dalgarno (sd) sequences, only one-sixth have a start codon downstream of sd sequences; thus, most of the predicted srnas are noncoding rnas. quantitative reverse transcription-pcr (q-rt-pcr) and northern analysis were employed to test the presence of a randomly chosen set of srnas in c. acetobutylicum and several c. botulinum strains, leading to the confirmation of a large fraction of the tested  srnas. we identified a conserved, novel srna which, together with the downstream  gene coding for an atp-binding cassette (abc) transporter gene, responds to the antibiotic clindamycin. the number of predicted srnas correlated with the physiological function of the species (high for pathogens, low for cellulolytic,  and intermediate for solventogenic), but not with 16s rrna-based phylogeny.
TIHT== 
ABHT== 

PMID== 20597009
TI  == clostron-targeted mutagenesis.
AB  == members of the genus clostridium have long been recognised as important to humankind and its animals, both in terms of the diseases they cause and the useful biological processes they undertake. this has led to increasing efforts directed at deriving greater information on their basic biology, most notably through genome sequence. accordingly, annotated sequences of all of the most important species are now available. however, full exploitation of the data generated has been hindered by the lack of mutational tools that may be used in functional genomic studies. thus, the number of clostridial mutants generated has until recently been disappointingly small. in particular, the construction of directed mutants using classical homologous recombination-based methods has met with only limited success. moreover, most of these few mutants were constructed by the unstable integration of a plasmid into the chromosome via a single crossover event. as an alternative, recombination-independent strategies have been devised that are reliant upon a re-targeted group ii intron. one element in  particular, the clostron, provides the facility for the positive selection of insertional mutants. the generation of mutants using the clostron is extremely rapid (as little as 10 days) and is highly efficient and reproducible. furthermore, the insertions made are extremely stable. its deployment has considerably expanded available options for clostridial functional genomic studies.
TIHT== 
ABHT== 

PMID== 17658189
TI  == the clostron: a universal gene knock-out system for the genus clostridium.
AB  == progress in exploiting clostridial genome information has been severely impeded by a general lack of effective methods for the directed inactivation of specific  genes. those few mutants that have been generated have been almost exclusively derived by single crossover integration of a replication-deficient or defective plasmid by homologous recombination. the mutants created are therefore unstable.  here we have adapted a mutagenesis system based on the mobile group ii intron from the ltrb gene of lactococcus lactis (ll.ltrb) to function in clostridial hosts. integrants are readily selected on the basis of acquisition of resistance  to erythromycin, and are generated from start to finish in as little as 10 to 14  days. unlike single crossover plasmid integrants, the mutants are extremely stable. the system has been used to make 6 mutants of clostridium acetobutylicum  and 5 of clostridium difficile, exceeding the number of published mutants ever generated in these species. genes have also been inactivated for the first time in clostridium botulinum and clostridium sporogenes, suggesting the system will be universally applicable to the genus. the procedure is highly efficient and reproducible, and should revolutionize functional genomic studies in clostridia.
TIHT== 
ABHT== 

PMID== 16957268
TI  == complementation of a clostridium perfringens spo0a mutant with wild-type spo0a from other clostridium species.
AB  == to evaluate whether c. perfringens can be used as a model organism for studying the sporulation process in other clostridia, c. perfringens spo0a mutant ih101 was complemented with wild-type spo0a from four different clostridium species. wild-type spo0a from c. acetobutylicum or c. tetani, but not from c. botulinum or c. difficile, restored sporulation and enterotoxin production in ih101. the ability of spo0a from c. botulinum or c. difficile to complement the lack of spore formation in ih101 might be due, at least in part, to the low levels of spo0a transcription and spo0a production.
TIHT== 
ABHT== 

PMID== 16701501
TI  == insights in metabolism and toxin production from the complete genome sequence of  clostridium tetani.
AB  == the decryption of prokaryotic genome sequences progresses rapidly and provides the scientific community with an enormous amount of information. clostridial genome sequencing projects have been finished only recently, starting with the genome of the solvent-producing clostridium acetobutylicum in 2001. a lot of attention has been devoted to the genomes of pathogenic clostridia. in 2002, the  genome sequence of c. perfringens, the causative agent of gas gangrene, has been  released. currently in the finishing stage and prior to publication are the genomes of the foodborne botulism-causing c. botulinum and of c. difficile, the causative agent of a wide spectrum of clinical manifestations such as antibiotic-associated diarrhea. our team sequenced the genome of neuropathogenic  c. tetani, a gram-positive spore-forming bacterium predominantly found in the soil. in deep wound infections it occasionally causes spastic paralysis in humans and vertebrate animals, known as tetanus disease, by the secretion of potent neurotoxin, designated tetanus toxin. the toxin blocks the release of neurotransmitters from presynaptic membranes of interneurons of the spinal cord and the brainstem, thus preventing muscle relaxation. fortunately, this disease is successfully controlled through immunization with tetanus toxoid, a formaldehyde-treated tetanus toxin, but nevertheless, an estimated 400,000 cases  still occur each year, mainly of neonatal tetanus. the world health organization  has stated that neonatal tetanus is the second leading cause of death from vaccine preventable diseases among children worldwide. this minireview focuses on an analysis of the genome sequence of c. tetani e88, a vaccine production strain, which is a toxigenic non-sporulating variant of strain massachusetts. the genome  consists of a 2,799,250 bp chromosome encoding 2618 open reading frames. the tetanus toxin is encoded on a 74,082 kb plasmid, containing 61 genes. additional  virulence-related factors as well as an insight into the metabolic strategy of c. tetani with regard to its pathogenic phenotype will be presented. the information from other clostridial genomes by means of comparative analysis will also be explored.
TIHT== 
ABHT== 

PMID== 16677313
TI  == regulation of toxin and bacteriocin gene expression in clostridium by interchangeable rna polymerase sigma factors.
AB  == the production of major extracellular toxins by pathogenic strains of clostridium botulinum, clostridium tetani and clostridium difficile, and a bacteriocin by clostridium perfringens is dependent on a related group of rna polymerase sigma-factors. these sigma-factors (botr, tetr, tcdr and uvia) were shown to be sufficiently similar that they could substitute for one another in in vitro dna binding and run-off transcription experiments. in cells, however, the sigma-factors fell into two subclasses. botr and tetr were able to direct transcription of their target genes in a fully reciprocal manner. similarly, uvia and tcdr were fully interchangeable. neither botr nor tetr could substitute for uvia or tcdr, however, and neither uvia nor tcdr could direct transcription of the natural targets of botr or tetr. the extent of functional interchangeability  of the sigma-factors was attributed to the strong conservation of their subregion 4.2 sequences and the conserved -35 sequences of their target promoters, while restrictions on interchangeability were attributed to variations in their subregion 2.4 sequences and the target site -10 sequences. the four sigma-factors have been assigned to group 5 of the sigma(70) family and seem to have arisen from a common ancestral protein that may have co-evolved with the genes whose transcription they direct. a fifth clostridiumsigma-factor, sigma(y) of clostridium acetobutylicum, resembles the tcdr family, but was not functionally interchangeable with members of this family.
TIHT== 
ABHT== 

PMID== 11411680
TI  == clostridium uliginosum sp. nov., a novel acid-tolerant, anaerobic bacterium with  connecting filaments.
AB  == an anaerobic, acid-tolerant bacterium, ck55t, was isolated from an acidic forest  bog. cells of ck55t stained gram-negative but did not have an outer membrane. cells were spore-forming, motile rods with peritrichous flagella, formed chains or aggregates and were linked by connecting filaments that were composed of a core and outer sheath. cellobiose, glucose, xylose, mannose, mannitol, sucrose and peptone supported growth. arabinose, lactose, raffinose, h2/co2, co/co2, vanillate, casamino acids and various purines and pyrimidines did not support growth. growth on carbohydrates yielded acetate, butyrate, lactate, formate and h2 as end-products. growth was observed at ph 4.0-9.0, with an optimum at ph 6.5, and at 10-30 degrees c, with an optimum at 20-25 degrees c. at 20 degrees c, doubling times were 4 and 6 h at ph 6.5 and 4.0, respectively. hydrogenase activity in cell-free extracts was 12 u (mg protein)-1. ck55t did not: (i) contain detectable levels of co, formate, lactate dehydrogenases or cytochromes;  (ii) carry out dissimilatory reduction of nitrate or sulfate; or (iii) produce methane. thus, ck55t was characterized as a non-acetogenic, fermentative chemo-organotroph. the g+c content of ck55t was 28.0 mol%. ck55t was phylogenetically most closely related to clostridium botulinum (types b, e and f), clostridium acetobutylicum and other saccharolytic clostridia; the 16s rrna gene sequence similarity values to the nearest relatives of ck55t were approximately 97%. based on morphological, physiological and phylogenetic properties of ck55t, it is proposed that ck55t be termed clostridium uliginosum sp. nov. (= dsm 12992t = atcc baa-53t).
TIHT== 
ABHT== 

PMID== 3079172
TI  == host: vector systems for gene cloning in clostridium.
AB  == the genus clostridium contains some of the most toxic bacteria known to man (e.g., clostridium tetani, clostridium botulinum) as well as solvent-producing organisms of biotechnological interest (e.g., clostridium acetobutylicum). developments within the areas of plasmid vector construction and plasmid delivery methodology now provide the opportunity for applying recombinant dna technology to this important group of bacteria.
TIHT== 
ABHT== 

PMID== 5335894
TI  == serological studies of clostridium botulinum type e and related organisms.
AB  == clostridium botulinum type e antigens prepared from washed cells by either formalin treatment or heating at 100 c were used for immunizing rabbits. agglutination tests showed that high levels of antibody were produced by both types of preparations. flagellar antigens were highly strain-specific, whereas the somatic antigens were sufficiently similar to produce complete cross-agglutination. one toxigenic strain produced toxigenic and nontoxigenic progeny which were physiologically and antigenically identical in all other respects. other nontoxigenic strains whose growth, physiological, and morphological characters were identical to type e and strains which had some physiological differences completely cross-agglutinated with type e strains via the somatic antigen. neither type of antiserum agglutinated other clostridia against which they were tested except for c. acetobutylicum. this reaction seems  to be due to a nonspecific anamnestic response and does not appear to be related  to the immunizing strains. the nontoxigenic strains studied seem to have no greater antigenic differences from type e strains than the type e strains have from each other.
TIHT== 
ABHT== 

PMID== 4288828
TI  == antagonistic effect on clostridium botulinum type e by organisms resembling it.
AB  == a bacteriocin-like substance, active against strains of clostridium botulinum type e, is produced by certain nontoxic organisms whose biochemical properties and morphological characteristics are similar to type e. the substance, for which the name "boticin e" is proposed, is bacteriolytic for vegetative cells and bacteriostatic for spores of type e. its spectrum of activity is somewhat strain-specific. of the clostridial species tested, only c. botulinum type e and, to a lesser extent, c. perfringens and c. acetobutylicum, but not c. botulinum types a, b, or f, are sensitive. irreversibly resistant variants originating from both vegetative cells and spores of certain strains were obtained. the active substance is heat-stable and dialyzable, and is not inactivated by chloroform but is digested by trypsin. ethyl alcohol and acetone precipitates are fully active,  whereas trichloroacetic acid precipitates are only partially active. other nontoxic organisms producing similar antagonistic substances are discussed.
TIHT== 
ABHT== 

