@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23647919
TI  == sequences of multiple bacterial genomes and a chlamydia trachomatis genotype from direct sequencing of dna derived from a vaginal swab diagnostic specimen.
AB  == ultra-deep illumina sequencing was performed on whole genome amplified dna derived from a chlamydia trachomatis-positive vaginal swab. alignment of reads with reference genomes allowed robust snp identification from the c. trachomatis  chromosome and plasmid. this revealed that the c. trachomatis in the specimen was very closely related to the sequenced urogenital, serovar f, clade t1 isolate f-sw4. in addition, high genome-wide coverage was obtained for prevotella melaninogenica, gardnerella vaginalis, clostridiales genomosp. bvab3 and mycoplasma hominis. this illustrates the potential of metagenome data to provide  high resolution bacterial typing data from multiple taxa in a diagnostic specimen.
TIHT== 
ABHT== 

PMID== 17687006
TI  == targeted pcr for detection of vaginal bacteria associated with bacterial vaginosis.
AB  == several novel bacterial species have been detected in subjects with bacterial vaginosis (bv) by using broad-range pcr assays, but this approach is insensitive  for detecting minority species. we developed a series of taxon-directed 16s rrna  gene pcr assays for more sensitive detection of key vaginal bacteria. we sought to determine the prevalence of each species in the vagina, its association with bv, and the utility of pcr for the microbiological diagnosis of bv. targeted pcr  assays were developed for 17 vaginal bacterial species and applied to 264 vaginal-fluid samples from 81 subjects with and 183 subjects without bv. the results were compared to those of two widely accepted methods for diagnosing bv,  the use of clinical findings (amsel criteria) and the interpretation of vaginal-fluid gram stains (nugent criteria). leptotrichia/sneathia, atopobium vaginae, an eggerthella-like bacterium, megasphaera species, and three novel bacteria in the order clostridiales are among the bacterial species significantly associated with bv. pcr detection of either a megasphaera species or one of the clostridiales bacteria yielded a sensitivity of 99% and a specificity of 89% for  diagnosis of bv compared to the amsel clinical criteria and a sensitivity of 95.9% and a specificity of 93.7% compared to the nugent criteria (gram stain). pcr detection of one or more fastidious bacterial species is a more reliable indicator of bv than detection of bacteria, such as gardnerella vaginalis, previously linked to bv, highlighting the potential of pcr for the diagnosis of bv.
TIHT== 
ABHT== 

PMID== 17510259
TI  == rapid characterization of the normal and disturbed vaginal microbiota by application of 16s rrna gene terminal rflp fingerprinting.
AB  == bacterial vaginosis (bv) is a prevalent infection in women of reproductive age associated with numerous sequelae, including preterm delivery, amniotic fluid infections and an increased risk of acquiring sexually transmitted diseases. the  vaginal microbiota in bv patients is characterized by a shift from lactobacilli to a diverse spectrum of mostly anaerobic bacteria. in this study, terminal restriction fragment length polymorphism (t-rflp) was used to characterize the vaginal bacterial communities from 50 women with bv and 20 healthy subjects. in the bv samples, 23 species or phylotypes from 17 genera could be identified, including atopobium vaginae, megasphaera sp., lactobacillus iners, gardnerella vaginalis and three recently described phylotypes from the order clostridiales. the number of detected species or phylotypes was on average 6.3 per sample (range 2-14). in contrast, in normal samples, only lactobacillus species could be identified. in conclusion, t-rflp provides a rapid and reliable technique to investigate the diversity of the predominant vaginal microbiota and allows differentiation of the flora of bv and healthy women. as such, t-rflp may be helpful both in the diagnosis of bv from vaginal fluids and in a better understanding of the bacterial succession involved in the aetiology of bv.
TIHT== 
ABHT== 

PMID== 16267321
TI  == molecular identification of bacteria associated with bacterial vaginosis.
AB  == background: bacterial vaginosis affects millions of women and is associated with  several serious health conditions. the cause of bacterial vaginosis remains poorly understood despite numerous studies based on cultures. bacteria in microbial communities can be identified without cultivation by characterizing their ribosomal dna (rdna) sequences. methods: we identified bacteria in samples  of vaginal fluid with a combination of broad-range polymerase-chain-reaction (pcr) amplification of 16s rdna with clone analysis, bacterium-specific pcr assay of 16s rdna, and fluorescence in situ hybridization (fish) performed directly on  vaginal fluid from 27 subjects with bacterial vaginosis and 46 without the condition. twenty-one subjects were studied with the use of broad-range pcr of 16s rdna, and 73 subjects were studied with the use of bacterium-specific pcr. results: women without bacterial vaginosis had 1 to 6 vaginal bacterial species (phylotypes) in each sample (mean, 3.3), as detected by broad-range pcr of 16s rdna, and lactobacillus species were the predominant bacteria noted (83 to 100 percent of clones). women with bacterial vaginosis had greater bacterial diversity (p<0.001), with 9 to 17 phylotypes (mean, 12.6) detected per sample and newly recognized species present in 32 to 89 percent of clones per sample library (mean, 58 percent). thirty-five unique bacterial species were detected in the women with bacterial vaginosis, including several species with no close cultivated relatives. bacterium-specific pcr assays showed that several bacteria  that had not been previously described were highly prevalent in subjects with bacterial vaginosis but rare in healthy controls. fish confirmed that newly recognized bacteria detected by pcr corresponded to specific bacterial morphotypes visible in vaginal fluid. conclusions: women with bacterial vaginosis have complex vaginal infections with many newly recognized species, including three bacteria in the clostridiales order that were highly specific for bacterial vaginosis.
TIHT== 
ABHT== 

