@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23603688
TI  == site-directed mutations in the lanthipeptide mutacin 1140.
AB  == the oral bacterium streptococcus mutans, strain jh1140, produces the antibiotic mutacin 1140. mutacin 1140 belongs to a group of antibiotics called lanthipeptides. more specifically, mutacin 1140 is related to the epidermin type  a(i) lanthipeptides. mutagenesis experiments of this group of lanthipeptides have been primarily restricted to the posttranslationally modified meso-lanthionine and 3-methyllanthionine residues. site-directed mutagenesis of the core peptide of mutacin 1140 was performed using the suicide vector pva891. substitutions of the n-terminal residue, the charged residue in the hinge region, and residues in  ring a and intertwined rings c and d were investigated. a truncation and insertion of residues in ring a and intertwined rings c and d were also performed to determine whether or not they would alter the antimicrobial activity of the producing strain. bioassays revealed that five of 14 mutants studied had improved antimicrobial activity against the indicator strain micrococcus luteus atcc 10240. mics against streptococcus mutans ua159, streptococcus pneumoniae atcc 27336, staphylococcus aureus atcc 25923, clostridium difficile uk1, and micrococcus luteus atcc 10240 were determined for three mutacin 1140 variants that had the most significant increases in bioactivity in the m. luteus bioassay. this mutagenesis study of the epidermin group of lanthipeptides shows that antimicrobial activity can be significantly improved.
TIHT== 
ABHT== 

PMID== 10616964
TI  == antibacterial activity of aristolochia paucinervis pomel.
AB  == several fractions of the methanolic extract of the rhizome or the leaves of aristolochia paucinervis pomel were screened for antibacterial activity using the agar dilution method against fourteen reference bacterial strains. only three fractions (defatted chloroformic rhizome fraction: aprc, rhizome ethyl acetate fraction: apre and leaf chloroform fraction: aplc) showed an activity against at  least one of the microorganisms tested. the minimum inhibitory concentration (mic) determination showed that aprc was the most active against clostridium perfringens, clostridium difficile, enterococcus faecalis, micrococcus luteus and bacillus subtilis. the high bacteriostatic activity of aprc was confirmed by its  mic determination against clinical strains of c. perfringens (n = 32), c. difficile (n = 31), and e. faecalis (n = 22). results of this study suggest the potential interest of this highly active fraction and support the use of a. paucinervis pomel in moroccan traditional medicine to treat skin and soft-tissue  infections, especially gas gangrene and intestinal diseases.
TIHT== 
ABHT== 

PMID== 9125011
TI  == the stethoscope. a potential source of nosocomial infection?
AB  == background: stethoscope diaphragms have been shown to harbor potentially pathogenic bacteria. objectives: to assess bacterial contamination on the diaphragm and under the plastic rim that secures the diaphragm of stethoscopes of physicians, nurses, medical students, and house staff in an intensive care unit and a general medical ward of a large university hospital. also to compare the effectiveness of various cleaning agents and assess the transmissibility of bacteria from contaminated stethoscopes to human skin. methods: aerobic and anaerobic bacterial cultures were performed on 40 randomly selected stethoscopes. we compared the effects of isopropyl alcohol, sodium hypochlorite (bleach), and benzalkonium chloride swabs, as well as soap and water, on reducing bacterial contamination on the stethoscope diaphragm and under the rim. the transmissibility of micrococcus luteus inoculated onto a stethoscope diaphragm to clean human skin was also determined. results: eleven genera and species of bacteria were isolated, with coagulase-negative staphylococcus present on 100% of stethoscopes and staphylococcus aureus on 38%. clostridium difficile was not isolated. the mean (+/-se) number of total colony-forming units was 158 +/- 33 per diaphragm and 289 +/- 54 per rim. physicians' stethoscope diaphragms had significantly more colony-forming units of coagulase-negative staphylococci than  those of nurses: 163 +/- 44 vs 50 +/- 12, respectively (p = .02). the most effective cleaning agent was isopropyl alcohol after cleaning the diaphragm surface, the stethoscope diaphragms contained 0.2 +/- 0.2 colony-forming units and the rims contained 2.2 +/- 1.5 colony-forming units (p = .01). in addition, m luteus was transferred from inoculated stethoscopes to human skin. conclusions: most stethoscopes harbor potential pathogens but are not a source of c difficile. physicians' stethoscopes generally had a higher bacterial load than nurses' stethoscopes. isopropyl alcohol is an effective cleaning agent when applied to the stethoscope diaphragm. stethoscopes transfer m luteus to human skin, making it likely that other bacteria can be transferred as well.
TIHT== 
ABHT== 

