@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 11479641
TI  == etiologies of the urinary tract infections in a yemeni city.
AB  == objective: to determine the causative agents of urinary tract infection in yemeni patients in sana'a city, and to determine the antibiotic susceptibilities of these agents in vitro. methods: consecutive mid-stream urine specimens were submitted to our laboratory by 4029 patients in sana'a city from 1990 to the end  of 1999. the specimens were cultured and the isolates were identified using standard microbiological techniques. the antibiotic susceptibilities of the isolates were also determined (in vitro). results: the number of patients with urinary tract infection who yielded positive cultures from their mid stream urine specimens was 685 out of 4029 patients (17%). the ratio of female-to-male patients was 462:223 (2.07:1). the causative agents were mainly members of the family enterobacteriaceae, 579 out of the 685 isolates (84.5%). escherichia coli  was the main pathogen, 357 isolates out of all the isolates (52%) followed by klebsiella pneumoniae, 143 isolates (21%) and proteus species, 56 isolates (8%).  the other pathogens (staphylococcus aureus, pseudomonas aeruginosa, enterobacter  aerogenes, staphylococcus saprophyticus, corynebacterium urealyticum and enterococcus faecalis) constituted 129 out of the 685 isolates (19%). there was a shift in the types of the causative agents of urinary tract infection between the first and 2nd halves of the study period. the isolation of escherichia coli decreased from 60% in the first half to 42% in the 2nd. whereas klebsiella pneumoniae increased from 16% in the first half to 27% in the 2nd, proteus species from 8% to 9%, staphylococcus aureus from 5% to 7%, pseudomonas aeruginosa from 3% to 7%, enterobacter aerogenes from 3% to 3.5%, staphylococcus  saprophyticus from 2% to 3% and corynebacterium urealyticum from 1% to 2%. ninety percent of all the urinary pathogens were sensitive to ciprofloxacin, 75% to nitrofurantoin, 57% to gentamicin, 46% to cefaclor, 46% to nalidixic acid, 39% to doxycycline, 37% to co-trimoxazole and 20% to ampiclox. conclusion: the types of  urinary tract pathogens and their antibiotic susceptibilities in addition to the  rate of isolation from male and female patients are reported. it is recommended that ciprofloxacin and nitrofurantoin or both are used in the blind treatment of  urinary tract infection while awaiting the culture and sensitivity results. it is also recommended to continuously monitor the pattern of urinary pathogens from the community to guide the blind treatment of patients in the future.
TIHT== 
ABHT== 

