@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 19664834
TI  == microarray-based comparative genomic indexing of the cronobacter genus (enterobacter sakazakii).
AB  == cronobacter (enterobacter sakazakii) is a recently defined genus consisting of 6  species. to extend our understanding of the genetic relationship between cronobacter sakazakii baa-894 and the other species of this genus, microarray-based comparative genomic indexing (cgi) was undertaken to determine the presence/absence of genes identified in the former sequenced genome and to compare 276 selected open reading frames within the different cronobacter strains. seventy-eight cronobacter strains (60 c. sakazakii, 8 c. malonaticus, 5  c. dublinensis, 2 c. muytjensii, 1 c. turicensis, 1 c. genomospecies 1, and 1 cronobacter sp.) representing clinical and environmental isolates from various geographical locations were investigated. hierarchical clustering of the cgi data showed that the species grouped as clusters. the 5 c. dublinensis and 2 c. muytjensii strains examined formed distinct species clusters. moreover, all of the c. sakazakii and 3 of 8 c. malonaticus strains formed a large cluster. the remaining c. malonaticus strains formed a sub-group within a larger cluster that  also contained c. turicensis, c. genomospecies 1, and an unknown cronobacter sp.  cronobacter sakazakii and 3 of 8 c. malonaticus strains could be distinguished from the others within the collection by the presence of 10 fimbrial related genes. similarly, capsule and/or lipopolysaccharide (lps) related glycosyltransferases differentiated several of the c. sakazakii strains from each other.
TIHT== 
ABHT== 

PMID== 18523192
TI  == cronobacter gen. nov., a new genus to accommodate the biogroups of enterobacter sakazakii, and proposal of cronobacter sakazakii gen. nov., comb. nov., cronobacter malonaticus sp. nov., cronobacter turicensis sp. nov., cronobacter muytjensii sp. nov., cronobacter dublinensis sp. nov., cronobacter genomospecies  1, and of three subspecies, cronobacter dublinensis subsp. dublinensis subsp. nov., cronobacter dublinensis subsp. lausannensis subsp. nov. and cronobacter dublinensis subsp. lactaridi subsp. nov.
AB  == [enterobacter] sakazakii is an opportunistic pathogen that can cause infections in neonates. this study further clarifies the taxonomy of isolates described as [e.] sakazakii and completes the formal description of the proposed reclassification of these organisms as novel species and subspecies within a proposed novel genus, cronobacter gen. nov. [e.] sakazakii was first defined in 1980, however recent polyphasic taxonomic analysis has determined that this group of organisms consists of several genomospecies. in this study, the phenotypic descriptions of the proposed novel species are expanded using biotype 100 and biolog phenotype microarray data. further dna-dna hybridization experiments showed that malonate-positive strains within the [e.] sakazakii genomospecies represent a distinct species, not a subspecies. dna-dna hybridizations also determined that phenotypically different strains within the proposed species, cronobacter dublinensis sp. nov., belong to the same species and can be considered as novel subspecies. based on these analyses, the following alternative classifications are proposed: cronobacter sakazakii gen. nov., comb.  nov. [type strain atcc 29544(t) (=nctc 11467(t))]; cronobacter malonaticus sp. nov. [type strain cdc 1058-77(t) (=lmg 23826(t)=dsm 18702(t))]; cronobacter turicensis sp. nov. [type strain z3032(t) (=lmg 23827(t)=dsm 18703(t))]; cronobacter muytjensii sp. nov. [type strain atcc 51329(t) (=cip 103581(t))]; cronobacter dublinensis sp. nov. [type strain des187(t) (=lmg 23823(t)=dsm 18705(t))]; cronobacter dublinensis subsp. dublinensis subsp. nov. [type strain des187(t) (=lmg 23823(t)=dsm 18705(t))]; cronobacter dublinensis subsp. lausannensis subsp. nov. [type strain e515(t) (=lmg 23824=dsm 18706(t))], and cronobacter dublinensis subsp. lactaridi subsp. nov. [type strain e464(t) (=lmg 23825(t)=dsm 18707(t))].
TIHT== 
ABHT== 

PMID== 17439656
TI  == the taxonomy of enterobacter sakazakii: proposal of a new genus cronobacter gen.  nov. and descriptions of cronobacter sakazakii comb. nov. cronobacter sakazakii subsp. sakazakii, comb. nov., cronobacter sakazakii subsp. malonaticus subsp. nov., cronobacter turicensis sp. nov., cronobacter muytjensii sp. nov., cronobacter dublinensis sp. nov. and cronobacter genomospecies 1.
AB  == background: enterobacter sakazakii is an opportunistic pathogen that can cause infections such as necrotizing enterocolitis, bacteraemia, meningitis and brain abscess/lesions. when the species was defined in 1980, 15 biogroups were described and it was suggested that these could represent multiple species. in this study the taxonomic relationship of strains described as e. sakazakii was further investigated. results: strains identified as e. sakazakii were divided into separate groups on the basis of f-aflp fingerprints, ribopatterns and full-length 16s rrna gene sequences. dna-dna hybridizations revealed five genomospecies. the phenotypic profiles of the genomospecies were determined and biochemical markers identified. conclusion: this study clarifies the taxonomy of  e. sakazakii and proposes a reclassification of these organisms.
TIHT== 
ABHT== 

