@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25796741
TI  == [bacteria isolated from surgical infections and its susceptibilities to antimicrobial agents - special references to bacteria isolated between april 2011 and march 2012].
AB  == bacteria isolated from surgical infections during the period from april 2011 to march 2012 were investigated in a multicenter study in japan, and the following results were obtained. in this series, 785 strains including 31 strains of candida spp. were isolated from 204 (78.8%) of 259 patients with surgical infections. five hundred and twenty three strains were isolated from primary infections, and 231 strains were isolated from surgical site infection. from primary infections, anaerobic gram-negative bacteria were predominant, followed by aerobic gram-negative bacteria, while from surgical site infection aerobic gram-positive bacteria were predominant, followed by anaerobic gram-negative bacteria. among aerobic gram-positive bacteria, the isolation rate of enterococcus spp. was highest, followed by streptococcus spp. and staphylococcus  spp., in this order, from primary infections, while enterococcus spp. was highest, followed by staphylococcus spp. from surgical site infection. among aerobic gram-negative bacteria, escherichia coli was the most predominantly isolated from primary infections, followed by klebsiella pneumoniae, pseudomonas  aeruginosa and enterobacter cloacae, in this order, and from surgical site infection, e. coli was most predominantly isolated, followed by p. aeruginosa, k. pneumoniae, and e. cloacae. among anaerobic gram-positive bacteria, the isolation rate of eggerthella lenta was the highest from primary infections, followed by parvimonas micra, collinsella aerofaciens, lactobacillus acidophilus and finegoldia magna, and from surgical site infection, e. lenta was most predominantly isolated, followed by p micra and l. acidophilus, in this order. among anaerobic gram-negative bacteria, the isolation rate of bacteroidesfragilis was the highest from primary infections, followed by bilophila wadsworthia, bacteroides thetaiotaomicron, bacteroides uniformis and bacteroides vulgatus, and from surgical site infection, b. fragilis was most predominantly isolated, followed by bacteroides caccae, b. thetaiotaomicron, bacteroides ovatus and b. wadsworthia, in this order. in this series, vancomycin-resistant mrsa (methicillin-resistant staphylococcus aureus), vancomycin-resistant enterococcus  spp. and multidrug-resistant p. aeruginosa were not observed. we should carefully follow up b. wadsworthia which was resistant to various antimicrobial agents, and also bacteroides spp. which was resistant to many beta-lactams.
TIHT== 
ABHT== 

PMID== 22552027
TI  == influence of red wine polyphenols and ethanol on the gut microbiota ecology and biochemical biomarkers.
AB  == background: few studies have investigated the effect of dietary polyphenols on the complex human gut microbiota, and they focused mainly on single polyphenol molecules and select bacterial populations. objective: the objective was to evaluate the effect of a moderate intake of red wine polyphenols on select gut microbial groups implicated in host health benefits. design: ten healthy male volunteers underwent a randomized, crossover, controlled intervention study. after a washout period, all of the subjects received red wine, the equivalent amount of de-alcoholized red wine, or gin for 20 d each. total fecal dna was submitted to polymerase chain reaction(pcr)-denaturing gradient gel electrophoresis and real-time quantitative pcr to monitor and quantify changes in fecal microbiota. several biochemical markers were measured. results: the dominant bacterial composition did not remain constant over the different intake  periods. compared with baseline, the daily consumption of red wine polyphenol for 4 wk significantly increased the number of enterococcus, prevotella, bacteroides, bifidobacterium, bacteroides uniformis, eggerthella lenta, and blautia coccoides-eubacterium rectale groups (p < 0.05). in parallel, systolic and diastolic blood pressures and triglyceride, total cholesterol, hdl cholesterol, and c-reactive protein concentrations decreased significantly (p < 0.05). moreover, changes in cholesterol and c-reactive protein concentrations were linked to changes in the bifidobacteria number. conclusion: this study showed that red wine consumption can significantly modulate the growth of select gut microbiota in humans, which suggests possible prebiotic benefits associated with  the inclusion of red wine polyphenols in the diet. this trial was registered at controlled-trials.com as isrctn88720134.
TIHT== 
ABHT== 

