@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 15295960
TI  == implant therapy following liver transplantation: clinical and microbiological results after 10 years.
AB  == background: the number of immunocompromised patients is increasing as a consequence of successful organ transplantation. placing dental implants in these patients has been questioned because of their increased risk for infections. the  10-year follow-up data of a 71-year-old liver transplant recipient with long-term immunosuppressive therapy is reported. six months after liver transplantation, two interforaminal implants were inserted in the edentulous mandible, and an overdenture using non-rigid telescopic attachments was fabricated 3 months later. methods: oral clinical parameters included the modified plaque index, sulcus fluid flow rate, modified bleeding index, probing depth, distance implant mucosa, attachment level, width of the keratinized mucosa and mobility values. the distance implant bone (dib) was determined on digital panoramic radiographs. the  levels of eight periodontal marker organisms were established using dna probe technology. additionally, swabs of the edentulous oral mucosa were taken for microbiological culture and antimicrobial resistance testing. results: the peri-implant parameters were within normal ranges indicating a stable osseointegration with moderate vertical bone loss. actinobacillus actinomycetemcomitans, tannerella forsythensis, campylobacter rectus, and treponema denticola were not detected. low levels of porphyromonas gingivalis, fusobacterium nucleatum, and eikenella corrodens were found. prevotella intermedia was the only bacterium with a level higher than 10(4). the mucosal swabs indicated the presence of an abundant normal oral flora, including escherichia coli and candida albicans. the antibiogram revealed multiple resistance to antibiotics. conclusion: this case report suggests that immunocompromised patients can be successfully rehabilitated with dental implants.
TIHT== 
ABHT== 

PMID== 16887581
TI  == subgingival microflora in smokers with early onset periodontitis.
AB  == cigarette smoking is a potent risk factor which has recently been associated with periodontal disease progression. the objective of this study was to detect the microbial profile of early onset periodontitis in smokers and compare it to that  of non-smokers. the study population consisted of 50 systemically healthy individuals aged 25 to 38 years, exhibiting early onset periodontitis. 25 patients were smokers (> 20 cigarettes/day) and 25 non-smokers. two pooled bacterial samples comprised of four periodontal sites with probing depth > 5 mm each, were collected from each individual. the samples were cultured aerobically  and anaerobically for bacterial isolation using selective and non-selective media. isolates were characterized to species level by conventional biochemical tests and various identification kits. the differences in bacterial counts using  the mann whitney u test were statistically significant for staphylococcus aureus, campylobacter concisus, eikenella corrodens, escherichia coli, bacteroides forsythus, bacteroides gracilis, campylobacter rectus, porphyromonas gingivalis,  selenomonas sputigena and candida albicans in smokers. statistically significant  differences for peptostreptococcus micros, actinomyces naeslundii, eubacterium lentum and capnocytophaga gingivalis were detected in non-smokers. the isolation  of bacteria belonging to the exogenous flora like e. coli, c. albicans and s. aureus in smokers microflora underscores the importance of the host which is adversely affected by cigarette smoking.
TIHT== 
ABHT== 

PMID== 8708939
TI  == comparison of the pro-inflammatory cytokine-stimulating activity of the surface-associated proteins of periodontopathic bacteria.
AB  == saline extraction of the periodontopathic bacterium, actinobacillus actinomycetemcomitans, releases surface-associated material (sam), a complex mixture of proteins and carbohydrates with potent biological actions on isolated  bone and on various mammalian cell populations. in this study, the relative ability of the sam from 5 organisms, implicated in the pathology of periodontal disease, to stimulate human mesenchymal and myelomonocytic cells to synthesize the proinflammatory cytokines - interleukin (il)-1 beta, il-6 and tumour necrosis factor (tnf)alpha has been investigated. the bacteria investigated were actinobacillus actinomycetemcomitans, eikenella corrodens, porphyromonas gingivalis, prevotella intermedia and campylobacter rectus. human cells were exposed to a four log order range of concentrations of the sam, or of escherichia coli lipopolysaccharide, to provide full agonist dose responses in order to allow comparison of the potency and efficacy of each sam. all sams demonstrated the capacity to stimulate human gingival fibroblasts (hgfs), human peripheral blood mononuclear cells (pbmcs) or the myelomonocytic cell line - mono-mac-6 to release one or all of the cytokines assayed. activity was heat- and trypsin-sensitive suggesting that the active components were proteinaceous. however, there were substantial differences in the potency and efficacy of each sam when compared on  a concentration basis (w/v). the most active sam was from a. actinomycetemcomitans with those from e. corrodens and p. gingivalis being slightly less active. the least active cytokine-stimulating sams were from c. rectus and pr. intermedia. one major difference between the sams and e. coli lps  was the inability of the former to stimulate hgfs to release il-1 beta or tnf alpha although they could stimulate pbmcs to release these cytokines. this may have relevance to the pathology of the periodontal diseases.
TIHT== 
ABHT== 

