@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 18225640
TI  == decontamination effects of low-temperature plasma generated by corona discharge.  part ii: new insights.
AB  == the second part of our paper presents the results of experiments with the decontamination of surfaces by low-temperature plasma generated by corona discharge in air at atmospheric pressure. a simple device is described and the effects of the corona discharge on model microorganisms, viz. the yeast candida albicans, gram-negative bacteria escherichia coli, enterobacter aerogenes, neisseria sicca, stenotrophomonas maltophilia, gram-positive bacteria deinococcus radiodurans, enterococcus faecium, staphylococcus epidermidis, streptococcus sanguinis, and vegetative and spore forms of geobacillus stearothermophilus are discussed. a similar microbicidal effect after about one-minute exposure was observed in all vegetative forms of the microorganisms. measurement in growth inhibition zones on a semisolid medium was used to determine the dependence of the microbicidal effect on exposure time and the distance between electrodes. counting of colonies served to assess the microbicidal effect of the discharge on contaminated inert surfaces observable after more than 1 min exposure. geobacillus stearothermophilus spores were found to have several times lower susceptibility to the action of the discharge and the microbicidal effect was observed only after an 8 min exposure. reaction with the iodide reagent did not unambiguously demonstrate the difference between ozone and singlet oxygen as presumed active components of the corona. the area distribution of reactive oxygen species was determined; it was found to differ from the wartburg law depending on exposure time. qualitative evidence was obtained on the penetration  of the reactive oxygen species into the semisolid medium.
TIHT== 
ABHT== 

PMID== 8167004
TI  == novel automated microbial screening of platelet concentrates.
AB  == the recovery of bacteria and the speed of detection of microbial growth in platelet concentrates (pc) were studied, comparing a novel automated blood culture system (bact/alert) with two traditional methods. full-scale experiments  were performed with a total of 33 units of pc (average content 320 x 10(9) platelets per unit) obtained from pooled buffy coats. six strains known as possible pc contaminants were tested: s. epidermidis, s. aureus, p. aeruginosa, b. cereus, e. aerogenes, and s. sanguis. using an inoculum of 50-98 bacteria/ml,  bacterial contamination was detected in all of 11 pcs on 132 sampling occasions.  with a small inoculum (0.3-9 bacteria/ml), the bacterial contamination was detected in all pcs in which abundant growth appeared, but failed to be detected  in some instances where the bacterial content was very small. all of 11 uninoculated pc controls were negative. with the automated method the time for detection of a culture-positive pc was 6-16 h, clearly shorter than with the two  manual-visual systems. the new system provides a rapid, reliable, and labour-saving method for screening of bacterial contamination in pcs. this would  increase safety particularly if the present 5-day shelf life were extended.
TIHT== 
ABHT== 

PMID== 6888963
TI  == laboratory diagnosis of bacteremia by headspace gas-liquid chromatography.
AB  == the growth of staphylococcus aureus, streptococcus pneumoniae, s. fecalis, s. sanguis, s. bovis, s. mitior, s. agalactiae, escherichia coli, a-d group, klebsiella aerogenes, k. oxytoca, enterobacter cloacae, proteus mirabilis, serratia marcescens, pasteurella multocida or listeria monocytogenes in 83 blood  cultures was detected in a 1.5-min analysis using head-space gas-liquid chromatography. two hundred and twenty-four blood cultures in which there was no  growth of micro-organisms were negative in the analysis. the analysis detected the growth of s. epidermidis in only 6 of 26 blood cultures and failed to detect  the growth of pseudomonas aeruginosa, candida albicans and species of micrococcus, corynebacterium or bacillus in 18 blood cultures.
TIHT== 
ABHT== 

