@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 24411451
TI  == functional characterization of the sucrose isomerase responsible for trehalulose  production in plant-associated pectobacterium species.
AB  == fifty-three plant-associated microorganisms were investigated for their ability to convert sucrose to its isomers. these microorganisms included one dickeya zeae isolate and 7 enterobacter, 3 pantoea, and 43 pectobacterium species. eleven out  of the 53 strains (21%) showed the ability to transform sucrose to isomaltulose and trehalulose. among those, pectobacterium carotovorum kkh 3-1 showed the highest bioconversion yield (97.4%) from sucrose to its isomers. in this strain,  the addition of up to 14% sucrose in the medium enhanced sucrose isomerase (siase) production. the siase activity at 14% sucrose (47.6 u/mg dcw) was about 3.6-fold higher than that of the negative control (13.3 u/mg dcw at 0% sucrose).  the gene encoding siase, which is comprised a 1776 bp open reading frame (orf) encoding 591 amino acids, was cloned from p. carotovorum kkh 3-1 and expressed in escherichia coli. the recombinant siase (pcsi) was shown to have optimum activity at ph 6.0 and 40 degrees c. the reaction temperature significantly affected the ratio of sucrose isomers produced by pcsi. the amount of trehalulose increased from 47.5% to 79.1% as temperature was lowered from 50 degrees c to 30 degrees c, implying that siase activity can be controlled by reaction temperature.
TIHT== 
ABHT== 

PMID== 18066619
TI  == carbohydrate and ethane release with erwinia carotovora subspecies betavasculorum--induced necrosis.
AB  == erwinia carotovora subspecies betavasculorum, also known as e. betavasculorum and pectobacterium betavasculorum, is a soil bacterium that has the capacity to cause root rot necrosis of sugarbeets. the qualitatively different pathogenicity exhibited by the virulent e. carotovora strain and two avirulent strains, a citrobacter sp. and an enterobacter cloacae, was examined using digital analysis  of photographic evidence of necrosis as well as for carbohydrate, ethane, and ethylene release compared with uninoculated potato tuber slices. visual scoring of necrosis was superior to digital analysis of photographs. the release of carbohydrates and ethane from potato tuber slices inoculated with the soft rot necrosis-causing erwinia was significantly greater than that of potato tuber slices that had not been inoculated or that had been inoculated with the nonpathogenic e. cloacae and citrobacter sp. strains. interestingly, ethylene production from potato slices left uninoculated or inoculated with the nonpathogenic citrobacter strain was 5- to 10-fold higher than with potato slices inoculated with the pathogenic erwinia strain. these findings suggest that (1) carbohydrate release might be a useful measure of the degree of pathogenesis, or  relative virulence; and that (2) bacterial suppression of ethylene formation may  be a critical step in root rot disease formation.
TIHT== 
ABHT== 

PMID== 17483271
TI  == characterization of the zinc-containing metalloprotease encoded by zpx and development of a species-specific detection method for enterobacter sakazakii.
AB  == enterobacter sakazakii causes a severe form of neonatal meningitis that occurs as sporadic cases as well as outbreaks. the disease has been epidemiologically associated with consumption of reconstituted, dried infant formulas. very little  information is available regarding pathogenicity of the organism and production of virulence factors. clinical and environmental strains were screened for production of factors which have activity against chinese hamster ovary (cho) cells in tissue culture. polymyxin b lysate and sonicate preparations but not culture supernatants from the strains caused "rounding" of cho cells. subsequent  studies showed that the cho cell-rounding factor is a proteolytic enzyme that has activity against azocasein. the cell-bound protease was isolated by using a combination of polymyxin b lysis, followed by sonication of cells harvested from  tryptone broth. the protease was purified to homogeneity by sequential ammonium sulfate precipitation, gel filtration chromatography with sephadex g-100, hydrophobic interaction chromatography with phenyl-sepharose cl-4b, and a second  gel filtration with sephadex g-100. in addition to activity against azocasein, the purified protease also exhibits activity against azocoll and insoluble casein but not elastin. the protease has a molecular weight of 38,000 and an isoelectric point of 4.4. it is heat labile and for maximal activity against azocasein has an optimum temperature of 37 degrees c and a ph range of 5 to 7. proteolytic activity is inhibited by ortho-phenanthroline and zincov but is not affected by phenylmethylsulfonyl fluoride, n-ethylmaleimide, and trypsin inhibitors, which demonstrates that the protease is a zinc-containing metalloprotease. the metalloprotease does not hemagglutinate chicken or sheep erythrocytes. twenty-three to 27 of the first 42 n-terminal amino acid residues of the metalloprotease are identical to proteases produced by serratia proteamaculans, pectobacterium carotovorum, and anabaena sp. pcr analysis using primers designed  from a consensus nucleotide sequence showed that 135 e. sakazakii strains possessed the metalloprotease gene, zpx, and 25 non-e. sakazakii strains did not. the cloned zpx gene of strain 29544 consists of 1,026 nucleotides, and the deduced amino acid sequence of the metalloprotease has 341 amino acid residues, which corresponds to a theoretical protein size of 37,782 with a theoretical pi of 5.23. the sequence possesses three well-characterized zinc-binding and active-site motifs present in other bacterial zinc metalloproteases.
TIHT== 
ABHT== 

