@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 21969898
TI  == the disinfecting potential of contact lens soutions used by sultan qaboos university students.
AB  == objectives: this study aimed to determine the disinfecting potential of some contact lens solutions used by some university students in oman. methods: this work was carried out from january to june 2010 in the department of microbiology  & immunology, college of medicine and health sciences, sultan qaboos university,  oman. fifty disinfecting solutions, in which contact lenses were disinfected according to the manufacturers' instructions, were collected from the students and plated on various microbiological culture media. bacterial isolates were identified by api-20e, api-20ne and phoenix automated systems while fungi were identified by their cultural characteristics and biochemistry. results: from 98 isolates, pseudomonas aeruginosa was 23.5%; penicillium, 13%; candida species, 9.2%; coagulase negative staphylococci, 9.2%; serratia marcescens, 6.1%; bacillus, 5.1%; aspergillus flavus, 5.1%; serratia liquefaciens, pseudomonas fluorescens, enterobacter cloacae and aspergillus niger, 4.1% each; chryseomonas  luteola and chryseomonas indologenes, 3.1% each; stenotrophomonas maltophilia, serratia odorifera, 2.0% each; enterobacter aerogenes and klebsiella pneumoniae,  1% each. most isolates (65%) came from polyhexanide containing solutions. conclusion: contact lens disinfecting solutions with the same formulations, but manufactured by different companies, possessed different disinfecting potentials.
TIHT== 
ABHT== 

PMID== 8850133
TI  == [utility of pyrrolidonyl-arylamidase detection for typing enterobacteriaceae and  non-fermenting gram-negative bacteria].
AB  == detection of pyrrolidonyl-aryl-amidase activity (pyr) is an important tool to identify gram-positive cocci, such as staphylococci, enterococci, streptococci, and other related genera. however, only few studies evaluating its usefulness with gram-negative rods have been published. thus, a prospective study including  542 and 215 unique clinical isolates of enterobacteriaceae and non-fermentative gram-negative rods, respectively, was undertaken. strains were identified by conventional methods. pyr test was performed using a commercial kit, according to the manufacturer recommendations. positive results were uniformly obtained for the pyr test with the following species: citrobacter spp, klebsiella spp, enterobacter aerogenes, enterobacter agglomerans group, serratia marcescens and s. odorifera. on the other hand, negative results were uniformly displayed by e.  coli (including inactive e. coli), protease group, salmonellia spp, shigella spp, acinetobacter spp, burkholderia (pseudomonas) cepacia and flavobacterium spp. variable results were shown in pseudomonas aeruginosa, stenotrophomonas (xanthomonas) malthophilia, kluyvera cryocrescens, and enterobacter cloacae. pyr  test proved to be a reliable and simple tool to rapidly distinguish certain species belonging to enterobacteriaceae (ie. citrobacter freundii from salmonella spp, and inactive e. coli from k. ozaenae). further studies, including a wide diversity of species, are required to assess usefulness of the pyr test for the identification of non-fermentative gram-negative rods.
TIHT== 
ABHT== 

PMID== 8027345
TI  == evaluation of rapid one system for identification of 379 strains in the family enterobacteriaceae and oxidase-negative, gram-negative nonfermenters.
AB  == the ability of the rapid one system (innovative diagnostic systems, inc., norcross, ga.) to identify 364 strains in the family enterobacteriaceae and 15 oxidase-negative, gram-negative, nonfermentative rods was evaluated. kits were inoculated with no. 2 mcfarland standard suspensions, and reactions were interpreted after 4 h of incubation at 35 degrees c. overall, the method correctly identified (to the species level or to the genus level for salmonellas  and non-shigella sonnei shigella species) 363 strains (95.8%) without additional  tests. for four strains (1.0%), additional tests were required to delineate the correct identification from a range of two or more possibilities; these included  one serratia liquefaciens (serratia marcescens or serratia liquefaciens), one serratia rubidaea (serratia rubidaea or serratia odorifera), one salmonella typhi (leminorella richardii or salmonella sp.) and one yersinia enterocolitica (yersinia frederiksenii, yersinia intermedia, or yersinia enterocolitica). twelve strains (3.2%) were misidentified or yielded codes with no identification; these  comprised one citrobacter amalonaticus (no identification), three enterobacter hormaechei (not in the rapid one database; two enterobacter amnigenus, one enterobacter sp.), one serratia liquefaciens (enterobacter cloacae), one serratia rubidaea (no identification), four serratia fonticola (not in rapid one database; two enterobacter aerogenes, one serratia marcescens, one not identified), one proteus mirabilis (proteus penneri), and one proteus vulgaris (providencia rustigianii). if the seven strains not included in the database had been excluded, correct identification rates would have risen to 97.6% without additional tests and 98.7% with additional tests, with misidentification rates dropping to 1.3%. the rapid one system is easy to set up and the results are easy to read, and the system provides an accurate, nonautomated commercially available method for the same-day identification of members of the family enterobacteriaceae and oxidase-negative, gram-negative nonfermenters.
TIHT== 
ABHT== 

PMID== 6104464
TI  == [interest of gamma-glutamyltransferase in "enterobacteriaceae" (author's transl)].
AB  == gamma-glutamyltransferase (gammagt) could be detected in 86,6% of 3,027 strains of enterobacteriaceae, by the use of gamma-l-glutamin-p-nitranilide acid for substrate. the following species produced gamma gt: citrobacter freundii, levinea malonatica, l. amalonatica, klebsiella pneumoniae, k. oxytoca, k. ozaenae, enterobacter aerogenes, e. cloacae, e. agglomerans, e. gergoviae, k. ozaenae, enterobacter aerogenes, e. cloacae, e. agglomerans, e. gergoviae, hafnia alvei, erwinia carotovora, serratia marcescens, s. liquefaciens, s. plymuthica, s. marinorubra, s. odorifera, s. ficaria, proteus vulgaris, p. mirabilis, p. morganii, p. rettgeri, providencia alcalifaciens, p. stuartii, yersinia enterocolitica and y. pseudotuberculosis. most strains of escherichia coli and alkalescens dispar group are gamma gt+. the following species did not produce gammagt: shigella sonnei, edwardsiella tarda, klebsiella rhinoscleromatis and yersinia pestis. within the salmonella, most strains of subgenus i, ii and iv, and diphasic strains of subgenus iii (s. arizonae) produced gamma gt, whereas monophasic strains of subgenus iii did not produce gammagt. salmonella enteritidis (gammagt+) and s. dublin (gammagt-) can readily be distinguished. this test (gammagt) could also serve as a biochemical marker for s. typhi-murium  strains. shigella dysenteriae serotypes 3 to 9 were gammagt+ whereas other serotypes were gammagt-. within s. flexneri serotype 6, varieties boyd 88 and newcastle were found gammagt+; and varieties sussex and manchester were gammagt-. the use of gammagt test as an epidemiological marker for other shigella serotypes is suggested.
TIHT== 
ABHT== 

