@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25666178
TI  == purification and identification of an antibacterial protein from the symbiotic bacteria associated with novel entomopathogenic nematode, rhabditis (oscheius) sp.
AB  == entomopathogenic nematodes (epn) belonging to the families steinernematidae and heterorhabditidae and their symbiotic bacteria xenorhabdus and photorhabdus are well-known as biological control agents and are found to produce a wide range of  bioactive secondary metabolites. studies carried out at the central tuber crops research institute (ctcri) on entomopathogenic nematodes resulted in the identification of novel epn belonging to the family rhabditidae. this study reports the purification of a high molecular weight antibacterial protein from culture filtrates of a bacterium (bacillus cereus) symbiotically associated with  a novel entomopathogenic nematode rhabditis (oscheius) species, maintained at ctcri laboratory. fermentation conditions were standardized and optimum antibacterial activity was observed in tryptic soy broth after 48 h incubation at 30 degrees c. the aqueous extracts yielded antibacterial proteins which were purified by ammonium sulfate precipitation followed by ion exchange chromatography and size exclusion chromatography. native gel electrophoresis indicated an active protein of molecular mass 220kda which resolved into a major  band of 90 kda and a minor band of about 40 kda on sds-page. the 90 kda protein showed antibacterial activity and was further analysed by maldi tof-ms/ms. the protein was identified as a tqxa (threonine-glutamine dipeptide) domain containing protein from bacillus cereus. the protein was found to be active against bacillus subtilis mtcc2756, staphylococus aureus mtcc902 and escherichia  coli mtcc 2622 and was thermally stable.
TIHT== 
ABHT== 

PMID== 25539914
TI  == a new recombineering system for photorhabdus and xenorhabdus.
AB  == precise and fluent genetic manipulation is still limited to only a few prokaryotes. ideally the highly advanced technologies available in escherichia coli could be broadly applied. our efforts to apply lambda red technology, widely termed 'recombineering', in photorhabdus and xenorhabdus yielded only limited success. consequently we explored the properties of an endogenous photorhabdus luminescens lambda red-like operon, plu2934/plu2935/plu2936. bioinformatic and functional tests indicate that plu2936 is a 5'-3' exonuclease equivalent to redalpha and plu2935 is a single strand annealing protein equivalent to redbeta.  plu2934 dramatically enhanced recombineering efficiency. results from bioinformatic analysis and recombineering assays suggest that plu2934 may be functionally equivalent to redgamma, which inhibits the major endogenous e. coli  nuclease, recbcd. the recombineering utility of plu2934/plu2935/plu2936 was demonstrated by engineering photorhabdus and xenorhabdus genomes, including the activation of the 49-kb non-ribosomal peptide synthase (nrps) gene cluster plu2670 by insertion of a tetracycline inducible promoter. after tetracycline induction, novel secondary metabolites were identified. our work unlocks the potential for bioprospecting and functional genomics in the photorhabdus, xenorhabdus and related genomes.
TIHT== 
ABHT== 

PMID== 25538952
TI  == expression, purification, and functional analysis of novel rele operon from x. nematophila.
AB  == bacterial toxin-antitoxin (ta) complexes induce programmed cell death and also function to relieve cell from stress by various response mechanisms. escherichia  coli relb-rele ta complex consists of a rele toxin functionally counteracted by relb antitoxin. in the present study, a novel homolog of rele toxin designated as xn-rele toxin from xenorhabdus nematophila possessing its own antitoxin designated as xn-releat has been identified. expression and purification of recombinant proteins under native conditions with gst and ni-nta chromatography prove the existence of novel ta module. the expression of recombinant xn-rele under tightly regulated ara promoter in e. coli top 10 cells confirms its toxic nature in endogenous toxicity assay. the neutralization activity in endogenous toxicity assay by xn-releat antitoxin confirms its antidote nature when studying  the whole ta operon under ara regulated promoter. this study promotes newly discovered ta module to be regarded as important as other proteins of type ii toxin-antitoxin system.
TIHT== 
ABHT== 

PMID== 24816640
TI  == yeast homologous recombination cloning leading to the novel peptides ambactin and xenolindicin.
AB  == heterologous production of gamexpeptide a (1), as well as of the novel peptide natural products ambactin (2) and xenolindicins a-c (3 a-c), was achieved by using the "overlap extension pcr-yeast homologous recombination" (exrec) method.  exrec cloning is based on the ability of yeast to assemble overlapping dna fragments into functional plasmids. here we used this technique to clone a total  of 15 biosynthesis gene clusters from photorhabdus and xenorhabdus with sizes of  up to 45 kb. the structures of the novel compounds 2 and 3 a, which were produced in escherichia coli, were elucidated by detailed ms and bioinformatics analysis,  and additionally confirmed by their chemical synthesis.
TIHT== 
ABHT== 

PMID== 24673206
TI  == antiparasitic chaiyaphumines from entomopathogenic xenorhabdus sp. pb61.4.
AB  == a new class of four depsipentapeptides called chaiyaphumines a-d (1-4) was isolated from xenorhabdus sp. pb61.4. their structures were elucidated by detailed 1d and 2d nmr experiments and by a marfey's analysis following flash hydrolysis of the peptide. verification of the structure was achieved by three-dimensional modeling using noe-derived distance constraints, molecular dynamics, and energy minimization. chaiyaphumine a (1) showed good activity against plasmodium falciparum (ic50 of 0.61 mum), the causative agent of malaria, and was active against other protozoal tropical disease causing agents.
TIHT== 
ABHT== 

PMID== 24616055
TI  == rapid determination of the amino acid configuration of xenotetrapeptide.
AB  == an e. coli strain with deletions in five transaminases (deltaaspc deltailve deltatyrb deltaavta deltaybfq) was constructed to be unable to degrade several amino acids. this strain was used as an expression host for the analysis of the amino acid configuration of nonribosomally synthesized peptides, including the novel peptide "xenotetrapeptide" from xenorhabdus nematophila, by using a combination of labeling experiments and mass spectrometry. additionally, the number of d-amino acids in the produced peptide was assigned following simple cultivation of the expression strain in d2 o.
TIHT== 
ABHT== 

PMID== 24098116
TI  == the role of tcdb and tccc subunits in secretion of the photorhabdus tcd toxin complex.
AB  == the toxin complex (tc) is a large multi-subunit toxin encoded by a range of bacterial pathogens. the best-characterized examples are from the insect pathogens photorhabdus, xenorhabdus and yersinia. they consist of three large protein subunits, designated a, b and c that assemble in a 5ratio1ratio1 stoichiometry. oral toxicity to a range of insects means that some have the potential to be developed as pest control technology. the three subunit proteins  do not encode any recognisable export sequences and as such little progress has been made in understanding their secretion. we have developed heterologous tc production and secretion models in e. coli and used them to ascribe functions to  different domains of the crucial b+c sub-complex. we have determined that the b and c subunits use a secretion mechanism that is either encoded by the proteins themselves or employ an as yet undefined system common to laboratory strains of e. coli. we demonstrate that both the n-terminal domains of the b and c subunits  are required for secretion of the whole complex. we propose a model whereby the n-terminus of the c-subunit toxin exports the b+c sub-complex across the inner membrane while that of the b-subunit allows passage across the outer membrane. we also demonstrate that even in the absence of the b-subunit, that the c-subunit can also facilitate secretion of the larger a-subunit. the recognition of this novel export system is likely to be of importance to future protein secretion studies. finally, the identification of homologues of b and c subunits in diverse bacterial pathogens, including burkholderia and pseudomonas, suggests that these  toxins are likely to be important in a range of different hosts, including man.
TIHT== 
ABHT== 

PMID== 24002058
TI  == yaxab, a yersinia enterocolitica pore-forming toxin regulated by rova.
AB  == the transcriptional regulator rova positively regulates transcription of the yersinia enterocolitica virulence gene inv. invasin, encoded by inv, is important for establishment of y. enterocolitica infection. however, a rova mutant is more  attenuated for virulence than an inv mutant, implying that rova regulates additional virulence genes. when the y. enterocolitica rova regulon was defined by microarray analysis, ye1984 and ye1985 were among the genes identified as being upregulated by rova. since these genes are homologous to xenorhabdus nematophila cytotoxin genes xaxa and xaxb, we named them yaxa and yaxb, respectively. in this work, we demonstrate the effects of yaxab on the course of  infection in the murine model. while a yaxab mutant (deltayaxab) is capable of colonizing mice at the same level as the wild type, it slightly delays the course of infection and results in differing pathology in the spleen. further, we found  that yaxab encode a probable cytotoxin capable of lysing mammalian cells, that both yaxa and yaxb are required for cytotoxic activity, and that the two proteins associate. yaxab-mediated cell death occurs via osmotic lysis through the formation of distinct membrane pores. in silico tertiary structural analysis identified predicted structural homology between yaxa and proteins in pore-forming toxin complexes from bacillus cereus (hbl-b) and escherichia coli (hlye). thus, it appears that yaxab function as virulence factors by inducing cell lysis through the formation of pores in the host cell membrane. this characterization of yaxab supports the hypothesis that rova regulates expression  of multiple virulence factors in y. enterocolitica.
TIHT== 
ABHT== 

PMID== 23716638
TI  == computational analysis of bacterial rna-seq data.
AB  == recent advances in high-throughput rna sequencing (rna-seq) have enabled tremendous leaps forward in our understanding of bacterial transcriptomes. however, computational methods for analysis of bacterial transcriptome data have  not kept pace with the large and growing data sets generated by rna-seq technology. here, we present new algorithms, specific to bacterial gene structures and transcriptomes, for analysis of rna-seq data. the algorithms are implemented in an open source software system called rockhopper that supports various stages of bacterial rna-seq data analysis, including aligning sequencing  reads to a genome, constructing transcriptome maps, quantifying transcript abundance, testing for differential gene expression, determining operon structures and visualizing results. we demonstrate the performance of rockhopper  using 2.1 billion sequenced reads from 75 rna-seq experiments conducted with escherichia coli, neisseria gonorrhoeae, salmonella enterica, streptococcus pyogenes and xenorhabdus nematophila. we find that the transcriptome maps generated by our algorithms are highly accurate when compared with focused experimental data from e. coli and n. gonorrhoeae, and we validate our system's ability to identify novel small rnas, operons and transcription start sites. our  results suggest that rockhopper can be used for efficient and accurate analysis of bacterial rna-seq data, and that it can aid with elucidation of bacterial transcriptomes.
TIHT== 
ABHT== 

PMID== 23227808
TI  == role of d535 and h538 in endogenous toxicity of xenocin from xenorhabdus nematophila.
AB  == bacteriocins are the toxic proteins produced by bacteria under stress condition to inhibit the growth of closely related bacterial strain(s). in our earlier study, purified recombinant xenocin-immunity protein complex from xenorhabdus nematophila showed detrimental effect on six different insect gut residing bacteria. in this study, endogenous toxicity assay with xcina and its catalytic domain under tightly regulated ara promoter was performed. multiple sequence alignment and homology modelling revealed six conserved amino acid residues in the catalytic domain of xenocin. site-directed mutagenesis was performed in all the conserved residues, followed growth profile analysis of all the mutants by endogenous toxicity assay. among the six different conserved sites in catalytic domain of xenocin, we have identified one position where mutation resulted in no  measurable reduction in the endogenous toxicity (k564), three positions with measurable reduction in the endogenous toxicity (e542, h551 and r570) and two positions where mutation caused a significant reduction in the toxicity (d535 and h538). endogenous toxicity assay is validated by in vitro rna degradation assay.  structural integrity of purified recombinant proteins was confirmed through circular dichroism and fluorescence spectroscopy. our results indicate that d535  and h538 act as the acid-base pair for rna hydrolysis.
TIHT== 
ABHT== 

PMID== 23117838
TI  == visualizing bacteria in nematodes using fluorescent microscopy.
AB  == symbioses, the living together of two or more organisms, are widespread throughout all kingdoms of life. as two of the most ubiquitous organisms on earth, nematodes and bacteria form a wide array of symbiotic associations that range from beneficial to pathogenic (1-3). one such association is the mutually beneficial relationship between xenorhabdus bacteria and steinernema nematodes, which has emerged as a model system of symbiosis (4). steinernema nematodes are entomopathogenic, using their bacterial symbiont to kill insects (5). for transmission between insect hosts, the bacteria colonize the intestine of the nematode's infective juvenile stage (6-8). recently, several other nematode species have been shown to utilize bacteria to kill insects (9-13), and investigations have begun examining the interactions between the nematodes and bacteria in these systems (9). we describe a method for visualization of a bacterial symbiont within or on a nematode host, taking advantage of the optical  transparency of nematodes when viewed by microscopy. the bacteria are engineered  to express a fluorescent protein, allowing their visualization by fluorescence microscopy. many plasmids are available that carry genes encoding proteins that fluoresce at different wavelengths (i.e. green or red), and conjugation of plasmids from a donor escherichia coli strain into a recipient bacterial symbiont is successful for a broad range of bacteria. the methods described were developed to investigate the association between steinernema carpocapsae and xenorhabdus nematophila (14). similar methods have been used to investigate other nematode-bacterium associations (9) (,) (15-18)and the approach therefore is generally applicable. the method allows characterization of bacterial presence and localization within nematodes at different stages of development, providing insights into the nature of the association and the process of colonization (14)  (,) (16) (,) (19). microscopic analysis reveals both colonization frequency within a population and localization of bacteria to host tissues (14) (,) (16) (,) (19-21). this is an advantage over other methods of monitoring bacteria within nematode populations, such as sonication (22)or grinding (23), which can provide average levels of colonization, but may not, for example, discriminate populations with a high frequency of low symbiont loads from populations with a low frequency of high symbiont loads. discriminating the frequency and load of colonizing bacteria can be especially important when screening or characterizing  bacterial mutants for colonization phenotypes (21) (,) (24). indeed, fluorescence microscopy has been used in high throughput screening of bacterial mutants for defects in colonization (17) (,) (18), and is less laborious than other methods,  including sonication (22) (,) (25-27)and individual nematode dissection (28) (,)  (29).
TIHT== 
ABHT== 

PMID== 23115973
TI  == [an idp16 protein from xenorhabdus bovienii depresses the immune response in galleria mellonella].
AB  == objective: a protein with insect immunodepressive activity was purified from xenorhabdus bovienii, a bacterial symbiosis of entomopathogenic nematode. to determine the function of this protein in the pathogenesis of bacterium-nematode  symbiosis, we detected the effect of this protein on immune response in galleria  mellonella. methods: proteins from extracellular extact of x. bovienii were purified using ammonium sulfate precipitation, hitrap q hp chromatography, hitrap butyl ff chromatography, and hitrap sp hp chromatography. intra-hemocoel injection assay followed by observation of hemolymph melanization was used for activity determination. fluorescent microspheres and sepharose beads were used to assess the effect of purified protein on phagocytosis and encapsulation of hemocytes, respectively. the purified protein was identified by 2-d and ms anlysis. the full-length encoding gene was cloned by pcr, and expressed with pet  30a in escherichia coli. the recombinant protein was purified by ni-nta affinity  chromatography. results: an immunodepressive protein was purified and designed as idp16, which can inhibit the phenoloxidase activity, and weaken the phagocytosis  and encapsulation of galleria mellonella hemocytes. the encoding gene was then cloned and expressed in e. coli. the recombinant protein was also determined to be immunodepressive. conclusion: the idp16 protein from xenorhabdus bovienii can  depress the immune response in insect, which may play an important role in bacteria-host interaction.
TIHT== 
ABHT== 

PMID== 22750626
TI  == steinernema glaseri surface enolase: molecular cloning, biological characterization, and role in host immune suppression.
AB  == entomopathogenic nematodes are widely used as biological control agents that can  suppress or evade the host immune defense upon entry into insects. the surface coat of steinernema glaseri has been shown to play important roles in defeating the host immune system. in this work, a protein fraction with antiphagocytic activity was separated by electro-elution and further analyzed by two-dimensional electrophoresis (2-de). lc-ms/ms analysis of one protein spot from a 2-de gel gave five peptides that were highly similar to enolases of many organisms. a 1311 bp cdna was cloned that encodes a 47 kda protein with high sequence identity to enolases from different species of nematodes. the deduced protein, sg-enol, was expressed in escherichia coli, and its glycolytic activity was demonstrated by the conversion of 2-phospho-d-glycerate to phosphoenolpyruvate. recombinant sg-enol significantly reduced the lt(50)s of xenorhabdus poinarii and metarhizium anisopliae when co-injected into galleria mellonella and locusta migratoria manilensis meyen, respectively. using immuno-gold transmission electron microscopy, native sg-enol was confirmed to be localized to both the nematode cuticle and the surface coat. in vitro, secretion of sg-enol was inducible rather than constitutive. in vivo, sg-enol was detected in the host hemolymph after infection of g. mellonella with s. glaseri, indicating that sg-enol was secreted  into the insect hemocoel and was involved in infection. this is the first report  of the cloning and characterization of a surface coat protein in an entomopathogenic nematode. our findings provide clear evidence for an important role for a cell surface enolase in s. glaseri infection and host immune suppression.
TIHT== 
ABHT== 

PMID== 22711807
TI  == small molecule perimeter defense in entomopathogenic bacteria.
AB  == two gram-negative insect pathogens, xenorhabdus nematophila and photorhabdus luminescens, produce rhabduscin, an amidoglycosyl- and vinyl-isonitrile-functionalized tyrosine derivative. heterologous expression of the rhabduscin pathway in escherichia coli, precursor-directed biosynthesis of rhabduscin analogs, biochemical assays, and visualization using both stimulated raman scattering and confocal fluorescence microscopy established rhabduscin's role as a potent nanomolar-level inhibitor of phenoloxidase, a key component of the insect's innate immune system, as well as rhabduscin's localization at the bacterial cell surface. stimulated raman scattering microscopy visualized rhabduscin at the periphery of wild-type x. nematophila cells and e. coli cells heterologously expressing the rhabduscin pathway. precursor-directed biosynthesis created rhabduscin mimics in x. nematophila pathway mutants that could be accessed at the bacterial cell surface by an extracellular bioorthogonal probe, as judged by confocal fluorescence microscopy. biochemical assays using both wild-type and mutant x. nematophila cells showed that rhabduscin was necessary and sufficient for potent inhibition (low nm) of phenoloxidases, the enzymes responsible for producing melanin (the hard black polymer insects generate to seal off microbial pathogens). these observations suggest a model in which rhabduscin's physical association at the bacterial cell surface provides a highly effective inhibitor concentration directly at the site of phenoloxidase contact.  this class of molecules is not limited to insect pathogens, as the human pathogen vibrio cholerae also encodes rhabduscin's aglycone, and bacterial cell-coated immunosuppressants could be a general strategy to combat host defenses.
TIHT== 
ABHT== 

PMID== 22615559
TI  == pdl1 is a putative lipase that enhances photorhabdus toxin complex secretion.
AB  == the toxin complex (tc) is a large multi-subunit toxin first characterized in the  insect pathogens photorhabdus and xenorhabdus, but now seen in a range of pathogens, including those of humans. these complexes comprise three protein subunits, a, b and c which in the xenorhabdus toxin are found in a 4:1:1 stoichiometry. some tcs have been demonstrated to exhibit oral toxicity to insects and have the potential to be developed as a pest control technology. the  lack of recognisable signal sequences in the three large component proteins hinders an understanding of their mode of secretion. nevertheless, we have shown  the photorhabdus luminescens (pl) tcd complex has been shown to associate with the bacteria's surface, although some strains can also release it into the surrounding milieu. the large number of tc gene homologues in pl make study of the export process difficult and as such we have developed and validated a heterologous escherichia coli expression model to study the release of these important toxins. in addition to this model, we have used comparative genomics between a strain that releases high levels of tcd into the supernatant and one that retains the toxin on its surface, to identify a protein responsible for enhancing secretion and release of these toxins. this protein is a putative lipase (pdl1) which is regulated by a small tightly linked antagonist protein (orf53). the identification of homologues of these in other bacteria, linked to other virulence factor operons, such as type vi secretion systems, suggests that  these genes represent a general and widespread mechanism for enhancing toxin release in gram negative pathogens.
TIHT== 
ABHT== 

PMID== 22465768
TI  == characterization of xenorhabdus and photorhabdus bacteria by fourier transform mid-infrared spectroscopy with attenuated total reflection (ft-ir/atr).
AB  == the use of fourier transform mid-infrared spectroscopy with attenuated total reflection for characterizing entomopathogenic bacteria from genera xenorhabdus and photorhabdus is evaluated for the first time. the resulting spectra of xenorhabdus poinarii and photorhabdus luminiscens were compared with the spectrum of escherichia coli samples. the absorption spectra generated by the bacteria samples, were very different at the region below 1400cm(-1) which represents the  stretching vibrations of phosphate and carbohydrates. star diagrams of the fingerprint section of nematodes spectra (between 1,350 and 1,650 cm(-1)) for separation between spectra was used and showed to be a useful tool for classification purposes.
TIHT== 
ABHT== 

PMID== 22446508
TI  == scavenger deterrent factor (sdf) from symbiotic bacteria of entomopathogenic nematodes.
AB  == entomopathogenic nematodes (epns) in the genera steinernema and heterorhabditis are symbiotically associated with bacteria in the genera xenorhabdus and photorhabdus, respectively. the symbiotic bacteria produce a chemical compound(s) that deterred ants from feeding on nematode-killed insects (i.e., cadavers) and has been previously referred to as an ant deterrent factor (adf). we studied the  response of different arthropod scavenger species which included the ant lepisiota frauenfeldi, cricket gryllus bimaculatus, wasps vespa orientalis and paravespula sp., and calliphorid fly chrysomya albiceps, to adf. these scavengers (ants, crickets, and wasps) were exposed to cadavers with and without the nematode/bacterium complex or to photorhabdus luminescens cultures of different ages on different substrates. the ant, cricket, and wasp species did not feed on  nematode-killed insects containing the nematode/bacterium complex that were 2 days old and older but fed on 1-day-old nematode-killed and freeze -killed insects. crickets consumed 2- to 7-day-old axenic nematode-killed insects, 1-, 4-, and 5-day-old insects killed by the bacterium, serratia marcescens, and freeze-killed, putrid insects that were up to 10 days old. the crickets only partially consumed 2- and 3-day-old insects killed by s. marcescens which differed significantly from the 1-, 4-, and 5-day-old killed insects by this bacterium. ants fed only on 5% sucrose solution (control) and 1- to 3- day old cultures of p. luminescens containing 5% sucrose but not on older cultures of p.  luminescens. wasps did not feed on meat treated with p. luminescens supernatant,  whereas they fed on meat treated with escherichia coli supernatant and control meat. calliphorid flies did not oviposit on meat treated with p. luminescens supernatant but did oviposit on untreated meat. based on the response of these scavengers, the chemical compound(s) responsible for this deterrent activity should be called "scavenger deterrent factor" (sdf).
TIHT== 
ABHT== 

PMID== 22352834
TI  == proteomic identification of a novel toxin protein (txp40) from xenorhabdus nematophila and its insecticidal activity against larvae of plutella xylostella.
AB  == for the identification of a novel insecticidal protein, a two-dimensional liquid  chromatography (pf-2d) system was used in a quantitative proteomic analysis of xenorhabdus nematophila cbnu strain isolated from entomophagous nematode steinernema carpocapsae . protein patterns obtained from minimum and maximum insecticidal activities during cultivation were contrasted, and a novel toxin protein (txp40) was identified by maldi-tof/ms. the dna sequence of the cloned toxin gene (1089 bp) has an open reading frame encoding 363 amino acids with a predicted molecular mass of 41162 da. the txp40 identified in this study is most  closely related to the known txp40 cloned from x. nematophila eb (adq92844) with  94.4% identical sequence residues. following the expression of the newly identified toxin gene in escherichia coli , the insecticidal activity of the recombinant toxin protein was determined against plutella xylostella larvae; a 56.7% mortality rate was observed within 24 h.
TIHT== 
ABHT== 

PMID== 21239661
TI  == horse species symposium: a novel approach to monitoring pathogen progression during uterine and placental infection in the mare using bioluminescence imaging  technology and lux-modified bacteria.
AB  == uterine and placental infections are the leading cause of abortion, stillbirth, and preterm delivery in the mare. whereas uterine and placental infections in women have been studied extensively, a comprehensive examination of the pathogenic processes leading to this unsatisfactory pregnancy outcome in the mare has yet to be completed. most information in the literature relating to late-term pregnancy loss in mares is based on retrospective studies of clinical cases submitted for necropsy. here we report the development and application of a novel approach, whereby transgenically modified bacteria transformed with lux genes of  xenorhabdus luminescens or photorhabdus luminescens origin and biophotonic imaging are utilized to better understand pathogen-induced preterm birth in late-term pregnant mares. this technology uses highly sensitive bioluminescence imaging camera systems to localize and monitor pathogen progression during tissue invasion by measuring the bioluminescent signatures emitted by the lux-modified pathogens. this method has an important advantage in that it allows for the potential tracking of pathogens in vivo in real time and over time, which was hitherto impossible. although the application of this technology in domestic animals is in its infancy, investigators were successful in identifying the fetal lungs, sinuses, nares, urinary, and gastrointestinal systems as primary tissues for pathogen invasion after experimental infection of pregnant mares with lux-modified escherichia coli. it is important that pathogens were not detected in other vital organs, such as the liver, brain, and cardiac system. such precision in localizing sites of pathogen invasion provides potential application for this novel approach in the development of more targeted therapeutic interventions for pathogen-related diseases in the equine and other domestic species.
TIHT== 
ABHT== 

PMID== 20627393
TI  == imd pathway is involved in the interaction of drosophila melanogaster with the entomopathogenic bacteria, xenorhabdus nematophila and photorhabdus luminescens.
AB  == xenorhabdus nematophila/steinernema carpocapsae and photorhabdus luminescens/heterorhabditis bacteriophora are nemato-bacterial complexes highly pathogenic for insects. using a syringe as artificial vector, we have analyzed the effects of the two bacteria, x. nematophila and p. luminescens on the genetic tool insect, drosophila melanogaster. both bacteria were found to kill adult flies in a dose dependent manner with x. nematophila being the fastest. on the other hand, when an injection of non-pathogenic bacteria, escherichia coli, is performed 1 day before challenge with the entomopathogenic bacteria, then the survival of drosophila flies was prolonged by at least 20h. after injection of entomopathogenic bacteria, drosophila mutant dif(1), affected on the toll pathway, showed a similar phenotype than wild-type flies whereas drosophila mutant dredd(d55), affected on the imd pathway, was not protected by a prior injection of e. coli. this suggested that members of the imd pathway might be targets of these entomopathogenic bacteria albeit synthesis of antimicrobial peptides through this signaling pathway was induced by x. nematophila as well as  p. luminescens. finally, p. luminescens phop mutant, an avirulent mutant in the lepidopteran insect, spodoptera littoralis, was found poorly virulent for d. melanogaster. phop mutant partially protected d. melanogaster flies if injected 1 day before the injection of p. luminescens wild-type tt01 to the same extent than the e. coli-induced protection. however, phop recovered a level of pathogenicity  comparable to p. luminescens wild-type tt01 when injected to drosophila flies affected on the imd pathway.
TIHT== 
ABHT== 

PMID== 18375563
TI  == transcriptional analysis and functional characterization of a gene pair encoding  iron-regulated xenocin and immunity proteins of xenorhabdus nematophila.
AB  == we describe a two-gene cluster encoding a bacteriocin, xenocin, and the cognate immunity protein in the insect-pathogenic bacterium xenorhabdus nematophila, which infects and kills larval stages of the common crop pest helicoverpa armigera. the two genes, xcina and ximb, are present in the genome as a single transcriptional unit, which is regulated under sos conditions. the stress-inducible promoter was activated by mitomycin c, glucose, and fe(3+) depletion and at an elevated temperature when it was tested in escherichia coli cells. expression of the xenocin protein alone in e. coli inhibited the growth of this organism. the growth inhibition was abolished when the immunity protein was  also present. a recombinant xenocin-immunity protein complex inhibited the growth of e. coli indicator cells when it was added exogenously to a growing culture. xenocin is an endoribonuclease with an enzymatically active c-terminal domain. six resident bacterial species (i.e., bacillus, enterobacter, enterococcus, citrobacter, serratia, and stenotrophomonas species) from the h. armigera gut exhibited sensitivity to recombinant xenocin when the organisms were grown under  iron-depleted conditions and at a high temperature. xenocin also inhibited the growth of two xenorhabdus isolates. this study demonstrates that fe(3+) depletion acts as a common cue for synthesis of xenocin by x. nematophila and sensitization of the target strains to the bacteriocin.
TIHT== 
ABHT== 

PMID== 17976177
TI  == xenorhabdus antibiotics: a comparative analysis and potential utility for controlling mastitis caused by bacteria.
AB  == aims: the role of antibiotics produced by bacterial symbionts of entomopathogenic nematodes is to suppress growth of microbes in the soil environment. these antibiotics are active against gram-positive and gram-negative bacteria, and were tested against mastitis isolates from dairy cows. methods and results: two bioassays were adapted for xenorhabdus antibiotics; an overlay method on agar plates, and serially diluted, cell-free, xenorhabdus cultures. the antimicrobial  activities of the liquid cultures of 13 strains from five xenorhabdus species were further evaluated. antimicrobial activities of the type strains of x. nematophila, x. budapestensis and x. szentirmaii were tested on mastitis isolates of staphylococcus aureus, escherichia coli and klebsiella pneumoniae with both bioassays. a previously reported antibiotic from x. nematophila, nematophin, was  synthesized in three steps from tryptamine and 4-methyl-2-oxovaleric acid sodium  salt. conclusions: the antibiotics of all three xenorhabdus strains were powerful in either bioassay, but the sensitivity of the isolates differed from each other. while kl. pneumoniae was the least susceptible, staph. aureus had the highest sensitivity to each xenorhabdus strain. xenorhabdus szentirmaii and x. budapestensis were more potent antibiotic producers than x. nematophila, and raceme nematophin was ineffective against all mastitis isolates. significance and impact of the study: these results indicate that xenorhabdus antibiotics are effective against mastitis isolates and should be further evaluated for their potential in mastitis control or prevention.
TIHT== 
ABHT== 

PMID== 17951441
TI  == cpxra regulates mutualism and pathogenesis in xenorhabdus nematophila.
AB  == the cpxra signal transduction system, which in escherichia coli regulates surface structure assembly and envelope maintenance, is involved in the pathogenic and mutualistic interactions of the entomopathogenic bacterium xenorhabdus nematophila. when deltacpxr1 cells were injected into manduca sexta insects, the  time required to kill 50% of the insects was twofold longer than the time observed for wild-type cells and the deltacpxr1 cells ultimately killed 16% fewer insects than wild-type cells killed. during mutualistic colonization of steinernema carpocapsae nematodes, the deltacpxr1 mutant achieved colonization levels that were only 38% of the wild-type levels. deltacpxr1 cells exhibited an  extended lag phase when they were grown in liquid lb or hemolymph, formed irregular colonies on solid medium, and had a filamentous cell morphology. a mutant with a cpxrp-lacz fusion had peaks of expression in the log and stationary phases that were conversely influenced by cpxr; the deltacpxr1 mutant produced 130 and 17% of the wild-type beta-galactosidase activity in the log and stationary phases, respectively. cpxr positively influences motility and secreted lipase activity, as well as transcription of genes necessary for mutualistic colonization of nematodes. cpxr negatively influences the production of secreted  hemolysin, protease, and antibiotic activities, as well as the expression of mrxa, encoding the pilin subunit. thus, x. nematophila cpxra controls expression  of envelope-localized and secreted products, and its activity is necessary for both mutualistic and pathogenic functions.
TIHT== 
ABHT== 

PMID== 17266984
TI  == structural characterisation of the insecticidal toxin xpta1, reveals a 1.15 mda tetramer with a cage-like structure.
AB  == a recently identified class of proteins conferring insecticidal activity to several bacteria within the enterobacteriaceae family have potential for control  of commercially important insect pests. here, we report the first purification, biophysical characterisation and 3-d structural analysis of one of the toxin components, xpta1, from xenorhabdus nematophila pmfi296 to a resolution of 23 a.  membrane binding studies indicate that the three-component toxin system has a different mode of action from that of proteins from bacillus thuringiensis (bt).  biophysical characterisation of xpta1 suggests a mechanism of action of xpta1 whereby it first binds to the cell membrane forming a structure with a central cavity and forms a complex with its partners xptb1 and xptc1 producing the full insecticidal toxin. the structure of xpta1 is shown by a combination of electron  microscopy, ultracentrifugation and circular dichroism spectroscopy to be a 1.15  mda tetramer with a cage-like structure. each of the four symmetry-related subunits has three well-defined domains and a longitudinal twist with one end narrower than the other. one third of the residues of xpta1 are alpha-helical and it is suggested the subunits associate partly via an alpha-helical coiled-coil interaction. xpta1 itself shows the same secondary structure at neutral ph and in an alkaline environment up to ph10.5. this ph tolerance indicates that the folded xpta1 can pass through the midgut of lepidopteran insects susceptible to the insecticidal toxin complex. this implies therefore that its folded structure is important for its biological activity.
TIHT== 
ABHT== 

PMID== 17229739
TI  == the xaxab genes encoding a new apoptotic toxin from the insect pathogen xenorhabdus nematophila are present in plant and human pathogens.
AB  == xenorhabdus nematophila, a member of the enterobacteriaceae, kills many species of insects by strongly depressing the immune system and colonizing the entire body. a peptide cytotoxin has been purified from x. nematophila broth growth, and the cytolytic effect on insect immunocytes and hemolytic effect on mammalian red  blood cells of this toxin have been described (ribeiro, c., vignes, m., and brehelin, m. (2003) j. biol. chem. 278, 3030-3039). we show here that this toxin, xenorhabdus alpha-xenorhabdolysin (xax), triggers apoptosis in both insect and mammalian cells. we also report the cloning and sequencing of two genes, xaxab, encoding this toxin in x. nematophila. the expression of both genes in recombinant escherichia coli led to the production of active cytotoxin/hemolysin. however, hemolytic activity was observed only if the two peptides were added in the appropriate order. furthermore, we report here that inactivation of xaxab genes in x. nematophila abolished the major cytotoxic activity present in broth growth, called c1. we also show that these genes are present in various entomopathogenic bacteria of the genera xenorhabdus and photorhabdus, in pseudomonas entomophila, in the human pathogens yersinia enterocolitica and proteus mirabilis, and in the plant pathogen pseudomonas syringae. this toxin cannot be classified in any known family of cytotoxins on the basis of amino acid sequences, locus organization, and activity features. it is, therefore, probably  the prototype of a new family of binary toxins.
TIHT== 
ABHT== 

PMID== 16420626
TI  == nutritive significance of crystalline inclusion proteins of photorhabdus luminescens in steinernema nematodes.
AB  == phase i cells of photorhabdus luminescens produce two types of intracellular crystalline inclusion proteins designated cipa and cipb. the genes encoding cipa  and cipb proteins from p. luminescens h06 were expressed respectively in escherichia coli and these cells were used to feed the axenic first juveniles (j1) of three steinernema nematode isolates in liquid cultures and on agar plates. in liquid cultures, the axenic j1 juveniles of all three test steinernema nematode isolates were able to produce next dauer juveniles (djs) in the e. coli  cultures with at least one of the expressed cip proteins, but unable to develop beyond the next j1 stage without expressed cip proteins. for each target nematode isolate, addition of the supernatant of the bacterial culture of its xenorhabdus  symbiont to the tested liquid cultures did not induce the formation of djs. however, on lb agar plates with different test e. coli cultures, all j1 juveniles of the three steinernema strains finally developed into next djs. it seemed that  the metabolite pathway of the test bacteria in both culture systems was different. the presence of the cip proteins has a significant influence on the dj formation of the steinernema nematodes in liquid culture system.
TIHT== 
ABHT== 

PMID== 16204546
TI  == pyrimidine nucleoside salvage confers an advantage to xenorhabdus nematophila in  its host interactions.
AB  == xenorhabdus nematophila is a mutualist of entomopathogenic nematodes and a pathogen of insects. to begin to examine the role of pyrimidine salvage in nutrient exchange between x. nematophila and its hosts, we identified and mutated an x. nematophila tdk homologue. x. nematophila tdk mutant strains had reduced virulence toward manduca sexta insects and a competitive defect for nematode colonization in plate-based assays. provision of a wild-type tdk allele in trans  corrected the defects of the mutant strain. as in escherichia coli, x. nematophila tdk encodes a deoxythymidine kinase, which converts salvaged deoxythymidine and deoxyuridine nucleosides to their respective nucleotide forms. thus, nucleoside salvage may confer a competitive advantage to x. nematophila in  the nematode intestine and be important for normal entomopathogenicity.
TIHT== 
ABHT== 

PMID== 16042769
TI  == an encoded n-terminal extension results in low levels of heterologous protein production in escherichia coli.
AB  == background: the tdk gene (encoding deoxythymidine kinase) of the gamma-proteobacterium xenorhabdus nematophila has two potential translation start sites. the promoter-distal start site was predicted to be functional based on amino acid sequence alignment with closely related tdk proteins. however, to experimentally determine if either of the two possible start codons allows production of a functional tdk, we expressed the "long-form" (using the promoter-proximal start codon) and "short-form" (using the promoter-distal start  codon) x. nematophila tdk genes from the t7 promoter of the pet-28a(+) vector. we assessed tdk production and activity using a functional assay in an escherichia coli tdk mutant, which, since it lacks functional tdk, is able to grow in 5-fluorodeoxyuridine (fudr)-containing medium. results: short-form tdk complemented the e. coli tdk mutant strain, resulting in fudr sensitivity of the  strain. however, the e. coli tdk mutant expressing the long form of tdk remained  fudr resistant, indicating it did not have a functional deoxythymidine kinase enzyme. we report that long-form tdk is at least 13-fold less abundant than short-form tdk, the limited protein produced was as stable as short-form tdk and  the long-form transcript was 1.7-fold less abundant than short-form transcript. additionally, we report that the long-form extension was sufficient to decrease heterologous production of a different x. nematophila protein, nilc. conclusion:  we conclude that the difference in the fudr growth phenotype between the e. coli  tdk mutant carrying the long-or short-form x. nematophila tdk is due to a difference in tdk levels. the lower long-form protein level does not result from  protein instability, but instead from reduced transcript levels possibly combined with reduced translation efficiency. because the observed effect of the encoded n-terminal extension is not specific to tdk production and can be overcome with induction of gene expression, these results may have particular relevance to researchers attempting to limit production of toxic proteins under non-inducing conditions.
TIHT== 
ABHT== 

PMID== 15494228
TI  == enhancement of the multi-channel continuous monitoring system through the use of  xenorhabdus luminescens lux fusions.
AB  == the enhancement of the multi-channel continuous toxicity monitoring system developed previously was studied. to achieve better and more stable results from  the system, the use of thermo-lux fusion strains that express the luxcdabe genes  from xenorhabdus luminescens was evaluated. a total of six recombinant escherichia coli strains with the promoters from three oxidative-stress responsive genes, i.e. the katg, soda and pqi-5 genes, fused to either the lux genes from vibrio fischeri or x. luminescens were characterized and their responses to different chemicals compared. it was found that the basal level bioluminescence (bl) from the thermo-lux fusion strains was always higher while that of the v. fischeri lux strains were always near or below the lower limit of  detection of the system. for example, the katg::v. fischeri lux strain, dpd2511,  gave no discernible response due to its low level expression while a fusion of the katg promoter with the x. luminescens lux operon was clearly responsive and capable of detecting hydrogen peroxide down to about 1 ppm. the use of the thermo-lux strains found them to be as sensitive as the v. fischeri lux strains while providing a brighter, more stable basal level bioluminescence, making the analysis and monitoring of water-borne toxicity more reliable.
TIHT== 
ABHT== 

PMID== 15469517
TI  == characterization of a lipoprotein, nilc, required by xenorhabdus nematophila for  mutualism with its nematode host.
AB  == xenorhabdus nematophila is a gamma-proteobacterial mutualist of an insect-pathogenic nematode, steinernema carpocapsae. x. nematophila requires nilc, a gene predicted to encode an outer membrane lipoprotein of unknown function, for colonization of its nematode host. characterization of nilc, described here, demonstrated it is a 28 kda lipoprotein directed to the periplasm by an n-terminal signal sequence. lipidation and processing of nilc occurs by a mechanism that is conserved in proteobacteria. this work also showed nilc is membrane associated and oriented towards the periplasm of x. nematophila and is produced as an outer membrane-associated protein when expressed in escherichia coli. expression analyses revealed that nilc transcription is directly or indirectly repressed by lrp, and this regulatory link may explain the nematode mutualism defect of a previously identified lrp::tn5 mutant. an lrp::tn5 mutant produces an additional nilc transcript, not observed in wild-type cells growing in vitro, and produces approximately 75-fold more nilc than wild-type cells in late stationary phase. these fundamental characterizations of nilc expression and nilc localization and processing events have provided firm bases for understanding the role of this colonization factor in the x. nematophila/s. carpocapsae microbe-host interaction.
TIHT== 
ABHT== 

PMID== 15375127
TI  == insecticidal pilin subunit from the insect pathogen xenorhabdus nematophila.
AB  == xenorhabdus nematophila is an insect pathogen and produces protein toxins which kill the larval host. previously, we characterized an orally toxic, large, outer  membrane-associated protein complex from the culture medium of x. nematophila. here, we describe the cloning, expression, and characterization of a 17-kda pilin subunit of x. nematophila isolated from that protein complex. the gene was amplified by pcr, cloned, and expressed in escherichia coli. the recombinant protein was refolded in vitro in the absence of its cognate chaperone by using a  urea gradient. the protein oligomerized during in vitro refolding, forming multimers. point mutations in the conserved n-terminal residues of the pilin protein greatly destabilized its oligomeric organization, demonstrating the importance of the n terminus in refolding and oligomerization of the pilin subunit by donor strand complementation. the recombinant protein was cytotoxic to cultured helicoverpa armigera larval hemocytes, causing agglutination and subsequent release of the cytoplasmic enzyme lactate dehydrogenase. the agglutination of larval cells by the 17-kda protein was inhibited by several sugar derivatives. the biological activity of the purified recombinant protein indicated that it has a conformation similar to that of the native protein. the 17-kda pilin subunit was found to be orally toxic to fourth- or fifth-instar larvae of an important crop pest, h. armigera, causing extensive damage to the midgut epithelial membrane. to our knowledge, this is first report describing an  insecticidal pilin subunit of a bacterium.
TIHT== 
ABHT== 

PMID== 15345451
TI  == identification and functional characterization of a xenorhabdus nematophila oligopeptide permease.
AB  == the bacterium xenorhabdus nematophila is a mutualist of steinernema carpocapsae nematodes and a pathogen of insects. presently, it is not known what nutrients the bacterium uses to thrive in these host environments. in other symbiotic bacteria, oligopeptide permeases have been shown to be important in host interactions, and we therefore sought to determine if oligopeptide uptake is essential for growth or symbiotic functions of x. nematophila in laboratory or host environments. we identified an x. nematophila oligopeptide permease (opp) operon of two sequential oppa genes, predicted to encode oligopeptide-binding proteins, and putative permease-encoding genes oppb, oppc, oppd, and oppf. peptide-feeding studies indicated that this opp operon encodes a functional oligopeptide permease. we constructed strains with mutations in oppa(1), oppa(2), or oppb and examined the ability of each mutant strain to grow in a peptide-rich  laboratory medium and to interact with the two hosts. we found that the opp mutant strains had altered growth phenotypes in the laboratory medium and in hemolymph isolated from larval insects. however, the opp mutant strains were capable of initiating and maintaining both mutualistic and pathogenic host interactions. these data demonstrate that the opp genes allow x. nematophila to utilize peptides as a nutrient source but that this function is not essential for the existence of x. nematophila in either of its host niches. to our knowledge, this study represents the first experimental analysis of the role of oligopeptide transport in mediating a mutualistic invertebrate-bacterium interaction.
TIHT== 
ABHT== 

PMID== 15194482
TI  == cloning and heterologous expression of a novel insecticidal gene (tccc1) from xenorhabdus nematophilus strain.
AB  == we have identified and cloned a novel toxin gene (tccc1/xptb1) from xenorhabdus nematophilus strain isolated from korea-specific entomophagous nematode steinernema glaseri mk. the dna sequence of cloned toxin gene (3048 bp) has an open reading frame encoding 1016 amino acids with a predicted molecular mass of 111058 da. the toxin sequence shares 50-96% identical amino acid residues with the previously reported tccc1 cloned from x. nematophilus, photorhabdus luminescens w14 p. luminescens tto1, and yersinia pestis co92. the toxin gene was successfully expressed in escherichia coli, and the recombinant toxin protein caused a rapid cessation in mortality of galleria mellonella larvae (80% death of larvae within 2 days). conclusively, the heterologous expression of the novel gene tccc1 cloned into e. coli plasmid vector produced recombinant toxin with high insecticidal activity.
TIHT== 
ABHT== 

PMID== 15183278
TI  == an entomopathogenic bacterium, xenorhabdus nematophila, inhibits the expression of an antibacterial peptide, cecropin, of the beet armyworm, spodoptera exigua.
AB  == an entomopathogenic bacterium, xenorhabdus nematophila, is known to depress hemocyte nodule formation of target insects by inhibiting eicosanoid biosynthesis. this study analyzed the inhibitory effect of x. nematophila on the  humoral immunity of the target insects and tested its association with the host eicosanoid pathway. plasma collected from the fifth instar larvae of spodoptera exigua, when they were injected with x. nematophila, did not show antibacterial activity against escherichia coli by a growth inhibition zone assay. in comparison, heat-killed x. nematophila induced significant antibacterial activity in the plasma. the antibacterial humoral activity was further demonstrated by examining a specific potent antibacterial peptide, cecropin. two cecropin genes ('a' and 'b') were partially cloned from the fifth instar larvae of s. exigua by  conserved degenerate primers using nested reverse transcriptase-polymerase chain  reaction (rt-pcr). they showed high homologies with known cecropins from other lepidopteran species. northern analysis using the cecropin probe showed that the  injection of the heat-killed x. nematophila induced significant expression of a cecropin mrna transcript (approximately 1.1 kb), but the larvae injected with the live bacteria did not show the corresponding transcript. injection of arachidonic acid did not rescue the inhibition of x. nematophila based on either antibacterial activity or cecropin gene expression. the addition of dexamethasone, a specific phospholipase a2 inhibitor, did not inhibit antibacterial activity or cecropin gene expression when the larvae were injected  with heat-killed x. nematophila. these results suggest that x. nematophila inhibits the antibacterial humoral immune reaction as well as the cellular immune reaction in s. exigua and that the inhibition of x. nematophila on the expression of the antibacterial peptide is not associated with inhibition of the eicosanoid  pathway.
TIHT== 
ABHT== 

PMID== 15018952
TI  == construction and characterization of novel dual stress-responsive bacterial biosensors.
AB  == using the genes for the green fluorescence protein and xenorhabdus luminescens luciferase operon and the promoters for the reca and katg genes, two stress-responsive escherichia coli biosensor strains have been constructed that can individually or concurrently respond to oxidative and genotoxic conditions. strain duo-1 carries the prgdk1 plasmid, which has the reca::gfpuv4 and katg::luxcdabe fusion genes oriented divergently with each other, while in duo-2, i.e., prgdk2, they are in a tandem orientation, with the reca promoter showing run-though transcription of the katg::luxcdabe fusion. these two strains and their responses were characterized using several known hydroxyl radical-forming chemicals, e.g., hydrogen peroxide and cadmium chloride, along with some genotoxins, e.g., mitomycin c and methyl-n-nitro-n-nitrosoguanidine, and some general toxicants. both strains showed an induction of green fluorescent protein  (gfp) and bioluminescence when they experienced dna and oxidative damage, respectively, while the tandem orientation of the two fusion genes within duo-2 allowed it to also sensitively respond to genotoxins via the production of bioluminescence. however, the characteristics of duo-2's bioluminescent response  to each stress were easily distinguishable, making it useful for the detection of both stresses. furthermore, tests with mixtures of chemicals showed that both duo-1 and duo-2 were responsive when chemicals causing oxidative or genotoxic stress were present as a single chemical or within complex chemical mixtures.
TIHT== 
ABHT== 

PMID== 14707137
TI  == a novel secreted protein toxin from the insect pathogenic bacterium xenorhabdus nematophila.
AB  == the bacterium xenorhabdus nematophila is an insect pathogen that produces several proteins that enable it to kill insects. screening of a cosmid library constructed from x. nematophila strain a24 identified a gene that encoded a novel protein that was toxic to insects. the 42-kda protein encoded by the toxin gene was expressed and purified from a recombinant system, and was shown to kill the larvae of insects such as galleria mellonella and helicoverpa armigera when injected at doses of around 30-40 ng/g larvae. sequencing and bioinformatic analysis suggested that the toxin was a novel protein, and that it was likely to  be part of a genomic island involved in pathogenicity. when the native bacteria were grown under laboratory conditions, a soluble form of the 42-kda toxin was secreted only by bacteria in the phase ii state. preliminary histological analysis of larvae injected with recombinant protein suggested that the toxin primarily acted on the midgut of the insect. finally, some of the common strategies used by the bacterial pathogens of insects, animals, and plants are discussed.
TIHT== 
ABHT== 

PMID== 14551984
TI  == bacterial detection of the toxicity of dioxins, polychlorinated diphenyls, and polybrominated diphenyl ethers.
AB  == polychlorinated dibenzo-p-dioxins (pcdds), biphenyls (pcbs), and polybrominated diphenyl ethers (pbdes) were found to induce several specific stresses within bacterial cells. four different recombinant escherichia coli with specific stress promoters (i.e., the reca responsive to dna damage, faba responsive to membrane damage, katg responsive to oxidative damage, and grpe responsive to protein damage) that were fused to the lux operon from vibrio fischeri showed very unique specificities in terms of their stress responses in the presence of pcdd and pcbs. in addition, a recombinant bacterium with the lac promoter fused to the lux operon from xenorhabdus luminescence also showed dose-dependent responses via a loss of bioluminescence because of the addition of the pcdds and pcbs. brominated diphenyl ethers (bde) -47, -99, and -153 congeners, however, were not found to induce any stress within the bacterial cells, indicating that these chemicals do  not stimulate any cellular stresses related to those tested. these three congeners, however, did result in different levels of general cellular toxicity,  which was found to be dependent on the position of the bromine. finally, the cellular toxicity within the bacteria was found to increase when exposed to mixtures of dioxins, pcbs, and pbdes, possibly from synergistic effects.
TIHT== 
ABHT== 

PMID== 12923104
TI  == inactivation of ompr promotes precocious swarming and flhdc expression in xenorhabdus nematophila.
AB  == the response regulator ompr is involved in numerous adaptive responses to environmental challenges. the role that ompr plays in swarming behavior and swarm-cell differentiation in the symbiotic-pathogenic bacterium xenorhabdus nematophila was examined in this study. swarming began 4 h sooner in an ompr mutant strain than in wild-type cells. precocious swarming was correlated with elevated expression of flic, early flagellation, and cell elongation. the level of flhdc mrna was elevated during the early period of swarming in the ompr strain relative to the level in the wild type. these findings show that ompr is involved in the temporal regulation of flhdc expression and flagellum production and demonstrate that this response regulator plays a role in the swarming behavior of x. nematophila.
TIHT== 
ABHT== 

PMID== 12788735
TI  == interactions of insecticidal toxin gene products from xenorhabdus nematophilus pmfi296.
AB  == four genes on a genomic fragment from xenorhabdus nematophilus pmfi296 were shown to be involved in insecticidal activity towards three commercially important insect species. each gene was expressed individually and in combinations in escherichia coli, and the insecticidal activity of the lysates was determined. the combined four genes (xpta1, xpta2, xptb1, and xptc1), in e. coli, showed activity towards pieris brassicae, pieris rapae, and heliothis virescens. the genes xpta1, xptb1, and xptc1 were involved in expressing activity towards p. rapae and p. brassicae, while the genes xpta2, xptb1, and xptc1 were needed for activity towards h. virescens. when each of these three genes was expressed individually in e. coli and the cell lysates were used in insect assays or mixed  and then used, insecticidal activity was detected at a very low level. if the genes xptb1 and xptc1 were expressed in the same e. coli cell and this cell lysate was mixed with cells expressing xpta1, activity was restored to p. rapae and p. brassicae. similarly mixing xptb1/c1 lysate with xpta2 lysate restored activity towards h. virescens. individual gene disruptions in x. nematophilus pmfi296 reduced activity to insects; this activity was restored by complementation with cells expressing either xpta1 or xpta2 for their respective  disruptions or e. coli expressing both xptb1 and xptc1 for individual disruptions of either of these genes. the genes xpta2, xptc1, and xptb1 were expressed as an  operon in pmfi296 and inactivation of xpta2 or xptc1 resulted in silencing of downstream gene(s), while xpta1 was expressed as a single gene. therefore, the two three gene product combinations interact with each other to produce good insecticidal activity.
TIHT== 
ABHT== 

PMID== 12583905
TI  == holin locus characterisation from lysogenic xenorhabdus nematophila and its involvement in escherichia coli shea haemolytic phenotype.
AB  == lysogeny has previously been described in the entomopathogenic bacteria of the genus xenorhabdus. screening of a x. nematophila prophage dna library on blood agar resulted in the identification of a 5.7-kb locus that caused a haemolytic phenotype when cloned in escherichia coli, but not in the e. coli shea null mutant, lacking the shea cryptic haemolysin. this locus exhibited similarity to lysis genes from lambdoid phages. in particular, it encoded a functional holin able to complement a lambda sam7 mutant. it is the second time that a locus encoding a functional holin is shown to reveal the shea haemolytic phenotype in e. coli. the possible role of the holin in extracellular release of shea is discussed.
TIHT== 
ABHT== 

PMID== 12448704
TI  == characterization of the pleiotropic phenotype of an ompr strain of xenorhabdus nematophila.
AB  == xenorhabdus nematophila is an insect pathogen that forms a symbiotic association  with the nematode, steinernema carpocapsae. xenorhabdus is carried into the insect host by the nematode, is released into the hemolymph and participates in killing the insect. the bacteria grow to high concentrations supporting the development of the nematode in the hemolymph. ompr is a global regulatory protein involved in the regulation of porin genes, motility, acid tolerance and virulence in several enteric bacteria. to study the role of ompr in the lifecyle of xenorhabdis, an ompr -minus strain was constructed. the ompr strain produced markedly reduced levels of the porin protein, opnp and was both hypermotile and exhibited a hyperhemolysis phenotype. inactivation of flhdc, the master regulator for flagella synthesis, eliminated hemolysin production in the ompr strain, suggesting that ompr regulates hemolysin production via flhdc. the ompr mutant strain was virulent towards insect hosts. however, when nematodes were grown on a mixture of the wild-type and the omnpr strain, only the wild-type strain was recovered indicating that ompr is required for competitive symbiotic interaction  with the nematode. the role of ompr in the symbiosis between the bacterium and the nematode is under investigation.
TIHT== 
ABHT== 

PMID== 12117988
TI  == diverse bacteria are pathogens of caenorhabditis elegans.
AB  == practically and ethically attractive as model systems, invertebrate organisms are increasingly recognized as relevant for the study of bacterial pathogenesis. we show here that the nematode caenorhabditis elegans is susceptible to a surprisingly broad range of bacteria and may constitute a useful model for the study of both pathogens and symbionts.
TIHT== 
ABHT== 

PMID== 11719071
TI  == two novel insect defensins from larvae of the cupreous chafer, anomala cuprea: purification, amino acid sequences and antibacterial activity.
AB  == a humoral immune response in larvae of the coleopteran insect, anomala cuprea has been examined for exploring the molecular basis of host-pathogen interactions. the antibacterial activity against the gram-positive strain, micrococcus luteus was detected at a low level in absence of injection. the activity increased strikingly in the hemolymph of the larvae challenged with escherichia coli, showing the fluctuating profile through a time course, which consists of the static induction phase, the production phase rising to a maximum level, and the reduction phase extending over a long duration. two peptides were purified and characterized by reverse-phase hplc, edman degradation and mass spectrometry. they were isoforms, composed of similar sequences with two amino acid substitutions in 43 residues, and novel members of the insect defensins, cysteine-rich antibacterial peptides. anomala defensins a and b showed potent activity against gram-positive bacteria, with slight differences in activity against a few strains of tested bacteria. anomala defensin b was active at high concentration of 40 microm against the gram-negative strain, xenorhabdus japonicus, a pathogen toward the host, a. cuprea larvae.
TIHT== 
ABHT== 

PMID== 11319082
TI  == sequence analysis of insecticidal genes from xenorhabdus nematophilus pmfi296.
AB  == three strains of xenorhabdus nematophilus showed insecticidal activity when fed to pieris brassicae (cabbage white butterfly) larvae. from one of these strains (x. nematophilus pmfi296) a cosmid genome library was prepared in escherichia coli and screened for oral insecticidal activity. two overlapping cosmid clones were shown to encode insecticidal proteins, which had activity when expressed in  e. coli (50% lethal concentration [lc(50)] of 2 to 6 microg of total protein/g of diet). the complete sequence of one cosmid (chrim1) was obtained. on chrim1, five genes (xpta1, -a2, -b1, -c1, and -d1) showed homology with up to 49% identity to  insecticidal toxins identified in photorhabdus luminescens, and also a smaller gene (chi) showed homology to a putative chitinase gene (38% identity). transposon mutagenesis of the cosmid insert indicated that the genes xpta2, xptd1, and chi were not important for the expression of insecticidal activity toward p. brassicae. one gene (xpta1) was found to be central for the expression  of activity, and the genes xptb1 and xptc1 were needed for full activity. the location of these genes together on the chromosome and therefore present on a single cosmid insert probably accounted for the detection of insecticidal activity in this e. coli clone. although multiple genes may be needed for full activity, e. coli cells expressing the xpta1 gene from the bacteriophage lambda p(l) promoter were shown to have insecticidal activity (lc(50) of 112 microg of total protein/g of diet). this is contrary to the toxin genes identified in p. luminescens, which were not insecticidal when expressed individually in e. coli.  high-level gene expression and the use of a sensitive insect may have aided in the detection of insecticidal activity in the e. coli clone expressing xpta1. the location of these toxin genes and the chitinase gene and the presence of mobile elements (insertion sequence) and trna genes on chrim1 indicates that this region of dna represents a pathogenicity island on the genome of x. nematophilus pmfi296.
TIHT== 
ABHT== 

PMID== 11065360
TI  == xenorhabdus bovienii t228 phase variation and virulence are independent of reca function.
AB  == colony pleomorphism, or phase variation, expressed by entomopathogenic bacteria belonging to the genus xenorhabdus, is an important factor which determines the association of the bacteria with their nematode symbiont and the outcome of infection of susceptible insect larvae by the bacterium- nematode parasitic complex. the mechanism underlying phase variation is unknown. to determine whether reca-mediated processes are linked to phase variation, the reca gene of xenorhabdus bovienii was cloned and sequenced. when expressed in a reca-deleted strain of escherichia coli, the x. bovienii reca clone was able to complement the loss of reca function. x. bovienii chromosomal reca insertion mutants showed increased sensitivity to uv. phase 1 forms did not show altered ability to convert to phase 2 and no significant differences in expression of other phase-dependent characteristics, including phospholipase c, haemolysin, protease, antibiotic activity and congo red binding, were noted. furthermore, the ld(50) of the x. bovienii reca insertion mutant for galleria mellonella larvae was not significantly different from that of wild-type strains. from these data the authors conclude that reca is unlikely to be involved in phase variation, the expression of phase-dependent characteristics, or virulence factors involved in killing of susceptible larvae.
TIHT== 
ABHT== 

PMID== 10613869
TI  == flhdc, the flagellar master operon of xenorhabdus nematophilus: requirement for motility, lipolysis, extracellular hemolysis, and full virulence in insects.
AB  == xenorhabdus is a major insect pathogen symbiotically associated with nematodes of the family steinernematidae. this motile bacterium displays swarming behavior on  suitable media, but a spontaneous loss of motility is observed as part of a phenomenon designated phase variation which involves the loss of stationary-phase products active as antibiotics and potential virulence factors. to investigate the role of one of the transcriptional activators of flagellar genes, flhdc, in motility and virulence, the xenorhabdus nematophilus flhdc locus was identified by functional complementation of an escherichia coli flhd null mutant and dna sequencing. construction of x. nematophilus flhd null mutants confirmed that the  flhdc operon controls flagellin expression but also revealed that lipolytic and extracellular hemolysin activity is flhdc dependent. we also showed that the flhd null mutant displayed a slightly attenuated virulence phenotype in spodoptera littoralis compared to that of the wild-type strain. thus, these data indicated that motility, lipase, hemolysin, or unknown functions controlled by the flhdc operon are involved in the infectious process in insects. our investigation expands the view of the flagellar regulon as a checkpoint coupled to a major network involving bacterial physiological aspects as well as motility.
TIHT== 
ABHT== 

PMID== 10529227
TI  == control of luminescence decay and flavin binding by the luxa carboxyl-terminal regions in chimeric bacterial luciferases.
AB  == bacterial luciferases (luxab) can be readily classed as slow or fast decay luciferases based on their rates of luminescence decay in a single turnover assay. luciferases from vibrio harveyi and xenorhabdus (photorhabdus) luminescens have slow decay rates, and those from the photobacterium genus, such as p. (vibrio) fischeri, p. phosphoreum, and p. leiognathi, have rapid decay rates. by  generation of an x. luminescens-based chimeric luciferase with a 67 amino acid substitution from p. phosphoreum luxa in the central region of the luxa subunit,  the "slow" x. luminescens luciferase was converted into a chimeric luciferase, luxa(1)b, with a significantly more rapid decay rate. two other chimeras with p.  phosphoreum sequences substituted closer to the carboxyl terminal of luxa, luxa(2)b and luxa(3)b, retained the characteristic slow decay rates of x. luminescens luciferase but had weaker interactions with both reduced and oxidized flavins, implicating the carboxyl-terminal regions in flavin binding. the dependence of the luminescence decay on concentration and type of fatty aldehyde  indicated that the decay rate of "fast" luciferases arose due to a high dissociation constant (k(a)) for aldehyde (a) coupled with the rapid decay of the resultant aldehyde-free complex via a dark pathway. the decay rate of luminescence (k(t)) was related to the decanal concentration by the equation: k(t) = (k(l)a + k(d)k(a))/(k(a) + a), showing that the rate constant for luminescence decay is equal to the decay rate via the dark- (k(d)) and light-emitting (k(l)) pathways at low and high aldehyde concentrations, respectively. these results strongly implicate the central region in luxa(1)b as  critical in differentiating between "slow" and "fast" luciferases and show that this distinction is primarily due to differences in aldehyde affinity and in the  decomposition of the luciferase-flavin-oxygen intermediate.
TIHT== 
ABHT== 

PMID== 9765850
TI  == universal ribotyping method using a chemically labelled oligonucleotide probe mixture.
AB  == some of the present problems in ribotyping are associated with a lack of uniform  reactivity of probes when bacterial dnas are of phylogenetically diverse origins. to overcome these problems, a set of five oligonucleotides (referred to as oligomix5) was selected to react with conserved sequences located near both extremities of rrs (16s rrna gene) and near both extremities and the middle of rrl (23s rrna gene). dna samples from 13 bacterial species selected to represent  various phylogenetic branches within the eubacteria were cleaved by a restriction endonuclease and electrophoresed in 0.8% agarose, and the fragments were vacuum-transferred to nylon membranes and hybridized with digoxigenin-labelled oligomix5, plasmid dna from pkk3535 (cloned rrn operon from escherichia coli) or  pba2 (cloned rrs from bacillus subtilis), or acetylamino-fluorene-labelled e. coli 16 + 23s rrna. the results showed oligomix5 to visualize patterns in dna from phylogenetically diverse bacteria with comparable intensity. banding patterns (not band intensity) obtained with oligomix5 were identical with those obtained with 16 + 23s rrna or plasmid pkk3535 for each strain studied and represented complete ribotypes. for dna from gram-positive bacteria, complete ribotypes were observed after prolonged enzymatic detection of bands when probes  were either e. coli 16 + 23s rrna or pkk3535. patterns given by plasmid pba2 were subsets of the complete ribotypes for 9/13 strains. each oligonucleotide of the oligomix5 set was used as a probe to determine its contribution to the complete ribotype. the five oligonucleotide probes, used individually, visualized one to four patterns per dna sample. use of dna from xenorhabdus sp. cip 105189 cleaved  by ecori is suggested to control the quality of the oligonucleotide probes composing oligomix5. probe oligomix5 was found to be an essential tool for ribotyping phylogenetically diverse eubacteria.
TIHT== 
ABHT== 

PMID== 9353217
TI  == h-ns protein represses transcription of the lux systems of vibrio fischeri and other luminous bacteria cloned into escherichia coli.
AB  == high expression in escherichia coli of the lux system cistron of a luminous bacteria under its own control has been accomplished only for the vibrio fischeri lux system at high cell density. mutation of the hns gene in e. coli has resulted in strong expression of the v. fischeri lux system at low cell density even in an rpos-deleted strain of e. coli that emits very low levels of luminescence. the e. coli double mutant, mc4110 hns::kan rpos::tet carrying the lux system of v. fischeri, developed high luminescence from the very early stages of cellular growth, regardless of the presence of deletion mutations in the luxi or luxr genes. moreover, autoinducer synthesis was restored in the double mutant with the luxr-deleted system. plac-controlled v. fischeri luxcdabe genes missing luxi and  luxr were dim in e. coli rpos mutant cells, but had wild-type levels of light in  the hns-deleted strain [mc4110 hns rpos], showing that expression was independent of lux regulators in the absence of h-ns. dna gyrase inhibitors and dna intercalating agents also brought about the restoration of luminescence in the rpos-deficient strain. high expression of the lux systems of vibrio harveyi, photobacterium leiognathi, and xenorhabdus luminescens in e. coli mc4110 hns rpos cells compared with that in wild-type or rpos mutants was also accomplished. taken together, these data suggest that the h-ns protein inhibits transcription in e. coli of the lux systems of all or most luminous bacteria at the luxc gene as well as in the luxri region of the v. fischeri lux operon. these dna regions are highly enriched with homopolymeric stretches of poly d(a) and poly d(t) characterizing curved dna, a preferable site of h-ns binding. the significance of the new findings in understanding the regulatory control of the bacterial lux system is discussed.
TIHT== 
ABHT== 

PMID== 8996114
TI  == cloning and nucleotide sequence of a flagellin encoding genetic locus from xenorhabdus nematophilus: phase variation leads to differential transcription of  two flagellar genes (flicd).
AB  == the insect-pathogenic bacterium xenorhabdus undergoes spontaneous phase variation involving a large number of phenotypes. our previous study indicated that phase i variants were motile, whereas phase ii variants of x. nematophilus f1 were nonflagellated cells which did not synthesize flagellin [givaudan a., baghdiguian, s., lanois, a. and boemare, n. (1995) appl. environ. microbiol. 61,  1408-1413]. in order to approach the study of the flagellar switching, a locus containing two orfs from x. nematophilus f1 (phase i) was identified by using functional complementation of flagellin-negative e. coli. the sequence analysis revealed that the first orf corresponds to the flic gene coding for flagellin, and showed a high degree of homology between the n-terminal and c-terminal of xenorhabdus flic and flagellins from other bacteria. the second identified orf in the opposite orientation encodes a homologue of the enterobacterial hook-associated protein 2, flid. both xenorhabdus flicd genes were required for the entire restoration of e. coli motility. a sequence highly homologous to the sigma 28 consensus promoter was identified upstream from the coding sequences from both genes. the structure of the flic gene and its surrounding region was shown to be the same in both phase variants, but northern blot analysis revealed  that flic and flid were, respectively, not and weakly transcribed in phase ii variants. in addition, complementation experiments showed that motility and flagellin synthesis of phase ii cannot be recovered by placing in trans flicd genes from phase i. these latter results suggest that a gene(s) higher in the transcriptional hierarchy of the flagellar regulon is switched off in xenorhabdus phase ii variants.
TIHT== 
ABHT== 

PMID== 8817498
TI  == functional and regulatory analysis of the ompf-like porin, opnp, of the symbiotic bacterium xenorhabdus nematophilus.
AB  == the function and novel regulation of opnp of the symbiotic/pathogenic bacterium,  xenorhabdus nematophilus was studied. in vitro pore-function analysis of purified opnp indicated that the single-channel-conductance values were similar to that measured for the porin protein, ompf, of esherichia coli. nucleotide sequence analysis revealed that the mature opnp protein contained 348 amino acid residues  and shared 55% amino acid sequence identity with ompf. similar to ompf, opnp mapped between asns and aspc. the 16 transmembrane beta-sheet structures and the  internal loop 3 were highly conserved, while the remaining external loop domains  were more divergent. primer extension analysis identified the start site of transcription of opnp. a sigma 70-type promoter, a perfect 20 bp ompr-binding site, and a binding site for the antisense molecule, micf rna, were found in the  upstream region of opnp. while the overall sequence identity of the asn-opnp-aspc region was high, the intergenic region between asns and opnp had diverged markedly. the asns-opnp region was 313 bp shorter than the intergenic region between asns and ompf and lacked the ompr-binding site that is required for ompf  repression by high osmolarity in e. coli. results from osmolarity-shift experiments indicated that opnp was not repressed by high osmolarity. it was also found that opnp was thermally regulated.
TIHT== 
ABHT== 

PMID== 8801419
TI  == molecular analysis of the two-component genes, ompr and envz, in the symbiotic bacterium xenorhabdus nematophilus.
AB  == in escherichia coli the histidine kinase sensor protein, envz, undergoes autophosphorylation and subsequently phosphorylates the regulatory protein, ompr. modulation of the levels of ompr-phosphate controls the differential expression of ompf and ompc. while the phosphotransfer reaction between envz and ompr has been extensively studied, the domains involved in the sensing function of envz are not well understood. we have used a comparative approach to study the sensing function of envz. during our search of numerous bacteria we found that the symbiotic/pathogenic bacterium xenorhabdus nematophilus contained the operon encoding both ompr and envz. nucleotide sequence analysis revealed that envz of x. nematophilus (envzx.n.) is composed of 342 amino acid residues, which is 108 residues shorter than envz of e. coli (envze.c.). amino acid sequence comparison  showed that the cytoplasmic domains of the envz molecules shared 57% sequence identity. in contrast, the large hydrophilic periplasmic domain of envze.c. was absent in envzx.n., and was replaced by a shorter hydrophobic region. although the periplasmic domains had diverged extensively, envzx.n. was able to complement a delta envz strain of e. coli. ompf and ompc were differentially produced in response to changes in medium osmolarity in this strain. further genetic analysis established that heterologous phosphorylation between envzx.n. and ompr of e. coli (ompre.c.) accounted for the complementation of the delta envz strain. in addition we show that the ompr molecules of x. nematophilus and e. coli share 78% amino acid sequence identity. these results indicate that the envz protein of x.  nematophilus was able to sense these changes in the osmolarity of the growth environment and properly regulate the levels of ompr-phosphate in e. coli.
TIHT== 
ABHT== 

PMID== 7676858
TI  == formation of active bacterial luciferase between interspecific subunits in vivo.
AB  == interspecific complementation between luxas and luxbs from vibrio harveyi, vibrio fischeri, photobacterium leiognathi and xenorhabdus luminescens was examined in vivo. the individual genes from these species were cloned on different compatible plasmids or amplified by pcr and brought together to yield cis combinations without extraneous dna. the beta subunits from v. harveyi and x. luminescens form active enzyme only with alpha subunits from one of these species. all other combinations yield active enzymes. the lack of activity of the v. harveyi and x.  luminescens beta subunits with the alpha subunits from v. fischeri and p. leiognathi results from a lack of association. this was shown by in vivo competition in which these beta subunits were overproduced in comparison with the beta and alpha of v. fischeri. no reduction in light was found. overall, the in vivo results parallel those found in vitro using isolated denatured subunits and  renaturation by removal of the denaturant.
TIHT== 
ABHT== 

PMID== 7887602
TI  == characterization and environmental regulation of outer membrane proteins in xenorhabdus nematophilus.
AB  == we have examined the production of the outer membrane proteins of the primary and secondary forms of xenorhabdus nematophilus during exponential- and stationary-phase growth at different temperatures. the most highly expressed outer membrane protein of x. nematophilus was opnp. the amino acid composition of opnp was very similar to those of the porin proteins ompf and ompc of escherichia coli. n-terminal amino acid sequence analysis revealed that residues 1 to 27 of the mature opnp shared 70 and 60% sequence identities with ompc and ompf, respectively. these results suggest that opnp is a major porin protein in x. nematophilus. three additional proteins, opna, opnb, and opns, were induced during stationary-phase growth. opnb was present at a high level in stationary-phase cells grown at 19 to 30 degrees c and was repressed in cells grown at 34 degrees c. opna was optimally produced at 30 degrees c and was not present in cells grown at lower and higher temperatures. the production of opns was not dependent on growth temperature. in contrast, another outer membrane protein, opnt, was strongly induced as the growth temperature was elevated from 19 to 34 degrees c. in addition, we show that the stationary-phase proteins opna  and opnb were not produced in secondary-form cells.
TIHT== 
ABHT== 

PMID== 7959046
TI  == expression of luxcd-e in anabaena sp. can replace the use of exogenous aldehyde for in vivo localization of transcription by luxab.
AB  == the genes luxcdabe from four luminescent bacteria suffice for light production in escherichia coli [meighen, microbiol. rev. 55 (1991) 123-142]. we have inserted these gene clusters between inverted polylinkers, and placed the resulting cassettes as reporters within derivatives of transposon tn5. anabaena sp. strain  pcc 7120 was mutagenized with these transposons. the luminescence of all but the  most highly self-luminescent resulting derivatives of anabaena sp. was strongly dependent on exogenously added aldehyde. thus, luminescence based on luxcdabe is  multiplicatively limited by production of luciferase and aldehyde. no toxicity was observed over protracted periods of luminescence. by deletion, new cassettes  were derived in which only the aldehyde biosynthetic genes, luxcd-e, remained intact. transcription was localized at the single-cell level in strains of cyanobacteria bearing constitutively expressed xenorhabdus luminescens luxcd-e on a plasmid and relatively weakly expressed, developmentally regulated luxab from vibrio spp. in the chromosome. the developmentally critical gene, hetr, was thereby shown to remain active in mature heterocysts.
TIHT== 
ABHT== 

PMID== 7986053
TI  == immobilization of escherichia coli expressing the lux genes of xenorhabdus luminescens.
AB  == the luxcdabe operon of xenorhabdus luminescens was cloned into puc18 to make plite27. expression of the lux genes from the lac promoter resulted in strong constitutive light emission by escherichia coli dh5 carrying the recombinant lux  plasmid, plite27. when strain dh5(plite27) was immobilized with sodium alginate-cacl2, the embedded cells retained their luminescence up to 2 weeks under appropriate storage conditions.
TIHT== 
ABHT== 

PMID== 7510325
TI  == antimicrobial activity and biosynthesis of indole antibiotics produced by xenorhabdus nematophilus.
AB  == we have investigated the mechanism of action and physiology of production of the  indole derivative antibiotics produced by the nematode-associated, entomopathogenic bacterium xenorhabdus nematophilus. maximum antibiotic concentration was reached during the late stationary phase of growth, and the antibiotic yield was appreciably enhanced by supplementation with tryptophan. antibiotic biosynthesis apparently involved the removal of the side-chain carboxyl (c-1) carbon of tryptophan. the c-3 methylene carbon of tryptophan, on the other hand, was retained. the purified indole antibiotic was effective against both gram-positive and gram-negative bacteria at low to moderate concentrations causing a severe inhibition of rna synthesis, accompanied by a less severe effect on protein synthesis. an isogenic pair of escherichia coli strains differing at the rela locus was used to demonstrate that the swift reduction in total rna synthesis is related to an antibiotic-induced accumulation of the regulatory nucleotide, ppgpp, in susceptible bacteria. the e. coli rela mutant, which does not exhibit any discernible increase in ppgpp upon antibiotic  treatment, showed no decrease in growth or rna synthesis. using this antibiotic,  it was also observed that ppgpp may be employed as a metabolic regulator in bacteria such as pseudomonas putida, which have not previously been reported to employ ppgpp as a regulatory molecule. we propose that the indole derivative antibiotic exerts growth inhibitory control in susceptible bacteria by greatly enhancing synthesis of ppgpp, resulting in a rapid inhibition of rna synthesis.
TIHT== 
ABHT== 

PMID== 8399314
TI  == subunit interactions and the role of the luxa polypeptide in controlling thermal  stability and catalytic properties in recombinant luciferase hybrids.
AB  == bacterial luciferases with over 70% sequence identity from the terrestrial species, xenorhabdus luminescens, and the marine species, vibrio harveyi, exhibit large differences in thermal stability (szittner and meighen, 1990, j. biol. chem. 265, 16581-16587). the origin of these differences was investigated with genetically constructed hybrids containing one subunit from x. luminescens and the other from v. harveyi. while no activity was detected with the single (alpha  and beta) subunits both in vitro and in vivo, the recombinant hybrid luciferases  (alpha xl beta vh and alpha vh beta xh) were highly active and could be purified  to homogeneity. the kinetic properties of the hybrid enzymes including aldehyde specificity, flavin binding and luminescence decay rates, were found to be nearly identical to those of the native luciferases (alpha xl beta xl or alpha vh beta vh) containing the same alpha subunit. in addition, the rate of thermal inactivation and temperature dependent quenching of the intrinsic fluorescence by flavin were found to be independent of the nature of the beta subunit, quite opposite to previous reports that the thermal stability is controlled by the beta subunit. thus, the alpha subunit appears primarily responsible for controlling both the catalytic and structural properties of luciferase.
TIHT== 
ABHT== 

PMID== 1282791
TI  == the role of guanosine-3',5'-bis-pyrophosphate in mediating antimicrobial activity of the antibiotic 3,5-dihydroxy-4-ethyl-trans-stilbene.
AB  == the mode of action of 3,5-dihydroxy-4-ethyl-trans-stilbene (es), an antibiotic produced by xenorhabdus luminescens symbiotically associated with an entomopathogenic nematode, was investigated. es was active against gram-positive  and a number of gram-negative bacteria. in susceptible bacteria this antibiotic caused the inhibition of total rna synthesis and, to a lesser extent, protein synthesis. at or above mics, es triggered a substantial accumulation of an intracellular regulatory compound, guanosine-3',5'-bis-pyrophosphate (ppgpp). this response was also noticed in species of bacteria which have previously not been shown to use ppgpp as a regulatory molecule. the involvement of ppgpp in antibiotic action was confirmed by using an isogenic stringent and a relaxed pair of escherichia coli strains. the fact that the accumulation of ppgpp was correlated with the susceptibility of various gram-positive and gram-negative bacteria to es suggests that this nucleotide is involved in the regulation of rna synthesis and growth in all these microorganisms. thus, inhibition of rna synthesis via an increase in ppgpp concentrations may represent a mechanism that  is prevalent among most bacteria and one that could be exploited for achieving a  rapid inhibition of bacterial growth.
TIHT== 
ABHT== 

PMID== 1633988
TI  == molecular cloning and characterization of the lux genes from the secondary form of xenorhabdus luminescens, k122.
AB  == 
TIHT== 
ABHT== 

PMID== 16348462
TI  == characterization of tn5-induced mutants of xenorhabdus nematophilus atcc 19061.
AB  == a negative-selection vector, phx1, was constructed for use in transposon mutagenesis of xenorhabdus nematophilus atcc 19061. phx1 contains the bacillus subtilis levansucrase gene which confers sucrose sensitivity. in addition, various tn5-containing plasmids with different replication origins were transferred by conjugation from escherichia coli into x. nematophilus atcc 19061, and one of these plasmids, pgs9, yields tn5 insertion mutants of x. nematophilus  atcc 19061. by using these two delivery vehicles, more than 250 putative tn5 insertion mutants of x. nematophilus atcc 19061 were isolated and were then characterized. mutants that were altered in bromothymol blue adsorption, ability  to lyse sheep erythrocytes, production of antibiotics on a variety of media, and  virulence for galleria mellonella were found.
TIHT== 
ABHT== 

PMID== 1995589
TI  == cloning and nucleotide sequences of lux genes and characterization of luciferase  of xenorhabdus luminescens from a human wound.
AB  == xenorhabdus luminescens hw is the only known luminous bacterium isolated from a human (wound) source. a recombinant plasmid was constructed that contained the x. luminescens hw luxa and luxb genes, encoding the luciferase alpha and beta subunits, respectively, as well as luxc, luxd, and a portion of luxe. the nucleotide sequences of these lux genes, organized in the order luxcdabe, were determined, and overexpression of the cloned luciferase genes was achieved in escherichia coli host cells. the cloned luciferase was indistinguishable from the wild-type enzyme in its in vitro bioluminescence kinetic properties. contrary to  an earlier report, our findings indicate that neither the specific activity nor the size of the alpha (362 amino acid residues, mr 41,389) and beta (324 amino acid residues, mr 37,112) subunits of the x. luminescens hw luciferase was unusual among known luminous bacterial systems. significant sequence homologies of the alpha and beta subunits of the x. luminescens hw luciferase with those of  other luminous bacteria were observed. however, the x. luminescens hw luciferase  was unusual in the high stability of the 4a-hydroperoxyflavin intermediate and its sensitivity to aldehyde substrate inhibition.
TIHT== 
ABHT== 

PMID== 2211511
TI  == cloning, organization, and expression of the bioluminescence genes of xenorhabdus luminescens.
AB  == the lux genes of xenorhabdus luminescens, a symbiont of the nematode heterorhabditis bacteriophora, were cloned and expressed in escherichia coli. the expression of these genes in e. coli was qualitatively similar to their expression in x. luminescens. the organization of the genes is similar to that found in the marine luminous bacteria. hybridization studies with the dna that codes for the two subunits of luciferase revealed considerable homology among all of the strains of x. luminescens and with the dna of other species of luminous bacteria, but none with the nonluminous xenorhabdus species. gross dna alterations such as insertions, deletions, or inversions do not appear to be involved in the generation of dim variants known as secondary forms.
TIHT== 
ABHT== 

PMID== 2204626
TI  == nucleotide sequence, expression, and properties of luciferase coded by lux genes  from a terrestrial bacterium.
AB  == the lux genes required for expression of luminescence have been cloned from a terrestrial bacterium, xenorhabdus luminescens, and the nucleotide sequences of the luxa and luxb genes coding for the alpha and beta subunits of luciferase determined. the lux gene organization was closely related to that of marine bacteria from the vibrio genus with the luxd gene being located immediately upstream and the luxe downstream of the luciferase genes, luxab. a high degree of homology (85% identity) was found between the amino acid sequences of the alpha subunits of x. luminescens luciferase and the luciferase from a marine bacterium, vibrio harveyi, whereas the beta subunits of the two luciferases had only 60% identity in amino acid sequence. the similarity in the sequences of the alpha subunits of the two luciferases was also reflected in the substrate specificities and turnover rates with different fatty aldehydes supporting the proposal that the alpha subunit almost exclusively controls these properties. the luciferase from x. luminescens was shown to have a remarkably high thermal stability being stable at 45 degrees c (t 1/2 greater than 3 h) whereas v. harveyi luciferase was rapidly inactivated at this temperature (t 1/2 = 5 min). these results indicate that the x. luminescens lux system may be the bacterial bioluminescent system of  choice for application in coupled luminescent assays and expression of lux genes  in eukaryotic systems at higher temperatures.
TIHT== 
ABHT== 

