@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25975665
TI  == clinical utility and performance of sock sampling in weaner pig diarrhoea.
AB  == low pathogen diarrhoea is a group-level diagnosis, characterised by non-haemorrhagic diarrhoea. in the current study, the apparent prevalence of low  pathogen diarrhoea outbreaks in danish herds was investigated along with the clinical utility of a laboratory examination for intestinal disease, agreement between three consecutive herd examinations from the same herd and agreement between quantitative pcr results from pooled faecal samples and sock samples. twenty-four veterinarians submitted faecal and sock samples for quantitative pcr  testing from outbreaks of diarrhoea in nursery pigs (n=38 herds) where the farmer or veterinarian had decided that antimicrobial treatment was necessary. the veterinarians were asked to fill in a questionnaire and participate in telephone  interviews. the apparent prevalence of low pathogen diarrhoea was 0.18 (95% cl: 0.08-0.34). agreement between the veterinarians' clinical aetiological diagnosis  and the pooled faecal sample was 0.18 (95% cl: 0.08-0.34), and cohen's kappa was  0.03 (95% cl: -0.08 to 0.14). antibiotic treatment or prevention strategies were  changed in 0.63 (95% cl: 0.46-0.78) of the herds, and the veterinarians indicated that, for 0.32 (95% cl: 0.18-0.50) of the herds, changes were related to the diagnostic results from the laboratory examination performed in the study. in 0.16 (95% cl: 0.05-0.36) of the herds, the same infections were demonstrated at all three consecutive examinations. no herds had three consecutive diarrhoea outbreaks classified as low pathogen diarrhoea. for the quantitative results (log10 of the summed amounts of lawsonia intracellularis, brachyspira pilosicoli, escherichia coli f4 and f18) agreement between pooled faecal samples and sock samples was evaluated. lin's concordance correlation coefficient was 0.69 (95% cl: 0.48-0.82), and the mean difference between the two types of samples was -0.38 log10 bacteria/g faeces (sd=1.59log10 bacteria/g faeces; 95% ci: -0.90 to 0.14log10 bacteria/g faeces). agreement for the dichotomised results was 0.89 (95% ci: 0.75-0.97) when test results were classified as low pathogen diarrhoea or not, and cohen's kappa was 0.61 (95% ci: 0.26-0.95). in relation to detection  of the individual infections, agreement was 0.63 (95% ci: 0.46-0.78), and cohen's kappa was 0.53 (95% ci: 0.34-0.71). in conclusion, low pathogen diarrhoea is a common finding amongst diarrhoea outbreaks that are subjected to antibiotic batch treatment in danish nursery pigs. sock samples seem to offer a reliable diagnostic method with impact on clinical decisions for treatment and prevention. however, both the diarrhoea type and the aetiology change with time in the majority of herds, indicating a potential need for frequent diagnostic examinations.
TIHT== 
ABHT== 

PMID== 25392732
TI  == herd diagnosis of low pathogen diarrhoea in growing pigs - a pilot study.
AB  == background: the major indication for antibiotic use in danish pigs is treatment of intestinal diseases post weaning. clinical decisions on antibiotic batch medication are often based on inspection of diarrhoeic pools on the pen floor. in some of these treated diarrhoea outbreaks, intestinal pathogens can only be demonstrated in a small number of pigs within the treated group (low pathogen diarrhoea). termination of antibiotic batch medication in herds suffering from such diarrhoea could potentially reduce the consumption of antibiotics in the pig industry. the objective of the present pilot study was to suggest criteria for herd diagnosis of low pathogen diarrhoea in growing pigs. data previously collected from 20 danish herds were used to create a case series of clinical diarrhoea outbreaks normally subjected to antibiotic treatment. in the present study, these diarrhoea outbreaks were classified as low pathogen (<15% of the pigs having bacterial intestinal disease) (n =5 outbreaks) or high pathogen (>/=15% of the pigs having bacterial intestinal disease) (n =15 outbreaks). based on the case series, different diagnostic procedures were explored, and criteria for herd diagnosis of low pathogen diarrhoea were suggested. the effect of sampling variation was explored by simulation. results: the diagnostic procedure  with the highest combined herd-level sensitivity and specificity was qpcr testing of a pooled sample containing 20 randomly selected faecal samples. the criteria for a positive test result (high pathogen diarrhoea outbreak) were an average of  1.5 diarrhoeic faecal pools on the floor of each pen in the room under investigation and a pathogenic bacterial load >/=35,000 per gram in the faecal pool tested by qpcr. the bacterial load was the sum of lawsonia intracellularis,  brachyspira pilosicoli and escherichia coli f4 and f18 bacteria per gram faeces.  the herd-diagnostic performance was (herd-level) diagnostic sensitivity =0.99, diagnostic specificity =0.80, positive predictive value =0.94 and negative predictive value =0.96. conclusions: the pilot study suggests criteria for herd diagnosis of low pathogen diarrhoea in growing pigs. the suggested criteria should now be evaluated, and the effect of terminating antibiotic batch medication in herds identified as suffering from low pathogen diarrhoea should be explored.
TIHT== 
ABHT== 

PMID== 24576503
TI  == immunomodulatory factors and infectious agents associated with the hepatic gene expression of the igf system in nursery pigs.
AB  == recent findings suggest there is a complex interaction between the igf system and the inflammatory immune response. the objective of this study was to determine whether gene expression of growth factors (igf-1, igf-binding protein-3 (igfbp-3) and growth hormone receptors (ghr)) in the liver is associated with gene expression of immunomodulators in the liver, including c-reactive protein (crp),  serum amyloid a (saa), haptoglobin (hp), interferon-alpha (ifn-alpha), ifn-gamma, tumour necrosis factor-alpha (tnf-alpha), interleukin (il)-1beta, il-6, il-10 and il-18, as well as with the presence of salmonella spp., lawsonia intracellularis, brachyspira spp., enterotoxigenic escherichia coli, methicillin-resistant staphylococcus aureus, swine influenza virus, and porcine reproductive and respiratory syndrome virus (prrsv) in nursery pigs (n=74) from commercial farms (n=4). gene expression was quantified using reverse transcription quantitative-pcr (rt-qpcr) and the data were modelled using logistic regression methods. pigs with elevated igf-1 expression were less likely to have increased expression of tnf-alpha (odds ratio (or)=0.14, p<0.01) and il-18 (or=0.19, p<0.05), and less likely to be colonized with prrsv (or=0.03, p<0.01). pigs with  increased expression of igfbp-3 were more likely to have elevated il-6 expression (or=8.5, p<0.05). it was also observed that igfbp-3 and igf-1 were significantly  associated when hp expression was low (or=30, p<0.05), but this association was not significant when hp expression was high (p=0.54). pigs with increased expression of ghr were less likely to have elevated expression of saa (or=0.01, p<0.05) and il-1beta (or=0.03, p<0.05), but more likely to have increased expression of crp (or=290, p<0.01). overall, there appears to be an inverse association between the hepatic expression of the igf system (igf-1, igfbp-3, ghr) and certain cytokines (il-1beta, il-18, tnf-alpha) and acute-phase proteins  (saa, hp).
TIHT== 
ABHT== 

PMID== 24289297
TI  == phytochemical, toxicological and antimicrobial evaluation of lawsonia inermis extracts against clinical isolates of pathogenic bacteria.
AB  == background: the emerging resistance of pathogen against the currently available antimicrobial agents demands the search of new antimicrobial agents. the use of medicinal plants as natural substitute is the paramount area of research to overwhelm the drug resistance of infectious agents. scientists have not made enough effort on the evaluation of safety of medicinal plant yet. methods: in the present study antimicrobial activity of lawsonia inermis is investigated against  clinical isolates of seven bacteria including four gram negative (escherichia coli, salmonella typhi, klebsiella spp., shigella sonnei) and three gram positive (bacillus subtilis, staphylococcus aureus, staphylococcus epidermidis) using disc diffusion method. four types of lawsonia inermis extracts were prepared using methanol, chloroform, acetone and water as extraction solvents, while dmso (dimethyl sulfoxide) and water as dissolution solvents. the rate and extent of bacterial killing was estimated by time-kill kinetic assay at 1x mic of each bacterial isolate. the overall safety of lawsonia inermis extracts was assessed in mice. results: lawsonia inermis displayed noteworthy antimicrobial activity against both gram positive and gram negative bacterial strains used in the study. the minimum value of mic for different bacterial strains ranged from 2.31 mg/ml to 9.27 mg/ml. at 1x mic of each bacterial isolate, 3log10 decrease in cfu was recorded after 6 hours of drug exposure and no growth was observed in almost all  tested bacteria after 24 hours of exposure. no sign of toxidrome were observed during in vivo toxicity evaluation in mice at 300 mg/kg concentration. conclusion: in conclusion, the present study provides the scientific rational for medicinal use of lawsonia inermis. the use of lawsonia inermis extracts is of great significance as substitute antimicrobial agent in therapeutics.
TIHT== 
ABHT== 

PMID== 23758488
TI  == preparation of antibacterial pva and peo nanofibers containing lawsonia inermis (henna) leaf extracts.
AB  == concerns about health issues and environmental pollution stimulate research to find new health and hygiene related products with healing properties and minimum  negative effect on the environment. development of new, natural antibacterial agents has become one of the most important research areas to combat some pathogens such as gram- positive and gram-negative bacteria, fungi, algae, yeast, and some microorganisms which cause serious human infections. lawsonia inermis (henna) leaf extracts for preparation of antibacterial poly(ethylene oxide) (peo) and poly(vinyl alcohol) (pva) nanofibers via electrospinning technique were investigated. peo and pva based electrospun fibers containing henna extract were  verified by the appearance of ftir peaks corresponding to the pure extract. our study demonstrates that 2.793 wt.% li in pva and peo based solutions showed bactericidal effects against staphylococcus aureus and bacteriostatic action to escherichia coli. concentrations of henna leaf extract strongly impacted antibacterial activities against both bacteria. henna leaves have a great potential to be used as a source of a potent eco-friendly antimicrobial agent.
TIHT== 
ABHT== 

PMID== 23569850
TI  == antibacterial activity of sequentially extracted organic solvent extracts of fruits, flowers and leaves of lawsonia inermis l. from jaffna.
AB  == objective: to reveal the antibacterial activity of sequentially extracted different cold organic solvent extracts of fruits, flowers and leaves of lawsonia inermis (l. against) some pathogenic bacteria. methods: powders of fruits, flowers and leaves of l. inermis were continuously extracted with dichloromethane (dcm), ethyl acetate and ethanol at ambient temperature. the dried extracts were  prepared into different concentrations and tested for antibacterial activity by agar well diffusion method, and also the extracts were tested to determine the available phytochemicals. results: except dcm extract of flower all other test extracts revealed inhibitory effect on all tested bacteria and their inhibitory effect differed significantly (p<0.05). the highest inhibitory effect was showed  by ethyl acetate extract of flower against staphylococcus aureus (s. aureus) and  pseudomonas aeruginosa (p. aeruginosa), and ethyl acetate extract of fruit on escherichia coli (e. coli) and bacillus subtilis (b. subtilis). the ethyl acetate and ethanol extracts of flower, fruit and leaf expressed inhibition even at 1 mg/100 microl against all test bacteria. among the tested phytochemicals flavonoids were detected in all test extracts except dcm extract of flower. conclusions: the study demonstrated that the ethyl acetate and ethanol extracts of fruit and flower of l. inermis are potentially better source of antibacterial  agents compared to leaf extracts of respective solvents.
TIHT== 
ABHT== 

PMID== 23536614
TI  == diagnostic performance of fecal quantitative real-time polymerase chain reaction  for detection of lawsonia intracellularis-associated proliferative enteropathy in nursery pigs.
AB  == quantitative polymerase chain reaction (qpcr) tests for detection and quantification of lawsonia intracellularis in feces from pigs have been developed. the objective of the current study was to evaluate the diagnostic performance of a fecal qpcr test for detection of nursery pigs with l. intracellularis-associated proliferative enteropathy (pe) under field conditions. furthermore, the diagnostic performance for different subpopulations of pigs was  investigated, including pigs infected or noninfected with porcine circovirus-2, brachyspira pilosicoli, and escherichia coli. the diagnostic performance was evaluated in terms of diagnostic sensitivity and specificity. data from pigs originating from 20 herds with antibiotic treatment requiring diarrhea outbreaks  from a prior study were reused. before treatment, pigs were randomly selected for histological and immunohistochemical examination of intestinal segments and fecal quantification of l. intracellularis by qpcr. a total of 313 pigs (157 without diarrhea, 156 with diarrhea) were included in the statistical analysis, and 37 pigs (11.8%) were classified as pe positives (defined as proliferative histological lesions in combination with l. intracellularis demonstration by immunohistochemistry). lawsonia intracellularis was detected by qpcr in feces from 91 pigs (29.1%). a nonparametric receiver operating characteristic (roc) analysis provided an area under the roc curve (0.93) and an optimal cutoff value  of 4.8 log10 l. intracellularis bacteria/g feces. this cutoff provided a diagnostic sensitivity of 0.84 and diagnostic specificity of 0.93. the diagnostic sensitivity and specificity were significantly different between herds (p < 0.0001). numerically, diagnostic sensitivity and specificity were different between subpopulations of pigs, but no significant differences were demonstrated.
TIHT== 
ABHT== 

PMID== 21530108
TI  == the use of quantitative pcr for identification and quantification of brachyspira  pilosicoli, lawsonia intracellularis and escherichia coli fimbrial types f4 and f18 in pig feces.
AB  == four quantitative pcr (qpcr) assays were evaluated for quantitative detection of  brachyspira pilosicoli, lawsonia intracellularis, and e. coli fimbrial types f4 and f18 in pig feces. standard curves were based on feces spiked with the respective reference strains. the detection limits from the spiking experiments were 10(2) bacteria/g feces for bpilo-qpcr and laws-qpcr, 10(3)cfu/g feces for f4-qpcr and f18-qpcr. the pcr efficiency for all four qpcr assays was between 0.91 and 1.01 with r(2) above 0.993. standard curves, slopes and elevation, varied between assays and between measurements from pure dna from reference strains and feces spiked with the respective strains. the linear ranges found for spiked fecal samples differed both from the linear ranges from pure culture of the reference strains and between the qpcr tests. the linear ranges were five log units for f4-qpcr, and laws-qpcr, six log units for f18-qpcr and three log units  for bpilo-qpcr in spiked feces. when measured on pure dna from the reference strains used in spiking experiments, the respective log ranges were: seven units  for bpilo-qpcr, laws-qpcr and f18-qpcr and six log units for f4-qpcr. this shows  the importance of using specific standard curves, where each pathogen is analysed in the same matrix as sample dna. the qpcrs were compared to traditional bacteriological diagnostic methods and found to be more sensitive than cultivation for e. coli and b. pilosicoli. the qpcr assay for lawsonia was also more sensitive than the earlier used method due to improvements in dna extraction. in addition, as samples were not analysed for all four pathogen agents by traditional diagnostic methods, many samples were found positive for agents that were not expected on the basis of age and case history. the use of quantitative pcr tests for diagnosis of enteric diseases provides new possibilities for veterinary diagnostics. the parallel simultaneous analysis for  several bacteria in multi-qpcr and the determination of the quantities of the infectious agents increases the information obtained from the samples and the chance for obtaining a relevant diagnosis.
TIHT== 
ABHT== 

PMID== 21236578
TI  == investigations on the prevalence and potential pathogenicity of intestinal trichomonads in pigs using in situ hybridization.
AB  == in pigs, three different trichomonad species (tritrichomonas foetus, tetratrichomonas buttreyi and tritrichomonas rotunda) have been described as commensals in the large intestine. the aim of this study was to gain further knowledge on the prevalence and pathogenicity of trichomonads in pigs by using a  morphology-based approach. chromogenic in situ hybridization (ish) is a technique which allows direct localization of the protozoa in the intestinal tissue and correlation of the infection with pathologic changes. in the present study paraffin-wax embedded colon and ileum samples of 192 pigs were analyzed with this method. using a probe specific for all known members of the order trichomonadida  (ot) 100 of the 192 pigs were tested positive. thereof, about 10% showed moderate to high-grade parasitic load with trichomonads invading the lamina propria. partial 18s ribosomal rna gene sequencing of six of those animals showed a 100% sequence identity with t. foetus sequences. the majority of these animals were also tested positive for other enteropathogenic agents, such as brachyspira sp.,  lawsonia intracellularis, escherichia coli, and porcine circovirus type 2. all ot-positive samples were further examined with another probe complementary to all known tritrichomonas species sequences including t. foetus, t. augusta, t. mobilensis and t. nonconforma resulting in only 48 positives. these results suggest that t. foetus may not only be considered as an intestinal commensal but  rather a facultative pathogen of pigs with a tendency for tissue invasion in the  presence of other agents. furthermore, the existence of other - yet to be identified - trichomonad species in the colon of pigs was shown.
TIHT== 
ABHT== 

PMID== 18606736
TI  == lawsonia intracellularis contains a gene encoding a functional rickettsia-like atp/adp translocase for host exploitation.
AB  == atp/adp translocases are a hallmark of obligate intracellular pathogens related to chlamydiae and rickettsiae. these proteins catalyze the highly specific exchange of bacterial adp against host atp and thus allow bacteria to exploit their hosts' energy pool, a process also referred to as energy parasitism. the genome sequence of the obligate intracellular pathogen lawsonia intracellularis (deltaproteobacteria), responsible for one of the most economically important diseases in the swine industry worldwide, revealed the presence of a putative atp/adp translocase most similar to known atp/adp translocases of chlamydiae and  rickettsiae (around 47% amino acid sequence identity). the gene coding for the putative atp/adp translocase of l. intracellularis (l. intracellularis nucleotide transporter 1 [ntt1(li)]) was cloned and expressed in the heterologous host escherichia coli. the transport properties of ntt1(li) were determined by measuring the uptake of radioactively labeled substrates by e. coli. ntt1(li) transported atp in a counterexchange mode with adp in a highly specific manner; the substrate affinities determined were 236.3 (+/- 36.5) microm for atp and 275.2 (+/- 28.1) microm for adp, identifying this protein as a functional atp/adp translocase. ntt1(li) is the first atp/adp translocase from a bacterium not related to chlamydiae or rickettsiales, showing that energy parasitism by atp/adp translocases is more widespread than previously recognized. the occurrence of an  atp/adp translocase in l. intracellularis is explained by a relatively recent horizontal gene transfer event with rickettsiae as donors.
TIHT== 
ABHT== 

PMID== 18404337
TI  == antibacterial activity of some medicinal plant extracts.
AB  == antibacterial activity of hot aqueous and methanolic extracts prepared from six plants (terminallia chebula, terminallia bellerica, phyllanthus emblica, punica granatum, lawsonia alba and mikania micrantha) used in traditional folk medicines of india were screened against five pathogenic bacteria (staphylococcus aureus mtcc 2940, bacillus subtilis mtcc 441, escherichia coli mtcc 739, proteus vulgaris mtcc 426 and enterobacter aerogenes mtcc 111). the highest antibacterial potentiality was exhibited by the methanolic leaf extract of t. chebula, followed by the aqueous fruit extract of t. bellerica. the leaf extract of t. chebula can  be considered to be as equally potent as the most effective antibiotics, such as  ciprofloxacin, gentamycin, kanamycin, ofloxacin and cephalexin. a sensitivity test performed with commonly used sensitivity test disks resulted in the appearance of multiple drug resistance phenotypes of the bacteria tested. a comparison of data in the inhibition zones of pathogenic bacteria showed that gentamycin, ofloxacin, kanamycin and tobramycin were effective against all of the bacterial strains tested.
TIHT== 
ABHT== 

PMID== 17440624
TI  == antibacterial properties of traditionally used indian medicinal plants.
AB  == in search of broad-spectrum antibacterial activity from traditionally used indian medicinal plants, 66 ethanolic plant extracts were screened against nine different bacteria. of these, 39 extracts demonstrated activity against six or more test bacteria. twelve extracts showing broad-spectrum activity were tested against specific multidrug-resistant (mdr) bacteria, methicillin-resistant staphylococcus aureus (mrsa) and extended spectrum beta-lactamases (esbetal)-producing enteric bacteria. in vitro efficacy was expressed in terms of minimum inhibitory concentration (mic) values of plant extracts. mic values ranged from 0.32-7.5 mg/ml against mrsa and 0.31-6.25 mg/ml against esbetal-producing enteric bacteria. the overall activity against all groups of bacteria was found in order of plumbago zeylanica > hemidesmus indicus > acorus calamus > camellia sinensis > terminalia chebula > terminalia bellerica > holarrhena antidysenterica > lawsonia inermis > mangifera indica > punica granatum > cichorium intybus and delonix regia. in addition, these extracts showed synergistic interaction with tetracycline, chloramphenicol and ciprofloxacin against s. aureus and/or escherichia coli. the ethanolic extracts of more than 12 plants were found nontoxic to sheep erythrocytes and nonmutagenic, determined by ames test using salmonella typhimurium test strains (ta 97a, ta 100, ta 102 and ta 104). based on above properties, six plants-plumbago zeylanica, hemidesmus indicus, acorus calamus, punica granatum, holarrhena antidysenterica and delonix regia-were further subjected to fractionation-based study. ethyl acetate, acetone and methanol fractions of more  than six plants indicated that the active phytocompounds were distributed mainly  into acetone and ethyl acetate fractions, whereas they were least prevalent in methanol fractions as evident from their antibacterial activity against mdr bacteria. gram-positive and gram-negative mdr bacteria are almost equally sensitive to these extracts/fractions, indicating their broad-spectrum nature. however, strain- and plant extract-dependent variations in the antibacterial activity were also evident. time-kill assay with the most promising plant fraction plumbago zeylanica (ethyl acetate fraction) demonstrated killing of test bacteria at the level lower than its mic. further, identification of active constituents in each fraction and their additive and synergistic interactions are needed to exploit them in evaluating efficacy and safety in vivo against mdr bacteria.
TIHT== 
ABHT== 

PMID== 15996159
TI  == the comparative importance of e. coli antigen in granulomatous colitis of boxer dogs.
AB  == granulomatous colitis of boxer dogs is characterized by mucosal and submucosal infiltration by abundant large macrophages and lymphocytes and plasma cells. involved intestine is thickened, corrugated and ulcerated. the macrophages that occur in colon, cecum and regional lymph nodes are pas-positive, lipid-rich, contain cholesterol, and some of the time can be seen to hold bacteria. paraffin  tissue blocks of formalin-fixed colon and colic lymph nodes from 10 cases were cut at 5 microm and immunostained by a streptavidin-biotin immunoperoxidase technique, employing primary antibodies against escherichia coli, e. coli 0157: 2, campylobacter, c. jejuni-coli, yersinia pseudotuberculosis, salmonella, shigella, pseudomonas and lawsonia intracellularis. the macrophages in the lamina propria and submucosa, as well as those in aggregates in regional lymph nodes, showed immunoreactivity with polyclonal e. coli antibody in all 10 cases. tissues lacking granulomas were negative, as were those reacted with the other eight antibodies, with the exception that there was rare focal staining for campylobacter, lawsonia and salmonella in a few dogs. we believe these results identify the causative agent of this granulomatous disease of boxer dogs, a disease with great histologic and etiologic similarity to granulomatous leptomeningitis of beagle dogs, and malacoplakia and xanthogranulomatous cholecystitis of man. macrophages that are immunopositive for e. coli antigen occur in crohn's disease as well, where their significance is less well understood.
TIHT== 
ABHT== 

PMID== 14620553
TI  == bacterial pathogens in field cases of clinical colitis in growing and finishing pigs in italy.
AB  == 
TIHT== 
ABHT== 

PMID== 14535543
TI  == preparation and characterization of polyclonal and monoclonal antibodies against  lawsonia intracellularis.
AB  == proliferative enteropathy is an intestinal infectious disease caused by the obligate intracellular bacterium lawsonia intracellularis. immunohistochemistry staining has superior sensitivity over hematoxylin and eosin and silver staining  for detecting l. intracellularis in histological sections. a l. intracellularis-specific monoclonal antibody (mab) produced in the uk (ig4 mab) has been described in the literature. however, no monoclonal or polyclonal antibodies are commercially available. therefore, the objective of this study was to produce and characterize new polyclonal and monoclonal antibodies against l. intracellularis that are suitable for diagnostic use. the new monoclonal (2001 mab) and polyclonal antibodies (1999 pab) were compared with the ig4 mab using western blot analysis of outer membrane proteins (omps) of 6 l. intracellularis isolates, bilophila wadsworthia and brachyspira hyodysenteriae and using immunohistochemistry of known positive and negative histologic samples and pure cultures of l. intracellularis, b. wadsworthia, b. hyodysenteriae, salmonella choleraesuis, s. typhimurium, and escherichia coli k88. immunogold staining using 2001 mab was performed to show the specificity of the antibody against an l. intracellularis surface protein. western blot analysis showed that the 2001 mab targeted an omp of 77 kd, which made it different from the ig4 mab that targeted  an 18-kd omp. the immunogold stain demonstrated the specificity of the 2001 mab to a surface protein of l. intracellularis. the polyclonal antibody (1999 pab) targeted 5 omps (77, 69, 54, 42, and 36 kd). both the 2001 mab and 1999 pab stained known positive, but not negative, histologic samples. both the 2001 mab and 1999 pab reacted with a pure culture of l. intracellularis but not with any other common enteric pathogens. these two new antibodies will be useful for immunodiagnosis of l. intracellularis.
TIHT== 
ABHT== 

PMID== 12837737
TI  == the european ban on growth-promoting antibiotics and emerging consequences for human and animal health.
AB  == following the ban of all food animal growth-promoting antibiotics by sweden in 1986, the european union banned avoparcin in 1997 and bacitracin, spiramycin, tylosin and virginiamycin in 1999. three years later, the only attributable effect in humans has been a diminution in acquired resistance in enterococci isolated from human faecal carriers. there has been an increase in human infection from vancomycin-resistant enterococci in europe, probably related to the increased in usage of vancomycin for the treatment of methicillin-resistant staphylococci. the ban of growth promoters has, however, revealed that these agents had important prophylactic activity and their withdrawal is now associated with a deterioration in animal health, including increased diarrhoea, weight loss and mortality due to escherichia coli and lawsonia intracellularis in early post-weaning pigs, and clostridial necrotic enteritis in broilers. a directly attributable effect of these infections is the increase in usage of therapeutic antibiotics in food animals, including that of tetracycline, aminoglycosides, trimethoprim/sulphonamide, macrolides and lincosamides, all of which are of direct importance in human medicine. the theoretical and political benefit of the widespread ban of growth promoters needs to be more carefully weighed against the increasingly apparent adverse consequences.
TIHT== 
ABHT== 

PMID== 12088666
TI  == how bacteria could cause cancer: one step at a time.
AB  == helicobacter pylori highlighted the potential for bacteria to cause cancer. it is becoming clear that chronic infection with other bacteria, notably salmonella typhi, can also facilitate tumour development. infections caused by several bacteria (e.g. bartonella spp., lawsonia intracellularis and citrobacter rodentium) can induce cellular proliferation that can be reversed by antibiotic treatment. other chronic bacterial infections have the effect of blocking apoptosis. however, the underlying cellular mechanisms are far from clear. conversely, several bacterial toxins interfere with cellular signalling mechanisms in a way that is characteristic of tumour promoters. these include pasteurella multocida toxin, which uniquely acts as a mitogen, and escherichia coli cytotoxic necrotizing factor, which activates rho family signalling. this leads to activation of cox2, which is involved in several stages of tumour development, including inhibition of apoptosis. such toxins could provide valuable models for bacterial involvement in cancer, but more significantly they  could play a direct role in cancer causation and progression.
TIHT== 
ABHT== 

PMID== 11448502
TI  == risk factors for intestinal pathogens in danish finishing pig herds.
AB  == the objective of this investigation was to identify risk factors for infection with the intestinal bacteria: lawsonia intracellularis, brachyspira hyodysenteriae, serpulina intermedia, brachyspira innocens, brachyspira pilosicoli and swine-pathogenic escherichia coli (serogroups o138, o139, o141 and o149) in danish finishing pig herds.a total of 79 herds was randomly selected and visited during 1998. from each herd, 20 faecal samples were collected from individual pigs weighing 30-50 kg. in total, 1580 faecal samples were collected and examined by polymerase chain reaction (l. intracellularis) or culture (all other agents). information on feed and management procedures was collected by filling in questionnaires at the herd visits. the questionnaires included information on 29 dichotomous variables and three continuous variables. variables with p<0.25 in a preliminary screening (chi2- or t-test) were selected for the statistical modelling. our conclusions, based on the results of multifactorial logistic regression (cut-off: p=0.05), were the following: 1. consistent batch production was associated with reduced prevalences of l. intracellularis and weakly -haemolytic spirochetes (s. intermedia, b. innocens, b. pilosicoli) (or's=0.43 and 0.06, respectively). 2. home-mixed (and/or non-pelleted) feed was  associated with reduced prevalences of l. intracellularis and weakly -haemolytic  spirochetes (or's=0.6 and 0.4, respectively). 3. providing straw to finishers was associated with a reduced prevalence of weakly -haemolytic spirochetes (or=0.28-0.32). 4. not using antimicrobial growth promoters for piglets was associated with an increased prevalence of s. intermedia (or=11.11). 5. rare occurrence of post-weaning diarrhoea (as opposed to common) was associated with an increased prevalence of weakly -haemolytic spirochetes (or=8.3-13.7).
TIHT== 
ABHT== 

PMID== 10960714
TI  == prevalence of intestinal pathogens in danish finishing pig herds.
AB  == our aim was to determine the prevalence of the intestinal bacteria: lawsonia intracellularis, brachyspira hyodysenteriae, serpulina intermedia, brachyspira innocens, brachyspira pilosicoli, pathogenic escherichia coli (serogroups o138, o139, o141 and o149) and salmonella enterica in danish finishing pig herds. a total of 79 herds was randomly selected and visited during 1998. from each herd,  20 faecal samples were collected from individual pigs weighing 30-50kg. furthermore, 10 pooled pen samples were collected and examined for s. enterica. in total, 1580 faecal samples and 790 pen samples were collected and examined by  polymerase chain reaction (pcr) or culture. l. intracellularis was found in 74 herds (93.7%), b. hyodysenteriae in two herds (2.5%), s. intermedia in 10 herds (12. 7%), b. innocens in 27 herds (34.2%), b. pilosicoli in 15 herds (19. 0%), pathogenic e. coli in 19 herds (24.1%) and s. enterica in eight herds (10.1%). the within-herd prevalences of l. intracellularis and b. hyodysenteriae were 25-30%; the within-herd prevalences of the other agents were 5-10%. three herds (4%) were not infected with any of the bacteria and 25 herds (32%) were only infected with l. intracellularis.
TIHT== 
ABHT== 

PMID== 10659346
TI  == comparative pathology of bacterial enteric diseases of swine.
AB  == enteric bacterial infections are among the most common and economically significant diseases affecting swine production worldwide. clinical signs of these infections include diarrhea, reduced growth rate, weight loss, and death of preweaned, weanling, grower-finisher, young and adult age breeding animals. the most common etiological agents include escherichia coli, clostridium perfringens, lawsonia intracellularis, salmonella enterica, and brachyspira (serpulina) spp. with the exception of brachyspira (serpulina) hyodysenteriae, the cause of swine  dysentery, and lawsonia intracellularis, the cause of proliferative enteropathy,  the pathological changes seen with these agents closely resemble the diseases occurring in human beings. histological changes in the intestines of swine with enteric bacterial infections include bacterial colonization without significant damage (e.g., certain enterotoxigenic e. coli and c. perfringens type a), attaching and effacing lesions with enteropathogenic e. coli and brachyspira pilosicoli, the cause of colonic spirochetosis, inflammation with s. enterica, and necrotizing and hemorrhagic lesions with certain c. perfringens. extraintestinal spread of bacteria and/or toxins occurs with some serotypes of e. coli and most serotypes of s. enterica. enteric bacterial diseases of swine have  been used as models to study the pathogenesis of similar diseases of human beings. several of these pathogens are also important causes of food-borne disease in humans.
TIHT== 
ABHT== 

PMID== 9720028
TI  == identification and sequencing of the groe operon and flanking genes of lawsonia intracellularis: use in phylogeny.
AB  == proliferative enteropathy (pe) is a complex of diseases of commercial importance  to the pig industry. the obligate intracellular bacterium lawsonia intracellularis is consistently associated with pe and pure cultures of this bacterium have been used to reproduce pe in pigs. in this study l. intracellularis bacteria were purified directly from pe-affected tissue. dna extracted from purified bacteria was used to construct a partial genomic library  which was screened using sera from l. intracellularis-immunized rabbits. two seroreactive recombinant clones were identified, one of which expressed proteins  of 10 and 60 kda. the sequence of the insert from this clone, pisi-2, revealed orfs with sequence similarity to the groes/el operon of escherichia coli, the 505 ribosomal proteins l21 and l27 of e. coli, a gtp-binding protein of bacillus subtilis and a possible protoporphyrinogen oxidase, hemk, of e. coli. primers designed from unique sequences from the pisi-2 insert amplified dna from infected, but not non-infected, porcine ilea; the amplicon sequence obtained from tissue-cultured l. intracellularis was identical to the corresponding sequence in pisi-2, confirming the origin of the clone. the sequence of l. intracellularis groel and other groel sequences in the databases were used to construct a partial phylogenetic tree. analysis of the groel sequence relationship suggested that l.  intracellularis is not significantly related to other organisms whose groel sequences are held in the databases and supports previous data from 16s sequence  analyses suggesting that l. intracellularis is a member of a novel group of enteric pathogens.
TIHT== 
ABHT== 

PMID== 9659692
TI  == detection of lawsonia intracellularis, serpulina hyodysenteriae, weakly beta-haemolytic intestinal spirochaetes, salmonella enterica, and haemolytic escherichia coli from swine herds with and without diarrhoea among growing pigs.
AB  == a polymerase chain reaction (pcr) was optimized to detect lawsonia intracellularis in faeces from naturally infected pigs. by combining a boiling procedure to extract dna and a nested pcr procedure, a detection limit at 2 x 10(2) bacterial cells per gram of faeces was achieved. the optimized pcr was used together with conventional culture techniques to detect serpulina hyodysenteriae, weakly beta-haemolytic intestinal spirochaetes (wbhis), salmonella enterica, and  haemolytic escherichia coli, in a case control study to examine selected risk factors for the development of diarrhoea in growing pigs. herds with diarrhoea were selected as cases and randomly chosen herds without diarrhoea were chosen as controls. infection with l. intracellularis significantly enhanced the chance of  diarrhoea. s. hyodysenteriae, wbhis group iv (serpulina pilosicoli), and s. enterica were isolated only from case herds which indicate that these species may influence the development of diarrhoea. in addition, herd-type had a significant  impact, that is specific pathogen-free herds showed an odds ratio at 0.2 relative to conventional herds for the development of diarrhoea.
TIHT== 
ABHT== 

PMID== 9620403
TI  == proliferative enterocolitis associated with dual infection with enteropathogenic  escherichia coli and lawsonia intracellularis in rabbits.
AB  == both enteropathogenic escherichia coli (epec) and an obligate intracellular bacterium, previously referred to as an intracellular campylobacter-like organism and now designated lawsonia intracellularis, have been reported as causes of enterocolitis in rabbits. an outbreak of enterocolitis in a group of rabbits, characterized by an unusually high rate of mortality, was found to be associated  with dual infection with epec and l. intracellularis. the epec strain was found to have eaea gene homology but was negative for afra homology. the absence of the afra gene, which encodes the structural subunit for the af/r1 pilus, indicates that this rabbit epec strain is distinct from the prototypic rdec-1 strain. this  finding suggests that rabbit epec strains widely reported in western europe, which lack af/r1 pili, are also present in rabbits in the united states. dual infection with these two pathogens in rabbits has not been previously reported and may have contributed to the unusually high mortality observed in this outbreak.
TIHT== 
ABHT== 

PMID== 4199288
TI  == antimicrobial principles in leaves of lawsonia inermis l.
AB  == 
TIHT== 
ABHT== 

PMID== 4967454
TI  == antimicrobial activity of lawsonia inermis l.
AB  == 
TIHT== 
ABHT== 

