@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23082149
TI  == the effect of selected synbiotics on microbial composition and short-chain fatty  acid production in a model system of the human colon.
AB  == background: prebiotics, probiotics and synbiotics can be used to modulate both the composition and activity of the gut microbiota and thereby potentially affecting host health beneficially. the aim of this study was to investigate the  effects of eight synbiotic combinations on the composition and activity of human  fecal microbiota using a four-stage semicontinuous model system of the human colon. methods and findings: carbohydrates were selected by their ability to enhance growth of the probiotic bacteria lactobacillus acidophilus ncfm (ncfm) and bifidobacterium animalis subsp. lactis bl-04 (bl-04) under laboratory conditions. the most effective carbohydrates for each probiotic were further investigated, using the colonic model, for the ability to support growth of the probiotic bacteria, influence the composition of the microbiota and stimulate formation of short-chain fatty acids (scfa).the following combinations were studied: ncfm with isomaltulose, cellobiose, raffinose and an oat beta-glucan hydrolysate (obgh) and bl-04 with melibiose, xylobiose, raffinose and maltotriose. all carbohydrates showed capable of increasing levels of ncfm and bl-04 during fermentations in the colonic model by 10(3)-10(4) fold and 10-10(2)  fold, respectively. also the synbiotic combinations decreased the modified ratio  of bacteroidetes/firmicutes (calculated using qpcr results for bacteroides-prevotella-porphyromonas group, clostridium perfringens cluster i, clostridium coccoides - eubacterium rectale group and clostridial cluster xiv) as well as significantly increasing scfa levels, especially acetic and butyric acid, by three to eight fold, as compared to the controls. the decreases in the modified ratio of bacteroidetes/firmicutes were found to be correlated to increases in acetic and butyric acid (p=0.04 and p=0.03, respectively). conclusions: the results of this study show that all synbiotic combinations investigated are able to shift the predominant bacteria and the production of scfa of fecal microbiota in a model system of the human colon, thereby potentially being able to manipulate the microbiota in a way connected to human health.
TIHT== 
ABHT== 

PMID== 17927751
TI  == effects of yogurt and bifidobacteria supplementation on the colonic microbiota in lactose-intolerant subjects.
AB  == aims: colonic metabolism of lactose may play a role in lactose intolerance. we investigated whether a 2-week supplementation of bifidobacterium longum (in capsules) and a yogurt enriched with bifidobacterium animalis could modify the composition and metabolic activities of the colonic microbiota in 11 chinese lactose-intolerant subjects. methods and results: the numbers of total cells, total bacteria and the eubacterium rectale/clostridium coccoides group in faeces  as measured with fluorescent in situ hybridization and the faecal beta-galactosidase activity increased significantly during supplementation. the number of bifidobacterium showed a tendency to increase during and after supplementation. with pcr-denaturing gradient gel electrophoresis, in subjects in which b. animalis and b. longum were not detected before supplementation, both strains were present in faeces during supplementation, but disappeared after supplementation. the degree of lactose digestion in the small intestine and the oro-caecal transit time were not different before and after supplementation, whereas symptom scores after lactose challenge decreased after supplementation. conclusions: the results suggest that supplementation modifies the amount and metabolic activities of the colonic microbiota and alleviates symptoms in lactose-intolerant subjects. the changes in the colonic microbiota might be among the factors modified by the supplementation which lead to the alleviation of lactose intolerance. significance and impact of the study: this study provides evidence for the possibility of managing lactose intolerance with dietary lactose (yogurt) and probiotics via modulating the colonic microbiota.
TIHT== 
ABHT== 

