@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23613805
TI  == cystic fibrosis transmembrane conductance regulator (cftr) allelic variants relate to shifts in faecal microbiota of cystic fibrosis patients.
AB  == introduction: in this study we investigated the effects of the cystic fibrosis transmembrane conductance regulator (cftr) gene variants on the composition of faecal microbiota, in patients affected by cystic fibrosis (cf). cftr mutations (f508del is the most common) lead to a decreased secretion of chloride/water, and to mucus sticky secretions, in pancreas, respiratory and gastrointestinal tracts. intestinal manifestations are underestimated in cf, leading to ileum meconium at  birth, or small bowel bacterial overgrowth in adult age. methods: thirty-six cf patients, fasting and under no-antibiotic treatment, were cftr genotyped on both  alleles. faecal samples were subjected to molecular microbial profiling through temporal temperature gradient electrophoresis and species-specific pcr. ecological parameters and multivariate algorithms were employed to find out if cftr variants could be related to the microbiota structure. results: patients were classified by two different criteria: 1) presence/absence of f508del mutation; 2) disease severity in heterozygous and homozygous f508del patients. we found that homozygous-f508del and severe cf patients exhibited an enhanced dysbiotic faecal microbiota composition, even within the cf cohort itself, with higher biodiversity and evenness. we also found, by species-specific pcr, that potentially harmful species (escherichia coli and eubacterium biforme) were abundant in homozygous-f508del and severe cf patients, while beneficial species (faecalibacterium prausnitzii, bifidobacterium spp., and eubacterium limosum) were reduced. conclusions: this is the first report that establishes a link among cftr variants and shifts in faecal microbiota, opening the way to studies that perceive cf as a 'systemic disease', linking the lung and the gut in a joined axis.
TIHT== 
ABHT== 

PMID== 11851378
TI  == identification of predominant human and animal anaerobic intestinal bacterial species by terminal restriction fragment patterns (trfps): a rapid, pcr-based method.
AB  == identification of predominant human and animal intestinal tract anaerobes by conventional methods is cumbersome, time-consuming and less sensitive as compared to molecular methods. we have developed a molecular technique to identify most of the abundant intestinal microflora by polyermase chain reaction (pcr) amplification of a 16s rrna gene fragment using a pair of universal pcr primers.  the forward pcr primer was labelled with 6-carboxyfluorescein amino hexy (6-fam)  fluorescent dye to detect the terminal fragment of the pcr products after digestion with restriction enzymes. the pcr products were purified and digested with restriction enzymes and were analysed by capillary electrophoresis using an  automated dna sequencer. the data was analysed with genescan software 2.1. eleven bacteria (eubacterium biforme, e. limosum, peptostreptococcus productus, lactobacillus acidophilus, bacteroides thetaiotaomicron, b. vulgatus, b. distasonis, clostridium clostridiiforme, c. leptum, c. perfringens and escherichia coli) that are predominant in human and animal intestinal tract were  successfully identified by this rapid molecular technique. this protocol is rapid, accurate, sensitive and capable of identifying multiple organisms in a single sample.
TIHT== 
ABHT== 

PMID== 10618251
TI  == quantification of different eubacterium spp. in human fecal samples with species-specific 16s rrna-targeted oligonucleotide probes.
AB  == species-specific 16s rrna-targeted, cy3 (indocarbocyanine)-labeled oligonucleotide probes were designed and validated to quantify different eubacterium species in human fecal samples. probes were directed at eubacterium barkeri, e. biforme, e. contortum, e. cylindroides (two probes), e. dolichum, e.  hadrum, e. lentum, e. limosum, e. moniliforme, and e. ventriosum. the specificity of the probes was tested with the type strains and a range of common intestinal bacteria. with one exception, none of the probes showed cross-hybridization under stringent conditions. the species-specific probes were applied to fecal samples obtained from 12 healthy volunteers. e. biforme, e. cylindroides, e. hadrum, e. lentum, and e. ventriosum could be determined. all other eubacterium species for  which probes had been designed were under the detection limit of 10(7) cells g (dry weight) of feces(-1). the cell counts obtained are essentially in accordance with the literature data, which are based on colony counts. this shows that whole-cell in situ hybridization with species-specific probes is a valuable tool  for the enumeration of eubacterium species in feces.
TIHT== 
ABHT== 

PMID== 8919784
TI  == pcr detection and quantitation of predominant anaerobic bacteria in human and animal fecal samples.
AB  == pcr procedures based on 16s rrna gene sequences specific for 12 anaerobic bacteria that predominate in the human intestinal tract were developed and used for quantitative detection of these species in human (adult and baby) feces and animal (rat, mouse, cat, dog, monkey, and rabbit) feces. fusobacterium prausnitzii, peptostreptococcus productus, and clostridium clostridiiforme had high pcr titers (the maximum dilutions for positive pcr results ranged from 10(-3) to 10(-8)) in all of the human and animal fecal samples tested. bacteroides thetaiotaomicron, bacteroides vulgatus, and eubacterium limosum also  showed higher pcr titers (10(-2) to 10(-6)) in adult human feces. the other bacteria tested, including escherichia coli, bifidobacterium adolescentis, bifidobacterium longum, lactobacillus acidophilus, eubacterium biforme, and bacteroides distasonis, were either at low pcr titers (less than 10(-2)) or not detected by pcr. the reported pcr procedure including the fecal sample preparation method is simplified and rapid and eliminates the dna isolation steps.
TIHT== 
ABHT== 

