@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 24586292
TI  == disrupted intestinal microbiota and intestinal inflammation in children with cystic fibrosis and its restoration with lactobacillus gg: a randomised clinical  trial.
AB  == background & aims: intestinal inflammation is a hallmark of cystic fibrosis (cf). administration of probiotics can reduce intestinal inflammation and the incidence of pulmonary exacerbations. we investigated the composition of intestinal microbiota in children with cf and analyzed its relationship with intestinal inflammation. we also investigated the microflora structure before and after lactobacillus gg (lgg) administration in children with cf with and without antibiotic treatment. methods: the intestinal microbiota were analyzed by denaturing gradient gel electrophoresis (dgge), real-time polymerase chain reaction (rt-pcr), and fluorescence in situ hybridization (fish). intestinal inflammation was assessed by measuring fecal calprotectin (clp) and rectal nitric oxide (rno) production in children with cf as compared with healthy controls. we  then carried out a small double-blind randomized clinical trial with lgg. results: twenty-two children with cf children were enrolled in the study (median  age, 7 years; range, 2-9 years). fecal clp and rno levels were higher in children with cf than in healthy controls (184+/-146 microg/g vs. 52+/-46 microg/g; 18+/-15 vs. 2.6+/-1.2 micromol/l no2 (-), respectively; p<0.01). compared with healthy controls, children with cf had significantly different intestinal microbial core structures. the levels of eubacterium rectale, bacteroides uniformis, bacteroides vulgatus, bifidobacterium adolescentis, bifidobacterium catenulatum, and faecalibacterium prausnitzii were reduced in children with cf. a similar but more extreme pattern was observed in children with cf who were taking antibiotics. lgg administration reduced fecal clp and partially restored intestinal microbiota. there was a significant correlation between reduced microbial richness and intestinal inflammation. conclusions: cf causes qualitative and quantitative changes in intestinal microbiota, which may represent a novel therapeutic target in the treatment of cf. administration of probiotics restored gut microbiota, supporting the efficacy of probiotics in reducing intestinal inflammation and pulmonary exacerbations. trial registration: clinicaltrials.gov nct 01961661.
TIHT== 
ABHT== 

