@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 18385433
TI  == bacterial profiles of root caries in elderly patients.
AB  == culture-based studies have shown that streptococcus mutans and lactobacilli are associated with root caries (rc). the purpose of the present study was to assess  the bacterial diversity of rc in elderly patients by use of culture-independent molecular techniques and to determine the associations of specific bacterial species or bacterial communities with healthy and carious roots. plaque was collected from root surfaces of 10 control subjects with no rc and from 11 subjects with rc. the bacterial 16s rrna genes from extracted dna were pcr amplified, cloned, and sequenced to determine species identity. from a total of 3,544 clones, 245 predominant species or phylotypes were observed, representing eight bacterial phyla. the majority (54%) of the species detected have not yet been cultivated. species of selenomonas and veillonella were common in all samples. the healthy microbiota included fusobacterium nucleatum subsp. polymorphum, leptotrichia spp., selenomonas noxia, streptococcus cristatus, and kingella oralis. lactobacilli were absent, s. mutans was present in one, and actinomyces spp. were present in 50% of the controls. in contrast, the microbiota of the rc subjects was dominated by actinomyces spp., lactobacilli, s. mutans, enterococcus faecalis, selenomonas sp. clone cs002, atopobium and olsenella spp., prevotella multisaccharivorax, pseudoramibacter alactolyticus, and propionibacterium sp. strain fma5. the bacterial profiles of rc showed considerable subject-to-subject variation, indicating that the microbial communities are more complex than previously presumed. the data suggest that putative etiological agents of rc include not only s. mutans, lactobacilli, and actinomyces but also species of atopobium, olsenella, pseudoramibacter, propionibacterium, and selenomonas.
TIHT== 
ABHT== 

PMID== 15695690
TI  == molecular analysis of microbial diversity in advanced caries.
AB  == real-time pcr analysis of the total bacterial load in advanced carious lesions has shown that the total load exceeds the number of cultivable bacteria. this suggests that an unresolved complexity exists in bacteria associated with advanced caries. in this report, the profile of the microflora of carious dentine was explored by using dna extracted from 10 lesions selected on the basis of comparable total microbial load and on the relative abundance of prevotella spp.  using universal primers for the 16s rrna gene, pcr amplicons were cloned, and approximately 100 transformants were processed for each lesion. phylogenetic analysis of 942 edited sequences demonstrated the presence of 75 species or phylotypes in the 10 carious lesions. up to 31 taxa were represented in each sample. a diverse array of lactobacilli were found to comprise 50% of the species, with prevotellae also abundant, comprising 15% of the species. other taxa present in a number of lesions or occurring with high abundance included selenomonas spp., dialister spp., fusobacterium nucleatum, eubacterium spp., members of the lachnospiraceae family, olsenella spp., bifidobacterium spp., propionibacterium sp., and pseudoramibacter alactolyticus. the mechanisms by which such diverse patterns of bacteria extend carious lesions, including the aspect of infection of the vital dental pulp, remain unclear.
TIHT== 
ABHT== 

PMID== 14871191
TI  == gingival crevice microbiota from chinese patients with gingivitis or necrotizing  ulcerative gingivitis.
AB  == the objective of this study was to quantitatively compare the bacterial population structure in plaque from the gingival margin of two groups of 21 chinese patients with gingivitis or necrotizing ulcerative gingivitis (nug). subjects were recruited in four dental clinics in eastern china. samples were quantitatively assessed by immunofluorescence and fluorescent in situ hybridization for taxa known to be associated with periodontal diseases. the analyses showed that the fusiform taxa (fusobacterium nucleatum/fusobacterium periodonticum, leptotrichia buccalis, tannerella forsythensis, and capnocytophaga sp.), campylobacter rectus, prevotella intermedia, prevotella nigrescens, selenomonas sputigena, and treponemes were present in both groups with high prevalence. porphyromonas gingivalis and actinomyces gerencseriae were much more  prevalent in the nug group. quantitatively, most taxa, including p. gingivalis, f. nucleatum and the treponemes, accounted, on average, for < 3% of the total bacterial cell number. only p. intermedia/p. nigrescens, p. gingivalis, s. sputigena, a. gerencseriae, and the sum of all monitored suspected periodontal pathogens were significantly increased in the nug group. the present study demonstrates for both groups a highly diverse plaque composition and suggests that, etiologically, the overall concentration and the concerted effects of the entire group of opportunistic pathogens thriving in nug-associated plaque are of  prime importance.
TIHT== 
ABHT== 

PMID== 12902270
TI  == effects of a chlorhexidine gluconate-containing mouthwash on the vitality and antimicrobial susceptibility of in vitro oral bacterial ecosystems.
AB  == oral bacterial microcosms, established using saliva inocula from three individuals, were maintained under a feast-famine regime within constant-depth film fermenters. steady-state communities were exposed four times daily, postfeeding, to a chlorhexidine (chx) gluconate-containing mouthwash (chxm) diluted to 0.06% (wt/vol) antimicrobial content. the microcosms were characterized by heterotrophic plate counts and pcr-denaturing gradient gel electrophoresis (dgge). chxm caused significant decreases in both total anaerobe  and total aerobe/facultative anaerobe counts (p < 0.05), together with lesser decreases in gram-negative anaerobes. the degree of streptococcal and actinomycete inhibition varied considerably among individuals. dgge showed that chxm exposure caused considerable decreases in microbial diversity, including marked reductions in prevotella sp. and selenomonas infelix. pure-culture studies of 10 oral bacteria (eight genera) showed that actinomyces naeslundii, veillonella dispar, prevotella nigrescens, and the streptococci were highly susceptible to chx, while lactobacillus rhamnosus, fusobacterium nucleatum, and neisseria subflava were the least susceptible. determination of the mics of triclosan, chx, erythromycin, penicillin v, vancomycin, and metronidazole for microcosm isolates, before and after 5 days of chxm exposure, showed that chxm exposure altered the distribution of isolates toward those that were less susceptible to chx (p < 0.05). changes in susceptibility distributions for the other test agents were not statistically significant. in conclusion, population changes in plaque microcosms following repeated exposure to chxm represented an inhibition of the most susceptible flora with a clonal expansion of less susceptible species.
TIHT== 
ABHT== 

PMID== 5370458
TI  == oxygen sensitivity of various anaerobic bacteria.
AB  == anaerobes differ in their sensitivity to oxygen, as two patterns were recognizable in the organisms included in this study. strict anaerobes were species incapable of agar surface growth at po(2) levels greater than 0.5%. species that were found to be strict anaerobes were treponema macrodentium, treponema denticola, treponema oralis n. sp., clostridium haemolyticum, selenomonas ruminatium, butyrivibrio fibrisolvens, succinivibrio dextrinosolvens, and lachnospira multiparus. moderate anaerobes would include those species capable of growth in the presence of oxygen levels as high as 2 to 8%. the moderate anaerobes could be exposed to room atmosphere for 60 to 90 min without appreciable loss of viability. species considered as moderate anaerobes were bacteroides fragilis, b. melaninogenicus, b. oralis, fusobacteria nucleatum, clostridium novyi type a, and peptostreptococcus elsdenii. the recognition of at  least two general types of anaerobes would seem to have practical import in regard to the primary isolation of anaerobes from source material.
TIHT== 
ABHT== 

