@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 9310640
TI  == recently described clinically important anaerobic bacteria: taxonomic aspects and update.
AB  == a new method of identifying bacteria, phylogenetic 16s rrna sequencing, has led to major reorganizations among most genera of anaerobic bacteria. the pigmented prevotella species now comprise seven species including p. nigrescens and p. tannerae; p. intermedia/p. nigrescens-like organisms await inclusion. the former  mitsuokella dentalis and hallella seregens were transferred to prevotella as one  species, p. dentalis. p. enoeca is a new nonpigmenting prevotella. the genus porphyromonas currently includes 11 pigmented species and one nonpigmented species, p. catoniae; p. levii-like and p. endodontalis-like organisms are candidates for the genus. fusobacterium nucleatum currently has five subspecies,  and f. varium includes the former f. pseudonecrophorum. former wolinella recta and wolinella curva now are campylobacter rectus and campylobacter curvus; campylobacter showae is a new species. isolates included in the bile-sensitive former bacteroides gracilis now are campylobacter gracilis; the bile-resistant b. gracilis isolates were transferred to a new genus, sutterella, as s. wadsworthensis. the new actinomyces species include two subspecies of the a. neuii and the a. radingae-a. turicensis complex. the genus eubacterium sensu stricto is represented by e. limosum, and the former e. alactolyticum was reclassified in a new genus, pseudoramibacter, as p. alactolyticus. recent entries include e. saphenum, e. minutum, e. exiguum, e. infirmum, and e. tardum.  a new genus, atopobium houses some former lactobacilli and streptococci. the genus peptostreptococcus also have four new species; p. hydrogenalis, p. lacrimalis, p. lactolyticus, and p. vaginalis.
TIHT== 
ABHT== 

PMID== 1398963
TI  == identification of proteases from periodontopathogenic bacteria as activators of latent human neutrophil and fibroblast-type interstitial collagenases.
AB  == activation of latent human fibroblast-type and neutrophil interstitial procollagenases as well as degradation of native type i collagen by supra- and subgingival dental plaque extracts, an 80-kda trypsinlike protease from porphyromas gingivalis (atcc 33277), a 95-kda chymotrypsinlike protease from treponema denticola (atcc 29522), and selected bacterial species commonly isolated in periodontitis was studied. the bacteria included were prevotella intermedia (atcc 25261), prevotella buccae (es 57), prevotella oris (atcc 33573), porphyromonas endodontalis (es 54b), actinobacillus actinomycetemcomitans (atcc 295222), fusobacterium nucleatum (atcc 10953), mitsuokella dentalis (dsm 3688), and streptococcus mitis (atcc 15909). none of the bacteria activated latent procollagenases; however, both sub- and supragingival dental plaque extracts (neutral salt extraction) and proteases isolated from cell extracts from potentially periodontopathogenic bacteria p. gingivalis and t. denticola were found to activate latent human fibroblast-type and neutrophil interstitial procollagenases. the fibroblast-type interstitial collagenase was more efficiently activated by bacterial proteases than the neutrophil counterpart, which instead preferred nonproteolytic activation by the oxidative agent hypochlorous acid. the proteases were not able to convert collagenase tissue inhibitor of metalloproteinase (timp-1) complexes into active form or to change the ability of timp-1 to inhibit interstitial collagenase. none of the studied bacteria, proteases from p. gingivalis and t. denticola, or extracts of supra- and subgingival dental plaque showed any significant collagenolytic activity. however, the proteases degraded native and denatured collagen fragments after cleavage by interstitial collagenase and gelatinase. our results indicate that proteases from periodontopathogenic bacteria can act as direct proteolytic activators of human procollagenases and degrade collagen fragments. thus, in concert with host enzymes the bacterial proteases may participate in periodontal  tissue destruction.
TIHT== 
ABHT== 

