@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25847068
TI  == occurrence of periodontal pathogens in ethnic groups from a native brazilian reservation.
AB  == objective: the present study was designed to evaluate the occurrence of periodontal pathogens in the subgingival biofilm of 100 native brazilians living  at the umutina indian reservation, mato grosso state, brazil. methods: periodontal clinical examinations were carried out prior to collection of subgingival biofilm, and the presence of 14 periodontal microorganisms was evaluated by polymerase chain reaction (pcr). the prevalence and risk analysis was performed using cochran and mantel-haenszel statistics for dichotomous variables or pearson's chi-squared test for analysis of proportions when variables had three or more categories. the interrelations between clinical and microbiological parameters were assessed using fisher's exact test and the mann-whitney u test. results: individuals with chronic periodontitis were frequently colonized by the association between porphyromonas gingivalis and campylobacter rectus, p. gingivalis and prevotella intermedia, or p. gingivalis and tannerella forsythia. patients with chronic periodontitis were also colonized by porphyromonas gulae and p. intermedia or by the association between p. gulae and t. forsythia. p. gulae was detected only in the subgingival samples from natives on a traditional diet. gingival bleeding was associated with aggregatibacter actinomycetemcomitans, fusobacterium nucleatum, t. forsythia, p.  gingivalis, p. gulae, porphyromonas endodontalis, p. intermedia, and prevotella nigrescens. treponema denticola was uncommon. conclusions: peculiar microbiota was demonstrated to be associated with different periodontal disease statuses in  native brazilians, with modest occurrence of certain pathogens, such as t. denticola, and the presence of p. gulae in natives with gingivitis or chronic periodontitis.
TIHT== 
ABHT== 

PMID== 25280920
TI  == hydrogen sulfide production from subgingival plaque samples.
AB  == periodontitis is a polymicrobial anaerobe infection. little is known about the dysbiotic microbiota and the role of bacterial metabolites in the disease process. it is suggested that the production of certain waste products in the proteolytic metabolism may work as markers for disease severity. hydrogen sulfide (h2s) is a gas produced by degradation of proteins in the subgingival pocket. it  is highly toxic and believed to have pro-inflammatory properties. we aimed to study h2s production from subgingival plaque samples in relation to disease severity in subjects with natural development of the disease, using a colorimetric method based on bismuth precipitation. in remote areas of northern thailand, adults with poor oral hygiene habits and a natural development of periodontal disease were examined for their oral health status. h2s production was measured with the bismuth method and subgingival plaque samples were analyzed for the presence of 20 bacterial species with the checkerboard dna-dna hybridization technique. in total, 43 subjects were examined (age 40-60 years, mean pi 95 +/- 6.6%). fifty-six percent had moderate periodontal breakdown (cal > 3 < 7 mm) and 35% had severe periodontal breakdown (cal > 7 mm) on at least one site. parvimonas micra, filifactor alocis, porphyromonas endodontalis and fusobacterium nucleatum were frequently detected. h2s production could not be correlated to periodontal disease severity (ppd or cal at sampled sites) or to a  specific bacterial composition. site 21 had statistically lower production of h2s (p = 0.02) compared to 16 and 46. betel nut chewers had statistically significant lower h2s production (p = 0.01) than non-chewers. rapid detection and estimation  of subgingival h2s production capacity was easily and reliably tested by the colorimetric bismuth sulfide precipitation method. h2s may be a valuable clinical marker for degradation of proteins in the subgingival pocket.
TIHT== 
ABHT== 

PMID== 25139407
TI  == microbial signature profiles of periodontally healthy and diseased patients.
AB  == aim: to determine microbial profiles that discriminate periodontal health from different forms of periodontal diseases. methods: subgingival biofilm was obtained from patients with periodontal health (27), gingivitis (11), chronic periodontitis (35) and aggressive periodontitis (24), and analysed for the presence of >250 species/phylotypes using homim. microbial differences among groups were examined by mann-whitney u-test. regression analyses were performed to determine microbial risk indicators of disease. results: putative and potential new periodontal pathogens were more prevalent in subjects with periodontal diseases than periodontal health. detection of porphyromonas endodontalis/porphyromonas spp. (or 9.5 [1.2-73.1]) and tannerella forsythia (or  38.2 [3.2-450.6]), and absence of neisseria polysaccharea (or 0.004 [0-0.15]) and prevotella denticola (or 0.014 [0-0.49], p < 0.05) were risk indicators of periodontal disease. presence of aggregatibacter actinomycetemcomitans (or 29.4 [3.4-176.5]), cardiobacterium hominis (or 14.9 [2.3-98.7]), peptostreptococcaceae sp. (or 35.9 [2.7-483.9]), p. alactolyticus (or 31.3 [2.1-477.2]), and absence of fretibacterium spp. (or 0.024 [0.002-0.357]), fusobacterium naviforme/fusobacterium nucleatum ss vincentii (or 0.015 [0.001-0.223]), granulicatella adiacens/granulicatella elegans (or 0.013 [0.001-0.233], p < 0.05) were associated with aggressive periodontitis. conclusion: there were specific microbial signatures of the subgingival biofilm that were able to distinguish between microbiomes of periodontal health and diseases. such profiles may be used to establish risk of disease.
TIHT== 
ABHT== 

PMID== 24918364
TI  == effects of stress hormones on the production of volatile sulfur compounds by periodontopathogenic bacteria.
AB  == little is known about the effects of stress hormones on the etiologic agents of halitosis. thus, the aim of this study was to evaluate in vitro the effects of adrenaline (adr), noradrenaline (na) and cortisol (cort) on bacteria that produce volatile sulfur compounds (vsc), the major gases responsible for bad breath. cultures of fusobacterium nucleatum (fn), porphyromonas endodontalis (pe), prevotella intermedia (pi) and porphyromonas gingivalis (pg) were exposed to 50 microm adr, na and cort or equivalent volumes of sterile water as controls for 12 and 24 h. growth was evaluated based on absorbance at 660 nm. portable gas chromatography was used to measure vsc concentrations. kruskal-wallis and the dunn post-hoc test were used to compare the groups. for fn, adr, na and cort significantly reduced bacterial growth after 12 h and 24 h (p<0.05). all the substances tested increased hydrogen sulfide (h2s) production (p<0.05). for pe, all the substances tested reduced bacterial development after 24 h (p<0.05), and  na significantly increased the h2s concentration after 12 h (p<0.05). in the pg and pi cultures, no effects on bacterial growth were observed (p>0.05). in the pi cultures, adr, na and cort increased h2s (p<0.05). catecholamines and cortisol can interfere with growth and h2s production of sub-gingival species in vitro. this process appears to be complex and supports the association between stress and the production of vsc.
TIHT== 
ABHT== 

PMID== 24862703
TI  == microbial evaluation of traumatized teeth treated with triple antibiotic paste or calcium hydroxide with 2% chlorhexidine gel in pulp revascularization.
AB  == introduction: revascularization outcome depends on microbial elimination because  apical repair will not happen in the presence of infected tissues. this study evaluated the microbial composition of traumatized immature teeth and assessed their reduction during different stages of the revascularization procedures performed with 2 intracanal medicaments. methods: fifteen patients (7-17 years old) with immature teeth were submitted to the revascularization procedures; they were divided into 2 groups according to the intracanal medicament used: tap group (n = 7), medicated with a triple antibiotic paste, and chp group (n = 8), dressed with calcium hydroxide + 2% chlorhexidine gel. samples were taken before any treatment (s1), after irrigation with 6% naocl (s2), after irrigation with 2% chlorhexidine (s3), after intracanal dressing (s4), and after 17% edta irrigation (s5). cultivable bacteria recovered from the 5 stages were counted and identified by means of polymerase chain reaction assay (16s rrna). results: both groups had  colony-forming unit counts significantly reduced after s2 (p < .05); however, no  significant difference was found between the irrigants (s2 and s3, p = .99). no difference in bacteria counts was found between the intracanal medicaments used (p = .95). the most prevalent bacteria detected were actinomyces naeslundii (66.67%), followed by porphyromonas endodontalis, parvimonas micra, and fusobacterium nucleatum, which were detected in 33.34% of the root canals. an average of 2.13 species per canal was found, and no statistical correlation was observed between bacterial species and clinical/radiographic features. conclusions: the microbial profile of infected immature teeth is similar to that  of primarily infected permanent teeth. the greatest bacterial reduction was promoted by the irrigation solutions. the revascularization protocols that used the tested intracanal medicaments were efficient in reducing viable bacteria in necrotic immature teeth.
TIHT== 
ABHT== 

PMID== 24666896
TI  == signaling pathways activation by primary endodontic infectious contents and production of inflammatory mediators.
AB  == introduction: this study investigated the bacterial community involved in primary endodontic diseases, evaluated its ability to activate the macrophage toll-like receptor 4 receptor through p38 mitogen-activated protein kinase (mapk) and nuclear factor kappa b (nf-kappab) signaling pathways, and determined the levels  of endotoxins and interleukins (interleukin [il]-6 and -10) produced by endodontic content-stimulated macrophages. methods: samples were taken from 21 root canals by using sterile/apyrogenic paper points. raw 264.7 macrophages were  stimulated with root canal contents. checkerboard dna-dna hybridization was used  for bacterial analysis and the limulus amebocyte lysate assay for endotoxin measurement; p38 mapk and nf-kappab activation was determined by western blot analysis. il-6 and il-10 were measured using the enzyme-linked immunosorbent assay. results: bacteria and endotoxins were detected in 100% of the samples (21/21). the most frequently observed species were parvimonas micra (16/21, 76%), fusobacterium nucleatum ssp. nucleatum (15/21, 71%), and porphyromonas endodontalis (14/21, 66%). correlations were found between endotoxins and il-6 and il-10 (p < .05); p38 phosphorylation had a peak at 60 minutes, and nf-kappab  was quickly activated after 10 minutes of stimulation. conclusions: it was concluded that the complex bacterial community was shown to be a potent activator of tlr-4 determined by the p38 mapk and nf-kappab signaling pathways, culminating in a high antigenicity against macrophages through the levels of il-6 and il-10,  all significantly affected by endotoxin levels.
TIHT== 
ABHT== 

PMID== 23538426
TI  == an investigation of the presence of specific anaerobic species in necrotic primary teeth.
AB  == different microbial identification methods have shown that the microbial community profiles in endodontic infections are diverse and assorted. the aim of  this study was to evaluate the frequency of selected endodontic pathogens in the  pulp chambers (pcs) and root canals (rcs) of infected primary teeth using pcr methods. paired pc and rc samples were collected from 15 subjects and analyzed by pcr for the presence of filifactor alocis, fusobacterium nucleatum, parvimonas micra, porphyromonas endodontalis, porphyromonas gingivalis, prevotella intermedia, prevotella nigrescens, prevotella tannerae, tanerella forsythia, treponema denticola, and treponema socranskii. the frequency of each species was  determined in the pc and rc of each case. the species most frequently detected in pcs were p. nigrescens (86.7%), p. gingivalis (73.3%), and f. alocis (73.3%). of  the pc samples, 13.3% contained p. micra and t. denticola, and 6.7% contained t.  forsythia. the species most frequently detected in rcs were p. gingivalis (100%)  and p. nigrescens (93.3%). p. tannerae, p. micra, and t. denticola were found in  40% of the rc samples; t. forsythia was found in 26.7% of the rc samples. the "red complex", which comprises p. gingivalis, t. denticola, and t. forsythia, was not found in the pc of any tooth but was found in 30% of the rc samples. the detection of p. nigrescens in the pc was statistically associated with the presence of p. nigrescens in the rc (p = 0.04). the results suggest high heterogeneity among the samples, even among those from the same subject.
TIHT== 
ABHT== 

PMID== 22794210
TI  == comparison of endotoxin levels found in primary and secondary endodontic infections.
AB  == introduction: this clinical study was conducted to compare the levels of endotoxins (lipopolysaccharides [lpss]) found in primary and secondary endodontic infections with apical periodontitis by correlating lps contents with clinical/radiographic findings. in addition, the presence of target gram-negative anaerobic bacteria was also investigated. methods: samples were taken from 15 root canals with primary infections and 15 with secondary infections by using paper points. the limulus amebocyte lysate assay was used to quantify endotoxins, and the polymerase chain reaction technique (16s rdna) was used for bacterial investigation. results: endotoxins were detected in 100% of the root canal samples collected from primary (15/15) and secondary (15/15) infections with median values of 7.49 eu/ml and 3.96 eu/ml, respectively (p < .05). the median value of endotoxins found in the presence of clinical symptoms was significantly  higher than in asymptomatic teeth with primary infections (p < .05). a positive correlation was found between endotoxin contents and a larger size of the radiolucent area (>3 mm) (p < .05). prevotella nigrescens (10/15, 4/15), fusobacterium nucleatum (5/15, 1/15), treponema denticola (3/15, 1/15), and treponema socranskii (5/15, 1/15) were detected in teeth with primary and secondary infections, respectively. p. endodontalis was present only in teeth with primary infections (5/15). conclusions: teeth with primary endodontic infections had higher contents of endotoxins and a more complex gram-negative bacterial community than teeth with secondary infections. moreover, the levels of endotoxins were related to the severity of bone destruction in periapical tissues as well as the development of clinical features in teeth with primary infections.
TIHT== 
ABHT== 

PMID== 22703649
TI  == a microbiological profile of unexposed and exposed pulp space of primary endodontic infections by checkerboard dna-dna hybridization.
AB  == introduction: the aim of this study was to evaluate, by checkerboard dna-dna hybridization, the composition of the microbiota of primary endodontic infections in cases associated with exposed (n = 30) and unexposed (n = 30) pulp space. methods: samples were collected by means of a #15 h-type file and 2 sterile paper points from 60 single-rooted teeth with necrotic pulp and periapical lesions. the presence, levels, and proportions of 40 bacterial species were determined by checkerboard dna-dna hybridization. results: the species found in higher counts (x10(5)) in exposed pulp space cases were eubacterium saburreum, fusobacterium nucleatum ssp. vincentii, tannerella forsythia, enterococcus faecalis, neisseria  mucosa, campylobacter gracilis, and prevotella nigrescens, and in unexposed pulp  space cases they were f. nucleatum ssp. vincentii, n. mucosa, e. faecalis, e. saburreum, c. gracilis, and porphyromonas gingivalis. counts of f. nucleatum ssp. vincentii, campylobacter sputigena, capnocytophaga showae, treponema socrenskii,  porphyromonas endodontalis, eikenella corrodens, and capnocytophaga ochracea were significantly higher in unexposed pulp space cases (p < .05). conclusions: the data of the present investigation suggested specific differences between the composition of the microbiota in cases with exposed and unexposed pulp space and  an association between higher levels of some specific species and unexposed pulp  space cases.
TIHT== 
ABHT== 

PMID== 22326171
TI  == molecular analysis of 16s rrna genes identifies potentially periodontal pathogenic bacteria and archaea in the plaque of partially erupted third molars.
AB  == purpose: small subunit rrna sequencing and phylogenetic analysis were used to identify cultivable and uncultivable microorganisms present in the dental plaque  of symptomatic and asymptomatic partially erupted third molars to determine the prevalence of putative periodontal pathogens in pericoronal sites. materials and  methods: template dna prepared from subgingival plaque collected from partially erupted symptomatic and asymptomatic mandibular third molars and healthy incisors was used in polymerase chain reaction with broad-range oligonucleotide primers to amplify 16s rrna bacterial and archaeal genes. amplicons were cloned, sequenced,  and compared with known nucleotide sequences in online databases to identify the  microorganisms present. results: two thousand three hundred two clones from the plaque of 12 patients carried bacterial sequences from 63 genera belonging to 11  phyla, including members of the uncultivable tm7, sr1, and chloroflexi, and difficult-to-cultivate synergistetes and spirochaetes. dialister invisus, filifactor alocis, fusobacterium nucleatum, porphyromonas endodontalis, prevotella denticola, tannerella forsythia, and treponema denticola, which have been associated with periodontal disease, were found in significantly greater abundance in pericoronal compared with incisor sites. dialister invisus and f nucleatum were found in greater abundance in sites exhibiting clinical symptoms.  the archaeal species, methanobrevibacter oralis, which has been associated with severe periodontitis, was found in 3 symptomatic patients. conclusions: these findings have provided new insights into the complex microbiota of pericoronitis. several bacterial and archaeal species implicated in periodontal disease were recovered in greater incidence and abundance from the plaque of partially erupted third molars compared with incisors, supporting the hypothesis that the pericoronal region may provide a favored niche for periodontal pathogens in otherwise healthy mouths.
TIHT== 
ABHT== 

PMID== 22244629
TI  == clustering behavior in microbial communities from acute endodontic infections.
AB  == introduction: acute endodontic infections harbor heterogeneous microbial communities in both the root canal (rc) system and apical tissues. data comparing the microbial structure and diversity in endodontic infections in related ecosystems, such as rc with necrotic pulp and acute apical abscess (aaa), are scarce in the literature. the aim of this study was to examine the presence of selected endodontic pathogens in paired samples from necrotic rc and aaa using polymerase chain reaction (pcr) followed by the construction of cluster profiles. methods: paired samples of rc and aaa exudates were collected from 20 subjects and analyzed by pcr for the presence of selected strict and facultative anaerobic strains. the frequency of species was compared between the rc and the aaa samples. a stringent neighboring clustering algorithm was applied to investigate  the existence of similar high-order groups of samples. a dendrogram was constructed to show the arrangement of the sample groups produced by the hierarchical clustering. results: all samples harbored bacterial dna. porphyromonas endodontalis, prevotella nigrescens, filifactor alocis, and tannerela forsythia were frequently detected in both rc and aaa samples. the selected anaerobic species were distributed in diverse small bacteria consortia.  the samples of rc and aaa that presented at least one of the targeted microorganisms were grouped in small clusters. conclusions: anaerobic species were frequently detected in acute endodontic infections and heterogeneous microbial communities with low clustering behavior were observed in paired samples of rc and aaa.
TIHT== 
ABHT== 

PMID== 22181039
TI  == predominant bacterial species in subgingival plaque in dogs.
AB  == background and objective: the dog has been used extensively for experimental and  microbiological studies on periodontitis and peri-implantitis without detailed knowledge about the predominant flora of the subgingival plaque. this study was designed to evaluate the predominant cultivable bacterial species in dogs and compare them phenotypically and genotypically with corresponding human species. material and methods: four subgingival samples were taken from two upper premolars in each of six labrador retrievers. the samples from each dog were processed for anaerobic culture. from the samples of each dog, the five or six predominating bacteria based on colony morphology were selected and pure cultured. each of the strains was characterized by gram stain, anaerobic/aerobic  growth and api-zym test. eighteen strains showing clear-cut phenotypic differences were further classified based on dna sequencing technology. cross-reactions of dna probes from human and dog strains were also tested against a panel of both human and dog bacterial species. results: thirty-one strains in the dogs were isolated and characterized. they represented 21 different species,  of which six belonged to the genus porphyromonas. no species was found consistently in the predominant flora of all six dogs. porphyromonas crevioricanis and fusobacterium canifelinum were the two most prevalent species in predominant flora in dogs. dna probes from human and dog species cross-reacted to some extent with related strains from humans and dogs; however, distinct exceptions were found. conclusion: the predominant cultural subgingival flora in  dogs shows great similarities with the subgingival bacteria from humans at the genus level, but distinct differences at the species level; however, a genetic relatedness could be disclosed for most strains investigated.
TIHT== 
ABHT== 

PMID== 21846535
TI  == analysis of symptomatic and asymptomatic primary root canal infections in adult norwegian patients.
AB  == introduction: this molecular study analyzed the microbiota of primary root canal  infections from adult norwegian patients. methods: samples were taken from the necrotic root canals of teeth with symptomatic (n = 13) or asymptomatic (n = 21)  apical periodontitis and chronic apical abscesses (n = 9). dna was extracted from samples, and bacterial identifications were performed by a closed-ended reverse-capture checkerboard approach targeting 50 candidate endodontic pathogens. results: bacterial dna was detected in all cases. in teeth with asymptomatic apical periodontitis, the most frequent taxa were dialister invisus  (71%), fusobacterium nucleatum (62%), and porphyromonas endodontalis (62%). in chronic apical abscesses, the most prevalent taxa were p. endodontalis (100%), d. invisus (89%), parvimonas micra (78%), and solobacterium moorei (78%). in teeth with symptomatic apical periodontitis, the most prevalent taxa were d. invisus, p. endodontalis, s. moorei, propionibacterium acnes, and streptococcus species (all in 69%). none of the targeted taxa were significantly associated with either sinus tract or pain (p > .05), except for selenomonas sputigena, which was more frequently found in painful cases (p = .04). no taxa were found in significantly  higher levels in any conditions (p > .05). cluster analyses revealed bacterial groupings that differed between cases with and without pain. conclusions: although basically the same species were highly prevalent in the different conditions examined and none of the most prevalent taxa were positively associated with symptoms, results revealed that species formed different partnerships and associations in samples from teeth with or without pain. therefore, it is possible that more virulent multispecies communities can form as a result of overall bacterial combinations and give rise to acute inflammation.
TIHT== 
ABHT== 

PMID== 21496656
TI  == antigenicity of primary endodontic infection against macrophages by the levels of pge(2) production.
AB  == introduction: root canal contents are potent stimuli for proinflammatory cytokines involved in apical periodontitis. this study investigated target gram-negative bacterial species and endotoxins in primary endodontic infection with apical periodontitis, determined their antigenicity against macrophages through the levels of pge(2), and evaluated their relationship with clinical findings. methods: samples were taken from 21 root canals with primary infection  and apical periodontitis by using paper points. polymerase chain reaction (16s rdna) was used for bacterial detection and limulus amebocyte lysate assay for endotoxin measurement. levels of prostaglandin e2 (pge(2)) were measured by enzyme-linked immunosorbent assay (duoset kit; r&d, minneapolis, mn). results: prevotella nigrescens (13/21), fusobacterium nucleatum (6/21), and porphyromonas  endodontalis (6/21) were the most frequently observed species. a positive association was found between f. nucleatum and p. endodontalis (p < .05). a correlation was found between the number of gram-negative bacterial species and the levels of endotoxins, such as pge(2) (p < .05). higher levels of endotoxin were detected in teeth with exudation, whereas elevated levels of pge(2) were found in teeth with tenderness to percussion and pain on palpation. conclusions:  our findings imply an additive effect between the number of gram-negative bacterial species involved in endodontic infection regarding the induction of proinflammatory cytokine by macrophage cells. moreover, teeth with clinical symptomatology were related to higher levels of endotoxins and pge(2) secretion.
TIHT== 
ABHT== 

PMID== 20850664
TI  == apical root canal microbiota as determined by reverse-capture checkerboard analysis of cryogenically ground root samples from teeth with apical periodontitis.
AB  == introduction: bacteria located in the apical root canal system potentially participate in the pathogenesis of apical periodontitis. detection and identification of apical bacteria can be compromised because of limitations in conventional sampling and identification procedures. this study identified several bacterial taxa in the apical and middle/coronal segments of primarily infected root canal system by using pulverized root segments and a culture-independent molecular method. methods: seventeen extracted teeth with attached apical periodontitis lesions were sectioned to obtain 2 root fragments (apical and middle/coronal segments). root fragments were cryogenically ground, and dna was extracted from samples. after multiple displacement amplification, dna from samples was used as template in a reverse-capture checkerboard hybridization assay targeting 28 bacterial taxa. results: bacterial dna was detected in all samples. the most prevalent taxa in the apical root canal system  were olsenella uli (76.5%), prevotella baroniae (71%), porphyromonas endodontalis (65%), fusobacterium nucleatum (53%), and tannerella forsythia (47%). o. uli, p.  endodontalis, and propionibacterium acnes were as frequently detected in apical samples as they were in middle/coronal samples. p. baroniae, t. forsythia, and f. nucleatum were found more frequently in the apical part of the canal as compared  with matched coronal segments. streptococcus species were more prevalent in middle/coronal samples. the median and mean of shared bacterial taxa between matched apical and middle/coronal segments were 27% and 41%, respectively. conclusions: several candidate endodontic pathogens were very prevalent in the apical root canal system. the apical microbiota was usually complex and differed  in species composition when compared with the microbiota of middle/coronal samples from the same tooth.
TIHT== 
ABHT== 

PMID== 20392909
TI  == detection of a mixed infection in a culture-negative brain abscess by broad-spectrum bacterial 16s rrna gene pcr.
AB  == we describe the identification of two bacterial pathogens from a culture-negative brain abscess by the use of broad-spectrum 16s rrna gene pcr. simultaneous detection of fusobacterium nucleatum and porphyromonas endodontalis was possible  due to a 24-bp length difference of their partially amplified 16s rrna genes, which allowed separation by high-resolution polyacrylamide gel electrophoresis.
TIHT== 
ABHT== 

PMID== 19912382
TI  == sonic extracts from a bacterium related to periapical disease activate gelatinase a and inactivate tissue inhibitor of metalloproteinases timp-1 and timp-2.
AB  == aim: to examine the effects of sonicated bacterial extracts (sbes) from three related to periapical disease bacteria (porphyromonas gingivalis, p. endodontalis and f. nucleatum) on the activation of matrix metalloproteinase (mmp-2) and the inactivation of tissue inhibitors of metalloproteinase (timp-1 and timp-2). methodology: each sbe was added to cultures of human periodontal ligament (pl) cells or ht1080 cells and their supernatants were analysed by zymography for mmp-2. each sbe was added to pl cell cultures, and the amount of timp-1 was determined by elisa. p. gingivalis sbe was incubated with ht1080 cell culture supernatants, and the amounts of timp-1 and timp-2 were determined by elisa. statistical analysis was performed with the paired student's t-test. results: in  extracts of pl cells that had been incubated in the presence of p. gingivalis sbe, one representing pro-mmp-2 (72 kda) and a band corresponding to the active mmp-2 (66 kda) were observed; but in the other extracts it was not detected. when ht1080 cells were treated with p. gingivalis sbe, the pro-mmps was processed into 86- and 66-kda fragments, but in the other extracts, the processing did not occur when the other sbes were used. when pl cells were incubated with the same sbes, the amount of timp-1 was markedly decreased (p < 0.01), but in the other extracts, it was not. the amounts of both timp-1 and timp-2 were decreased in a dose-dependent manner when ht1080 cell culture supernatant was incubated with p.  gingivalis sbe. conclusions: these findings suggest that p. gingivalis sbe may cause connective tissue to be destroyed, contributing to the process of periapical disease, by activating pro-mmp-2 as well as by inactivating timp-1 and timp-2.
TIHT== 
ABHT== 

PMID== 19426923
TI  == bacteria in the apical root canal of teeth with primary apical periodontitis.
AB  == objective: bacteria settled in the apical root canal are in a privileged position to inflict damage to the periradicular tissues. therefore, the species identified in this region can be of special relevance for the pathogenesis of apical periodontitis. this study investigated the occurrence and levels of several bacterial taxa in the apical root canal of teeth with apical periodontitis. study design: dna extracts from samples taken from the apical part of the root canal of extracted teeth evincing chronic apical periodontitis lesions served as templates for analysis of the presence and levels of 28 bacterial species/phylotypes using  a 16s ribosomal rna gene-based reverse-capture checkerboard hybridization assay.  results: bacterial dna was detected in 19 out of 20 samples. detected taxa included pseudoramibacter alactolyticus (32%), bacteroidetes clone x083 (26%), streptococcus species (21%), olsenella uli (10.5%), synergistes clone ba121 (10.5%), fusobacterium nucleatum (10.5%), porphyromonas endodontalis (10.5%), dialister clone bs016 (5%), filifactor alocis (5%), parvimonas micra (5%), and treponema denticola (5%). of these, only bacteroidetes clone x083 and synergistes clone ba121 were found at levels above 10(5). conclusion: occurrence of these bacterial taxa in the apical part of infected root canals indicates their potential pathogenetic role in the etiology of apical periodontitis.
TIHT== 
ABHT== 

PMID== 19405829
TI  == the impact of the stone age diet on gingival conditions in the absence of oral hygiene.
AB  == background: the objective of this study was to assess the oral microbiota and clinical data in subjects without access to traditional oral hygiene methods and  who ate a diet available in the stone age. methods: ten subjects living in an environment replicating the stone age for 4 weeks were enrolled in this study. bleeding on probing (bop), gingival and plaque indices, and probing depth (pd) were assessed at baseline and at 4 weeks. microbiologic samples were collected at the mesio-buccal subgingival aspects of all teeth and from the dorsum of the tongue and were processed by checkerboard dna-dna hybridization methods. results: no subject had periodontitis. mean bop decreased from 34.8% to 12.6% (p <0.001).  mean gingival index scores changed from 0.38 to 0.43 (not statistically significant) and mean plaque scores increased from 0.68 to 1.47 (p <0.001). pd at sites of subgingival sampling decreased (mean difference: 0.2 mm; p <0.001). at week 4, the total bacterial count was higher (p <0.001) for 24 of 74 species, including bacteroides ureolyticus, eikenella corrodens, lactobacillus acidophilus, capnocytophaga ochracea, escherichia coli, fusobacterium nucleatum naviforme, haemophilus influenzae, helicobacter pylori, porphyromonas endodontalis, staphylococcus aureus (two strains), streptococcus agalactiae, streptococcus anginosis, and streptococcus mitis. bacterial counts from tongue samples were higher at baseline (p <0.001) for 20 species, including tannerella forsythia (previously t. forsythensis), aggregatibacter actinomycetemcomitans (previously actinobacillus actinomycetemcomitans; serotype a), and streptococcus  spp. conclusions: the experimental gingivitis protocol is not applicable if the diet (e.g., stone age) does not include refined sugars. although plaque levels increased, bop and pd decreased. subgingival bacterial counts increased for several species not linked to periodontitis, whereas tongue bacterial samples decreased during the study period.
TIHT== 
ABHT== 

PMID== 19131319
TI  == the microbiota of acute apical abscesses.
AB  == as the breadth of bacterial diversity in the oral cavity has been deciphered by molecular studies, several newly identified species/phylotypes have emerged as potential pathogens. we hypothesized that many of these species/phylotypes could  also be involved with the etiology of endodontic abscesses. abscess aspirates from 42 persons were analyzed for the presence of 81 species/phylotypes by means  of a reverse-capture checkerboard hybridization assay. associations between the most frequently detected taxa were calculated. the most prevalent taxa were fusobacterium nucleatum, parvimonas micra, and porphyromonas endodontalis. other  frequently found taxa included olsenella uli, streptococci, eikenella corrodens,  some as-yet-uncultivated phylotypes (bacteroidetes clone x083 and synergistes clone ba121), and newly named species (prevotella baroniae and dialister invisus). several positive bacterial associations were disclosed. findings not only strengthen the association of many cultivable species with abscesses, but also include some newly named species and uncultivated phylotypes in the set of candidate pathogens associated with this disease.
TIHT== 
ABHT== 

PMID== 18793361
TI  == molecular identification and quantification of bacteria from endodontic infections using real-time polymerase chain reaction.
AB  == introduction: it was the aim of the present study to evaluate root canal samples  for the presence and numbers of specific species as well as for total bacterial load in teeth with chronic apical periodontitis using quantitative real-time polymerase chain reaction (pcr). methods: forty adult patients with one radiographically documented periapical lesion were included. twenty teeth presented with primary infections and 20 with secondary infections, requiring retreatment. after removal of necrotic pulp tissue or root canal filling, a first bacterial sample was obtained. following chemo-mechanical root canal preparation  a second sample was taken and a third sample was obtained after 14 days of intracanal dressing with calcium hydroxide. analysis by real-time pcr enabled the quantification of total bacterial counts and of nine selected species. results: root canals with primary infections harbored significantly more bacteria (by total bacterial count) than teeth with secondary infections (p < 0.05). mean total bacterial count in the retreatment group was 2.1 x 10(6) and was significantly reduced following root canal preparation (3.6 x 10(4)) and intracanal dressing (1.4 x 10(5)). corresponding values for primary infections were: 4.6 x 10(7), 3.6 x 10(4), and 6.9 x 10(4). the numbers of the selected bacteria and their detection frequency were also significantly reduced. conclusion: root canals with primary infections contained a higher bacterial load. chemo-mechanical root canal preparation reduced bacterial counts by at least 95%.
TIHT== 
ABHT== 

PMID== 18547832
TI  == pcr-based identification of selected pathogens associated with endodontic infections in deciduous and permanent teeth.
AB  == objective: the aim of the present study was to evaluate the presence of the selected pathogens in samples from deciduous and permanent tooth root canals by using pcr method and to determine the association of these organisms with clinical symptoms. study design: a total of 145 children, 5 to 13 years old, were involved in this study. the presence of selected pathogens (actinomyces israelii, candida albicans, enterococcus faecalis, fusobacterium nucleatum, porphyromonas endodontalis, porphyromonas gingivalis, prevotella intermedia, streptococcus intermedius, treponema denticola, parvimonas micra, tannerella forsythensis, enterococcus faecium, prevotella melaninogenica) in infected root canals was studied using pcr. results: t. denticola (p = .012, .02) and e. faecalis (p = .012, .04) were highly associated with periapical radiolucency and previous pain, while p. gingivalis was associated with tenderness to percussion in both deciduous and permanent teeth (p = .01, .015). conclusion: the results of the present study confirm that certain species of microorganisms are associated with  clinical signs and symptoms of endodontic disease in both deciduous and permanent teeth.
TIHT== 
ABHT== 

PMID== 18422583
TI  == microbiological evaluation of primary endodontic infections in teeth with and without sinus tract.
AB  == aim: to examine the microbiological status of primary endodontic infections in teeth with and without a sinus tract. methodology: samples were collected by means of a size 15 h-type file and two sterile paper points from 30 cases of primary endodontic infections with (n = 15) or without (n = 15) a sinus tract. the presence of 40 bacterial species was determined by the checkerboard dna-dna hybridization method. results: the species found at the highest levels and prevalence were fusobacterium nucleatum sp. vincentii, porphyromonas gingivalis,  veillonella parvula, enterococcus faecalis, campylobacter gracilis and neisseria  mucosa. total bacterial counts were similar between teeth with (44 x 10(5)) and without (50 x 10(5)) a sinus tract (t-test: p > 0.05). e. faecalis, streptococcus anginosus, capnocytophaga sputigena and capnocytophaga gingivalis had significantly higher counts in the absence of sinus tract (mann-whitney test, p < 0.05). higher levels of p. gingivalis and fusobacterium nucleatum sp. nucleatum were observed in cases with a sinus tract. leptotrichia buccalis (or = 1.83; ci 95%) and porphyromonas endodontalis (or = 2.15; ci 95%) were associated with an increased chance of subjects having a sinus tract. conclusions: primary endodontic infections were associated with a large variety of bacterial species.  specific differences between the composition of the microbiota of primary root canal infections were observed in cases with or without a sinus tract.
TIHT== 
ABHT== 

PMID== 17949346
TI  == improved accuracy in terminal restriction fragment length polymorphism phylogenetic analysis using a novel internal size standard definition.
AB  == background: terminal restriction fragment length polymorphism (t-rflp) analysis is commonly used to analyze microbial communities, including oral microflora. however, accurate identification of terminal restriction fragment (t-rf) origins  is prevented by unpredictable errors in sizing, thus necessitating the clone library analysis. to minimize sizing errors, we proposed optimizing the size definition of internal standards. methods: genescan-1000 rox was regenerated as an internal standard by redefining the fragment sizes in terms of molecular weight (mw) based on their mobility relative to 6-carboxyfluorescein (fam) -labeled restriction fragments derived from the 16s recombinant rna gene of porphyromonas gingivalis. using the new size definition, the average sizing error among eight oral bacteria from six phyla was estimated and compared with that of  the conventional method. microbial communities isolated from saliva were analyzed using the new mw size definition. bacterial species were assigned to peaks using  trfma, a web-based tool for t-rflp analysis, and compared with those identified in a clone library analysis. results: using the new size definition, the average  sizing error for 40 t-rfs was drastically reduced from 2.42 to 0.62 bases, and large sizing errors (more than two bases) were eliminated. more than 90% of the total bacterial clones detected by the clone library analysis were assigned by t-rflp. conclusion: the size definition of the newly constructed internal standards reduced fragment sizing errors and allowed for accurate assignment of bacteria to peaks by the t-rflp analysis. this provided a more effective means for studying microbial communities, including the oral microflora.
TIHT== 
ABHT== 

PMID== 17949342
TI  == evaluation of the microbiota of primary endodontic infections using checkerboard  dna-dna hybridization.
AB  == background/aims: the aim of this study was to evaluate the composition of the microbiota of primary endodontic infections in 111 selected cases of single-rooted teeth with necrotic pulp. methods: samples were collected from the  root canals using #15 hedstroen-type files and two sterile paper points, which were introduced 1 mm short of the apical foramen. the presence, levels, and proportions of 40 different bacterial species in each sample were determined using dna probes and checkerboard dna-dna hybridization techniques. results: the  mean number of species per sample was 22. enterococcus faecalis (89.3%), campylobacter gracilis (89.3%), leptotrichia buccalis (89.3%), neisseria mucosa (87.5%), prevotella melaninogenica (86.6%), fusobacterium nucleatum ssp. vincentii (85.7%), eubacterium saburreum (75.9%), streptococcus anginosus (75%),  and veillonella parvula (74.1%) were the most prevalent species. the species found in highest mean counts (over 10(5)) were f. nucleatum ssp. vincentii (13.14 x 10(5)), e. saburreum (5.67 x 10(5)), e. faecalis (5.38 x 10(5)), n. mucosa (4.19 x 10(5)), v. parvula (3.63 x 10(5)), c. gracilis (3.46 x 10(5)), treponema  socranskii (3.34 x 10(5)), porphyromonas endodontalis (2.96 x 10(5)), porphyromonas gingivalis (2.85 x 10(5)), micromonas micros (2.81 x 10(5)), prevotella nigrescens (2.68 x 10(5)) and fusobacterium nucleatum ssp. nucleatum (2.64 x 10(5)). most of these species were also found in high proportions. conclusions: our results suggest that several bacterial species considered to be  oral pathogens seem to be implicated in the etiology of primary endodontic infections.
TIHT== 
ABHT== 

PMID== 17172525
TI  == phylogenetic analysis of bacterial and archaeal species in symptomatic and asymptomatic endodontic infections.
AB  == phylogenetic analysis of bacterial and archaeal 16s rrna was used to examine polymicrobial communities within infected root canals of 20 symptomatic and 14 asymptomatic patients. nucleotide sequences from approximately 750 clones amplified from each patient group with universal bacterial primers were matched to the ribosomal database project ii database. phylotypes from 37 genera representing actinobacteria, bacteroidetes, firmicutes, fusobacteria and proteobacteria were identified. results were compared to those obtained with species-specific primers designed to detect prevotella intermedia, porphyromonas  gingivalis, porphyromonas endodontalis, peptostreptococcus micros, enterococcus sp., streptococcus sp., fusobacterium nucleatum, tannerella forsythensis and treponema denticola. since members of the domain archaea have been implicated in  the severity of periodontal disease, and a recent report confirms that archaea are present in endodontic infections, 16s archaeal primers were also used to detect which patients carried these prokaryotes, to determine if their presence correlated with severity of the clinical symptoms. a methanobrevibacter oralis-like species was detected in one asymptomatic and one symptomatic patient. dna from root canals of these two patients was further analysed using species-specific primers to determine bacterial cohabitants. trep. denticola was  detected in the asymptomatic but not the symptomatic patient. conversely, porph.  endodontalis was found in the symptomatic but not the asymptomatic patient. all other species except enterococci were detected with the species-specific primers  in both patients. these results confirm the presence of archaea in root canals and provide additional insights into the polymicrobial communities in endodontic  infections associated with clinical symptoms.
TIHT== 
ABHT== 

PMID== 17014526
TI  == in vitro antimicrobial activity of sodium hypochlorite and chlorhexidine against  selected single-species biofilms.
AB  == aim: to investigate the antimicrobial activity of 2.5% and 5.25% sodium hypochlorite and 2.0% chlorhexidine gel and liquid as endodontic-irrigating substances against selected single-species biofilms. methods: single-species biofilms of enterococcus faecalis, staphylococcus aureus, candida albicans, prevotella intermedia, porphyromonas gingivalis, porphyromonas endodontalis and fusobacterium nucleatum were generated on a cellulose nitrate membrane placed on  agar medium. the biofilms were then immersed in the endodontic-irrigating substances for 30 s and also for 5, 10, 15, 30 and 60 min, with and without mechanical agitation. sterile saline was used as control. after each time period, the membrane filters were then transferred to tubes containing 2 ml of fresh broth medium plus neutralizers (in order to prevent the residual action of the tested substances). the micro-organisms were suspended using a vortex, and the inoculum was serially diluted 10-fold. aliquots of the dilutions were plated on 5% sheep blood agar medium, and incubated under adequate gaseous conditions. colony-forming units were calculated. the samples were compared using the friedman and tukey test, when necessary, at a significance level of p < 0.05. results: mechanical agitation promoted the effectiveness of the antimicrobial agents, resulting in less time to eliminate the same micro-organisms, except for  s. aureus with 2.5% naocl. antimicrobial agents in liquid presentation, especially 5.25% naocl and 2% chlorhexidine, killed the tested micro-organisms more rapidly. saline did not inhibit the growth of any of the tested micro-organisms, with or without agitation, being statistically different (p < 0.05) from naocl and chlorhexidine. p. intermedia, p. gingivalis, p. endodontalis and f. nucleatum were eliminated in 30 s by all antimicrobial agents, with our without agitation, in contrast with the facultative and aerobe strains. conclusions: mechanical agitation improved the antimicrobial properties of the chemical substances tested using a biofilm model, favouring the agents in liquid  presentation, especially 5.25% naocl and 2% chlorhexidine.
TIHT== 
ABHT== 

PMID== 16982278
TI  == photodynamic therapy for endodontic disinfection.
AB  == the aims of this study were to investigate the effects of photodynamic therapy (pdt) on endodontic pathogens in planktonic phase as well as on enterococcus faecalis biofilms in experimentally infected root canals of extracted teeth. strains of microorganisms were sensitized with methylene blue (25 microg/ml) for  5 minutes followed by exposure to red light of 665 nm with an energy fluence of 30 j/cm2. methylene blue fully eliminated all bacterial species with the exception of e. faecalis (53% killing). the same concentration of methylene blue  in combination with red light (222 j/cm2) was able to eliminate 97% of e. faecalis biofilm bacteria in root canals using an optical fiber with multiple cylindrical diffusers that uniformly distributed light at 360 degrees. we conclude that pdt may be developed as an adjunctive procedure to kill residual bacteria in the root canal system after standard endodontic treatment.
TIHT== 
ABHT== 

PMID== 15829891
TI  == differences in prevalence of selected bacterial species in primary endodontic infections from two distinct geographic locations.
AB  == objective: this study intended to compare the prevalence of 7 putative endodontic pathogens in samples of primary endodontic infections taken from patients of 2 distant geographic locations. study design: samples from infected root canals associated with asymptomatic periradicular lesions or from pus aspirated from acute periradicular abscesses were collected from patients in rio de janeiro, brazil, and seoul, south korea. south korean samples were frozen and delivered to brazil, where all steps in the molecular analysis were performed. dna was extracted and a species-specific nested polymerase chain reaction assay was used  to detect 7 target bacterial species. results: the most prevalent species detected in brazilian samples were porphyromonas endodontalis (79% of the cases)  , treponema denticola (79%), and dialister pneumosintes (76%). the most prevalent species found in south korean samples were fusobacterium nucleatum (38% of the cases) , tannerella forsythia (26%), and treponema maltophilum (24%). overall, p  endodontalis, d pneumosintes, filifactor alocis, t denticola, and t forsythia were significantly more detected in brazilian samples than in south korean samples ( p < .05). conclusions: findings indicated that the prevalence of some species in infections of endodontic origin may significantly differ from one geographic location to another.
TIHT== 
ABHT== 

PMID== 15329567
TI  == selected endodontic pathogens in the apical third of infected root canals: a molecular investigation.
AB  == bacteria located at the apical portion of the root canals are conceivably in a strategic position to induce damage to the periradicular tissues and resulting inflammatory diseases. this study sought to investigate the prevalence of 11 selected putative endodontic pathogens in the apical third of infected root canals associated with periradicular lesions. the apical root portion of 23 extracted teeth with carious pulpal exposures and attached periradicular lesions  was sectioned, and the root canals were sampled for microbiological investigation. dna was extracted from the samples and analyzed for the presence of 11 bacterial species using a nested polymerase chain reaction assay. the results showed that pseuramibacter alactolyticus occurred in 10 cases (44%), treponema denticola in 6 (26%), fusobacterium nucleatum in 6 (26%), porphyromonas endodontalis in 4 (17%), filifactor alocis in 2 (9%), dialister pneumosintes in 1 (4%), porphyromonas gingivalis in 1 (4%), and tannerella forsythensis in 1 (4%).  no sample yielded prevotella intermedia, prevotella nigrescens, or campylobacter  rectus. of the samples examined, 17 were positive for at least 1 of the target species. occurrence of these bacterial species in the apical third of infected root canals suggests that they can be involved in causation of periradicular lesions.
TIHT== 
ABHT== 

PMID== 15128058
TI  == the role of lipopolysaccharide in infectious bone resorption of periapical lesion.
AB  == background: the role of lipopolysaccharide (lps) in periapical lesion-induced bone resorption was investigated. polymyxin b (pmb), a specific inhibitor of lps, was evaluated to treat the apical lesion. methods: lipopolysaccharide isolated from two common endodontic pathogens, fusobacterium nucleatum and porphyromonas endodontalis, stimulated mouse macrophage (j774) to release interleukin-1alpha (il-1 alpha) and tumor necrosis factor-alpha (tnf-alpha) in a time-dependent manner. results: combination of lps further enhanced the stimulation. pmb inhibited these effects significantly. lps also stimulated matrix metalloproteinase-1 (mmp-1) gene expression in j774, whereas anti-il-1 alpha and  anti-tnf-alpha antibodies, as well as pmb, diminished this effect. a disease model of periapical lesion was established in wistar rat. administration of pmb reduced the extent of lesion-associated bone resorption by 76% to approximately 80%, and simultaneously reduced the numbers of mmp-1-producing macrophages. conclusions: it is suggested that lps released from the infected root canal triggers the synthesis of il-1 alpha and tnf-alpha from macrophages. these pro-inflammatory cytokines up-regulate the production of mmp-1 by macrophages to  promote periapical bone resorption.
TIHT== 
ABHT== 

PMID== 15055430
TI  == geographical differences in bacteria detected in endodontic infections using polymerase chain reaction.
AB  == the polymerase chain reaction (pcr) is an innovative nucleic acid-based assay that has the highest sensitivity of any microbiological technique for the detection of bacteria. the purpose of this study was to use pcr to detect the presence of specific species of bacteria in samples collected from two geographical locations. microbial samples from abscesses of endodontic origin were collected from patients in portland, oregon, and rio de janeiro, brazil. pcrs with species-specific oligonucleotide primers for the 16s ribosomal rna gene were used for detection of the bacteria after dna extraction from each clinical sample. statistical analysis revealed that there was a significant difference in  detection of the bacteria between the two geographical locations for prevotella intermedia, prevotella nigrescens, prevotella tannerae, fusobacterium nucleatum,  and porphyromonas gingivalis, but not for porphyromonas endodontalis, fusobacterium necrophorum, and enterococcus faecalis. these results suggest that  differences in bacteria detected or cultured in studies can be associated with geographical location.
TIHT== 
ABHT== 

PMID== 14871344
TI  == microbiological examination of infected dental root canals.
AB  == objectives: the aim of this study was to investigate the root canal microbiota of primary and secondary root-infected canals and the association of constituent species with specific endodontic signs and symptoms. methods: microbial samples were taken from 60 root canals, 41 with necrotic pulp tissues (primary infection) and 19 with failed endodontic treatment (secondary infection). strict anaerobic techniques were used for serial dilution, plating, incubation and identification. results: a total of 224 cultivable isolates were recovered belonging to 56 different bacterial species. individual root canals yielded a maximum of 10 bacterial species. of the bacterial isolates, 70% were either strict anaerobes or microphilic. the anaerobes most frequently isolated were: peptostreptococcus micros (35%), fusobacterium necrophorum (23.3%), fusobacterium nucleatum (11.7%), prevotella intermedia/nigrescens (16.7%), porphyromonas gingivalis (6.7%) and porphyromonas endodontalis (5%). the root canal microflora of untreated teeth with apical periodontitis was found to be mixed, comprising gram-negative and gram-positive and mostly anaerobic microorganisms and usually containing more than 3 species per canal. on the other hand, facultative anaerobic and gram-positive bacteria predominated in canals with failed endodontic treatment, which harbored 1-2 species per canal. suggested relationships were found between  anaerobes, especially gram-negatives, and the presence or history of pain, tenderness to percussion and swelling (p<0.05). in particular, associations were  found between: a) pain (n=29) and p. micros (p<0.01), p. intermedia/nigrescens and eubacterium spp. (both p<0.05); b) history of pain (n=31) and p. micros (p<0.01) porphyromonas and fusobacterium spp. (p<0.05); c) tenderness to percussion (n=29) and porphyromonas spp. (p<0.01), peptostreptococcus and fusobacterium spp. (p<0.001); d) swelling (n=20) and peptostreptococcus spp. (p<0.01), porphyromonas and enterococcus spp. (p<0.05); e) wet canals (n=33) and  porphyromonas and fusobacterium spp. (p<0.05); f) purulent exudate (n=20) and porphyromonas, peptostreptococcus and fusobacterium spp. (p<0.05); previous endodontic treatment and enterococcus faecalis, streptococcus spp., p. micros, f. necrophorum (p<0.05). conclusions: our findings indicate potential complex interactions of species resulting in characteristic clinical pictures which cannot be achieved by individual species alone. they also indicate that the microbiota of primary infected canals with apical periodontitis differs in number and in species from the secondary infected canals by using the culture technique.
TIHT== 
ABHT== 

PMID== 12877258
TI  == positive and negative bacterial associations involving dialister pneumosintes in  primary endodontic infections.
AB  == dialister pneumosintes is an anaerobic gram-negative rod that has been recently implicated as a candidate endodontic pathogen. in this study, samples taken from  abscessed teeth and infected root canals associated with asymptomatic or symptomatic periradicular lesions were examined for the occurrence of bacterial associations involving d. pneumosintes. dna was extracted from the samples, and the presence of d. pneumosintes and 16 other bacterial species was determined by  means of species-specific nested polymerase chain reaction. positive and negative associations involving d. pneumosintes were investigated by computing the odds ratio of d. pneumosintes being found in a sample from endodontic infection in co-infection with one of the other target species. the association between the pairs containing d. pneumosintes and the occurrence of pain also was evaluated. d. pneumosintes was always detected in mixed infections with at least two of the  other target species. d. pneumosintes was positively associated with treponema denticola, porphyromonas endodontalis, fusobacterium nucleatum, peptostreptococcus micros, campylobacter rectus, prevotella intermedia, t. pectinovorum, and t. vincentii. negative associations were observed with bacteroides forsythus, p. gingivalis, and actinomyces israelii. no pair containing d. pneumosintes was found to be significantly associated with symptomatic cases (p > 0.01). the findings of this study lend considerable support to the notion of d. pneumosintes being an important endodontic pathogen,  usually in a mixed infection. positive associations of this species with other highly prevalent species, such as t. denticola and p. endodontalis, suggest that  bacterial synergism can occur and thereby play an important role in the pathogenesis of different forms of periradicular lesions.
TIHT== 
ABHT== 

PMID== 12670069
TI  == antimicrobial properties of self-etching primer-bonding systems.
AB  == self-etching primers are now considered the new generation of dentin bonding systems that modify and incorporate the bacteria-containing smear layer into their bonding mechanism. the antibacterial effects of the self-etching primers clearfil se bond, mac bond, imperva fl bond, one-up bondf and prompt l-pop were evaluated using the bacteria streptococcus mutans atcc25175, peptostreptococcus anaerobius, peptostreptococcus prevotii, peptostreptococcus asaccharolyticus, lactobacillus acidophilus, lactobacillus catenaforme, lactobacillus jensenii, actinomyces odontolyticus, porphyromonas endodontalis, clostridium ramosum, prevotella oris, prevotella denticola and fusobacterium nucleatum, with a disk diffusion method. a single-bottle total-etch dentin adhesive (excite) was used for comparisons and chlorhexidine (0.2%) was used as the positive control. after  incubation, zones of inhibited bacterial growth were observed. one-up bondf, prompt l-pop and excite showed growth inhibition for all bacterial strains. the bonding agents of clearfil se bond, mac bond and imperva fl bond were unable to inhibit the growth of lactobacillus jensenii and actinomyces odontolyticus, while the primers of these systems produced inhibition halos to all tested microorganisms greater than that of chlorhexidine.
TIHT== 
ABHT== 

PMID== 12597711
TI  == antibacterial effects of resinous retrograde root filling materials.
AB  == the effect of three resinous retrograde root filling materials on the growth of four obligate anaerobic bacteria associated with endodontic infections was determined by using the agar diffusion inhibitory test. samples of the following  resinous materials (resin-modified, glass-ionomer cement, fuji ii lc; compomer, dyract; and composite resin, spectrum) were incubated for 1 week with the following anaerobic bacteria: fusobacterium nucleatum, porphyromonas gingivalis,  p. endodontalis, and prevotella intermedia. the freshly mixed and set resinous materials were placed into the prepared wells of agar plates inoculated with the  test microorganisms for 1 week. after the end of the incubation period, the zone  of growth inhibition was observed and measured. analysis of variance of the mean  diameter of the zone of inhibition indicated no statistically significant overall differences in the response of the black-pigmented bacteroides species (p > 0.05). for f. nucleatum, spectrum had more antibacterial effect against this bacteria than dyract (p < 0.05). additionally, fuji ii lc was ineffective against f. nucleatum (p < 0.05). however, positive control plates showed bacterial growth in all cases. our data suggest that the antibacterial potency of polymerized materials varied considerably, depending on the type and the product tested.
TIHT== 
ABHT== 

PMID== 12202557
TI  == pcr-based identification of bacteria associated with endodontic infections.
AB  == pcr primers that target the bacterial 16s rrna genes (or the tuf gene for the genus enterococcus) were used to identify 10 putative bacterial pathogens in root canals with necrotic pulp. in addition, the associations of these microorganisms  with symptoms and a history of diabetes mellitus were investigated. microbial samples from the root canals of 24 teeth with necrotic pulp were included in the  study. pcr with universal bacterial primers identified bacterial dna in 22 specimens; the remaining 2 specimens were from intact teeth that had been traumatized 6 months prior to treatment. pcr with specific primers showed that preoperative symptoms were significantly associated with the presence of streptococcus spp. (p < 0.001 by chi-square analysis). there was also a nonsignificant trend for symptoms to be associated with fusobacterium nucleatum and porphyromonas gingivalis (odds ratio, >2) and for diabetes mellitus to be associated with p. gingivalis and porphyromonas endodontalis (odds ratio, >2). cloning and sequencing of the universal pcr product in one specimen revealed the  presence of an organism related to the genus olsenella, which has not previously  been described in endodontic infections.
TIHT== 
ABHT== 

PMID== 12200976
TI  == microbiological, immunological and genetic factors in family members with periodontitis as a manifestation of systemic disease, associated with hematological disorders.
AB  == the microflora, immunological profiles of host defence functions, and human leukocyte antigen (hla) findings are reported for a mother, son and daughter who  were diagnosed as having 'periodontitis as a manifestation of systemic diseases,  associated with hematological disorders'. examinations were made of the bacterial flora from the periodontal pocket, neutrophil chemotaxis, neutrophil phagocytosis, and the genotypes (dqb1) and serotypes (dr locus) of hla class ii antigens. phenotypic analyses of the peripheral lymphocytes were also conducted.  the subgingival microflora from the mother was dominated by gram-negative rods, especially porphyromonas endodontalis, prevotella intermedia/prevotella nigrescens and fusobacterium nucleatum. subgingival microflora samples from the son and daughter were dominated by gram-positive cocci and gram-positive rods. through the use of polymerase chain reaction, campylobacter rectus and capnocytophaga gingivalis were detected in all subjects, whereas porphyromonas gingivalis, p. intermedia, and treponema denticola were not detected in any subjects. all three subjects showed a remarkable level of depressed neutrophil chemotaxis to n-formyl-methionyl-leucyl-phenylalanine, although their phagocyte function levels were normal, in comparison to healthy control subjects. each subject had the same genotype, hla-dqb1*0601, while the mother had hla-dr2 and hla-dr8, and the son and daughter had hla-dr2 only. in summary, the members of this family showed a similar predisposition to periodontitis with regard to certain host defence functions. it is suggested that the depressed neutrophil chemotaxis that was identified here could be a significant risk factor for periodontitis in this family.
TIHT== 
ABHT== 

PMID== 11856276
TI  == evaluation of the rapid id 32a system for identification of anaerobic gram-negative bacilli, excluding the bacteroides fragilis group.
AB  == objective: to evaluate the rapid id 32a system (biomerieux, marcy-l'etoile, france) for the identification of anaerobic gram-negative bacilli, excluding the  bacteroides fragilis group. methods: five hundred and twenty-eight identified clinical isolates of non-b. fragilis group anaerobic gram-negative bacilli were tested in the rapid id 32a system, and identifications were compared with those obtained with conventional biochemical tests and gas-liquid chromatography. results: the rapid id 32a system correctly identified 280 (60.9%) of the 460 isolates tested for which taxa were included in the database, without the need for additional testing. a further 97 (21.1%) isolates were correctly identified to species level following the performance of complementary tests recommended by  the manufacturer. fifty-nine (12.8%) isolates were identified at the genus level  only, and 21 (4.6%) were misidentified at the species level. three isolates of prevotella were not identified by the system. of the 68 isolates belonging to taxa not included in the database, no identification was obtained for 33 (48.5%), while 35 (51.5%) were misidentified. conclusions: the rapid id 32a system provided a rapid and reliable method for the identification of non-b. fragilis group, anaerobic gram-negative bacilli to the genus level, while the success of species-level identification varied with different taxa. there was poor discrimination between fusobacterium nucleatum and f. necrophorum, between porphyromonas asaccharolytica and porphyromonas endodontalis, and between prevotella buccalis, prevotella denticola, prevotella loescheii, prevotella melaninogenica and prevotella oralis. the need to perform conventional complementary tests on 149 (32.4%) of the 460 isolates compromised the usefulness of the system for rapid species identification.
TIHT== 
ABHT== 

PMID== 11800436
TI  == antimicrobial activity of four root canal sealers against endodontic pathogens.
AB  == the antibacterial effects of various types of widely used endodontic sealers have not been compared systematically on facultative or obligate anaerobic endodontic  pathogens. the aim of this study was to evaluate the antimicrobial properties of  four commonly used endodontic sealers: two epoxy-resin-based sealers (ah26, ah plus), one zinc-oxide eugenol-based sealer (n2), and one calcium hydroxide-based  sealer (sealapex). the testing microbes were four facultative anaerobic species (streptococcus mutans, streptococcus sanguis, escherichia coli, and staphylococcus aureus) and four obligate anaerobic species (porphyromonas gingivalis, porphyromonas endodontalis, fusobacterium nucleatum, and prevotella intermedia). the freshly mixed sealers were placed into the prepared wells of agar plates inoculated with the test microorganisms. after varying periods of incubation (2 days for facultative anaerobic species and 7 days for obligate anaerobic species), the zones of growth inhibition were observed and measured. all the sealers were distinctly different from each other in their antimicrobial  activity. the sealers showed different inhibitory effects depending on the types  and bacterial strains. n2 containing formaldehyde and eugenol proved to be the most effective against the microorganisms. the extreme antimicrobial potency of this root canal sealer must be weighted against its pronounced tissue toxic effect.
TIHT== 
ABHT== 

PMID== 11202881
TI  == assessment of periradicular microbiota by dna-dna hybridization.
AB  == in the present study the "checkerboard" dna-dna hybridization technique was used  to identify bacteria in periapical endodontic lesions of asymptomatic teeth. thirty-four patients with root-filled teeth and apical periodontitis were divided into two groups, each containing 17 patients. in group 1, a marginal incision was performed during surgery to expose the lesion, and in group 2, a submarginal incision was applied. the gingiva and mucosa were swabbed with an 0.2% chlorhexidine gluconate solution prior to surgery. bacterial dna was identified in all samples from the two groups using 40 different whole genomic probes. the mean number (+/- sd) of species detected was 33.7 +/- 3.3 in group 1 and 21.3 +/- 6.3 in group 2 (p < 0.001). the majority of the probe-detected bacteria were present in more lesions from group 1 than from group 2. the differences were most notable for campylobacter gracilis, porphyromonas endodontalis, propionibacterium acnes, capnocytophaga gingivalis, fusobacterium nucleatum ssp. nucleatum, fusobacterium nucleatum ssp. polymorphum, prevotella intermedia, treponema denticola, streptococcus constellatus and actinomyces naeslundii i. bacterial species such as actinobacillus actinomycetemcomitans and bacteroides forsythus were detected in more than 60% of the lesions from both groups. also, p. endodontalis was abundant in periapical tissue. the data supported the idea that  following a marginal incision, bacteria from the periodontal pocket might reach the underlying tissues by surgeon-released bacteremia. the study provided solid evidence that bacteria invade the periapical tissue of asymptomatic teeth with apical periodontitis. the detection of much more bacteria with the "checkerboard" dna-dna hybridization method than has previously been recovered by anaerobic culture indicated that the endodontic (and periodontal) microfloras should be redefined using molecular methods.
TIHT== 
ABHT== 

PMID== 11199767
TI  == anaerobic bacterial extracts influence production of matrix metalloproteinases and their inhibitors by human dental pulp cells.
AB  == the role of human dental pulp (hdp) cells in extracellular matrix degradation in  pulpitis is still unclear. in this study, the effects of sonicated bacterial extracts (sbes) from prevotella intermedia, fusobacterium nucleatum, porphyromonas endodontalis, and porphyromonas gingivalis on the balance between the production of matrix metalloproteinases (mmps) and that of their inhibitors [tissue inhibitors of metalloproteinases (timps)] by hdp cells were examined. hdp cells were treated with sbes, and their culture media were later harvested. mmp activities and timp concentrations were determined by use of independent measurement strategies and sensitive elisas. the production of mmp-1 and mmp-2 was accelerated by all sbe. on the other hand, timp-1 production was slightly elevated; and timp-2 production was markedly inhibited by all of the extracts. sbes derived from these anaerobic bacteria seemed to affect the acceleration of extracellular matrix degradation activity by hdp cells. these findings suggest that hdp cells stimulated by bacterial byproducts may be involved in the pathogenesis of pulpitis.
TIHT== 
ABHT== 

PMID== 10914791
TI  == "checkerboard" assessments of periodontal microbiota and serum antibody responses: a case-control study.
AB  == background: we explored the association between subgingival microbial profiles and serum igg responses to periodontal microbiota in relation to clinical periodontal status. methods: one hundred thirty-one (131) periodontitis patients  aged 29 to 74 years (mean 51.8) were age- and gender-matched with 74 periodontally intact controls (range 26 to 77, mean 49.3). smoking habits and health history were recorded and assessments of plaque, bleeding on probing, probing depth, and attachment level were performed at 6 sites per tooth on all present teeth, excluding third molars. subgingival plaque samples were obtained from each tooth in one upper and one lower quadrant (maximum 14 samples/subject;  2,440 samples total) and analyzed with respect to 19 species by means of whole genomic dna probes. serum igg antibodies against the same 19 species were assessed by an immunoassay. results: cases displayed an average of 22.7 teeth, 20.3 sites with probing depth > or =6 mm, and 18.9 sites with attachment loss > or =6 mm. corresponding figures for controls were 27.1, 0.1, and 1.0, respectively. heavy smoking was 3 times more frequent among cases than controls (32.1% versus 9.6%). higher levels of porphyromonas gingivalis, porphyromonas endodontalis, prevotella intermedia, prevotella nigrescens, prevotella melaninogenica, bacteroides forsythus, fusobacterium nucleatum, treponema denticola, eubacterium nodatum, peptostreptococcus micros, and campylobacter rectus were found in cases and higher levels of eikenella corrodens, veillonella  parvula, and actinomyces naeslundii in controls. cases displayed higher igg levels against p. gingivalis and actinobacillus actinomycetemcomitans, while controls displayed higher levels against f. nucleatum, t. denticola, e. nodatum,  and capnocytophaga ochracea. positive correlations between bacterial colonization and antibody responses were identified for 9 species in controls. in cases, however, statistically significant correlations were observed for only 3 species  out of which only one was positive (v. parvula). both bacterial levels and antibody responses declined in ages over 55 years. a logistic regression employing selected elements of bacterial colonization and antibody responses as independent variables resulted in 81.1% correct diagnosis, with sensitivity of 83.1%, specificity of 77.8%, positive predictability of 86%, and negative predictability of 73.7%. smoking did not reach statistical significance in this model. conclusion: a combined microbial colonization/antibody response profile can effectively discriminate between periodontitis patients and periodontally intact controls.
TIHT== 
ABHT== 

PMID== 10726523
TI  == inflammatory cytokine production and specific antibody responses to lipopolysaccharide from endodontopathic black-pigmented bacteria in patients with multilesional periapical periodontitis.
AB  == we examined the induction of the cytokines interleukin (il)-1 beta, il-6, and il-8 by lipopolysaccharides (lpss) from several species of possible endodontopathic black-pigmented bacteria. studies were conducted in human whole blood cultures from six patients (two from each group) with differing numbers of  periapical periodontitis lesions (i.e. patients with radiographically clear periapical lesions in 10 or more teeth (high-lesion group, n = 4), in one or two  teeth (low-lesion group, n = 6), and six healthy volunteers with no periapical lesions (no lesion group)). lps from prevotella intermedia atcc 25611, porphyromonas gingivalis 381, and prophyromonas endodontalis atcc 27067 induced a higher il-8 response in the subjects of the high-lesion group, compared with the  subjects of the other two groups. to ascertain the degree of sensitization by test bacteria, we examined the reactivities of antibodies in serum and saliva from the subjects to different bacterial species. lps from p. gingivalis reacted  strongly with sera from the high-lesion group. thus, lps from black-pigmented bacteria may be involved in multilesional periapical periodontitis by inducing particular cytokines and/or humoral immune responses.
TIHT== 
ABHT== 

PMID== 9759015
TI  == cytotoxic effect of endodontic bacteria on periapical fibroblasts.
AB  == this study was conducted to investigate the effects of sonicated bacterial extracts (sbes) from anaerobic gram-negative bacteria on periapical fibroblast obtained from the apical portion of human periodontal ligaments. porphyromonas endodontalis, porphyromonas gingivalis, prevotella intermedia, and fusobacterium  nucleatum were chosen from among the endodontic bacteria isolated from root canals having a periapical lesion and compared in terms of their cytotoxicity. the purpose of this study was to examine which bacteria are involved in the development of periapical inflammation. the anaerobes were cultured under strict  anaerobic conditions, and the bacterial cells were then harvested by centrifugation after incubation. the concentrated cell suspensions were sonicated and subsequently centrifuged. an sbe was made of each of the filtered supernatants. each sbe was added to cultures of periapical fibroblasts. the cell  growth and proliferation were measured by the mtt method after 3, 5, and 7 days.  the sbes from p. endodontalis, p. gingivalis, and f. nucleatum inhibited the growth of the fibroblasts, whereas the sbe from p. intermedia did not inhibit it. the sbes from p. gingivalis and f. nucleatum inhibited the fibroblast growth more strongly than did the p. endodontalis, p. gingivalis, and f. nucleatum may participate in the development of periapical lesions.
TIHT== 
ABHT== 

PMID== 9693583
TI  == experimental root canal infections in conventional and germ-free mice.
AB  == a small animal model was evaluated to study the interrelationships between microorganisms after their implantation in root canals (inferior central incisors) using germ-free (gf) and conventional (cv) mice. the selected microorganisms were: porphyromonas endodontalis (atcc 35406), eubacterium lentum  (atcc 25559), peptostreptococcus anaerobius (atcc 27337), fusobacterium nucleatum (atcc 10953), escherichia coli (atcc 25922), and enterococcus faecalis (atcc 4083). only p. anaerobius, e. coli, and e. faecalis, respectively, were able to colonize when inoculated alone into the root canal of both cv and gf mice. e. lentum, when inoculated alone colonized only in cv animals. p. endodontalis and f. nucleatum were unable to colonize in cv and gf animals after single inoculation. it is concluded that the experimental animal model presented herein  is valuable for ecological studies of root canal infections and that only some strict anaerobic bacteria are able to colonize mice root canals when inoculated by themselves alone in pure culture.
TIHT== 
ABHT== 

PMID== 9573801
TI  == effect of red blood cells on the growth of porphyromonas endodontalis and microbial community development.
AB  == establishment of a microbial community in the root canal system depends on numerous factors, of which nutrient availability may be one of the most important. we hypothesized that the presence of red blood cells or hemoglobin in  this environment could cause shifts in microbial composition of communities, resulting in organisms such as porphyromonas endodontalis becoming more dominant. an in vitro model system using mixed, batch cultures was performed with the bacteria p. endodontalis, fusobacterium nucleatum, peptostreptococcus micros and  campylobacter rectus. bacteria were cultured in media with or without the addition of washed red blood cells, hemoglobin, or serum. cyclic growth studies revealed that p. endodontalis was lost from the community of organisms after three cycles. however, inclusion of red blood cells resulted in establishment of  this organism. moreover, red blood cells added to pure cultures of p. endodontalis substantially enhanced growth and protected the organisms from oxygen. we conclude that the presence of red blood cells could result in shifts of microbial communities of organisms within the root canal system.
TIHT== 
ABHT== 

PMID== 9310708
TI  == pore-forming molecules in gram-negative anaerobic bacteria.
AB  == little information is available about porin molecules in anaerobes. porins from bacteroides fragilis and porphyromonas, fusobacterium, and campylobacter species  have been described. a pore-forming outer membrane (om) porin protein was isolated from b. fragilis (omp-200); it is exposed at the cell surface and dissociated by boiling and application of reducing agents. fusobacterium nucleatum foma, an om porin protein of 40 kd, had a deduced topology of foma similar to that of established porins, despite the lack of sequence similarity. an om preparation from porphyromonas endodontalis (including a major protein with an apparent molecular mass of 31 kd and other proteins of 40.3-71.6 kd) formed pores in a liposome assay. a major outer membrane protein (momp) from campylobacter jejuni (a microaerophile) is related to the family of trimeric bacterial porins, although little homology was seen with other porins. the development of antimicrobial resistance related to decreased permeability underlines the importance of identifying and characterizing the pore-forming molecules of anaerobes.
TIHT== 
ABHT== 

PMID== 9310640
TI  == recently described clinically important anaerobic bacteria: taxonomic aspects and update.
AB  == a new method of identifying bacteria, phylogenetic 16s rrna sequencing, has led to major reorganizations among most genera of anaerobic bacteria. the pigmented prevotella species now comprise seven species including p. nigrescens and p. tannerae; p. intermedia/p. nigrescens-like organisms await inclusion. the former  mitsuokella dentalis and hallella seregens were transferred to prevotella as one  species, p. dentalis. p. enoeca is a new nonpigmenting prevotella. the genus porphyromonas currently includes 11 pigmented species and one nonpigmented species, p. catoniae; p. levii-like and p. endodontalis-like organisms are candidates for the genus. fusobacterium nucleatum currently has five subspecies,  and f. varium includes the former f. pseudonecrophorum. former wolinella recta and wolinella curva now are campylobacter rectus and campylobacter curvus; campylobacter showae is a new species. isolates included in the bile-sensitive former bacteroides gracilis now are campylobacter gracilis; the bile-resistant b. gracilis isolates were transferred to a new genus, sutterella, as s. wadsworthensis. the new actinomyces species include two subspecies of the a. neuii and the a. radingae-a. turicensis complex. the genus eubacterium sensu stricto is represented by e. limosum, and the former e. alactolyticum was reclassified in a new genus, pseudoramibacter, as p. alactolyticus. recent entries include e. saphenum, e. minutum, e. exiguum, e. infirmum, and e. tardum.  a new genus, atopobium houses some former lactobacilli and streptococci. the genus peptostreptococcus also have four new species; p. hydrogenalis, p. lacrimalis, p. lactolyticus, and p. vaginalis.
TIHT== 
ABHT== 

PMID== 7561654
TI  == effects of lipopolysaccharides on human dental pulp cells.
AB  == human dental pulp cells were treated with 1, 10, and 100 micrograms/ml of lipopolysaccharide (lps). the effects of treatment were examined by measurement of the dna content, protein content, and alkaline phosphatase activity of the cells. lps samples were purified from porphyromonas gingivalis, porphyromonas endodontalis, and fusobacterium nucleatum isolated from root canals, and escherichia coli 0111:b4 lps was used as a positive control. at a concentration of 1 microgram/ml, none of the lpss caused any change in the production of dna or protein, whereas the amount of dna was increased at 10 micrograms/ml and inhibited at 100 micrograms/ml. protein synthesis was decreased by lpss at both 10 and 100 micrograms/ml. alkaline phosphatase activity was not changed at any concentration of lps tested.
TIHT== 
ABHT== 

PMID== 7553378
TI  == oligonucleotide probes to the 16s ribosomal rna: implications of sequence homology and secondary structure with particular reference to the oral species prevotella intermedia and prevotella nigrescens.
AB  == eight oligonucleotides based upon regions of the small subunit 16s ribosomal rna  gene sequences were analysed against a background of their position within the molecule and their two-dimensional structure to rationalise their use in recognising prevotella intermedia and prevotella nigrescens. the 41 clinical isolates from both oral and respiratory sites and two reference strains were subjected to dna-dna hybridisation and multilocus enzyme electrophoresis to confirm their identity. alignment of oligonucleotide probes designated i bi-2 to  i bi-6 (for p. intermedia) and 2bi-2 (for p. nigrescens) with the 16s rrna suggested that these probes lacked specificity or were constructed from hypervariable regions. a 52-mer oligonucleotide (designated bi) reliably detected both species. because of the high degree of concordance between the 16s rrnas of  both species, it was necessary to vary the stringency of hybridisation conditions for detection of both species. thus probe i bi-i recognised p. intermedia while i bi-i detected both p. intermedia and p. nigrescens at low stringency. however, under conditions of high stringency only p. nigrescens was recognised by probe 2bi-i. these probes were highly specific and did not hybridise with dna from the  closely related p. corporis, nor other periodontal pathogens such as fusobacterium nucleatum, actinobacillus actinomycetemcomitans, treponema denticola and several pigmented species such as prevotella melaninogenica, p. denticola, p. loescheii, porphyromonas asaccharolytica, py. endodontalis, py. gingivalis, py. levii, and py. macacae.
TIHT== 
ABHT== 

PMID== 7870469
TI  == degradation of immunoglobulin g by periodontal bacteria.
AB  == several subgingival microorganisms were tested for their ability to utilize human immunoglobulin g (igg) as a substrate for growth. this was done using a protein-free chemically defined medium, supplemented with igg. stimulation of growth was observed for capnocytophaga ochracea, porphyromonas asaccharolytica, porphyromonas endodontalis, porphyromonas gingivalis, prevotella intermedia, prevotella oralis, lactobacillus catenaforme and streptococcus intermedius. immunoelectrophoresis, sodium dodecyl sulfate-polyacrylamide gel electrophoresis  and a protein assay demonstrated that p. intermedia and p. endodontalis completely degraded the protein chains of igg. partial breakdown of igg was observed for p. asaccharolytica and c. ochracea, whereas p. oralis cleaved the igg heavy chain, yielding fc and fab fragments. all these bacteria utilized igg as a substrate for growth. binding studies using an enzyme-linked immunosorbent assay, revealed complete loss of in vitro antigen-antibody binding capacity after incubation of specific igg with p. endodontalis and partial loss of binding with  p. intermedia, p. gingivalis, c. ochracea or fusobacterium nucleatum. degradation or inactivation of igg by oral bacteria is thought to be important in the causation of polymicrobial infections.
TIHT== 
ABHT== 

PMID== 8324136
TI  == oral and dental infections with anaerobic bacteria: clinical features, predominant pathogens, and treatment.
AB  == microbial populations colonizing the teeth are a major source of pathogens responsible for oral and dental infections, including periodontal diseases, gingivitis, pericoronitis, endodontitis, peri-implantitis, and postextraction infections. each entity has distinct clinical and microbial features. bacterial species associated with oral infections include actinobacillus actinomycetemcomitans, porphyromonas gingivalis, prevotella intermedia, bacteroides forsythus, campylobacter rectus, eubacterium species, fusobacterium nucleatum, eikenella corrodens, and peptostreptococcus micros. treponema pallidum-related spirochetes have been associated with acute necrotizing ulcerative gingivitis. porphyromonas endodontalis appears to be specifically related to endodontic infections. oral infections in medically compromised patients, including those with aids, are associated with similar species and are  usually complicated by superinfection with enteric and candida species. isolation of species causing oral infections requires the collection of appropriate samples and the use of strictly anaerobic techniques. rapid selective culture, immunofluorescence, and dna probe methods have been developed for the identification of these oral species. the varied measures required in the management of oral and dental infections may include antimicrobial therapy. accurate microbiological diagnosis, including antibiotic susceptibility testing,  is indicated for cases that do not respond to therapy.
TIHT== 
ABHT== 

PMID== 1437068
TI  == complement activation by lipopolysaccharides purified from gram-negative bacteria isolated from infected root canals.
AB  == the purpose of the present study was to investigate the complement activation by  lipopolysaccharides purified from porphyromonas (bacteroides) endodontalis, veillonella parvula, and fusobacterium nucleatum isolated from infected root canals. the rate of consumption of the c3t component of the complement increased  remarkably when lipopolysaccharides of more than 10 micrograms were added.
TIHT== 
ABHT== 

PMID== 1398963
TI  == identification of proteases from periodontopathogenic bacteria as activators of latent human neutrophil and fibroblast-type interstitial collagenases.
AB  == activation of latent human fibroblast-type and neutrophil interstitial procollagenases as well as degradation of native type i collagen by supra- and subgingival dental plaque extracts, an 80-kda trypsinlike protease from porphyromas gingivalis (atcc 33277), a 95-kda chymotrypsinlike protease from treponema denticola (atcc 29522), and selected bacterial species commonly isolated in periodontitis was studied. the bacteria included were prevotella intermedia (atcc 25261), prevotella buccae (es 57), prevotella oris (atcc 33573), porphyromonas endodontalis (es 54b), actinobacillus actinomycetemcomitans (atcc 295222), fusobacterium nucleatum (atcc 10953), mitsuokella dentalis (dsm 3688), and streptococcus mitis (atcc 15909). none of the bacteria activated latent procollagenases; however, both sub- and supragingival dental plaque extracts (neutral salt extraction) and proteases isolated from cell extracts from potentially periodontopathogenic bacteria p. gingivalis and t. denticola were found to activate latent human fibroblast-type and neutrophil interstitial procollagenases. the fibroblast-type interstitial collagenase was more efficiently activated by bacterial proteases than the neutrophil counterpart, which instead preferred nonproteolytic activation by the oxidative agent hypochlorous acid. the proteases were not able to convert collagenase tissue inhibitor of metalloproteinase (timp-1) complexes into active form or to change the ability of timp-1 to inhibit interstitial collagenase. none of the studied bacteria, proteases from p. gingivalis and t. denticola, or extracts of supra- and subgingival dental plaque showed any significant collagenolytic activity. however, the proteases degraded native and denatured collagen fragments after cleavage by interstitial collagenase and gelatinase. our results indicate that proteases from periodontopathogenic bacteria can act as direct proteolytic activators of human procollagenases and degrade collagen fragments. thus, in concert with host enzymes the bacterial proteases may participate in periodontal  tissue destruction.
TIHT== 
ABHT== 

PMID== 1494447
TI  == associations between microbial species in dental root canal infections.
AB  == the existence of commensal or antagonistic relationships between microorganisms in the root canals of teeth with apical periodontitis was investigated. samples were taken from 65 infected human root canals and were analysed according to species, frequency of occurrence and proportion of the total isolated flora. the  most frequent species were fusobacterium nucleatum, prevotella intermedia, peptostreptococcus micros, peptostreptococcus anaerobius, eubacterium alactolyticum, eubacterium lentum and wolinella recta. an odds ratio system was used to calculate positive or negative associations between the isolated bacteria. strong positive associations were found between f. nucleatum and p. micros, porphyromonas endodontalis, selenomonas sputigena and w. recta. there was also a positive association between p. intermedia and p. micros, p. anaerobius and the eubacteria. in general, species of streptococci, propionibacterium propionica, capnocytophaga ochracea and veillonella parvula showed no or negative associations with the other bacteria. the results are consistent with the concept of a special and selective environment occurring in the root canal that is due, in part, to the cooperative as well as antagonistic nature of the relationships between bacteria in the root canal.
TIHT== 
ABHT== 

PMID== 1940739
TI  == reactivity of igg from explant cultures of periapical lesions with implicated microorganisms.
AB  == the presence of igg in periapical inflammatory lesions suggests that immune responses participate in the disease process. the purpose of this investigation was to study the reactivity of igg from the supernatant fluids of explant cultures of periapical lesions with microorganisms implicated in infections of endodontic origin. ninety periapical lesions that had been contiguous with the apex of a root were removed and maintained in explant cultures. a dot-enzyme-linked immunosorbent assay (dot-elisa) was used to demonstrate the presence of igg in the supernatant fluids of the explant cultures reactive with a panel of microorganisms associated with infections of endodontic origin. the percentages of reactivity by dot-elisa follow: bacteroides intermedius (84%), b.  buccae (12%), porphyromonas (bacteroides) gingivalis (50%), p. endodontalis (58%), p. asaccharolyticus (17%), peptostreptococcus micros (44%), p. anaerobius  (26%), eubacterium alactolyticum (34%), fusobacterium nucleatum (14%), and actinomyces israelii (6%). at least one of the three species of b. intermedius, p. gingivalis, or p. endodontalis tested gave a positive dot-elisa with 89% of the supernatant fluids from explant cultures of periapical lesions. a lack of cross reactivity of igg in supernatant fluids from explants of periapical lesions was demonstrated for the four strains of black-pigmented bacteroides/porphyromonas by dot-elisa.
TIHT== 
ABHT== 

PMID== 2108991
TI  == sialidase (neuraminidase) activity among gram-negative anaerobic and capnophilic  bacteria.
AB  == a filter paper spot test with 2'-(4-methylumbelliferyl)-alpha-d-n-acetylneuraminic acid as a substrate was used to study the prevalence of sialidase activity among gram-negative anaerobic and capnophilic bacteria. a total of 567 isolates representing four genera of obligate anaerobes and four genera of capnophilic organisms was tested. sialidase activity was detected in 94% of 66 isolates from the bacteroides fragilis group,  98% of 66 b. bivius isolates, and all isolates of the following species (number of isolates follows species name): b. capillosus, 4; b. levii, 2; b. denticola, 22; b. loescheii, 23; b. melaninogenicus, 32; b. forsythus, 44; and b. buccalis,  2. however, sialidase activity was detected in only 29% of 7 b. buccae isolates,  79% of 14 b. disiens isolates, and 55% of 11 b. oralis isolates. sialidase activity was not detected among any of 13 isolates of b. gracilis, 12 isolates of b. ureolyticus, 61 isolates of b. intermedius, or 26 isolates of b. corporis. porphyromonas (bacteroides) asaccharolytica (20 isolates) and p. endodontalis (8  isolates) did not demonstrate sialidase activity, while 25 isolates of p. gingivalis were sialidase positive. sialidase activity was found in 10 (100%) of  10 isolates of capnocytophaga ochracea of c. sputigena but not in any of 4 c. gingivalis isolates. other gram-negative anaerobic or capnophilic bacteria, including the following, were negative for sialidase activity: fusobacterium nucleatum, 39 isolates; wolinella recta, 19 isolates; eikenella corrodens, 17 isolates; haemophilus aphrophilus, 10 isolates; and actinobacillus actinomycetemcomitans, 10 isolates. these data demonstrate sialidase activity in  several species of the genera bacteroides and porphyromonas and suggest that this characteristic may be useful for identification.
TIHT== 
ABHT== 

