@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 7492110
TI  == comparative antimicrobial activities of the penem wy-49605 (sun5555) against recent clinical isolates from five u.s. medical centers.
AB  == the in vitro activity of wy-49605 (sun5555) (wy) was compared with those of cefaclor, cefixime, and amoxicillin-clavulanic acid against 2,958 consecutive clinical isolates from five medical centers and 402 respiratory pathogens from 18 other facilities. most members of the family enterobacteriaceae were inhibited by wy (mic at which 50% of the isolates are inhibited [mic50], < or = 2.0 micrograms/ml). mic90s of > or = 8.0 micrograms/ml were observed for enterobacter cloacae, serratia spp., and proteus mirabilis. wy was the most active drug against methicillin-susceptible staphylococcus aureus (mic90, 0.12 microgram/ml)  and other coagulase-negative staphylococci (mic90, 4.0 micrograms/ml). the four drugs were not active against nonenteric gram-negative bacilli, methicillin-resistant staphylococcus aureus, and staphylococcus haemolyticus. at  2.0 micrograms/ml, wy inhibited 82% of enterococcus faecalis strains and was equal to or superior to the other drugs against streptococci, haemophilus influenzae, and moraxella catarrhalis.
TIHT== 
ABHT== 

PMID== 1809811
TI  == clinical results of a multicenter study with sulbactam/ampicillin for the treatment of patients with lower respiratory and urinary tract infections.
AB  == a total of 124 patients with lower respiratory tract (44) or urinary tract infections (80) were enrolled in an open, multicenter study to evaluate the efficacy and tolerability of sulbactam/ampicillin, administered at the dosage of  3 g/die by intramuscular route. pretreatment pathogens from patients with lower respiratory tract infections included: streptococcus alpha-haemolyticus in 8 cases, streptococcus beta-haemolyticus in 2 cases, staphylococcus albus in 7 cases, haemophilus influenzae in 7 cases, staphylococcus aureus in 6 cases, klebsiella oxytoca in 5 cases, staphylococcus epidermidis in 3 cases, streptococcus pneumoniae in 3 cases, escherichia coli in 2 cases; in one subject  (2.75%), no microorganisms were isolated. in vitro, 36 isolates (84%) were sensitive to sa and 7 (16%) were resistant. at the end of therapy, all the causative pathogens sensitive to sulbactam/ampicillin were eliminated. in patients with urinary tract infections, pretreatment pathogens were: e. coli in 40 cases, s. albus in 16 cases, proteus mirabilis in 8 cases, enterobacter agglomerans in 6 cases, proteus vulgaris in 3 cases, streptococcus faecalis in 3  cases, streptococcus liquefaciens in 2 cases, pseudomonas aeruginosa in 2 cases.  in vitro, 64 isolates (80%) were sensitive to sulbactam/ampicillin and 16 (20%) were resistant. at the end of therapy, 63 out of the 64 pathogens sensitive to sulbactam/ampicillin were eliminated; in one case the therapy was interrupted due to adverse effect. clinical efficacy: in subjects with lower respiratory tract infections, sulbactam/ampicillin cured 32 patients (72.72%) and ameliorated the clinical status of 8 patients (18.18%); efficacy rate: 90.9%).(abstract truncated at 250 words)
TIHT== 
ABHT== 

PMID== 2685026
TI  == nonculture detection of haemophilus influenzae in sputum with monoclonal antibodies specific for outer membrane lipoprotein p6.
AB  == isolation of haemophilus influenzae from sputum is hampered by overgrowth by other microorganisms or by antibiotic treatment of the patient. to overcome this  problem in the detection of h. influenzae, an in situ immunoperoxidase staining technique was developed with monoclonal antibody (mab) 8bd9, immunoglobulin subclass g2a. mab 8bd9 appeared to be directed to an epitope on the outer membrane lipoprotein p6 of h. influenzae. the species specificity of mab 8bd9 was analyzed by staining isolates from different bacterial species. mab 8bd9 reacted  with all 300 h. influenzae strains tested and with h. aegyptius and h. haemolyticus. twenty-six of 30 h. parainfluenzae strains, other haemophilus species, and other bacterial species often isolated from sputum were not stained. the staining technique was compared with culture of 845 routinely obtained sputum samples from patients with respiratory tract infections. in 829 sputa (98.1%), the results of both techniques were in agreement; 173 were positive for h. influenzae, and 656 were negative. with 14 sputum samples, the staining method gave a positive result for h. influenzae, but the bacterium was not cultured. this could be ascribed to antibiotic treatment of the patient (n = 7), the presence of other mab 8bd9-positive haemophilus species in the sputum (n = 5), and overgrowth by swarming proteus mirabilis or by branhamella catarrhalis. in the immunoperoxidase- and gram-stained smears of two sputum samples, no bacteria  were seen, although some h. influenzae was cultured. on the basis of these results, we conclude that immunoperoxidase staining with mab 8bd9 is a fast and reliable extension of the available detection techniques for h. influenzae.
TIHT== 
ABHT== 

