@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 17189093
TI  == human serum activity of telithromycin, azithromycin and amoxicillin/clavulanate against common aerobic and anaerobic respiratory pathogens.
AB  == telithromycin is a new ketolide antimicrobial with a good in vitro activity against both aerobic and anaerobic respiratory pathogens. in this study, we evaluated the antibacterial activity over time of telithromycin (800mg), azithromycin (500mg), and amoxicillin/clavulanate (875/125mg) in serum following  single oral doses of these agents to 10 healthy subjects. inhibitory and bactericidal titers were determined at 2, 6, 12, and 24h after each dose and the  median titer was used to determine antibacterial activity. against two azithromycin-resistant strains of streptococcus pneumoniae, both telithromycin (mic=0.25 and 0.5 microg/ml) and amoxicillin/clavulanate exhibited inhibitory and cidal activity for at least 6h. all three antibiotics provided prolonged (>or=12h) inhibitory activity against strains of hemophilus influenzae (telithromycin mic=4.0 microg/ml). both telithromycin and amoxicillin/clavulanate exhibited rapid and prolonged inhibitory activity (>or=12h) against each of the anaerobes studied (finegoldia [peptostreptococcus] magna peptostreptococcus micros, prevotella bivia, and prevotella melaninogenica). moreover, both agents provided bactericidal activity against both prevotella species. in this ex vivo pharmacodynamic study, we found that telithromycin provided rapid and prolonged antibacterial activity in serum against macrolide-resistant strains of s. pneumoniae, beta-lactamase-positive and -negative strains of h. influenzae, and common respiratory anaerobic pathogens. these findings suggest that telithromycin could have clinical utility in the treatment of community-acquired mixed aerobic-anaerobic respiratory tract infections, including chronic sinusitis and aspiration pneumonia.
TIHT== 
ABHT== 

PMID== 16276738
TI  == [two cases of bartholin's gland abscesses caused by streptococcus pneumoniae and  haemophilus influenzae].
AB  == most of bartholin's gland abscesses have been thought to be caused by microorganisms found in opportunistic infections. however, we have encountered two very interesting cases of bartholin's gland abscesses caused by streptococcus pneumoniae and haemophilus influenzae, two major pathogens of respiratory tract infections. in the first case, since abscess formation was not observed due to disintegration, cefdinir (cfdn), 300 mg/day, t.i.d. for 5 days was administered.  the treatment improved clinical symptoms, but relapse occurred 3 days after the administration was discontinued. microbiological examination of pus revealed the  presence of streptococcus pneumoniae and finegoldia magna, and it also showed that the isolated s. pneumoniae was penicillin-resistant s. pneumoniae (prsp). after an incision and drainage of abscess, cefteram pivoxil (cftm-pi), 300 mg/day t.i.d. for 7 days, was administered, and the cure was confirmed. in the second case, after an incision and drainage of bartholin's gland abscess, amoxicillin (ampc), 750 mg/day, t.i.d. for 5 days, was administered. the treatment improved clinical symptoms temporarily. however, the symptoms deteriorated 7 days after the operation, and the patient was diagnosed with relapse. microbiological examination of pus revealed the presence of haemophilus influenzae and peptostreptococcus anaerobius, and it also showed that the isolated h. influenzae was beta-lactamase-nonproducing ampicillin-resistant h. influenzae (blnar). after performing additional incision and drainage of abscess again, cftm-pi, 300 mg/day, t.i.d. for 7 days, was administered, and the cure was confirmed. in addition, the analysis of these two cases using pk/pd theory revealed that the time above mic reached 100% with administration of cftm-pi 300mg, t.i.d. suggesting that the dosage is sufficient for treating these infections. there are other cases of external genitalia infections caused by microorganisms usually associated with respiratory tract infections like cases that we are reporting here. therefore, it is necessary to consider a possible infection by drug-resistant bacteria even for a case of external genitalia infection. in addition, it was thought that adjusting dosage and method for administration of antibacterial agents based on pk/pd theory would help to rovide efficient treatment.
TIHT== 
ABHT== 

