@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25190354
TI  == expansion of esbl-producing klebsiella pneumoniae in hospitalized patients: a successful story of international clones (st15, st147, st336) and epidemic plasmids (incr, incfiik).
AB  == the aim of this study was to characterize by a multi-level approach extended-spectrum beta-lactamase (esbl)-producing enterobacteriaceae isolates other than e. coli from portuguese hospitals. eighty-eight esbl-producing clinical isolates (69 klebsiella pneumoniae, 13 enterobacter cloacae complex, 3 klebsiella oxytoca, 1 enterobacter asburiae, 1 proteus mirabilis and 1 serratia marcescens) recovered from hospitals located in the north (a) or centre (b, c) regions during two time periods (2006-7 and 2010) were analyzed. standard methods were used for bacterial identification, antibiotic susceptibility testing, esbl characterization, clonal (pfge, mlst) and plasmid (s1-pfge, i-ceui-pfge, replicon typing, hybridization) analysis. isolates produced mostly ctx-m-15 (47%) or shv-12 (30%), and less frequently other shv- (15%; shv-2, -5, -28, -55, -106) or  tem- (9%; tem-10, -24, -199)-types, with marked local and temporal variations. the increase of ctx-m-15 and diverse shv esbl-types observed in hospital a was associated with the amplification of multidrug-resistant (mdr) k. pneumoniae epidemic clones (st15, st147, st336). shv-12 and tem-type esbls were mostly identified in diverse isolates of different enterobacteriaceae species in hospitals b and c in 2006-7. particular plasmid types were linked to blactx-m-15  (incr or non-typeable plasmids), blashv-12 (incr or inchi2), blashv-28/-55/-106 (incfiik1 or incfiik5), blatem-10 (incl/m) or blatem-24 (inca/c), mostly in epidemic clones. in our country, the amplification of ctx-m-15 and diverse shv-type esbl among non-e. coli enterobacteriaceae is linked to international mdr k. pneumoniae clones (st15, st147, st336) and plasmid types (incr, incfiik). furthermore, we highlight the potential of incfiik plasmids (here firstly associated with blashv-2/-28/-55/-106) to disseminate as antibiotic resistance plasmids.
TIHT== 
ABHT== 

PMID== 24657043
TI  == carbapenemase-producing enterobacteriaceae in a tertiary hospital in madrid, spain: high percentage of colistin resistance among vim-1-producing klebsiella pneumoniae st11 isolates.
AB  == here we describe the carbapenemase genes, genetic relatedness and antimicrobial susceptibility data of 123 carbapenemase-producing enterobacteriaceae (cpe) clinical isolates recovered from 2010 to 2012, comprising klebsiella pneumoniae (n = 79), klebsiella oxytoca (n = 13), serratia marcescens (n = 14), enterobacter cloacae (n = 12), enterobacter asburiae (n = 4) and enterobacter aerogenes (n = 1). vim-1 was the most common carbapenemase (n = 101) followed by kpc-2 (n = 19), oxa-48 (n = 2) and imp-22 (n = 1). among the k. pneumoniae isolates, nine sequence types (sts) were identified but two clones were dominant: st11 (54/79) containing mainly vim-1-producing isolates; and st101 (13/79) constituted by kpc-2-producing strains. pulsed-field gel electrophoresis (pfge) showed a higher  genetic diversity among the remaining enterobacteriaceae. amikacin and fosfomycin were the most active agents with 82.9% and 80.5% susceptibility, respectively. non-susceptibility to tigecycline was detected in 36.5% of strains. overall, colistin resistance was 24.7% and was as high as 47% in enterobacter spp. an increase in colistin resistance from 13.5% to 31.7% was observed among k. pneumoniae isolates during the study period. resistance was focused on st11 since 83.3% of colistin-resistant strains belonged to this clone. the high level of colistin resistance observed in this study is worrying with respect to the already limited therapeutic options for infections caused by multidrug-resistant  gram-negative bacteria.
TIHT== 
ABHT== 

PMID== 23587958
TI  == distribution of extended-spectrum beta-lactamases, ampc beta-lactamases, and carbapenemases among enterobacteriaceae isolates causing intra-abdominal infections in the asia-pacific region: results of the study for monitoring antimicrobial resistance trends (smart).
AB  == the increasing trend of beta-lactam resistance among enterobacteriaceae is a worldwide threat. enterobacteriaceae isolates causing intra-abdominal infections  (iai) from the study for monitoring antimicrobial resistance trends (smart) collected in 2008 and 2009 from the asia-pacific region were investigated. detection of extended-spectrum beta-lactamases (esbls), ampc beta-lactamases, and carbapenemases was performed by multiplex pcr. a total of 699 enterobacteriaceae  isolates with positive genotypic results, included escherichia coli (n = 443), klebsiella pneumoniae (n = 187), enterobacter cloacae (n = 45), klebsiella oxytoca (n = 9), citrobacter freundii (n = 5), proteus mirabilis (n = 3), enterobacter aerogenes (n = 2), morganella morganii (n = 2), and one each of enterobacter asburiae, proteus vulgaris, and providencia rettgeri were analyzed.  nearly 20% of these beta-lactamase-producing enterobacteriaceae isolates were from community-associated iai. ctx-m (588 isolates, including 428 [72.8%] with ctx-m-15) was the most common esbl, followed by shv (n = 59) and tem (n = 4). cmy (n = 110, including 102 [92.7%] with cmy-2) was the most common ampc beta-lactamase, followed by dha (n = 46) and act/mir (n = 40). ndm (n = 65, including 62 [95.4%] with ndm-1) was the most common carbapenemase, followed by imp (n = 7) and oxa (n = 7). isolates from hospital-associated iai had more complicated beta-lactamase combinations than isolates from the community. carbapenemases were all exclusively detected in enterobacteriaceae isolates from  india, except that imp beta-lactamases were also detected in philippines and australia. ctx-m beta-lactamases were the predominant esbls produced by enterobacteriaceae causing iai in the asia-pacific region. emergence of ctx-m-15-, cmy-2-, and ndm-1-producing enterobacteriaceae isolates is of major concern and highlights the need for further surveillance in this area.
TIHT== 
ABHT== 

PMID== 18767694
TI  == bacterial communities on electron-beam pt-deposited electrodes in a mediator-less microbial fuel cell.
AB  == the content of a bacterial consortium found on an electron beam (e-beam) pt-deposited electrode in a mediator-less microbial fuel cell (mfc) using glucose and glutamate as fuel is reported in this paper. the e-beam pt-deposited electrode and electrochemically active bacteria (eab) consortium were developed to improve the mediator-less mfc performance. denaturing gradient gel electrophoresis (dgge), restriction fragment length polymorphism (rflp), and 16s  rrna sequencing were used to identify the eab consortia. sequencing results showed that clone asp-31 was predominant and was similar to aeromonas hydrophila, an fe(iii)-reducing and eab. the phylogenetic tree analysis disclosed the presence of gamma-proteobacteria groups such as aeromonas genus, enterobacter asburiae, and klebsiella oxytoca. these results suggest that mfc performance of the e-beam pt-deposited electrode with aeromonas genus consortia dominated by a.  hydrophila was higher than other mfcs within a short period. with the e-beam pt-deposited electrode and aeromonas genus consortia in the mediator-less mfc, it is possible to increase the efficiency of electron transfer between the bacteria  and the electrode.
TIHT== 
ABHT== 

