@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25995756
TI  == urinary microbiota in patients with prostate cancer and benign prostatic hyperplasia.
AB  == introduction: inflammation is associated with promotion of the initiation of various malignancies, partly due to bacterial infection-induced microenvironmental changes. however, the exact association between microbiota in  urine, seminal fluid and the expressed prostatic secretions and benign prostatic  hypertrophy and prostate cancer is not clear. material and methods: in the present study, we investigated the type of microbiota in the expressed prostatic  secretions (eps) of patients with prostate cancer and benign prostatic hyperplasia (bph) by the polymerase chain reaction-denaturing gradient gel electrophoresis (pcr-dgge) method using universal bacterial primers. in order to  understand the possible association between various bacteria and prostate cancer, quantitative real-time pcr assay was performed to quantify the amount of strains  of bacteria in urine, eps and seminal fluid. results: the prostate cancer group had a significantly increased number of bacteroidetes bacteria, alphaproteobacteria, firmicutes bacteria, lachnospiraceae, propionicimonas, sphingomonas, and ochrobactrum, and a decrease in eubacterium and defluviicoccus  compared to the bph group. the number of escherichia coli in the prostate cancer  group was significantly decreased in urine and increased in the eps and seminal fluid, while the number of enterococcus was significantly increased in the seminal fluid with little change in urine and eps. conclusions: based on these results, we suggest that there are significant changes in the microbial population in eps, urine and seminal fluid of subjects with prostate cancer and bph, indicating a possible role for these bacteria in these two conditions.
TIHT== 
ABHT== 

PMID== 25845411
TI  == identification and functional expression of genes encoding flavonoid o- and c-glycosidases in intestinal bacteria.
AB  == gut bacteria play a crucial role in the metabolism of dietary flavonoids and thereby influence the bioactivity of these compounds in the host. the intestinal  lachnospiraceae strain cg19-1 and eubacterium cellulosolvens are able to deglycosylate c- and o-coupled flavonoid glucosides. growth of strain cg19-1 in the presence of the isoflavone c-glucoside puerarin (daidzein 8-c-glucoside) led  to the induction of two proteins (dfgc, dfgd). heterologous expression of the encoding genes (dfgc, dfgd) in escherichia coli revealed no c-deglycosylating activity in the resulting cell extracts but cleavage of flavonoid o-glucosides such as daidzin (daidzein 7-o-glucoside). the recombinant dfgc and dfgd proteins  were purified and characterized with respect to their quaternary structure, substrate and cofactor specificity. the products of the corresponding genes (dfgc, dfgd) from e. cellulosolvens also catalysed the o-deglycosylation of daidzin following their expression in e. coli. in combination with three recombinant proteins encoded by adjacent genes in e. cellulosolvens (dfga, dfgb,  dfge), dfgc and dfgd from e. cellulosolvens catalysed the deglycosylation of the  flavone c-glucosides homoorientin (luteolin 6-c-glucoside) and isovitexin (apigenin 6-c-glucoside). even intact cells of e. coli expressing the five e. cellulosolvens genes cleaved these flavone c-glucosides and, also, flavonoid o-glucosides to the corresponding aglycones.
TIHT== 
ABHT== 

PMID== 25253126
TI  == the atg16l1-t300a allele impairs clearance of pathosymbionts in the inflamed ileal mucosa of crohn's disease patients.
AB  == objective: crohn's disease (cd) is caused by a complex interplay among genetic, microbial and environmental factors. atg16l1 is an important genetic factor involved in innate immunity, including autophagy and phagocytosis of microbial components from the gut. we investigated the effect of inflammation on the composition of microbiota in the ileal mucosa of cd patients in relation to the atg16l1 risk status. design: biopsies (n=35) were obtained from inflamed and non-inflamed regions of the terminal ileum of 11 cd patients homozygous for the atg16l1 risk allele (atg16l1-t300a) and 9 cd patients homozygous for the atg16l1  protective allele (atg16l1-t300). biopsy dna was extracted and the bacterial composition analysed by pyrosequencing. intracellular survival rates of adherent-invasive escherichia coli (aiec) were analysed by determining colony forming units after exposure to monocytes isolated from healthy volunteers homozygous for the atg16l1 risk or protective allele. results: inflamed ileal tissue from patients homozygous for the atg16l1 risk allele contained increased numbers of fusobacteriaceae, whereas inflamed ileal tissue of patients homozygous for the atg16l1 protective allele showed decreased numbers of bacteroidaceae and  enterobacteriaceae and increased lachnospiraceae. the atg16l1 allele did not affect the bacterial composition in the non-inflamed ileal tissue. monocytes homozygous for the atg16l1 risk allele showed impaired killing of aiec under inflammatory conditions compared with those homozygous for the atg16l1 protective allele. conclusions: cd patients homozygous for the atg16l1-t300a risk allele show impaired clearance of pathosymbionts in ileal inflammation indicating that atg16l1 is essential for effective elimination of pathosymbionts upon inflammation.
TIHT== 
ABHT== 

PMID== 25227462
TI  == susceptibility to campylobacter infection is associated with the species composition of the human fecal microbiota.
AB  == the gut microbiota is essential for human health, but very little is known about  how the composition of this ecosystem can influence and respond to bacterial infections. here we address this by prospectively studying the gut microbiota composition before, during, and after natural campylobacter infection in exposed  poultry abattoir workers. the gut microbiota composition was analyzed with 16s amplicon sequencing of fecal samples from poultry abattoir workers during the peak season of campylobacter infection in sweden. the gut microbiota compositions were compared between individuals who became culture positive for campylobacter and those who remained negative. individuals who became campylobacter positive had a significantly higher abundance of bacteroides (p = 0.007) and escherichia (p = 0.002) species than those who remained culture negative. furthermore, this group had a significantly higher abundance of phascolarctobacterium (p = 0.017) and streptococcus (p = 0.034) sequences than the campylobacter-negative group, which had an overrepresentation of clostridiales (p = 0.017), unclassified lachnospiraceae (p = 0.008), and anaerovorax (p = 0.015) sequences. intraindividual comparisons of the fecal microbiota compositions yielded small differences over time in campylobacter-negative participants, but significant long-term changes were found in the campylobacter-positive group (p < 0.005). the results suggest that the abundance of specific genera in the microbiota reduces resistance to campylobacter colonization in humans and that campylobacter infection can have long-term effects on the composition of the human fecal microbiota. importance: studies using mouse models have made important contributions to our understanding of the role of the gut microbiota in resistance to bacterial enteropathogen colonization. the relative abundances of escherichia coli and bacteroides species have been pointed out as important determinants of susceptibility to gram-negative pathogens in general and campylobacter infection in particular. in this study, we assessed the role of the human gut microbiota in resistance to campylobacter colonization by studying abattoir workers that are heavily exposed to these bacteria. individuals with a certain composition of the gut microbiota became culture positive for campylobacter. as their microbiotas were characterized by high abundances of bacteroides spp. and e. coli, well in line with the findings with mouse models, these bacterial species likely play an important role in colonization resistance  also in humans.
TIHT== 
ABHT== 

PMID== 25059827
TI  == enteric dysbiosis promotes antibiotic-resistant bacterial infection: systemic dissemination of resistant and commensal bacteria through epithelial transcytosis.
AB  == antibiotic usage promotes intestinal colonization of antibiotic-resistant bacteria. however, whether resistant bacteria gain dominance in enteric microflora or disseminate to extraintestinal viscera remains unclear. our aim was to investigate temporal diversity changes in microbiota and transepithelial routes of bacterial translocation after antibiotic-resistant enterobacterial colonization. mice drinking water with or without antibiotics were intragastrically gavaged with ampicillin-resistant (amp-r) nonpathogenic escherichia coli (e. coli) and given normal water afterward. the composition and  spatial distribution of intestinal bacteria were evaluated using 16s rdna sequencing and fluorescence in situ hybridization. bacterial endocytosis in epithelial cells was examined using gentamicin resistance assay and transmission  electromicroscopy. paracellular permeability was assessed by tight junctional immunostaining and measured by tissue conductance and luminal-to-serosal dextran  fluxes. our results showed that antibiotic treatment enabled intestinal colonization and transient dominance of orally acquired amp-r e. coli in mice. the colonized amp-r e. coli peaked on day 3 postinoculation and was competed out  after 1 wk, as evidenced by the recovery of commensals, such as escherichia, bacteroides, lachnospiraceae, clostridium, and lactobacillus. mucosal penetration and extraintestinal dissemination of exogenous and endogenous enterobacteria were correlated with abnormal epithelial transcytosis but uncoupled with paracellular  tight junctional damage. in conclusion, antibiotic-induced enteric dysbiosis predisposes to exogenous infection and causes systemic dissemination of both antibiotic-resistant and commensal enterobacteria through transcytotic routes across epithelial layers. these results may help explain the susceptibility to sepsis in antibiotic-resistant enteric bacterial infection.
TIHT== 
ABHT== 

PMID== 25048562
TI  == influence of green and gold kiwifruit on indices of large bowel function in healthy rats.
AB  == the effects of kiwifruit on large bowel health were investigated in healthy rats. four-week old sprague-dawley rats were given diets containing 10% homogenized green kiwifruit, gold kiwifruit or 10% glucose solution (control) over 4 or 6 wk. green kiwifruit increased the fecal output compared to control. growth of certain bacterial species in cecum was influenced by both green and gold kiwifruit. a significant increase in cecal lachnospiraceae in rats fed the green kiwifruit diet was observed at week 4. at week 6, green and gold kiwifruit diets assisted in improving colonic barrier function by upregulating the expression of mucin (muc)-2, muc3, toll-like receptor (tlr)-4 or trefoil factor-3 genes. gold kiwifruit consumption increased the colonic goblet cells per crypt at week 6. significant negative correlations between e. coli and beta-defensin 1 and tlr4 expression were observed. consuming green and gold kiwifruit for 6 wk significantly altered the biomarkers of large bowel health; indicating that regularly consuming kiwifruit helps attain optimal digestive health.
TIHT== 
ABHT== 

PMID== 24352967
TI  == investigation of bacterial diversity in the feces of cattle fed different diets.
AB  == the objective of this study is to investigate individual animal variation of bovine fecal microbiota including as affected by diets. fecal samples were collected from 426 cattle fed 1 of 3 diets typically fed to feedlot cattle: 1) 143 steers fed finishing diet (83% dry-rolled corn, 13% corn silage, and 4% supplement), 2) 147 steers fed late growing diet (66% dry-rolled corn, 26% corn silage, and 8% supplement), and 3) 136 heifers fed early growing diet (70% corn silage and 30% alfalfa haylage). bacterial 16s rrna gene amplicons were determined from individual fecal samples using next-generation pyrosequencing technology. a total of 2,149,008 16s rrna gene sequences from 333 cattle with at  least 2,000 sequences were analyzed. firmicutes and bacteroidetes were dominant phyla in all fecal samples. at the genus level, oscillibacter, turicibacter, roseburia, fecalibacterium, coprococcus, clostridium, prevotella, and succinivibrio were represented by more than 1% of total sequences. however, numerous sequences could not be assigned to a known genus. dominant unclassified  groups were unclassified ruminococcaceae and unclassified lachnospiraceae that could be classified to a family but not to a genus. these dominant genera and unclassified groups differed (p < 0.001) with diets. a total of 176,692 operational taxonomic units (otu) were identified in combination across all the 333 cattle. only 2,359 otu were shared across 3 diet groups. unifrac analysis showed that bacterial communities in cattle feces were greatly affected by dietary differences. this study indicates that the community structure of fecal microbiota in cattle is greatly affected by diet, particularly between forage- and concentrate-based diets.
TIHT== 
ABHT== 

PMID== 23438335
TI  == sewage reflects the distribution of human faecal lachnospiraceae.
AB  == faecal pollution contains a rich and diverse community of bacteria derived from animals and humans, many of which might serve as alternatives to the traditional  enterococci and escherichia coli faecal indicators. we used massively parallel sequencing (mps) of the 16s rrna gene to characterize microbial communities from  wastewater treatment plant (wwtp) influent sewage from 12 cities geographically distributed across the usa. we examined members of the clostridiales, which included the families clostridiaceae, lachnospiraceae and ruminococcaceae for their potential as sewage indicators. lachnospiraceae was one of the most abundant groups of faecal bacteria in sewage, and several lachnospiraceae high-abundance sewage pyrotags occurred in at least 46 of 48 human faecal samples. clone libraries targeting clostridium coccoides (c. coccoides) in sewage samples demonstrated that lachnospiraceae-annotated v6 pyrotags encompassed the previously reported c. coccoides group. we used oligotyping to profile the genus  blautia within lachnospiraceae and found oligotypes comprised of 24 entropy components that showed patterns of host specificity. these findings suggest that  indicators based on blautia might have the capacity to discriminate between different faecal pollution sources. development of source-specific alternative indicators would enhance water quality assessments, which leads to improved ecosystem health and reduced human health risk due to waterborne disease.
TIHT== 
ABHT== 

PMID== 23437088
TI  == comparative microbial analysis of paired amniotic fluid and cord blood from pregnancies complicated by preterm birth and early-onset neonatal sepsis.
AB  == background: 16s rrna-based genomic analyses have revolutionized our understanding of infectious diseases. many cases which were recognized as "idiopathic" are now  known to have an infectious etiology. here, we present a proof-of-concept study to examine the microbial link between intra-amniotic infection (iai) and early-onset neonatal sepsis (eons). results: using culture independent methods, we analyzed paired amniotic fluid (af) and cord blood (cb) samples from 36 singleton pregnancies complicated by preterm birth (ptb), iai, and/or eons. ptb cases were grouped as 1) group 1- neonatal blood culture-positive eons (n=6). 2)  group 2- neonatal blood culture-negative presumed eons with positive iai (n=16).  3) group 3- neonatal blood culture-negative presumed eons with no iai (n=7); 4) group 4- no eons or iai (n=7). in addition, samples from term healthy deliveries  (n=8) served as technical controls. a total of 31 species (15 non-redundant) were identified in af, of which only 1/3 were cultivated. significantly fewer microorganisms were detected in cb, with a total of 18 species (7 non-redundant)  identified, of which only 2 (escherichia coli, streptococcus agalactiae) were cultivated. of those, bergeyella, fusobacterium nucleatum, and sneathia sanguinegens had not been detected in eons before. the novel species identified in af by pcr include peptoniphilus harei and lachnospiraceae sp. the majority (72%) of cb species were also detected in the matching af, with e. coli and f. nucleatum as the most prevalent. the 16s rrna sequences of paired af and cb were  99.9-100% identical, while no identical sequences were found between different pregnancies. conclusions: previously unrecognized, uncultivated or difficult-to-cultivate species are implicated in eons. microbial species in paired af and cb likely share the same infectious origin. given its prevalence in eons, f. nucleatum should be placed on the same importance scale as e. coli.
TIHT== 
ABHT== 

PMID== 23247126
TI  == temporal variations of the ileal microbiota in intestinal ischemia and reperfusion.
AB  == gastrointestinal bacteria and epithelia contribute to systemic inflammation and infections in critically ill patients, but the gut microbiota in these diseases has not been analyzed dynamically by molecular fingerprinting methods. this study aimed to identify ileal flora dysbiosis pattern and bacterial species that changed significantly in a rat model of intestinal ischemia and reperfusion and illustrate time courses of both epithelial alterations and gut flora variations in the same injury. forty-eight rats were randomized into eight groups (n = 6/group). six groups underwent superior mesenteric artery occlusion for 30 min and were killed at 1, 3, 6, 12, 24, and 72 h following reperfusion, respectively; a group of rats were killed just after anesthesia (control), and a sham-operated  group received 12-h reperfusion. denaturing gradient gel electrophoresis of ileal microbiota showed that gut flora pattern changed early after intestinal ischemia  and reperfusion, differed significantly at 12 h of reperfusion, and then started  to recover toward normal pattern. the specific dysbiosis were characterized by escherichia coli proliferation and lachnospiraceae and lactobacilli reduction. these bacteria that contributed most were identified by principal component analysis and sequencing and confirmed by real-time polymerase chain reaction. in  addition, alterations of ileal microbiota followed epithelial changes in the time course of reperfusion.
TIHT== 
ABHT== 

PMID== 22890996
TI  == suppression of clostridium difficile in the gastrointestinal tracts of germfree mice inoculated with a murine isolate from the family lachnospiraceae.
AB  == the indigenous microbial community of the gastrointestinal (gi) tract determines  susceptibility to clostridium difficile colonization and disease. previous studies have demonstrated that antibiotic-treated mice challenged with c. difficile either developed rapidly lethal c. difficile infection or were stably colonized with mild disease. the gi microbial community of animals with mild disease was dominated by members of the bacterial family lachnospiraceae, while the gut community in moribund animals had a predominance of escherichia coli. we  investigated the roles of murine lachnospiraceae and e. coli strains in colonization resistance against c. difficile in germfree mice. murine lachnospiraceae and e. coli isolates were cultured from wild-type mice. the ability of each of these isolates to interfere with c. difficile colonization was tested by precolonizing germfree mice with these bacteria 4 days prior to experimental c. difficile challenge. mice precolonized with a murine lachnospiraceae isolate, but not those colonized with e. coli, had significantly  decreased c. difficile colonization, lower intestinal cytotoxin levels and exhibited less severe clinical signs and colonic histopathology. infection of germfree mice or mice precolonized with e. coli with c. difficile strain vpi 10463 was uniformly fatal by 48 h, but only 20% mortality was seen at 2 days in mice precolonized with the lachnospiraceae isolate prior to challenge with vpi 10463. these findings confirm that a single component of the gi microbiota, a murine lachnospiraceae isolate, could partially restore colonization resistance against c. difficile. further study of the members within the lachnospiraceae family could lead to a better understanding of mechanisms of colonization resistance against c. difficile and novel therapeutic approaches for the treatment and prevention of c. difficile infection.
TIHT== 
ABHT== 

PMID== 21803887
TI  == lachnospiraceae and bacteroidales alternative fecal indicators reveal chronic human sewage contamination in an urban harbor.
AB  == the complexity of fecal microbial communities and overlap among human and other animal sources have made it difficult to identify source-specific fecal indicator bacteria. however, the advent of next-generation sequencing technologies now provides increased sequencing power to resolve microbial community composition within and among environments. these data can be mined for information on source-specific phylotypes and/or assemblages of phylotypes (i.e., microbial signatures). we report the development of a new genetic marker for human fecal contamination identified through microbial pyrotag sequence analysis of the v6 region of the 16s rrna gene. sequence analysis of 37 sewage samples and comparison with database sequences revealed a human-associated phylotype within the lachnospiraceae family, which was closely related to the genus blautia. this  phylotype, termed lachno2, was on average the second most abundant fecal bacterial phylotype in sewage influent samples from milwaukee, wi. we developed a quantitative pcr (qpcr) assay for lachno2 and used it along with the qpcr-based assays for human bacteroidales (based on the hf183 genetic marker), total bacteroidales spp., and enterococci and the conventional escherichia coli and enterococci plate count assays to examine the prevalence of fecal and human fecal pollution in milwaukee's harbor. both the conventional fecal indicators and the human-associated indicators revealed chronic fecal pollution in the harbor, with  significant increases following heavy rain events and combined sewer overflows. the two human-associated genetic marker abundances were tightly correlated in the harbor, a strong indication they target the same source (i.e., human sewage). human adenoviruses were routinely detected under all conditions in the harbor, and the probability of their occurrence increased by 154% for every 10-fold increase in the human indicator concentration. both lachno2 and human bacteroidales increased specificity to detect sewage compared to general indicators, and the relationship to a human pathogen group suggests that the use  of these alternative indicators will improve assessments for human health risks in urban waters.
TIHT== 
ABHT== 

PMID== 21742925
TI  == identification and characterization of potential performance-related gut microbiotas in broiler chickens across various feeding trials.
AB  == three broiler feeding trials were investigated in order to identify gut bacteria  consistently linked with improvements in bird performance as measured by feed efficiency. trials were done in various geographic locations and varied in diet composition, broiler breed, and bird age. gut microbial communities were investigated using microbial profiling. eight common performance-linked operational taxonomic units (otus) were identified within both the ilea (180, 492, and 564-566) and ceca (140-142, 218-220, 284-286, 312, and 482) across trials. otu 564-566 was associated with lower performance, while otus 140-142, 482, and 492 were associated with improved performance. targeted cloning and sequencing of these eight otus revealed that they represented 26 bacterial species or phylotypes which clustered phylogenetically into seven groups related  to lactobacillus spp., ruminococcaceae, clostridiales, gammaproteobacteria, bacteroidales, clostridiales/lachnospiraceae, and unclassified bacteria/clostridia. where bacteria were identifiable to the phylum level, they belonged predominantly to the firmicutes, with bacteroidetes and proteobacteria also identified. some of the potential performance-related phylotypes showed high sequence identity with classified bacteria (lactobacillus salivarius, lactobacillus aviarius, lactobacillus crispatus, faecalibacterium prausnitzii, escherichia coli, gallibacterium anatis, clostridium lactatifermentans, ruminococcus torques, bacteroides vulgatus, and alistipes finegoldii). the 16s rrna gene sequence information generated will allow quantitative assays to be developed which will enable elucidations of which of these phylotypes are truly performance related. this information could be used to monitor strategies to improve feed efficiency and feed formulation for optimal gut health.
TIHT== 
ABHT== 

PMID== 20668486
TI  == muramidases found in the foregut microbiome of the tammar wallaby can direct cell aggregation and biofilm formation.
AB  == we describe here the role of muramidases present in clones of metagenomic dna that result in cell aggregation and biofilm formation by escherichia coli. the metagenomic clones were obtained from uncultured lachnospiraceae-affiliated bacteria resident in the foregut microbiome of the tammar wallaby. one of these fosmid clones (p49c2) was chosen for more detailed studies and a variety of genetic methods were used to delimit the region responsible for the phenotype to  an open reading frame of 1425 bp. comparative sequence analysis with other fosmid clones giving rise to the same phenotype revealed the presence of muramidase homologues with the same modular composition. phylogenetic analysis of the fosmid sequence data assigned these fosmid inserts to recently identified, but uncultured, phylogroups of lachnospiraceae believed to be numerically dominant in the foregut microbiome of the tammar wallaby. the muramidase is a modular protein containing putative n-acetylmuramoyl-l-alanine amidase and an endo-beta-n-acetylglucosaminidase catalytic module, with a similar organization and functional properties to some staphylococcal autolysins that also confer adhesive properties and biofilm formation. we also show here that the cloned muramidases result in the production of extracellular dna, which appears to be the key for biofilm formation and autoaggregation. collectively, these findings suggest that biofilm formation and cell aggregation in gut microbiomes might occur via the concerted action of carbohydrate-active enzymes and the production  of extracellular dna to serve as a biofilm scaffold.
TIHT== 
ABHT== 

PMID== 19395520
TI  == effect of dietary protein level on growth performance, indicators of enteric health, and gastrointestinal microbial ecology of weaned pigs induced with postweaning colibacillosis.
AB  == the effect of dietary cp level on performance, enteric health, and gastrointestinal microbial ecology of weaned pigs challenged with enterotoxigenic escherichia coli (etec) k88 was investigated in a 14-d study. forty weaned pigs (bw = 5.32 +/- 0.24 kg, mean +/- sd), housed 4 per pen, were randomly assigned to 2 diets (5 pens/diet): 1) 22.5% cp or 2) 17.6% cp supplemented with aa. diets contained the same amount of me and standardized ileal digestible lys, met + cys, thr, and trp based on the ideal protein ratio. isoleucine and val were added to the 17.6% cp diet up to the level in the 22.5% cp diet. on d 8 postweaning, pigs  were challenged with 6 ml of etec suspension (10(10) cfu/ml) by gavage. feed disappearance and bw were measured on d 7, 9, 10, 12, and 14 for determination of adg, adfi, and g:f. one pig from each pen was serially slaughtered on -1, 3, and  7 d postchallenge (10 pigs/d of slaughter) to evaluate gut morphology, and gut microbial ecology and metabolites. pigs fed the 22.5% cp diet had greater (p < 0.05) adg and g:f than those fed the 17.6% cp diet before infection, but performance was similar between the 2 diets after etec challenge and overall. on  d 3 after challenge, etec was not detected in the ileal digesta of pigs fed the 17.6% cp diet but was detected in the ileal digesta of 80% of pigs fed the 22.5%  cp diet (5.22 +/- 1.07 cfu/g, mean +/- sd). pigs fed the 17.6% cp diet had a greater (p < 0.01) prevalence of order clostridiales (73 vs. 50%), family lachnospiraceae (43 vs. 18%), and genus roseburia (13 vs. 3%) in the colon digesta 7 d after challenge compared with those fed the 22.5% cp diet. the richness and diversity of bacteria in the colon digesta were less (p < 0.05) in pigs fed the 17.6% cp diet than in those fed the 22.5% cp diet at -1, 3, and 7 d  postchallenge. pigs fed the 22.5% cp diet had greater (p < 0.05) ammonia n concentration in the colon digesta on -1 and 7 d after challenge compared with those fed the 17.6% cp diet. pigs fed the 22.5% cp diet had deeper (p < 0.05) crypts 1 d before challenge, shorter villi 3 d after challenge, and reduced villus height:crypt depth 1 d before and 3 d after challenge compared with those  fed the 17.6% cp diet. in conclusion, a reduction in the dietary cp level of weaned pigs from 22.5 to 17.6% with aa supplementation impaired growth performance before, but not after, the etec challenge and increased the relative  composition of butyrate producing bacteria in the colon digesta after etec challenge.
TIHT== 
ABHT== 

