@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23329243
TI  == antibacterial effect of water-soluble chitosan on representative dental pathogens streptococcus mutans and lactobacilli brevis.
AB  == dental caries is still a major oral health problem in most industrialized countries. the development of dental caries primarily involves lactobacilli spp.  and streptococcus mutans. although antibacterial ingredients are used against oral bacteria to reduce dental caries, some reports that show partial antibacterial ingredients could result in side effects. objectives: the main objective is to test the antibacterial effect of water-soluble chitosan while the evaluation of the mouthwash appears as a secondary aim. material and methods: the chitosan was obtained from the application chemistry company (taiwan). the authors investigated the antibacterial effects of water-soluble chitosan against  oral bacteria at different temperatures (25-37 masculinec) and ph values (ph 5-8), and evaluated the antibacterial activities of a self-made water-soluble chitosan-containing mouthwash by in vitro and in vivo experiments, and analyzed the acute toxicity of the mouthwashes. the acute toxicity was analyzed with the pollen tube growth (ptg) test. the growth inhibition values against the logarithmic scale of the test concentrations produced a concentration-response curve. the ic50 value was calculated by interpolation from the data. results: the effect of the ph variation (5-8) on the antibacterial activity of water-soluble chitosan against tested oral bacteria was not significant. the maximal antibacterial activity of water-soluble chitosan occurred at 37 masculinec. the minimum bactericidal concentration (mbc) of water-soluble chitosan on streptococcus mutans and lactobacilli brevis were 400 microg/ml and 500 microg/ml, respectively. only 5 s of contact between water-soluble chitosan and oral bacteria attained at least 99.60% antibacterial activity at a concentration  of 500 microg/ml. the water-soluble chitosan-containing mouthwash significantly demonstrated antibacterial activity that was similar to that of commercial mouthwashes (>99.91%) in both in vitro and in vivo experiments. in addition, the  alcohol-free mouthwash exhibited no cytotoxicity and no oral stinging. to the best of our knowledge, this was the first study to combine in vitro and in vivo investigations to analyze the antibacterial properties of water-soluble chitosan-containing mouthwash. conclusions: this study illustrated that water-soluble chitosan may be a viable alternative to commercial mouthwashes in the future.
TIHT== 
ABHT== 

PMID== 11393751
TI  == lactobacilli in human dental caries and saliva.
AB  == samples (98 plaque and 72 saliva) from 93 patients with dental caries were investigated for lactobacillus species which comprised 65 (62.5%) of 104 isolates. yeasts (20.1%), streptococcus spp. (8.7%), staphylococcus spp. (2.9%) and a few unidentified species (5.8%), were also found. the lactobacillus isolates were l. brevis (24.6%) l. fermentum (18.5%) l. casei (16.9%), l. delbrueckii (15.4%), l. plantarum (9.23%), l. acidophilus (7.69%), l. jensenii (4.62%), l. salivarius (1.54%) and l. gasseri (1.54%). the most common species was l. brevis (24.6%). the strains tested for beta-lactamase production showed 75.4% positive. all the lactobacillus strains were tested for bacteriocin production against escherichia coli, salmonella spp., shigella dysenteriae, s. sonnei, klebsiella spp. and campylobacter sp. all the lactobacilli except l. jensenii produced bacteriocin against at least one of the indicator organisms. the involvement of lactobacillus in dental caries was established, although its role and mechanism is not well understood. the ability of lactobacillus spp. to protect their host against certain diseases by inhibiting the growth of potential pathogens was evident.
TIHT== 
ABHT== 

PMID== 8868433
TI  == inducer expulsion and the occurrence of an hpr(ser-p)-activated sugar-phosphate phosphatase in enterococcus faecalis and streptococcus pyogenes.
AB  == inducer expulsion, a phenomenon in which rapidly metabolizable sugars cause cytoplasmic dephosphorylation and efflux of pre-accumulated sugar-phosphates (sugar-p), has been documented for streptococcus pyogenes, streptococcus bovis, and lactococcus lactis, but not for other gram-positive bacteria. using intact cells and membrane vesicles, we show that enterococcus faecalis exhibits both inducer exclusion and inducer expulsion, and that the latter phenomenon is dependent on the metabolite-activated atp-dependent hpr(ser) kinase that phosphorylates ser-46 in hpr of the phosphotransferase system. a small, heat-stable, membrane-associated, hpr(ser-p)-activated sugar-p phosphatase (pase  ii), previously identified only in lc. lactis, is shown to be present in extracts of enterococcus faecalis and streptococcus pyogenes but not in those of staphylococcus aureus, streptococcus mutans, streptococcus salivarius, or bacillis subtilis, organisms that do not exhibit the inducer expulsion phenomenon. further, lactobacillus brevis, an organism that exhibits inducer expulsion by a different mechanism, also apparently lacks pase ii. the results reveal that pase ii is present in those organisms that exhibit the coupled sugar-p hydrolysis/expulsion mechanism but not those that lack this mechanism. they provide correlative evidence that pase ii initiates inducer expulsion in species of enterococci, streptococci and lactococci.
TIHT== 
ABHT== 

PMID== 2341169
TI  == microflora associated with experimental root surface caries in humans.
AB  == this study describes the microflora from actively progressing root surface caries lesions, in which mineral loss had been determined by quantitative microradiography. the caries lesions were produced experimentally in root surface specimens from human molars inserted in lower partial dentures carried for 3 months by six elderly individuals. a total of 780 bacterial isolates were identified from 13 plaque samples, collected with a punch technique, and six dentin samples. the composition of the microflora showed distinct individual differences. the microflora from plaque samples associated with the highest mineral loss was dominated by either actinomyces viscosus or a combination of mutans streptococci (serotypes c, d, and f) and lactobacillus species (l. casei and l. brevis). plaque from root surfaces with less pronounced mineral loss harbored a more complex microflora comprising gram-positive rods, mutans streptococci, streptococcus mitis biovar 1, veillonella spp., gram-negative rods, and low numbers of lactobacilli. in the latter samples, individual variations in  the proportions of mutans streptococci (serotypes c, d, and g), actinomyces species (a. viscosus and a. naeslundii), and veillonella parvula biotypes were observed. these findings suggest that certain species or combinations of species  are more cariogenic than others and that dominance of single acidogenic species in particular is conducive to high caries activity.
TIHT== 
ABHT== 

PMID== 2632598
TI  == the effect of ph on the sensitivity of species of lactobacillus to chlorhexidine  and the antibiotics minocycline and spiramycin.
AB  == the purpose of this study was to determine the sensitivity of a range of lactobacillus species to chlorhexidine, minocycline, and spiramycin, at a range of ph from 5.0 to 7.4. strains of streptococcus were also tested for their sensitivity to chlorhexidine, as a comparison between the genera. there were both inter- and intra-species variations in the sensitivity of these strains to chlorhexidine. the strains tested were sensitive at ph 6.7 to the following levels of chlorhexidine (micrograms/ml): l. casei (6 strains), 10-60; l. plantarum (4 strains), 40; l. fermentum (13 strains), 2-20; l. brevis (1 strain), 10; and l. acidophilus (3 strains), 10-60. the streptococcus species were sensitive to 1-4 micrograms/ml (13 strains); 4-10 micrograms/ml (3 strains); and  10-20 micrograms/ml (2 strains). one strain was able to survive 20 micrograms/ml. chlorhexidine was found to be less effective at lower ph levels. the following examples show sensitivity (micrograms/ml) at ph 6.5 followed by sensitivity at ph 5.0: l. casei (atcc 15008), 40,60; l. plantarum (ch 374), 40,100; l. fermentum (ch 324) 10,40; l. acidophilus (atcc 4356), 10,40; and s. mutans (bm 52), 2,2. all of the strains of lactobacillus tested with spiramycin were resistant at ph 5.0. minocycline was less affected by changes in ph, but at ph 7.4 lactobacillus  strains were more resistant to minocycline as compared with spiramycin. both of these antibiotics are bacteriostatic, and therefore may have a more limited effect than a bactericidal agent such as chlorhexidine. the lactobacillus strains tested required higher concentrations of chlorhexidine than did the strains of streptococcus for a killing effect in vitro.
TIHT== 
ABHT== 

