@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 20719993
TI  == suppression of human immunodeficiency virus type 1 replication in macrophages by  commensal bacteria preferentially stimulating toll-like receptor 4.
AB  == protection from primary human immunodeficiency virus type 1 (hiv-1) infection has not yet been accomplished by vaccines inducing hiv-1-specific acquired immunity.  nevertheless, it has been reported that a small subgroup of women remain resistant to hiv-1 infection under natural conditions. if similar conditions can  be induced in uninfected individuals, it will contribute the first line of protection against hiv-1 infection, and also improve the effects of anti-hiv-1 vaccines. we reasoned that innate immunity may be involved in the resistance to hiv-1 infection, and investigated the effects of various toll-like receptor (tlr) ligands and commensal bacteria on hiv-1 replication in macrophages, one of the initial targets of hiv-1 infection and also the main mediators of innate immunity. we established the hiv-1 reporter monocytic cell line, thp-1/nl4-3luc,  which could be differentiated into macrophage-like cells in vitro. in these cells, stimulation of tlr3 and tlr4 by their ligands suppressed hiv-1 expression  partly through type i interferon (ifn). among the commensal bacteria tested, escherichia coli, veillonella parvula and neisseria mucosa suppressed hiv-1 expression, whereas lactobacillus acidophilus, prevotella melaninogenica, p. bivia and mycobacterium smegmatis enhanced it. the bacteria with suppressive effects preferentially stimulated tlr4, whereas the ones with enhancing effects stimulated tlr2. neutralizing antibodies against tlr4 and ifn-alpha/beta receptor abrogated bacterially mediated hiv-1 suppression. suppressive effects of e. coli, v. parvula and n. mucosa on hiv-1 replication were reproducible in primary monocyte-derived macrophages following acute hiv-1 infection. these findings suggest that certain commensal bacteria preferentially stimulating tlr4 potentially produce local environments resistant to hiv-1 infection.
TIHT== 
ABHT== 

PMID== 19207737
TI  == distribution of selected cariogenic bacteria in five different intra-oral habitats in young children.
AB  == background: knowledge of the colonization patterns and composition of the oral microbiota can lead to a better understanding of disease initiation. aim: the aim of this study was to examine the distribution of selected cariogenic bacteria in  samples from five different oral habitats in young greek children. design: ninety-three children 3-12 years old (mean + sd 7.9 +/- 2.5) (60.2% male, 39.8% female) participated and split into three different age groups: primary (3-6 years), early mixed (6-9 years), and mixed dentition (9-12 years). samples for bacterial enumeration were taken from saliva, supragingival and subgingival plaque, tongue dorsum, and soft tissues from each child, and were further analysed using checkerboard dna-dna hybridization. results: mean counts and proportions of all the test bacteria differed significantly among sample locations. cariogenic bacteria were present in almost all healthy children. mean  proportions of streptococcus mutans isolated from soft tissue and streptococcus sanguinis from soft tissue, subgingival and saliva samples increased significantly with age, whereas the opposite was seen for lactobacillus acidophilus. conclusions: cariogenic bacteria were present in almost all young children. soft tissues, saliva, and tongue were more often colonized by cariogenic streptococcal species than teeth. these surfaces may serve as reservoirs for oral pathogens, requiring attention during preventive interventions.
TIHT== 
ABHT== 

