@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23022427
TI  == development of bacteria identification array to detect lactobacilli in thai fermented sausage.
AB  == to improve the quality and safety of food products, there is a need in the food industry for a reliable method for simultaneously monitoring multiple bacterial strains. microarray technology is a high-throughput screening approach that can provide an alternative for bacteria detection. a total of 164 bacteria-specific probes were designed from 16s rrna gene sequences to target 12 bacteria species,  including lactic acid bacteria and selected food pathogens. after fabrication onto aminosilane-coated slides, hybridization conditions of the array were optimized for high specificity and signal intensities. the array was applied to detect 12 bacteria individually and was specific to all (lactobacillus plantarum  group, l. fermentum, l. brevis, l. delbrueckii, l. casei, l. sakei, escherichia coli, staphylococcus aureus, micrococcus luteus and listeria monocytogenes) except l. animalis. multiplex detection using mixed bacteria populations was evaluated and accurate detection was obtained. the feasibility of using the array to detect the target bacteria in food was evaluated with thai fermented sausages  (nham). meat samples were collected on days 2, 3 and 7 after natural fermentation, l. plantarum-inoculated fermentation and l. brevis-inoculated fermentation before applying to the array. the naturally-fermented nham contained l. sakei, l. delbrueckii, l. plantarum and l. fermentum. the l. plantarum-inoculated nham showed a similar lactic acid bacteria population but the positive signal level for l. plantarum was higher than with natural fermentation. the l. brevis-inoculated nham contained l. brevis, l. plantarum, l. delbrueckii and l. fermentum. the array was used to monitor bacteria population dynamics during the fermentation process. the naturally-fermented and l. brevis-inoculated samples showed lower positive signal levels of l. plantarum on  day 2, but signals gradually increased on days 3 and 7 of the fermentation. in contrast, the l. plantarum-started fermentation showed a higher positive signal level on day 2 than the natural and l. brevis-inoculated samples, and the positive signal level remained high on days 3 and 7. the bacteria identification  array was proven to be useful as an alternative method to detect and monitor target bacteria populations during food fermentation.
TIHT== 
ABHT== 

PMID== 16943094
TI  == microbiological characteristics of "androlla", a spanish traditional pork sausage.
AB  == counts of total aerobic mesophilic microflora, lactic acid bacteria, salt-tolerant microflora, enterobacteriaceae, enterococci, moulds and yeasts, and staphylococci, and some physico-chemical parameters (total solids, nacl and nitrate contents and ph and aw values) were determined in 20 units of "androlla", a traditional dry-fermented sausage made in the nw of spain. in general, high counts of all the investigated microbial groups were observed, with average values of 8.99 +/- 0.46 log cfu/g for the total aerobic mesophilic microflora, 9.11 +/- 0.16 log cfu/g for the lactic acid bacteria, 6.87 +/- 0.68 log cfu/g for the salt-tolerant microflora, 2.80+/-1.85 log cfu/g for the enterobacteriaceae, 3.25 +/- 1.86 log cfu/g for the enterococci, 4.30 +/- 1.73 log cfu/g for the moulds and yeasts, and 3.62 +/- 0.60 log cfu/g for the staphylococci. from mrs agar, spc agar + 7.5% nacl, vrbg agar, and kaa agar, 10 colonies were randomly taken from each androlla unit and from each culture medium. a total of 200 strains per culture medium were then identified using the classical methods. among the isolates from mrs agar, lactobacillus sakei predominated, followed by lactobacillus curvatus, lactobacillus alimentarius and lactobacillus plantarum. of the 200 isolates obtained from spc agar + 7.5% nacl, only 56 strains belonged  to the staphylococcaceae or micrococcaceae families. among the staphylococcaceae, staphylococcus xylosus was the main species, followed by staph. epidermidis; staph. equorum, staph. capitis and staph. saprophyticus were isolated in very low proportions. among the micrococcaceae, micrococcus luteus predominated, followed  by micrococcus lylae, kocuria varians and kocuria kristinae. of the 150 isolates  obtained from vrbg agar, hafnia alvei was the main species, followed by serratia  liquefaciens and enterobacter amnigenus; six isolates were identified as salmonella. among the 190 isolates obtained from kaa agar, 122 were considered enterococci; 20 isolates were identified as enterococcus faecium, one as enterococcus faecalis and 101 as enterococcus inter faecalis-faecium.
TIHT== 
ABHT== 

PMID== 14963617
TI  == evaluation of agar diffusion bioassay for nisin quantification.
AB  == the agar diffusion bioassay is the most widely used method for the quantification of nisin, due to its high sensitivity, simplicity, and cost-effectiveness. this method is based on the measurement of the inhibition zone produced in nisin-sensitive microorganisms. the size of the zone is affected by many factors, such as nisin-sensitive strain, amount of added agar and surfactant, and pre-diffusion step. this research aims to evaluate the effects of nisin-sensitive strains and pre-diffusion on the accuracy and precision of nisin quantification.  three strains of nisin-sensitive microorganisms (micrococcus luteus, lactobacillus sakei, brochothrix thermosphacta) were tested along with three different incubation processes. the best combination was the method using l. sakei as an indicator strain with pre-diffusion at 4 degrees c for 24 h. compared with m. luteus and b. thermosphacta, l. sakei gave more accurate and reproducible results. moreover, the pre-diffusion step resulted in larger inhibition zones and more precise results. finally, the best combination was validated and compared with the method that is usually used and the result showed that the method using  l. sakei with pre-diffusion gave more accurate and precise results.
TIHT== 
ABHT== 

