@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 24779583
TI  == pathogen exclusion properties of canine probiotics are influenced by the growth media and physical treatments simulating industrial processes.
AB  == aims: manufacturing process used in preparation of probiotic products may alter beneficial properties of probiotics. the effect of different growth media and inactivation methods on the protective properties of canine-originated probiotic  bacteria against adhesion of canine enteropathogens was investigated. methods and results: three established dog probiotics, lactobacillus fermentum vet9a, lactobacillus plantarum vet14a and lactobacillus rhamnosus vet16a, and their mixture were assessed using the dog mucus pathogen exclusion model. the pathogens used were enterococcus canis, salmonella enterica serovar typhimurium and clostridium perfringens. the effect of growth media, one reflecting laboratory and the other manufacture conditions, and viability (viable and heat inactivated, 80 degrees c per 30 min) on the pathogen exclusion properties of probiotics were  characterized. greater pathogen exclusion percentages were noted for probiotics growing in conditions reflecting manufacture when compared to laboratory (p < 0.05). inactivation of probiotics by heat (80 degrees c per 30 min) increased pathogen exclusion compared with their viable forms (p < 0.05). conclusions: manufacturing process conditions such as growth media, incubation temperature and pretreatment methods may significantly affect the protective properties of the tested strains. significance and impact of the study: growing conditions and pretreatment methods should be carefully considered when designing new probiotics to reduce the risk of common infections in dogs. the studied probiotics are promising potential feed additives for dogs.
TIHT== 
ABHT== 

PMID== 23155014
TI  == reduced lesions in chickens with clostridium perfringens-induced necrotic enteritis by lactobacillus fermentum 1.20291.
AB  == previous studies have demonstrated that lactobacillus has anti-inflammatory properties, but the protective functions of lactobacillus and mechanisms of inhibition of necrotic enteritis (ne) in the intestines of chickens have not been fully clarified. in the present study, we selected a probiotic strain, lactobacillus fermentum 1.2029, which has good adhesive ability and a high survival rate in low ph and bile salts. the objective of this study was to examine the anti-inflammatory properties of l. fermentum 1.2029 against ne in chickens. two hundred forty 1-d-old male arbor acres broilers were blocked into 3 experimental groups as follows: (i) nonchallenge control group, (ii) clostridium  perfringens challenge group, and (iii) c. perfringens challenge + l. fermentum 1.2029 group. lactobacillus fermentum 1.2029 (1.0 ml/d, 10(8) cfu/ml) was orally  administered daily to group iii during the course of the experiment, and all uninfected control chickens were inoculated accordingly with the same volume of pbs. clostridium perfringens (0.5 ml on d 1 and 1.0 ml on d 14 to 21, 10(8) cfu/ml) was administered to chickens in group ii. at 28 d, scoring of gross ne lesions was performed. ileal segments of approximately 2 cm from 24 chickens in each experimental group were collected and fixed in 4% (wt/vol) neutral-buffered  formalin solution for histological scoring. ileal mucosa samples were also collected for mrna analysis by real-time pcr. the results showed that l. fermentum 1.2029 reduced the severity of ne lesions in chickens. histological scores revealed that l. fermentum 1.2029 also reduced the inflammation damage of  ne in chickens. changes in cytokines and toll-like receptors (tlr) were determined, and l. fermentum 1.2029 was found to increase interleukin-10 levels and reduce interferon-gamma and tlr2 levels in ne-infected chickens. the results  showed that l. fermentum 1.2029 was able to regulate the intestinal mucosal immune response and ameliorate inflammation by changing expression levels of cytokines and tlr.
TIHT== 
ABHT== 

PMID== 21602389
TI  == effect of lactobacillus fermentum on beta2 toxin production by clostridium perfringens.
AB  == clostridium perfringens, although a member of the normal gut flora, is also an important cause of intestinal disease in animals and, to a lesser extent, in humans. disease is associated with the production of one or more toxins, and little is known about environmental influences on the production of these toxins. one of the health-promoting effects of lactic acid bacteria (lab) is the establishment and maintenance of a low ph in the intestine since an acidic environment inhibits the growth of many potentially harmful bacteria. here, the effect of the lab lactobacillus fermentum on beta2 toxin production by c. perfringens is described. coculturing of c. perfringens with l. fermentum showed  that under in vitro conditions, l. fermentum was capable of silencing beta2 toxin production by c. perfringens without influencing bacterial viability. the reduction in toxin production was shown to be most likely a result of the decline in ph. quantitative pcr showed that the reduction in beta2 toxin production was due to a decrease in cpb2 mrna. these results suggest that in the intestine, the  production of beta2 toxin by c. perfringens might be regulated by other members of the normal intestinal flora.
TIHT== 
ABHT== 

PMID== 21272950
TI  == analysis of bacterial communities of traditional fermented west african cereal foods using culture independent methods.
AB  == in this study, the microbial composition of kunu-zaki and ogi, two popular foods  in nigeria produced after natural, uncontrolled fermentation of cereals, was assessed by culture-independent molecular profiling methods. in particular, pcr-denaturing gradient gel electrophoresis and construction of 16s rrna gene clone libraries revealed the presence of diverse bacterial communities. dna sequencing of the highly variable v3 region of the 16s rrna genes obtained from pcr-dgge fingerprints identified species related to weissella confusa, lactobacillus fermentum, lactobacillus amylolyticus, lactobacillus delbrueckii subsp. bulgaricus, bacillus spp. and lactococcus lactis spp lactis from food samples obtained from northern and southern geographical locations. a more comprehensive analysis of 272 full-length 16s rrna gene inserts revealed that 70% of them were assigned to the lactobacillaceae family and 19% to the streptococcaceae family. interestingly, sequences associated with a particular food type were also identified. for example, l. plantarum, l. pantheris and l. vaccinostercus were found in ogi but not in kunu-zaki while w. confusa, streptococcus lutetiensis and streptococcus gallolyticus subsp. macedonicus were  found in kunu-zaki but not in ogi. phylotypes corresponding to potentially pathogenic bacteria, such as clostridium perfringens and bacillus cereus were also detected highlighting the need for controlled fermentation processes.
TIHT== 
ABHT== 

PMID== 17313661
TI  == identification of glucose-fermenting bacteria present in an in vitro model of the human intestine by rna-stable isotope probing.
AB  == 16s rrna-based stable isotope probing (sip) and nuclear magnetic resonance (nmr)  spectroscopy-based metabolic profiling were used to identify bacteria fermenting  glucose under conditions simulating the human intestine. the tim-2 in vitro model of the human intestine was inoculated with a gi tract microbiota resembling that  of the small intestine, to which subsequently 4, 20 or 40 mm of [u-(13)c]-glucose were added. rna was extracted from lumen samples after 0 (control), 1, 2 and 4 h  and subjected to density-gradient ultracentrifugation. phylogenetic analysis of unlabeled 16s rrna revealed a microbial community dominated by lactic acid bacteria and clostridium perfringens. distinct (13)c-incorporation into bacterial rna was only observed for the 40-mm addition. 16s rrna fingerprinting showed an activity drop of lactobacillus fermentum after glucose addition, while streptococcus bovis and c. perfringens were identified as the most active glucose-fermenters. accordingly, nmr analysis identified lactate, acetate, butyrate and formate as the principal fermentation products, constituting up to 91% of the (13)c-carbon balance. rna-sip combined with metabolic profiling allowed us to detect differential utilization of a general model carbohydrate, indicating that this approach holds great potential to identify bacteria involved in the fermentation of dietary relevant oligo- and polymeric carbohydrates in the human intestine.
TIHT== 
ABHT== 

PMID== 16632004
TI  == a fermentation assay to evaluate the effectiveness of antimicrobial agents on gut microflora.
AB  == the measurement of gas produced as a fermentation end product in vitro was correlated with absorbance as a measure of bacterial growth and was used as a rapid screening procedure to test the antimicrobial activity of certain essential oil and tannin secondary plant metabolites on gastrointestinal microorganisms from chickens. the assay was optimised using clostridium perfringens and lactobacillus fermentum, and tested in antimicrobial assays against c. perfringens; the minimum inhibitory concentration for each essential oil and condensed tannin was determined. the effect of penicillin-g on c. perfringens, in both growth and fermentation assays, was similar, and for all secondary metabolites tested, concentrations that inhibited fermentation were also bacteriocidal. the assay was also used to demonstrate the effect of dietary composition and enzyme supplementation on fermentation of mixed gut microflora in vitro; results are compared with in vivo results for the same dietary treatments. the data demonstrate that the effects of bioactive secondary plant products and feed composition on individual organisms or mixed gut microflora can be tested by analysis of fermentative activity in vitro, and that this provides a rapid assay  for testing potential poultry feed additives before in vivo trials.
TIHT== 
ABHT== 

