@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25862297
TI  == a randomized controlled trial to test the effect of multispecies probiotics on cognitive reactivity to sad mood.
AB  == background: recent insights into the role of the human microbiota in cognitive and affective functioning have led to the hypothesis that probiotic supplementation may act as an adjuvant strategy to ameliorate or prevent depression. objective: heightened cognitive reactivity to normal, transient changes in sad mood is an established marker of vulnerability to depression and is considered an important target for interventions. the present study aimed to test if a multispecies probiotic containing bifidobacterium bifidum w23, bifidobacterium lactis w52, lactobacillus acidophilus w37, lactobacillus brevis w63, lactobacillus casei w56, lactobacillus salivarius w24, and lactococcus lactis (w19 and w58) may reduce cognitive reactivity in non-depressed individuals. design: in a triple-blind, placebo-controlled, randomized, pre- and  post-intervention assessment design, 20 healthy participants without current mood disorder received a 4-week probiotic food-supplement intervention with the multispecies probiotics, while 20 control participants received an inert placebo  for the same period. in the pre- and post-intervention assessment, cognitive reactivity to sad mood was assessed using the revised leiden index of depression  sensitivity scale. results: compared to participants who received the placebo intervention, participants who received the 4-week multispecies probiotics intervention showed a significantly reduced overall cognitive reactivity to sad mood, which was largely accounted for by reduced rumination and aggressive thoughts. conclusion: these results provide the first evidence that the intake of probiotics may help reduce negative thoughts associated with sad mood. probiotics supplementation warrants further research as a potential preventive strategy for  depression.
TIHT== 
ABHT== 

PMID== 25576617
TI  == improvement of lysm-mediated surface display of designed ankyrin repeat proteins  (darpins) in recombinant and nonrecombinant strains of lactococcus lactis and lactobacillus species.
AB  == safety and probiotic properties make lactic acid bacteria (lab) attractive hosts  for surface display of heterologous proteins. protein display on nonrecombinant microorganisms is preferred for therapeutic and food applications due to regulatory requirements. we displayed two designed ankyrin repeat proteins (darpins), each possessing affinity for the fc region of human igg, on the surface of lactococcus lactis by fusing them to the usp45 secretion signal and to the peptidoglycan-binding c terminus of acma, containing lysine motif (lysm) repeats. growth medium containing a secreted fusion protein was used to test its  heterologous binding to 10 strains of species of the genus lactobacillus, using flow cytometry, whole-cell enzyme-linked immunosorbent assay (elisa), and fluorescence microscopy. the fusion proteins bound to the surfaces of all lactobacilli; however, binding to the majority of bacteria was only 2- to 5-fold  stronger than that of the control. lactobacillus salivarius atcc 11741 demonstrated exceptionally strong binding (32- to 55-fold higher than that of the control) and may therefore be an attractive host for nonrecombinant surface display. genomic comparison of the species indicated the exopolysaccharides of lb. salivarius as a possible reason for the difference. additionally, a 15-fold concentration-dependent increase in nonrecombinant surface display on l. lactis was demonstrated by growing bacteria with sublethal concentrations of the antibiotics chloramphenicol and erythromycin. nonrecombinant surface display on lab, based on lysm repeats, was optimized by selecting lactobacillus salivarius atcc 11741 as the optimal host and by introducing antibiotics as additives for increasing surface display on l. lactis. additionally, effective display of darpins on the surfaces of nonrecombinant lab has opened up several new therapeutic possibilities.
TIHT== 
ABHT== 

PMID== 23181509
TI  == isolation and characterization of bacteriocin-producing bacteria from the intestinal microbiota of elderly irish subjects.
AB  == aims: to isolate and characterize bacteriocins produced by predominant species of lactic acid bacteria from faeces of elderly subjects. methods and results: screening over 70,000 colonies, from faecal samples collected from 266 subjects,  using the indicator organisms lactobacillus bulgaricus lmg 6901 and listeria innocua dpc 3572, identified 55 antimicrobial-producing bacteria. genomic fingerprinting following apai digestion revealed 15 distinct strains. the antimicrobial activities associated with 13 of the 15 strains were sensitive to protease treatment. the predominant antimicrobial-producing species were identified as lactobacillus salivarius, lactobacillus gasseri, lactobacillus acidophilus, lactobacillus crispatus and enterococcus spp. a number of previously characterized bacteriocins, including abp-118 and salivaricin b (from lact. salivarius), enterocin b (enterococcus faecium), lactacin b (lact. acidophilus),  gassericin t and a variant of gassericin a (lact. gasseri), were identified. interestingly, two antimicrobial-producing species, not generally associated with intestinally derived microorganisms were also isolated: lactococcus lactis producing nisin z and streptococcus mutans producing mutacin ii. conclusion: these data suggest that bacteriocin production by intestinal isolates against our chosen targets under the screening conditions used was not frequent (0.08%). significance and impact of the study: the results presented are important due to  growing evidence indicating bacteriocin production as a potential probiotic trait by virtue of strain dominance and/or pathogen inhibition in the mammalian intestine.
TIHT== 
ABHT== 

PMID== 23056616
TI  == l. plantarum, l. salivarius, and l. lactis attenuate th2 responses and increase treg frequencies in healthy mice in a strain dependent manner.
AB  == many studies on probiotics are aimed at restoring immune homeostasis in patients  to prevent disease recurrence or reduce immune-mediated pathology. of equal interest is the use of probiotics in sub-clinical situations, which are characterized by reduced immune function or low-grade inflammation, with an increased risk of infection or disease as a consequence. most mechanistic studies focus on the use of probiotics in experimental disease models, which may not be informative for these sub-clinical conditions. to gain better understanding of the effects in the healthy situation, we investigated the immunomodulatory effects of two lactobacillus probiotic strains, i.e. l. plantarum wcfs1 and l. salivarius ucc118, and a non-probiotic lactococcus strain, i.e. l. lactis mg1363, in healthy mice. we studied the effect of these bacteria on the systemic adaptive immune system after 5 days of administration. only l. plantarum induced an increase in regulatory cd103(+) dc and regulatory t cell frequencies in the spleen. however, all three bacterial strains, including l. lactis, reduced specific splenic t helper cell cytokine responses after ex vivo restimulation. the effect on ifn-gamma, il5, il10, and il17 production by cd4(+) and cd8(+) t cells was dependent on the strain administered. a shared observation was that all three bacterial strains reduced t helper 2 cell frequencies. we demonstrate that  systemic immunomodulation is not only observed after treatment with probiotic organisms, but also after treatment with non-probiotic bacteria. our data demonstrate that in healthy mice, lactobacilli can balance t cell immunity in favor of a more regulatory status, via both regulatory t cell dependent and independent mechanisms in a strain dependent manner.
TIHT== 
ABHT== 

PMID== 21986357
TI  == in vitro assessment of the immunomodulatory effects of multispecies probiotic formulations for management of allergic diseases.
AB  == modulation of the composition of the intestinal microbiota with probiotics could  possibly offer a way of prevention or management of allergic diseases. the objective of this study was to determine the immunomodulating effects of various  multispecies probiotic combinations in vitro, as preamble to application in vivo. multispecies probiotic combinations were formulated and tested for their effects  on in vitro cytokine production by human mononuclear cells and were compared to products that already have shown beneficial effects in vivo. all 4 tested combinations of probiotics showed a 40-71% decrease of th2 cytokine production (il-4, il-5, and il-13) and a variable increase of th1 (ifn-gamma) and treg cytokine (il-10) production compared to the medium. a specific probiotic mixture  that contained bifidobacterium breve w25, bifidobacterium lactis atcc sd 5219, b. lactis atcc sd 5220, lactobacillus plantarum w62, lactobacillus salivarius w57 and lactococcus lactis w19 was superior in its stimulating effect on il-10 production (significant better than the other tested combinations; p=0.001). modulation of in vitro cytokine production profiles can be used to differentiate  between selected probiotic formulations for their immunomodulatory properties. in the future it should be demonstrated whether the immunomodulatory capacities from the multispecies probiotic formulation with the desired profile will be effective in vivo (in adolescents, followed by application in children).
TIHT== 
ABHT== 

PMID== 24031676
TI  == identification of the bacterial community responsible for traditional fermentation during sour cassava starch, cachaca and minas cheese production using culture-independent 16s rrna gene sequence analysis.
AB  == we used a cultivation-independent, clone library-based 16s rrna gene sequence analysis to identify bacterial communities present during traditional fermentation in sour cassava starch, cachaca and cheese production in brazil. partial 16s rrna gene clone sequences from sour cassava starch samples collected  on day five of the fermentation process indicated that leuconostoc citreum was the most prevalent species, representing 47.6% of the clones. after 27 days of fermentation, clones (genbank accession numbers gq999786 and gq999788) related to unculturable bacteria were the most prevalent, representing 43.8% of the clones from the bacterial community analyzed. the clone represented by the sequence gq999786 was the most prevalent at the end of the fermentation period. the majority of clones obtained from cachaca samples during the fermentation of sugar cane juice were from the genus lactobacillus. lactobacillus nagelli was the most  prevalent at the beginning of the fermentation process, representing 76.9% of the clones analyzed. after 21 days, lactobacillus harbinensis was the most prevalent  species, representing 75% of the total clones. at the end of the fermentation period, lactobacillus buchneri was the most prevalent species, representing 57.9% of the total clones. in the minas cheese samples, lactococcus lactis was the most prevalent species after seven days of ripening. after 60 days of ripening, streptococcus salivarius was the most prevalent species. our data show that these three fermentation processes are conducted by a succession of bacterial species,  of which lactic acid bacteria are the most prevalent.
TIHT== 
ABHT== 

PMID== 21442918
TI  == [ph and oxidation-reduction potential change of environment during a growth of lactic acid bacteria: effects of oxidizers and reducers].
AB  == decrease of ph and dropping of oxidation-reduction potential have been observed during growing lactobacillus salivarius 1588 and 3823, lactobacillus acidophilus  101e, and lactococcus lactis 3690 in anaerobic conditions in medium with glucose  acidification. these parameters and membrane proton permeability of bacteria (c(m)(h+)) changed in the mediums with different ph. oxidizer ferrycianide and reducer dl-dithiothreitol affected the bacterial growth and their changed h+ extrusion from the cells and k+ uptake by the cells in experiment conditions. application of oxidizers and reducers are suggested for regulation of growth related with h+ ion transport in lactic acid bacteria.
TIHT== 
ABHT== 

PMID== 21314706
TI  == fate and efficacy of lacticin 3147-producing lactococcus lactis in the mammalian  gastrointestinal tract.
AB  == gastrointestinal survival of the bacteriocin-producing strain, lactococcus lactis dpc6520, was evaluated systematically in vitro and in vivo with a view to using this strain to deliver biologically active lacticin 3147, a broad-spectrum bacteriocin, to the gut. the activity of the lacticin 3147 producer was also evaluated against two clinically relevant pathogens: clostridium difficile and listeria monocytogenes. when suspended in an appropriate matrix, the lactococcal  strain is capable of surviving simulated gastrointestinal juices similar to the porcine probiotic, lactobacillus salivarius dpc6005. upon administration of l. lactis dpc6520 to pigs (n=4), excretion rates of approximately 10(2) -10(5) cfu g(-1) faeces were observed by day 5. although passage through the gastrointestinal tract (git) did not affect lacticin 3147 production by l. lactis dpc6520 isolates, activity was undetectable in faecal samples by an agar well diffusion assay. furthermore, l. lactis dpc6520 had no inhibitory effect on c. difficile or other bacterial populations in a human distal colon model, while lactococcal counts declined 10,000-fold over 24 h. the lacticin 3147 producer failed to prevent l. monocytogenes infection in a mouse model, even though a mean l. lactis dpc6520 count of 4.7 x 10(4) cfu g(-1) faeces was obtained over the 5-day administration period. these data demonstrate that l. lactis dpc6520 is capable of surviving transit through the git, and yet lacks antimicrobial efficacy in the models of infection used.
TIHT== 
ABHT== 

PMID== 21840800
TI  == anti-inflammatory properties of probiotic bacteria on salmonella-induced il-8 synthesis in enterocyte-like caco-2 cells.
AB  == invasion of the gut by pathogenic salmonella leads to production of il-8 that initiates inflammatory reactions to combat the bacterium. however, its persistent production causes tissue damage and interventions that suppress il-8 production prevent tissue damage. we hypothesised that probiotics could mediate their benefits via inhibition of il-8 synthesis. caco-2 cells were infected with probiotic bifidobacterium infantis w52, lactobacillus casei w56, lactococcus lactis w58, lactobacillus acidophilus w70, bifidobacterium bifidum w23, or lactobacillus salivarius w24 or pathogenic salmonella enterica serovar enteritidis 857 at 0, 0.2, 1, 2, 10, 20, 100 or 200 bacterial cells/caco-2 cell for 1 hour. cells were also exposed to a combination of one probiotic bacterium (200 bacterial cells/caco-2 cell) and the graded numbers of salmonella as either  co-incubation (1 hour) or pre-incubation of the probiotic bacterium (1 hour) followed by salmonella (1 hour). the cells recovered for 2 or 24 hours. il-8 and  hsp70 were determined by elisa and western blot respectively. both probiotics and salmonella induced a dose- and time-dependent synthesis of il-8 but probiotics induced far lower il-8 levels than salmonella. the salmonella-induced il-8 was significantly suppressed by b. infantis w52, l. casei w56 and l. lactis w58 at low numbers of salmonella (0.2 to 20 bacterial cells/caco-2 cell) and within 2 hours of recovery. the observed probiotic-mediated reduction in il-8 secretion was transient, and lost after a few hours. in addition, these three probiotics induced a significant increase in hsp70 expression while l. acidophilus w70, b. bifidum w23 and l. salivarius w24 induced a weak hsp70 expression and could not suppress the salmonella-induced il-8 synthesis. we conclude that suppression of salmonella-induced il-8 synthesis by caco-2 cells is exhibited by probiotics that induce expression of hsp70, suggesting that the protective role of probiotics could be mediated, at least in part, via hsp70 expression. this suppression is limited to a low number of infecting pathogenic salmonella.
TIHT== 
ABHT== 

PMID== 19577815
TI  == main microorganisms involved in the fermentation of ugandan ghee.
AB  == ghee is widely produced from a traditional fermented butter-like product named mashita in western uganda. however, no detailed studies have been done to identify the microorganisms involved in mashita fermentation. the aim of this study was to identify the microorganisms present at the end of mashita ripening using culture-dependent and culture-independent techniques. the most commonly identified species of lactic acid bacteria (lab) in mashita using culture-dependent techniques were lactobacillus paracasei, lactobacillus helveticus, lactobacillus plantarum and lactobacillus perolens constituting 37.3%, 10.1%, 8.1% and 7.7% of total bacterial colonies isolated respectively. l. paracasei was the only bacterial species identified in all mashita samples by culture-dependent technique. two of the four most commonly isolated lab species (l. helveticus and l. plantarum) were also identified in mashita by a culture-independent method (pcr-dgge). other main lab species identified in mashita by pcr-dgge were bifidobacterium sp., enterococcus faecium, lactobacillus brevis, lactobacillus acetotolerans, lactobacillus sp., lactococcus raffinolactis, lactococcus lactis subsp. lactis and streptococcus salivarius. the main species of acetic acid bacteria (aab) identified in the mashita using pcr-dgge method were acetobacter aceti, acetobacter lovaniensis, acetobacter orientalis and acetobacter pasteurianus. pcr-dgge identification of yeasts showed that brettanomyces custersianus, candida silvae, geotrichum sp., issatchenkia occidentalis, issatchenkia orientalis, kluyveromyces marxianus, saccharomyces cerevisiae, and trichosporon asahii were main yeast species in mashita. a. lovaniensis, a. aceti, and i. orientalis were identified in all the six mashita samples analyzed using pcr-dgge method. other microbial species were only found in some samples. these results indicate that lab and yeasts, as in similar fermentation products, but also aab are main microbial groups involved in mashita fermentation.
TIHT== 
ABHT== 

PMID== 18538605
TI  == short-term relative antibacterial effect of octenidine dihydrochloride on the oral microflora in orthodontically treated patients.
AB  == objective: to evaluate the efficacy of common antiseptic mouth rinses and octenidine dihydrochloride (oct). methods: the antibacterial activities of antiseptics against total and cariogenic bacteria (streptococcus mutans and lactobacillus species) in saliva were studied in vitro and in vivo. after unstimulated saliva was collected, one of the mouth rinse solutions was applied for 30seconds. saliva samples were collected 15, 30, 60, and 120min later and evaluated for their bacterial count. results: oct had a significantly greater inhibitory effect on the studied bacteria than 0.2% chlorhexidine gluconate (chx) and 7.5% polyvinylpyrrolidone-iodine complex (pvp-i) from 15min to 120min following the application (p<0.01). the antiseptic efficacy of 0.2% chx on total  bacteria and lactobacillus species was very similar to the efficacy observed with 7.5% pvp-i mouth solution from 15min up to 120min. streptococcus mutans was completely inhibited by 0.15mg/ml pvp-i, 0.5mg/ml chx, and 0.1mg/ml oct concentrations, while streptococcus salivarius was inhibited by 0.15mg/ml pvp-i,  2mg/ml chx, and 0.8mg/ml oct concentrations. lactococcus lactis subspecies lactis was inhibited with 0.00313mg/ml oct, 30mg/ml pvp-i, and 0.0063mg/ml chx concentrations. conclusions: oct compared favorably with chx and pvp-i in its antibacterial effects, both in vitro and in vivo (p<0.01).
TIHT== 
ABHT== 

PMID== 17544549
TI  == design of a multispecies probiotic mixture to prevent infectious complications in critically ill patients.
AB  == background & aims: although the potential for probiotics is investigated in an increasing variety of diseases, there is little or no consensus regarding the desired probiotic properties for a particular disease in question, nor about the  final design of the probiotic. specific strain selection procedures were undertaken to design a disease-specific multispecies probiotic. methods: from a strain collection of 69 different lactic acid bacteria a primary selection was made of 14 strains belonging to different species showing superior survival in a  simulated gastrointestinal environment. functional tests like antimicrobial activity against a range of clinical isolates and cytokine inducing capacity in cultured human peripheral blood mononuclear cells were used to further identify potential strains. results: specific strains inhibited growth of clinical isolates whereas others superiorly induced the anti-inflammatory cytokine il-10.  based on functional tests and general criteria regarding probiotic design and safety, a selection of the following six strains was made (ecologic 641); bifidobacterium bifidum, bifidobacterium infantis, lactobacillus acidophilus, lactobacillus casei, lactobacillus salivarius and lactococcus lactis. combination of these strains resulted in a wider antimicrobial spectrum, superior induction of il-10 and silencing of pro-inflammatory cytokines as compared to the individual components. conclusions: application of strict criteria during the design of a disease-specific probiotic prior to implementation in clinical trials may provide a rational basis for use of probiotics.
TIHT== 
ABHT== 

PMID== 17521319
TI  == selection of probiotic bacteria for prevention of allergic diseases: immunomodulation of neonatal dendritic cells.
AB  == modification of intestinal microbiota early in life by administration of probiotic bacteria may be a potential approach to prevent allergic disease. to select probiotic bacteria for in vivo purposes, we investigated the capacity of probiotic bacteria to interact with neonatal dendritic cells (dc) and studied the ensuing t cell polarizing effect. immature dc were generated from cord blood-derived monocytes and maturation was induced by maturation factors (mf), lipopolysaccharide (lps) plus mf and bifidobacterium bifidum, b. infantis, lactobacillus salivarius, lactococcus lactis alone or combined with mf. after 12  days of co-culture with dc and staphylococcus aureus enterotoxin b (seb) as antigenic stimulus, cytokine production by autologous t cells was determined by intracellular cytokine staining. additionally, cells were stimulated with cd3 and cd28 monoclonal antibodies and cytokines were measured in supernatants by multiplex assay. the probiotic strains induced partial maturation of dc. full maturation of dc was induced for all strains tested when mf was added. the percentage of interleukin (il)-4 producing t cells was lower in t cell cultures stimulated with b. bifidum matured dc compared to mf and lps matured dc, which coincided with a higher percentage of interferon (ifn)-gamma-producing t cells. furthermore, t cells stimulated by b. bifidum matured dc produced significantly more il-10 compared to mf matured dc. selected species of the bifidobacterium genus prime in vitro cultured neonatal dc to polarize t cell responses and may therefore be candidates to use in primary prevention of allergic diseases.
TIHT== 
ABHT== 

PMID== 17388042
TI  == isolation and molecular characterization of antibiotic-resistant lactic acid bacteria from poultry and swine meat products.
AB  == the transfer via the food chain from animals to humans of microbes that are resistant to antimicrobial agents is of increasing concern. to determine the contributions of nonpathogenic microflora to the occurrence and spread of antibiotic resistance (ar) genes in the food chain, 123 lactic acid bacteria were isolated from 29 samples of raw and processed pork and chicken meat products that had previously tested positive for one or more ar genes that encode clinically relevant ars: tet(m), tet(o), tet(k), erm(a), erm(b), erm(c), aac (6')-ie aph (2")-ia, meca, and blaz. all of the isolates were initially tested for their ar gene profiles by pcr. the 59 isolates carrying a tet, erm, or blaz gene were taken through molecular identification, analyzed by determination of the mic, and subjected to genetic fingerprinting. lactococcus garvieae was the predominant species (28 isolates), followed by lactobacillus plantarum (11 isolates) and l. salivarius (6 isolates), whereas lactococcus lactis subsp. lactis, lactobacillus  johnsonii, l. reuteri, l. crispatus, and l. brevis were identified at lower frequencies. the tet(m) and erm(b) genes were the most frequently detected. assessment of multiple resistances in 18 tet positive (tet+) isolates revealed that tet(m) plus erm(b) and tet(k) plus erm(b) were the most frequent ar gene patterns. partial sequencing of the tet(m) open reading frame of three selected strains showed high sequence similarities (> 99%) with tet(m) genes previously found in human pathogens (listeria monocytogenes and neisseria meningitidis). southern hybridization with plasmid profiles revealed these strains contained tet(m)-carrying plasmids.
TIHT== 
ABHT== 

PMID== 17280749
TI  == mucosal immunisation of mice with malaria protein on lactic acid bacterial cell walls.
AB  == mice were orally and nasally immunised with a malaria parasite protein, msa2, expressed in lactococcus lactis, covalently attached to the peptidoglycan (msa2cp), or non-covalently rebound to l. lactis cell walls, live lactobacillus reuteri and lb. salivarius (msa2ca). although there was marked variation within mice of the same inbred strain, the data suggest that the characteristics of serum igg antibodies formed against msa2 are influenced by the mouse strain and mode of msa2 presentation. msa2-specific iga antibodies in sera and faecal pellets, and ifngamma-secreting spleen cells were detectable in some immunised animals. msa2ca on lactobacilli, although not effective in eliciting serum igg antibodies, showed a potential for eliciting iga antibodies in the gut. the presence of msa2 in l. lactis tended to divert the antibody response from lactococcal antigens. the data suggest that anti-msa2 and anti-lactococcal antibody responses are not necessarily associated in the mice. the findings are related to the use of lactic acid bacteria expressing heterologous proteins for therapy and vaccination.
TIHT== 
ABHT== 

PMID== 17187971
TI  == characterization of lactic acid bacteria isolated from the one humped camel milk  produced in morocco.
AB  == one hundred and twenty (120) strains of lactic acid bacteria (lab) were enumerated and isolated from raw dromedary milk in morocco using various cultured media. strains isolated were characterized by phenotypic, physiological and biochemical properties. results showed that high counts of lab were found. presumptive lactobacilli counts ranged from 2.5x10(2) to 6x10(7)cfu/ml, presumptive lactococci levels varied from 5x10(2) to 6x10(7)cfu/ml, presumptive streptococci counts varied from 4.2x10(2) to 8x10(7)cfu/ml, presumptive leuconostoc levels ranged from 5.4x10(2) to 5.4x10(7)cfu/ml. results showed also  that lactobacillus and lactococcus were the predominant genera with 37.5% and 25.8%, respectively. the dominated species found were lactococcus lactis subsp. lactis (17.5%), lactobacillus helveticus (10%), streptococcus salivarius subsp. thermophilus (9.20%), lactobacillus casei subsp. casei (5.80%) and lactobacillus  plantarum (5%). this is the first report on the characterization of lab strains isolated from the one humped camel milk produced in morocco.
TIHT== 
ABHT== 

PMID== 15530005
TI  == screening of lactic-acid bacteria from south african barley beer for the production of bacteriocin-like compounds.
AB  == strains of lactobacillus paracasei subsp. paracasei (strain st11br), l. pentosus  (strain st151br), l. plantarum (strain st13br), and lactococcus lactis subsp. lactis (strain st34br) producing bacteriocin-like peptides were isolated from barley beer produced in the western, northern and eastern provinces of south africa. the peptides (bacst11br, bacst151br, bacst13br and bacst34br) lost their  activity after treatment with proteinase k, a proteinase, papain, chymotrypsin, trypsin, pepsin and pronase, but not when they were treated with alpha-amylase, suggesting that the peptides are not glycosylated. the peptides inhibited the growth of lactobacillus casei, l. sakei, pseudomonas aeruginosa, escherichia coli and enterococcus faecalis, but not enterobacter cloacae, lactobacillus bulgaricus subsp. delbrueckii, l. plantarum, l. salivarius, listeria innocua, staphylococcus aureus, streptococcus uberis, s. agalactiae, s. caprinus and s. pneumoniae. peptides bacst11br and bacst13br differed from the other 2 peptides by failing to kill klebsiella pneumoniae and one of the e. coli strains. peptides were stable after 2 h of incubation at ph 2.0-12.0, and after 90 min at 100 degrees c. when autoclaved (121 degrees c, 20 min), only bacst13br lost its activity. the bacteriocin-like peptides were produced at a growth temperature of 30 degrees c,  but not at 37 degrees c.
TIHT== 
ABHT== 

PMID== 15190953
TI  == diversity of lactic acid bacteria isolated from aoc salers cheese.
AB  == the objective of this work was to describe the diversity of lactic acid bacteria  in traditional raw milk salers cheeses at the species and strain levels. the characterization of 381 strains isolated during ripening and various strain collections was investigated using physiological analysis and molecular techniques: rep-pcr, species and genus specific amplifications and the sequence analysis of 16s rdna for strain typing and taxonomic identification. the strains  belonged to lactobacillus plantarum, lactobacillus paracasei, lactococcus lactis, lactococcus garviae, enterococcus faecalis, enterococcus faecium, leuconostoc mesenteroides, leuconostoc pseudomesenteroides, streptococcus salivarius, streptococcus millieri, streptococcus macedonicus and pediococcus pentosaceus. a  wide phenotypic and genomic heterogeneity was observed within the different species (lactobacillus plantarum, lactobacillus paracasei and leuconostoc mesenteroides) according to the origin and the time of ripening. the natural microflora was different from strain collection and each method must be combined  to identify and characterize natural microflora. this study revealed the low selectivity of selective media used for the isolation of different groups of lactic acid bacteria except the facultatively heterofermentative lactobacilli medium selecting mesophile lactobacilli and sb medium selective for enterococcus. the study reveals, for the first time, the microbial lactic acid bacteria community of salers cheese and its diversity. a better knowledge of microbial flora will be useful to improve understanding of sensory quality of cheeses.
TIHT== 
ABHT== 

PMID== 14968979
TI  == changes in galactose and lactic acid content of sweet whey during storage.
AB  == whey is often stored or transported for a period of time prior to processing. during this time period, galactose and lactic acid concentrations may accumulate, reducing the quality of spray-dried whey powders in regard to stickiness and agglomeration. this study surveyed industry samples of cheddar and mozzarella cheese whey streams to determine how galactose and lactic acid concentrations changed with storage at appropriate (4 degrees c) and abuse (37.8 degrees c) temperatures. samples stored at 4 degrees c did not exhibit significant increases in levels of lactic acid or galactose. mozzarella whey accumulated the greatest amount of galactose and lactic acid with storage at 37.8 degrees c. whey samples  derived from cheese made from single strains of starter culture were also evaluated to determine each culture's contribution to galactose and lactic acid production. starter cultures evaluated included streptococcus salivarius ssp. thermophilus. lactobacillus helveticus, lactobacillus delbrueckii ssp. bulgaricus, lactococcus lactis ssp. cremoris, and lactococcus lactis ssp. lactis. whey derived from l. helveticus accumulated a significantly greater amount of lactic acid upon storage at 37.8 degrees c as compared with the other cultures. galactose accumulation was significantly decreased in whey from l. lactis ssp. lactis stored at 37.8 degrees c in comparison with the other cultures. results from this study indicate that proper storage conditions (4 degrees c) for whey prevent accumulation of galactose and lactic acid while the extent of accumulation during storage at 37.8 degrees c varies depending on the culture(s)  used in cheese production.
TIHT== 
ABHT== 

PMID== 14633020
TI  == multiple competitive pcr-dgge as a tool for quantifying and profiling defined mixed cultures of lactic acid bacteria during production of probiotics from complex polysaccharides.
AB  == aims: to apply a denaturing gradient gel electrophoretic (dgge) method to quantify and profile individual strains during a mixed culture fermentation. methods and results: dna was extracted during the culture of lactic acid bacteria (lab) and amplified in a multiple competitive pcr (cpcr) using general primers targeting 16s rdna and dna from streptococcus salivarius as competitive dna. subsequently the 200-kb amplified fragments were separated by dgge. the method was validated in pure cultures and used to profile a mixture of three lab grown on glucose, soluble starch and glycogen from mussel processing waste. the inclusion of a starch- and glycogen-degrading strain (lactobacillus plantarum) and a weakly amylotic nisin-resistant strain (lact. paracasei) allowed proliferation of the nisin producing lactococcus lactis which in itself is unable to grow on complex carbohydrates. cpcr-dgge permitted the monitoring of a different strain succession on the different carbohydrates, related to amylolytic activity and substrate consumption, acid production and nisin production. conclusions: cpcr-dgge is a useful tool for profiling defined mixed cultures of bacteria and hence allows their interaction to be studied. significance and impact of the study: provided validation of the method for each specific case, it may be appropriate to monitor and control the reproducibility of any defined mixed culture of bacteria, with the advantage that an increase in the strain numbers to be monitored does not yield an increase in the labour of the procedure.
TIHT== 
ABHT== 

PMID== 12911694
TI  == inhibition of staphylococcus aureus by the commensal bacteria of human milk.
AB  == aims: to study the bacterial diversity in expressed human milk with a focus on detecting bacteria with an antimicrobial activity against staphylococcus aureus,  known as a causative agent of maternal breast infections and neonatal infections. methods and results: random isolates (n = 509) were collected from breast milk samples (n = 40) of healthy lactating women, genotypically identified, and tested for antimicrobial activity against staph. aureus. commensal staphylococci (64%) and oral streptococci (30%), with staph. epidermidis, strep. salivarius, and strep. mitis as the most frequent isolates, were the predominant bacterial species in breast milk. one-fifth of staph. epidermidis and half of strep. salivarius isolates suppressed growth of staph. aureus. enterococci (ent. faecalis), isolated from 7.5% of samples, and lactic acid bacteria (lab) (lactobacillus rhamnosus, lact. crispatus, lactococcus lactis, leuconoctoc mesenteroides), isolated from 12.5% of samples, were also effective against staph. aureus. one l. lactis isolate was shown to produce nisin, a bacteriocin used in food industry to prevent bacterial pathogens and spoilage. conclusions: expressed breast milk contains commensal bacteria, which inhibit staph. aureus. significance and impact of the study: the strains inhibitory against the pathogen staph. aureus have potential use as bacteriotherapeutic agents in preventing neonatal and maternal breast infections caused by this bacterium.
TIHT== 
ABHT== 

PMID== 12810281
TI  == the effect of temperature and ph on the growth of lactic acid bacteria: a ph-auxostat study.
AB  == the growth of streptococcus salivarius subsp. thermophilus, lactococcus lactis subsp. lactis, lactobacillus delbrueckii subsp. bulgaricus, lactobacillus acidophilus and lactobacillus paracasei was studied in a ph-auxostat. the computer-controlled smooth change of ph or temperature was used to study the effect of ph and temperature on the culture characteristics (specific growth rate mu growth yield y(atp) and specific lactate production rate q(atp)). the behaviour of mu and q(atp) with an increase of temperature suggested that atp production capacity was an important factor in determining the maximum growth rate of lactic acid bacteria (lab). the decrease of y(atp) with increase of temperature resulted in the decrease of specific growth rate while q(atp) remained constant or even increased. with the decrease of ph, decrease of both y(atp) and q(atp) was observed. s. thermophilus st20 having the highest maximum specific growth rate of 2.2 h(-1) at 44 degrees c was the most acid sensitive strain. the l. paracasei e1h3 having the lowest mu(max) was the most tolerant strain to ph change. the behaviour of mixed culture of l. bulgaricus and s. thermophilus in milk in a ph-auxostat with ph-decrease was in agreement with the  pure culture experiments of the same species. the study showed that ph-auxostat with smooth controlled change of ph and temperature is an effective method for determination of technological characteristics and comparative physiological study of lab.
TIHT== 
ABHT== 

PMID== 12783652
TI  == influence of the oral administration of lactic acid bacteria on iga producing cells associated to bronchus.
AB  == intestinal, respiratory and genitourinary mucosal surfaces are the most important routes of entry for microbial pathogens. the stimulus of the mucosal immunity is  not easy because the trigger keys for the activation do not follow the ones of the systemic immune response. in previous works we have demonstrated that some lactic acid bacteria (lab), when orally administered, can induce an enhance of the gut immune response. taking into account the concept of a common mucosal response, we studied the effect of orally administered mice with lactobacillus casei, l. acidophilus, l. rhamnosus, l. delbrueckii subsp. bulgaricus, streptococcus salivarius subsp. thermophilus and lactococcus lactis on the iga secreting cells associated to bronchus. as shown before, oral immunostimulation with lab induced an increase of the iga* cells at intestinal level by a dose depending effect. in this study it is also showed that the lab assayed, with exception of l. acidophilus, were able to enhance iga+ cells at bronchial level,  being also this effect dose dependent. the increment induced by some lab in the number of iga+ cells on the mucosa surface of the lower respiratory tract may be  very important to prevent bronchus diseases.
TIHT== 
ABHT== 

PMID== 11932444
TI  == characterization of the genetic locus responsible for the production of abp-118,  a novel bacteriocin produced by the probiotic bacterium lactobacillus salivarius  subsp. salivarius ucc118.
AB  == abp-118, a small heat-stable bacteriocin produced by lactobacillus salivarius subsp. salivarius ucc118, a strain isolated from the ileal-caecal region of the human gastrointestinal tract, was purified to homogeneity. using reverse genetics, a dna fragment specifying part of abp-118 was identified on a 10769 bp  chromosomal region. analysis of this region revealed that abp-118 was a class iib two-peptide bacteriocin composed of abp118alpha, which exhibited the antimicrobial activity, and abp118beta, which enhanced the antimicrobial activity. the gene conferring strain ucc118 immunity to the action of abp-118, abpim, was identified downstream of the abp118beta gene. located further downstream of abp118beta, several orfs were identified whose deduced proteins resembled those of proteins involved in bacteriocin regulation and secretion. heterologous expression of abp-118 was achieved in lactobacillus plantarum, lactococcus lactis and bacillus cereus. in addition, the abp118 locus encoded an  inducing peptide, abpip, which was shown to play a role in the regulation of abp-118 production. this novel bacteriocin is, to the authors' knowledge, the first to be isolated from a known human probiotic bacterium and to be characterized at the genetic level.
TIHT== 
ABHT== 

PMID== 11510428
TI  == [viability and activity of the lactic bacteria (streptococcus salivarius ssp thermophilus y lactobacillus delbrueckii ssp bulgaricus) del yogurt en venezuela].
AB  == national and international legislations have agreed that the population of lactic bacteria in yogurt must be viable and not less than 10(6) ufc/g. in venezuela, during last years, observations indicate that the number of viable cells in some  commercial samples show high variations, as low levels. this research attempted to find the origin of this problem in the local industry. for this purpose 105 commercial samples were analyzed during their shelf life and 32 samples of yogurt prepared in the laboratory following the flow diagram of the local industry. the  different conditions of freeze dried lactic culture, were also analyzed. these samples were evaluated for viable cell count of lactic bacteria and possible variations of ph and acidity. the absence or low number of lactic bacteria detected in some commercial samples is due to the use of inadequate working cultures that show imbalanced proportions of the two microorganisms, besides a low count below 106 ufc/g. the succesive propagation and storage time of mother culture, and the overacidification of the product, produce subletal injury to the microbial cells of the yogurt starter culture. the data indicate that manufacturing practices significantly affect the survival of the lactic flora.
TIHT== 
ABHT== 

PMID== 10386296
TI  == study of the possible mechanisms involved in the mucosal immune system activation by lactic acid bacteria.
AB  == the induction of a mucosal immune response is not easy due to the development of  oral tolerance, but under some conditions, bacteria can activate this immune system. antigens administered orally can interact with m cells of peyer's patches or bind to the epithelial cells. we have demonstrated that certain lactic acid bacteria are able to induce specific secretory immunity, and others will enhance  the gut inflammatory immune response. the aim of this work was to establish the reason for these different behaviors and to define possible mechanisms involved in the interaction of lactic acid bacteria at the intestinal level. we studied iga+ and igm+ b cells comparatively in bronchus and intestine and cd4+ t cells and iga anti-lactic acid bacteria antibodies in the intestinal fluid, induced by  oral administration of lactobacillus casei, lb. delbrueckii ssp. bulgaricus, lb.  acidophilus, lb. plantarum, lb. rhamnosus, lactococcus lactis, and streptococcus  salivarius ssp. thermophilus. the increase in the iga+ b cells in the bronchus means that these lactic acid bacteria were able to induce the iga cycle by interaction with m cells from peyer's patches or intestinal epithelial cells. the igm+ cells increased when the stimulus did not induce the switch from igm+ to iga+. the increase in the cd4+ cells suggests interaction of peyer's patches and  enhancement of the b- and t-cell migration. the anti-lactic acid bacteria antibody is related to the processing and presentation of the microorganisms to the immune cells. we demonstrated that lb. casei and lb. plantarum were able to interact with peyer's patch cells and showed an increase in iga-, cd4+ cells, and antibodies specific for the stimulating strain. lactobacillus acidophilus induced gut mucosal activation by interaction with the epithelial cells without increase  in the immune cells associated with the bronchus. although lb. rhamnosus and strep. salivarius ssp. thermophilus interact with epithelial cells, they also induced an immune response against their epitopes. lactococcus lactis and lb. delbrueckii ssp. bulgaricus induced an increase of iga+ cells entering the iga cycle but not cd4+ cells; thus, these bacteria would have been bound to epithelial cells that activated b lymphocytes without processing and presenting of their epitopes. we did not determine specific antibodies against lc. lactis or lb. bulgaricus.
TIHT== 
ABHT== 

PMID== 9987115
TI  == ctsr, a novel regulator of stress and heat shock response, controls clp and molecular chaperone gene expression in gram-positive bacteria.
AB  == clpp and clpc of bacillus subtillis encode subunits of the clp atp-dependent protease and are required for stress survival, including growth at high temperature. they play essential roles in stationary phase adaptive responses such as the competence and sporulation developmental pathways, and belong to the  so-called class iii group of heat shock genes, whose mode of regulation is unknown and whose expression is induced by heat shock or general stress conditions. the product of ctsr, the first gene of the clpc operon, has now been  shown to act as a repressor of both clpp and clpc, as well as clpe, which encodes a novel member of the hsp100 clp atpase family. the ctsr protein was purified and shown to bind specifically to the promoter regions of all three clp genes. random mutagenesis, dnasel footprinting and dna sequence deletions and comparisons were  used to define a consensus ctsr recognition sequence as a directly repeated heptad upstream from the three clp genes. this target sequence was also found upstream from clp and other heat shock genes of several gram-positive bacteria, including listeria monocytogenes, streptococcus salivarius, s. pneumoniae, s. pyogenes, s. thermophilus, enterococcus faecalis, staphylococcus aureus, leuconostoc oenos, lactobacillus sake, lactococcus lactis and clostridium acetobutylicum. ctsr homologues were also identified in several of these bacteria, indicating that heat shock regulation by ctsr is highly conserved in gram-positive bacteria.
TIHT== 
ABHT== 

PMID== 9139932
TI  == cell wall anchoring of the streptococcus pyogenes m6 protein in various lactic acid bacteria.
AB  == the m6 protein from streptococcus pyogenes is the best-characterized member of a  family of cell envelope-associated proteins. based on the observation that the c-terminal sorting signals of these proteins can drive cell wall anchoring of heterologous unanchored proteins, we have cloned and expressed the emm6 structural gene for the m6 protein in various lactic acid bacteria (lab). the emm6 gene was successfully expressed from lactococcal promoters in several lactococcus lactis strains, an animal-colonizing lactobacillus fermentum strain,  lactobacillus sake, and streptococcus salivarius subsp. thermophilus. the m6 protein was efficiently anchored to the cell wall in all strains tested. in lactobacilli, essentially all detectable m6 protein was cell wall associated. these results suggest the feasibility of using the c-terminal anchor moiety of m6 for protein surface display in lab.
TIHT== 
ABHT== 

PMID== 8868433
TI  == inducer expulsion and the occurrence of an hpr(ser-p)-activated sugar-phosphate phosphatase in enterococcus faecalis and streptococcus pyogenes.
AB  == inducer expulsion, a phenomenon in which rapidly metabolizable sugars cause cytoplasmic dephosphorylation and efflux of pre-accumulated sugar-phosphates (sugar-p), has been documented for streptococcus pyogenes, streptococcus bovis, and lactococcus lactis, but not for other gram-positive bacteria. using intact cells and membrane vesicles, we show that enterococcus faecalis exhibits both inducer exclusion and inducer expulsion, and that the latter phenomenon is dependent on the metabolite-activated atp-dependent hpr(ser) kinase that phosphorylates ser-46 in hpr of the phosphotransferase system. a small, heat-stable, membrane-associated, hpr(ser-p)-activated sugar-p phosphatase (pase  ii), previously identified only in lc. lactis, is shown to be present in extracts of enterococcus faecalis and streptococcus pyogenes but not in those of staphylococcus aureus, streptococcus mutans, streptococcus salivarius, or bacillis subtilis, organisms that do not exhibit the inducer expulsion phenomenon. further, lactobacillus brevis, an organism that exhibits inducer expulsion by a different mechanism, also apparently lacks pase ii. the results reveal that pase ii is present in those organisms that exhibit the coupled sugar-p hydrolysis/expulsion mechanism but not those that lack this mechanism. they provide correlative evidence that pase ii initiates inducer expulsion in species of enterococci, streptococci and lactococci.
TIHT== 
ABHT== 

PMID== 7730253
TI  == distribution of proteins similar to iiimanh and iiimanl of the streptococcus salivarius phosphoenolpyruvate:mannose-glucose phosphotransferase system among oral and nonoral bacteria.
AB  == in streptococcus salivarius, the phosphoenolpyruvate (pep):mannose-glucose phosphotransferase system, which concomitantly transports and phosphorylates mannose, glucose, fructose, and 2-deoxyglucose, is composed of the general energy-coupling proteins ei and hpr, the specific membrane-bound iiiman, and two  forms of a protein called iiiman, with molecular weights of 38,900 (iiimanh) and  35,200 (iiimanl), that are found in the cytoplasm as well as associated with the  membrane. several lines of evidence suggest that iiimanh and/or iiimanl are involved in the control of sugar metabolism. to determine whether other bacteria  possess these proteins, we tested for their presence in 28 oral streptococcus strains, 3 nonoral streptococcus strains, 2 lactococcus strains, 2 enterococcus strains, 2 bacillus strains, 1 lactobacillus strain, staphylococcus aureus, and escherichia coli. three approaches were used to determine whether the iiiman proteins were present in these bacteria: (i) western blot (immunoblot) analysis of cytoplasmic and membrane proteins, using anti-iiimanh and anti-iiimanh rabbit  polyclonal antibodies; (ii) analysis of pep-dependent phosphoproteins by polyacrylamide gel electrophoresis; and (iii) inhibition by anti-iiiman antibodies of the pep-dependent phosphorylation of 2-deoxyglucose (a mannose analog) by crude cellular extracts. only the species s. salivarius and streptococcus vestibularis possessed the two forms of iiiman. fifteen other streptococcal species possessed one protein with a molecular weight between 35,200 and 38,900 that cross-reacted with both antibodies. in the case of 9 species, a protein possessing the same electrophoretic mobility was phosphorylated at the expense of pep. no such phosphoprotein, however, could be detected in the other six species. a iii(man)-like protein with a molecular weight of 35,500 was also detected in lactobacillus casei by western blot experiments as well as by pep-dependent phosphoprotein analysis, and a protein with a molecular weight of 38,900 that cross-reacted with anti-iii(man) antibodies was detected in lactococcus lactis. in several cases, the involvement  of these putative iii(man) proteins in the pep-dependent phosphorylation of 2-deoxyglucose was substantiated by the inhibition of phosphorylation activity of anti-iii(man) antibodies. no proteins cross-reacting with anti-iii(man) antibodies were detected in enterococci, bacilli, and e. coli. in s. aureus, a membrane protein with a molecular weight of 50,000 reacted strongly with the antibodies. this protein, however, was not phosphorylated at the expense of pep.
TIHT== 
ABHT== 

PMID== 7814703
TI  == absence of cholic acid 7 alpha-dehydroxylase activity in the strains of lactobacillus and bifidobacterium.
AB  == to investigate the presence of 7 alpha-dehydroxylase activity on bile acids in the bacterial strains of fermented milk products, 46 strains of lactobacillus casei, lactobacillus paracasei, lactobacillus rhamnosus, lactobacillus acidophilus, lactobacillus gasseri, bifidobacterium adolescentis, bifidobacterium bifidum, bifidobacterium breve, bifidobacterium infantis, bifidobacterium longum, lactococcus lactis spp. lactis, and streptococcus salivarius spp. thermophilus were tested for their ability to produce deoxycholic acid from cholic acid. the production of deoxycholic acid was quantitatively measured by radiochromatographic analysis in anaerobically prepared washed whole resting cells and by hplc analysis in growing cultures. resting whole cells from a positive control strain, eubacterium lentum-like strain c-25, converted 81.7% of  .2 mm cholic acid to deoxycholic acid and 3.7% to 7-keto-deoxycholic acid, when the cell suspension was incubated anaerobically at a concentration of 2 mg of protein/ml for 4 h at ph 7.3. however, none of the test strains investigated in this study was able to transform cholic acid under the same conditions. in growing cultures, 91.5% of 150 micrograms/ml of cholic acid was transformed to deoxycholic acid and 1.1% to 7-keto-deoxycholic acid by e. lentum-like c-25 after a 7-d anaerobic incubation. none of the test strains showed production of either  deoxycholic acid or 7-keto-deoxycholic acid as growing cultures.
TIHT== 
ABHT== 

PMID== 8110603
TI  == antimicrobial activity of neutralized extracellular culture filtrates of lactic acid bacteria isolated from a cultured indian milk product ('dahi').
AB  == neutralized extracellular culture filtrate obtained from isolates of lactobacillus acidophilus, lactobacillus delbruecki ssp. bulgaricus, lactobacillus salivarius and lactococcus lactis ssp. lactis from 'dahi' showed weak to moderate inhibition of staphylococcus aureus, bacillus cereus, escherichia coli, bacillus brevis, bacillus circulans, bacillus coagulans, bacillus laterosporus, bacillus subtilis and pseudomonas aeruginosa when tested by the diffusion agar well assay method. the effective minimum quantity of lactic culture filtrates required to obtain complete inhibition of an inoculum of 10(3)  cfu/ml of the bacteria tested was between 20 and 26% (vol/vol), as determined by  the agar incorporation method. neutralized extracellular culture filtrate of these lactic cultures added at a level of 10% in sterile, 10% reconstituted non-fat dry milk was able to either suppress or retard growth of selected bacterial cultures when incubated at 37 degrees c for 24 h. this study indicated  the antimicrobial activity of dahi and the potential of using neutralized extracellular culture filtrate of lactic acid bacteria in the biopreservation of  foods.
TIHT== 
ABHT== 

PMID== 8347427
TI  == characterization and frequency distribution of species of lactic acid bacteria involved in the processing of mawe, a fermented maize dough from benin.
AB  == lactic acid bacteria involved in the natural fermentation of both home-produced and commercial mawe were investigated during a 72 h fermentation period. lactobacillus spp. constitute the majority (94%) of the strains of the lactic acid bacteria isolated, among which 89% represent the betabacterium group. they include l. fermentum (biotype cellobiosus) (41%), l. fermentum or l. reuteri (19%), l. brevis (26%), l. confusus (less than 2%), l. curvatus (less than 1%) and l. buchneri (less than 1%). other isolated lactic acid bacteria were l. salivarius, lactococcus lactis, pediococcus pentosaceus, pediococcus acidilactici and leuconostoc mesenteroides. several species were detected at the early stage of fermentation, but the final stage was dominated by l. fermentum (biotype cellobiosus) and l. fermentum or l. reuteri totalling 90% of the isolated strains. the trend was the same for both home-produced and commercial mawe. no strains of l. plantarum, generally reported as dominating lactic acid bacteria at the final stage of fermentation of most plant foods, were isolated.
TIHT== 
ABHT== 

PMID== 1785932
TI  == purification and characterization of an endopeptidase from lactococcus lactis subsp. cremoris wg2.
AB  == an endopeptidase has been purified to homogeneity from a crude cell extract of lactococcus lactis subsp. cremoris wg2 by a procedure that includes diethyl-aminoethane-sephacel chromatography, phenyl-sepharose chromatography, hydroxylapatite chromatography, and fast protein liquid chromatography over an anion-exchange column and a hydrophobic-interaction column. gel filtration and sodium dodecyl sulfate-polyacrylamide gel electrophoresis indicated a molecular mass of the purified enzyme of 70,000 da. the endopeptidase can degrade several oligopeptides into various tetra-, tri-, and dipeptides. the endopeptidase has no aminopeptidase, carboxypeptidase, dipeptidase, or tripeptidase activity. it is optimally active at ph 6.0 to 6.5 and in the temperature range of 30 to 38 degrees c. the enzyme is inactivated by the chemical agents 1,10-phenanthroline,  ethylenedinitrilotetraacetate, beta-mercaptoethanol, and phenylmethylsulfonyl fluoride and is inhibited by cu2+ and zn2+. the ethylenedinitrilotetraacetate- or 1,10-phenanthroline-treated enzyme can be reactivated by co2+. immunoblotting with specific antibodies raised against the purified endopeptidase indicated that the enzyme is also present in other lactococcus spp., as well as in lactobacillus spp. and streptococcus salivarius subsp. thermophilus.
TIHT== 
ABHT== 

PMID== 2737464
TI  == genome comparison of lactococcus strains by pulsed-field gel electrophoresis.
AB  == the two restriction enzymes smai and apai were found to produce distributions of  dna fragments useful for genome analysis of some lactic acid bacteria (lactococcus lactis and streptococcus salivarius subsp. thermophilus) by pulsed-field gel electrophoresis. the genome size was estimated to be 1750 to 2500 kb depending on the species. each strain displayed unique restriction patterns; nevertheless, the percentage of the comigrating fragments of two isogenic or closely related strains was about 80% and fell to 20-40% when the patterns of two non-related strains of the same species or two strains belonging  to different species were compared.
TIHT== 
ABHT== 

PMID== 16347822
TI  == sugar utilization and acid production by free and entrapped cells of streptococcus salivarius subsp. thermophilus, lactobacillus delbrueckii subsp. bulgaricus, and lactococcus lactis subsp. lactis in a whey permeate medium.
AB  == cells of streptococcus salivarius subsp. thermophilus and lactococcus lactis subsp. lactis entrapped in k-carrageenan-locust bean gum gel performed similarly  to free cells in the conversion of lactose to lactic acid. bead diameter influenced the fermentation rate. cells entrapped in smaller beads (0.5 to 1.0 mm) showed higher release rates, higher lactose, glucose, and formic acid utilization, higher galactose accumulation, and higher lactic acid production than did cells entrapped in larger beads (1.0 to 2.0 mm). values for smaller beads were comparable with those for free cells. immobilization affected the fermentation rate of lactic acid bacteria, especially lactobacillus delbrueckii subsp. bulgaricus. entrapped cells of l. delbrueckii subsp. bulgaricus demonstrated a lower lactic acid production than did free cells in batch fermentation. the kinetics of the production of formic and pyruvic acids by l. lactis subsp. lactis and s. salivarius subsp. thermophilus are presented.
TIHT== 
ABHT== 

