@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 22209604
TI  == combination of culture-dependent and culture-independent molecular methods for the determination of lactic microbiota in sucuk.
AB  == in this study, the culture-dependent and culture-independent molecular methods were used for the identification of lactic acid bacteria (lab) in sucuk a turkish fermented dry sausage. on the one hand, the pcr-dgge method targetting the v1 and v3 regions of 16s dna was applied to dna that was directly extracted from sucuk samples. on the other hand, rep-pcr fingerprinting was performed for the primary  differentiation and grouping of the isolates, and the results were confirmed by sequencing of the 16s rdna and 16s-23s rdna intergenic spacer region. as a result of the pcr-dgge analysis of all the samples, total 8 different lactic acid bacteria were identified, and lactobacillus sakei, lactobacillus curvatus and weissella viridescens were the dominant microbiota among these bacteria. the culture-dependent approach indicated that the majority of the strains belonged to the lactobacillus genera including lb. sakei, lactobacillus plantarum, lb. curvatus, lactobacillus brevis, lactobacillus farciminis and lactobacillus alimentarius. however, leuconostoc and weisella were also detected as minor genera. again, lactococcus piscium, weissella halotolerans, staphylococcus succinus and the comigrated staphylococcus piscifermentans/staphylococcus condimenti/staphylococcus carnosus group were detected only with the culture-independent method while lb. plantarum, leuconostoc mesenteroides and leuconostoc citreum were identified only by using the culture-dependent method. in the results, it was concluded that the combination of culture-dependent and culture-independent methods was necessary for reliable and detailed investigation of lab communities in fermented food products.
TIHT== 
ABHT== 

PMID== 22177712
TI  == in vitro testing of commercial and potential probiotic lactic acid bacteria.
AB  == probiotics are defined as live microorganisms which when administered in adequate amounts confer a health benefit on the host. the objective of this study was to investigate the diversity of selected commercial and potential probiotic lactic acid bacteria using common in vitro screening assays such as transit tolerance in the upper human gastrointestinal tract, adhesion capacity to human intestinal cell lines and effect on epithelial barrier function. the selected bacteria include strains of lactobacillus plantarum, lactobacillus pentosus, lactobacillus farciminis, lactobacillus sakei, lactobacillus gasseri, lactobacillus rhamnosus,  lactobacillus reuteri and pediococcus pentosaceus. viable counts after simulated  gastric transit tolerance showed that l. reuteri strains and p. pentosaceus tolerate gastric juice well, with no reduction of viability, whereas l. pentosus, l. farciminis and l. sakei strains lost viability over 180min. all strains tested tolerate the simulated small intestinal juice well. the bacterial adhesion capacity to human intestinal cells revealed major species and strain differences. overall, l. plantarum mf1298 and three l. reuteri strains had a significant higher adhesion capacity compared to the other strains tested. all strains, both  living and uv-inactivated, had little effect on the epithelial barrier function.  however, living l. reuteri strains revealed a tendency to increase the transepithelial electrical resistance (ter) from 6 to 24h. this work demonstrates the diversity of 18 potential probiotic bacteria, with major species and strain specific effects in the in vitro screening assays applied. overall, l. reuteri strains reveal some interesting characteristics compared to the other strains investigated.
TIHT== 
ABHT== 

PMID== 21327742
TI  == isolation and partial characterization of halotolerant lactic acid bacteria from  two mexican cheeses.
AB  == isolated strains of halotolerant or halophilic lactic acid bacteria (halab) from  cotija and doble crema cheeses were identified and partially characterized by phenotypic and genotypic methods, and their technological abilities were studied  in order to test their potential use as dairy starter components. humidity, a(w), ph, and salt concentration of cheeses were determined. genotypic diversity was evaluated by randomly amplified polymorphic dna-polymerase chain reaction. molecular identification and phylogenetic reconstructions based on 16s rrna gene  sequences were performed. additional technological abilities such as salt tolerance, acidifying, and proteolytic and lipolytic activities were also investigated. the differences among strains reflected the biodiversity of halab in both types of cheeses. lactobacillus acidipiscis, tetragenococcus halophilus,  weissella thailandensis, and lactobacillus pentosus from cotija cheese, and l. acidipiscis, enterococcus faecium, lactobacillus plantarum, lactobacillus farciminis, and lactobacillus rhamnosus from doble crema cheese were identified based on 16s rrna. quantitative and qualitative assessments showed strains of t.  halophilus and l. plantarum to be proteolytic, along with e. faecium, l. farciminis, and l. pentosus to a lesser extent. lipolytic activity could be demonstrated in strains of e. faecium, l. pentosus, l. plantarum, and t. halophilus. strains belonging to the species l. pentosus, l. plantarum, and e. faecium were able to acidify the milk media. this study evidences the presence of halab that may play a role in the ripening of cheeses.
TIHT== 
ABHT== 

PMID== 21255857
TI  == simplification of a complex microbial antilisterial consortium to evaluate the contribution of its flora in uncooked pressed cheese.
AB  == a complex microbial consortium derived from raw milk and composed of populations  classified in 4 groups (lactic acid bacteria (a), gram positive catalase positive bacteria (b), gram negative bacteria (c) and yeasts (d)) can contribute to the inhibition of listeria monocytogenes in the core of an uncooked pressed cheese. to identify what groups may be involved in the inhibition, the consortium was simplified by successively omitting one group at a time. pasteurized milk was inoculated with these more or less complex consortia and their effects on l. monocytogenes count, ph, acids and volatile compounds in the core of uncooked pressed cheese were evaluated. the growth of l. monocytogenes was the highest in  cheeses prepared with pasteurized milk and only st. thermophilus. inhibition in other cheeses was expressed by comparison with growth in these ones. all the consortia containing both lactic acid bacteria (group a) and gram positive catalase positive bacteria (group b)--abcd, abd, abc, ab--were more inhibitory than those containing lactic acid bacteria on its own (a) or associated only with yeasts (ad) or/and gram negative (adc). consortia without lactic acid bacteria were weakly inhibitory or had no effect. gram positive catalase positive bacteria alone were not inhibitory although most of the species became established in the  cheeses. the lactobacillus population (lb. casei, lb. plantarum, lb. curvatus and lb. farciminis) was predominant in cheeses (9 log cfu/g) with a higher count than leuconostoc (7 log cfu/g) and enterococcus (7 log cfu/g). lactobacillus counts were negatively correlated with those of l. monocytogenes (r=-0.84 at 18 days) and with the level of d-lactic acid. there was no correlation between l. monocytogenes and leuconostoc or enterococcus counts. complex consortium abcd and ab not only had a stronger inhibitory power in cheeses than consortium ad, they were also associated with the highest levels of l-lactic and acetic acids. all cheeses inoculated with lactic acid bacteria differed from those without by higher levels of ethyl formiate, pentane and alcohols (2-butanol, 2-pentanol), and lower levels of ketones (2-hexanone, 2,3-butanedione) and aldehydes (2-methyl-butanal). levels of 2-methyl-butanal, 2-butanol and 2-pentanol were higher in abcd and ab cheeses than in ad cheeses. beside their contribution to the inhibition, their effect on cheese flavour must be evaluated.
TIHT== 
ABHT== 

PMID== 17625176
TI  == lactobacillus crustorum sp. nov., isolated from two traditional belgian wheat sourdoughs.
AB  == a polyphasic taxonomic study of the lactic acid bacteria (lab) population in three traditional belgian sourdoughs, sampled between 2002 and 2004, revealed a group of isolates that could not be assigned to any recognized lab species. initially, sourdough isolates were screened by means of (gtg)(5)-pcr fingerprinting. four isolates displaying unique (gtg)(5)-pcr patterns were further investigated by means of phenylalanyl-trna synthase (phes) gene sequence  analysis and represented a bifurcated branch that could not be allocated to any lab species present in the in-house phes database. their phylogenetic affiliation was determined using 16s rrna gene sequence analysis and showed that the four sourdough isolates belong to the lactobacillus plantarum group with lactobacillus mindensis, lactobacillus farciminis and lactobacillus nantensis as closest relatives. further genotypic and phenotypic studies, including whole-cell protein analysis (sds-page), amplified fragment length polymorphism (aflp) fingerprinting, dna-dna hybridization, dna g+c content analysis, growth characteristics and biochemical features, demonstrated that the new sourdough isolates represent a novel lactobacillus species for which the name lactobacillus crustorum sp. nov. is proposed. the type strain of the new species is lmg 23699(t) (=ccug 53174(t)).
TIHT== 
ABHT== 

PMID== 17172026
TI  == [composition diversity of lactic acid bacteria (lab) community al2 used for alfalfa silage].
AB  == alfalfa is the most important forage grass that is difficult to ensile for good quality. using silage inoculants are the important way for preservation of alfalfa silage. through continuous restricted subcultivation, a lactic acid bacteria (lab) community al2 was selected from well-fermented alfalfa silage. plate isolation and denaturing gradient gel electrophoresis (dgge), construction  of 16s rdna clone library were used to identify the composition diversity of al2  community, with 7 strains detected, and they were all belonged to lactobacillus.  the composition ratios of the 7 strains were 55.21%, 19.79%, 14.58%, 3.13%, 3.13%, 3.13%, 1.03% according to 16s rdna clone library. al2-1i, al2-2i, al2-3i,  corresponding to l. plantarum (99.9%), l. kimchii (99.4%), l. farciminis (100%) were detected by plate isolation. among 3 isolates, al2-1i had the highest ability of dropping ph and producing lactic acid, and the amount of lactic acid was reach to 18g/l at 24h cultivated in mrs media. the ability of dropping ph and producing lactic acid of al2-3i was the lowest. from dgge profiles, the dominant  strains in al2 community were l. plantarum and l. kimchii. l. plantarum was detected during the whole process, and l. kimchii was detected in the later phase.
TIHT== 
ABHT== 

PMID== 16076509
TI  == identification of potential probiotic starter cultures for scandinavian-type fermented sausages.
AB  == potential probiotic cultures suitable as starter cultures for the scandinavian-type fermented sausages were identified among strains well-adapted to fermented meats as well as strains originating from a culture collection. from 15 different fermented meat products, 22 strains were isolated as dominant non-starter lactic acid bacteria (nslab). the isolates were identified by rapd, api and sequence analysis of 16s rrna and showed to be five strains of lactobacillus sakei, five strains of lactobacillus farciminis, five strains belonging to the group of lactobacillus plantarum/pentosus, four strains of lactobacillus alimentarius, two strains of lactobacillus brevis and one strain of lactobacillus versmoldensis. heterofermentative strains as well as strains not growing at 37 degrees c and not lowering ph below 5.1 in a meat model were excluded leaving 9 strains for further studies. these strains together with 19 strains from a culture collection were evaluated by in vitro methods including survival upon exposure to ph 2.5 or 0.3% oxgall and adhesion to the human colon adenocarcinoma cell line caco-2 as well as antimicrobial activity against potential pathogens. strains that fulfilled all the probiotic criteria and showed to be fast acid producers in a meat model included three strains belonging to the group of lb. plantarum/pentosus (mf1291, mf1298, mf1300) which originated from the dominant nslab of fermented meat products. mf1291 and mf 1298 were further identified as lb. plantarum and mf1300 as lb. pentosus. the three strains were all successfully applied as starter cultures for the production of fermented sausage. the viable count at the end of the processing period reached high cell numbers (4.7x10(7)-2.9x10(8) cfu/g) and ph of the sausages decreased to ph 4.8-4.9 without any flavour deviation compared to sausage fermented by a commercial meat starter culture.
TIHT== 
ABHT== 

PMID== 15954655
TI  == characterisation of lab in typical salento pecorino cheese.
AB  == twenty-nine strains of lactic acid bacteria isolated from the typical pecorino cheese of the salento area of italy, were identified and grouped according to their genetic similarity. a preliminary characterisation of the strains was conducted by means of morphological and biochemical analysis, but molecular approaches were necessary for the clear identification of the species. for the species detection, the amplification and sequencing of the 16s rdna gene was employed in addition, restriction analysis of amplified rdna (ardra) and pcr and  aflp fingerprinting enabled inter- and intra-specific variation to be estimated upgma cluster analysis was used to divide the strains into distinct clusters which corresponded with the species delineation obtained by molecular identification. the data obtained show that the community of lactobacilli responsible for the fermentation and aging of pecorino cheese is composed of a limited number of species. the main identified strains were lactobacillus brevis, l. plantarum, l. casei, l. sakei, l. pentosus, l. farciminis and leuconostoc mesenteroides.
TIHT== 
ABHT== 

PMID== 14632993
TI  == identification of lactobacillus alimentarius and lactobacillus farciminis with 16s-23s rdna intergenic spacer region polymorphism and pcr amplification using species-specific oligonucleotide.
AB  == aims: the restriction fragment length polymorphism (rflp) method was used to differentiate lactobacillus species having closely related identities in the 16s-23s rdna intergenic spacer region (isr). species-specific primers for lact. farciminis and lact. alimentarius were designed and allowed rapid identification  of these species. methods and results: the 16s-23s rdna spacer region was amplified by primers tala and 23s/p10, then digested by hinfi and taqi enzymes and analysed by electrophoresis. digestion by hinfi was not sufficient to differentiate lact. sakei, lact. curvatus, lact. farciminis, lact. alimentarius,  lact. plantarum and lact. paraplantarum. in contrast, digestion carried out by taqi revealed five different patterns allowing these species to be distinguished, except for lact. plantarum from lact. paraplantarum. the 16s-23s rdna spacer region of lact. farciminis and lact. alimentarius were amplified and then cloned  into vector pcr(r)2.1 and sequenced. the dna sequences obtained were analysed and species-specific primers were designed from these sequences. the specificity of these primers was positively demonstrated as no response was obtained for 14 other species tested. results and conclusions: the species-specific primers for lact. farciminis and lact. alimentarius were shown to be useful for identifying these species among other lactobacilli. the rflp profile obtained upon digestion  with hinfi and taqi enzymes can be used to discriminate lact. farciminis, lact. alimentarius, lact. sakei, lact. curvatus and lact. plantarum. significance and impact of the study: in this paper, we have established the first species-specific primer for pcr identification of lact. farciminis and lact. alimentarius. both species-specific primer and rflp, could be used as tools for rapid identification of lactobacilli up to species level.
TIHT== 
ABHT== 

PMID== 12501428
TI  == lactic acid bacteria found in fermented fish in thailand.
AB  == forty-seven strains of homofermentative rod-shaped and 5 heterofermentative sphere-shaped lactic acid bacteria were isolated from 4 kinds of fermented fish (pla-ra, pla-chom, kung-chom, and hoi-dong) in thailand. these bacteria were separated into four groups by phenotypic and chemotaxonomic characteristics, including fluorometric dna-dna hybridization. five strains (group i) contained meso-diaminopimelic acid in the cell wall. four strains were identified as lactobacillus pentosus, and one strain was l. plantarum. tested strains of this group produced dl-lactic acid. the rest of the rod-shaped bacteria, 23 strains (group ii) and 19 strains (group iii), lacked meso-diaminopimelic acid in the cell wall and were identified as l. farciminis and lactobacillus species, respectively. the tested strains of these groups produced l-lactic acid. the amount of cellular fatty acids of c16:0 and c18:1, and the dna base compositions  were significant for differentiating the strains in groups ii and iii. five strains of cocci in chains (group iv) produced gas from glucose. the tested strains of this group produced d-lactic acid. they were identified as a leuconostoc species. the distribution of these bacteria in fermented fish in thailand is discussed.
TIHT== 
ABHT== 

PMID== 12469319
TI  == lactic acid bacteria isolated from soy sauce mash in thailand.
AB  == fourteen sphere-shaped and 30 rod-shaped lactic acid bacteria were isolated from  soy sauce mash of two factories in thailand. these strains were separated into two groups, group a and group b, by cell shape and dna-dna similarity. group a contained 14 tetrad-forming strains, and these strains were identified as tetragenococcus halophilus by dna similarity. group b contained 30 rod-shaped bacteria, and they were further divided into four subgroups, b1, b2, b3, and b4,  and three ungrouped strains by phenotypic characteristics and dna similarity. subgroup b1 contained 16 strains, and these strains were identified as lactobacillus acidipiscis by dna similarity. subgroup b2 included two strains, and the strains were identified as lactobacillus farciminis by dna similarity. subgroup b3 contained five strains. the strains had meso-diaminopimelic acid in the cell wall, and were identified as lactobacillus pentosus by dna similarity. the strains tested produced dl-lactic acid from d-glucose. subgroup b4 contained  four strains. the strains had meso-diaminopimelic acid in the cell wall, and they were identified as lactobacillus plantarum by dna similarity. two ungrouped strains were homofermentative, and one was heterofermentative. they showed a low  degree of dna similarity with the type strains tested, and were left unnamed. the distribution of lactic acid bacteria in soy sauce mash in thailand is discussed.
TIHT== 
ABHT== 

PMID== 11883675
TI  == fermentation and microflora of plaa-som, a thai fermented fish product prepared with different salt concentrations.
AB  == plaa-som is a thai fermented fish product prepared from snakehead fish, salt, palm syrup and sometimes roasted rice. we studied the effects of different salt concentrations on decrease in ph and on microflora composition during fermentation. two low-salt batches were prepared, containing 6% and 7% salt (w/w) as well as two high-salt batches, containing 9% and 11% salt. ph decreased rapidly from 6 to 4.5 in low-salt batches, whereas in high-salt batches, a slow or no decrease in ph was found. lactic acid bacteria (lab) and yeasts were isolated as the dominant microorganisms during fermentation. lab counts increased to 10(8)-10(9) cfu g(-1) and yeast counts to 10(7)-5 x 10(7) cfu g(-1) in all batches, except in the 11% salt batch, where counts were 1-2 log lower. phenotypic tests, its-pcr, carbohydrate fermentations and 16s rrna gene sequencing identified lab isolates as pediococcus pentosaceus, lactobacillus alimentarius/farciminis, weisella confusa, l. plantarum and lactococcus garviae.  the latter species was only isolated from high-salt batches. phenotypic characteristics, its-pcr and carbohydrate assimilation identified 95% of the yeasts as zygosaccharomyces rouxii. it is concluded that the fermentation of plaa-som is delayed by a salt-level of 9% due to an inhibition of lab growth. the growth of z. rouxii has no influence on the fermentation rate, but may contribute positively to the flavour development of the product.
TIHT== 
ABHT== 

PMID== 11822682
TI  == characterisation of is153, an is3-family insertion sequence isolated from lactobacillus sanfranciscensis and its use for strain differentiation.
AB  == an insertion sequence has been identified in the genome of lactobacillus sanfranciscensis dsm 20451t as segment of 1351 nucleotides containing 37-bp imperfect terminal inverted repeats. the sequence of this element encodes two out of phase, overlapping open reading frames, orfa and orfb, from which three putative proteins are produced. orfab is a transframe protein produced by -1 translational frame shifting between orf a and orf b that is presumed to be the transposase. the large orfab of this element encodes a 342 amino acid protein that displays similarities with transposases encoded by bacterial insertion sequences belonging to the is3 family. in l. sanfranciscensis type strain dsm 20451t multiple truncated is elements were identified. inverse pcr was used to analyze target sites of four of these elements, but except of their highly at rich character not any sequence specificity was identified so far. moreover, no flanking direct repeats were identified. multiple copies of is153 were detected by hybridization in other strains of l. sanfranciscensis. resulting hybridization patterns were shown to differentiate between organisms at strain level rather than a probe targeted against the 16s rdna. with a pcr based approach is153 or highly similar sequences were detected in l. acidophilus, l. casei, l. malefermentans, l. plantarum, l. hilgardii, l. collinoides l. farciminis l. sakei and l. salivarius, l. reuteri as well as in enterococcus faecium, pediococcus acidilactici and p. pentosaceus.
TIHT== 
ABHT== 

PMID== 9925588
TI  == identification of lactic acid bacteria from chili bo, a malaysian food ingredient.
AB  == ninety-two strains of lactic acid bacteria (lab) were isolated from a malaysian food ingredient, chili bo, stored for up to 25 days at 28 degreesc with no benzoic acid (product a) or with 7,000 mg of benzoic acid kg-1 (product b). the strains were divided into eight groups by traditional phenotypic tests. a total of 43 strains were selected for comparison of their sodium dodecyl sulfate-polyacrylamide gel electrophoresis (sds-page) whole-cell protein patterns with a sds-page database of lab. isolates from product a were identified as lactobacillus plantarum, lactobacillus fermentum, lactobacillus farciminis, pediococcus acidilactici, enterococcus faecalis, and weissella confusa. five strains belonging to clusters which could not be allocated to existing species by sds-page were further identified by 16s rrna sequence comparison. one strain was  distantly related to the lactobacillus casei/pediococcus group. two strains were  related to weissella at the genus or species level. two other strains did not belong to any previously described 16s rrna group of lab and occupied an intermediate position between the l. casei/pediococcus group and the weissella group and species of carnobacterium. the latter two strains belong to the cluster of lab that predominated in product b. the incidence of new species and subspecies of lab in chili bo indicate the high probability of isolation of new lab from certain southeast asian foods. none of the isolates exhibited bacteriocin activity against l. plantarum atcc 14917 and lmg 17682.
TIHT== 
ABHT== 

PMID== 24415009
TI  == interaction between lactic acid bacteria and yeasts in sour-dough using a rheofermentometer.
AB  == rheofermentometer assays were used to characterize the leavening of sour-doughs produced using species of lactic acid bacteria (lab) and yeasts, alone or in combination. saccharomyces cerevisiae 141 produced the most co2 and ethanol whereas s. exiguus m14 and lactobacillus brevis subsp. lindneri cb1 contributed poorly to leavening and gave sour-doughs without porosity. in comparison with that seen in sour-dough produced with yeast alone, yeast fermentation with heterofermentative lab present was faster whereas that with homofermentative lab  (l. plantarum dc400, l. farciminis cf3) present was slower and produced more co2. combining l. brevis subsp. lindneri cb1 with s. cerevisiae 141 decreased bacterial cell numbers and souring activity. however, addition of fructose to the sour-dough overcame these problems as well as activating s. cerevisiae 141.
TIHT== 
ABHT== 

PMID== 7848780
TI  == characterisation of lactic acid bacteria isolated from naturally fermented greek  dry salami.
AB  == a total of 348 lactic acid bacteria isolated from five batches of naturally fermented dry salami at various stages of ripening were characterised. the majority of the strains were assigned to two main phylogenetic groups of species: (i) the psychrotrophic, formerly called atypical, meat streptobacteria (169 strains) and (ii) a new genus weissella (120), which was recently proposed (collins et al., 1993) to include leuconostoc paramesenteroides and some other closely related species. meat streptobacteria were identified as lactobacillus curvatus (88 strains) and l. sake (76), whereas 5 strains were indistinguishable  and, thus designated l. sake/curvatus. non-psychrotrophic streptobacteria were also isolated and identified as l. plantarum (34 strains), l. farciminis (10), l. coryniformis (1) and l. casei subsp. pseudoplantarum (1). the majority of the weissella strains (86) were leuconostoc-like bacteria; four of them were identified as w. viridescens, 11 belonged to the newly described w. hellenica (collins et al., 1993), another 11 resembled w. paramesenteroides, whereas 60 isolates were not classified to any species. the latter group comprised strains that produced d(l)-lactate. the remaining weissella were gas-forming, arginine-positive rods assigned to w. minor (31) and w. halotolerans (3). other species identified were enterococcus faecium (10), leuconostoc mesenteroides (1), l. brevis (1) and pediococcus sp. (1). the main criteria used to distinguish between above species as well as their distribution on the five salami batches in relation to their succession with time and suitability as starters were discussed.
TIHT== 
ABHT== 

PMID== 735416
TI  == [the microflora of sour dough. iv. communication: bacterial composition of sourdough starters genus lactobacillus beijerinck (author's transl)].
AB  == the bacterial composition of three so called pure culture sourdough starters of varying origin was investigated. 245 isolates were obtained all belonging to the  genus beijerinck. according to their morphological, physiological and biochemical characteristics they were classified into the subgroups: thermobacterium (l. acidophilus), streptobacterium (l. casei, l. plantarum, l. farciminis, l. alimentarius) and betabacterium (l. brevis, l. brevis var. lindneri, l buchneri,  l. fermentum, l. fructi vorans). in the three sourdough starters the identified lactic organisms varied in number and proportion. in starter preparation "a" only the varieties l. fructi vorans and l. fermentum were present. preparation "b" contained a great variety of microorganisms with l. brevis and l. brevis l. lindneri predominating. in starter "c" l. brevis, l. plantarum and l. alimentarius predominated.
TIHT== 
ABHT== 

