@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25529295
TI  == molecular characterisation of abc-type multidrug efflux systems in bifidobacterium longum.
AB  == administration of probiotic bacteria such as bifidobacterium spp. can prevent antibiotic associated diarrhoea since they can survive the often harsh conditions of the gut. in bifidobacterium longum subsp. longum(t) ncimb 702259, two gene clusters, with homology to the atp-binding cassette (abc) family of efflux transporters, were identified and studied to assess their functional contribution to antibiotic resistance. both gene clusters contained two genes encoding putative efflux transporters and a regulator gene, upstream of the structural genes. reverse transcriptase analysis indicated that the genes in each cluster were transcribed as operons, one where all three genes, including a putative marr-type regulator were transcribed together (bllj_1496/1495/1494), and the other where the two abc-type transporter genes (bllj_1837/1836) were co-transcribed, but excluded the putative regulator (bllj_1838). heterologous expression of the cloned bllj_1837/1836 transporter genes in lactococcus lactis conferred resistance to erythromycin and tetracycline by increasing the minimum inhibitory concentration between 1.5 and 3 fold. the presence of these genes also allowed a 16% increase in the efflux of hoechst 33342 from l. lactis cells containing the two transporter genes, bllj_1837-6. in b. longum, an increase in the levels of transcription of 3.3 fold was observed for bllj_1837 in the presence of erythromycin, as measured by multiplex quantitative pcr. in contrast  to this, the expression of the genes of the bllj_1495/1494 operon in l. lactis did not show significant drug resistance functionality. gel shift experiments showed that in the bllj_1495/1494 operon, the putative marr-type regulator protein (bllj_1496) bound with high affinity to the dna sequence upstream of the  operon in which it was located but this was not erythromycin dependent. this study demonstrated the occurrence of a drug inducible, abc-type transporter system (bllj_1837/1836) in b. longum as well as a putative marr-type dna binding  protein (bllj_1496).
TIHT== 
ABHT== 

PMID== 25277407
TI  == use of selected lactic acid bacteria in the eradication of helicobacter pylori infection.
AB  == helicobacter pylori is among the major pathogenic bacteria that cause chronic gastritis and peptic ulcer disease and is related to the development of gastric cancer. several chemicals, including antibiotics, have been used to eradicate h.  pylori; however, they do not always curb the infection. ten representative type strains of lactic acid bacteria (lab) were screened for antagonism toward h. pylori via inhibition of urease activity. strains inhibiting the binding of h. pylori to human gastric cell line cells and suppressing h. pylori-induced interleukin-8 (il-8) production were also screened. of these, pediococcus pentosaseus (sl4), which inhibited the adhesion of h. pylori to mkn-45 gastric cancer cells, bifidobacterium longum (bg7), with urease inhibiting activity, and  lactococcus lactis (sl3), and enterococcus faecalis (sl5), which suppressed h. pylori-induced il-8 production within mkn-45 and ags cells, were selected. in mouse model, these lab stains in combination significantly suppressed il-8 levels in serum. gastric ph also recovered to normal values after the administration of  these lab. these stains effectively suppressed h. pylori viability, although not  to the extent of antibiotic treatment. when used as probiotics, lab may help decrease the occurrence of gastritis and reduce the risk of h. pylori infection without, inducing side effects.
TIHT== 
ABHT== 

PMID== 25227940
TI  == functional role of tlyc1 encoding a hemolysin-like protein from bifidobacterium longum bbmn68 in bile tolerance.
AB  == bifidobacteria are normal inhabitants of the human gut, and members of which are  generally considered to be probiotic. before exerting their beneficial properties, they must survive and persist in the physiological concentrations (0.05-2%) of bile in the gut. in this work, the functional role of tlyc1 encoding a hemolysin-like protein from bifidobacterium longum bbmn68 in bile tolerance was tested. analysis using the program tmhmm and homologous alignment indicated that  tlyc1 is a nontransporter membrane protein and is conserved in many bifidobacteria. heterologous expression of tlyc1 in lactococcus lactis nz9000 was shown to confer 45-fold higher tolerance to 0.15% ox-bile. notably, the recombinant strains showed threefold higher survival when exposed to sublethal concentration of tca and tdca, while no significant change was observed when exposed to gca and gdca. furthermore, real-time quantitative pcr demonstrated that the transcription of tlyc1 was up-regulated c. 2.5- and 2.7-fold in b. longum bbmn68 exposed to sublethal concentration of tca and tdca, while no significant change was observed with gca and gdca challenges. this study indicated that tlyc1 was specifically induced by tauroconjugates, which provided  enhanced resistance to sodium taurocholate and sodium taurodeoxycholate.
TIHT== 
ABHT== 

PMID== 25064650
TI  == effect of kcl substitution on bacterial viability of escherichia coli (atcc 25922) and selected probiotics.
AB  == excessive intake of nacl has been associated with the increased risk of several diseases, particularly hypertension. strategies to reduce sodium intake include substitution of nacl with other salts, such as kcl. in this study, the effects of nacl reduction and its substitution with kcl on cell membranes of a cheese starter bacterium (lactococcus lactis ssp. lactis), probiotic bacteria (bifidobacterium longum, lactobacillus acidophilus, and lactobacillus casei), and a pathogenic bacterium (escherichia coli) were investigated using fourier-transform infrared (ftir) spectroscopy. a critical nacl concentration that inhibited the viability of e. coli without affecting the viability of probiotic bacteria significantly was determined. to find the critical nacl concentration, de man, rogosa, and sharpe (mrs) broth was supplemented with a range of nacl concentrations [0 (control), 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, and 5.0%], and the effect on cell viability and ftir spectra was monitored for all bacteria. a nacl concentration of 2.5% was found to be the critical level of nacl to inhibit e. coli without significantly affecting the viability of most of the probiotic bacteria and the cheese starter bacterium. the ftir spectral analysis also highlighted the changes that occurred mainly in the amide regions upon increasing the nacl concentration from 2.5 to 3.0% in most of  the bacteria. escherichia coli and b. longum were more sensitive to substitution  of nacl with kcl, compared with lb. acidophilus, lb. casei, and lc. lactis ssp. lactis. to evaluate the effect of substitution of nacl with kcl, substitution was carried out at the critical total salt concentration (2.5%, wt/vol) at varying concentrations (0, 25, 50, 75, and 100% kcl). the findings suggest that 50% substitution of nacl with kcl, at 2.5% total salt, could inhibit e. coli without  affecting the probiotic bacteria.
TIHT== 
ABHT== 

PMID== 24965555
TI  == integrated transcriptomic and proteomic analysis of the bile stress response in a centenarian-originated probiotic bifidobacterium longum bbmn68.
AB  == bifidobacteria are natural inhabitants of the human gastrointestinal tract and well known for their health-promoting effects. tolerance to bile stress is crucial for bifidobacteria to survive in the colon and to exert their beneficial  actions. in this work, rna-seq transcriptomic analysis complemented with proteomic analysis was used to investigate the cellular response to bile in bifidobacterium longum bbmn68. the transcript levels of 236 genes were significantly changed (>/= threefold, p < 0.001) and 44 proteins were differentially abundant (>/=1.6-fold, p < 0.01) in b. longum bbmn68 when exposed  to 0.75 g l(-1) ox-bile. the hemolysin-like protein and bile efflux systems were  significantly over produced, which might prevent bile adsorption and exclude bile, respectively. the cell membrane composition was modified probably by an increase of cyclopropane fatty acid and a decrease of transmembrane proteins, resulting in a cell membrane more impermeable to bile salts. our hypothesis was later confirmed by surface hydrophobicity assay. the transcription of genes related to xylose utilization and bifid shunt were up-regulated, which increased  the production of atp and reducing equivalents to cope with bile-induced damages  in a xylan-rich colon environment. bile salts signal the b. longum bbmn68 to gut  entrance and enhance the expression of esterase and sortase associated with adhesion and colonization in intestinal tract, which was supported by a fivefold  increased adhesion ability to ht-29 cells by bbmn68 upon bile exposure. notably,  bacterial one-hybrid and emsa assay revealed that the two-component system senx3-regx3 controlled the expression of psts in bifidobacteria and the role of this target gene in bile resistance was further verified by heterologous expression in lactococcus lactis. taken altogether, this study established a model for global response mechanisms in b. longum to bile.
TIHT== 
ABHT== 

PMID== 22903573
TI  == d-tagatose production in the presence of borate by resting lactococcus lactis cells harboring bifidobacterium longum l-arabinose isomerase.
AB  == bifidobacterium longum nrrl b-41409 l-arabinose isomerase (l-ai) was overexpressed in lactococcus lactis using a phosphate depletion inducible expression system. the resting l. lactis cells harboring the b. longum l-ai were  used for production of d-tagatose from d-galactose in the presence of borate buffer. multivariable analysis suggested that high ph, temperature and borate concentration favoured the conversion of d-galactose to d-tagatose. almost quantitative conversion (92 %) was achieved at 20 g l(-)(1) substrate and at 37.5 degrees c after 5 days. the d-tagatose production rate of 185 g l(-)(1) day (-)(1) was obtained at 300 g l(-)(1) galactose, at 1.15 m borate, and at 41 degrees c during 10 days when the production medium was changed every 24 h. there was no significant loss in productivity during ten sequential 24 h batches. the initial d-tagatose production rate was 290 g l(-)(1) day(-)(1) under these conditions.
TIHT== 
ABHT== 

PMID== 22763951
TI  == bifidobacterium longum l-arabinose isomerase--overexpression in lactococcus lactis, purification, and characterization.
AB  == bifidobacterium longum nrrl b-41409 l-arabinose isomerase (l-ai) was cloned and overexpressed in lactococcus lactis using a phosphate-depletion-inducible expression system. the purified b. longum l-ai was characterized using d-galactose and l-arabinose as the substrates. the enzyme was active and stable at acidic ph with an optimum at ph 6.0-6.5. the enzyme showed the highest activity at 55 degrees c during a 20-min incubation at ph 6.5. the k(m) value was 120 mm for l-arabinose and 590 mm for d-galactose. the v(max) was 42 u mg(-1) with l-arabinose and 7.7 u mg(-1) with d-galactose as the substrates. the enzyme  had very low requirement for metal ions for catalytic activity, but it was stabilized by divalent metal ions (mg(2+), mn(2+)). the enzyme bound the metal ions so tightly that they could not be fully removed from the active site by edta treatment. using purified b. longum l-ai as the catalyst at 35 degrees c, equilibrium yields of 36 % d-tagatose and 11 % l-ribulose with 1.67 m d-galactose and l-arabinose, respectively, as the substrates were reached.
TIHT== 
ABHT== 

PMID== 21338777
TI  == improved viability of bifidobacteria in fermented milk by cocultivation with lactococcus lactis subspecies lactis.
AB  == the poor survival of probiotic bacteria in commercial yogurts may limit their potential to exert health benefits in humans. the objective was to improve the survival of bifidobacteria in fermented milk. cocultivation with some strains of  lactococcus lactis ssp. lactis improved the survival of bifidobacteria in fermented milk during refrigerated storage. studies on one strain, lc. lactis ssp. lactis mcc866, showed that the concentrations of dissolved oxygen were kept  lower in the cocultivated fermented milk during storage compared with monocultured bifidobacterium longum bb536 or samples cocultured with another noneffective lc. lactis ssp. lactis strain. degradation of genomic dna was suppressed in the cocultivating system with lc. lactis ssp. lactis mcc866. several genes that participated in protection from active oxygen species (e.g., genes coding for alkyl hydroperoxide reductase and fe(2+) transport system) were  expressed at higher levels during refrigerated storage in lc. lactis ssp. lactis  mcc 866 compared with another noneffective lc. lactis ssp. lactis strain. concentration of free iron ion was also lower in supernatants of fermented milk cocultivated with b. longum bb536 and lc. lactis ssp. lactis mcc866. these results suggest that lc. lactis ssp. lactis mcc 866 is potentially superior in reducing oxygen damage and consequently improves the survival of bifidobacteria in the cocultivating system. this cocultivation system is of industrial interest  for producing fermented milk containing viable bifidobacteria with long shelf life.
TIHT== 
ABHT== 

PMID== 19818009
TI  == effect of production conditions on the stability of a human bifidobacterial species bifidobacterium longum in yogurt.
AB  == aims: human bifidobacteria are more sensitive to external environmental factors than animal bifidobacteria, and it is difficult to ensure their stable survival in yogurt. the purpose of this investigation was to observe the survival of human bifidobacteria in yogurts produced under various production conditions. methods:  frozen or lyophilized bifidobacteria starters containing bifidobacterium longum bb536 originally isolated from an infant, and commercial lyophilized yogurt starters were used for yogurt preparation. after producing yogurts under various  conditions, the survival of bifidobacteria in these yogurts over various storage  periods was observed. results: although there were some differences in bifidobacterial survival in yogurt between various production conditions, more than 1.0 x 10(7) cfu g(-1) of bif. longum survived in yogurt after 35 days' storage at 5 degrees c. lower fermentation temperature (37 degrees c) and inclusion of lactococcus lactis in the starter significantly (p < 0.05) improved  survival of bif. longum in the yogurt. conclusion: in this investigation, the human bifidobacterial strain bif. longum survived adequately in yogurt, although  the fermentation temperature and starter composition affect bifidobacterial survival. significance and impact of the study: this investigation indicates that stable probiotic yogurt using human bifidobacteria can be produced by choosing optimal production conditions.
TIHT== 
ABHT== 

PMID== 19361877
TI  == antimicrobial susceptibility testing of lactic acid bacteria and bifidobacteria by broth microdilution method and etest.
AB  == we applied two methods of broth microdilution and etest for measuring minimal inhibition concentration (mic) of lactic acid bacteria and bifidobacteria for 15  antimicrobial agents to compare the feasibility, reproducibility, and equivalence of the two methods. both methods were originally described by the european projects prosafe and ace-art. in 84% combinations of strains and antimicrobial agents mic differences between the two methods were within one log(2) dilution. in the case of rifampicin the difference between the two methods was more than ten-fold. we further determined mics of 70 strains (14 strains of lactobacillus delbrueckii ssp. bulgaricus, 16 strains of lactococcus lactis, 30 strains of streptococcus thermophilus, and 10 strains of bifidobacterium longum) by the broth microdilution method. in most cases, mic distributions were uni-modal and within 5 log(2) dilutions except for the mic distribution of l. lactis to the aminoglycoside group which was broader. these data are a good basis for improving knowledge of antimicrobial susceptibility of lactic acid bacteria and bifidobacteria, and can be used to revise tentative epidemiological cut-off values.
TIHT== 
ABHT== 

PMID== 18539807
TI  == improved cloning vectors for bifidobacteria, based on the bifidobacterium catenulatum pbc1 replicon.
AB  == this study reports the development of several cloning vectors for bifidobacteria  based on the replicon of pbc1, a cryptic plasmid from bifidobacterium catenulatum l48 thought to replicate via the theta mode. these vectors, in which antibiotic resistance genes encoding either erythromycin or tetracycline resistance acted as selection markers, were able to replicate in a series of eight bifidobacterium species at frequencies ranging from 4.0 x 10(1) to 1.0 x 10(5) transformants microg(-1) but not in lactococcus lactis or lactobacillus casei. they showed a relative copy number of around 30 molecules per chromosome equivalent and a good  segregational stability, with more than 95% of the cells retaining the vectors after 80 to 100 generations in the absence of selection. vectors contain multiple cloning sites of different lengths, and the laczalpha peptide gene was introduced into one of the molecules, thus allowing the easy selection of colonies harboring recombinant plasmids in escherichia coli. the functionality of the vectors for engineering bifidobacterium strains was assessed by cloning and examining the expression of an alpha-l-arabinofuranosidase gene belonging to bifidobacterium longum. e. coli and bifidobacterium pseudocatenulatum recombinant clones were stable and showed an increase in alpha-arabinofuranosidase activity of over 100-fold compared to that of the untransformed hosts.
TIHT== 
ABHT== 

PMID== 16300933
TI  == testing of a whole genome pcr scanning approach to identify genomic variability in four different species of lactic acid bacteria.
AB  == genomes can be markedly heterogeneous in conspecific bacterial strains. genome sequences can be used to analyze genome plasticity via a pcr(2) (plasticity of chromosome revealed by pcr) approach. small-sized chromosomes can indeed be fully amplified by long-range pcr with a set of primers designed using a reference strain and then applied to several other strains. analysis of the resulting patterns can reveal genome plasticity. genofrag, a software package for the design of primers optimized for pcr(2) [n. ben zakour, m. gautier, r. andonov, d. lavenier, m.f. cochet, p. veber, a. sorokin, y. le loir, genofrag: software to design primers optimized for whole genome scanning by long-range pcr amplification, nucleic acids res. 32 (2004) 17-24] was developed for the analysis of bacterial genome plasticity by whole genome amplification in approximately 10-kb-long fragments. by applying genofrag, we provide herewith evidence that genome plasticity can be analyzed in lactic acid bacteria using a pcr(2) approach. the genome sequences of lactococcus lactis il1403, lactobacillus plantarum wcfs1, lactobacillus bulgaricus atcc11842 and bifidobacterium longum ncc2705 were used to design four sets of primers. each set was evaluated in silico to check that it ensured optimum coverage of the bacterial chromosome. to  validate the primers generated by genofrag, a subset of primers was successfully  used in lr-pcr experiments on genomic dna from four l. bulgaricus strains.
TIHT== 
ABHT== 

PMID== 16238755
TI  == production of propionibacterium shermanii biomass and vitamin b12 on spent media.
AB  == aims: the propionibacteria are commercially important due to their use in the cheese industry, and there is a growing interest for their probiotic effects. stimulatory effects of lactic acid bacteria (lab) on propionic acid bacteria have been observed. this study was designed to examine the possibility of using spent  media previously used to grow lab for the production of biomass and metabolites of propionibacterium freudenreichii subsp. shermanii. methods and results: seventeen mrs and vegetable juice media were prefermented by various lab and evaluated for their ability to subsequently support the growth of propionibacterium, using automated spectrophotometry (as). growth of propionibacterium in spent media was strongly affected by the lab strain used to  produce the spent medium. the native mrs medium (not prefermented) yielded the highest optical density values followed by prefermented media by lactobacillus acidophilus, bifidobacterium longum and lactococcus lactis. prefermented cabbage  juice enabled good growth of propionibacterium. for the production of organic acids and vitamin b12, cells of propionibacterium were concentrated and immobilized in alginate beads in the aim of accelerating the bioconversions. more propionic acid was obtained in spent media than in native mrs. the concentration  of vitamin b12 was higher in media fermented with free cells than those with immobilized cultures; with the free cells, its concentration varied from 900 to 1800 ng ml(-1) of media. conclusions: it was demonstrated that spent media could  be recycled for the production of propionibacterium and metabolites, depending on the lab strain that was previously grown. media remediation is needed to improve  the production of vitamin b12, especially with immobilized cells. significance and impact of the study: this study presents an option for recycling of spent media generated by producers of lab or producers of fermented vegetables. the propionic fermentation may result in three commercial products: biomass, vitamin  b12 or organic acids, which may be used as starters, supplements or food preservatives. it is an attractive process from economical and environmental standpoints.
TIHT== 
ABHT== 

PMID== 15281933
TI  == increased stress tolerance of bifidobacterium longum and lactococcus lactis produced during continuous mixed-strain immobilized-cell fermentation.
AB  == aims: the effect of immobilization and long-term continuous culture was studied on probiotic and technological characteristics of lactic acid and probiotic bacteria. methods and results: a continuous culture in a two-stage system was carried out for 17 days at different temperatures ranging from 32 to 37 degrees c, with a first reactor containing bifidobacterium longum atcc 15707 and lactococcus lactis subsp. lactis biovar. diacetylactis md immobilized separately  in gel beads, and a second reactor operated with free cells released from the first reactor. the tolerance of free cells from both strains produced in the effluent medium of both reactors to hydrogen peroxide, simulated gastric and intestinal juices, antibiotics and nisin, and freeze-drying markedly increased with culture time and was generally higher after 6 days than that of stationary-phase cells produced during free-cell batch fermentations. the reversibility of the acquired tolerance of b. longum, but not l. diacetylactis, to antibiotics was shown during successive free-cell batch cultures. conclusions: free cells produced from continuous immobilized-cell culture exhibited altered physiology and increased tolerance to various chemical and physico-chemical stresses. significance and impact of the study: continuous culture with immobilized cells could be used to produce probiotic and lactic acid bacteria with enhanced technological and probiotic characteristics.
TIHT== 
ABHT== 

PMID== 14763837
TI  == continuous production of mixed lactic starters containing probiotics using immobilized cell technology.
AB  == the production of a mixed lactic culture containing lactococcus lactis subsp. lactis biovar. diacetylactis md and bifidobacterium longum atcc 15707 was studied during a 17-day continuous immobilized-cell culture at different temperatures between 32 and 37 degrees c. the two-stage fermentation system was composed of a  first reactor (r1) containing cells of the two strains separately immobilized in  kappa-carrageenan/locust bean gum gel beads and a second reactor (r2) operated with free cells released from the first reactor. the system allowed continuous production of a concentrated mixed culture with a strain ratio whose composition  depended on temperature and fermentation time. a stable mixed culture (with a 22:1 ratio of l. diacetylactis and b. longum) was produced at 35 degrees c in the effluent of r2, whereas the mixed culture was rapidly unbalanced in favor of b. longum at a higher temperature (37 degrees c) or l. diacetylactis at a lower temperature (32 degrees c). strain redistribution in beads originally immobilizing pure cultures of l. diacetylactis or b. longum was observed. at the  end of culture, the strain ratio (7:1 l. diacetylactis/b. longum) in bulk bead samples was similar to that of individual beads. the determination of the spatial distribution of the two strains in gel beads by immunofluorescence and confocal laser-scanning microscopy showed that bead cross-contamination was limited to a 100 microm peripheral layer. data from this study validate a previous model for population dynamics and cell release in gel beads during mixed immobilized-cell cultures.
TIHT== 
ABHT== 

PMID== 12957891
TI  == purification and functional characterization of a novel alpha-l-arabinofuranosidase from bifidobacterium longum b667.
AB  == the gene encoding a novel alpha-l-arabinofuranosidase from bifidobacterium longum b667, abfb, was cloned and sequenced. the deduced protein had a molecular mass of about 61 kda, and analysis of its amino acid sequence revealed significant homology and conservation of different catalytic residues with alpha-l-arabinofuranosidases belonging to family 51 of the glycoside hydrolases.  regions flanking the gene comprised two divergently transcribed open reading frames coding for hypothetical proteins involved in sugar metabolism. a histidine tag was introduced at the c terminus of abfb, and the recombinant protein was overexpressed in lactococcus lactis under control of the tightly regulated, nisin-inducible nisa promoter. the enzyme was purified by nickel affinity chromatography. the molecular mass of the native protein, as determined by gel filtration, was about 260 kda, suggesting a homotetrameric structure. abfb was active at a broad ph range (ph 4.5 to 7.5) and at a broad temperature range (20 to 70 degrees c), and it had an optimum ph of 6.0 and an optimum temperature of 45 degrees c. the enzyme seemed to be less thermostable than most previously described arabinofuranosidases and had a half-life of about 3 h at 55 degrees c.  chelating and reducing agents did not have any effect on its activity, but the presence of cu(2+), hg(2+), and zn(2+) markedly reduced enzymatic activity. the protein exhibited a high level of activity with p-nitrophenyl alpha-l-arabinofuranoside, with apparent k(m) and v(max) values of 0.295 mm and 417 u/mg, respectively. abfb released l-arabinose from arabinan, arabinoxylan, arabinobiose, arabinotriose, arabinotetraose, and arabinopentaose. no endoarabinanase activity was detected. these findings suggest that abfb is an exo-acting enzyme and may play a role, together with other glycosidases, in the degradation of l-arabinose-containing polysaccharides.
TIHT== 
ABHT== 

PMID== 12111161
TI  == quantitative determination of the spatial distribution of pure- and mixed-strain  immobilized cells in gel beads by immunofluorescence.
AB  == a new method was developed to detect and quantify two strains, lactococcus lactis subsp. lactis biovar. diacetylactis md and bifidobacterium longum atcc 15707, immobilized separately and co-immobilized in gel beads, using specific polyclonal antibodies and confocal laser-scanning microscopy. the establishment of biomass concentration profiles for each strain was measured during colonization of beads  using successive ph-controlled batch fermentations. growth occurred preferentially in 200- and 300-microm peripheral layers of the beads for l. diacetylactis and b. longum, respectively. repeated-batch cultures with immobilized cells permitted the production of a mixed culture containing a non-competitive strain of bifidobacteria, as a result of immobilized-cell growth  and high cell-release activity from the beads. during co-immobilized fermentations, there were no apparent interactions between the strains.
TIHT== 
ABHT== 

PMID== 11003217
TI  == viability of probiotic (bifidobacterium, lactobacillus acidophilus and lactobacillus casei) and nonprobiotic microflora in argentinian fresco cheese.
AB  == we evaluated the suitability of argentinian fresco cheese as a food carrier of probiotic cultures. we used cultures of bifidobacterium bifidum (two strains), bifidobacterium longum (two strains), bifidobacterium sp. (one strain), lactobacillus acidophilus (two strains), and lactobacillus casei (two strains) in different combinations, as probiotic adjuncts. probiotic, lactic starter (lactococcus lactis and streptococcus thermophilus), and contaminant (coliforms,  yeasts, and molds) organisms were counted at 0, 30, and 60 d of refrigerated storage. furthermore, the acid resistance of probiotic and starter bacteria was determined from hydrochloric solutions (ph 2 and 3) of fresco cheese. the results showed that nine different combinations of bifidobacteria and l. acidophilus had  a satisfactory viability (count decreases in 60 d <1 log order) in the cheese. both combinations of bifidobacteria and l. casei cultures assayed also showed a satisfactory survival (counts decreased <1 log order for bifidobacteria but no decrease was detected for l. casei). on the other hand, the three combinations of bifidobacteria, l. acidophilus, and l. casei tested adapted well to the fresco cheese environment. when a cheese homogenate at ph 3 was used to partially simulate the acidic conditions in the stomach, the probiotic cultures had an excellent ability to remain viable up to 3 h. at ph 2, the cell viability was more affected; b. bifidum was the most resistant organism. this study showed that the argentinian fresco cheese could be used as an adequate carrier of probiotic bacteria.
TIHT== 
ABHT== 

PMID== 7814703
TI  == absence of cholic acid 7 alpha-dehydroxylase activity in the strains of lactobacillus and bifidobacterium.
AB  == to investigate the presence of 7 alpha-dehydroxylase activity on bile acids in the bacterial strains of fermented milk products, 46 strains of lactobacillus casei, lactobacillus paracasei, lactobacillus rhamnosus, lactobacillus acidophilus, lactobacillus gasseri, bifidobacterium adolescentis, bifidobacterium bifidum, bifidobacterium breve, bifidobacterium infantis, bifidobacterium longum, lactococcus lactis spp. lactis, and streptococcus salivarius spp. thermophilus were tested for their ability to produce deoxycholic acid from cholic acid. the production of deoxycholic acid was quantitatively measured by radiochromatographic analysis in anaerobically prepared washed whole resting cells and by hplc analysis in growing cultures. resting whole cells from a positive control strain, eubacterium lentum-like strain c-25, converted 81.7% of  .2 mm cholic acid to deoxycholic acid and 3.7% to 7-keto-deoxycholic acid, when the cell suspension was incubated anaerobically at a concentration of 2 mg of protein/ml for 4 h at ph 7.3. however, none of the test strains investigated in this study was able to transform cholic acid under the same conditions. in growing cultures, 91.5% of 150 micrograms/ml of cholic acid was transformed to deoxycholic acid and 1.1% to 7-keto-deoxycholic acid by e. lentum-like c-25 after a 7-d anaerobic incubation. none of the test strains showed production of either  deoxycholic acid or 7-keto-deoxycholic acid as growing cultures.
TIHT== 
ABHT== 

PMID== 1452029
TI  == cloning and sequence analysis of the gene encoding l-lactate dehydrogenase from lactococcus lactis: evolutionary relationships between 21 different ldh enzymes.
AB  == lactate dehydrogenase (ldh; ec1.1.1.27) is a key enzyme in the fermentation of milk by lactic acid bacteria used in the dairy industry. an 800-bp dna fragment containing part of the gene (ldh) encoding ldh was amplified from lactococcus lactis in a polymerase chain reaction using primers designed from the partial amino acid sequence of a lactococcal ldh. this fragment was radioactively labelled and used to probe a phage lambda library of lc. lactis genomic dna. fragments containing ldh were subcloned from lambda to puc13 and puc18 and a 1.2-kb region was sequenced. the deduced aa sequence reveals that the lactococcal ldh is highly homologous to the ldhs of other organisms. the active site and several other domains of unknown function are highly conserved between all ldh enzymes (prokaryotic and eukaryotic). an evolutionary study of ldh sequences clearly divides the prokaryotic from the eukaryotic enzymes except for the bifidobacterium longum ldh which anomalously groups with the eukaryotic enzymes.  the ldhs from gram-positive bacteria form a separate group from the enzymes from  the gram-negative organisms. the lactococcal ldh is phylogenetically closest to the streptococcal ldh.
TIHT== 
ABHT== 

