@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25597646
TI  == diversity of lactic acid bacteria isolated from brazilian water buffalo mozzarella cheese.
AB  == the water buffalo mozzarella cheese is a typical italian cheese which has been introduced in the thriving brazilian market in the last 10 y, with good acceptance by its consumers. lactic acid bacteria (lab) play an important role in the technological and sensory quality of mozzarella cheese. in this study, the aim was to evaluate the diversity of the autochthones viable lab isolated from water buffalo mozzarella cheese under storage. samples were collected in 3 independent trials in a dairy industry located in the southeast region of brazil, on the 28th day of storage, at 4 masculinec. the lab were characterized by gram staining, catalase test, capacity to assimilate citrate, and production of co2 from glucose. the diversity of lab was evaluated by rapd-pcr (randomly amplified  polymorphic dna-polymerase chain reaction), 16s rrna gene sequencing, and by vitek 2 system. twenty lab strains were isolated and clustered into 12 different  clusters, and identified as streptococcus thermophilus, enterococcus faecium, enterococcus durans, leuconostoc mesenteroides subsp. mesenteroides, lactobacillus fermentum, lactobacillus casei, lactobacillus delbrueckii subsp. bulgaricus, and lactobacillus helveticus. enterococcus species were dominant and  citrate-positive. only the strains of l. mesenteroides subsp. mesenteroides and l. fermentum produced co2 from glucose and were citrate-positive, while l. casei  was only citrate positive. this is the first report which elucidates the lab diversity involved in brazilian water buffalo mozzarella cheese. furthermore, the results show that despite the absence of natural whey cultures as starters in production, the lab species identified are the ones typically found in mozzarella cheese.
TIHT== 
ABHT== 

PMID== 23290237
TI  == development of a multiplex real time pcr to detect thermophilic lactic acid bacteria in natural whey starters.
AB  == a multiplex real time pcr (mrealt-pcr) useful to rapidly screen microbial composition of thermophilic starter cultures for hard cooked cheeses and to compare samples with potentially different technological properties was developed. novel primers directed toward phes gene were designed and optimized for multiple detection of lactobacillus helveticus, lactobacillus delbrueckii, streptococcus thermophilus and lactobacillus fermentum. the assay was based on sybr green chemistry followed by melting curves analysis. the method was then evaluated for applications in the specific detection of the 4 lactic acid bacteria (lab) in 29 different natural whey starters for parmigiano reggiano cheese production. the results obtained by mrealt-pcr were also compared with those obtained on the same samples by fluorescence in situ hybridization (fish) and length-heterogeneity pcr (lh-pcr). the mrealt-pcr developed in this study, was found to be effective for analyzing species present in the samples with an average sensitivity down to less than 600 copies of dna and therefore sensitive enough to detect even minor lab community members of thermophilic starter cultures. the assay was able to describe the microbial population of all the different natural whey starter samples analyzed, despite their natural variability. a higher number of whey starter samples with s. thermophilus and l.  fermentum present in their microbial community were revealed, suggesting that these species could be more frequent in parmigiano reggiano natural whey starter  samples than previously shown. the method was more effective than lh-pcr and fish and, considering that these two techniques have to be used in combination to detect the less abundant species, the mrealt-pcr was also faster. providing a single step sensitive detection of l. helveticus, l. delbrueckii, s. thermophilus and l. fermentum, the developed mrealt-pcr could be used for screening thermophilic starter cultures and to follow the presence of those species during  ripening of derived dairy products. a major increase in understanding the starter culture contribution to cheese ecosystem could be harnessed to control cheese ripening and flavor formation.
TIHT== 
ABHT== 

PMID== 22475947
TI  == monitoring of the microbial communities involved in the soy sauce manufacturing process by pcr-denaturing gradient gel electrophoresis.
AB  == soy sauce is a traditional seasoning produced through the fermentation of soybeans and wheat using microbes. in this study, the microbial communities involved in the soy sauce manufacturing process were analyzed by pcr-denaturing gradient gel electrophoresis (pcr-dgge). the bacterial dgge profile indicated that the bacterial microbes in the koji were weissella cibaria (weissella confusa, weissella kimchii, weissella salipiscis, lactobacillus fermentum, lactobacillus plantarum, lactobacillus iners, or streptococcus thermophilus), staphylococcus gallinarum (or staphylococcus xylosus), and staphylococcus kloosii. in addition to these bacteria, tetragenococcus halophilus was also detected in the mash during lactic acid fermentation. the fungal dgge profile indicated that the fungal microbes in the koji were not only aspergillus oryzae but also several yeasts. in the mash, zygosaccharomyces rouxii appeared in the early fermentation stage, candida etchellsii (or candida nodaensis) and candida versatilis were detected at the middle fermentation stage, and candida etchellsii was detected at the mature fermentation stage. these results suggest that the microbial communities present during the soy sauce manufacturing process change drastically throughout its production. this is the first report to reveal the microbial communities involved in the soy sauce manufacturing process using a culture-independent method.
TIHT== 
ABHT== 

PMID== 22336342
TI  == [development of pulsed field gel electrophoresis and application for characterization and identification of lactobacillus and streptococcus thermophilus].
AB  == objective: to develop a pulsed field gel electrophoresis (pfge) method for molecular typing of lactobacillus and streptococcus thermophilus (s. thermophilus) and to apply it in identification and characterization of both bacteria isolated from yoghurt collected from beijing supermarket. methods: the five most useful restriction enzymes including apa i, not i, sfi i, xba i and sma i were chosen to cut dna of 52 strains of lactobacillus, s. thermophilus as well  as associated standard bacteria strains. the endonucleases and electrophoresis conditions for pfge analysis were optimized and applied in molecular typing of lactobacillus and s.thermophilus isolates. cluster analysis based on the pfge data was conducted. the identification results of pfge were compared with those obtained in biochemical and 16s ribosomal rna pcr identification tests. results:  not i was suitable for l. bulgaricus, l. fermentum and l. delbrueckii digestion.  while apa i was an appropriate endonuclease for s. thermophilus, l. acidophilus and l. casei digestion. the results of molecular typing indicated that 24 strains of l.bulgaricus and 15 strains of s. thermophilus were grouped into 8 types by pfge method, respectively. while 7 strains of l.acidophilus were grouped into 3 types and 2 strains of l. delbrueckii were grouped into 2 different pfge types. conclusion: the results of pfge analysis are in compliance with those of 16s rrna pcr and biochemical identification. the pfge method developed in this study is suitable for molecular characterization of both lactobacillus and s. thermophilus.
TIHT== 
ABHT== 

PMID== 21839384
TI  == effect of grape polyphenols on lactic acid bacteria and bifidobacteria growth: resistance and metabolism.
AB  == food polyphenols are able to selectively modify the growth of susceptible micro-organisms. this study describes the effect of a flavan-3-ol enriched grape  seed extract (gse) on the growth of several lactic acid bacteria (lab) and bifidobacteria and the ability of the resistant strains to metabolize these compounds. streptococcus thermophilus, lactobacillus fermentum, lactobacillus acidophilus and lactobacillus vaginalis strains showed a remarkable sensitivity to the phenolic extracts assayed, including a gse fraction consisting mainly in (+)-catechin and (-)-epicatechin (gse-m). on the other hand, lactobacillus plantarum, lactobacillus casei, and lactobacillus bulgaricus strains reached maximal growth with the gse fractions, including a rich-oligomeric (gse-o) fraction. within bifidobacteria, bifidobacterium lactis bb12 showed the highest sensitivity to the phenolic extracts assayed, whereas bifidobacterium breve 26m2  and bifidobacterium bifidum hdd541 reached maximum growth in presence of gse-o and gse-m fractions. metabolism of flavan-3-ols by lab and bifidobacteria resistant strains was investigated in vitro. the results revealed that only l. plantarum ifpl935 was able to metabolize the polyphenols studied by means of galloyl-esterase, decarboxylase and benzyl alcohol dehydrogenase activities that  led to the formation of gallic acid, pyrogallol and catechol, respectively. an unknown metabolite that does not exhibit a phenolic-acid-type structure was also  detected, which suggests a new enzyme activity in l. plantarum ifpl935 able to degrade flavan-3-ol monomers.
TIHT== 
ABHT== 

PMID== 21700007
TI  == diversity of lactic acid bacteria associated with traditional fermented dairy products in mongolia.
AB  == spontaneous milk fermentation has a long history in mongolia, and beneficial microorganisms have been handed down from one generation to the next for use in fermented dairy products. the objective of this study was to investigate the diversity of lactic acid bacteria (lab) communities in fermented yak, mare, goat, and cow milk products by analyzing 189 samples collected from 13 different regions in mongolia. the lab counts in these samples varied from 3.41 to 9.03 log cfu/ml. fermented yak and mare milks had almost identical mean numbers of lab, which were significantly higher than those in fermented goat milk but slightly lower than those in fermented cow milk. in total, 668 isolates were obtained from these samples using de man, rogosa, and sharpe agar and m17 agar. each isolate was considered to be presumptive lab based on gram-positive and catalase-negative properties, and was identified at the species level by 16s rrna gene sequencing,  multiplex pcr assay, and restriction fragment length polymorphism analysis. all isolates from mongolian dairy products were accurately identified as enterococcus faecalis (1 strain), enterococcus durans (3 strains), lactobacillus brevis (3 strains), lactobacillus buchneri (2 strains), lactobacillus casei (16 strains), lactobacillus delbrueckii ssp. bulgaricus (142 strains), lactobacillus diolivorans (17 strains), lactobacillus fermentum (42 strains), lactobacillus helveticus (183 strains), lactobacillus kefiri (6 strains), lactobacillus plantarum ssp. plantarum (7 strains), lactococcus lactis ssp. lactis (7 strains), leuconostoc lactis (22 strains), leuconostoc mesenteroides (21 strains), streptococcus thermophilus (195 strains), and weissella cibaria (1 strain). the predominant lab were strep. thermophilus and lb. helveticus, which were isolated  from all sampling sites. the results demonstrate that traditional fermented dairy products from different regions of mongolia have complex compositions of lab species. such diversity of lab provides useful information for further studies of probiotic strain selection and starter culture design, with regard to the industrial production of traditional fermented milk.
TIHT== 
ABHT== 

PMID== 21377750
TI  == development of a pentaplex pcr assay for the simultaneous detection of streptococcus thermophilus, lactobacillus delbrueckii subsp. bulgaricus, l. delbrueckii subsp. lactis, l. helveticus, l. fermentum in whey starter for grana  padano cheese.
AB  == a pentaplex pcr assay for the rapid, selective and simultaneous detection of lactobacillus helveticus, l. delbrueckii subsp. lactis, l. delbrueckii subsp. bulgaricus, streptococcus thermophilus, and l. fermentum, was developed. the target sequences were a group of genes coding for beta-galactosidase production (s. thermophilus and l. delbrueckii subsp. bulgaricus), for cell-enveloped associated proteinase synthesis (l. helveticus), for dipeptide transport system production (l. delbrueckii subsp. lactis) and for arginine-ornithine antiporter protein production (l. fermentum). the analytical specificity of the assay was evaluated with 5 reference strains and 140 lactic acid bacterial strains derived  from raw milk cheeses and belonging to the lactobacillus, streptococcus, lactococcus and enterococcus genera. the identification limit for each target strain was 10(3)cfu/ml. this new molecular assay was used to investigate the lab  population by direct extraction of dna from the 12 whey cultures for grana padano. the pentaplex pcr assay revealed a good correspondence with microbiological analyses and allowed to identify even minor lab community members which, can be out-competed in vitro by numerically more abundant microbial species.
TIHT== 
ABHT== 

PMID== 21212956
TI  == characterization and transfer of antibiotic resistance in lactic acid bacteria from fermented food products.
AB  == the study provides phenotypic and molecular analyses of the antibiotic resistance in lactic acid bacteria (lab) from fermented foods in xi'an, china. lab strains (n = 84) belonging to 16 species of lactobacillus (n = 73), and streptococcus thermophilus (n = 11) were isolated and identified by sequencing their 16s rrna gene. all strains were susceptible to ampicillin, bacitracin, and cefsulodin, and intrinsically resistant to nalidixic acid, kanamycin, and vancomycin (except l. bulgaricus, l. acidophilus, and s. thermophilus, which were susceptible to vancomycin). some strains had acquired resistance for penicillin (n = 2), erythromycin (n = 9), clindamycin (n = 5), and tetracycline (n = 14), while resistance to gentamycin, ciprofloxacin, streptomycin, and chloramphenicol was species dependent. minimum inhibitory concentrations presented in this study will help to review microbiological breakpoints for some of the species of lactobacillus. the erm(b) gene was detected from two strains of each of l. fermentum and l. vaginalis, and one strain of each of l. plantarum, l. salivarius, l. acidophilus, l. animalis, and s. thermophilus. the tet genes were  identified from 12 strains of lactobacilli from traditional foods. this is the first time, the authors identified tet(s) gene from l. brevis and l. kefiri. the  erm(b) gene from l. fermentum nwl24 and l. salivarius nwl33, and tet(m) gene from l. plantarum nwl22 and l. brevis nwl59 were successfully transferred to enterococcus faecalis 181 by filter mating. it was concluded that acquired antibiotic resistance is well dispersed in fermented food products in xi'an, china and its transferability to other genera should be monitored closely.
TIHT== 
ABHT== 

PMID== 21175746
TI  == lactic acid bacteria fermentation of human milk oligosaccharide components, human milk oligosaccharides and galactooligosaccharides.
AB  == human milk contains about 7% lactose and 1% human milk oligosaccharides (hmos) consisting of lactose with linked fucose, n-acetylglucosamine and sialic acid. in infant formula, galactooligosaccharides (goss) are added to replace hmos. this study investigated the ability of six strains of lactic acid bacteria (lab), lactobacillus acidophilus, lactobacillus plantarum, lactobacillus fermentum, lactobacillus reuteri, streptococcus thermophilus and leuconostoc mesenteroides subsp. cremoris, to digest hmo components, defined hmos, and goss. all strains grew on lactose and glucose. n-acetylglucosamine utilization varied between strains and was maximal in l. plantarum; fucose utilization was low or absent in  all strains. both hetero- and homofermentative lab utilized n-acetylglucosamine via the embden-meyerhof pathway. lactobacillus acidophilus and l. plantarum were  the most versatile in hydrolysing pnp analogues and the only strains releasing mono- and disaccharides from defined hmos. whole cells of all six lab hydrolysed  onp-galactoside and pnp-galactoside indicating beta-galactosidase activity. high  beta-galactosidase activity of l. reuteri, l. fermentum, s. thermophilus and l. mesenteroides subsp. cremoris whole cells correlated to lactose and gos hydrolysis. hydrolysis of lactose and goss by heterologously expressed beta-galactosidases confirmed that lab beta-galactosidases are involved in gos digestion. in summary, the strains of lab used were not capable of utilizing complex hmos but metabolized hmo components and goss.
TIHT== 
ABHT== 

PMID== 21033428
TI  == [isolation and identification of probiotics from yoghourt in beijing].
AB  == objective: to carry out isolation and the viable plate count of probiotics from yoghourt. to investigate the antimicrobial susceptibility of strains to penicillin, gentamicin, ampicillin, vancomycin, clindamycin and erythromycin. methods: probiotics were recovered and counted from yoghourt by plate count method. the recovered isolates were characterized by gram's stain, biochemical test, antimicrobial susceptibility test. results: mrs medium and (36 +/- 1) degrees c were the optimum condition of culture. in total, 52 probiotic isolates  were recovered from 31 yoghourt products, 12 (38.7%) products showed a lower probiotic quantity than 1 x 10(6) cfu/ml of the national stantard, and 19 (61.3%) products were higher than 1 x 10(6) cfu/ml. gram's stain showed that 37 isolates  were gram positive bacilli and 15 isolates were positive coccus. these 52 isolates were grouped into six species by biochemical method, including l. bulgaricus, s. thermophilus, l. acidophilus, l. casei, l. delbrueckii and l. fermentum. all 52 isolates were susceptible to penicillin and ampicillin, one isolate was resistant to both clindamycin and erythromycin, four isolates were resistant to vancomycin. conclusion: most of yoghourt products contained sufficient viable probiotics as required by the national standard. a small quantity of isolates were resistant to some antimicrobials and multi -drug resistant isolates were also found.
TIHT== 
ABHT== 

PMID== 20726237
TI  == [identification of lactobacillus and streptococcus thermophilus by pcr amplification and sequence analysis of 16s rrna].
AB  == objective: to develop a pcr method for identifying the 16s rrna of lactobacillus  and streptococcus thermophilus at the species level. methods: optimizing the method for dna extraction and the conditions for pcr amplification. joining the pcr amplification products from 16s rrna to plasmid puc18-t and detecting the sequence. results: all 50 isolates recovered from yoghourt products were characterized by 16s rrna sequence analysis and 7 groups were identified as l. bulgaricus (24 strains), s. thermophilus (12 strains), l. acidophilus (7 strains), l. casei (3 strains), l. delbrueckii (2 strains), l. fermentum (1 strain) and s. lutetiensis (1 strain). conclusion: 16s rrna pcr method developed  in this research is a sensitive and reliable method for the identification of both lactobacillus and streptococcus thermophilus.
TIHT== 
ABHT== 

PMID== 20412906
TI  == identification of the bacterial biodiversity in koumiss by denaturing gradient gel electrophoresis and species-specific polymerase chain reaction.
AB  == bacterial biodiversity in traditional koumiss fermented milk was studied by denaturing gradient gel electrophoresis (dgge). target dna bands were identified  according to the reference species ladder, constructed in this study. comigrating bands present in the dgge profiles were resolved by species-specific pcr. the results revealed a novel bacterial profile and extensive bacterial biodiversity in koumiss. the dominant lactic acid bacteria included lactobacillus acidophilus, lactobacillus helveticus, lactobacillus fermentum, and lactobacillus kefiranofaciens. frequently encountered bacterial species were enterococcus faecalis, lactococcus lactis, lactobacillus paracasei, lactobacillus kitasatonis, and lactobacillus kefiri. leuconostoc mesenteroides, streptococcus thermophilus,  lactobacillus buchneri, and lactobacillus jensenii were occasionally found in this product. in addition, l. buchneri, l. jensenii, and l. kitasatonis, which were never previously isolated by culture-dependent methods, were identified for  the first time in the xinjiang koumiss. furthermore, conventional cultivation was performed by plating samples on m17, de man-rogosa-sharpe, halligan-pearce, and kenner fecal media. the results revealed that lactobacilli were the dominant species in the koumiss ecosystem, which was consistent with the results obtained  by the dgge analysis. this is the first systematic study of the microbial composition in koumiss, and our findings will be helpful in selecting appropriate strains for the manufacture of this product at the industrial level.
TIHT== 
ABHT== 

PMID== 20173067
TI  == characterization of a novel lysm domain from lactobacillus fermentum bacteriophage endolysin and its use as an anchor to display heterologous proteins on the surfaces of lactic acid bacteria.
AB  == the endolysin lyb5, from lactobacillus fermentum temperate bacteriophage phipyb5, showed a broad lytic spectrum against gram-positive as well as gram-negative bacteria. sequence analysis revealed that the c terminus of the endolysin lyb5 (ly5c) contained three putative lysin motif (lysm) repeat regions, implying that  ly5c was involved in bacterial cell wall binding. to investigate the potential of ly5c for surface display, green fluorescent protein (gfp) was fused to ly5c at its n or c terminus and the resulting fusion proteins were expressed in escherichia coli. after being mixed with various cells in vitro, gfp was successfully displayed on the surfaces of lactococcus lactis, lactobacillus casei, lb. brevis, lb. plantarum, lb. fermentum, lb. delbrueckii, lb. helveticus, and streptococcus thermophilus cells. increases in the fluorescence intensities of chemically pretreated l. lactis and lb. casei cells compared to those of nonpretreated cells suggested that the peptidoglycan was the binding ligand for ly5c. moreover, the ph and concentration of sodium chloride were optimized to enhance the binding capacity of gfp-ly5c, and high-intensity fluorescence of cells was observed under optimal conditions. all results suggested that ly5c was  a novel anchor for constructing a surface display system for lactic acid bacteria (lab). to demonstrate the applicability of the ly5c-mediated surface display system, beta-galactosidase (beta-gal) from paenibacillus sp. strain k1, replacing gfp, was functionally displayed on the surfaces of lab cells via ly5c. the success in surface display of gfp and beta-gal opened up the feasibility of employing the cell wall anchor of bacteriophage endolysin for surface display in  lab.
TIHT== 
ABHT== 

PMID== 19810037
TI  == genotypic characterization of non starter lactic acid bacteria involved in the ripening of artisanal bitto pdo cheese.
AB  == bitto of valchiavenna, an artisanal italian cheese produced without the addition  of any starter cultures, has been attributed a protected designation origin (pdo) cheese, but the strain composition of the natural microbial population colonizing this traditional dairy product is still unknown. to obtain preliminary information on the non starter lactic acid bacteria involved in its ripening, a total of 136 nslab isolates, randomly selected from mrs and m17 agar plates, were collected from three different cheese samples after 120 days of ripening. the new isolates were identified by combining pcr 16s-23s rdna spacer analyses, partial 16s rrna gene sequencing, species-specific probes and colony hybridization. eighty-two isolates, representing 60% of the total strains selected, were homofermentative cocci: 83% of them were enterococci, with enterococcus durans being the predominant species found. pediococcus spp. were also isolated, together with strains of streptococcus thermophilus. within lactobacilli, 57% of  the isolates were identified as lactobacillus paracasei; lact. curvatus, lact. plantarum, lact. fermentum, were present in a lower amount. the isolates were differentiated at strain-level by rep-pcr analysis. this is the first effort to microbiological characterization of valchiavenna's bitto; the results suggest the possibility of preserving the wild bacterial population in order to protect the typical organoleptic characteristics of this traditional raw milk cheese and to select new strains for the dairy industry.
TIHT== 
ABHT== 

PMID== 19703719
TI  == identification of lactic acid bacteria isolated from tarhana, a traditional turkish fermented food.
AB  == tarhana is a traditional fermented product produced from a mixture of spontaneously fermented yogurt and wheat flour in turkey. the aims of the present study were to enumerate and identify for the first time by molecular biology-based methods predominant lactic acid bacteria (lab) isolated during processing of tarhana. samples were collected from eight different regions of turkey. in order to explore the relationship between raw material and the microbiology of tarhana, yogurt and wheat flour were also analyzed. a total of 226 gram-positive and catalase-negative isolates were obtained from mrs, m17 and  sbm (slanetz and bartley medium). the isolates were grouped and identified using  a combination of pheno- and genotypic methods including rep-pcr fingerprinting [(gtg)(5) primer], multiplex pcr, 16s rrna gene sequencing and carbohydrate assimilation profiling. pediococcus acidilactici were found to constitute 27% of  the isolates, 19% were identified as streptococcus thermophilus, 19% as lactobacillus fermentum, 12% as enterococcus faecium, 7% as pediococcus pentosaceus, 5% as leuconostoc pseudomesenteroides, 4% as weissella cibaria, 2% as lactobacillus plantarum, 2% as lactobacillus delbrueckii spp. bulgaricus, 2% as leuconostoc citreum, 1% as lactobacillus paraplantarum and 0.5% as lactobacillus casei. the different production sites investigated all had individual lab profiles, but with p. acidilactici and s. thermophilus being isolated from the majority of samples. the main source of p. acidilactici and s.  thermophilus was found to be the yogurt.
TIHT== 
ABHT== 

PMID== 19187995
TI  == a qualified presumption of safety approach for the safety assessment of grana padano whey starters.
AB  == a qualified presumption of safety (qps) approach was applied to dominant lactic acid bacteria (lab) associated with grana padano cheese whey starters. thirty-two strains belonging to lactobacillus helveticus, lactobacillus delbrueckii subsp. lactis, streptococcus thermophilus, and lactobacillus fermentum, and representing the overall genotypic lab diversity associated with 24 previously collected whey  starters [rossetti, l., fornasari, m.e., gatti, m., lazzi, c., neviani, e., giraffa, g., 2008. grana padano cheese whey starters: microbial composition and strain distribution. international journal of food microbiology 127, 168-171], were analyzed. all l. helveticus, l. delbrueckii subsp. lactis, and s. thermophilus isolates were susceptible to four (i.e. vancomycin, gentamicin, tetracycline, and erythromycin) of the clinically most relevant antibiotics. one  l. fermentum strain displayed phenotypic resistance to tetracycline (tet(r)), with mic of 32 microg/ml, and gentamycin (gm(r)), with mic of 32 microg/ml. pcr was applied to this strain to test the presence of genes tet(l), tet(m), tet(s),  and aac(6')-aph(2')-ia, which are involved in horizontal transfer of tet(r) and gm(r), respectively but no detectable amplification products were observed. according to qps criteria, we conclude that grana cheese whey starters do not present particular safety concerns.
TIHT== 
ABHT== 

PMID== 18620769
TI  == grana padano cheese whey starters: microbial composition and strain distribution.
AB  == the aim of this work was to evaluate the species composition and the genotypic strain heterogeneity of dominant lactic acid bacteria (lab) isolated from whey starter cultures used to manufacture grana padano cheese. twenty-four grana padano cheese whey starters collected from dairies located over a wide geographic production area in the north of italy were analyzed. total thermophilic lab streptococci and lactobacilli were quantified by agar plate counting. population  structure of the dominant and metabolically active lab species present in the starters was profiled by reverse transcriptase, length heterogeneity-pcr (rt-lh-pcr), a culture-independent technique successfully applied to study whey starter ecosystems. the dominant bacterial species were lactobacillus helveticus, lactobacillus delbrueckii subsp. lactis, streptococcus thermophilus, and lactobacillus fermentum. diversity in the species composition allowed the whey cultures to be grouped into four main typologies, the one containing l. helveticus, l. delbrueckii subsp. lactis, and s. thermophilus being the most frequent one (45% of the cultures analyzed), followed by that containing only the two lactobacilli (40%). only a minor fraction of the cultures contained l. helveticus alone (4%) or all the four lab species (11%). five hundred and twelve  strains were isolated from the 24 cultures and identified by m13-pcr fingerprinting coupled with 16s rrna gene sequencing. most of the strains were l. helveticus (190 strains; 37% of the total), l delbrueckii subsp. lactis (90 strains; 18%) and s. thermophilus (215 strains; 42%). this result was in good agreement with the qualitative whey starter composition observed by rt-lh-pcr. m13-pcr fingerprinting indicated a markedly low infra-species diversity, i.e. the same biotypes were often found in more than one culture. the distribution of the  biotypes into the different cultures was mainly dairy plant-specific rather than  correlated with the different production areas.
TIHT== 
ABHT== 

PMID== 18555549
TI  == microflora of feta cheese from four greek manufacturers.
AB  == the components of the microflora of four feta cheeses, produced by different greek manufacturers, were determined by culture dependent and independent techniques. isolates from microbiological media were first grouped by polymerase  chain reaction-denaturing gradient gel electrophoresis (pcr-dgge) and then representatives of each dgge group were sequenced for identification purposes. dna and rna, extracted directly from the cheese, were subjected to pcr-dgge. moreover, feta cheeses were subjected to fish analysis in order to identify viable bacterial populations. the microbial ecology, as represented by the lactic acid bacteria (lab) and yeast populations, was different for the four cheeses. the main lab species isolated were lactobacillus plantarum, lactobacillus brevis, lactobacillus coryniformis and lactobacillus fermentum. however, some inconsistencies were observed between the results obtained with the culture dependent and the culture independent approach. in the case of the yeasts, the results obtained by pcr-dgge compared very well with those obtained by the conventional microbiological analysis and the main species found were kluyveromyces lactis, pichia fermentans and c. zeylanoides. fish analysis highlighted viable but not culturable populations of streptococcus thermophilus and lactococcus spp. rapd-pcr performed on the l. plantarum isolates revealed a cheese specific distribution and a temperature dependent clustering.
TIHT== 
ABHT== 

PMID== 17186668
TI  == nonstarter lactobacilli isolated from soft and semihard argentinean cheeses: genetic characterization and resistance to biological barriers.
AB  == nonstarter lactic acid bacteria isolated from argentinean cheeses were identified and characterized by focusing on their resistance to biological barriers, along with other physiological features of potential interest, in the search for future probiotic organisms. lactobacilli were enumerated and isolated from semihard and  soft cheeses made with multistrain streptococcus thermophilus starters. lactobacilli counts in 1-week-old cheeses were between 10(5) and 10(7) cfu/g and  then reached 10(7) cfu/ g in all 1-month samples, while streptococci were always  above 10(9) cfu/g. a total number of 22 lactobacilli isolates were retained, identified, and characterized by in vitro tests. species identity was determined  by carbohydrate metabolism and species-specific pcr assays. genetic diversity was explored by random amplified polymorphic dna (rapd) pcr analysis. the lactobacillus strains were assigned to the species l. casei, l. plantarum, l. rhamnosus, l. curvatus, l. fermentum, and l. perolens. all the strains studied tolerated 25 ppm of lysozyme, and most of them showed resistance to 0.3% bile. after incubation in gastric solution (ph 2.0), counts decreased by several log units, ranging from 3.2 to 7.0. the strains were able to grow in the presence of  bile salts, but only three isolates were capable of deconjugation. the nonstarter lactobacilli that were assayed fermented the prebiotic substrates (especially lactulose and inulin). some strains showed high cell hydrophobicity and beta-galactosidase activity, as well as inhibitory activity against pathogenic bacteria. it was concluded that most of the lactobacilli isolated in this study demonstrated resistance to biological barriers and physiological characteristics  compatible with probiotic properties, which make them suitable for further research in in vivo studies aimed at identifying new probiotic organisms.
TIHT== 
ABHT== 

PMID== 17150273
TI  == lactobacillus fermentum br11, a potential new probiotic, alleviates symptoms of colitis induced by dextran sulfate sodium (dss) in rats.
AB  == current treatments for inflammatory bowel disease (ibd) are relatively ineffective. recently, probiotics have emerged as a potential treatment modality  for numerous gastrointestinal disorders, including ibd. few probiotics, however,  have undergone appropriate preclinical screening in vivo. the current study compared the effects of four candidate probiotics on development of dextran sulfate sodium (dss)-induced colitis in rats. sprague dawley rats were gavaged 1  ml of the potential probiotic (1 x 10(10) cfu/ml), or vehicle, twice daily for 14 days. strains tested were lactobacillus rhamnosus gg (lgg), streptococcus thermophilus th-4 (th-4), bifidobacterium lactis bb12 (bb12) and lactobacillus fermentum br11 (br11). colitis was induced from day 7 to 14 via administration of 2% dss in drinking water. disease activity index (dai) was monitored daily until  rats were killed at day 14. dai decreased in dss+bb12 and dss+br11 compared to dss+vehicle. colon length increased in dss+br11 (10%) and dss+lgg (10%) compared  to dss+vehicle. dss+bb12 and dss+br11 prevented the distal colon crypt hyperplasia evident in dss+vehicle, dss+lgg and dss+th-4. br11 was most effective at reducing colitic symptoms. bb12 had minimal effects, whilst th-4 did not prevent dss-colitis and lgg actually exacerbated some indicators of colitis. further studies into the potential benefits of l. fermentum br11 are indicated.
TIHT== 
ABHT== 

PMID== 16786633
TI  == [study of vaginal and intestinal microflora of women in the prenatal period and its correction in dysbacteriosis].
AB  == a comparative research of the structure of vaginal and intestinal microflora in norm and at kidney pathologies in women in the prenatal period was carried out. at physiologically normal course of pregnancy microbiocenosis of vagina and intestine does not contain pathogenic and conditional-pathogenic microorganisms.  lactic acid bacteria are fixed within the limits of 10(5)-10(8) cfu/1 ml in the vagina secretion and 10(7)-10(8) cfu/1 g in the intestine content. the spore microorganisms have completely disappeared in vaginal biocenosis of women with pyelonephritis after pharmacotherapy; and colibacterias has disappeared in 62% of women. quantity of lactic acid bacteria has also decreased. quantity of e. coli (10(8)- 10(9)) cfu/g, sporous microorganisms (10(3)-10(4)) cfu/g and yeast (10(4)-10(5)) cfu/g has considerably increased in the content of intestine. lactic acid bacteria in content of the vagina are presented by: lactobacillus acidophilus, l. plantarum, l. fermentum, l. vaginalis; in content of the intestine--l. plantarum and l. fermentum. all the isolated strains of lactobacilli are resistant to metrogyl and amphotericin, 87%--to cephoxitine, cypropfloxacine. twenty three of 24 strains of lactic acid bacteria--antagonists  of pathogenic microflora have shown adhesion to vaginal epthelium. the degree of  adhesive activity depends on the strain and genus specificity of cultures. the highest index of adhesiveness in indicated in enterococcus faecium (5.82 - 7.62)  and streptococcus salivarius subsp. thermophilus (2.74 - 6.40) strains. the screening of strains has been performed, which suppress growth of gas-producing microflora. the strain of lactobacillus plantarum 200d proved to be the most active one. a complex of cultures of the lactic bacteria providing normalization  of microbial cenosis of the vagina in women in the prenatal period has been selected as based on the data obtained. the biotechnology of production of vaginal suppositories is developed.
TIHT== 
ABHT== 

PMID== 16213050
TI  == effects of yeasts and bacteria on the levels of folates in rye sourdoughs.
AB  == fermentation of rye dough is often accompanied with an increase in folate content. in this study, three sourdough yeasts, candida milleri cbs 8195, saccharomyces cerevisiae ts 146, and torulaspora delbrueckii ts 207; a control, baker's yeast s. cerevisiae alko 743; and four lactobacillus spp., l. acidophilus tsb 262, l. brevis tsb 307, l. plantarum tsb 304, and l. sanfranciscensis tsb 299 originally isolated from rye sourdough were examined for their abilities to produce or consume folates. the microorganisms were grown in yeast extract-peptone-d-glucose medium as well as in small-scale fermentations that modelled the sourdough fermentation step used in rye baking. total folate contents were determined using lactobacillus rhamnosus (atcc 7469) as the growth  indicator organism. the microorganisms studied did not excrete folates into the media in significant amounts. yeasts increased the folate contents of sterilised  rye flour-water mixtures from 6.5 microg/100 g to between 15 and 23 microg/100 g  after 19-h fermentation, whereas lactic acid bacteria decreased it to between 2.9 and 4.2 microg/100 g. strains of lactobacillus bulgaricus, l. casei, l. curvatus, l. fermentum, l. helveticus, pediococcus spp., and streptococcus thermophilus that were also tested gave folate contents after fermentation that varied between 2 and 10.4 microg/100 g. although the four lactobacillus spp. from sourdough consumed folates their effect on folate contents in co-cultivations was minimal.  it was concluded that the increase of folate content during fermentation was mainly due to folate synthesis by yeasts. fermentation of non-sterilised flour-water mixtures as such resulted in three-fold increases in the folate contents. two folate producing bacteria were isolated from the non-sterilised flour and identified as enterobacter cowanii and pantoea agglomerans.
TIHT== 
ABHT== 

PMID== 15893395
TI  == rapid identification of dairy lactic acid bacteria by m13-generated, rapd-pcr fingerprint databases.
AB  == about a thousand lactic acid bacteria (lab) isolated from dairy products, especially cheeses, were identified and typed by species-specific pcr and rapd-pcr, respectively. rapd-pcr profiles, which were obtained by using the m13 sequence as a primer, allowed us to implement a large database of different fingerprints, which were analysed by bionumerics software. cluster analysis of the combined rapd-pcr fingerprinting profiles enabled us to implement a library,  which is a collection of library units, which in turn is a selection of representative database entries. a library unit, in this case, can be considered  to be a definable taxon. the strains belonged to 11 main rapd-pcr fingerprinting  library units identified as lactobacillus casei/paracasei, lactobacillus plantarum, lactobacillus rhamnosus, lactobacillus helveticus, lactobacillus delbrueckii, lactobacillus fermentum, lactobacillus brevis, enterococcus faecium, enterococcus faecalis, streptococcus thermophilus and lactococcus lactis. the possibility to routinely identify newly typed, bacterial isolates by consulting the library of the software was valued. the proposed method could be suggested to refine previous strain identifications, eliminate redundancy and dispose of a technologically useful lab strain collection. the same approach could also be applied to identify lab strains isolated from other food ecosystems.
TIHT== 
ABHT== 

PMID== 15109791
TI  == indigenous raw milk microbiota influences the bacterial development in traditional cheese from an alpine natural park.
AB  == nostrano di primiero is a 6-month ripened cheese produced from raw milk collected in the paneveggio-pale di san martino natural park area in the italian dolomites. in summer, this cheese is made using milk collected from two different areas, passo rolle and vanoi, in the paneveggio natural park. during the experiment, the milk from the two areas was separately processed, and cheeses were made in the same cheese factory using the same technological process. the microbiota of raw milk and cheeses of the two areas was isolated and the dominant population was monitored by rapd analysis and identified by 16s rrna sequence. the milk of the passo rolle area was mainly composed of mesophilic strains, thermophilic streptococcus thermophilus, and low amounts of enterococci were also found; the milk of the vanoi area was dominated by mesophilic microbiota mostly lactococcus  lactis ssp. cremoris and ssp. lactis and lactobacillus paracasei ssp. paracasei.  the plating of the natural starter culture revealed the presence of a relevant community of thermophilic cocci and lower amounts of enterococci. the dynamic population analysis showed the importance of the natural starter culture in the first 2 days of cheese ripening in both cheeses. moreover, the large biodiversity observed in the raw milks was also detected in the cheeses during ripening. the vanoi cheese was dominated by enterococcus faecium and streptococcus macedonicus  in the first two days and mesophilic 21 lb. paracasei ssp. paracasei became the most represented population after 15 days of ripening. in the first few days, the rolle cheese was characterized by being mainly composed of thermophilic s. macedonicus and s. thermophilus and secondarily by mesophilic cocci. during ripening, the microbiota composition changed, and at 15 days, mesophilic lactobacilli were the dominant population, but later, this was mainly composed of mesophilic cocci and lactobacilli. the taxonomical identification by 16s rrna sequence confirmed a large biodiversity related to raw milk microbiota and only five strains of s. macedonicus, lactobacillus plantarum, 21 lb. paracasei ssp. paracasei, lactobacillus fermentum and e. faecium were detected in both cheeses.
TIHT== 
ABHT== 

PMID== 14962128
TI  == evaluation of bacterial communities belonging to natural whey starters for grana  padano cheese by length heterogeneity-pcr.
AB  == aims: to detect bacteria present in controlled dairy ecosystems with defined composition by length-heterogeneity (lh)-pcr. lh-pcr allows to distinguish different organisms on the basis of natural variations in the length of 16s rrna  gene sequences. methods and results: lh-pcr was applied to depict population structure of the lactic acid bacteria (lab) species recoverable from grana padano cheese whey starters. typical bacterial species present in the lab community were evidenced and well discriminated. small differences in species composition, e.g.  the frequent finding of streptococcus thermophilus and the constant presence of thermophilic lactobacilli (lactobacillus helveticus, lact. delbrueckii subsp. lactis/bulgaricus and lact. fermentum) were reliably highlighted. specificity of  lh-pcr was confirmed by species-specific pcr from total dna of the cultures. conclusions: lh-pcr is a useful tool to monitor microbial composition and population dynamics in dairy starter cultures. when present, non-dominant bacterial species present in the whey starters, such as strep. thermophilus, can  easily be visualized and characterized without isolating and cultivating single strains. a similar approach can be applied to more complex dairy ecosystems such  as milk or cheese curd. significance and impact of the study: community members and differences in population structure of controlled dairy ecosystems such as whey starters for hard cheeses can be evaluated and compared in a relative easy,  fast, reliable and highly reproducible way.
TIHT== 
ABHT== 

PMID== 12494920
TI  == isolation, characterisation and identification of lactic acid bacteria from bushera: a ugandan traditional fermented beverage.
AB  == one hundred and thirteen strains of lactic acid bacteria (lab) were selected from 351 isolates from 15 samples of traditionally fermented household bushera from uganda and also from laboratory-prepared bushera. isolates were phenotypically characterised by their ability to ferment 49 carbohydrates using api 50 chl kits  and additional biochemical tests. coliforms, yeasts and lab were enumerated in bushera. the ph, volatile organic compounds and organic acids were also determined. the lab counts in household bushera varied between 7.1 and 9.4 log cfu ml(-1). the coliform counts varied between < 1 and 5.2 log cfu ml(-1). the ph of bushera ranged from 3.7 to 4.5. ethanol (max, 0.27%) was the major volatile organic compound while lactic acid (max, 0.52%) was identified as the dominant organic acid in household bushera. the initial numbers of lab and coliforms in laboratory-fermented bushera were similar; however, the lab numbers increased faster during the first 24 h. lab counts increased from 5.5 to 9.0 log cfu ml(-1) during the laboratory fermentation. coliform counts increased from 5.9 to 7.8 log cfu ml(-1) at 24 h, but after 48 h, counts were less 4 log cfu ml(-1). yeasts increased from 4.3 to 7.7 log cfu ml(-1) at 48 h, but thereafter decreased slightly. the ph declined from 7.0 to around 4.0. lactic acid and ethanol increased from zero to 0.75% and 0.20%, respectively. lactic acid bacteria isolated from household bushera belonged to lactobacillus, streptococcus and enterococcus genera. tentatively, lactobacillus isolates were identified as lactobacillus plantarum, l. paracasei subsp. paracasei, l. fermentum, l. brevis and l. delbrueckii subsp. delbrueckii. streptococcus thermophilus strains were also identified in household bushera. lab isolated from bushera produced in the laboratory belonged to five genera (lactococcus, leuconostoc, lactobacillus, weissella and enterococcus. eight isolates were able to produce acid from starch  and were identified as lactococcus lactis subsp. lactis (four strains), leuconostoc mesenteroides subsp. mesenteroides (one strain), leuconostoc mesenteroides subsp. dextranicum (one strain), weissella confusa (one strain) and l. plantarum (one strain).
TIHT== 
ABHT== 

PMID== 11916708
TI  == diversity, dynamics, and activity of bacterial communities during production of an artisanal sicilian cheese as evaluated by 16s rrna analysis.
AB  == the diversity and dynamics of the microbial communities during the manufacturing  of ragusano cheese, an artisanal cheese produced in sicily (italy), were investigated by a combination of classical and culture-independent approaches. the latter included pcr, reverse transcriptase-pcr (rt-pcr), and denaturing gradient gel electrophoresis (dgge) of 16s rrna genes (rdna). bacterial and lactobacillus group-specific primers were used to amplify the v6 to v8 and v1 to  v3 regions of the 16s rrna gene, respectively. dgge profiles from samples taken during cheese production indicated dramatic shifts in the microbial community structure. cloning and sequencing of rdna amplicons revealed that mesophilic lactic acid bacteria (lab), including species of leuconostoc, lactococcus lactis, and macrococcus caseolyticus were dominant in the raw milk, while streptococcus thermophilus prevailed during lactic fermentation. other thermophilic lab, especially lactobacillus delbrueckii and lactobacillus fermentum, also flourished during ripening. comparison of the rrna-derived patterns obtained by rt-pcr to the rdna dgge patterns indicated a substantially different degree of metabolic activity for the microbial groups detected. identification of cultivated lab isolates by phenotypic characterization and 16s rdna analysis indicated a variety of species, reflecting to a large extent the results obtained from the 16s rdna clone libraries, with the significant exception of the lactobacillus delbrueckii  species, which dominated in the ripening cheese but was not detected by cultivation. the present molecular approaches combined with culture can effectively describe the complex ecosystem of natural fermented dairy products, giving useful information for starter culture design and preservation of artisanal fermented food technology.
TIHT== 
ABHT== 

PMID== 11876368
TI  == the potential of a polyphasic pcr-dgge approach in evaluating microbial diversity of natural whey cultures for water-buffalo mozzarella cheese production: bias of  culture-dependent and culture-independent analyses.
AB  == a polyphasic pcr-dgge approach was used to describe the microbial population occurring in natural whey cultures (nwcs) for water-buffalo mozzarella cheese production. total microbial community was assessed without cultivation by analyzing dna directly extracted from the original samples of nwc. in addition, dna extracted from bulks of cells formed by harvesting colonies from the serial dilution agar plates of a variety of culture media was used to profile the "cultivable" community. the 16s rdna v3 region was amplified using dna from nwc as well as dna from bulks as templates and the amplicons were separated by dgge.  the microbial entities occurring in nwcs were identified by partial 16s rdna sequencing of dgge bands: four lactic acid bacteria (lab) closest relative of streptococcus thermophilus, lactococcus lactis, lactobacillus delbrueckii and lactobacillus crispatus were revealed by the analysis of dna directly extracted from nwc while two other lab, lactobacillus fermentum and enterococcus faecalis,  were identified by analyzing dna from the cultivable community. the developed pcr-dgge analysis of the "cultivable" community showed good potential in evaluating microbial diversity of a dairy environment: it usefully highlighted the bias introduced by selective amplification when compared to the analysis of the total community from nwc and allowed suitability of media and growth conditions to be evaluated. moreover, it could be used to complete the culture independent study of microbial diversity to give information on concentration ratios among species occurring in a particular environment and can be proposed for rapid identification of dominant microorganisms in alternative to traditional tools.
TIHT== 
ABHT== 

PMID== 11772639
TI  == evolution of the lactic acid bacterial community during malt whisky fermentation: a polyphasic study.
AB  == the development of the lactic acid bacterial community in a commercial malt whisky fermentation occurred in three broad phases. initially, bacteria were inhibited by strong yeast growth. fluorescence microscopy and environmental scanning electron microscopy revealed, in this early stage, both cocci and rods that were at least partly derived from the wort and yeast but also stemmed from the distillery plant. denaturing gradient gel electrophoresis (dgge) of partial 16s rrna genes and sequence analysis revealed cocci related to streptococcus thermophilus or saccharococcus thermophilus, lactobacillus brevis, and lactobacillus fermentum. the middle phase began 35 to 40 h after yeast inoculation and was characterized by exponential growth of lactobacilli and residual yeast metabolism. lactobacillus casei or lactobacillus paracasei, l. fermentum, and lactobacillus ferintoshensis were detected in samples of fermenting wort examined by dgge during this stage. bacterial growth was accompanied by the accumulation of acetic and lactic acids and the metabolism of  residual maltooligosaccharides. by 70 h, two new pcr bands were detected on dgge  gels, and the associated bacteria were largely responsible for the final phase of the fermentation. the bacteria were phylogenetically related to lactobacillus acidophilus and lactobacillus delbrueckii, and strains similar to the former had  previously been recovered from malt whisky fermentations in japan. these were probably obligately homofermentative bacteria, required malt wort for growth, and could not be cultured on normal laboratory media, such as mrs. their metabolism during the last 20 to 30 h of fermentation was associated with yeast death and autolysis and further accumulation of lactate but no additional acetate.
TIHT== 
ABHT== 

PMID== 10933256
TI  == effect of probiotic bacteria on prevalence of yeasts in oropharyngeal biofilms on silicone rubber voice prostheses in vitro.
AB  == the proliferation of yeasts in the mixed bacterial and fungal biofilms colonising silicone rubber voice prostheses in laryngectomised patients is the main cause of malfunctioning of the valve mechanism on the oesophageal side of the prostheses.  indwelling voice prostheses usually have to be replaced every 3-4 months. the consumption of probiotic bacteria is largely motivated by health claims related to the urogenital and lower digestive tract, but not to the upper digestive tract. the present study examined the influence of probiotic bacteria on the prevalence of yeasts in oropharyngeal biofilms on silicone rubber voice prostheses, as formed in a modified robbins device. exposure of oropharyngeal biofilms on voice prostheses to suspensions of bifidobacterium infantis 420 or enterococcus faecium 603 did not significantly reduce the number of yeasts in the biofilm. however, suspensions of lactobacillus fermentum b54, l. rhamnosus 744 or l. lactis cremoris sk11 led to a reduction in the number of yeasts harvested from the voice prostheses. suspensions of l. casei shirota and streptococcus thermophilus b significantly reduced the number of yeasts in the biofilm to 39% and 33%, respectively. the reduction brought about in yeast prevalence in the mixed biofilm was greatest by exposure to a suspension of l. lactis 53, with yeast prevalence only 4% of the control. in conclusion, the study demonstrated that the prevalence of yeasts in oropharyngeal biofilms on silicone rubber voice  prostheses might be controlled by consumption of probiotic bacteria.
TIHT== 
ABHT== 

PMID== 10651931
TI  == modulating immune responses with probiotic bacteria.
AB  == for many years, probiotic bacteria have been known to confer health benefits to the consumer. one possible mechanism for this may be the ability of probiotic bacteria to modulate immune responses. oral administration of lactobacillus casei strain shirota (lcs) has been found to enhance innate immunity by stimulating the activity of splenic nk cells. oral feeding with killed lcs was able to stimulate  the production of th1 cytokines, resulting in repressed production of ige antibodies against ovalbumin in experimental mice. the ability to switch mucosal  immune responses towards th1 with probiotic bacteria provides a strategy for treatment of allergic disorders. growth of meth a tumour cells in the lungs was also inhibited by intrapleural injection of lcs. oral administration of other probiotic bacteria, such as streptococcus thermophilus (st), lactobacillus fermentum (lf) and yeast (y), elicited different immune responses. mice that were prefed yeast or lf followed by feeding with ovalbumin (ova) responded better to vaccination with ova than mice not given either probiotic or ova or mice that had been prefed only ova. however, antibody responses were significantly suppressed in response to vaccination with ova in mice that had been prefed yeast followed by yeast and ova as well as mice prefed lf followed by lf and ova. prefeeding st  followed by ova feeding enhanced cellular immune responses against ovalbumin. in  contrast, mice prefed st followed by st + ova were hyporesponsive against ova. while antigen feeding alone appears to prime for an immune response, cofeeding antigen with probiotic bacteria can suppress both antibody and cellular immune responses and may provide an efficacious protocol to attenuate autoimmune diseases, such as experimental allergic encephalomyelitis, by jointly dosing with myelin basic protein and probiotic bacteria.
TIHT== 
ABHT== 

PMID== 10419278
TI  == starter culture activity in refrigerated fermented soymilk.
AB  == the refrigerated shelf life of soymilk fermented with single cultures of lactobacillus fermentum, l. casei, streptococcus salivarius subsp. thermophilus,  and bifidobacterium longum was evaluated. during storage at 4 degrees c for 28 days, the stability of the microflora differed markedly among the starter cultures. after 28 days, the average numbers of s. salivarius subsp. thermophilus decreased by two log cycles to 6.0 x 10(7) cfu/ml, whereas those of l. casei increased gradually by more than two log cycles to 4.6 x 10(9) cfu/ml. numbers of b. longum and l. fermentum remained moderately high (8.7 x 10(8) cfu/ml and 3.7 x 10(8) cfu/ml, respectively) even after 28 days of storage. s. salivarius subsp. thermophilus and l. casei continued to metabolize sucrose during the storage period, but the pattern of consumption was different among the strains. the other starter cultures did not seem to have significant activity (p > 0.05) on the residual sugars. in most cases, l(+)-lactate predominated.
TIHT== 
ABHT== 

PMID== 9721662
TI  == preliminary characterization of microflora of comte cheese.
AB  == the evolution of the microflora of three comte cheeses made in duplicate with raw milk from three different sources was followed during ripening. the same starter  was used with each type of milk. the comparison of the cheeses did not reveal any significant difference in the development of the microflora. starter lactic acid  bacteria (streptococcus thermophilus and lactobacillus helveticus), which are added at the beginning of manufacture, decreased quickly in the first stages of ripening supporting the hypothesis of cell autolysis. other microorganisms, i.e.  homofermentative and heterofermentative lactobacilli (lact. delbrueckii ssp. lactis, lact. paracasei ssp. paracasei, lact. rhamnosus and lact. fermentum), pediococci, enterococci and propionibacteria grew in cheese from small numbers in fresh curd. the characterization of strep. thermophilus by pulsed-field gel electrophoresis showed that wild strains were also able to grow in the curd. the  values for the genome size of 11 strep. thermophilus strains determined in this investigation were in the range of 1.8-2.3 mbp. the potential role of starter and raw milk microflora in cheese flavour development was considered.
TIHT== 
ABHT== 

PMID== 9139932
TI  == cell wall anchoring of the streptococcus pyogenes m6 protein in various lactic acid bacteria.
AB  == the m6 protein from streptococcus pyogenes is the best-characterized member of a  family of cell envelope-associated proteins. based on the observation that the c-terminal sorting signals of these proteins can drive cell wall anchoring of heterologous unanchored proteins, we have cloned and expressed the emm6 structural gene for the m6 protein in various lactic acid bacteria (lab). the emm6 gene was successfully expressed from lactococcal promoters in several lactococcus lactis strains, an animal-colonizing lactobacillus fermentum strain,  lactobacillus sake, and streptococcus salivarius subsp. thermophilus. the m6 protein was efficiently anchored to the cell wall in all strains tested. in lactobacilli, essentially all detectable m6 protein was cell wall associated. these results suggest the feasibility of using the c-terminal anchor moiety of m6 for protein surface display in lab.
TIHT== 
ABHT== 

PMID== 16345572
TI  == culture of five commonly used acid-producing bacteria on banana pulp.
AB  == a significant fraction of the bananas and plantains produced in the humid tropics are wasted due to rapid spoilage. the use of acid-producing, anaerobic fermentation may be a safe and economical way to preserve the fruit in both large- and small-scale applications. the abilities of five commonly used, acid-producing bacteria to ferment media containing ripe or green bananas were examined. three homofermentative bacteria, lactobacillus bulgaricus, streptococcus thermophilus, and streptococcus faecalis, typically reduced the ph  of a puree of ripe bananas from 4.8 to about 3.5 to 3.6 in 7 days at 37 degrees c. action on green bananas was similar, but the drop in ph was less pronounced. very little gas evolved. lactobacillus fermentum (formerly lactobacillus fermenti) and leuconostoc mesenteroides showed active gas evolution and a significant drop in ph. about twice as much gas evolved from ripe banana medium as from green bananas. the fermented purees were spongy, soft solids floating in  a clear liquor. the color was medium to light creamy brown, and the odor was pleasant. fermented products stored at room temperature retained good appearance  and aroma throughout a 1-month storage test.
TIHT== 
ABHT== 

