@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 22897652
TI  == bacterial antagonism against periodontopathogens.
AB  == background: the aim of the current study is to compare the prevalence of commensal bacteria, with beneficial properties, for healthy and diseased individuals and additionally to examine the inhibitory effect of some commercial  dietary probiotics on periodontopathogens, comparing this inhibitory effect to that of orally derived beneficial bacteria. methods: subgingival plaque samples from 35 patients (healthy and periodontitis patients) were analyzed. growth inhibition of the periodontal pathogens porphyromonas gingivalis, prevotella intermedia, fusobacterium nucleatum, and aggregatibacter actinomycetemcomitans was examined using the agar overlay technique and agar well diffusion method. the quantification of the inhibitory effect was checked with the agar well diffusion  method. results: using the agar overlay technique, the prevalence of strains antagonistic toward p. gingivalis, a. actinomycetemcomitans, and f. nucleatum was found to be higher in healthy individuals than in individuals with periodontitis, but this could not be validated by the agar well diffusion assay. compared with the antagonistic activity of the isolated strains, the probiotic strains overall  showed a stronger inhibition of the periodontal pathogens. conclusion: it was shown that some oral bacteria can cause antagonism toward periodontopathogens, and these observations underline the therapeutic potential of applications that stimulate oral health by the application of beneficial effector strains.
TIHT== 
ABHT== 

PMID== 22739571
TI  == shifts in the microbial population in relation to in situ caries progression.
AB  == the shift in microbial diversity from young to mature plaque, related to caries activity on sound and restored surfaces, was studied using denaturing gradient gel electrophoresis. during a 20-week in situ study on caries progression 8 subjects wearing restored and unrestored dentin and enamel sections, biofilm was  sampled after 1 and 20 weeks (young or mature plaque). a higher microbial diversity (mature plaque) was seen in caries-active compared to caries-free subjects. rothia dentocariosa and scardovia inopinata were absent from all caries-free sites, but appeared in 50% of the caries-active sites.
TIHT== 
ABHT== 

PMID== 22414835
TI  == in vitro evaluation of mtad and nisin in combination against common pathogens associated with root canal infection.
AB  == introduction: many pathogenic microorganisms were found in an infected root canal. the object of this study was to evaluate the effect of mtad in combination with nisin on the pathogens associated with root canal infection. methods: the survival rates of 9 pathogenic bacteria were determined after 1-, 5-, and 10-minute treatment with mtad, mtan (substitution of doxycycline with nisin), and mtadn (nisin in combination with doxycycline). the survival rates of enterococcus faecalis in the starvation phase and pretreatment alkalization as well as in the  normal physiological state under mtad, mtan, and mtadn challenge for 1, 5, and 10 minutes were evaluated and compared. furthermore, scanning electron microscopy was used to observe the morphologic modification of actinomyces naeslundii, lactobacillus paracasei, and porphyromonas gingivalis after mtad and mtadn treatment. results: l. fermenti, l. paracasei, a. viscosus, a. naeslundii, streptococcus gordonii, and peptostreptococcus were more sensitive to mtadn and mtan than to mtad. mtad, mtan, and mtadn showed a rapid antibacterial effect on p. gingivalis, prevotella intermedia, and fusobacterium nucleatum. enterococcus faecalis in the stress state was as sensitive to mtad, mtan, and mtadn as the control e. faecalis. furthermore, in the observation of scanning electron microscopy, the membranes in a. naeslundii and l. paracasei presented significant rupture, and p. gingivalis did not exhibit significant damage after mtadn treatment. conclusions: mtad in combination with nisin improved antibacterial efficacy against pathogens, especially for some gram-positive bacteria associated with persistent intracanal infection. therefore, the combination had the potential to be used as an effective intracanal irrigation.
TIHT== 
ABHT== 

PMID== 21311610
TI  == the effect of xylitol on the composition of the oral flora: a pilot study.
AB  == objectives: our aim was to investigate the effect of short-term xylitol consumption on the microbial composition of plaque and saliva. methods: twelve volunteers (22-38 yrs) harboring mutans streptococci (ms) participated in the randomized, double-blind, cross-over study. the experimental chewing gum contained 65% xylitol while the control gum contained 63% sorbitol and 2% maltitol w/w. the polyol dose was approximately 6 g/day. stimulated saliva and plaque samples were collected before and after the two four-week test periods. the samples were cultured for ms, total streptococci, lactobacilli, and total facultatives. a part of the samples were subjected to dna-dna hybridizations of 14 microbial plaque species: actinomyces naeslundii, a. viscosus, fusobacterium nucleatum, lactobacillus acidophilus, l. fermentum, l. paracasei, l. rhamnose, l. plantarum, streptococcus gordonii, s. oralis, s. parasanguis, s. salivarius, s. sanguinis, veillonella parvula. results: the ms counts of the plaque samples collected from "caries-prone" tooth sites decreased significantly (p<.01) in the  xylitol gum group but not in the sorbitol gum group. also the plaque ms percentage decreased significantly in the xylitol gum group (p<.01). the salivary ms counts did not decrease either in the xylitol or in the sorbitol gum groups. nor were changes detected in the salivary levels of total streptococci or lactobacilli. the dna-dna hybridization assay revealed no study-induced changes in the microbial composition of the dental plaque. conclusions: within the limitations of this pilot study, xylitol consumption reduced ms counts in plaque  but appeared not to affect the microbial composition of plaque or saliva in general.
TIHT== 
ABHT== 

PMID== 21160186
TI  == microbiota of dentinal caries as assessed by reverse-capture checkerboard analysis.
AB  == background/aims: this study aimed to identify the microbiota of different layers  of dentinal caries by using a culture-independent molecular biology approach. methods: dna was extracted from samples taken from 3 distinct layers (superficial, middle and deep) of advanced occlusal caries and analyzed for the presence and relative levels of 28 oral bacterial species/phylotypes using a reverse-capture checkerboard hybridization assay. results: the mean number of target taxa per layer was 7.7 (+/- 3.96) in the superficial, 7 (+/- 3.4) in the middle, and 6.3 (+/- 3.04) in the deep layer. no statistical significance was observed for these differences (p = 0.36). overall, the most prevalent taxa in the 3 layers were atopobium genomospecies c1 (72.5%), fusobacterium nucleatum (69%), lactobacillus casei (68%), veillonella species (55%) and lactobacillus fermentum (52%). no differences were found in the prevalence rates of the most frequent target species in the 3 layers. the most prevalent taxa found at levels  above 10(5) in the advanced front line of deep-dentin caries were atopobium genomospecies c1, f. nucleatum, streptococcus mutans, streptococcus species and veillonella species. conclusion: the present results revealed that the prevalences of several established or candidate caries pathogens do not differ significantly in the different zones of dentinal caries lesions. the finding that some as-yet-uncharacterized species and novel species were found in high frequencies join other molecular studies to include them in the set of candidate  caries pathogens.
TIHT== 
ABHT== 

