@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23391223
TI  == lactic acid bacteria and bifidobacteria attenuate the proinflammatory response in intestinal epithelial cells induced by salmonella enterica serovar typhimurium.
AB  == inflammation is a physiological response to infections and tissue injury; however, abnormal immune responses can give rise to chronic inflammation and contribute to disease progression. various dietary components, including probiotic lactic acid bacteria and prebiotics, have the potential to modulate intestinal inflammatory responses. one factor in particular, the chemokine interleukin-8 (il-8, cxcl-8), is one of the major mediators of the inflammatory response. the purpose of this study was to investigate modulation of the inflammatory host response induced by salmonella enterica serovar typhimurium dt104 in the presence of selected probiotics and lactic acid bacteria (lab) isolated from human sources, dairy products, and farm animals. il-8 gene expression and protein production in ht-29 cells were evaluated by real-time pcr  and elisa, respectively. pre-incubation of ht-29 cells with lactobacillus kefir im002, bifidobacterium adolescentis frp 61, bifidobacterium longum frp 68 and frp 69, bifidobacterium breve frp 334, and leuconostoc mesenteroides im080 significantly inhibited il-8 secretion induced by salmonella typhimurium dt104. co-culture of selected probiotics and salmonella typhimurium dt104 reduced il-8 production, while potential probiotics and lab had no effect on il-8 secretion in ht-29 cells preincubated with salmonella typhimurium dt104 prior to adding probiotics. lactobacillus kefir im002 supernatant also significantly reduced il-8 production. in conclusion, our study suggests that probiotic bifidobacteria and lab modulate cytokine induction and possess anti-inflammatory properties; however, the effectiveness is strain dependent.
TIHT== 
ABHT== 

PMID== 21798524
TI  == transglucosylation potential of six sucrose phosphorylases toward different classes of acceptors.
AB  == in this study, the transglucosylation potential of six sucrose phosphorylase (sp) enzymes has been compared using eighty putative acceptors from different structural classes. to increase the solubility of hydrophobic acceptors, the addition of various co-solvents was first evaluated. all enzymes were found to retain at least 50% of their activity in 25% dimethylsulfoxide, with the enzymes  from bifidobacterium adolescentis and streptococcus mutans being the most stable. screening of the enzymes' specificity then revealed that the vast majority of acceptors are transglucosylated very slowly by sp, at a rate that is comparable to the contaminating hydrolytic reaction. the enzyme from s. mutans displayed the narrowest acceptor specificity and the one from leuconostoc mesenteroides nrrl b1355 the broadest. however, high activity could only be detected on l-sorbose and l-arabinose, besides the native acceptors d-fructose and phosphate. improving the affinity for alternative acceptors by means of enzyme engineering will, therefore, be a major challenge for the commercial exploitation of the transglucosylation potential of sucrose phosphorylase.
TIHT== 
ABHT== 

PMID== 21204871
TI  == predominant genera of fecal microbiota in children with atopic dermatitis are not altered by intake of probiotic bacteria lactobacillus acidophilus ncfm and bifidobacterium animalis subsp. lactis bi-07.
AB  == the effect of probiotic bacteria lactobacillus acidophilus ncfm and bifidobacterium lactis bi-07 on the composition of the lactobacillus group, bifidobacterium and the total bacterial population in feces from young children with atopic dermatitis was investigated. the study included 50 children randomized to intake of one of the probiotic strain or placebo. microbial composition was characterized by denaturing gradient gel electrophoresis, quantitative pcr and, in a subset of subjects, by pyrosequencing of the 16s rrna  gene. the core population of the lactobacillus group was identified as lactobacillus gasseri, lactobacillus fermentum, lactobacillus oris, leuconostoc mesenteroides, while the bifidobacterial community included bifidobacterium adolescentis, bifidobacterium bifidum, bifidobacterium longum and bifidobacterium catenulatum. the fecal numbers of l. acidophilus and b. lactis increased significantly after intervention, indicating survival of the ingested bacteria. the levels of bifidobacterium correlated positively (p=0.03), while the levels of the lactobacillus group negatively (p=0.01) with improvement of atopic eczema evaluated by the severity scoring of atopic dermatitis index. this correlation was observed across the whole study cohort and not attributed to the probiotic intake. the main conclusion of the study is that administration of l. acidophilus ncfm and b. lactis bi-07 does not affect the composition and diversity of the main bacterial populations in feces.
TIHT== 
ABHT== 

PMID== 17919298
TI  == differences in faecal bacterial communities in coeliac and healthy children as detected by pcr and denaturing gradient gel electrophoresis.
AB  == coeliac disease (cd) is a chronic inflammatory disorder of the small intestinal mucosa. scientific evidence supports a role of the gut microbiota in chronic inflammatory disorders; yet information is not specifically available for cd. in  this study, a comparative denaturing gradient gel electrophoresis analysis of faecal samples from coeliac children and age-matched controls was carried out. the diversity of the faecal microbiota was significantly higher in coeliac children than in healthy controls. the presence of the species lactobacillus curvatus, leuconostoc mesenteroides and leuconostoc carnosum was characteristic of coeliac patients, while that of the lactobacillus casei group was characteristic of healthy controls. the bifidobacterium population showed a significantly higher species diversity in healthy children than in coeliacs. in healthy children, this population was characterized by the presence of bifidobacterium adolescentis. overall, the results highlighted the need for further characterization of the microbiota in coeliac patients, and suggested a potential role of probiotics and/or prebiotics in restoring their gut microbial balance.
TIHT== 
ABHT== 

