@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 17975509
TI  == characterization of mucosal biofilms on human adenoid tissues.
AB  == objectives: to demonstrate the presence of mucosal biofilm in adenoid tissue using double staining for visualization of both the bacterial matrix and the bacterial cells. to identify bacterial species present on the surface of the studied adenoids. study design: prospective study. methods: a total of 39 specimens of adenoidectomy were removed from children with chronic and/or recurrent otitis media. the specimens were prepared for light microscopy using gram staining, scanning electron microscopy (sem) and confocal laser scanning microscopy (clsm). double staining was performed with clsm to visualize both the  bacteria and the glycocalyx matrix. nine adenoids on which bacterial biofilms were visualized with clsm were used for identification of bacterial species by 16s-dna polymerase chain reaction (pcr) amplification and homology analysis. results: of the 39 adenoids investigated, 22 (54%) showed evidence of mucosal biofilms. gram staining, sem and clsm showed the presence of bacterial cells, organized in bacterial microcolonies. clsm with double staining demonstrated mucosal biofilms by showing the presence of both bacteria and the glycocalyx. the use of 16s-dna polymerase chain reaction (pcr) amplification and subsequent sequence analyses identified the presence of corynebacterium argentoratense, streptococcus salivarius, micrococcus luteus, and staphylococcus aureus. conclusions: this study demonstrates that adenoid tissue in children with chronic or/and recurrent otitis media contains mucosal biofilms in 54% of the cases. the  existence of living bacteria has been demonstrated. further studies are required  to describe the panel of bacteria that can be harbored in the biofilms present in adenoids and the mechanisms involved in the physiopathology of otitis prone children.
TIHT== 
ABHT== 

PMID== 16461700
TI  == production of the lantibiotic salivaricin a and its variants by oral streptococci and use of a specific induction assay to detect their presence in human saliva.
AB  == salivaricin a (sala), the first streptococcus salivarius lantibiotic to be characterized, appears to be inhibitory to most streptococcus pyogenes strains. a variant of the sala structural gene (sala1) is present in more than 90% of s. pyogenes strains, but only strains of m serotype 4 and t pattern 4 produce the biologically active peptide. the present study identifies four additional variants (sala2 to sala5) of the sala structural gene and demonstrates that each  of the corresponding inhibitory peptides (sala2 to sala5) is produced in vitro. these variants appear to be similar to sala and sala1 in their inhibitory activity against micrococcus luteus and in their ability to act as inducers of sala production. it had previously been shown that s. pyogenes strain sf370 had a deletion (of approximately 2.5 kb) in the salm and salt genes of the sala1 locus. in the present study, several additional characteristic deletions within the sala1 loci were identified. s. pyogenes strains of the same m serotype all share  the same sala1 locus structure. since s. salivarius is a predominant member of the normal oral flora of healthy humans, strains producing anti-s. pyogenes lantibiotics, such as sala, may have excellent potential for use as oral probiotics. in the present study, we have used a highly specific sala induction system to directly detect the presence of sala in the saliva of humans who either naturally harbor populations of sala-producing s. salivarius or who have been colonized with the sala2-producing probiotic s. salivarius k12.
TIHT== 
ABHT== 

PMID== 16332887
TI  == cell adsorption and selective desorption for separation of microbial cells by using chitosan-immobilized silica.
AB  == cell adsorption and selective desorption for separation of microbial cells were conducted by using chitosan-immobilized silica (cis). when chitosan was immobilized onto silica surfaces with glutaraldehyde, bacterial cells adsorbed well and retained viability. testing of the adsorption and desorption ability of  cis using various microbes such as escherichia coli, aeromonas hydrophila, pseudomonas aeruginosa, bacillus subtilis, micrococcus luteus, staphylococcus aureus, staphylococcus epidermidis, lactobacillus casei, streptococcus mutans, streptococcus sobrinus, streptococcus salivarius, saccharomyces cerevisiae, saccharomyces ludwigii, and schizosaccharomyces pombe revealed that most microbes could be adsorbed and selectively desorbed under different conditions. in particular, recovery was improved when l-cysteine was added. a mixture of two bacterial strains adsorbed onto cis could also be successfully separated by use of specific solutions for each strain. most of the desorbed cells were alive. thus, quantitative and selective fractionation of cells is readily achievable by  employing chitosan, a known antibacterial material.
TIHT== 
ABHT== 

PMID== 2434147
TI  == [the capacity of anaerobically grown bacteria to exchange the 2h+ of the cell for the k+ of the medium and to maintain a high k+ distribution between cell and medium].
AB  == the n,n'-dicyclohexylcarbodiimide sensitive exchange of 2h+ of a cell for k+ of medium stable to ph, k+ activity and temperature changes has been discovered in anaerobically grown gram-negative escherichia coli, salmonella typhimurium. s. enteritidis, proteus mirabilis, p. vulgaris, anaerobic gram-positive bacteria streptococcus faecalis, lactobacillus salivarius, l. lactis in the presence of exogenic energy source. this exchange in gram-negative bacteria is operating only at increase of medium osmolarity. the high k+ distribution between cell and medium has been reached during the exchange of 2h+ for one k+ and the corresponding potassium equilibrium potential is much more than the measured delta psi. in aerobically grown e. coli, s. typhimurium, brevibacterium flavum and aerobic micrococcus luteus exchange of 2h+ for k+ does not take place, the k+ distribution is lower and in good conformity with the measured delta psi. it is assumed that exchange of 2h+ for k+ in anaerobic bacteria is carried out by the h+-atpase complex and the trk (or trk-like) system of k+ absorption united into the same membrane supercomplex which functions as the h+-k+-pump and supports the high k+ distribution between cell and medium.
TIHT== 
ABHT== 

