@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25838136
TI  == natural antimicrobials subtilosin and lauramide arginine ethyl ester synergize with conventional antibiotics clindamycin and metronidazole against biofilms of gardnerella vaginalis but not against biofilms of healthy vaginal lactobacilli.
AB  == the purpose of this study was to evaluate the ability of clindamycin and metronidazole to synergize with natural antimicrobials against biofilms of bacterial vaginosis (bv)-associated gardnerella vaginalis. minimum bactericidal concentrations for biofilm cells (mbcs-b) were determined for each antimicrobial. the mbcs-b of lauramide arginine ethyl ester (lae), subtilosin, clindamycin and metronidazole were 50, 69.5, 20 and 500 mug ml(-1), respectively. a checkerboard  assay and isobologram were used to analyze the type of interactions between these antimicrobials. the combination of metronidazole with natural antimicrobials did  not inhibit planktonic lactobacilli. clindamycin with either lae or with subtilosin was inhibitory for planktonic but not for biofilm-associated lactobacilli. all tested antimicrobial combinations were inhibitory for bv-associated mobiluncus curtisii and peptostreptococcus anaerobius. lae and subtilosin synergized with clindamycin and metronidazole against biofilms of g. vaginalis but not biofilm-associated vaginal lactobacilli. the biofilms of bv-associated pathogens can be controlled by synergistically acting combinations  of conventional antibiotics and natural antimicrobials which will help better management of current antibiotics, especially considering robust bacterial resistance. our findings create a foundation for a new strategy in the effective  control of vaginal infections.
TIHT== 
ABHT== 

PMID== 18579722
TI  == quantitative survival of aerobic and anaerobic microorganisms in port-a-cul and copan transport systems.
AB  == transport media should preserve the viability and stability of microorganisms in  clinical specimens. in this study, the port-a-cul transport system and the copan  transport system without charcoal, both designed to preserve anaerobes, were evaluated. dacron swabs were inoculated with two combinations of facultative and  anaerobic organisms typically found in vaginal swab samples. combination i contained candida albicans, escherichia coli, enterococcus spp., group b streptococci, lactobacillus crispatus, and staphylococcus aureus. combination ii  contained lactobacillus iners, peptoniphilus asaccharolyticus, mycoplasma hominis, prevotella bivia, prevotella corporis, porphyromonas asaccharolytica, mobiluncus curtisii, peptostreptococcus anaerobius, and gardnerella vaginalis. duplicate swabs were placed into the two transporters and held for 24, 48, 72, and 96 h at 4 and 24 degrees c. both transporters maintained the viability of organisms better at 4 degrees c than at 24 degrees c. prevotella bivia and prevotella corporis had a loss of viability in both transporters at both temperatures. however, at 24 degrees c, there was a significantly greater loss of viability for mycoplasma hominis, prevotella bivia, prevotella corporis, and peptoniphilus asaccharolyticus when the organisms were stored in copan transport  medium than when they were stored in port-a-cul transport medium for 96 h (p < 0.002). some organisms proliferated in the transport media, but when transporters were held at 24 degrees c for 96 h, a significantly greater increase in the concentrations of group b streptococci and candida albicans, escherichia coli, and enterococcus spp. organisms in copan medium than in port-a-cul medium was observed (p < 0.002). at room temperature, the port-a-cul system is superior to the copan system with respect to the preservation of fastidious microorganisms and the prevention of the proliferation of facultative organisms.
TIHT== 
ABHT== 

PMID== 10865430
TI  == [the range of antagonistic effects of lactobacillus bacterial strains on etiologic agents of bacterial vaginosis].
AB  == bacterial vaginosis is caused by uncontrolled sequential overgrowth of some anaerobic bacteria: gardnerella vaginalis, prevotella bivia, bacteroides spp., peptostreptococcus spp., mobiluncus sp. usually occurring in stable numbers in the bacterial flora of healthy women. on the other hand, different species of bacteria belonging to the genus lactobacillus, most frequently l. plantarum, l. rhamnosus and l. acidophilus, form a group of aerobic bacteria dominating in the  same environment. the diversity and density of their populations depend on the age and health conditions. thanks to their antagonistic and adherence properties  bacteria of the genus lactobacillus can maintain a positive balance role in this  ecosystem. the aim of this study was to assess the antagonistic properties of lactobacillus strains isolated from the vagina of healthy women against most common agents of bacterial vaginosis. it was found that nearly all of the tested  lactobacillus strains exerted distinct antagonistic activity against anaerobic bacteria: gardnerella vaginalis, prevotella bivia and peptostreptococcus anaerobius and quite a number also against gram-negative rods, while only some of them were able to inhibit gram-positive aerobic cocci as enterococcus faecalis or staphylococcus aureus.
TIHT== 
ABHT== 

PMID== 8667035
TI  == the in vitro activity of trospectomycin against anaerobic bacteria.
AB  == the authors evaluated the activity of trospectomycin, a new aminocyclitol which is characterized by good antibacterial and broad spectrum activity, in comparison with clindamycin and ampicillin on a sample of recent isolates: bacteroides fragilis (15 strains), bacteroides urealyticus (5 strains), bacteroides vulgatus  (5 strains), bacteroides spp. (15 strains), prevotella melaninogenica (6 strains), porphyromonas asaccharolytica (7 strains), mobiluncus spp. (3 strains), peptococcus niger (3 strains), peptococcus variabilis (9 strains), peptococcus spp (30 strains), peptostreptococcus anaerobius (5 strains), peptostreptococcus asaccharolyticus (3 strains), peptostreptococcus spp. (25 strains) and propionibacterium spp. (7 strains). the minimum inhibitory concentration (mic) and minimum bactericidal concentration (mbc) were determined for all strains by microtiter serial dilutions in wilkins-chalgren broth in an anaerobic chamber in  an atmosphere of 10% h2, 10% co2, 80% n2. all the drugs tested exert their activity against gram-positive and gram-negative anaerobic isolates. in particular, trospectomycin is quite active against gram-positive cocci (mic 90 =  4 - 8 mg/l), gram-negative rods (mic 90 = 8 - 16 mg/l), gram-positive rods (mic 90 = 4 mg/l) and mobiluncus spp. (mic 90 = 0.5 mg/l).
TIHT== 
ABHT== 

PMID== 8205934
TI  == in vitro antibacterial activity of fk037, a new parenteral broad-spectrum cephalosporin, against recent clinical isolates in the fields of obstetrics and gynecology.
AB  == the antibacterial activity of a new parenteral cephalosporin, fk037 was assessed  against recent aerobic and anaerobic strains isolated from patients in the fields of obstetrics and gynecology during the period between january 1992 and june 1993. the mics of fk037 for 90% of the clinical isolates tested were 0.10 microgram/ml for escherichia coli and klebsiella pneumoniae, 0.20 microgram/ml for streptococcus agalactiae, 0.39 microgram/ml for gardnerella vaginalis, 0.78 microgram/ml for staphylococcus epidermidis, peptostreptococcus anaerobius and mobiluncus spp., 1.56 micrograms/ml for peptostreptococcus magnus, 3.13 micrograms/ml for methicillin-sensitive staphylococcus aureus, 25 micrograms/ml for methicillin-resistant s. aureus (mrsa), bacteroides fragilis and prevotella disiens, 100 micrograms/ml for bacteroides thetaiotaomicron and prevotella bivia; and > 100 micrograms/ml for enterococcus faecalis. fk037 was superior in potency  to ceftazidime against all strains except e. faecalis, p. anaerobius and p. bivia. it was 4- to 16-fold more active than cefotaxime against aerobic gram-positive bacteria and p. disiens, and its activity was similar to that of cefotaxime against the other strains. fk037 had 4- to 16-fold stronger activity than flomoxef against mrsa, s. agalactiae and e. coli and a similar activity to flomoxef against the other strains except g. vaginalis and b. fragilis that were  4-fold more sensitive to flomoxef than to fk037.
TIHT== 
ABHT== 

PMID== 8324131
TI  == the normal vaginal flora, h2o2-producing lactobacilli, and bacterial vaginosis in pregnant women.
AB  == in this study of the vaginal flora of 171 pregnant women in labor at term, the flora was categorized as normal (lactobacillus predominant), intermediate, or representative of bacterial vaginosis (bv) on the basis of a vaginal smear. bv was diagnosed in 39 women (23%); the vaginal flora was classified as normal in 50% of cases and as intermediate in 27%. h2o2-producing lactobacilli were recovered from 5% of women with bv, 37% of those with an intermediate flora, and  61% of those with a normal flora. h2o2-negative lactobacilli were equally frequent (57%-65%) in all three groups. the microorganisms most frequently recovered from women with bv included gardnerella vaginalis, prevotella bivia/disiens, bacteroides ureolyticus, prevotella corporis/bacteroides levii, fusobacterium nucleatum, mobiluncus species, peptostreptococcus prevotii, peptostreptococcus tetradius, peptostreptococcus anaerobius, viridans streptococci, ureaplasma urealyticum, and mycoplasma hominis (p < .05 for each).  the presence of all but three of these organisms was inversely related to vaginal colonization by h2o2-producing lactobacilli; the exceptions were b. ureolyticus,  f. nucleatum, and p. prevotii. other microorganisms were equally frequent among women with and without bv. we conclude that specific groups of anaerobes are associated with bv in this population and that a strong association exists between species associated with bv and those inhibited by h2o2-producing lactobacilli.
TIHT== 
ABHT== 

PMID== 8517721
TI  == in vitro activity of fk037, a new parenteral cephalosporin, against anaerobic bacteria.
AB  == the activity of fk037, a new parenteral cephalosporin, was compared with those of cefpirome, ceftazidime, and flomoxef against 322 recent clinical isolates of anaerobic bacteria. a fastidious facultative anaerobe, gardnerella vaginalis, was also studied. fk037 inhibited 90% of isolates of peptostreptococcus anaerobius, peptostreptococcus asaccharolyticus, clostridium perfringens, mobiluncus spp., g. vaginalis, and porphyromonas gingivalis at < or = 0.78 micrograms/ml. the mics of fk037 for 50 and 90% of bacteroides fragilis isolates were 25 and > 200 micrograms/ml, respectively; the activity of fk037 was comparable to those of cefpirome and ceftazidime but lower than that of flomoxef. the activity of fk037  against fusobacterium nucleatum, fusobacterium varium, and bilophila wadsworthia  decreased when inoculum size was increased from 10(6) to 10(8) cfu/ml. little influence of inoculum size on the activity of fk037 was observed for other isolates tested. medium ph affected the activity of fk037 against f. varium (mics at phs 5 and 7, 3.13 and 100 micrograms/ml, respectively) and bacteroides gracilis (mics at phs 5 and 7, 12.5 and 1.56 micrograms/ml, respectively) but not against other organisms tested. fk037 was less resistant than flomoxef to hydrolysis by beta-lactamase group 2e derived from b. fragilis gai 0558 and gai 10150.
TIHT== 
ABHT== 

PMID== 1803013
TI  == normal vaginal aerobic and anaerobic bacterial flora of the rhesus macaque (macaca mulatta).
AB  == the most common bacterial species isolated from the vaginas of 37 healthy rhesus  macaques were streptococcus viridans, coagulase negative staphylococcus, mobiluncus curtisii ss. curtisii, corynebacterium renale-like organisms, peptostreptococcus anaerobius, gardnerella-like organisms, and other corynebacterium species. the vaginal flora of the rhesus macaque differs from that previously reported for five other primate species. a two-year retrospective review of clinical cases of vaginitis and metritis found escherichia coli and coagulase positive staphylococci to be the most common pathogens isolated.
TIHT== 
ABHT== 

