@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 24575808
TI  == diffusible signal factor (dsf) quorum sensing signal and structurally related molecules enhance the antimicrobial efficacy of antibiotics against some bacterial pathogens.
AB  == background: extensive use of antibiotics has fostered the emergence of superbugs  that are resistant to multidrugs, which becomes a great healthcare and public concern. previous studies showed that quorum sensing signal dsf (diffusible signal factor) not only modulates bacterial antibiotic resistance through intraspecies signaling, but also affects bacterial antibiotic tolerance through interspecies communication. these findings motivate us to exploit the possibility of using dsf and its structurally related molecules as adjuvants to influence antibiotic susceptibility of bacterial pathogens. results: in this study, we have demonstrated that dsf signal and its structurally related molecules could be used to induce bacterial antibiotic susceptibility. exogenous addition of dsf signal (cis-11-methyl-2-dodecenoic acid) and its structural analogues could significantly increase the antibiotic susceptibility of bacillus cereus, possibly through reducing drug-resistant activity, biofilm formation and bacterial fitness. the synergistic effect of dsf and its structurally related molecules with antibiotics on b. cereus is dosage-dependent. combination of dsf with gentamicin showed an obviously synergistic effect on b. cereus pathogenicity in an in vitro model. we also found that dsf could increase the antibiotic susceptibility of other bacterial species, including bacillus thuringiensis, staphylococcus aureus, mycobacterium smegmatis, neisseria subflava and pseudomonas aeruginosa. conclusion: the results indicate a promising potential of using dsf and its structurally related molecules as novel adjuvants to conventional antibiotics for treatment of infectious diseases caused by bacterial pathogens.
TIHT== 
ABHT== 

PMID== 1588587
TI  == production and characterisation of mouse monoclonal antibodies reactive with the  lipopolysaccharide core of pseudomonas aeruginosa.
AB  == monoclonal antibodies (mabs) to the core antigen region of lipopolysaccharide (lps) of pseudomonas aeruginosa were produced from mice immunised with whole cells of heat-killed rough mutants of pseudomonas aeruginosa expressing partial or complete core lps. mabs were screened in an enzyme-linked immunosorbent assay  (elisa) against three different antigen cocktails: s-form lps from three p. aeruginosa strains, r-form lps from six p. aeruginosa strains and, as a negative  control, r-form lps from salmonella typhimurium and escherichia coli. selected mabs were subsequently screened against a range of extracted lps and whole cells  from both reference strains and clinical isolates of p. aeruginosa. the antibodies were also screened in elisa against whole-cell antigens from other pseudomonas spp. as well as strains of haemophilus influenzae, neisseria subflava and staphylococcus aureus. five mabs reacting with the core component of p. aeruginosa lps were finally selected. two of these, mabs 360.7 and 304.1.4, were  particularly reactive in immunoblots against unsubstituted core lps, including that from o-antigenic serotypes of p. aeruginosa. the mabs also reacted with some of the other pseudomonas spp., but not with p. cepacia or xanthomonas (pseudomonas) maltophilia. cross-reactivity with whole cells from other bacterial species was minimal or not observed. reactivity of mabs with some staph. aureus strains was observed, and binding to the protein a component was implicated. the  reactivity of the mabs was investigated further by flow cytometry and immunogold  electronmicroscopy. the suitability of the mabs for an immunological assay for detection of p. aeruginosa in respiratory secretions from cf patients is discussed.
TIHT== 
ABHT== 

PMID== 2359905
TI  == unusual pathogens in narcotic-associated endocarditis.
AB  == we report the cases of three adults with a history of intravenous drug abuse who  developed endocarditis caused by corynebacterium xerosis, neisseria subflava, and neisseria flavescens, respectively. no cases of endocarditis caused by c. xerosis or n. flavescens and only one case caused by n. subflava have previously been reported in association with narcotic addiction. the prominent clinical features  in all patients included poor response to antibiotic therapy, persistent fever, and major embolic events. stigmata of infection with human immunodeficiency virus, as manifested by oral candidiasis, cervical lymphadenopathy, and serologic evidence, were present in two of the three patients. at our institution, where staphylococcus aureus remains the most frequent etiologic agent of narcotic-associated endocarditis, the occurrence of these three cases in a 9-month period is striking. we speculate that infection with human immunodeficiency virus may play a role in the pathogenesis of endocarditis caused by these unusual organisms.
TIHT== 
ABHT== 

PMID== 3859210
TI  == efficacy of imipenem/cilastatin in endocarditis.
AB  == imipenem, a potent new beta-lactam antibiotic, which is bactericidal against most pathogenic bacteria, and cilastatin, a dehydropeptidase inhibitor combined with imipenem to prevent the metabolism of imipenem in the kidney, were evaluated in the treatment of bacterial endocarditis. seventeen patients, including 14 who used intravenous drugs, were treated with imipenem/cilastatin in a dose of 500 mg each infused over 30 minutes every six hours. the mean duration of treatment was  29 days with a range of 21 to 56 days. causative bacteria were staphylococcus aureus in 10 patients, s. aureus plus group b streptococcus in one, viridans group streptococcus in two, neisseria subflava, eikenella corrodens, and group g  streptococcus in one patient, and staphylococcus epidermidis, hemophilus aphrophilus, and enterobacter aerogenes in one patient each. the minimal bactericidal concentration of imipenem against 16 of 18 isolates tested was 0.04  micrograms/ml, 1 microgram/ml against h. aphrophilus, and 0.4 micrograms/ml against e. aerogenes. the site of infection was the right side of the heart in 11 patients, the left side in five, and both sides in one. the mean number of days to defervescence was 9.7. all patients were cured, and none required cardiac surgery. adverse effects were few and interrupted treatment occurred in only one  patient who had acute dyspnea during an infusion on day 26 of therapy. imipenem/cilastatin appears to be a relatively safe and highly effective treatment of staphylococcal endocarditis in intravenous drug users; too few patients with endocarditis caused by other bacteria were treated to allow a firm  statement about efficacy in non-staphylococcal endocarditis.
TIHT== 
ABHT== 

PMID== 6157322
TI  == is there a specific stimulus of infectious-allergic bronchial asthma?
AB  == 1. pigmented neisseria species (neisseria perflava, flava, subflava, sicca) are constant inhabitants of patients with infectious asthma. 2. of all the diverse bronchial microflora of patients with infectious-allergic bronchial asthma, the pigmented neisseria species (neisseria perflava, flava, subflava, sicca), staphylococci (staphylococcus aureus, epidermidis), klebsiella (klebsiella pneumoniae) are active sensitizers of the human broncho-pulmonary tract. 3. neisseria strains, possessing similar antigenic determinants to human lung tissues, possess the highest allergenic activity. this raises the question of a new criterion for evaluating the allergenicity of cultures according to their antigenic characteristics. 4. in patients with infectious asthma allergy might develop to some of the structures of microbial cells, in which antigenic determinants, similar to human lung tissues are localized.
TIHT== 
ABHT== 

PMID== 824037
TI  == inhibition of growth of n. gonorrhoeae by bacterial interference.
AB  == observations made in our laboratory during the past 3 years showed that the growth of some neisseria gonorrhoeae cultures was inhibited in the presence of various bacterial contaminants of urogenital specimens. a total of 647 cultures confirmed as containing n. gonorrhoeae were examined in this study. the first part of the study was carried out on 520 n. gonorrhoeae cultures. of these 520 cultures, 110 (21.1%) showed contamination on purity plates (gc medium, antibiotic-free). when further subcultured, 96 (87.3%) of the n. gonorrhoeae strains grew in pure culture, but 14 (12.7%) failed to grow. subsequently, experiments were carried out on 127 pure n. gonorrhoeae cultures. the bacterial species that inhibited the growth of n. gonorrhoeae are listed in order of frequency: neisseria meningitidis, staphylococcus epidermidis, corynebacterium species, staphylococcus aureus, streptococcus group a, and neisseria subflava.
TIHT== 
ABHT== 

