@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 12720087
TI  == the integration site of the iga gene in commensal neisseria sp.
AB  == an iga1 protease is produced by the human pathogens neisseria gonorrhoeae and n.  meningitidis but not by related non-pathogenic, commensal, neisseria species. in  this study, the chromosomal iga locus was characterized in the n. gonorrhoeae strain ms11 and compared to corresponding loci in n. meningitidis and commensal neisseria species. in n. gonorrhoeae, the genes trpb and ksga were found immediately downstream of iga. in addition to coml and coma, a homolog of the escherichia coli yfii gene was identified upstream of iga. each gene in the iga region (yfii and coml, coma and iga, and trpb and ksga) is transcribed in the opposite direction to its neighbors. the coml/ coma and iga/ trpb pairs each have a transcriptional terminator in the correct position for joint use. these terminators contain the common gonococcal dna uptake sequence (dus). a highly conserved direct repeat of 25 bp located immediately adjacent to the iga gene in  n. gonorrhoeae was also found in n. meningitidis. in southern hybridization experiments, no homology to iga was detectable in the chromosomal dnas of the commensal species n. mucosa, n. lactamica, n. flavescens, n. cinerea, n. subflava, n. flava, n. sicca or n. elongata. when n. gonorrhoeae coml and trpb were used as probes, signals were detected on the same restriction fragment in six of the eight species. this indicated that commensal neisseria species share a possible integration site for the iga gene between coma and trpb. the region between coma and trpb was therefore amplified by pcr. the fragment obtained from  n. lactamica showed a high degree of homology to gonococcal coma and trpb, respectively, but iga was replaced by a sequence of 13 bp that shows no homology  to any known gonococcal sequence. our data suggest that iga was acquired by a common ancestor of n. gonorrhoeae and n. meningitidis rather than being distributed by horizontal gene transfer. n. lactamica, which is more closely related to n. gonorrhoeae than other commensals, may have lost iga by deletion.
TIHT== 
ABHT== 

PMID== 8000550
TI  == a numerical phenotypic taxonomic study of the genus neisseria.
AB  == a numerical phenotypic taxonomic study of 315 strains of neisseria and some allied bacteria examined for 155 phenotypic tests showed 31 groups, most of which were reasonably distinct. these fell into four major areas. areas a, b and c contained species of neisseria, whereas area d contained the organisms known as 'false neisserias' together with branhamella, moraxella and kingella species. area a contained n. gonorrhoeae (which showed two subgroups), n. meningitidis (with two subgroups, and n. cinerea closely associated), n. polysaccharea, n. elongata subsp, glycolytica and n. lactamica. area b contained mainly organisms from the human nasopharynx, and the nine groups were not very distinct: only three, n. mucosa, n. perflava and n. sicca could be recognized by the presence of type strains, and there was little relationship between taxonomic position and species epithets. area c contained several groups from animals, n. animalis, n. canis and two phenons that may be justified as new species of neisseria, one from lizards and the other from dental plaque of herbivores. area c also contained n.  elongata, n. subflava (with n. flavescens), type strain of morococcus cerebrosis  and the cdc groups m-5 (n. weaveri) and ef-4. area d contained branhamella catarrhalis, a combined group which consists of strains of the 'false neisserias' n. caviae and n. cuniculi, the 'false neisseria' n. ovis, and a group of moraxella strains. a small group representing kingella kingae is included in area d. mean test error was 1.7%.
TIHT== 
ABHT== 

PMID== 1536720
TI  == regulation of aspartate carbamoyltransferase in neisseria and branhamella species.
AB  == the regulatory characteristics of aspartate carbamoyltransferase (actase ec 2.1.3.2) from various species of neisseria and branhamella have been compared. great differences in the regulatory nature of the enzymes were observed. atp and  gtp were positive effectors in neisseria meningitidis, n. gonorrhoeae and nine other coccal "true neisseriae" species. in four "false neisseriae" species, including branhamella catarrhalis, no stimulating effect of atp or gtp was observed. the rod-shaped n. elongata behaved as the "false neisseriae" in these respects, despite its taxonomic affinity to the coccal "true neisseriae" species. except in n. meningitidis and n. lactamica, ctp had no distinct stimulatory effect. ctp had a strong inhibitory effect on actases from n. elongata and the "false neisseriae" species n. caviae and b. catarrhalis. the inhibitory effect of ctp was weak in n. cinerea, n. denitrificans, and the "false neisseriae" species  n. ovis and n. cuniculi. thus, there was no sharp reflection of taxonomy in the regulation of actase by ctp in these groups of bacteria. the apparent [s]0.5 values for aspartate and carbamoyl phosphate, displayed for five of the eighteen  species, showed great variability with [s]0.5 values for aspartate ranging from 6 to 34, and for carbamoyl phosphate from 2 to 9. treatment of the enzyme from the  main test microbe n. meningitidis strain m1 by heat or para-chloromercuribenzoate (pcmb) showed that both the catalytic and the regulatory functions decreased in parallel as in the class a enzymes found in species of pseudomonas. an estimation of the molecular weight (mr) of the actase enzyme from n. meningitidis showed it  to be about 295,000, which resembles the class b enzymes found in the enterobacteriaceae.
TIHT== 
ABHT== 

PMID== 6209399
TI  == the systematic serology of neisseria gonorrhoeae: antigens associated with pathogenesis in neisseria spp. from man.
AB  == sonicates of eight neisseria species from man were analysed in a micro-ouchterlony double-diffusion absorption assay in comparison with a gonococcal reference antiserum-antigen system. five major gonococcal precipitin zones were identified which comprised genus-, species- and type-specific components. one antigen was found in all strains of three species with pathogenic capability--n. gonorrhoeae, n. meningitidis and n. flavescens. it was not detected in n. lactamica, n. pharyngis, n. elongata, n. cinerea or n. catarrhalis.
TIHT== 
ABHT== 

PMID== 7415672
TI  == [immunologic characteristics of protein antigens of the neiseriaceae family. iii. study of delayed hypersensitivity cross reactions between different species of neisseria].
AB  == the immunological interrelations between the protein complexes of 34 strains of 12 species belonging to the family neisseriaceae were studied with the use of delayed hypersensitivity reactions in specifically sensitized guinea pigs. no statistically significant differences between the nonpathogenic species of the family neisseriaceae and the strains of n. haemolysans, n. cuniculi, n. lactamicus, n. ovis, n. elongata, n. cinerea were revealed. the preparations of branhamella catarrhalis and n. caviae gave weak cross reactions with each other,  as well as with other neisseria. the probability and intensity of delayed hypersensitivity cross reactions depended on the degree of the immunological affinity of the preparations. the immunological similarity of protein complexes in most of the representatives of the family neisseriaceae presents great possibilities for the development of sensitization to this group of microorganisms.
TIHT== 
ABHT== 

PMID== 961430
TI  == cellular monosaccharide patterns of neisseriaceae.
AB  == sixty-four strains of neisseria, moraxella, and acinetobacter were screened for cellular monosaccharides by gas-liquid chromatography and other chromatographic techniques. the four sugars ribose, glucose, glucosamine, and 2-keto-3-deoxyoctonate (kdo) were detected in all strains. heptose was detected only in "true neisseriae" (neisseria gonorrhoeae, n. meningitidis, n. sicca, n. cinerea, n. flavescens, and n. elongata) and in the tentaively named species moraxella urethralis. some marked interspecies dissimilarities within groups were revealed. thus, n. ovis and m. atlantae were characterized by the presence of mannose. intraspecies differences were also encountered. n. meningitidis strains  of serogroups b and c were distinguished from strains of serogroup a by their sialic acid content. this sugar was also detected in two out of three examined strains of m. nonliquefaciens. in acinetobacter, heterogeneity of monosaccharide  patterns was rather pronounced. the results show the applicability of gas chromatographic "monosaccharide" profiles fo whole cells or extracted carbohydrate in bacterial classification and identification, including differentiation at the subspecies level. in addition, such profiles may be useful for monitoring during purification of cellular polysaccharides.
TIHT== 
ABHT== 

