@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 22324467
TI  == impact of periodontal therapy on the subgingival microbiota of severe periodontitis: comparison between good responders and individuals with refractory periodontitis using the human oral microbe identification microarray.
AB  == background: this study compares the changes to the subgingival microbiota of individuals with "refractory" periodontitis (rp) or treatable periodontitis (good responders [gr]) before and after periodontal therapy by using the human oral microbe identification microarray (homim) analysis. methods: individuals with chronic periodontitis were classified as rp (n = 17) based on mean attachment loss (al) and/or >3 sites with al >/=2.5 mm after scaling and root planing, surgery, and systemically administered amoxicillin and metronidazole or as gr (n  = 30) based on mean attachment gain and no sites with al >/=2.5 mm after treatment. subgingival plaque samples were taken at baseline and 15 months after  treatment and analyzed for the presence of 300 species by homim analysis. significant differences in taxa before and post-therapy were sought using the wilcoxon test. results: the majority of species evaluated decreased in prevalence in both groups after treatment; however, only a small subset of organisms was significantly affected. species that increased or persisted in high frequency in  rp but were significantly reduced in gr included bacteroidetes sp., porphyromonas endodontalis, porphyromonas gingivalis, prevotella spp., tannerella forsythia, dialister spp., selenomonas spp., catonella morbi, eubacterium spp., filifactor alocis, parvimonas micra, peptostreptococcus sp. ot113, fusobacterium sp. ot203,  pseudoramibacter alactolyticus, streptococcus intermedius or streptococcus constellatus, and shuttlesworthia satelles. in contrast, capnocytophaga sputigena, cardiobacterium hominis, gemella haemolysans, haemophilus parainfluenzae, kingella oralis, lautropia mirabilis, neisseria elongata, rothia  dentocariosa, streptococcus australis, and veillonella spp. were more associated  with therapeutic success. conclusion: persistence of putative and novel periodontal pathogens, as well as low prevalence of beneficial species was associated with chronic refractory periodontitis.
TIHT== 
ABHT== 

PMID== 19266926
TI  == enhancement of biodegradation of crude petroleum-oil in contaminated water by the addition of nitrogen sources.
AB  == addition of nitrogen sources as supplementary nutrient into msm medium to enhance biodegradation by stimulating the growth four isolates, acinetobacter faecalis, staphylococcus sp., pseudomonas putida and neisseria elongata isolated from petroleum contaminated groundwater, wastewater aeration pond and biopond at the oil refinery terengganu malaysia was investigated. the organic nitrogen sources tested not only supported growth but also enhances biodegradation of 1% tapis crude oil. all four isolates showed good growth especially when peptone was employed as the organic nitrogen compared to growth in the basal medium. gas chromatography showed that more then 91, 93, 94 and 95% degradation of total hydrocarbon was observed after 5 days of incubation by isolates pseudomonas putida, neisseria elongate, acinetobacter faecalis and staphylococcus sp., respectively.
TIHT== 
ABHT== 

PMID== 18819623
TI  == growth enhancement of effective microorganisms for bioremediation of crude oil contaminated waters.
AB  == the bioremediation of polluted groundwater, wastewater aeration pond and biopond  sites was investigated using bacteria isolated from these sites located at the oil refinery terengganu malaysia. out of 62 isolates, only 16 isolates from groundwater (8) and wastewater aeration pond (3) and biopond (5) were chosen based on growth medium containing 1% (v/v) tapis crude oil. only four isolates; acinetobacter faecalis, staphylococcus sp., pseudomonas putida and neisseria elongata showed percentage biodegradation of crude oil more than 50% after 5 days using mineral salts medium (msm). the effect of physical parameters (temperature, ph and agitation) on growth by all four strains showed a maximum growth in msm medium with 1% tapis crude oil at 37 degrees c with ph 7 and agitation of 130 rpm.
TIHT== 
ABHT== 

PMID== 16455901
TI  == neisseria bacilliformis sp. nov. isolated from human infections.
AB  == most neisseria species are gram-negative cocci or diplococci; currently, n. elongata is the only species of human origin with a bacillary morphology. here, we report isolation and characterization of eight strains of another bacillary neisseria species from human infections. the organisms caused or contributed to either oral cavity-related or respiratory tract infections, and two strains were  isolated from blood cultures. the 16s rrna gene sequences of these organisms, being homogenous or nearly so (99.4 to 100% identity), matched at <96% known neisseria species and formed a distinct group within the genus. analysis of the cellular fatty acids showed broad similarity with a few neisseria species. the organisms were gram negative and measured 0.6 mum by 1.3 to 3.0 mum. they grew well on chocolate agar and on sheep blood agar but did not grow on modified thayer-martin agar. they were positive for oxidase and negative for indole production. there was no acid production from dextrose, lactose, maltose, or sucrose. the tests for catalase reaction, nitrate reduction, and tributilin varied with the strains. these results suggest that these organisms represent a novel species within the genus neisseria, for which the name neisseria bacilliformis sp. nov. is proposed. the type strain is mda2833 = atcc baa-1200(t) = ccug50858(t). distinction between n. bacilliformis and n. elongata can be made  confidently by 16s rrna gene sequencing or cellular fatty acid profiling but may  be difficult by morphology or routine biochemical tests.
TIHT== 
ABHT== 

PMID== 12720087
TI  == the integration site of the iga gene in commensal neisseria sp.
AB  == an iga1 protease is produced by the human pathogens neisseria gonorrhoeae and n.  meningitidis but not by related non-pathogenic, commensal, neisseria species. in  this study, the chromosomal iga locus was characterized in the n. gonorrhoeae strain ms11 and compared to corresponding loci in n. meningitidis and commensal neisseria species. in n. gonorrhoeae, the genes trpb and ksga were found immediately downstream of iga. in addition to coml and coma, a homolog of the escherichia coli yfii gene was identified upstream of iga. each gene in the iga region (yfii and coml, coma and iga, and trpb and ksga) is transcribed in the opposite direction to its neighbors. the coml/ coma and iga/ trpb pairs each have a transcriptional terminator in the correct position for joint use. these terminators contain the common gonococcal dna uptake sequence (dus). a highly conserved direct repeat of 25 bp located immediately adjacent to the iga gene in  n. gonorrhoeae was also found in n. meningitidis. in southern hybridization experiments, no homology to iga was detectable in the chromosomal dnas of the commensal species n. mucosa, n. lactamica, n. flavescens, n. cinerea, n. subflava, n. flava, n. sicca or n. elongata. when n. gonorrhoeae coml and trpb were used as probes, signals were detected on the same restriction fragment in six of the eight species. this indicated that commensal neisseria species share a possible integration site for the iga gene between coma and trpb. the region between coma and trpb was therefore amplified by pcr. the fragment obtained from  n. lactamica showed a high degree of homology to gonococcal coma and trpb, respectively, but iga was replaced by a sequence of 13 bp that shows no homology  to any known gonococcal sequence. our data suggest that iga was acquired by a common ancestor of n. gonorrhoeae and n. meningitidis rather than being distributed by horizontal gene transfer. n. lactamica, which is more closely related to n. gonorrhoeae than other commensals, may have lost iga by deletion.
TIHT== 
ABHT== 

PMID== 8408570
TI  == neisseria weaveri sp. nov., formerly cdc group m-5, a gram-negative bacterium associated with dog bite wounds.
AB  == cdc group m-5 is a rod-shaped, gram-negative, nonmotile bacterium associated with dog bite wounds. dna-dna relatedness and biochemical and growth characteristics were studied for 54 strains from the collection at the centers for disease control and prevention. one typical m-5 strain, 8142, was further studied by 16s  rrna sequencing. dna from 40 of 53 strains showed 82 to 100% relatedness (hydroxyapatite method) to labeled dna from strain 8142. the guanine-plus-cytosine (g + c) content in 8 of the 41 highly related m-5 strains was 50.5 to 52 mol%. these 41 strains were oxidase and catalase positive, nonfermentative, nitrite positive, nitrate negative, weakly phenylalanine deaminase positive, aerobic, and alpha-hemolytic (sheep blood). dna from the 13 remaining strains showed only 7 to 46% dna relatedness to strain 8142. these 13 non-m-5 strains differed from the m-5 strains in g + c content, growth characteristics, and biochemical profiles. dna from m-5 strain 8142 was most closely related to dna from groups ef-4b (47%) and ef-4a (45%). 16s rrna sequence analysis placed m-5 strain 8142 in the neisseriaceae cluster of the beta-3 subgroup of the class proteobacteria. it was most homologous (98.4 to 98.8%) to neisseria animalis, neisseria flavescens, neisseria canis, and neisseria elongata. all data are consistent with m-5 being a new species of neisseria, for  which we propose the name neisseria weaveri.
TIHT== 
ABHT== 

PMID== 8347509
TI  == phylogeny of species in the family neisseriaceae isolated from human dental plaque and description of kingella oralis sp. nov [corrected].
AB  == fourteen human periodontal isolates recovered from a purported eikenella corrodens-selective medium containing 1 microgram of clindamycin per ml displayed biochemical traits which differed from those described for e. corrodens. these organisms were gram-negative rods which corroded agar. the isolates were oxidase  positive and urease, indole, and esculin negative. they differed from e. corrodens in catalase, nitrate reduction, lysine decarboxylase, and ornithine decarboxylase activities. one isolate, strain ub-294, was presumptively identified as kingella denitrificans. a second isolate, strain ub-204, differed from e. corrodens by being catalase positive and nitrate reduction negative. twelve isolates, including strain ub-38t (t = type strain), were phenotypically similar to kingella kingae except that they did not produce acid from maltose and were not beta-hemolytic. essentially complete (1,480-base) 16s rrna sequences were determined for strains ub-38t, ub-204, and ub-294 and the type strains of neisseria animalis, neisseria canis, neisseria denitrificans, neisseria elongata, neisseria flavescens, neisseria macaca, and neisseria polysaccharea. these sequences were compared with the previously published sequences of six other species belonging to the family neisseriaceae. on the basis of the results of the comparative sequence analysis, ub-294 was confirmed as a k. denitrificans strain, ub-204 was identified as a member of a new species which may belong in the genus  eikenella, and ub-38t was identified as a member of a new species of the genus kingella, for which we propose the name kingella oralis [corrected]. since strain ub-204 was the only representative of a new species, it was not named.(abstract truncated at 250 words)
TIHT== 
ABHT== 

PMID== 5488467
TI  == neisseria elongata sp.nov., a rod-shaped member of the genus neisseria. re-evaluation of cell shape as a criterion in classification.
AB  == 
TIHT== 
ABHT== 

