@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 20739702
TI  == subgingival microbial profiles of smokers with periodontitis.
AB  == the subgingival microbiome is largely uncultivated, and therefore, cultivation-based and targeted molecular approaches have limited value in examining the effect of smoking on this community. we tested the hypothesis that  the subgingival biofilm is compositionally different in current and never-smokers by using an open-ended molecular approach for bacterial identification. subgingival plaque from deep sites of current and never-smokers matched for disease was analyzed by 16s sequencing. smokers demonstrated greater abundance of parvimonas, fusobacterium, campylobacter, bacteroides, and treponema and lower levels of veillonella, neisseria, and streptococcus. several uncultivated peptostreptococci, parvimonas micra, campylobacter gracilis, treponema socranskii, dialister pneumosintes, and tannerella forsythia were elevated in this group, while veillonella sp. oral clone b2, neisseria sp. oral clone 2.24, streptococcus sanguinis, and capnocytophaga sp. clone ah015 were at lower levels. the microbial profile of smoking-associated periodontitis is distinct from that of non-smokers, with significant differences in the prevalence and abundance of disease-associated and health-compatible organisms.
TIHT== 
ABHT== 

PMID== 19053926
TI  == microbiological findings in subjects with asymptomatic oral lichen planus: a cross-sectional comparative study.
AB  == background: the bacterial colonization of the oral mucosa was evaluated in patients with asymptomatic oral lichen planus (olp) and compared to the microbiologic status in mucosally healthy subjects. methods: bacteria from patients with clinically and histopathologically diagnosed olp from the stomatology service, department of oral surgery and stomatology, school of dental medicine, university of bern, were collected with a non-invasive swab system. samples were taken from olp lesions on the gingiva and from non-affected sites on the contralateral side of the mouth. the control population did not have olp and  was recruited from the student clinic. all samples were processed with the checkerboard dna-dna hybridization method using well-defined bacterial species for the analysis. results: significantly higher bacterial counts of bacteroides ureolyticus (p = 0.001), dialister species (sp.) (p = 0.006), staphylococcus haemolyticus (p = 0.007), and streptococcus agalactiae (p = 0.006) were found in  samples taken from olp lesions compared to sites with no clinical evidence of olp. significantly higher bacterial counts were found for capnocytophaga sputigena, eikenella corrodens, lactobacillus crispatus, mobiluncus curtisii, neisseria mucosa, prevotella bivia, prevotella intermedia, and s. agalactiae at sites with lesions in subjects with olp compared to sites in control subjects (p  <0.001). conclusions: microbiologic differences were found between sites with olp and sites in subjects without a diagnosis of olp. specifically, higher counts of  staphylococci and s. agalactiae were found in olp lesions.
TIHT== 
ABHT== 

PMID== 18422583
TI  == microbiological evaluation of primary endodontic infections in teeth with and without sinus tract.
AB  == aim: to examine the microbiological status of primary endodontic infections in teeth with and without a sinus tract. methodology: samples were collected by means of a size 15 h-type file and two sterile paper points from 30 cases of primary endodontic infections with (n = 15) or without (n = 15) a sinus tract. the presence of 40 bacterial species was determined by the checkerboard dna-dna hybridization method. results: the species found at the highest levels and prevalence were fusobacterium nucleatum sp. vincentii, porphyromonas gingivalis,  veillonella parvula, enterococcus faecalis, campylobacter gracilis and neisseria  mucosa. total bacterial counts were similar between teeth with (44 x 10(5)) and without (50 x 10(5)) a sinus tract (t-test: p > 0.05). e. faecalis, streptococcus anginosus, capnocytophaga sputigena and capnocytophaga gingivalis had significantly higher counts in the absence of sinus tract (mann-whitney test, p < 0.05). higher levels of p. gingivalis and fusobacterium nucleatum sp. nucleatum were observed in cases with a sinus tract. leptotrichia buccalis (or = 1.83; ci 95%) and porphyromonas endodontalis (or = 2.15; ci 95%) were associated with an increased chance of subjects having a sinus tract. conclusions: primary endodontic infections were associated with a large variety of bacterial species.  specific differences between the composition of the microbiota of primary root canal infections were observed in cases with or without a sinus tract.
TIHT== 
ABHT== 

PMID== 16783243
TI  == ultrasound markers of fetal infection, part 2: bacterial, parasitic, and fungal infections.
AB  == up to 1% of all pregnancies have clinically overt intra-amniotic bacterial infections, and an even larger percentage of pregnant women may be affected by silent infections. although most pregnant women with overt intra-amniotic bacterial infection have experienced prolonged rupture of membranes (prom), symptomatic and most silent nonviral intra-amniotic infections may occur with intact membranes. the etiology of intra-amniotic infection after prom is almost always polymicrobial and consists of genital tract pathogens, such as group b streptococci, chlamydia trachomatis, neisseria gonorrhoeae, mycoplasmas, aerobic  gram-negative bacilli, such as the coliforms, and facultative and anaerobic endogenous organisms, such as peptococci, peptostreptococci, and bacteroides species. these organisms gain access to the uterine cavity by the ascending route. organisms such as treponema pallidum, listeria monocytogenes, toxoplasma gondii, trypanosomes, and plasmodia are capable of gaining access to the amniotic cavity by transplacental hematogenous spread, and cause devastating fetal infections. symptomatic intra-amniotic infection is usually a diagnosis of exclusion. diagnostic criteria based on both clinical and laboratory findings lack sensitivity and are nonspecific. it is difficult to obtain uncontaminated intra-amniotic samples, especially when there is prom. the problem is even greater with silent infections. in most cases, fetal infection is suspected after an unexplained and unexpected adverse outcome. maternal morbidity is increased with intra-amniotic infection; although maternal mortality is extremely rare in developed countries, this is not the case in societies where pregnant women have  limited or no access to medical care. although infected women who are treated early and aggressively with wide-spectrum antibiotics do well, more than 10% of these women develop bacteremia and up to half of them will require cesarean delivery because of poor uterine contractions and arrest of labor. the overwhelming majority of term neonates exposed to intrauterine infection after prom do well, but up to 30% of these neonates require treatment of neonatal pneumonia or bacteremia. outcomes for preterm neonates or for neonates who experienced silent fetal infections are more severe. morbidity and mortality rates in these cases are high, and survivors may have long-term devastating sequelae. the ability to identify ultrasound markers of fetal infection will help clinicians identify etiologic agents with greater accuracy and correlate these infections with specific antepartum and postpartum syndromes. the recognition of  markers of intrauterine infection will also reduce unexpected adverse outcomes that result from undiagnosed fetal infections.
TIHT== 
ABHT== 

PMID== 12839632
TI  == etiology of persistent tubo-ovarian abscess in nairobi, kenya.
AB  == objective: to study the microbial etiology of tubo-ovarian abscess (toa). methods: we recruited 11 women in nairobi, kenya who failed antibiotic therapy alone and required surgical drainage of a presumptive toa. pus from the nine abscesses and two pyosalpinges were collected and cultured for aerobic, facultative and anaerobic microorganisms. results: eleven women suspected of having a toa were hospitalized and treated for a median of 6 days (range 3-14 days) prior to surgical drainage of the abscess. nine (82%) specimens were culture positive. aerobes were present in all nine specimens. seven of the nine positive cultures (78%) were polymicrobial and five of the polymicrobial cultures contained both anaerobes and aerobes. anaerobic gram-negative bacilli (prevotella sp., porphyromonas sp. and bacteroides sp., escherichia coli) and streptococcus sp. (s. viridans and s. agalactiae) were the most common microorganisms isolated. neisseria gonorrhoeae and chlamydia trachomatis were not isolated by culture or detected by polymerase chain reaction. conclusions: in kenya, persistent toas are associated with endogenous flora similar to that normally found in the gastrointestinal tract.
TIHT== 
ABHT== 

PMID== 11545276
TI  == comparative genomics and evolution of genes encoding bacterial (p)ppgpp synthetases/hydrolases (the rel, rela and spot proteins).
AB  == in the gram-negative model organism escherichia coli, the effector molecule of the stringent response, (p)ppgpp, is synthesized by two different enzymes, rela and spot, whereas in the gram-positive model organism bacillus subtilis only one  enzyme named rel is responsible for this activity. rel and spot also possess (p)ppgpp hydrolase activity. blast searches were used to identify orthologous genes in databases. the construction and bootstrapping of phylogenetic trees allowed classification of these orthologs. four groups could be distinguished: with the exception of neisseria and bordetella (beta subdivision), the rela and spot groups are exclusively found in the gamma subdivision of proteobacteria. two rel groups representing the actinobacterial and the bacillus/clostridium group were also identified. the spot proteins are related to the gram positive rel proteins. rela proteins carry substitutions in the hd domain (aravind and koonin, 1998, tibs 23: 469-472) responsible for ppgpp degradation. a theory for the evolution of the specialized, paralogous rela and spot genes is presented: after  gene duplication of an ancestral rellike gene, the spot and rela genes evolved from the duplicated genes. the distribution pattern of the paralogous rela and spot proteins supports a new model of linear bacterial evolution (gupta, 2000, fems microbiol. rev. 24: 367-402). this model postulates that the gamma subdivision of proteobacteria represents the most recently evolved bacterial lineage. however, two paralogous, closely related genes of porphyromonas gingivalis (cytophaga-flavobacterium-bacteroides phylum) encoding proteins with functions probably identical to the rela and spot proteins do not fit in this model. completely sequenced genomes of several obligately parasitic organisms (treponema pallidum, chlamydia species, rickettsia prowazekii) and the obligate aphid symbiont buchnera sp. aps as well as archaea do not contain rel-like genes  but they are present in the arabidopsis genome. in crosslinking experiments using different analogs of ppgpp as crosslinking reagents and rna polymerase preparations of escherichia coli, binding of ppgpp to distinct regions at the c-terminus of the beta subunit (the rpob gene product) and/or at the n-terminus of the beta subunit (the rpoc gene product) was observed previously. rpob and rpoc sequences of the species which do not possess a rel like gene do not exhibit specific insertions or deletions in the ppgpp binding regions.
TIHT== 
ABHT== 

PMID== 9696261
TI  == serum antibodies reacting with subgingival species in refractory periodontitis subjects.
AB  == the purpose of this investigation was to compare the levels of serum igg antibody to 85 subgingival species in 32 refractory periodontitis, 56 successfully treated, and 33 periodontally healthy subjects. refractory subjects showed mean full mouth attachment loss and/or >3 sites showing attachment loss >2.5 mm within 1 year after 2 treatment modalities, scaling and root planing and surgery plus systemically administered tetracycline. successfully-treated subjects showed mean attachment level gain and no sites with attachment loss >2.5 mm, 1 year post-therapy. periodontally healthy subjects exhibited no pocket or attachment level >3 mm, and no evidence of progressing attachment loss during 1 year of monitoring. baseline serum was obtained from each subject and tested against 85 subgingival species, including reference strains and strains isolated from refractory subjects, using checkerboard immunoblotting. significance of differences in levels of serum antibody among groups were sought using the kruskal-wallis test. refractory subjects constituted a heterogeneous group based  on their serum antibody response to subgingival species. some individuals had antibody reactions to many subgingival species, while other subjects showed fewer or low numbers of responses. on average, refractory subjects exhibited higher numbers and levels of serum antibody reactions to a wide range of subgingival species than successfully treated or periodontally healthy subjects. differences  in serum antibody among clinical groups were more striking at higher threshold levels of antibody (>50 microg/ml and > 100 microg/ml). the data showed that a subject was 10.1 x more likely to be refractory if the subject exhibited antibody reactions with >9 subgingival species at >50 microg/ml (p<0.001, after adjusting  for multiple comparisons). serum antibody to a subset of the test species differed among the clinical groups. porphyromonas gingivalis, bacteroidesforsythus, and some strains isolated from refractory subjects (a novel neisseria sp., enterococcus faecalis, prevotella loescheii and prevotella oulora) elicited high serum antibody in the successfully treated and refractory subjects. high levels of serum antibody to a microbacterium lacticum-like organism, streptococcus oralis, streptococcus constellatus, actinobacillus actinonmycetemcomitans serotype c and haemophilus aphrophilus significantly increased the likelihood of a subject being refractory to conventional periodontal therapy.
TIHT== 
ABHT== 

PMID== 9065140
TI  == bacterial colonization of the vagina during pregnancy in four ethnic groups. vaginal infections and prematurity study group.
AB  == objective: our purpose was determine whether there are ethnic differences in vaginal colonization with organisms reputed to be associated with preterm delivery. study design: in seven urban medical centers in the united states from  1984 to 1989, 13,747 predominantly low-socioeconomic-status women at 23 to 26 weeks' gestation were grouped according to ethnic origin. each had a vaginal culture for multiple organisms and gram's stain and ph test to diagnose bacterial vaginosis. multivariate analyses with adjustment for maternal age, insurance status, marital status, smoking history, education level, age at first sexual intercourse, and number of male partners in the past year were also performed to  determine the odds ratio for a black woman versus a white woman having a positive test result. results: for nearly every organism studied, asian-pacific islander and white women had the lowest percentages of positive test results whereas black women had the highest. when black and white women are compared, black women were  more likely to be colonized with chlamydia trachomatis, 16% versus 5%; neisseria  gonorrhoeae, 2.5% versus 0.4%; bacteroides sp., 25% versus 14%; bacterial vaginosis, 23% versus 9%; and the four other organisms evaluated. adjustment for  potential confounders including certain health behaviors did not markedly change  the risk of a black woman having a positive test result, with the odds ratios for colonization with each organism ranging from 1.8 to 6.4. conclusions: highly significant differences exist in vaginal colonization patterns among women of different ethnic groups, with the highest rates of potentially pathogenic organisms observed in black women and the lowest in asian-pacific islander women. differences in health behaviors do not explain the variation in colonization rates.
TIHT== 
ABHT== 

PMID== 7639475
TI  == quantitative bacteriology of tonsils removed from children with tonsillitis hypertrophy and recurrent tonsillitis with and without hypertrophy.
AB  == the aerobic and anaerobic bacterial species and their numbers were studied in tonsillar specimens from children who had undergone elective tonsillectomy: 6 patients with recurrent tonsillitis (rt), 9 with recurrent tonsillitis with hypertrophy (rth), and 8 with obstructive tonsillar hypertrophy (oth). mixed flora were present in all tonsils, yielding an average of 6.7 isolates (5.6 aerobic or facultative and 1.1 anaerobic bacteria). the highest recovery rate of  organisms per tonsil was in patients with oth (7.7 per tonsil), compared to 6.3 per tonsil in rt and 5.9 per tonsil in rth. the predominant aerobic and facultative organisms were haemophilus influenzae (22 isolates), neisseria sp (16), staphylococcus aureus (14), and eikenella corrodens (14), and the predominant anaerobic bacteria were fusobacterium sp (8), bacteroides sp (7), and prevotella melaninogenica (5). the number of bacteria per gram of tonsillar tissue varied between 10(4) and 10(8). a higher concentration of s aureus and h influenzae was found in hypertrophic tonsils (rth and oth) as compared to rt. these findings suggest the presence of an increased bacterial load and supports an etiologic role for h influenzae and s aureus in hypertrophic tonsils with and  without inflammation (rth and oth). further studies to elucidate the effect of selective antimicrobial therapy directed at these organisms may offer an alternative management of hypertrophic tonsils.
TIHT== 
ABHT== 

PMID== 7654835
TI  == [bacteremia in 13 general hospitals of the province of barcelona. prospective study of 1,674 episodes. group of microbiologists of the county hospitals of catalonia].
AB  == background: clinical and microbiological description of bacteremias seen in 13 regional hospitals of barcelona. methods: from january to december of 1991 a multicenter prospective study of bacteremia in regional hospitals was performed.  the filiation, clinical findings and microbiological results were registered according to a common protocol. results: we studied 1674 episodes of bacteremia (13.8 per 1000 admissions). patients were distributed into 3 groups according to  age: under 14: 204 patients, between 14 to 65: 759 and over 65: 711 patients. men account for 55% and women for 45% of episodes. the bacteremia was hospital-acquired in 24.4% of cases. the most common foci of infection were: urinary tract (32%), respiratory tract (14%), intestinal tract (8%), intravascular catheter (7%), biliary tract (7%) and unknown (10%). the most commonly isolated strains were: escherichia coli 544 cases, streptococcus pneumoniae 212, staphylococcus aureus 139, coagulase negative staphylococi 85, non-typhoid salmonella 66, neisseria meningitidis 63, pseudomonas sp. 59, enterococcus sp. 59 and bacteroides sp. 58. polimicrobial bacteremia was detected in 83 episodes (5%). related mortality rate was 9.6% (161 patients).
TIHT== 
ABHT== 

PMID== 8523970
TI  == [susceptibility of bacteria isolated from clinical material to ciprofloxacin].
AB  == the aim of the study was to evaluate susceptibility to ciprofloxacin of bacteria  species isolated from different specimens of clinical materials. the investigated strains (830) were identified using conventional methods. the antibacterial activity of ciprofloxacin was studied by the method of drug dilution in mueller-hinton agar. among aerobic bacteria, only 5 strains (0.6%) were resistant to ciprofloxacin in concentration 4 micrograms/ml; two belonged to e. coli species, two to s. aureus and one was a streptococcus group b., corynebacterium sp. mic90 = 0.12 microgram/ml turned out to be most resistant, next, gram-negative rods mic90 = 0.5 microgram/ml, coagulase-negative and positive staphylococci and neisseria sp. mic90 = 1.0 microgram/ml. enterococcus faecalis and anaerobes were the least susceptible to ciprofloxacin. their mic90 was 2 and  16 micrograms/ml respectively. among 20 anaerobic strains, up to 10 were resistant to ciprofloxacin, mainly from bacteroides and clostridium genus.
TIHT== 
ABHT== 

PMID== 8290195
TI  == piperacillin and tazobactam versus clindamycin and gentamicin in the treatment of hospitalized women with pelvic infection. the piperacillin/tazobactam study group.
AB  == objective: to compare the efficacy and safety of a combination of piperacillin and tazobactam with that of clindamycin and gentamicin in the treatment of hospitalized women with infections of the upper genital tract. methods: this was  a randomized open-label trial in hospitalized women with infections of the upper  genital tract. patients were recruited at 12 hospitals in the united states and two hospitals in canada and were randomly assigned to one of two regimens in a 2:1 ratio. one group received piperacillin, 3 g every 6 hours, and tazobactam, 375 mg every 6 hours; the other group received clindamycin, 900 mg every 8 hours, and gentamicin, 2.5-5.0 mg/kg/day in three divided doses. therapy with the assigned regimen was to be administered for a minimum of 3 days. cultures for aerobic and anaerobic bacteria were obtained from the site of infection before initiation of therapy. cultures for chlamydia trachomatis were also obtained from patients with endometritis or pelvic inflammatory disease. subjects were evaluated for clinical and bacteriologic response at 24-72 hours and 2-4 weeks after completing therapy. results: two hundred ninety-nine patients were enrolled; 196 were in the piperacillin-tazobactam group and 103 were in the clindamycin-gentamicin group. the most common diagnoses were endometritis (146) and pelvic inflammatory disease (115). the most common microorganisms recovered included: peptostreptococcus sp (99), prevotella sp (87), black pigmented bacteroides (29), b fragilis (11), enterococci (64), group b streptococcus (26),  escherichia coli (31), neisseria gonorrhoeae (49), and c trachomatis (19). a favorable clinical response occurred in 84.7% (166 of 196) of piperacillin-tazobactam patients and 87.3% (90 of 103) of clindamycin-gentamicin  patients. among those evaluable for bacteriologic response, 78% (67 of 86) and 82% (23 of 28), respectively, had a favorable response. diarrhea occurred significantly more frequently in the piperacillin-tazobactam group (9.7 versus 2.9%; p = .04), but the majority of episodes were mild to moderate. none of the adverse experiences in either treatment group were considered life-threatening and drug-related. conclusion: the combination of piperacillin and tazobactam is an effective and well-tolerated antibiotic regimen for the treatment of infections of the upper genital tract in women.
TIHT== 
ABHT== 

PMID== 1775091
TI  == evaluation of vaginal microflora in patients infected with hiv.
AB  == hiv infection is thought to exacerbate the virulence of normal saprophytic vaginal microflora. we studied the vaginal ecosystem of hiv patients to detect the quantitative and qualitative variation of vaginal microorganisms. 15 patients (5 with aids and 10 with arc) were investigated. vaginal candidiasis was more frequent in this group than in the control groups. gardnerella was present in 60% of patients generally in association with anaerobic bacteria and mycoplasma. among anaerobia, bacteroides sp and other gram-negative rods were the most common bacteria. neisseria gonorrhoeae was absent in all patients tested. chlamydia trachomatis was recovered in two out of the 15 hiv-positive patients. aerobic gram-negative flora was 100-fold that of the control group and anaerobic gram-negative flora 10-fold.
TIHT== 
ABHT== 

PMID== 2664255
TI  == [susceptibilities of clinical isolates to antibacterial agents. a study mainly focused on ofloxacin (the second report). reported by the research group for testing ofloxacin susceptibility on clinical isolates].
AB  == susceptibilities of various clinical isolates to ofloxacin (oflx) and other antibacterial drugs were examined at 128 hospital laboratories in 36 prefectures  throughout japan between april, 1986 and march, 1987. the results were totalized  with an emphasis mainly on oflx and were compared with data obtained in the previous year. in this study, identification and susceptibility tests of the isolates were carried out at each hospital laboratory and the tests were performed according to the 1-dilution or 3-dilution disc method in which susceptibilities are classified into 4 grades: , ++, +, and -. similarly to the study performed in the previous year, species showing susceptibilities to oflx included staphylococcus aureus (4,205 strains), staphylococcus epidermidis (2,009 strains), entercoccus faecalis (1,697 strains), streptococcus pneumoniae (702 strains), escherichia coli (4,097 strains), klebsiella pneumoniae (1,375 strains), enterobacter cloacae (762 strains), enterobacter aerogenes (296 strains), citrobacter freundii (406 strains), proteus mirabilis (613 strains), morganella morganii (320 strains), serratia marcescens (869 strains), haemophilus influenzae (1,282 strains), pseudomonas aeruginosa (4,206 strains), acinetobacter calcoaceticus (351 strains), acinetobacter sp. (415 strains), and campylobacter jejuni (151 strains). neisseria gonorrhoeae (26 strains) were exceptional due to  their smaller number this time than that of the previous year and only the susceptibility to oflx was investigated with this species. as results, oflx showed strong antibacterial activities (similar to the previous year) against s.  aureus, s. epidermidis, n. gonorrhoeae, e. coli, k. pneumoniae, e. cloacae, e. aerogenes, c. freundii, p. mirabilis, m. morganii, h. influenzae, a. calcoaceticus, acinetobacter sp., and c. jejuni. however, when these susceptibilities shown in the present study were compared to those obtained in the previous year, many species showed decreases in the occurrence of or increases in -, though they were rather small changes. the following species were not totalized in the previous year due to their low numbers but were summarized in combination with those examined in this study: streptococcus pyogenes (944 strains), streptococcus agalactiae (815 strains), enterococcus faecium (146 strains), branhamella catarrhalis (135 strains), citrobacter diversus (128 strains), klebsiella oxytoca (873 strains), proteus vulgaris (438 strains), serratia liquefaciens (266 strains), pseudomonas cepacia (433 strains), pseudomonas putida (154 strains), xanthomonas maltophilia (272 strains), vibrio parahaemolyticus (120 strains), bacteroides fragilis (98 strains),
TIHT== 
ABHT== 

PMID== 2509645
TI  == the in vitro activity of tigemonam: a comparison with other antimicrobial agents.
AB  == the activity of tigemonam was compared with that of aztreonam, cefuroxime, cephalexin, amoxicillin/clavulanate potassium, gentamicin, and ofloxacin, using an agar dilution method. tigemonam was active against strains containing known beta-lactamases of tem and oxa types, but strains containing broad-spectrum (group iv) enzymes were less susceptible. the mic90 of tigemonam against the common enterobacteriaceae was less than or equal to 0.25 mg/l. the mic90s against haemophilus influenzae and neisseria gonorrhoeae were 0.5 and 0.06 mg/l, respectively. pseudomonas, staphylococci, and bacteroides sp. were less susceptible (mic90 greater than 128 mg/l). protein binding in human serum was found to be 62.5%; the presence of serum had only a modest effect on the activity of tigemonam.
TIHT== 
ABHT== 

PMID== 2644068
TI  == direct and indirect pathogenicity of beta-lactamase-producing bacteria in mixed infections in children.
AB  == the recent emergence of numerous aerobic and anaerobic beta-lactamase-producing bacterial strains has been associated with an increase in the failure rate of penicillins in the therapy of infection caused by these organisms. these include  respiratory tract, skin of soft tissue, female genital tract, intra-abdominal, and other miscellaneous infections. the important aerobic beta-lactamase-producing bacteria (blpb) include staphylococcus aureus, branhamella catarrhalis, haemophilus sp., neisseria gonorrhoeae, escherichia coli, klebsiella pneumoniae, pseudomonas aeruginosa, and legionella sp. the anaerobic blpb are all bacteroidiaceae and include bacteroides fragilis group, b. melaninogenicus group, b. oralis, b. oris-buccae, and fusobacterium sp. laboratory, animal, and clinical studies that support the indirect pathogenicity  of these organisms and the distribution of these blpb in various infections are reviewed. blpb may not only have a direct pathogenic role in causing the infection, but also an indirect pathogenic role. the indirect pathogenicity of these organisms is apparent through their ability not only to survive penicillin  therapy, but also to protect penicillin-susceptible pathogens from that drug. these direct and indirect virulence characteristics of aerobic and anaerobic blpb require the administration of appropriate antimicrobial therapy directed against  all pathogens in mixed infections.
TIHT== 
ABHT== 

PMID== 3142350
TI  == in vitro activity of pd 127,391, an enhanced-spectrum quinolone.
AB  == the in vitro activity of pd 127,391, a dihalogenated quinolone, was compared with those of ofloxacin, ciprofloxacin, nalidixic acid, gentamicin, and cefuroxime against 525 recent isolates and well-characterized antimicrobial agent-resistant  strains. the mics of pd 127,391 against 90% of members of the family enterobacteriaceae, bacteroides fragilis, haemophilus influenzae, neisseria sp.,  and streptococcus pneumoniae were less than or equal to 0.12 microgram/ml. some 90% of pseudomonas aeruginosa and staphylococci were susceptible to 0.25 micrograms of pd 127,391 per ml. against most strains, pd 127,391 was 2- to 8-fold more active than ciprofloxacin, but it was 64-fold more active than ciprofloxacin against b. fragilis. strains of members of the family enterobacteriaceae which were resistant to nalidixic acid were less susceptible to all of the quinolones tested, including pd 127,391. the mic and minimum lethal concentration of pd 127,391 against three strains of chlamydia trachomatis were each 0.06 microgram/ml, and the mic against 90% of 21 strains of mycobacterium tuberculosis was 1 microgram/ml. pd 127,391 was less active at ph 5, its maximal  activity being at ph 7 to 8. the presence of urine at ph 5.9 decreased the bactericidal activity. the protein binding of pd 127,391 was 2 to 7%, and serum had little effect on activity.
TIHT== 
ABHT== 

PMID== 3134843
TI  == in vitro activity of lomefloxacin, a new quinolone antimicrobial agent, in comparison with those of other agents.
AB  == the in vitro activity of lomefloxacin (sc-47111; ny-198), a new difluorinated quinolone, was compared with those of ofloxacin, ciprofloxacin, fleroxacin, amoxicillin, cefuroxime, and trimethoprim against 585 recent clinical isolates and other strains with known mechanisms of resistance. the mics of lomefloxacin against 90% of the members of the family enterobacteriaceae, pseudomonas aeruginosa, and staphylococci were between 0.25 and 4 micrograms/ml. ninety percent of neisseria sp. and haemophilus influenzae were susceptible to less than or equal to 0.06 micrograms/ml, and streptococci (including streptococcus pyogenes, streptococcus pneumoniae, and enterococci) and bacteroides fragilis were susceptible to 8 micrograms/ml. lomefloxacin was comparable in activity to fleroxacin and ofloxacin, but it was less active than ciprofloxacin. there was cross-resistance between the quinolone group of antimicrobial agents. the protein binding of lomefloxacin was 15.4%, and serum had little effect on the activity of the compound. however, urine at ph 5.0 decreased the activity by two- to eightfold compared with that at ph 7.0
TIHT== 
ABHT== 

PMID== 3162652
TI  == results of noncomparative studies of cefotetan in the treatment of obstetric and  gynecologic infections.
AB  == in a multicenter trial involving 11 centers, 160 women were enrolled to evaluate  the safety and effectiveness of 1 or 2 gm of cefotetan administered every 12 hours in the treatment of obstetric and gynecologic infections. the 133 evaluable patients generally were under 25 years of age, were nonwhite, and had hospital-acquired endometritis or pelvic inflammatory disease caused by both aerobic and anaerobic bacteria. escherichia coli, neisseria gonorrhoeae, group d  streptococci, bacteroides sp., and peptococcus sp. were among the most frequently isolated pathogens. the patients were treated for a mean of 5.6 +/- 1.6 days and  received a total dose of 19.27 gm. the signs and symptoms of infection were cleared or improved in 93% of the 133 patients evaluable for clinical response. of the 116 evaluated bacteriologically, 95% had a satisfactory or presumed satisfactory response; only six patients (5%) were considered to be bacteriologic failures. differences in the results of several clinical laboratory tests performed before and after treatment were statistically, but not clinically, significant (p less than 0.05). safety was evaluated in the 158 patients who received cefotetan, and only four (3%) had adverse reactions considered related to the drug. cefotetan was clearly effective and produced no untoward reactions in these women with obstetric and gynecologic infections caused by both aerobic and anaerobic organisms when administered at 1 or 2 gm every 12 hours.
TIHT== 
ABHT== 

PMID== 3369805
TI  == [sensitivity to an amoxicillin-clavulanic acid combination, of deep tonsillar flora isolated in chronic tonsillitis].
AB  == deep tonsillar flora were identified in tonsils removed from 48 patients, children and adults, with chronic tonsillitis and recurrent sore throats or obstructive hypertrophy. most specimens (38/48) cultured multiple germs (2 to 5 different species) with aerobic and anaerobic gram+ and gram-forms, some being beta-lactamase producers. of the total of 135 strains isolated, 104 were aerobic  and 31 anaerobic. the species of aerobic germs most frequently isolated were: apart from alpha-hemolytic streptococci of undertermined group (38 strains), haemophilus sp. : 14 (including 3 beta-lactamase + strains), staphylococcus aureus: 15 (including 11 beta-lactamase + strains), streptococcus a : 10, enterobacteriaceae : 6, neisseria sp. : 8 (including 1 beta-lactamase + strain).  and among the anaerobic germs: peptococcus : 3, veillonella alc : 10, fusobacterium nucleatum : 9, bacteroides melaninogenicus : 6, other bacteroides : 2. of the 127 strains tested, 102 were sensitive to amoxicillin and 121 to amoxicillin and clavulanic acid combination. the presence of a beta-lactamase producing bacterium in 1 of 3 specimens suggests the risk of failure of treatment with penicillin, prescribed classically for this type of affection.
TIHT== 
ABHT== 

PMID== 2975212
TI  == trospectomycin, a novel spectinomycin analogue: antibacterial activity and preliminary human pharmacokinetics.
AB  == trospectomycin (tsp; u-63366f) is a novel spectinomycin (sp) analogue with broad-spectrum antibacterial activity. the in vitro activity of the analogue was  compared to that of sp against approximately 400 bacterial isolates. the in vivo  activity of the compound was assessed using experimental infection models for both gram-positive and gram-negative facultative bacteria. the preliminary human  pharmacokinetics of tsp were evaluated following single-dose i.v. or i.m. administration. tsp was more active in vitro than sp (2 to 32-fold) against strains of numerous bacterial species, including staphylococci, streptococci, haemophilus influenzae, branhamella catarrhalis, neisseria gonorrhoeae, proteus spp., bacteroides spp., gardnerella vaginalis and chlamydia trachomatis. the activity of tsp for most species of the family enterobacteriaceae was comparable  to that of sp. tsp was more active than sp (2 to 32-fold) in curing experimental  infections due to streptococci, salmonella typhi, serratia marcescens, klebsiella pneumoniae and haemophilus influenzae. tsp was well-absorbed following both i.v.  and i.m. administration. pharmacokinetic analysis of microbiological assay data for the 1000 mg dose yielded the following mean values for the i.v. and i.m. routes, respectively: cmax = 81.2, 28.7 micrograms/ml; serum half-life = 2.2, 2.2 h; tmax = 25, 75 min; and auc = 156.6, 116.2 h micrograms/ml. pharmacokinetic analysis of assay data derived using the more sensitive hplc assay revealed the biphasic nature of trospectomycin elimination, highlighted by a short apparent serum half-life (2.2 h) and a prolonged tissue half-life (approximately 36 h). tsp inhibits a variety of clinically important organisms, including agents of sexually transmitted diseases and pelvic inflammatory disease, and demonstrates favourable pharmacokinetic properties.(abstract truncated at 250 words)
TIHT== 
ABHT== 

PMID== 3680003
TI  == coloradocin, an antibiotic from a new actinoplanes. i. taxonomy, fermentation and biological properties.
AB  == coloradocin was discovered in a screen for anti-anaerobe activity. the producing  organism was determined to be a new species of actinoplanes, designated actinoplanes coloradoensis sp. nov. coloradocin inhibits bacteroides, clostridium and other anaerobes. it does not inhibit most aerobic bacteria but is effective against neisseria gonorrhoeae and haemophilus influenzae. coloradocin has low acute toxicity.
TIHT== 
ABHT== 

PMID== 3030109
TI  == ampicillin/sulbactam versus metronidazole-gentamicin in the treatment of soft tissue pelvic infections.
AB  == the clinical efficacy and safety of ampicillin/sulbactam versus metronidazole-gentamicin were evaluated in a comparative, randomized, prospective study. forty-four patients were enrolled: 22 received the ampicillin/sulbactam regimen, and 22 received the metronidazole-gentamicin combination. there were 33  cases of severe acute pelvic inflammatory disease, two tuboovarian abscesses, five cases of endomyometritis, and two cases of posthysterectomy pelvic cellulitis. aerobic and anaerobic cultures from the infection sites yielded 447 microorganisms from 44 patients (an average of 10 bacteria per infection; 6.4 anaerobes and 3.7 aerobes). the most frequent isolates were bacteroides sp., 54;  bacteroides bivius, 17; black-pigmented bacteroides, 12; bacteroides disiens, 11; fusobacterium, 13; peptostreptococcus anaerobius, 24; peptostreptococcus asaccharolyticus, 21; anaerobic gram-positive cocci, 34; gardnerella vaginalis, 29; neisseria gonorrhoeae, 17; alpha-hemolytic streptococci, 15; and escherichia  coli, five. clinical cure was noted in 19 of 20 patients treated with ampicillin/sulbactam and 18 of 21 patients treated with metronidazole-gentamicin. one treatment failure occurred in the ampicillin/sulbactam group in a patient who required antichlamydial therapy and had a complex left adnexal mass consistent with an abscess. the cases of metronidazole-gentamicin failure included two patients initially diagnosed as having tuboovarian abscesses who required a change in antibiotic therapy to control the infections. the third patient had postabortion endomyometritis that did not respond to metronidazole-gentamicin therapy within 48 hours, and required a change of medication. no adverse hematologic, renal, or hepatic effects were noted in either group of patients.
TIHT== 
ABHT== 

PMID== 3549179
TI  == in vitro activity of two new aryl-fluoroquinolone antimicrobial agents, difloxacin (a-56619) and a-56620 compared to that of other antimicrobial agents.
AB  == the in vitro activity of difloxacin (a-56619) and a-56620, two new aryl-difluoroquinolones, was compared to that of other new quinolones and several parenteral and oral antimicrobial agents. a-56620 inhibited 90% of enterobacteriaceae at less than or equal to 1 microgram/ml, staphylococcus aureus 0.25 micrograms/ml, hemolytic streptococci 2 micrograms/ml, pseudomonas aeruginosa 2 micrograms/ml, bacteroides sp. and clostridium at 8 micrograms/ml. a-56620 was equal or 2-fold more active than norfloxacin and ofloxacin, and 2-8-fold less active than ciprofloxacin. difloxacin had similar in vitro activity with many isolates but usually was 2-8-fold less active than a-56620. both agents inhibited beta-lactamase positive haemophilus influenzae (mic 0.015 micrograms/ml) and neisseria gonorrhoeae (mk less than or equal to 0.008 micrograms/ml). both agents were more active against streptococci and streptococcus pneumoniae than norfloxacin, ofloxacin and enoxacin, but not more active than ciprofloxacin. they inhibited enterobacter cloacae, citrobacter freundii and serratia marcescens resistant to cephalosporins and methicillin-resistant s. aureus and staphylococcus epidermidis. spontaneously resistant mutants were seen with enterobacteriaceae, p. aeruginosa and s. aureus  at a frequency similar to that found for other new quinolones. these agents show  overall in vitro activity comparable to other quinolones in clinical trial or recently approved for clinical use.
TIHT== 
ABHT== 

PMID== 3324977
TI  == bacterial synergy in pelvic inflammatory disease.
AB  == polymicrobial aerobic and anaerobic flora are responsible for pelvic inflammatory disease (pid). the most frequent pathogens appear to be neisseria gonorrhoea and  anaerobic bacteria (most commonly anaerobic cocci and bacteroides sp.). recent studies have demonstrated the recovery of chlamydia trachomatis in up to a third  of these infections. although n. gonorrhoea is frequently recovered from cervical cultures, it is less commonly recovered from intra-abdominal sites. recent studies have demonstrated the in-vivo synergistic relationship between n. gonorrhoeae and bacteroides fragilis. the growth of each component of the mixed infection was enhanced when these were present together in an abscess. furthermore, the emergence of encapsulated strains was enhanced in these infections. this synergy enables the organisms to cause more severe local and systemic damage to the host. therapeutic intervention should include the use of antimicrobial agents effective against both the aerobic and anaerobic components  of the mixed infection. unless such therapy is given, the infection may persist.  it is also recommended to use antimicrobials that possess synergy between them against the bacterial pathogens. agents effective against the anaerobic pathogens are metronidazole, clindamycin and cefoxitin. antimicrobials effective against the gram-positive aerobic pathogens and n. gonorrhoeae are spiramycin and penicillins. aminoglycosides or third generation cephalosporins are effective against gram-negative enterics. the combination of metronidazole and spiramycin has shown to be synergistic against mixed infections of bacteroides sp. and n. gonorrhoeae.
TIHT== 
ABHT== 

PMID== 3463557
TI  == the in-vitro activity of ci-934 compared with that of other new 4-quinolones and  nalidixic acid.
AB  == the in-vitro activity of ci-934, a new 4-quinolone compound, was compared with that of the other new 4-quinolones, enoxacin and ciprofloxacin, and also with that of nalidixic acid. ci-934 was more active than any of the other 4-quinolones tested against gram-positive aerobic organisms including staphylococcus aureus (mics 0.06-0.25 mg/l), beta-haemolytic streptococci (mics 0.12-0.5 mg/l), streptococcus pneumoniae (mics 0.25-0.5 ml/l), viridans streptococci (mics 0.06-0.5 mg/l) and most enterococci (mics 0.12-0.5 mg/l), although some ampicillin-resistant isolates of str. faecium were slightly less susceptible (mics 2 mg/l). all three of the newer 4-quinolones tested were highly active against enterobacteriaceae, aeromonas sp., haemophilus influenzae and neisseria gonorrhoeae (mics mostly less than 1 mg/l). the other gram-negative aerobes tested were in general somewhat less susceptible, although for acinetobacter and  pseudomonas aeruginosa mics seldom exceeded 8 mg/l. ci-934 was more active than enoxacin against gardnerella vaginalis (mics 1-8 mg/l) although it was a little less active than ciprofloxacin. bacteroides species (including about half of the  fragilis group) were susceptible to ci-934 (mics mostly 1-8 mg/l): ciprofloxacin  had similar activity but enoxacin was less active. other anaerobes tested were mostly highly susceptible to ci-934 (mics 1 mg/l or less) but were somewhat less  susceptible to enoxacin and ciprofloxacin.
TIHT== 
ABHT== 

PMID== 3865923
TI  == in-vitro activity of ofloxacin, a quinolone carboxylic acid compared to other quinolones and other antimicrobial agents.
AB  == ofloxacin is a new quinolone carboxylic acid compound. its activity against 900 bacterial isolates was determined. it inhibited 90% of escherichia coli, klebsiella sp., aeromonas hydrophila, salmonella spp., shigella spp., citrobacter spp., enterobacter spp., morganella morganii, proteus mirabilis, yersinia enterocolitica at less than or equal to 0.8 mg/l. branhamella catarrhalis, haemophilus sp., neisseria sp. were inhibited by less than or equal to 0.1 mg/l.  pseudomonas aeruginosa and other pseudomonas species were inhibited by less than  or equal to 6.3 mg/l. although most staphylococcal species, including methicillin-resistant staphylococci were inhibited by 3.1 mg/l, many streptococcal species had higher mic values, and most bacteroides species were inhibited at less than or equal to 6.3 mg/l. the overall activity of ofloxacin was similar to enoxacin and norfloxacin. ofloxacin inhibited organisms resistant  to nalidixic acid, ampicillin, cephalexin, piperacillin, and gentamicin including enterobacter spp., citrobacter freundii and serratia marcescens resistant to cefotaxime. the activity of ofloxacin was lower at an acid ph and in urine, but serum had no effect on mics or mbcs. increase in ofloxacin mics for various bacteria could be achieved by repeated subculture in the presence of ofloxacin.
TIHT== 
ABHT== 

PMID== 3932293
TI  == the establishment of reproducible, complex communities of oral bacteria in the chemostat using defined inocula.
AB  == nine commonly isolated oral bacterial populations were inoculated into a glucose-limited and a glucose-excess (amino acid-limited) chemostat maintained at a constant ph 7.0 and a mean community generation time of 13.9 h. the bacterial populations were streptococcus mutans atcc 2-27351, strep. sanguis nctc 7865, strep. mitior ef 186, actinomyces viscosus wvu 627, lactobacillus casei ac 413, neisseria sp. a1078, veillonella alkalescens atcc 17745, bacteroides intermedius  t 588 and fusobacterium nucleatum nctc 10593. all nine populations became established in the glucose-limited chemostat although strep. sanguis and neisseria sp. were present only after a second and third inoculation, respectively. in contrast, even following repeated inoculations, strep. mutans, b. intermedius and neisseria sp. could not be maintained under glucose-excess conditions. a more extensive pattern of fermentation products and amino acid catabolism occurred under glucose-limited growth; this simultaneous utilization of mixed substrates also contributed to the higher yields (y molar glucose) and greater species diversity of these communities. microscopic and biochemical evidence suggested that cell-to-cell interactions and food chains were occurring  among community members. to compare the reproductibility of this system, communities were established on three occasions under glucose-limitation and twice under glucose-excess conditions. the bacterial composition of the steady-state communities and their metabolic behaviour were similar when grown under identical conditions but varied in a consistent manner according to the nutrient responsible for limiting growth. although a direct simulation of the oral cavity was not attempted, the results show that the chemostat could be used  as an environmentally-related model to grow complex but reproducible communities  of oral bacteria for long periods from a defined inoculum.
TIHT== 
ABHT== 

PMID== 3895947
TI  == moxalactam versus clindamycin plus tobramycin in the treatment of obstetric and gynecologic infections.
AB  == the clinical efficacy of moxalactam versus clindamycin/tobramycin was evaluated in a comparative, randomized, prospective study. sixty patients were treated: 30  with moxalactam and 30 with clindamycin/tobramycin. there were 15 cases of tuboovarian abscess, 36 cases of severe pelvic inflammatory disease with peritonitis, eight cases of endomyometritis, and one wound abscess. aerobic and anaerobic cultures from the sites of infection yielded 441 microorganisms from 53 patients; an average of 8.3 bacteria per infection (4.5 anaerobes and 3.8 aerobes). the infections tended to be mixed aerobic-anaerobic with anaerobes isolated in 90% of cases. the most frequently isolated possible pathogens were bacteroides sp. (37), bacteroides bivius (23), bacteroides asaccharolyticus (12), peptococcus asaccharolyticus (29), peptostreptococcus anaerobius (19), unidentified anaerobic gram-positive cocci (18), escherichia coli (17), nonhemolytic streptococci (16), neisseria gonorrhoeae (13), and gardnerella vaginalis (38). clinical cure was noted in 29 of 30 moxalactam-treated and 29 of  30 clindamycin/tobramycin-treated patients. moxalactam was effective in five of six cases of tuboovarian abscess, all 22 cases of pelvic inflammatory disease with peritonitis, the one case of endomyometritis and the one wound abscess. clindamycin/tobramycin was effective in eight of nine cases of tuboovarian abscess, all 14 cases of pelvic inflammatory disease with peritonitis, and all seven cases of endomyometritis. no adverse hematologic, renal, or hepatic effects were noted with either regimen.
TIHT== 
ABHT== 

PMID== 3911142
TI  == [multicenter study of the in vitro effect of imipenem (n-formimidoyl-thienamycin) on hospital bacteria].
AB  == minimal inhibitory concentrations (mics) of imipenem were evaluated by agar dilution for 2 895 bacterial strains isolated in 9 hospitals. imipenem proved highly active against enterobacteriaceae, with an mic less than or equal to 0.25  for 63% of the 1 556 tested strains, less than or equal to 1 for 89.6% and less than or equal to 4 for 99%. the different groups of enterobacteriaceae exhibited  similar mode mics (0.12 to 0.25), with the exception of serratia (0.25-0.5), p. mirabilis (0.5), indole-positive proteus (2), and providencia (1). mics of most cefotaxime-resistant strains were within the susceptibility range. imipenem also  exhibited satisfactory activity against p. aeruginosa (mode mic 1-2) and acinetobacter sp. (mode mic: 0.25-0.5). mics ranged from 0.03 to 4 (mode mic: 0.5) for haemophilus sp. and 0.25 to 1 for gonococci, regardless of beta-lactamase-production status. mics for meningococci were less than or equal to 0,06. methicillin-susceptible staphylococci had low mics, ranging from 0.008 to 0.5 (mode mic : 0.016); mics for methicillin-resistant strains varied widely,  from 0.016 to 64, and were higher after incubation at 30 degrees c. streptococci, except for enterococci, and pneumococci were highly susceptible (usually 0.008-0.03); mics for enterococci varied from 0,12 to 32 (mode mic: 1-2). except  for four c. difficile strains, all tested anaerobic strains were inhibited by concentrations less than or equal to 1 (mode mics: 0.06 for c. perfringens and 0.03 for b. fragilis).
TIHT== 
ABHT== 

PMID== 2868442
TI  == [in vitro activity of ceftriaxone on hospital bacteria. results of a multicenter  study].
AB  == minimal inhibitory concentrations (mics) of ceftriaxone were determined by agar dilution for 2 099 strains isolated in six teaching hospitals. mics were less than 1 microgram/ml for the great majority of enterobacteriaceae, with mode mics  varying across groups from less than 0.008 micrograms/ml for proteus (mirabilis and indole-positive) to 0.25 for enterobacter. only a few resistant strains were  found, mainly among enterobacter and citrobacter. ceftriaxone proved noticeably less active against p. aeruginosa and acinetobacter (mode mics: 16 micrograms/ml). haemophilus sp. and gonococci, regardless of beta-lactamase production status, as well as neisseria meningitidis, were highly susceptible (mic less than 0.008-0.032). ceftriaxone was moderately active against methicillin-susceptible staphylococci (mic: 2 to 8 micrograms/ml) and failed to inhibit methicillin resistant strains. enterococci were slightly susceptible or resistant, whereas the other streptococci and pneumococci had low mics (0.03-0.25). a fairly wide range of mics was found for anaerobes (clostridium: 0.06-2, bacteroides: 0.5-32). our data show that its particularly strong activity against proteus, haemophilus and neisseria sets ceftriaxone apart from the other  third-generation cephalosporins.
TIHT== 
ABHT== 

PMID== 6330645
TI  == [in vitro activity of ceftizoxime on hospital bacteria. results of a multicenter  study].
AB  == the susceptibility to ceftizoxime of all bacterial strains isolated from seven university-affiliated hospitals over one month was tested with disk-diffusion technique. additionally, the mic of 1937 strains selected at random was evaluated by the agar dilution method. the majority of enterobacteriaceae are inhibited at  a concentration of less than 1 microgram/ml with a mode mic varying from 0.008 to 0.12 among the various groups. a few enterobacter and citrobacter strains are resistant. little activity was demonstrated by ceftizoxime on pseudomonas aeruginosa and acinetobacter sp. (mode mic 32 and 8 micrograms/ml respectively).  haemophilus sp. (mic 0.01-0.03) and neisseria (mic less than 0,008-0,016) are very susceptible to the drug. the mic of methicillin-sensitive strains of staphylococcus aureus varies from 1 to 4 micrograms/ml ; enterococci are less susceptible, whereas other streptococci and pneumococci have low mics (less than  0.008-0.025). the susceptibility of anaerobic pathogens varies widely between species, and within species ; mic ranges from 0.008 to 32 micrograms/ml for clostridium sp. and 0.25 to 128 micrograms/ml for bacteroides sp.
TIHT== 
ABHT== 

PMID== 6597563
TI  == trends in the development of beta-lactam antibiotics.
AB  == in many ways it is ironic that the first description of a beta-lactamase occurred in 1940 with an enzyme isolated from escherichia coli since in recent years there has been a major interest in gram-negative species and the development of agents  to overcome the hydrolytic action of beta-lactamases of gram-negative species. there have been four distinctly different approaches to the development of new beta-lactam antibiotics. these have been the search for inhibitors of beta-lactamases and agents such as clavulanic acid and sulbactam are examples of  compounds which by virtue of kcat function act as suicide inhibitors and make old antibiotics new. there has been the modification of the penicillin and cephem nucleus to increase beta-lactamase stability or failing that to improve the ability of the compounds to pass through the cell wall and increase affinity for  critical beta-lactam receptors, i.e. penicillin-binding proteins. there has been  the development of carbapenem type of agents such as imipenem which would have broad activity including aerobic, anaerobic, gram-positive and gram-negative species. there has been the discovery of the monobactam agents of which aztreonam is an example of a compound with great beta-lactamase stability but with activity limited to gram-negative aerobic species. bacterial resistance has indeed been the major factor that has modified use of beta-lactams and influenced the development of the aforementioned types of drugs. the widespread presence of beta-lactamases in common pathogens such as haemophilus influenzae, neisseria gonorrhoeae, escherichia coli, klebsiella sp., pseudomonas aeruginosa, and bacteroides fragilis has made it necessary to have beta-lactamase stable compounds for initial therapy of infection. it is possible to analyze structure-activity relations of beta-lactam compounds to determine changes which  will be most advantageous in light of known and expected resistance patterns. but the increased realization in recent years of the importance of the pharmacokinetics of beta-lactam drugs has made it essential that the development  of new compounds be based on an integration of microbiological and pharmacokinetic parameters. interest in the prevention of resistant flora has also affected the development of new drugs since it is increasingly appreciated that alteration of intestinal flora contributes to selection of drug resistant microorganisms. finally, new toxicities or adverse effects associated with the use of certain new agents has modified the development of certain compounds.
TIHT== 
ABHT== 

PMID== 6229216
TI  == in vitro activity of enoxacin, a quinolone carboxylic acid, compared with those of norfloxacin, new beta-lactams, aminoglycosides, and trimethoprim.
AB  == enoxacin is a new quinolone carboxylic acid compound. its activity against 740 bacterial isolates was determined. it inhibited 90% escherichia coli, klebsiella  sp., aeromonas sp., enterobacter spp., serratia spp., proteus mirabilis, and morganella morganii at less than or equal to 0.8 micrograms/ml. the majority of pseudomonas aeruginosa was inhibited by less than or equal to 3.1 micrograms/ml.  haemophilus spp. and neisseria spp. were inhibited by less than 0.1 micrograms/ml. although most staphylococcus aureus were inhibited by 3.1 micrograms/ml, some streptococcal species had minimal inhibitory concentrations of 6.3 to 12.5 micrograms/ml and bacteroides sp. had minimal inhibitory concentrations greater than or equal to 25 micrograms/ml. activity of enoxacin and norfloxacin was similar. enoxacin inhibited organisms resistant to cefotaxime, moxalactam, gentamicin, and piperacillin. enoxacin was less active in urine at an acid ph than in broth, but serum did not decrease minimal inhibitory  concentrations or minimal bactericidal concentrations. there was no major difference between minimal inhibitory concentrations and minimal bactericidal concentrations. resistance frequency development was less than 10(-9) for most bacterial species.
TIHT== 
ABHT== 

PMID== 7099784
TI  == vulvovaginitis in premenarcheal girls: clinical features and diagnostic evaluation.
AB  == fifty-four premenarcheal patients (median age 5.8 years) with symptoms or signs of vulvovaginitis were studied, and the results of cultures of vaginal secretions were compared with those from an age-matched control group. vaginal discharge was found on examination in 24 of 42 patients with a complaint of discharge, and in two of 12 patients without a complaint of discharge. convincing evidence of bacterial or monilial infection was found in 14 of the 26 patients with discharge on examination, but in none of the 28 patients without discharge (p less than .001). in the latter group pinworm infestation was present in one patient. moniliasis occurred exclusively in girls who were pubertal (p less than .001). four patients were found to have gonorrhea. no patient appeared to have symptoms  or signs caused by bacteroides sp, chlamydia trachomatis, viruses, or trichomonas vaginalis. noninfectious causes were identified in four patients with and 13 without discharge (p less than .025); the most common cause was poor hygiene, implicated in six patients. bubble bath use was implicated in only one patient. in 22 patients, no specific cause could be identified. all patients with poor hygiene as the only cause, and most with no demonstrable etiology, recovered after being advised to institute improved perineal hygiene. patients with vaginal discharge are likely to have specific infections, and therefore cultures should be taken, in particular for neisseria gonorrhoeae. genital pruritus in prepubertal girls has little or no etiologic specificity, but in pubertal girls with vaginal discharge it suggests the presence of monilial vaginitis.
TIHT== 
ABHT== 

