@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25946126
TI  == oral microbiota shift after 12-week supplementation with lactobacillus reuteri dsm 17938 and pta 5289; a randomized control trial.
AB  == background: lactobacillus spp. potentially contribute to health by modulating bacterial biofilm formation, but their effects on the overall oral microbiota remain unclear. methods and findings: oral microbiota was characterized via 454-pyrosequencing of the 16s rdna hypervariable region v3-v4 after 12 weeks of daily lactobacillus reuteri dsm 17938 and pta 5289 consumption. forty-four adults were assigned to a test group (n = 22) that received lactobacilli lozenges (108 cfu of each strain/lozenge) or a control group that received placebo (n = 22). presence of l. reuteri was confirmed by cultivation and species specific pcr. tooth biofilm samples from 16 adults before, during, and after exposure were analyzed by pyrosequencing. a total of 1,310,292 sequences were quality filtered. after removing single reads, 257 species or phylotypes were identified at 98.5% identity in the human oral microbiome database. firmicutes, bacteroidetes, fusobacteria, proteobacteria, and actinobacteria were the most abundant phyla. streptococcus was the most common genus and the s. oralis/s. mitis/s. mitis bv2/s. infantis group comprised the dominant species. the number of observed species was unaffected by l. reuteri exposure. however, subjects who had consumed l. reuteri were clustered in a principal coordinates analysis relative to scattering at baseline, and multivariate modeling of pyrosequencing microbiota, and culture and pcr detected l. reuteri separated baseline from 12-week samples in test subjects. l. reuteri intake correlated with increased s. oralis/s. mitis/s. mitis bv2/s. infantis group and campylobacter concisus, granulicatella adiacens, bergeyella sp. hot322, neisseria subflava, and sr1 [g-1] sp. hot874 detection and reduced s. mutans, s. anginosus, n. mucosa, fusobacterium periodicum, f. nucleatum ss vincentii, and prevotella maculosa detection. this effect had disappeared 1 month after exposure was terminated. conclusions: l. reuteri consumption did not affect species richness but induced a shift in the oral microbiota composition. the biological relevance of this remains to be elucidated. trial registration: clinicaltrials.gov nct02311218.
TIHT== 
ABHT== 

PMID== 15117935
TI  == selection for high-level resistance by chronic triclosan exposure is not universal.
AB  == objectives: to investigate the effect of triclosan exposure on the antimicrobial  susceptibilities of numerically important dental bacteria. methods: a gradient plate technique was used to expose fusobacterium nucleatum, lactobacillus rhamnosus, neisseria subflava, porphyromonas gingivalis, actinomyces naeslundii,  prevotella nigrescens, streptococcus oralis, streptococcus sanguis, streptococcus mutans and veillonella dispar repeatedly to escalating, sublethal concentrations  of triclosan. escherichia coli atcc 8739 was included as an organism showing the  triclosan resistance development trait. mic values towards chlorhexidine, metronidazole and tetracycline were determined before and after biocide exposure. results: n. subflava, pr. nigrescens po. gingivalis and e. coli were highly susceptible to triclosan (mic range 0.1-3.9 mg/l), whereas the lactobacillus and  s. mutans were less susceptible (mic range 15.6-20.8 mg/l). triclosan exposure resulted in a highly significant ( approximately 400-fold) reduction in triclosan susceptibility (p < 0.01) for the positive control e. coli, although its mics towards chlorhexidine, metronidazole and tetracycline were not significantly altered. minor ( approximately two-fold) decreases in triclosan susceptibility (mic) occurred for pr. nigrescens and in s. sanguis and s. oralis (mbc). mean changes in susceptibilities (mic and mbc) of the oral species to chlorhexidine, metronidazole and tetracycline did not exceed two-fold, although chlorhexidine mbcs for s. sanguis were markedly, but transiently, increased. conclusions: these data fail to demonstrate biologically significant drug resistance in triclosan-exposed bacteria and suggest that markedly decreased triclosan susceptibility, although confirmed for e. coli, is not a universal phenomenon. other bacteria possibly possess more susceptible targets than fabi that are highly conserved, which may govern triclosan activity.
TIHT== 
ABHT== 

PMID== 12902270
TI  == effects of a chlorhexidine gluconate-containing mouthwash on the vitality and antimicrobial susceptibility of in vitro oral bacterial ecosystems.
AB  == oral bacterial microcosms, established using saliva inocula from three individuals, were maintained under a feast-famine regime within constant-depth film fermenters. steady-state communities were exposed four times daily, postfeeding, to a chlorhexidine (chx) gluconate-containing mouthwash (chxm) diluted to 0.06% (wt/vol) antimicrobial content. the microcosms were characterized by heterotrophic plate counts and pcr-denaturing gradient gel electrophoresis (dgge). chxm caused significant decreases in both total anaerobe  and total aerobe/facultative anaerobe counts (p < 0.05), together with lesser decreases in gram-negative anaerobes. the degree of streptococcal and actinomycete inhibition varied considerably among individuals. dgge showed that chxm exposure caused considerable decreases in microbial diversity, including marked reductions in prevotella sp. and selenomonas infelix. pure-culture studies of 10 oral bacteria (eight genera) showed that actinomyces naeslundii, veillonella dispar, prevotella nigrescens, and the streptococci were highly susceptible to chx, while lactobacillus rhamnosus, fusobacterium nucleatum, and neisseria subflava were the least susceptible. determination of the mics of triclosan, chx, erythromycin, penicillin v, vancomycin, and metronidazole for microcosm isolates, before and after 5 days of chxm exposure, showed that chxm exposure altered the distribution of isolates toward those that were less susceptible to chx (p < 0.05). changes in susceptibility distributions for the other test agents were not statistically significant. in conclusion, population changes in plaque microcosms following repeated exposure to chxm represented an inhibition of the most susceptible flora with a clonal expansion of less susceptible species.
TIHT== 
ABHT== 

PMID== 11054158
TI  == the formation of mixed culture biofilms of oral species along a gradient of shear stress.
AB  == a chemostat mixed culture system was used to produce two distinct ecological states, state-1 (caries-like microcosm) and state-2 (periodontal-like microcosm). eleven bacterial species (streptococcus gordonii, strep. mitis i, strep. mutans,  strep. oralis, actinomyces naeslundii, lactobacillus casei, neisseria subflava, fusobacterium nucleatum, porphyromonas gingivalis, prevotella nigrescens, veillonella dispar) were used to inoculate the planktonic system. a flow cell, designed to produce convergent flow with increasing shear stress, was attached to the chemostat system, and the resultant biofilms developed from the state-1 and state-2 microcosms along the shear stress gradient were examined and compared using image analysis and viable counts. the biofilm produced from state-1 showed  a lower shear stress tolerance (0.146 pa) than the state-2 biofilm (0.236 pa). the biofilm compositions did not vary along the gradient of shear stress and were dependent on the initial inoculum conditions. gram-positive species were predominant in the state-1 biofilm, while gram-negative species were predominant  in state-2.
TIHT== 
ABHT== 

PMID== 9745120
TI  == analysis of ph-driven disruption of oral microbial communities in vitro.
AB  == previously, a mixed culture chemostat system was used to demonstrate that the ph  generated from carbohydrate metabolism, rather than carbohydrate availability per se, was responsible for the shifts observed in the oral microflora which are associated with high carbohydrate diets and the development of dental caries. the aim of this study was to determine more accurately the microbially generated ph at which such shifts occurred. nine oral bacteria were grown in three independent chemostats, and pulsed with glucose on 10 consecutive days. in one chemostat, ph  control was discontinued for 6 h, and the ph fall was restricted to a minimum value of ph 5.5; the ph fall was arrested in the other two chemostats at either ph 5. 0, or at ph 4.5. when the ph was allowed to fall, the numbers and proportions of streptococcus mutans and lactobacillus rhamnosus increased; this increase was directly related to the magnitude of the ph fall. veillonella dispar was the most numerous organism following all glucose pulsing regimes, especially  at low ph. the increase in proportions of acidogenic bacteria was accompanied by  a fall in the proportions of acid-sensitive species (fusobacterium nucleatum, prevotella nigrescens, streptococcus gordonii and streptococcus oralis). the counts of these species were relatively stable between ph 5.5 and 4.5, but were markedly reduced when the ph fell below ph 4.5; neisseria subflava could not persist in the culture at ph 4.5 or below. the data suggest that the disruption of communities associated with glucose metabolism and low ph can be explained in  terms of a two-stage process. a fall in ph to a value between ph 5.5 and 4.5 may  allow the enrichment of potentially cariogenic species, whilst permitting species associated with health to remain relatively unaffected. a further reduction in ph (<ph 4.5) may not only enhance the competitiveness of odontopathogens, but inhibit the growth and metabolism of non-caries-associated species. the results also indicate that species other that mutans streptococci or lactobacilli are competitive at ph values low enough to demineralise enamel, and thus suggest that a broader range of micro-organisms may be associated with caries initiation.
TIHT== 
ABHT== 

PMID== 8868438
TI  == development of a steady-state oral microbial biofilm community using the constant-depth film fermenter.
AB  == the complexity of biofilm communities like dental plaque suggests that laboratory model biofilm growth systems may help to understand their structure and function. this study describes the use of a constant-depth film fermenter (cdff) to investigate biofilm formation by a nine-membered community of oral bacteria. the  community was grown to steady state in a chemostat incubated anaerobically. the chemostat output was fed into the cdff incubated aerobically. viable counts for each species from the chemostat and the cdff at steady state showed major differences; however, all nine organisms were present under both conditions. there was evidence of succession during biofilm formation with obligately anaerobic species only establishing after several days. a steady-state biofilm community was achieved which remained stable over time. electron microscopy showed evidence of spatial differentiation with what appeared to be neisseria subflava dominant near the upper surface and fusobacterium nucleatum largely confined to the middle portion.
TIHT== 
ABHT== 

PMID== 8868437
TI  == effect of oxygen, inoculum composition and flow rate on development of mixed-culture oral biofilms.
AB  == the effect of aeration on the development of a defined biofilm consortium of oral bacteria was investigated in a two-stage chemostat system. an inoculum comprising 10 species, including both facultatively anaerobic and obligately anaerobic bacteria, and species associated with oral health and disease, was inoculated into an anaerobic first-stage chemostat vessel. the effluent from this chemostat  was linked to an aerated [200 ml co2/air (5:95, v/v) min-1] second-stage vessel,  in which removable hydroxyapatite discs were inserted to allow biofilm formation. comparisons were made of planktonic and biofilm communities in the aerated second-stage vessel by means of viable counts. both planktonic and early biofilm  communities were dominated by neisseria subflava, comprising > 40% of total c.f.u. in the fluid phase, and > 80% of c.f.u. in 2 h biofilms. obligate anaerobes persisted in this mixed culture, and succession in biofilms led them to predominate only after 7 d. despite the continuous addition of air, the dissolved oxygen tension (do2) within the culture remained low (< 5% of air saturation), and the redox potential (eh) was -275 mv. in order to assess the significance of  the presence of n. subflava in community development, a subsequent experiment omitted this aerobe from the inoculum, to produce a nine-species culture. the planktonic phase was predominated by three streptococcal species, prevotella nigrescens and fusobacterium nucleatum. biofilms again underwent successional changes, with anaerobes increasing in proportion with time. in contrast to the culture including n. subflava, do2 was 50-60% of air saturation, and the eh was +50 mv. in the final experiment, the rate of addition of first-stage culture was  reduced to 1/10 of that in the previous experiment, in order to determine whether anaerobes were growing, rather than merely persisting in the aerated culture. the data for the planktonic phase indicated that the anaerobes were growing in aerated (do2 40-50%, eh +100 mv) conditions. once again, anaerobes increased in proportion in older biofilms. the study indicates that mixed cultures can protect obligate anaerobes from the toxic effects of oxygen, both in the biofilm and planktonic modes of growth.
TIHT== 
ABHT== 

