@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 24314107
TI  == physical impaction injury effects on bacterial cells during spread plating influenced by cell characteristics of the organisms.
AB  == aims: to understand the factors that contribute to the variations in colony-forming units (cfu) in different bacteria during spread plating. methods and results: employing a mix culture of vegetative cells of ten organisms varying in cell characteristics (gram reaction, cell shape and cell size), spread plating to the extent of just drying the agar surface (50-60 s) was tested in comparison  with the alternate spotting-and-tilt-spreading (sats) approach where 100 mul inoculum was distributed by mere tilting of plate after spotting as 20-25 microdrops. the former imparted a significant reduction in cfu by 20% over the spreader-independent sats approach. extending the testing to single organisms, gram-negative proteobacteria with relatively larger cells (escherichia, enterobacter, agrobacterium, ralstonia, pantoea, pseudomonas and sphingomonas spp.) showed significant cfu reduction with spread plating except for slow-growing methylobacterium sp., while those with small rods (xenophilus sp.) and cocci (acinetobacter sp.) were less affected. among gram-positive nonspore formers, staphylococcus epidermidis showed significant cfu reduction while staphylococcus haemolyticus and actinobacteria (microbacterium, cellulosimicrobium and brachybacterium spp.) with small rods/cocci were unaffected. vegetative cells of bacillus pumilus and b. subtilis were generally unaffected while others with larger rods (b. thuringiensis, brevibacillus, lysinibacillus and paenibacillus spp.) were significantly affected. a simulated plating study coupled with live-dead bacterial staining endorsed the chances of cell disruption with spreader impaction in afflicted organisms. conclusions: significant reduction in cfu could occur during spread plating due to physical impaction injury to bacterial cells depending on the spreader usage and the variable effects on different organisms are determined by gram reaction, cell size and cell shape. the inoculum spreader could impart physical disruption of vegetative cells against a hard surface. significance and impact of study: possibility of cfu reduction in sensitive organisms and the skewed selection of hardier organisms during spread plating, and the recommendation of sats as an easier and safer alternative for cfu enumerations.
TIHT== 
ABHT== 

