@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25104766
TI  == screening of lactobacillus strains of domestic goose origin against bacterial poultry pathogens for use as probiotics.
AB  == lactobacilli are natural inhabitants of human and animal mucous membranes, including the avian gastrointestinal tract. recently, increasing attention has been given to their probiotic, health-promoting capacities, among which their antagonistic potential against pathogens plays a key role. a study was conducted  to evaluate probiotic properties of lactobacillus strains isolated from feces or  cloacae of domestic geese. among the 104 examined isolates, previously identified to the species level by whole-cell matrix-assisted laser desorption/ionization time-of-flight mass spectrometry and analysis of 16s-23s regions of rdna, dominated lactobacillus salivarius (35%), followed by lactobacillus johnsonii (18%) and lactobacillus ingluviei (11%). all lactobacilli were screened for antimicrobial activity toward salmonella enteritidis, escherichia coli, clostridium perfringens, staphylococcus aureus, pasteurella multocida, and riemerella anatipestifer using the agar slab method and the well diffusion method. lactobacillus salivarius and lactobacillus plantarum exhibited particularly strong antagonism toward all of the indicator strains. in the agar slab method, the highest sensitivity to lactobacillus was observed in r. anatipestifer and p. multocida, and the lowest in e. coli and s. aureus. the ability to produce h(2)o(2)was exhibited by 92% of isolates, but there was no correlation between the rate of production of this reactive oxygen species and the antimicrobial activity of lactobacillus sp. all lactobacilli showed resistance to ph 3.0 and 3.5 and to 2% bile. the data demonstrate that lactobacillus isolates from geese may have probiotic potential in reducing bacterial infections. the antibacterial activity of the selected lactobacilli is  mainly due to lactic acid production by these bacteria. the selected lactobacillus strains that strongly inhibited the growth of pathogenic bacteria,  and were also resistant to low ph and bile salts, can potentially restore the balance of intestinal microflora in geese and could offer an alternative to antibiotic therapy.
TIHT== 
ABHT== 

PMID== 24045008
TI  == new derivatives of salicylamides: preparation and antimicrobial activity against  various bacterial species.
AB  == three series of salicylanilides, esters of n-phenylsalicylamides and 2-hydroxy-n-[1-(2-hydroxyphenylamino)-1-oxoalkan-2-yl]benzamides, in total thirty target compounds were synthesized and characterized. the compounds were evaluated against seven bacterial and three mycobacterial strains. the antimicrobial activities of some compounds were comparable or higher than the standards ampicillin, ciprofloxacin or isoniazid. derivatives 3f demonstrated high biological activity against staphylococcus aureus (0.03mumol/l), mycobacterium marinum (0.40mumol/l) and mycobacterium kansasii (1.58mumol/l), 3g shows activity against clostridium perfringens (0.03mumol/l) and bacillus cereus (0.09mumol/l),  3h against pasteurella multocida (0.03mumol/l) and m. kansasii (0.43mumol/l), 3i  against methicillin-resistant s. aureus and b. cereus (0.03mumol/l). the structure-activity relationships are discussed for all the compounds.
TIHT== 
ABHT== 

PMID== 23571324
TI  == development and application of a multiplex pcr assay for rapid detection of 4 major bacterial pathogens in ducks.
AB  == infections with pasteurella multocida, salmonella enterica, riemerella anatipestifer, and escherichia coli result in high morbidity and mortality, which cause significant economic loss in the poultry industry. it can be difficult to distinguish these pathogens based on clinical signs because these pathogens can cause similar clinical signs and coinfections can occur. thus, rapid and sensitive detection of these 4 major bacterial pathogens are important in ducks.  the aim of this study was to develop a multiplex pcr (mpcr) assay for simultaneously detecting and identifying these 4 pathogenic bacteria in a single  tube reaction. the target genes used were kmt1 of p. multocida, the invasion protein gene of s. enterica, 16s rdna of r. anatipestifer, and the alkaline phosphatase gene of e. coli. the detection limit of the assay for all bacterial dna was 10 pg. the mpcr did not produce any nonspecific amplification products when tested against other related pathogens, including staphylococcus aureus, streptococcus pyogenes, clostridium perfringens, mycoplasma gallinarum, mycoplasma synoviae, and mycoplasma gallisepticum, which can also infect ducks. we applied mpcr to field samples, and the results were the same as the single pcr results. these results suggest that mpcr for the 4 bacteria is a useful and rapid technique to apply to field samples.
TIHT== 
ABHT== 

PMID== 17615154
TI  == nucleoside analogues are activated by bacterial deoxyribonucleoside kinases in a  species-specific manner.
AB  == objectives: to investigate the bactericidal activity of antiviral and anticancer  nucleoside analogues against a variety of pathogenic bacteria and characterize the activating enzymes, deoxyribonucleoside kinases (dnks). methods: several fda-approved nucleoside analogue drugs were screened for their potential bactericidal activity against several clinical bacterial isolates and type strains. we identified and subcloned the genes coding for putative deoxyribonucleoside kinases in escherichia coli, pasteurella multocida, salmonella enterica, yersinia enterocolitica, bacillus cereus, clostridium perfringens and listeria monocytogenes. these genes were tested for their ability to increase the susceptibility of a dnk-deficient e. coli strain to various analogues. we overexpressed, purified and characterized the substrate specificity and kinetic properties of the recombinant enzymes from s. enterica and b. cereus. results: the tested gram-negative bacteria were susceptible to 3'-azido-3'-deoxythymidine (azt) in the concentration range 0.032-31.6 microm except for a single e. coli isolate and two pseudomonas aeruginosa isolates which were resistant to the tested azt concentrations. purified recombinant s. enterica thymidine kinase phosphorylated azt efficiently with a km of 73.3 microm and k(cat)/km of 6.6 x 10(4) s(-1) m(-1) and is the activator of this drug in vivo. 2',2'-difluoro-2'-deoxycytidine (gemcitabine) was a potent antibiotic against gram-positive bacteria in the concentration range between 0.001 and 1.0 microm. the b. cereus deoxyadenosine kinase had a km for gemcitabine of 33.5 microm and k(cat)/km of 5.1 x 10(3) s(-1) m(-1) and activates gemcitabine in vivo. s. enterica and b. cereus are now amongst the first bacteria with a completely characterized set of dnk enzymes. conclusions: bacterial dnks efficiently activate nucleoside analogues in a species-specific manner. therefore, nucleoside analogues have a potential to be employed as antibiotics in the fight against emerging multiresistant bacteria.
TIHT== 
ABHT== 

PMID== 2752934
TI  == [the "diseased" or "dead" guillemots (uria aalge), three-toed gulls (rissa tridactyla), silver gulls (larus argentatus) and laughing gulls (larus ridibundus) found in the area of the german bay, 1982-1985].
AB  == between 1982 and 1985 the cadavers of 50 guillemots (uria aalge), 41 kittiwakes (rissa tridactyla), 26 herring gulls (larus argentatus) and 34 black-headed gulls (larus ridibundus) were examined pathological, bacteriological and virological. the probable cause of death was established. parasitosis were particularly prevalent in herring gulls (49%), where the main infection--as in black-headed gulls--was with cestoides. in kittiwakes and guillemots mainly spiruroideae were  recorded. the commonest bacterium isolated in organs and intestinal tract was escherichia coli, followed by aeromonas hydrophila and clostridium perfringens. salmonella were found in the organs of 5% and in the intestinal tract of 3% of the birds. the species of salmonella most frequently isolated was salmonella typhimurium varieties copenhagen. also recorded were yersinia intermedia serovar  0:17 (1x), pseudomonas spp. (2x), bacteria of the haemophilus-pasteurella-actinobacillus group (1x), pasteurella multocida (2x), moraxella septicaemiae (1x), campylobacter spec. (1x), mycoplasma spec. (6x), dnase positive staphylococcus spec. (4x) and streptococcus spec. (6x). less in evidence among the birds examined were fungus diseases with aspergillus spec. (4x) and blastomyces spec. (4x). as for viruses one guillemot was found to have an adenovirus and another one to have a paramyxovirus. from one of the herring gulls there also was isolated a paramyxovirus, from a second one to a reovirus. three other species isolated have get to be identified. the chief cause of sickness and death in the guillemots was oil-contamination. the majority of the examined kittiwakes and herring gulls were victims of pathogenic agents. many of  the black-headed gulls died through traumata as gunshots or road traffic etc. in  order to establish the causes of sickness and death in seabirds and to ascertain  the importance of the various species as possible carriers of infectious diseases, a systematic series of investigation will be necessary. without this it will not be possible to assess their epidemiological relevance for other wild birds, domestic poultry and humans.
TIHT== 
ABHT== 

PMID== 3345248
TI  == characterization of the dermal lesions induced by a purified protein from toxigenic pasteurella multocida.
AB  == the dermonecrotic effect of purified pasteurella multocida toxin (pmt) was studied sequentially in guinea pigs and rats. the skin reaction was initially an  acute inflammatory reaction, with edema and emigration of neutrophils and a few eosinophils and diapedesis of some erythrocytes. four hours after intracutaneous  injection the vessels were congested and thrombocytes were focally attached to the endothelial wall. twenty-four h after the injection the inflammatory reaction appeared more severe and venules and arterioles were thrombosed. necrotic changes were seen in hair follicles and in striated muscle fibers. crude extracts from p. multocida and clostridium perfringens injected intracutaneously into guinea pigs  induced skin lesions qualitatively similar to the lesions induced by the purified pmt, indicating that dermonecrotic bacterial toxins may share similar biochemical properties.
TIHT== 
ABHT== 

PMID== 4124474
TI  == [serological studies on bacterial neuraminidases with special reference to the neuraminidase of pasteurella multocida].
AB  == 
TIHT== 
ABHT== 

