@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 22491987
TI  == antimicrobial susceptibility of microflora from ovine cheese.
AB  == strains identified in ovine cheese and bryndza by matrix-assisted laser desorption/ionization time-of-flight analysis belonged to ten species of non-enterococcal lactic acid bacteria and included lactobacillus casei/lactobacillus paracasei, lactobacillus plantarum, lactobacillus rhamnosus,  lactobacillus helveticus, lactobacillus delbrueckii, lactobacillus fermentum, lactobacillus brevis, lactococcus lactis, pediococcus pentosaceus and pediococcus acidilactici. the susceptibility toward antibiotics was determined in lactobacilli, lactococci and pediococci and also in escherichia coli for comparison. analysis of l. fermentum and pediococci revealed the presence of non-wild-type epidemiological cut-offs in streptomycin, clindamycin or gentamicin. e. coli were resistant to ampicillin, tetracycline, enrofloxacin and  florfenicol. no extended spectrum beta-lactamases were detected.
TIHT== 
ABHT== 

PMID== 21943677
TI  == the spatial distribution of bacteria in grana-cheese during ripening.
AB  == the microbial composition and its spatial distribution of grana trentino, a hard  parmesan-like cheese, was determined, from vat milk to cheese. after cutting along the vertical axis of the cheese wheels, three layers were sampled diagonally across the cheese: under the cheese rind, an intermediate section and  the cheese core. after two different ripening periods (9 and 18 months), the cheese samples were analysed using traditional culture dependent and culture independent methods. milk samples were dominated by mesophilic and psychrophilic  bacterial counts. thermophilic bacteria (lactobacillus helveticus) were found in  high amounts in cooked whey and natural whey starter cultures. after 9 months of  ripening, lactic acid bacteria (lab) counts were higher than those after 18 months. furthermore, the lab numbers in the cheese core was lower than those under the rind or in the intermediate section. the main lab species isolated from milk (lactococcus lactis, pediococcus pentosaceus, streptococcus uberis and lactococcus garvieae) were not found in the corresponding cheeses. some differences were observed in the species composition among the three cheese sections. microbiota under the rind and in the intermediate section was similar and dominated by lactobacillus paracasei and lactobacillus rhamnosus. the core, after 18 months of ripening, was characterized by a total absence of lab. in each sample, all lab were genotypically grouped and the different biotypes were subjected to several technological tests indicating that some non-starter lab (nslab) displayed technological features that are favorable for the production of grana trentino cheese.
TIHT== 
ABHT== 

PMID== 17953562
TI  == redox potential to discriminate among species of lactic acid bacteria.
AB  == aims: to verify to what degree reducing capacity is a characterizing parameter of a species, and of the strains themselves within a given species, of lactic acid bacteria. methods and results: eighty-eight strains belonging to 10 species of lactic acid bacteria (lab) isolated from traditional italian cheeses were studied for their reduction activity: enterococcus faecalis, enterococcus faecium, enterococcus durans, streptococcus thermophilus, lactococcus lactis ssp. lactis,  lactobacillus paracasei ssp. paracasei, lactobacillus plantarum, lactobacillus delbrueckii ssp. bulgaricus, lactobacillus helveticus and pediococcus pentosaceus. it was observed that the lactococci reached minimum redox potential  before the lactobacilli. the reduction rate of enterococcus spp. and l. lactis ssp. lactis was higher than that of the streptococci and lactobacillus spp. all the p. pentosaceus strains had poor reduction activity compared with the other species. conclusions: the evolution of the redox potential in milk over a time span of 24 h has been found to be a parameter that characterizes a species: the different courses corresponding to the species in question are clearly evident, and interesting differences can also be noted within the same species. significance and impact of the study: the reduction aptitude of strains might be  used to select and adapt appropriate strains for use as starters for dairy products.
TIHT== 
ABHT== 

PMID== 15941626
TI  == use of hydrolysates from atlantic cod (gadus morhua l.) viscera as a complex nitrogen source for lactic acid bacteria.
AB  == hydrolysates of cod viscera were tested as an alternative to commonly used complex nitrogen sources (peptones and/or extracts) for the type strains of the lactic acid bacteria lactococcus lactis, lactobacillus acidophilus, lactobacillus helveticus, lactobacillus casei, lactobacillus sakei and pediococcus pentosaceus. comparative studies with mrs-like media containing different nitrogen sources showed that all the fish hydrolysates performed equally well or better than commercial extracts/peptones for all selected lactic acid bacteria.
TIHT== 
ABHT== 

PMID== 12631191
TI  == autolytic activity and pediocin-induced lysis in pediococcus acidilactici and pediococcus pentosaceus strains.
AB  == aims: to evaluate the autolytic phenotype of pediococcus acidilactici and p. pentosaceus, the peptidoglycan hydrolases content and the effect of pediocin ach/pa-1 and autolysins on cell lysis. methods and results: the autolytic phenotype of pediococcus strains was evaluated under starvation conditions in potassium phosphate buffer. the strains tested showed an extent of autolysis ranging between 40 and 90% after 48 h of starvation at 37 degrees c. peptidoglycan hydrolase content was evaluated by renaturing sodium dodecyl sulphate-polyacrylamide gel electrophoresis (sds-page) using cells of micrococcus lysodeikticus as a target for the enzymatic activity and a major activity band migrating at about 116 kda was detected. additional secondary lytic bands migrating in a range of molecular weight between 45 and 110 kda were also detected. the lytic activity, evaluated in the presence of different chemicals, was retained in 15 mm cacl2 and in a range of ph between 5 and 9.5 but was strongly reduced in presence of 8% nacl and in the presence of protease inhibitors. the substrate specificity of peptidoglycan hydrolases of pediococcus  strains was evaluated in renaturing sds-page incorporating cells of different bacterial species. lytic activity was detected against cells of lactococcus lactis subsp. lactis, l. delbrueckii subsp. bulgaricus, lactobacillus helveticus  and listeria monocytogenes. the interaction between pediocin ach/pa-1 and autolysis was evaluated and a relevant effect of bacteriocin in cell-induced lysis was observed. conclusions: the autolytic phenotype is widely distributed among p. acidilactici and p. pentosaceus and the rate of autolysis is high in the majority of the analysed strains. several autolytic bands, detected by renaturing sds-page, retained their activity against several lactic acid bacteria and l. monocytogenes. significance and impact of the study: the characterization of the  autolytic phenotype of pediococcus acidilactici and p. pentosaceus strains should expand the knowledge of their role in fermentation processes where these species  occur as primary or secondary bacterial population.
TIHT== 
ABHT== 

PMID== 9767713
TI  == conservation of the major cold shock protein in lactic acid bacteria.
AB  == primers designed from consensus regions of the major cold shock gene of different bacterial species were used in pcr amplification of lactic acid bacteria (lab). an appropriately-sized pcr product was obtained from lactococcus lactis subsp. lactis ll43-1 and mg1363; lactococcus lactis subsp. cremoris lc10-1, lc11-1, and  lc12-1; streptococcus thermophilus st1-1; enterococcus faecalis ef1-1; lactobacillus acidophilus la1-1; lactobacillus helveticus lh1-1; pediococcus pentosaceus pp1-1; and bifidobacterium animalis ba1-1. the pcr products were cloned and sequenced. the deduced amino acid sequences displayed high sequence similarity with the major cold shock proteins of escherichia coli and bacillus subtilis and the human y-box factor. the amino acid residues of the cold shock domain implicated in nucleic acid binding in several unrelated species were also  highly conserved in the lab strains. it is possible, therefore, that this protein in lab may also act as a transcriptional enhancer to other cold shock genes and/or act as an rna chaperone unwinding tightly folded rna molecules.
TIHT== 
ABHT== 

PMID== 9175562
TI  == identification of a cold shock gene in lactic acid bacteria and the effect of cold shock on cryotolerance.
AB  == when lactic acid bacterial cultures were frozen at -20 degrees c for 24 h, the cell viability decreased drastically, but when they were cold shocked at 10 degrees c for 2 h prior to freezing, viability improved significantly for the lactococcus lactis subsp. lactis strains (25-37%) and pediococcus pentosaceus po2 (18%), but not for the lactococcus lactis subsp. cremoris strains tested or for one strain of lactobacillus helveticus lb1 and streptococcus thermophilus ts2. when the period for cold shock was extended to 5 h, the viability increased even  further for those strains that displayed cold shock cryotolerance. use of degenerate pcr primers based on the major cold shock protein (csp) of both escherichia coli and bacillus subtilis resulted in pcr products from all strains  tested. the pcr product from lactococcus lactis ssp. lactis m474 was cloned and sequenced, and the deduced amino acid sequence displayed a high sequence similarity to other csp's. use of pcr primers based on the m474 sequence resulted in pcr products being produced only from the lactococcal strains studied and not  from the lactobacillus helveticus, streptococcus thermophilus, or pediococcus pentosaceus strains tested.
TIHT== 
ABHT== 

PMID== 16535280
TI  == development and characterization of lactose-positive pediococcus species for milk fermentation.
AB  == bacteriophages against streptococcus thermophilus are a growing problem in the italian cheese industry. one possible control method involves replacing s. thermophilus in mozzarella starter blends with lactic acid bacteria from a different genus or species. in this study, we evaluated lactose-positive pediococci for this application. because we could not identify any commercially available pediococci with fast acid-producing ability in milk, we transformed pediococcus pentosaceus atcc 25744, p. pentosaceus atcc 25745, and pediococcus acidilactici atcc 12697 by electroporation with ppn-1, a 35-kb lactococcus lactis lactose plasmid. transformants of p. pentosaceus atcc 25745 and p. acidilactici atcc 12697 were then used to examine lactose-positive pediococci for properties related to milk fermentation. both transformants rapidly produced acid and efficiently retained ppn-1 in lactose broth, and neither bacterium was attacked by bacteriophages in whey collected from commercial cheese facilities. paired starter combinations of pediococcus spp. and lactobacillus helveticus lh100 exhibited synergistic ph reduction in milk, and small-scale cheese trials showed  that these cultures could be used to manufacture part-skim mozzarella cheese. results demonstrate that lactose-positive pediococci have potential as replacement cocci for s. thermophilus in italian cheese starter blends and may facilitate development of new strain rotation schemes to combat s. thermophilus bacteriophage problems in mozzarella cheese plants.
TIHT== 
ABHT== 

PMID== 23194733
TI  == a phylogenetic analysis of lactobacilli, pediococcus pentosaceus and leuconostoc  mesenteroides.
AB  == lactobacillus acidophilus, l. helveticus, l. lactis, l. brevis, l. plantarum, l.  ruminis, l. casei, l. bifermentans, l. viridescens, l. fermentum, pediococcus pentosaceus and leuconostoc mesenteroides have been characterized by oligonucleotide cataloguing of their 16 s ribosomal rnas. all lactobacillus species investigated together with p. pentosaceus and l. mesenteroides form a phylogenetically coherent and ancient group. l. acidophilus and l. helveticus is  the only closely related pair of species; all other species are only remotely related among each other, indicating that they are well-defined species. lactobacillus, together with streptococcus and bacillus, constitute a super-cluster within the 'clostridium' sub-branch of gram-positive eubacteria showing a low guanine plus cytosine content of their deoxyribonucleic acid.
TIHT== 
ABHT== 

