@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 16887680
TI  == an in vitro time-kill assessment of linezolid and anaerobic bacteria.
AB  == linezolid is a novel oxazolidinone antibacterial agent active against staphylococci (including methicillin-resistant strains), enterococci (including vancomycin-resistant strains), streptococci (including penicillin-intermediate and -resistant streptococcus pneumoniae), and other aerobic and facultative bacteria. the agent has also demonstrated activity against a broad spectrum of gram-positive and gram-negative anaerobic bacteria. previous time-kill assessments have shown linezolid to be generally bacteriostatic against staphylococci and enterococci, and bactericidal against streptococci. in this study, an anaerobic glovebox technique was employed to conduct time-kill assessments for four strains of anaerobic gram-positive, and seven strains of anaerobic gram-negative bacteria. the time-kill experiment was performed using anaerobe broth medium. the drugs were tested at four-fold the minimum inhibitory  concentration (mic), or at the higher concentration of 8mg/l for linezolid, 2mg/l for clindamycin, and 8mg/l for metronidazole. samples for viable count were taken at 0, 6, and 24h, and plated using the bioscience international autospiral dw. exposure of samples to the aerobic environment during plating was held to less than 30min. plates were counted after a 48h anaerobic incubation (37 degrees c).  the species tested included bacteroides fragilis (2), b. distasonis, b. thetaiotaomicron, fusobacterium nucleatum, f. varium, prevotella melaninogenica,  clostridium perfringens, eubacterium lentum and peptostreptococcus anaerobius (2). the activity of linezolid was compared to that of metronidazole and clindamycin, two standard anti-anaerobe agents. as expected, the control agents were very active in these assays. metronidazole yielded log(10)cfu/ml reductions  of 3.0 or greater for nine of ten strains; clindamycin yielded log(10)cfu/ml reductions of 2.0 or greater for six of 11 strains, and 3.0 or greater for three  strains. linezolid also produced significant in vitro killing in this model achieving log(10)cfu/ml reductions of 2.0 or greater for six of 11 strains, and 3.0 or greater for four strains. the profile of activity was similar to that of clindamycin indicating that additional developmental studies of linezolid with anaerobic bacteria are warranted.
TIHT== 
ABHT== 

PMID== 12604521
TI  == activities of garenoxacin (bms-284756) and other agents against anaerobic clinical isolates.
AB  == a total of 590 clinical isolates consisting of 33 species of both gram-positive and gram-negative anaerobes were collected from nine centers in the chicago area  in 1998-1999. the largest number of isolates (330 isolates, 56%) belonged to the  bacteroides group. isolates were tested by agar dilution against garenoxacin (bms-284756, t-3811 me), trovafloxacin, moxifloxacin, clindamycin, imipenem, piperacillin-tazobactam, and cefoxitin. all but one species (2% of bacteroides vulgatus isolates) were fully susceptible to piperacillin-tazobactam and imipenem. a number of species were resistant to clindamycin. among the fluoroquinolones, garenoxacin and trovafloxacin had an mic at which 90% of the isolates tested were inhibited of <4 micro g/ml for all but two species (fusobacterium mortiferum/varium and peptostreptococcus anaerobius).
TIHT== 
ABHT== 

PMID== 12384389
TI  == in vitro activities of faropenem against 579 strains of anaerobic bacteria.
AB  == the activity of faropenem, a new oral penem, was tested against 579 strains of anaerobic bacteria by using the nccls-approved reference method. drugs tested included amoxicillin-clavulanate, cefoxitin, clindamycin, faropenem, imipenem, and metronidazole. of the 176 strains of bacteroides fragilis group isolates tested, two isolates had faropenem mics of 64 micro g/ml and imipenem mics of >32 micro g/ml. faropenem had an mic of 16 micro g/ml for an additional isolate of b. fragilis; this strain was sensitive to imipenem (mic of 1 micro g/ml). both faropenem and imipenem had mics of < or=4 micro g/ml for all isolates of bacteroides capillosus (10 isolates), bacteroides splanchnicus (13 isolates), bacteroides ureolyticus (11 isolates), bilophila wadsworthia (11 isolates), porphyromonas species (42 isolates), prevotella species (78 isolates), campylobacter species (25 isolates), sutterella wadsworthensis (11 isolates), fusobacterium nucleatum (19 isolates), fusobacterium mortiferum/varium (20 isolates), and other fusobacterium species (9 isolates). faropenem and imipenem had mics of 16 to 32 micro g/ml for two strains of clostridium difficile; the mics for all other strains of clostridium tested (69 isolates) were < or =4 micro g/ml. faropenem had mics of 8 and 16 micro g/ml, respectively, for two strains of peptostreptococcus anaerobius (mics of imipenem were 2 micro g/ml). mics were < or =4 micro g/ml for all other strains of gram-positive anaerobic cocci (53 isolates) and non-spore-forming gram-positive rods (28 isolates). other results were as expected and reported in previous studies. no metronidazole resistance was seen in gram-negative anaerobes other than s. wadsworthensis (18% resistant); 63% of gram-positive non-spore-forming rods were resistant. some degree of clindamycin resistance was seen in most of the groups tested.
TIHT== 
ABHT== 

PMID== 10471570
TI  == in vitro activity of gemifloxacin (sb 265805) against anaerobes.
AB  == gemifloxacin mesylate (sb 265805), a new fluoronaphthyridone, was tested against  359 recent clinical anaerobic isolates by the national committee for clinical laboratory standards reference agar dilution method with supplemented brucella blood agar and an inoculum of 10(5) cfu/spot. comparative antimicrobials tested included trovafloxacin, levofloxacin, grepafloxacin, sparfloxacin, sitafloxacin (du-6859a), penicillin g, amoxicillin clavulanate, imipenem, cefoxitin, clindamycin, and metronidazole. the mic(50) and mic(90) (mics at which 50 and 90% of the isolates were inhibited) of gemifloxacin against various organisms (with the number of strains tested in parentheses) were as follows (in micrograms per milliliter): for bacteroides fragilis (28), 0.5 and 2; for bacteroides thetaiotaomicron (24), 1 and 16; for bacteroides caccae (12), 1 and 16; for bacteroides distasonis (12), 8 and >16; for bacteroides ovatus (12), 4 and >16; for bacteroides stercoris (12), 0.5 and 0.5; for bacteroides uniformis (12), 1 and 4; for bacteroides vulgatus (11), 4 and 4; for clostridium clostridioforme (15), 0.5 and 0.5; for clostridium difficile (15), 1 and >16; for clostridium innocuum (13), 0.125 and 2; for clostridium perfringens (13), 0.06 and 0.06; for  clostridium ramosum (14), 0.25 and 8; for fusobacterium nucleatum (12), 0.125 and 0.25; for fusobacterium necrophorum (11), 0.25 and 0.5; for fusobacterium varium  (13), 0.5 and 1; for fusobacterium spp. (12), 1 and 2; for peptostreptococcus anaerobius (13), 0.06 and 0.06; for peptostreptococcus asaccharolyticus (13), 0.125 and 0.125; for peptostreptococcus magnus (14), 0.03 and 0.03; for peptostreptococcus micros (12), 0.06 and 0.06; for peptostreptococcus prevotii (14), 0.06 and 0.25; for porphyromonas asaccharolytica (11), 0.125 and 0.125; for prevotella bivia (10), 8 and 16; for prevotella buccae (10), 2 and 2; for prevotella intermedia (10), 0.5 and 0.5; and for prevotella melaninogenica (11),  1 and 1. gemifloxacin mesylate (sb 265805) was 1 to 4 dilutions more active than  trovafloxacin against fusobacteria and peptostreptococci, and the two drugs were  equivalent against clostridia and p. asaccharolytica. gemifloxacin was equivalent to sitafloxacin (du 6859a) against peptostreptococci, c. perfringens, and c. ramosum, and sitafloxacin was 2 to 3 dilutions more active against fusobacteria.  sparfloxacin, grepafloxacin, and levofloxacin were generally less active than gemifloxacin against all anaerobes.
TIHT== 
ABHT== 

PMID== 8517721
TI  == in vitro activity of fk037, a new parenteral cephalosporin, against anaerobic bacteria.
AB  == the activity of fk037, a new parenteral cephalosporin, was compared with those of cefpirome, ceftazidime, and flomoxef against 322 recent clinical isolates of anaerobic bacteria. a fastidious facultative anaerobe, gardnerella vaginalis, was also studied. fk037 inhibited 90% of isolates of peptostreptococcus anaerobius, peptostreptococcus asaccharolyticus, clostridium perfringens, mobiluncus spp., g. vaginalis, and porphyromonas gingivalis at < or = 0.78 micrograms/ml. the mics of fk037 for 50 and 90% of bacteroides fragilis isolates were 25 and > 200 micrograms/ml, respectively; the activity of fk037 was comparable to those of cefpirome and ceftazidime but lower than that of flomoxef. the activity of fk037  against fusobacterium nucleatum, fusobacterium varium, and bilophila wadsworthia  decreased when inoculum size was increased from 10(6) to 10(8) cfu/ml. little influence of inoculum size on the activity of fk037 was observed for other isolates tested. medium ph affected the activity of fk037 against f. varium (mics at phs 5 and 7, 3.13 and 100 micrograms/ml, respectively) and bacteroides gracilis (mics at phs 5 and 7, 12.5 and 1.56 micrograms/ml, respectively) but not against other organisms tested. fk037 was less resistant than flomoxef to hydrolysis by beta-lactamase group 2e derived from b. fragilis gai 0558 and gai 10150.
TIHT== 
ABHT== 

PMID== 1271586
TI  == [antibacterial and bactericidal activity of tinidazole against anaerobic bacteria comparing with metronidazole (author's transl)].
AB  == antibacterial activity of tinidazole (1-2-(ethylsulfonyl)-2-methyl-5-nitroimidazole) against anaerobic bacteria including peptococcus, peptostreptococcus, eubacterium, propionibacterium, bacteroides and fusobacterium was studied by agar dilution method comparing with  metronidazole. in addition to this work, bactericidal effect of tinidazole and metronidazole against p. prevotii, b. fragilis ss. fragilis and f. varium was examined by quantitative culture method after incubation in gam broth containing  of 4 mic, 2 mic, 1 mic and 1/2 mic of both drugs against each of three strains for 1, 3, 6, 12 and 24 hours. all the strains of peptococcus and peptostreptococcus including p. anaerobius, p. saccharolyticus, p. prevotii and ps. anaerobius and others were susceptible to a concentration of 6.25 mcg/ml of this drug. a concentration of 3.13 mcg/ml inhibited all strains of bacteroides including b. fragilis ss. fragilis (12 strains), ss. vulgatus (5 strains), ss. thetaiotaomicron (4 strains) and ss. distasonis (2 strains). to this concentration all strains of fusobacterium including f. varium (20 strains), f. mortiferum (2 strains) and other fusobacterium sp. (5 strains) were susceptible.  on the contrary, propionibacterium acnes (6 strains) was resistant to 100 mcg/ml  or more of tinidazole and metronidazole. the antibacterial activity of tinidazole was stronger against bacteroides than that of metronidazole, while almost equal against peptococcus, peptostreptococcus, eubacterium and fusobacterium. tinidazole was bactericidal against f. varium in a concentration of 2 mic till 24 hours of incubation but did not show such an activity on b. fragilis ss. fragilis in same concentration even after 12 hours of incubation. on the other hand, metronidazole was bactericidal against b. fragilis ss. fragilis while was not against f. varium. against p. prevotii bactericidal activity of both drugs was similar. tinidazole as well as metronidazole is an excellent chemotherapeutic agent against anaerobic bacteria excluding propionibacterium acnes and bifidobacterium adolescentis.
TIHT== 
ABHT== 

