@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23060013
TI  == subgingival microflora in inflammatory bowel disease patients with untreated periodontitis.
AB  == objective: to analyze the subgingival microflora composition of inflammatory bowel disease (ibd) patients with untreated chronic periodontitis and compare them with systemically healthy controls also having untreated chronic periodontitis. method: thirty ibd patients [15 with crohn's disease (cd) and 15 with ulcerative colitis (uc)] and 15 control individuals participated in the study. all patients had been diagnosed with untreated chronic periodontitis. from every patient, subgingival plaque was collected from four gingivitis and four periodontitis sites with paper points. samples from the same category (gingivitis or periodontitis) in each patient were pooled together and stored at -70 degrees  c until analysis using a checkerboard dna-dna hybridization technique for 74 bacterial species. results: multiple-comparison analysis showed that the groups differed in bacterial counts for bacteroides ureolyticus, campylobacter gracilis, parvimonas micra, prevotella melaninogenica, peptostreptococcus anaerobius, staphylococcus aureus, streptococcus anginosus, streptococcus intermedius, streptococcus mitis, streptococcus mutans, and treponema denticola (p<0.001). cd  patients had significantly higher levels of these bacteria than uc patients either in gingivitis or in periodontitis sites (p<0.05). cd patients harbored higher levels of p. melaninogenica, s. aureus, s. anginosus, and s. mutans compared with controls both at gingivitis and at periodontitis sites (p<0.05). uc patients harbored higher levels of s. aureus (p=0.01) and p. anaerobius (p=0.05)  than controls only in gingivitis sites. conclusion: our study showed that even with similar clinical periodontal parameters, ibd patients harbor higher levels of bacteria that are related to opportunistic infections in inflamed subgingival  sites that might be harmful for the crucial microbe-host interaction.
TIHT== 
ABHT== 

PMID== 19819812
TI  == comparative evaluation of the antimicrobial efficacy of aloe vera tooth gel and two popular commercial toothpastes: an in vitro study.
AB  == aloe vera (aloe barbadensis miller) has been suggested for a wide variety of ailments but its use in dentistry is limited. this article reviews the uses of the plant and describes an in vitro investigation that compared the antimicrobial effectiveness of aloe vera tooth gel with two popular, commercially available dentifrices. the preliminary results showed that aloe vera tooth gel and the toothpastes were equally effective against candida albicans, streptococcus mutans, lactobacillus acidophilus, enterococcus faecalis, prevotella intermedia,  and peptostreptococcus anaerobius. aloe vera tooth gel demonstrated enhanced antibacterial effect against s. mitis.
TIHT== 
ABHT== 

PMID== 18775647
TI  == in vitro bactericidal activity of recombinant human beta-defensin-3 against pathogenic bacterial strains in human tooth root canal.
AB  == human beta-defensin-3 (hbd3), an endogenous antimicrobial peptide, has strong broad-spectrum antimicrobial activity. this study aimed to obtain recombinant hbd3 (rhbd3) and to test the hypothesis that the antimicrobial characteristics of hbd3 may offer an advantage over conventional medicine in reducing intracanal bacteria. genetic engineering was used to obtain active rhbd3 and analysis revealed that it exhibited a broad spectrum of antibacterial activity at low micromolar concentrations against not only staphylococcus aureus and escherichia  coli but also against some critical pathogenic microbes in infected root canals,  including fusobacterium nucleatum, prevotella melaninogenica, peptostreptococcus  anaerobius, streptococcus mutans, actinomyces naeslundii, enterococcus faecalis and candida albicans. in an in vitro antibacterial experiment, rhbd3 significantly eliminated pathogenic bacteria in root canals. the ratio of bacterial death was up to 98%. we conclude that hbd3 has the potential to eliminate bacteria effectively and rapidly in the local microenvironment of the root canal system and that it may contribute to successful endodontic treatment.
TIHT== 
ABHT== 

PMID== 17584471
TI  == production of antagonistic substance by eikenella corrodens isolated from the oral cavity of human beings with and without periodontal disease.
AB  == aims: antagonistic abilities may confer ecological advantages for micro-organisms in competitive ecosystems. however, reports regarding this phenomenon in eikenella corrodens are not available. methods and results: nineteen e. corrodens strains, isolated from the oral cavity of human beings without periodontal disease (n = 5) and with aggressive (n = 9) and chronic (n = 5) periodontitis, as well as a reference strain (e. corrodens atcc23834), were evaluated for antagonistic activity. the following indicators were used: porphyromonas gingivalis fdc381, prevotella intermedia atcc25611, actinomyces israelii atcc12102, eubacterium lentum atcc25559, peptostreptococcus anaerobius atcc27337, actinobacillus actinomycetemcomitans fdcy4, fusobacterium nucleatum atcc10953, streptococcus sanguinis atcc10557, streptococcus uberis atcc9927, streptococcus mutans im/ufrj, staphylococcus aureus atcc33591 and candida albicans atcc18804. all the strains showed antagonism against at least one of the indicator strains.  this phenomenon was more frequently observed for strains isolated from patients with chronic periodontitis (36.4%), than those from healthy subjects (20.6%) and  those with aggressive periodontitis (10.8%). conclusions: the heterogeneous antagonistic spectrum exhibited by e. corrodens isolates suggests their ability to produce more than one antagonistic substance, whose ecological relevance is yet to be demonstrated. significance and impact of the study: this is the first description of antagonistic compound production by e. corrodens and its relationships with the clinical status of the patients.
TIHT== 
ABHT== 

PMID== 12670069
TI  == antimicrobial properties of self-etching primer-bonding systems.
AB  == self-etching primers are now considered the new generation of dentin bonding systems that modify and incorporate the bacteria-containing smear layer into their bonding mechanism. the antibacterial effects of the self-etching primers clearfil se bond, mac bond, imperva fl bond, one-up bondf and prompt l-pop were evaluated using the bacteria streptococcus mutans atcc25175, peptostreptococcus anaerobius, peptostreptococcus prevotii, peptostreptococcus asaccharolyticus, lactobacillus acidophilus, lactobacillus catenaforme, lactobacillus jensenii, actinomyces odontolyticus, porphyromonas endodontalis, clostridium ramosum, prevotella oris, prevotella denticola and fusobacterium nucleatum, with a disk diffusion method. a single-bottle total-etch dentin adhesive (excite) was used for comparisons and chlorhexidine (0.2%) was used as the positive control. after  incubation, zones of inhibited bacterial growth were observed. one-up bondf, prompt l-pop and excite showed growth inhibition for all bacterial strains. the bonding agents of clearfil se bond, mac bond and imperva fl bond were unable to inhibit the growth of lactobacillus jensenii and actinomyces odontolyticus, while the primers of these systems produced inhibition halos to all tested microorganisms greater than that of chlorhexidine.
TIHT== 
ABHT== 

PMID== 9641137
TI  == endodontic pathogens stimulate monocyte chemoattractant protein-1 and interleukin-8 in mononuclear cells.
AB  == microbial infection of the dental pulp leads to the recruitment of leukocytes and the formation of lesions of endodontic origin. the chemokines interleukin-8 (il-8) and monocyte chemoattractant protein-1 (mcp-1) are relatively specific chemoattractants for neutrophils and monocytes, respectively. in the present studies, peripheral blood mononuclear cells were stimulated by streptococcus mutants, porphyromonas endodontalis, and peptostreptococcus anaerobius, which are associated with lesions of endodontic origin. each of these bacteria induced a dose-dependent increase in il-8 and mcp-1, determined by elisa. the levels induced are physiologically relevant. however, low doses of p. endodontalis were  less effective in inducing il-8 or mcp-1 expression, compared with s. mutants or  p. anaerobius. thus, these bacteria can induce significant levels of the chemokines il-8 and mcp-1, which could contribute to the recruitment of neutrophils or monocytes in vivo. the expression of these mediators may contribute to the development of endodontic infections, particularly with regard  to inflammatory leukocyte recruitment.
TIHT== 
ABHT== 

PMID== 7595152
TI  == antibacterial effects of some root end filling materials.
AB  == in addition to having good sealing ability, root end filling materials should "ideally" have some antibacterial activity to prevent bacterial growth. this investigation compared the antibacterial effects of amalgam, zinc oxide-eugenol,  super eba and a mineral trioxide aggregate on nine facultative bacteria streptococcus fecalis, streptococcus mitis, streptococcus mutans, streptococcus salivarius, lactobacillus species, staphylococcus aureus, staphylococcus epidermidis, bacillus subtilis, and escherichia coli b and seven strict anaerobic bacteria, prevotella (bacteroides) buccae, bacteroides fragilis, prevotella (bacteroides) intermedia, prevotella (bacteroides) melaninogenica, fusobacterium  necrophorum, fusobacterium nucleatum, and peptostreptococcus anaerobius. after growing these bacteria on solid media, freshly mixed and 24-h set test materials  were placed on the surface of these inoculated media and incubated in the appropriate atmosphere for 24 to 48 h at 37 degrees c. impregnated discs with the super eba liquid were used as positive controls. the antibacterial effects of each material were measured in millimeters and the data were analyzed using one-way and two-way analysis of variance and scheffe tests to determine the statistical differences between the antibacterial effects of the test materials.  impregnated discs with super eba liquid caused varying degrees of growth inhibition for both facultative and strict anaerobic bacteria. both types of amalgam had no antibacterial effect against any of the bacteria tested in this study. mineral trioxide aggregate had an antibacterial effect on some of the facultative bacteria and no effect on any of the strict anaerobic bacteria. zinc  oxide-eugenol and super eba pastes had some antibacterial effects on both types of bacteria tested.(abstract truncated at 250 words)
TIHT== 
ABHT== 

PMID== 1337555
TI  == antibacterial efficacy of root canal medicaments.
AB  == the antibacterial efficacy of four endodontic medicaments was studied in vitro. calcium hydroxide (calacept), camphorated parachlorophenol (cpcp), cresophene, and 2% iodine-potassium iodide (iki) were tested against four anaerobic microorganisms, streptococcus mutans, peptostreptococcus anaerobius, porphyromonus gingivalis and fusobacterium nucleatum, for 10 or 15 min. iki was effective only against f. nucleatum and p. gingivalis, and the others were effective against all four microorganisms.
TIHT== 
ABHT== 

PMID== 2229394
TI  == use of modified norleucine-tyrosine broth in identification of peptostreptococcus anaerobius.
AB  == gas-liquid chromatography was employed to analyze the volatile and nonvolatile acids produced in modified norleucine-tyrosine (mnt) broth by various gram-positive cocci. the mnt broth consists of 0.5% trypticase (bbl microbiology  systems, cockeysville, md.), 0.5% yeast extract (difco laboratories, detroit, mich.), 0.2% l-norleucine, and 0.1% l-tyrosine. the microorganisms included reference strains and clinical isolates of peptostreptococcus spp. (p. anaerobius, p. asaccharolyticus, p. indolicus, p. magnus, and p. prevotii), staphylococcus spp. (s. aureus, s. epidermidis, and s. saccharolyticus), and streptococcus spp. (s. agalactiae, s. intermedius, s. mutans, s. sanguis i, and s. sanguis ii). only peptostreptococcus anaerobius strains produced caproic and valeric acids in mnt broth cultures. all 11 p. anaerobius strains produced valeric acid in mnt broth, and only 1 strain failed to produce caproic acid in the medium. this unique feature aids in rapid, reliable identification of p. anaerobius with a minimum number of tests.
TIHT== 
ABHT== 

PMID== 3155547
TI  == bactericidal effects of photoradiation therapy with hematoporphyrin derivative.
AB  == hematoporphyrin derivative (hpd) localizes selectively in malignant and rapidly metabolizing tissues and undergoes a cytotoxic reaction when exposed to light of  a specific wavelength. hpd has been studied extensively with regard to the diagnosis and treatment of tumors but not with regard to bactericidal activity. this investigation assessed the effect of light-activated hpd on various microorganisms, on human polymorphonuclear leukocytes, and on the interactions of polymorphonuclear leukocytes and bacteria. light-activated hpd was 99.9% bactericidal against staphylococcus aureus, streptococcus faecalis, bacteroides fragilis, streptococcus m-g intermedius, streptococcus mutans, peptostreptococcus anaerobius, peptococcus magnus, and clostridium perfringens, but did not affect escherichia coli, pseudomonas aeruginosa, or candida albicans. photoactivation of hpd rendered 98% of polymorphonuclear leukocytes inviable. combinations of light-activated hpd and polymorphonuclear leukocytes had a 4-log (99.99%) bactericidal effect on both intra- and extracellular s. aureus. the ability of hpd to localize in inflammatory tissues may have therapeutic applications in the  treatment of abscesses.
TIHT== 
ABHT== 

