@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23877700
TI  == comparative in vitro activities of smt19969, a new antimicrobial agent, against clostridium difficile and 350 gram-positive and gram-negative aerobic and anaerobic intestinal flora isolates.
AB  == the comparative in vitro activity of smt19969, a novel, narrow-spectrum, nonabsorbable agent, was studied against 50 ribotype-defined clostridium difficile strains, 174 gram-positive and 136 gram-negative intestinal anaerobes,  and 40 gram-positive aerobes. smt19969 was one dilution more active against c. difficile isolates (mic range, 0.125 to 0.5 mug/ml; mic90, 0.25 mug/ml), including ribotype 027 strains, than fidaxomicin (range, 0.06 to 1 mug/ml; mic90, 0.5 mug/ml) and two to six dilutions lower than either vancomycin or metronidazole. smt19969 and fidaxomicin were generally less active against gram-negative anaerobes, especially the bacteroides fragilis group species, than  vancomycin and metronidazole, suggesting that smt19969 has a lesser impact on the normal intestinal microbiota that maintain colonization resistance. smt19969 showed limited activity against other gram-positive anaerobes, including bifidobacteria species, eggerthella lenta, finegoldia magna, and peptostreptococcus anaerobius, with mic90s of >512, >512, 64, and 64 mug/ml, respectively. clostridium species showed various levels of susceptibility, with c. innocuum being susceptible (mic90, 1 mug/ml) and c. ramosum and c. perfringens being nonsusceptible (mic90, >512 mug/ml). activity against lactobacillus spp. (range, 0.06 to >512 mug/ml; mic90, >512 mug/ml) was comparable to that of fidaxomicin and varied by species and strain. gram-positive aerobic cocci (staphylococcus aureus, enterococcus faecalis, e. faecium, and streptococci) showed high smt19969 mic90 values (128 to >512 mug/ml).
TIHT== 
ABHT== 

PMID== 17714522
TI  == development of 16s rrna-based probes for the identification of gram-positive anaerobic cocci isolated from human clinical specimens.
AB  == fluorescent probes targeted at 16s rrna were designed for peptostreptococcus anaerobius and peptostreptococcus stomatis (pana134), parvimonas micra (pamic1435), finegoldia magna (fmag1250), peptoniphilus asaccharolyticus (pnasa1254), peptoniphilus ivorii (pnivo731), peptoniphilus harei (pnhar1466), anaerococcus vaginalis (avag1280) and anaerococcus lactolyticus (alac1438), based on the 16s rrna sequences of reference strains and 88 randomly chosen clinical isolates. these strains were also used for validation of the probes. application  of the probes to an additional group of 100 clinical isolates revealed that 87% of gram-positive anaerobic cocci (gpac) could be identified with this set of probes. the 16s rrnas of 13 clinical isolates that could not be identified were sequenced. most of these isolates were gpac that were not targeted by the probes. no clinical isolates of pn. asaccharolyticus were encountered. near full-length sequences were obtained from 71 of 101 (n = 88 + 13) sequenced clinical isolates. of these, 25 showed <98% similarity with the homologues of the closest established species. the fmag1250, pamic1435, pnhar1466, pana134, pnasa1254 and pnivo731 probes allowed reliable identification and hybridised with all corresponding isolates. the avag1280 and alac1438 probes failed to hybridise with two isolates and one isolate, respectively, because of intra-species variation. however, overall, the set of probes yielded fast and reliable identification for  the majority of clinical isolates.
TIHT== 
ABHT== 

PMID== 16982780
TI  == in vitro activity of ceftobiprole against aerobic and anaerobic strains isolated  from diabetic foot infections.
AB  == against 443 aerobic and anaerobic bacteria isolated from diabetic foot infections, ceftobiprole mics (microg/ml) at which 90% of the isolates tested were inhibited were as follows: methicillin-resistant staphylococcus aureus, 1; methicillin-susceptible s. aureus and staphylococcus lugdunensis, 0.5; anaerococcus prevotii, 0.125; finegoldia magna, 0.5; peptoniphilus asaccharolyticus, 1; peptostreptococcus anaerobius, 4; escherichia coli and enterobacter species, 0.125; klebsiella species, 2; and pseudomonas aeruginosa, 8.
TIHT== 
ABHT== 

PMID== 16701537
TI  == in vitro activity of oritavancin (ly333328), vancomycin, clindamycin, and metronidazole against clostridium perfringens, propionibacterium acnes, and anaerobic gram-positive cocci.
AB  == using an agar dilution method, we determined the in vitro activity of oritavancin, vancomycin, clindamycin and metronidazole against 114 unique clinical isolates of gram-positive anaerobes. mic(90)s (microg/ml) for oritavancin were as follows: clostridium perfringens 1.0, propionibacterium acnes 0.25, peptostreptococcus anaerobius 0.25, peptoniphilus asaccharolyticus 0.5, finegoldia magna 0.25, micromonas. micros 0.25, and anaerococcus prevotii 0.25. on a weight basis, oritavancin is slightly more active than vancomycin against the strains tested. the oritavancin mics are comparable to those previously reported against staphylococci and enterococci. oritavancin shows excellent potential for treatment of infections containing gram-positive anaerobes such as  these.
TIHT== 
ABHT== 

PMID== 16701526
TI  == anaerobic microbiology in 198 cases of pleural empyema: a bulgarian study.
AB  == the aim of the study was to evaluate the incidence of anaerobic bacteria in 198 patients with pleural empyema and the susceptibility of isolates to eight antibacterial agents. isolates were identified by the crystal anaerobes identification system, api system rapid id 32 a and/or routine methods. susceptibility was tested by sceptor mic system for anaerobic bacteria and limited agar dilution method. anaerobic bacteria were found in 74.2% of the patients and included 247 strains within 21 genera. the predominant anaerobes were gram-positive anaerobic cocci (52 isolates), fusobacterium (51), microaerophilic streptococci (24), prevotella (19) and bacteroides species (11).  common species/groups were fusobacterium nucleatum (in 27.2% of specimens yielding anaerobes), micromonas micros (8.2%), finegoldia magna (7.5%), bacteroides fragilis group (6.8%), peptostreptococcus anaerobius (6.1%) and f. necrophorum (5.4%). no resistance to chloramphenicol and ampicillin/sulbactam was detected. the susceptibility rates of gram-negative anaerobic isolates to penicillin, cefoxitin, clindamycin, clarithromycin, metronidazole and tetracycline were 63.8%, 90.2%, 87.8%, 58.6%, 98.8% and 71%, and those of gram-positive anaerobes were 79.2%, 100%, 84.3%, 68.4%, 41.9% and 75%, respectively. the wide diversity of isolated anaerobic genera and species and the susceptibility patterns of the isolates emphasize the role of the anaerobic microbiology in cases of pleural empyema.
TIHT== 
ABHT== 

PMID== 16276738
TI  == [two cases of bartholin's gland abscesses caused by streptococcus pneumoniae and  haemophilus influenzae].
AB  == most of bartholin's gland abscesses have been thought to be caused by microorganisms found in opportunistic infections. however, we have encountered two very interesting cases of bartholin's gland abscesses caused by streptococcus pneumoniae and haemophilus influenzae, two major pathogens of respiratory tract infections. in the first case, since abscess formation was not observed due to disintegration, cefdinir (cfdn), 300 mg/day, t.i.d. for 5 days was administered.  the treatment improved clinical symptoms, but relapse occurred 3 days after the administration was discontinued. microbiological examination of pus revealed the  presence of streptococcus pneumoniae and finegoldia magna, and it also showed that the isolated s. pneumoniae was penicillin-resistant s. pneumoniae (prsp). after an incision and drainage of abscess, cefteram pivoxil (cftm-pi), 300 mg/day t.i.d. for 7 days, was administered, and the cure was confirmed. in the second case, after an incision and drainage of bartholin's gland abscess, amoxicillin (ampc), 750 mg/day, t.i.d. for 5 days, was administered. the treatment improved clinical symptoms temporarily. however, the symptoms deteriorated 7 days after the operation, and the patient was diagnosed with relapse. microbiological examination of pus revealed the presence of haemophilus influenzae and peptostreptococcus anaerobius, and it also showed that the isolated h. influenzae was beta-lactamase-nonproducing ampicillin-resistant h. influenzae (blnar). after performing additional incision and drainage of abscess again, cftm-pi, 300 mg/day, t.i.d. for 7 days, was administered, and the cure was confirmed. in addition, the analysis of these two cases using pk/pd theory revealed that the time above mic reached 100% with administration of cftm-pi 300mg, t.i.d. suggesting that the dosage is sufficient for treating these infections. there are other cases of external genitalia infections caused by microorganisms usually associated with respiratory tract infections like cases that we are reporting here. therefore, it is necessary to consider a possible infection by drug-resistant bacteria even for a case of external genitalia infection. in addition, it was thought that adjusting dosage and method for administration of antibacterial agents based on pk/pd theory would help to rovide efficient treatment.
TIHT== 
ABHT== 

PMID== 15049457
TI  == phospholipid analogue profiles of peptostreptococcus, micromonas, and finegoldia  species analysed by fast atom bombardment mass spectrometry.
AB  == species of peptostreptococcus cause a variety of infections, primarily abscesses  of soft tissues, joints, and mucous membranes. the aim of this study was to compare the phospholipid analogue profiles of peptostreptococcus species, represented by p. anaerobius, p. asaccharolyticus, p. indolicus, p. lacrimalis, and p. prevotii; micromonas micros (p. micros) and finegoldia magna (p. magnus).  after anaerobic growth on blood-faa, lipids extracted by chloroform-methanol (2:1 v/v) were purified, then analysed by fast atom bombardment mass spectrometry (fab-ms) in negative ion mode. the major peaks with mass to charge (m/z) 719, 721, and 749, corresponded to phosphatidylglycerol analogues, namely pg (32:1), pg (32:0), and pg (34:0), which have been found previously in lactobacillus spp., clostridium difficile, and staphylococcus spp. other major peaks observed, with m/z 619, 647, 665, 675, 677, 687, 691, 693, 701, 703, 707, 733, and 746 have also been reported in one or more of these three species. however, other major peaks found here in peptostreptococcus, micromonas, and finegoldia have not been described elsewhere; these are 501, 514, 515, 618, 659, 673, 676, 688, 690, 692,  694, 700, 706, 715, 718, 722, and 750. we conclude that peptostreptococcus, micromonas, and finegoldia isolates are chemically unique.
TIHT== 
ABHT== 

PMID== 12855723
TI  == rapid identification of gram-positive anaerobic coccal species originally classified in the genus peptostreptococcus by multiplex pcr assays using genus- and species-specific primers.
AB  == here, a rapid and reliable two-step multiplex pcr assay for identifying 14 gram-positive anaerobic cocci (gpac) species originally classified in the genus peptostreptococcus (anaerococcus hydrogenalis, anaerococcus lactolyticus, anaerococcus octavius, anaerococcus prevotii, anaerococcus tetradius, anaerococcus vaginalis, finegoldia magna, micromonas micros, peptostreptococcus anaerobius, peptoniphilus asaccharolyticus, peptoniphilus harei, peptoniphilus indolicus, peptoniphilus ivorii and peptoniphilus lacrimalis) is reported. fourteen type strains representing 14 gpac species were first identified to the genus level by multiplex pcr (multiplex pcr-g). since three of these genera (finegoldia, micromonas and peptostreptococcus) contain only a single species, f. magna, m. micros and p. anaerobius, respectively, these organisms were identified to the species level directly by using the multiplex pcr-g. then six species of the genus anaerococcus (a. hydrogenalis, a. lactolyticus, a. octavius, a. prevotii, a. vaginalis and a. tetradius) were further identified to the species level using multiplex pcr assays (multiplex pcr-ia and multiplex pcr-ib). similarly, five species of the genus peptoniphilus (pn. asaccharolyticus, pn. harei, pn. indolicus, pn. ivorii and pn. lacrimalis) were identified to the species level using multiplex pcr-iia and multiplex pcr-iib. the established two-step multiplex pcr identification scheme was applied to the identification of 190 clinical isolates of gpac species that had been identified previously to the  species level by 16s rrna sequencing and phenotypic tests. the identification obtained from multiplex pcr assays showed 100 % agreement with 16s rdna sequencing identification, but only 65 % (123/190) agreement with the identification obtained by phenotypic tests. the multiplex pcr scheme established in this study is a simple, rapid and reliable method for the identification of gpac species. it will permit a more accurate assessment of the role of various gpac species in infection and of the degree of antimicrobial resistance in each of the group members.
TIHT== 
ABHT== 

PMID== 12714813
TI  == in vitro and in vivo antibacterial activities of telithromycin.
AB  == background: telithromycin is one of the ketolides, characterised by a 3-keto group instead of l-cladinose and a c(11)-c(12) carbamate link by an alkyl chain to a pyridinum and imidazolium ring side chain. we evaluated in vitro and in vivo antibacterial activities of telithromycin against gynaecological pathogens. methods: in the vitro study, the antibacterial activity of telithromycin against  180 isolates (isolated in the year 2000) of streptococcus agalactiae (n = 33), enterococcus faecalis (n = 22), neisseria gonorrhoeae (n = 30), peptostreptococcus anaerobius (n = 20), finegoldia magna (n = 20), bacteroides fragilis (n = 25) and prevotella bivia (n = 30) was compared with that of erythromycin a, clarithromycin, azithromycin, ampicillin and levofloxacin. in the in vivo study, the efficacy of telithromycin was evaluated using experimental intra-abdominal abscesses in mice caused by b. fragilis (minimum inhibitory concentration of telithromycin 0.5 mg/l). results: in the in vitro study, telithromycin inhibited more than 50% of clinical isolates of s. agalactiae, e. faecalis, n. gonorrhoeae, p. anaerobius, f. magna, b. fragilis and p. bivia at concentrations of 0.016, 0.063, 0.063, 0.032, 0.032, 0.5 and 0.25 mg/l, respectively. telithromycin inhibited more than 90% of these clinical isolates at concentrations of 0.016, 4, 0.125, 0.063, 0.063, 4 and 1 mg/l, respectively. in the in vivo study, telithromycin inhibited abscess formation and significantly decreased viable cell counts in abscesses in comparison with the untreated group. conclusions: these in vitro and in vivo antibacterial activities suggest that telithromycin could be a potential candidate for the treatment of bacterial infections complicated by chlamydial infection.
TIHT== 
ABHT== 

PMID== 12023074
TI  == physical and genetic map of the finegoldia magna (formerly peptostreptococcus magnus) atcc 29328 genome.
AB  == a physical and genetic map of finegoldia magna (formerly peptostreptococcus magnus) atcc 29328 chromosome was constructed. the order of rare cleavage restriction fragments was determined by double digestion with the restriction enzymes i-ceui, sgrai, apai and pmei, cross-hybridization and apai-linking clones. the size of the circular chromosome of f. magna was estimated to be 1.9 mb. this strain also had a 200-kb megaplasmid. the chromosome contained four rrn  operons, and the orientation of two rrn operons was opposite to the others. fragment analysis of peptostreptococcus anaerobius atcc 27337(t) chromosome suggested that its size was much smaller than that of f. magna atcc 29328.
TIHT== 
ABHT== 

