@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 24657864
TI  == salivary microbiota and metabolome associated with celiac disease.
AB  == this study aimed to investigate the salivary microbiota and metabolome of 13 children with celiac disease (cd) under a gluten-free diet (treated celiac disease [t-cd]). the same number of healthy children (hc) was used as controls. the salivary microbiota was analyzed by an integrated approach using culture-dependent and -independent methods. metabolome analysis was carried out by gas chromatography-mass spectrometry-solid-phase microextraction. compared to  hc, the number of some cultivable bacterial groups (e.g., total anaerobes) significantly (p < 0.05) differed in the saliva samples of the t-cd children. as  shown by community-level catabolic profiles, the highest shannon's diversity and  substrate richness were found in hc. pyrosequencing data showed the highest richness estimator and diversity index values for hc. levels of lachnospiraceae,  gemellaceae, and streptococcus sanguinis were highest for the t-cd children. streptococcus thermophilus levels were markedly decreased in t-cd children. the saliva of t-cd children showed the largest amount of bacteroidetes (e.g., porphyromonas sp., porphyromonas endodontalis, and prevotella nanceiensis), together with the smallest amount of actinobacteria. t-cd children were also characterized by decreased levels of some actinomyces species, atopobium species, and corynebacterium durum. rothia mucilaginosa was the only actinobacteria species found at the highest level in t-cd children. as shown by multivariate statistical analyses, the levels of organic volatile compounds markedly differentiated t-cd children. some compounds (e.g., ethyl-acetate, nonanal, and 2-hexanone) were found to be associated with t-cd children. correlations (false discovery rate [fdr], <0.05) were found between the relative abundances of bacteria and some volatile organic compounds (vocs). the findings of this study indicated that cd is associated with oral dysbiosis that could affect the oral metabolome.
TIHT== 
ABHT== 

PMID== 22837552
TI  == white-spot lesions and gingivitis microbiotas in orthodontic patients.
AB  == white-spot lesions (wsl) associated with orthodontic appliances are a cosmetic problem and increase risk for cavities. we characterized the microbiota of wsl, accounting for confounding due to gingivitis. participants were 60 children with  fixed appliances, aged between 10 and 19 yrs, half with wsl. plaque samples were  assayed by a 16s rrna-based microarray (homim) and by pcr. mean gingival index was positively associated with wsl (p = 0.018). taxa associated with wsl by microarray included granulicatella elegans (p = 0.01), veillonellaceae sp. hot 155 (p < 0.01), and bifidobacterium cluster 1 (p = 0.11), and by qpcr, streptococcus mutans (p = 0.008) and scardovia wiggsiae (p = 0.04) taxa associated with gingivitis by microarray included: gemella sanguinis (p = 0.002), actinomyces sp. hot 448 (p = 0.003), prevotella cluster iv (p = 0.021), and streptococcus sp. hot 071/070 (p = 0.023); and levels of s. mutans (p = 0.02) and bifidobacteriaceae (p = 0.012) by qpcr. species' associations with wsl were minimally changed with adjustment for gingivitis level. partial least-squares discriminant analysis yielded good discrimination between children with and those without wsl. granulicatella, veillonellaceae and bifidobacteriaceae, in addition  to s. mutans and s. wiggsiae, were associated with the presence of wsl in adolescents undergoing orthodontic treatment. many taxa showed a stronger association with gingivitis than with wsl.
TIHT== 
ABHT== 

PMID== 19722792
TI  == comparisons of subgingival microbial profiles of refractory periodontitis, severe periodontitis, and periodontal health using the human oral microbe identification microarray.
AB  == background: this study compared the subgingival microbiota of subjects with refractory periodontitis (rp) to those in subjects with treatable periodontitis (grs = good responders) or periodontal health (ph) using the human oral microbe identification microarray (homim). methods: at baseline, subgingival plaque samples were taken from 47 subjects with periodontitis and 20 individuals with ph and analyzed for the presence of 300 species by homim. the subjects with periodontitis were classified as having rp (n = 17) based on mean attachment loss (al) and/or more than three sites with al >or=2.5 mm after scaling and root planing, surgery, and systemically administered amoxicillin and metronidazole or  as grs (n = 30) based on mean attachment gain and no sites with al >or=2.5 mm after treatment. significant differences in taxa among the groups were sought using the kruskal-wallis and chi(2) tests. results: more species were detected in patients with disease (gr or rp) than in those without disease (ph). subjects with rp were distinguished from grs or those with ph by a significantly higher frequency of putative periodontal pathogens, such as parvimonas micra (previously peptostreptococcus micros or micromonas micros), campylobacter gracilis, eubacterium nodatum, selenomonas noxia, tannerella forsythia (previously t. forsythensis), porphyromonas gingivalis, prevotella spp., treponema spp., and eikenella corrodens, as well as unusual species (pseudoramibacter alactolyticus,  tm7 spp. oral taxon [ot] 346/356, bacteroidetes sp. ot 272/274, solobacterium moorei, desulfobulbus sp. ot 041, brevundimonas diminuta, sphaerocytophaga sp. ot 337, shuttleworthia satelles, filifactor alocis, dialister invisus/pneumosintes,  granulicatella adiacens, mogibacterium timidum, veillonella atypica, mycoplasma salivarium, synergistes sp. cluster ii, and acidaminococcaceae [g-1] sp. ot 132/150/155/148/135) (p <0.05). species that were more prevalent in subjects with ph than in patients with periodontitis included actinomyces sp. ot 170, actinomyces spp. cluster i, capnocytophaga sputigena, cardiobacterium hominis, haemophilus parainfluenzae, lautropia mirabilis, propionibacterium propionicum, rothia dentocariosa/mucilaginosa, and streptococcus sanguinis (p <0.05). conclusion: as determined by homim, patients with rp presented a distinct microbial profile compared to patients in the gr and ph groups.
TIHT== 
ABHT== 

PMID== 18438556
TI  == antimicrobial effect and ph of chlorhexidine gel and calcium hydroxide alone and  associated with other materials.
AB  == the purposes of this study were to evaluate the effectiveness of 2% chlorhexidine (chx) gluconate gel, calcium hydroxide [ca(oh)2] and their combination with iodoform and zinc oxide powder as intracanal medications against select microorganisms, and to measure the ph changes caused by these medications. antimicrobial activity was determined by the agar diffusion method. the zones of  growth inhibition were measured and the results were analyzed statistically by kruskal-wallis test (p<0.05). the ph of the pastes was measured right after preparation, after 24 h and 1 week later. the largest mean zones of microbial inhibition were produced by 2% chx gel, followed by ca(oh)2 + 2% chx gel + iodoform, ca(oh)2 + 2% chx gel, ca(oh)2 + 2% chx gel + zinc oxide, and ca(oh)2 +  water. the mean ph of all medications stayed above 12.0 during the whole experiment, except for chx gel (ph=7.0). the results of this study showed that all medications had antimicrobial activity, but the most effective against the tested microorganisms were 2% chx gel, followed by its combination with ca(oh)2 and iodoform.
TIHT== 
ABHT== 

PMID== 18278298
TI  == comparative study of the antimicrobial efficacy of chlorhexidine gel, chlorhexidine solution and sodium hypochlorite as endodontic irrigants.
AB  == the purpose of this study was to assess the in vitro the antimicrobial efficacy of chlorhexidine gluconate gel as an endodontic auxiliary chemical substance compared to sodium hypochlorite (naocl) and chlorhexidine gluconate solution. the antimicrobial efficacy of the tested substances was evaluated using the agar diffusion test. the growth inhibition zones produced by 0.2%, 1% and 2% chlorhexidine gel were evaluated against 5 facultative anaerobic bacteria and 4 pigmented gram-negative anaerobes, and compared to the results obtained by naocl  and chlorhexidine solution. the largest growth inhibition zones were produced when the test bacteria were in contact with 2% chlorhexidine gluconate gel (11.79 mm), being significantly different (p<0.05) from the growth inhibition zones produced by all naocl concentrations, including 5.25% (9.54 mm). however, there was no statistically significant difference (p>0.05) between the growth inhibition zones obtained with equal concentrations of chlorhexidine solution and gel. the results of this study indicate that, as far as its antimicrobial properties are concerned, chlorhexidine gel has a great potential to be used as an endodontic auxiliary chemical substance.
TIHT== 
ABHT== 

PMID== 17539719
TI  == bacterial species in subgingival plaque and oral bone loss in postmenopausal women.
AB  == background: oral bacteria are widely recognized in the etiology of periodontal disease. we investigated the prevalence of subgingival bacterial infection with eight species, tested associations between infection and oral bone loss, and assessed potential confounding factors and effect modifiers of those associations in a large community-based cohort of postmenopausal women. methods: a cross-sectional study of oral health and osteoporosis in 1,256 postmenopausal women recruited from the buffalo, new york women's health initiative observational study was conducted. standardized dental radiographs were used to measure alveolar crestal height (ach). subgingival plaque samples were taken, and the presence of eight bacterial species was assessed by indirect immunofluorescent microscopy in each participant. results: the most prevalent infection was streptococcus sanguis (59.5%), followed by prevotella intermedia (43.4%), tannerella forsythensis (37.9%), capnocytophaga sp. (36.9%), eubacterium saburreum (32.7%), campylobacter rectus (17.4%), porphyromonas gingivalis (15.1%), and fusobacterium nucleatum (14.2%). infections with p. gingivalis, t. forsythensis, p. intermedia, and c. rectus were associated with an increased likelihood of having oral bone loss as measured by ach, even after adjustment for age, smoking, and income. the body mass index (bmi) was a modifier of this association. overweight women with t. forsythensis infection were more likely to  have oral bone loss (or = 3.37; 95% confidence interval [ci]: 2.08 to 5.46) than  normal weight (or = 1.27; 95% ci: 0.82 to 1.98) or obese (or = 1.26, 95% ci: 0.72 to 2.20) women with t. forsythensis infection. conclusions: the prevalence of specific bacterial infections was determined for a large group of postmenopausal  women. those with infection were more likely to have oral bone loss. further studies should investigate potential modifying effects of bmi and/or inflammatory factors.
TIHT== 
ABHT== 

PMID== 17098542
TI  == bacterial diversity in aortic aneurysms determined by 16s ribosomal rna gene analysis.
AB  == background: aortic aneurysms are common vascular conditions that cause considerable morbidity and mortality. understanding of the mechanisms involved in the pathogenesis of the condition remains limited. recently, infection has been suggested as possible contributor in the development of the disease. the aim of the present study was to examine aortic aneurysms for the presence of bacterial dna using polymerase chain reaction (pcr) targeting the 16s ribosomal rna (rrna)  gene, followed by cloning and sequencing. methods: universal eubacterial primers  were used to amplify 16s rrna bacterial genes in 10 specimens from arterial walls of aortic aneurysms. subsequently, pcr amplicons were cloned into escherichia coli and sequencing of the cloned inserts was used to determine species identity  or closest relatives by comparison with known sequences in genbank. results: sequences of stenotrophomonas spp., including s. maltophilia (formerly pseudomonas homology group v) were detected in six aneurysm samples. propionibacterium acnes was identified in five samples, and brevundimonas diminuta (formerly p. diminuta) in four samples. other species previously assigned to the pseudomonas genus such as comamonas testosteroni, delftia acidovorans, burkholderia cepacia, herbaspirillum sp., and acidovorax sp. were also detected. some clones fell into other environmental species, including methylobacterium sp. and bradyrhizobium elkanii, and others represented bacteria  that have not yet been cultivated. dna sequences from oral bacteria, including streptococcus sanguinis, tannerella forsythia, and leptotrichia buccalis were detected. sequences from prevotella melaninogenica and lactobacillus delbrueckii, which are commonly found in both mouth and gastrointestinal tract, were also detected. additional species included dermacoccus spp. and corynebacterium vitaeruminis. conclusions: a wide variety of bacteria, including oral bacteria, was found to colonize aortic aneurysms and may play a role in their development.  several of these microorganisms have not yet been cultivated. clinical relevance: although chlamydophila pneumoniae has been detected in aneurysmal walls, its exact role in the condition remains inconclusive. overall, there is scarce information about the role of microorganisms in aneurysmal disease. in the present study, we used molecular genetics to detect a diversity of bacteria in arterial walls of aortic aneurysms. the presence of multiple microorganisms in aneurysmal disease may have implications for chemoprophylaxis and antibiotic treatment if directed only at c.pneumoniae.
TIHT== 
ABHT== 

PMID== 9209128
TI  == [a case of severe odontogenic infection with allergic skin reaction for beta-lactam antibiotics].
AB  == a 54-aged woman consulted with right buccal phlegmon caused by lower apical periodontitis. the primary chemotherapy using flomoxef induced allergic skin eruption. a decision was made for using clindamycin, levofloxacin and fosfomycin  as chemotherapeutic agents. cultured organisms from the abscess revealed the mixed infection with streptococcus sanguis, veillonella sp., prevotella loescheii, wolinella spp. on 12th hospital day, her serum crp turned to negative. this case carried numerous implications for the use of antibiotics as chemotherapy agents.
TIHT== 
ABHT== 

