@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25606402
TI  == study of rumen metagenome community using qpcr under different diets.
AB  == the aim of this study was to detect the major bacteria present in rumen microbiota. here, we performed qpcr based absolute quantitation of selected rumen microbes in rumen fluid of river buffalo adapted to varying proportion of concentrate to roughage diets. animals were adapted to roughage-to-concentrate ratio in the proportion of 100:00 (t1), 75:25 (t2), 50:50 (t3) and 25:75 (t4) respectively for 30 days. at the end of each treatment, rumen fluid was collected at 0 h and 2 h after feeding. it was found that among fibrolytic bacteria ruminococcus flavefaciens (2.22 x 10(8) copies/ml) were highest in t2 group and followed by 1.11 x 10(8) copies/ml for fibrobacter succinogenes (t2), 2.56 x 10(7) copies/ml for prevotella ruminicola (t1) and 1.25 x 10(7) copies/ml for ruminococcus albus (t4). in non-fibrolytic bacteria, the selenomonas ruminantium  (2.62 x 10(7) copies/ml) was predominant in group t3 and followed by treponema bryantii (2.52 x 10(7)copies/ml) in group t1, ruminobacter amylophilus (1.31 x 10(7)copies/ml) in group t1 and anaerovibrio lipolytica (2.58 x 10(6) copies/ml)  in group t4. it is most notable that r. flavefaciens were the highest in population in the rumen of surti buffalo fed wheat straw as roughage source.
TIHT== 
ABHT== 

PMID== 24053023
TI  == use of real-time pcr technique in determination of major fibrolytic and non fibrolytic bacteria present in indian surti buffaloes (bubalus bubalis).
AB  == in the milk industry in india, buffalo breeds are most commonly used for milk production. efficiency of fiber digestion in ruminants is critical for animal productivity. bacteria play an important role in fiber digestion and utilization. absolute quantification real-time pcr was used to quantify ten bacterial species  in rumen fluid of surti buffalo fed green fodder, dry roughage and compound concentrate mixture. abundance of each target taxon was calculated as a fraction  of the total 16s rrna gene copies in the samples, using taxon-specific primers. bacterial populations showed a clear predominance of ruminococcus albus, which comprised 5.66% of the bacterial rrna gene copies in the samples. however, only 0.9% to 4.24% of the bacterial rrna gene copies were represented by the ruminal fibrobacter succinogenes, ruminococcus flavefaciens and prevotella species. the proportion of rrna gene copies attributable to selenomonas ruminantium, streptococcus bovis, ruminobacter amylophilus, treponema bryantii and anaerovibrio lipolytica was even less abundant, each comprising < 0.11% of the bacterial rrna gene copies. the data suggest that the aggregate abundance of the  most intensively studied ruminal bacterial species is relatively low and that a large fraction of the uncultured population represents a single bacterial genus.
TIHT== 
ABHT== 

PMID== 23653262
TI  == antimicrobial activity of brazilian propolis extracts against rumen bacteria in vitro.
AB  == the antimicrobial activity of three brazilian propolis extracts was evaluated on  bacterial strains representing major rumen functional groups. the extracts were prepared using different concentrations of propolis and alcohol, resulting in different phenolic compositions. the propolis extracts inhibited the growth of fibrobacter succinogenes s85, ruminococcus flavefaciens fd-1, ruminococcus albus  7, butyrivibrio fibrisolvens d1, prevotella albensis m384, peptostreptococcus sp. d1, clostridium aminophilum f and streptococcus bovis pearl11, while r. albus 20, prevotella bryantii b(1)4 and ruminobacter amylophilus h18 were resistant to all  the extracts. the inhibited strains showed also different sensitivity to propolis; the hyper-ammonia-producing bacteria (c. aminophilum f and peptostreptococcus sp. d1) being the most sensitive. inhibition of hyper-ammonia-producing bacteria by propolis would be beneficial to the animal. the extract containing the lowest amount of phenolic compounds (llos c3) showed the lowest antimicrobial activity against all the bacteria. the major phenolic compounds identified in the propolis extracts (naringenin, chrysin, caffeic acid, p-coumaric acid and artepillin c) were also evaluated on four sensitive strains.  only naringenin showed inhibitory effect against all strains, suggesting that naringenin is one of the components participating to the antibacterial activity of propolis.
TIHT== 
ABHT== 

PMID== 22901468
TI  == use of prevotella bryantii 25a and a commercial probiotic during subacute acidosis challenge in midlactation dairy cows.
AB  == the objective of this study was to determine the efficacy of prevotella bryantii  25a as a probiotic during a subacute ruminal acidosis (sara) challenge using a commercial probiotic as a positive control. six multiparous ruminally fistulated  cows (bw=685 +/- 65 kg; (mean +/- sd) in the mid-phase of lactation (70 to 148 dim) received the following treatments in a replicated 3x3 latin square design: (1) total mixed ration (tmr; control, con), (2) tmr + 2g/head per day of a probiotic combination of enterococcus faecium and saccharomyces cerevisiae (efsc), or (3) tmr + prevotella bryantii 25a. the latin square consisted of 3 wk  of adaptation to the respective treatments during which the animals were fed ad libitum once per day a conventional early-lactation tmr and 1.5 kg of hay. the adaptation was followed by 4 d of sara (no hay) and 10d of rest (adaptation diet  without probiotics). dry matter intake and milk production were depressed during  sara (22.0 and 31.8 kg/d, respectively) compared with adaptation (24.4 and 34.0 kg/d, respectively) and did not recover during rest (22.3 and 30.7 kg/d, respectively). during sara, p. bryantii 25a had no effect on rumen ph, whereas efsc reduced the percentage of time with ph <6.0 (71%) compared with con (85%) and increased maximum ph. the efsc treatment tended to increase mean ph over 24h  (5.65) compared with con (5.45). proportion of time with ph <5.6 tended to be lower with efsc (46%) than with con (62%). populations of bacteria considered to  be the most important cellulose digesters in the rumen (ruminococcus flavefaciens, ruminococcus albus, and fibrobacter succinogenes) were also monitored during these treatments using culture-independent real-time pcr methods. the population of r. flavefaciens was similar between the 2 feeding phases, whereas f. succinogenes and r. albus were lower during sara compared with rest. in light of the present study, p. bryantii 25a did not prove to be an effective preventative for sara. the role of efsc in regulating rumen ph was confirmed, with a possible effect of maintaining r. flavefaciens populations during sara.
TIHT== 
ABHT== 

PMID== 22692875
TI  == effects of hop varieties on ruminal fermentation and bacterial community in an artificial rumen (rusitec).
AB  == background: there is a growing interest in the use of hops (humulus lupulus) as an alternative to antibiotics to manipulate ruminal fermentation. however, the effects of different hop varieties on ruminal fermentation and bacterial populations have not been studied. here the effects of three hop varieties, cascade (cas), millennium (mil) and teamaker (tm), at a level of 800 microg ml(-1) inoculum on ruminal fermentation and microbial populations in an artificial rumen system (rusitec) fed a barley silage-based total mixed ration were investigated. bacterial populations were assessed using real-time polymerase chain reaction and expressed as a percentage of total bacterial 16s rrna gene copies. results: all hops reduced (p < 0.001) total gas, methane and the acetate:propionate ratio. liquid-associated fibrobacter succinogenes, ruminococcus albus and streptococcus bovis were reduced (p < 0.05) by mil and tm. feed particle-associated s. bovis was reduced (p < 0.01) by mil and tm, but tm and cas increased (p < 0.01) ruminobacter amylophilus and prevotella bryantii respectively. methanogens were decreased (p < 0.05) by mil in both liquid and solid fractions and by cas in the solid fraction. the total amount of alpha- and  beta-acids in hops affected the ruminal fermentation. conclusion: hop-induced changes in fermentation and microbial populations may improve energy efficiency use in the rumen. further research is needed to determine the effects of hops on  in vivo ruminal fermentation, microbial populations and animal performance.
TIHT== 
ABHT== 

PMID== 20163675
TI  == detection and identification of rumen bacteria constituting a fibrolytic consortium dominated by fibrobacter succinogenes.
AB  == a fibrolytic consortium, dominated by the rumen cellulolytic bacterium fibrobacter succinogenes, was artificially constructed on hay stems to detect and identify rumen bacteria that can potentially interact with f. succinogenes. consortium-bacterial members were determined by dgge and sequencing analysis targeted bacterial 16s rdna. an artificial consortium was formed in a 2-step incubation of hay stems; the first step with group 1, 2 or 3 f. succinogenes strains, the second step with rumen fluid. after consortium formation, morphologically different bacteria were observed in association with f. succinogenes. dgge exhibited more than 30 bands, the pattern of which depended on the f. succinogenes group. sequencing suggested that butyrivibrio fibrisolvens, pseudobutyrivibrio ruminis, clostridium sp., f. succinogenes group 2, prevotella  ruminicola and unclassified bacteroides were prominent in the group 1 consortium  and that treponema bryantii, b. fibrisolvens, acinetobacter sp, and wolinella succinogenes were prominent in the group 2 consortium. however, in the group 3 consortium, f. succinogenes-like bacteria were microscopically undetectable, whereas cellulolytic ruminococcus albus and f. succinogenes group 1 were prominent, suggesting that the group 3 cannot be a core member of this consortium. this study is the first attempt to identify bacterial members of a fibrolytic consortium dominated by a specific bacterium.
TIHT== 
ABHT== 

PMID== 18839246
TI  == biotransformation of 2,4,6-trinitrotoluene by pure culture ruminal bacteria.
AB  == twenty-one ruminal bacteria species were tested for their ability to degrade 2,4,6-trinitrotoluene (tnt) within 24 h. butyrivibrio fibrisolvens, fibrobacter succinogenes, lactobacillus vitulinus, selenomonas ruminantium, streptococcus caprinus, and succinivibrio dextrinosolvens were able to completely degrade 100 mg/l tnt, with <5% of the original tnt recovered as diaminonitrotoluene metabolites. eubacterium ruminantium, lactobacillus ruminis, ruminobacter amylophilus, streptococcus bovis, and wolinella succinogenes were able to completely degrade 100 mg/l tnt, with 23-60% of the tnt recovered as aminodinitrotoluene and/or diaminonitrotoluene metabolites. clostridium polysaccharolyticum, megasphaera elsdenii, prevotella bryantii, prevotella ruminicola, ruminococcus albus, and ruminococcus flavefaciens were able to degrade 80-90% of 100 mg/l tnt. desulfovibrio desulfuricans subsp. desulfuricans, prevotella albensis, and treponema bryantii degraded 50-80% of the tnt. anaerovibrio lipolytica was completely inhibited by 100 mg/l tnt. these results indicate that a variety of rumen bacteria is capable of transforming tnt.
TIHT== 
ABHT== 

PMID== 17235560
TI  == dominance of prevotella and low abundance of classical ruminal bacterial species  in the bovine rumen revealed by relative quantification real-time pcr.
AB  == relative quantification real-time pcr was used to quantify several bacterial species in ruminal samples from two lactating cows, each sampled 3 h after feeding on two successive days. abundance of each target taxon was calculated as  a fraction of the total 16s rrna gene copies in the samples, using taxon-specific and eubacterial domain-level primers. bacterial populations showed a clear predominance of members of the genus prevotella, which comprised 42% to 60% of the bacterial rrna gene copies in the samples. however, only 2% to 4% of the bacterial rrna gene copies were represented by the classical ruminal prevotella species prevotella bryantii, prevotella ruminicola and prevotella brevis. the proportion of rrna gene copies attributable to fibrobacter succinogenes, ruminococcus flavefaciens, selenomonas ruminantium and succinivibrio dextrinosolvens were each generally in the 0.5% to 1% range. proportions for ruminobacter amylophilus and eubacterium ruminantium were lower (0.1% to 0.2%), while butyrivibrio fibrisolvens, streptococcus bovis, ruminococcus albus and megasphaera elsdenii were even less abundant, each comprising <0.03% of the bacterial rrna gene copies. the data suggest that the aggregate abundance of the  most intensively studied ruminal bacterial species is relatively low and that a large fraction of the uncultured population represents a single bacterial genus.
TIHT== 
ABHT== 

PMID== 10792550
TI  == effect of steroidal saponin from yucca schidigera extract on ruminal microbes.
AB  == the effects of steroidal saponins (sap) isolated from yucca schidigera extract on ruminal bacteria and fungi were investigated in pure culture studies. prevotella  bryantii, ruminobacter amylophilus, selenomonas ruminantium and streptococcus bovis were cultured through ten 24-h transfers in ruminal fluid medium containing 0 or 25 microg sap ml-1 (measured as smilagenin equivalents). the four strains, each non-exposed or pre-exposed to sap, were then inoculated into medium containing 0 or 250 microgram smilagenin equivalents ml-1 and 24-h growth curves  were determined. the cellulolytic ruminal bacteria ruminococcus flavefaciens, fibrobacter succinogenes and rc. albus were cultured for 72 h on whatman no. 1 filter paper in medium containing 0, 9, 90 or 180 microgram sap ml-1 for the determination of filter paper digestion and endoglucanase activity. the ruminal bacteria differed in their responses to sap. steroidal saponins in the medium reduced the growth of strep. bovis (p < 0.01 at 2, 3, 4, 5, 6 and 8 h), p. bryantii (p < 0.05 at 4, 5, 6, 8, 10 and 24 h) and rb. amylophilus (p < 0.05 at 14 and 24 h), but the growth of s. ruminantium was enhanced (p < 0.05) at 10, 14  and 24 h. the growth curves of all four non-cellulolytic species were similar (p  > 0.05) between pre-exposed and non-exposed cultures and the concentrations of total sap and soluble (deglycosylated) sap in the liquid fraction were unchanged  (p > 0.05) over time. steroidal saponins inhibited the digestion of filter paper  by all three cellulolytic bacteria, but f. succinogenes was less (p < 0.05) sensitive to sap and more (p < 0. 05) effective at deglycosylating sap than were  rc. flavefaciens or rc. albus. transmission electron microscopy revealed that sap altered the cell walls of the sap-inhibited non-cellulolytic bacteria. the ruminal fungi, neocallimastix frontalis and piromyces rhizinflata, were cultured  on filter paper in medium containing 0, 0. 45, 2.25 or 4.5 microgram sap ml-1. filter paper digestion by both fungi was completely inhibited by 2.25 microgram sap ml-1. steroidal saponins from y. schidigera inhibit cellulolytic ruminal bacteria and fungi, but their effects on amylolytic bacteria are species dependent and similar to the effects of ionophores. as such, sap may be useful in nutritional applications targeting starch-digesting ruminal micro-organisms.
TIHT== 
ABHT== 

