@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25606402
TI  == study of rumen metagenome community using qpcr under different diets.
AB  == the aim of this study was to detect the major bacteria present in rumen microbiota. here, we performed qpcr based absolute quantitation of selected rumen microbes in rumen fluid of river buffalo adapted to varying proportion of concentrate to roughage diets. animals were adapted to roughage-to-concentrate ratio in the proportion of 100:00 (t1), 75:25 (t2), 50:50 (t3) and 25:75 (t4) respectively for 30 days. at the end of each treatment, rumen fluid was collected at 0 h and 2 h after feeding. it was found that among fibrolytic bacteria ruminococcus flavefaciens (2.22 x 10(8) copies/ml) were highest in t2 group and followed by 1.11 x 10(8) copies/ml for fibrobacter succinogenes (t2), 2.56 x 10(7) copies/ml for prevotella ruminicola (t1) and 1.25 x 10(7) copies/ml for ruminococcus albus (t4). in non-fibrolytic bacteria, the selenomonas ruminantium  (2.62 x 10(7) copies/ml) was predominant in group t3 and followed by treponema bryantii (2.52 x 10(7)copies/ml) in group t1, ruminobacter amylophilus (1.31 x 10(7)copies/ml) in group t1 and anaerovibrio lipolytica (2.58 x 10(6) copies/ml)  in group t4. it is most notable that r. flavefaciens were the highest in population in the rumen of surti buffalo fed wheat straw as roughage source.
TIHT== 
ABHT== 

PMID== 23624710
TI  == effects of vanillin, quillaja saponin, and essential oils on in vitro fermentation and protein-degrading microorganisms of the rumen.
AB  == this study investigated the effects of vanillin on methanogenesis and rumen fermentation, and the responses of ruminal protein-degrading bacteria to vanillin (at concentrations of 0, 0.76 and 1.52 g/l), essential oils (clove oil, 1 g/l; origanum oil, 0.50 g/l, and peppermint oil, 1 g/l), and quillaja saponin (at concentration of 0 and 6 g/l) in vitro. methane production, degradabilities of feed substrate, and ammonia concentration decreased linearly with increasing doses of vanillin. concentration of total volatile fatty acids also decreased, whereas proportion of butyrate tended to increase linearly with increasing doses  of vanillin. protozoa population decreased, but abundances of ruminococcus flavefaciens, prevotella bryantii, butyrivibrio fibrisolvens, prevotella ruminicola, clostridium aminophilum, and ruminobacter amylophilus increased with  increasing doses of vanillin. origanum and clove oils resulted in lower ammonia concentrations compared to control and peppermint oil. all the tested essential oils decreased abundances of protozoa, selenomonas ruminantium, r. amylophilus, p. ruminicola and p. bryantii, with the largest decrease resulted from origanum oil followed by clove oil and peppermint oil. the abundances of megasphaera elsdenii, c. aminophilum, and clostridium sticklandii were deceased by origanum oil while that of b. fibrisolvens was lowered by both origanum and clove oils. saponin decreased ammonia concentration and protozoal population, but increased the abundances of s. ruminantium, r. amylophilus, p. ruminicola, and p. bryantii, though the magnitude was small (less than one log unit). the results suggest that reduction of ammonia production by vanillin and saponin may not be caused by direct inhibition of major known proteolytic bacteria, and essential oils can have different inhibitory effects on different proteolytic bacteria, resulting in varying reduction in ammonia production.
TIHT== 
ABHT== 

PMID== 23216628
TI  == effect of non-starch-polysaccharide-degrading enzymes as feed additive on the rumen bacterial population in non-lactating cows quantified by real-time pcr.
AB  == the effects of non-starch-polysaccharide-degrading enzymes, added to a maize silage- and grass silage-based total mixed ration (tmr) at least 14 h before feeding, on the rumen bacterial population were investigated. six non-lactating holstein friesian cows were allocated to three treatment groups using a duplicate 3 x 3 latin square design with three 31-day periods (29 days of adaptation and 2  days of sampling). treatments were control tmr [69% forage and 31% concentrates on a dry matter (dm) basis] or tmr with 13.8 or 27.7 ml/kg of feed dm of roxazyme g2 liquid with activities (u/ml enzyme preparation) of xylanase 260 000, beta-glucanase 180 000 and cellulase 8000 (dsm nutritional products, basel, switzerland). the concentrations of 16s rdna of anaerovibrio lipolytica, fibrobacter succinogenes, prevotella ruminicola, ruminococcus flavefaciens, selenomonas ruminantium and treponema bryantii, and their relative percentage of  total bacteria in rumen samples obtained before feeding and 3 and 7 h after feeding and from two rumen fractions were determined using real-time pcr. sampling time had only little influence, but bacterial numbers and the composition of the population differed between the transition layer between rumen fluid and the fibre mat (fraction a) and the rumen fluid (fraction b) highlighting the importance to standardize sampling. the 16s rdna copies of total bacteria and the six bacterial species as well as the population composition were mainly unaffected by the high levels of exogenous enzymes supplemented at all sampling times and in both rumen fractions. occasionally, the percentages of the  non-fibrolytic species p. ruminicola and a. lipolytica changed in response to enzyme supplementation. some increases in the potential degradability of the diet and decreases in lag time which occurred collaterally indicate that other factors than changes in numbers of non-particle-associated bacteria are mainly responsible for the effects of exogenous enzymes.
TIHT== 
ABHT== 

PMID== 20585943
TI  == comparative genome analysis of prevotella ruminicola and prevotella bryantii: insights into their environmental niche.
AB  == the prevotellas comprise a diverse group of bacteria that has received surprisingly limited attention at the whole genome-sequencing level. in this communication, we present the comparative analysis of the genomes of prevotella ruminicola 23 (genbank: cp002006) and prevotella bryantii b(1)4 (genbank: adwo00000000), two gastrointestinal isolates. both p. ruminicola and p. bryantii  have acquired an extensive repertoire of glycoside hydrolases that are targeted towards non-cellulosic polysaccharides, especially gh43 bifunctional enzymes. our analysis demonstrates the diversity of this genus. the results from these analyses highlight their role in the gastrointestinal tract, and provide a template for additional work on genetic characterization of these species.
TIHT== 
ABHT== 

PMID== 20558310
TI  == diversity and abundance of the bacterial 16s rrna gene sequences in forestomach of alpacas (lama pacos) and sheep (ovis aries).
AB  == two bacterial 16s rrna gene clone libraries were constructed from the forestomach of alpacas and sheep fed alfalfa. after the amplification using the universal 16s rrna gene primers, equal quantities of pcr products from the same species were mixed and used to construct the two libraries. sequence analysis showed that the  60 clones from alpacas were divided into 27 phylotypes with 25% clones affiliated with eubacterium sp. f1. the 60 clones from sheep were divided into 21 phylotypes with 7 phylotypes affiliated with prevotella ruminicola (40% clones). clones closely related to clostridium proteoclasticum, eubacterium sp. f1, clostridium cellobioparum, mogibacterium neglectum, eubacterium ventriosum, clostridiaceae bacterium wn011, clostridium coccoides, clostridium orbiscindens, eubacterium sp. f1, cytophaga sp. dex80-37, treponema bryantii and pelotomaculum sp. fp were only found in the forestomach of alpacas, and those to anaerovorax odorimutans, treponema zioleckii, bifidobacterium indicum, paludibacter propionicigenes, paraprevotella clara, eubacterium siraeum, desulfotomaculum sp. cyp1, clostridium bolteae, clostridium termitidis and clostridiaceae bacterium djf_ls40 only in the rumen of sheep. quantitative real-time pcr revealed that the forestomach of alpacas had significantly lower density of bacteria, with bacterial 16s rrna gene copies (6.89 [log10 (copies per gram of wet weight)]), than that of sheep (7.71,  p<0.01). the two clone libraries also appeared different in shannon index (library from alpacas 3.30 and from sheep 3.04). our results showed that there were apparent differences in the bacterial diversity and abundance in the forestomach between alpacas and sheep.
TIHT== 
ABHT== 

PMID== 20163675
TI  == detection and identification of rumen bacteria constituting a fibrolytic consortium dominated by fibrobacter succinogenes.
AB  == a fibrolytic consortium, dominated by the rumen cellulolytic bacterium fibrobacter succinogenes, was artificially constructed on hay stems to detect and identify rumen bacteria that can potentially interact with f. succinogenes. consortium-bacterial members were determined by dgge and sequencing analysis targeted bacterial 16s rdna. an artificial consortium was formed in a 2-step incubation of hay stems; the first step with group 1, 2 or 3 f. succinogenes strains, the second step with rumen fluid. after consortium formation, morphologically different bacteria were observed in association with f. succinogenes. dgge exhibited more than 30 bands, the pattern of which depended on the f. succinogenes group. sequencing suggested that butyrivibrio fibrisolvens, pseudobutyrivibrio ruminis, clostridium sp., f. succinogenes group 2, prevotella  ruminicola and unclassified bacteroides were prominent in the group 1 consortium  and that treponema bryantii, b. fibrisolvens, acinetobacter sp, and wolinella succinogenes were prominent in the group 2 consortium. however, in the group 3 consortium, f. succinogenes-like bacteria were microscopically undetectable, whereas cellulolytic ruminococcus albus and f. succinogenes group 1 were prominent, suggesting that the group 3 cannot be a core member of this consortium. this study is the first attempt to identify bacterial members of a fibrolytic consortium dominated by a specific bacterium.
TIHT== 
ABHT== 

PMID== 20158525
TI  == genetic diversity and diet specificity of ruminal prevotella revealed by 16s rrna gene-based analysis.
AB  == 16s rrna gene-based analysis of rumen prevotella was carried out to estimate the  diversity and diet specificity of bacteria belonging to this genus. total dna was extracted from the rumen digesta of three sheep fed two diets with different hay-to-concentrate ratios (10 : 1 and 1 : 2). real-time pcr quantification of prevotella revealed that the relative abundance of this genus in the total rumen  bacteria was up to 19.7%, while the representative species prevotella bryantii and prevotella ruminicola accounted for only 0.6% and 3.8%, respectively. denaturing gradient gel electrophoresis analysis for prevotella revealed shifts in the community composition with the diet. analysis of 16s rrna gene clone libraries showed significant differences (p=0.001) between clones detected from the sheep on the diets with different hay-to-concentrate ratios. the majority (87.8%) of prevotella clones had <97% sequence similarity with known rumen prevotella. these data suggest that uncultured prevotella is more abundant than known prevotella and that members of this genus appear to have specific metabolic niches.
TIHT== 
ABHT== 

PMID== 18839246
TI  == biotransformation of 2,4,6-trinitrotoluene by pure culture ruminal bacteria.
AB  == twenty-one ruminal bacteria species were tested for their ability to degrade 2,4,6-trinitrotoluene (tnt) within 24 h. butyrivibrio fibrisolvens, fibrobacter succinogenes, lactobacillus vitulinus, selenomonas ruminantium, streptococcus caprinus, and succinivibrio dextrinosolvens were able to completely degrade 100 mg/l tnt, with <5% of the original tnt recovered as diaminonitrotoluene metabolites. eubacterium ruminantium, lactobacillus ruminis, ruminobacter amylophilus, streptococcus bovis, and wolinella succinogenes were able to completely degrade 100 mg/l tnt, with 23-60% of the tnt recovered as aminodinitrotoluene and/or diaminonitrotoluene metabolites. clostridium polysaccharolyticum, megasphaera elsdenii, prevotella bryantii, prevotella ruminicola, ruminococcus albus, and ruminococcus flavefaciens were able to degrade 80-90% of 100 mg/l tnt. desulfovibrio desulfuricans subsp. desulfuricans, prevotella albensis, and treponema bryantii degraded 50-80% of the tnt. anaerovibrio lipolytica was completely inhibited by 100 mg/l tnt. these results indicate that a variety of rumen bacteria is capable of transforming tnt.
TIHT== 
ABHT== 

PMID== 18661292
TI  == effect of sodium monensin and cinnamaldehyde on the growth and phenotypic characteristics of prevotella bryantii and prevotella ruminicola.
AB  == two representative strains of gram-negative rumen bacteria from the genus prevotella were used as model organisms in order to evaluate the effect of cinnamaldehyde (the secondary metabolite found in extracts of the cinnamomum family) vs. sodium monensin on growth, cell size and cell protein production. prevotella bryantii b(1)4 was found to be remarkably more resistant to the action of both compounds than prevotella ruminicola 23. the approximate ic(50) concentrations of sodium monensin influenced the increase in cell size of both strains during growth, which was much more pronounced in the case of the b(1)4 strain. a similar effect was observed in strain b(1)4 when 1.438 mmol/l cinnamaldehyde was added to the growth medium, indicating a possible interference with cell division. the action of cinnamaldehyde on p. bryantii b(1)4 was concentration-dependent, in contrast to the effect observed on p. ruminicola 23.
TIHT== 
ABHT== 

PMID== 17235560
TI  == dominance of prevotella and low abundance of classical ruminal bacterial species  in the bovine rumen revealed by relative quantification real-time pcr.
AB  == relative quantification real-time pcr was used to quantify several bacterial species in ruminal samples from two lactating cows, each sampled 3 h after feeding on two successive days. abundance of each target taxon was calculated as  a fraction of the total 16s rrna gene copies in the samples, using taxon-specific and eubacterial domain-level primers. bacterial populations showed a clear predominance of members of the genus prevotella, which comprised 42% to 60% of the bacterial rrna gene copies in the samples. however, only 2% to 4% of the bacterial rrna gene copies were represented by the classical ruminal prevotella species prevotella bryantii, prevotella ruminicola and prevotella brevis. the proportion of rrna gene copies attributable to fibrobacter succinogenes, ruminococcus flavefaciens, selenomonas ruminantium and succinivibrio dextrinosolvens were each generally in the 0.5% to 1% range. proportions for ruminobacter amylophilus and eubacterium ruminantium were lower (0.1% to 0.2%), while butyrivibrio fibrisolvens, streptococcus bovis, ruminococcus albus and megasphaera elsdenii were even less abundant, each comprising <0.03% of the bacterial rrna gene copies. the data suggest that the aggregate abundance of the  most intensively studied ruminal bacterial species is relatively low and that a large fraction of the uncultured population represents a single bacterial genus.
TIHT== 
ABHT== 

PMID== 16887612
TI  == degradation and utilization of xylans by the rumen anaerobe prevotella bryantii (formerly p. ruminicola subsp. brevis) b(1)4.
AB  == freshly harvested whole cells from cultures of p. bryantii b(1)4 grown with oat spelt xylan (osx) as an energy source showed less than 25% of the enzyme activity against osx, and less than 15% of the activity against birchwood xylan (bwx) and  carboxymethylcellulose, that was detectable in sonicated cell preparations. this  indicates that much of this hydrolytic activity is either periplasmic, membrane-associated or intracellular and may be concerned with the processing of  transported oligosaccharides.p. bryantii b(1)4 cultures were able to utilise up to 45% and 51% of the total pentose present in osx and bwx, respectively, after 24 h, but could utilize 84% of a water-soluble fraction of bwx. analysis of the xylan left undegraded after incubation with p. bryantii showed that while xylose  and arabinose were removed to a similar extent, uronic acids were utilized to a greater extent than xylose. predigestion of xylans with two cloned xylanases from the cellulolytic rumen anaerobe ruminococcus flavefaciens gave little increase in overall pentose utilization suggesting that external p. bryantii xylanases are as effective as the cloned r. flavefaciens enzymes in releasing products that can be utilised by p. bryantii cells. the xylanase system of p. bryantiiis able to efficiently utilise not only xylo-oligosaccharides but also larger water-soluble  xylan fragments.
TIHT== 
ABHT== 

PMID== 15936894
TI  == type ii restriction modification systems of prevotella bryantii tc1-1 and prevotella ruminicola 23 strains and their effect on the efficiency of dna introduction via electroporation.
AB  == the restriction endonucleases pbrti and pru2i, isoschizomers of sau3ai and haeiii, were partially purified and characterized from anaerobic rumen bacteria prevotella bryantii tc1-1 and prevotella ruminicola 23, respectively. these are the first type ii restriction endonucleases discovered in strains of the genus prevotella, and they represent one of the barriers hindering gene transfer in these microorganisms. heterologous dna was protected against the action of the pbrti or pru2i by incubation in a cell-free extract of the respective strain which contained 20 mm edta. this led to the development of a protocol enabling successful electrotransformation of the p. bryantii tc1-1 strain with a prh3 bacteroides--escherichia coli shuttle vector containing up to 7-kb long dna inserts. plasmid dna isolated from the transformed strain facilitated the transfer with further increased efficiency and made possible the introduction of  ligation reaction products directly to p. bryantii tc1-1 without passing them first through e. coli.
TIHT== 
ABHT== 

PMID== 15297916
TI  == influence of dipeptidyl peptidase inhibitors on growth, peptidase activity, and ammonia production by ruminal microorganisms.
AB  == the aim was to investigate known and potential new inhibitiors of dipeptidyl peptidases (dpp) for their effects on ruminal microorganisms. gly-phe diazomethylketone (gpd), ala-ala chloromethylketone (aac), benserazide (dl-serine 2-(2,3,4- trihydroxybenzyl) hydrazide), and diprotin a (ile-pro-ile) inhibited dpp activities of prevotella albensis, p. ruminicola, p. bryantii, p. brevis, and mixed ruminal microorganisms, though incompletely and, except for diprotin a, without absolute specificity for any of the peptidases. leucine aminopeptidase activity of streptococcus bovis was also inhibited by gpd and benserazide. the inhibitors had no effect on the growth of the bacteria, except for gpd, which inhibited growth of p. albensis when only peptides were available for growth. benserazide had some inhibitory effects on the growth of megasphaera elsdenii and prevotella spp., even in the absence of peptides. the predatory activity of ciliate protozoa on bacteria was unaffected by dpp inhibitors. ammonia production from casein by mixed ruminal microorganisms was inhibited significantly (p < 0.05) by aac (29% inhibition) and benserazide (33%). it was concluded that dpp inhibitors can influence the rate of nh3 production in the rumen and may form the basis for developing protein-sparing feed additives for ruminants.
TIHT== 
ABHT== 

PMID== 11501487
TI  == molecular monitoring of ruminal prevotellas.
AB  == the development and preliminary use of two different molecular approaches for rapid enumeration and monitoring of ruminal prevotellas are described. several oligonucleotide dna probes, specific for the genus prevotella and the species p.  ruminicola and p. bryantii were labeled with various fluorochromes and used in in situ hybridization experiments. epifluorescent microscopy was successfully used for the detection of fluorescent signal emitted by the probes in pure and mixed culture samples. the enumeration of the target cells and the analysis of the crude rumen fluid proved to be difficult, however, mainly due to the autofluorescent background and nonhomogeneous distribution of the cells on the microscope slide. the development of a competitive pcr system for ruminal prevotellas is described and the preliminary results of the rumen fluid analysis  from a black-and-white holstein cow are given.
TIHT== 
ABHT== 

PMID== 11375193
TI  == diet-dependent shifts in the bacterial population of the rumen revealed with real-time pcr.
AB  == a set of pcr primers was designed and validated for specific detection and quantification of prevotella ruminicola, prevotella albensis, prevotella bryantii, fibrobacter succinogenes, selenomonas ruminantium-mitsuokella multiacida, streptococcus bovis, ruminococcus flavefaciens, ruminobacter amylophilus, eubacterium ruminantium, treponema bryantii, succinivibrio dextrinosolvens, and anaerovibrio lipolytica. by using these primers and the real-time pcr technique, the corresponding species in the rumens of cows for which the diet was switched from hay to grain were quantitatively monitored. the  dynamics of two fibrolytic bacteria, f. succinogenes and r. flavefaciens, were in agreement with those of earlier, culture-based experiments. the quantity of f. succinogenes dna, predominant in animals on the hay diet, fell 20-fold on the third day of the switch to a grain diet and further declined on day 28, with a 57-fold reduction in dna. the r. flavefaciens dna concentration on day 3 declined to approximately 10% of its initial value in animals on the hay diet and remained at this level on day 28. during the transition period (day 3), the quantities of  two ruminal prevotella dnas increased considerably: that of p. ruminicola increased 7-fold and that of p. bryantii increased 263-fold. on day 28, the quantity of p. ruminicola dna decreased 3-fold, while p. bryantii dna was still elevated 10-fold in comparison with the level found in animals on the initial hay diet. the dna specific for another xylanolytic bacterium, e. ruminantium, dropped 14-fold during the diet switch and was maintained at this level on day 28. the concentration of a rumen spirochete, t. bryantii, decreased less profoundly and stabilized with a sevenfold decline by day 28. the variations in a. lipolytica dna were not statistically significant. after an initial slight increase in s. dextrinosolvens dna on day 3, this dna was not detected at the end of the experiment. s. bovis dna displayed a 67-fold increase during the transition period on day 3. however, on day 28, it actually declined in comparison with the  level in animals on the hay ration. the amount of s. ruminantium-m. multiacida dna also increased eightfold following the diet switch, but stabilized with only  a twofold increase on day 28. the real-time pcr technique also uncovered differential amplification of rumen bacterial templates with the set of universal bacterial primers. this observation may explain why some predominant rumen bacteria have not been detected in pcr-generated 16s ribosomal dna libraries.
TIHT== 
ABHT== 

PMID== 10919398
TI  == phenotypic characterization of polysaccharidases produced by four prevotella type strains.
AB  == four ruminal prevotella type strains, p. ruminicola jcm8958t, p. bryantii b 4t, p. albensis m384t, and p. brevis atcc19188t, were characterized for polysaccharide-degrading activities with the reducing sugar release assay and zymogram analyses. carboxymethylcellulase, xylanase, and polygalacturonate (pg)-degrading enzyme activities were determined in cultures grown on oat spelt xylan, xylose, arabinose, cellobiose, and glucose as sole growth substrates. p. ruminicola and p. albensis showed carboxymethylcellulase induction patterns. when xylan was supplied as a sole growth substrate, xylanase activities produced by p. bryantii and p. albensis were at least 18- and 11-fold higher, respectively, than during growth on other carbohydrates, suggesting that the regulation of the xylanases was highly specific to xylan. all strains constitutively produced pg-degrading enzymes. the corresponding activity of p. bryantii was more than 40-fold higher than in other strains. zymogram analyses routinely detected the presence of high-molecular-weight (100-170 kda) polysaccharide-degrading enzymes  in ruminal prevotella. characteristics of the polysaccharide-degrading activities showed diversity of ruminal prevotella species.
TIHT== 
ABHT== 

PMID== 10679051
TI  == variations in the ability of ruminal gram-negative prevotella species to resist monensin.
AB  == gram-negative, ruminal prevotella strains (n = 15) differed greatly in their sensitivity to the feed additive monensin. strains that were repeatedly transferred with sublethal doses tolerated more monensin than those that were unadapted, but growth experiments indicated that the sensitivity range was as great as 2000-fold. prevotella bryantii b(1)4 grew with monensin concentrations as high as 20 microm, but p. ruminicola h15a, d31d, 20-63, e40a, and d42f never initiated growth if monensin was greater than 0.01 microm. washed cell preparations that were energized with glucose lost intracellular potassium when monensin was added, and potassium depletion could also be used as an index of monensin sensitivity. adapted cells of p. bryantii b(1)4 had a half-maximal potassium depletion constant (k(d)) of 3.2 microm, but the k(d) values of p. ruminicola strains h15a, d31d, 20-63, e40a, and d42f were less than 0.04 microm.  maximal potassium depletion (k(max)) values range from 90% to 40%, and monensin-adapted cells always had lower k(max) values than unadapted cells. a linear regression of log k(d)/k(max) versus percentage decrease in optical density divided by monensin concentration had an r(2) of 0.75, and this regression indicated that potassium depletion from washed cells closely correlated with growth inhibition. p. bryantii b(1)4 had a k(d)/k(max) ratio that was sevenfold greater than other prevotella strains, and this result indicated that p. bryantii may be unusual in its ability to grow with very high concentrations of monensin.
TIHT== 
ABHT== 

PMID== 10922505
TI  == unravelling the genetic diversity of ruminal bacteria belonging to the cfb phylum.
AB  == molecular biology approaches were employed to examine the genetic diversity of bacteria from the cytophaga/flexibacter/bacteroides (cfb) phylum in the rumen of  cattle. by this means we were able to identify cultured strains that represent some of the larger cfb clusters previously identified only by pcr amplification and sequencing. complete 16s rdna sequences were obtained for 16 previously isolated rumen strains, including the type strains of prevotella ruminicola, p. bryantii, p. brevis and p. albensis to represent a wide range of diversity. phylogenetic analysis of cultured strains revealed the existence of three clusters of ruminal cfb: (i) a cluster of prevotella strains, which have been found only in the rumen, including the two type strains, p. brevis ga33(t) and p. ruminicola 23(t); (ii) prevotella spp. that cluster with prevotellas from other ecological niches such as the oral cavity and which include the type strains, p.  bryantii b(1)4(t) and p. albensis m384(t); (iii) two bacteroides spp. strains clustering with b. forsythus of oral origin. in order to establish whether the cultivated isolates cover the whole range of ruminal cfb genetic diversity, 16s rrna gene sequences were amplified and cloned from dna extracted from the same rumen samples (one cow in slovenia, one in scotland and three in japan). sequencing and phylogenetic analysis of 16s rrna genes confirmed the existence of two superclusters of ruminal prevotella, one exclusively ruminal and the other including non-ruminal species. in the case of ruminal bacteroides spp., however,  phylogenetic analysis revealed the existence of three new superclusters, one of which has as yet no cultivable counterpart. interestingly, these bacteroides clusters were represented almost exclusively by clone libraries from the japanese cattle and only three sequences were from the european cattle. this study agrees  with previous analyses in showing that rumen prevotella/bacteroides strains exhibit a remarkable degree of genetic diversity and suggests that different strain groupings may differ greatly in their recovery by cultural methods. the most important conclusion, however, is that cultured strains can be identified that represent some of the larger clusters previously identified only by pcr amplification and sequencing.
TIHT== 
ABHT== 

PMID== 10486053
TI  == diversity of extracellular proteolytic activities among prevotella species from the rumen.
AB  == the current research was aimed at comparing proteolytic activities among ruminal  prevotella spp. growth rates of prevotella sp. 2202, prevotella ruminicola d31d,  p. brevis ga33, p. albensis m384, and p. bryantii b(1)4 varied with n source, and no one n source produced the fastest growth in all species. proteolytic activity  was greatest with casein compared with peptides, aa, and nh(4)cl in all species.  proteolytic activity of prevotella sp. 2202, p. brevis ga33, and p. bryantii b(1)4 was modulated by n source. with gelatin co-polymerized sds-page, the extracellular activities of the prevotella spp. showed wide variation in number,  size, and type of proteases. prevotella sp. 2202 and p. albensis m384 produced metalloproteases of low molecular weight (40 kda). p. ruminicola d31d produced one cysteine protease (100-200 kda) and two metalloproteases (90-100 kda). p. brevis ga33 generated a diffuse clearing zone (95-160 kda) containing serine, cysteine, and metalloproteases. p. bryantii b(1)4 produced a metalloprotease greater than 200 kda in size. the molecular sizes provided are estimations and served only to differentiate among the bacterial species in this study. large variations in proteolytic activities among species and the known genetic diversity of the prevotella taxon suggested that targeting this bacterial assemblage for genetic manipulation in order to alter the bacterial impact on ruminal protein degradation would be difficult.
TIHT== 
ABHT== 

PMID== 9251223
TI  == glutamate dehydrogenase activity profiles for type strains of ruminal prevotella  spp.
AB  == the glutamate dehydrogenase (gdh) activities for the type strains of prevotella ruminicola (strain 23), prevotella brevis (strain ga33), and prevotella bryantii  (strain b(1)4) were assessed by a combination of enzyme assays and analysis of migration patterns of gdh proteins following nondenaturing polyacrylamide gel electrophoresis. unlike results with most other prokaryotes, but similar to results with other members of the family bacteroidaceae, nadph-utilizing specific activity was greatest in all species following ammonia-limited growth. similar also to previous findings with p. bryantii, the nad(p)h-utilizing gdh activity of p. ruminicola can be attributed to a single protein. however, p. brevis produces  an additional gdh protein(s) in response to growth with peptides. these results conclusively demonstrate that all type strains of the ruminal prevotella sp. grouping possess gdh activity.
TIHT== 
ABHT== 

PMID== 9103611
TI  == phenotypic diversity among ruminal isolates of prevotella ruminicola: proposal of prevotella brevis sp. nov., prevotella bryantii sp. nov., and prevotella albensis sp. nov. and redefinition of prevotella ruminicola.
AB  == selected phenotypic characteristics of isolates of prevotella ruminicola (formerly bacteroides ruminicola) were studied in order to establish whether the  characteristics of genotypic strain groups established previously on the basis of 16s ribosomal dna sequences differed systematically. among strains formerly considered p. ruminicola subsp. brevis, strains related to strain ga33t (t = type strain) typically failed to produce carboxymethyl cellulase (cmcase) activity detectable by plate assays and failed to ferment xylose, while strains related to strain b14t produced abundant cmcase and fermented xylose. we propose that strains related to ga33t, which have dna g + c contents between 45 and 51 mol%, should be assigned to a new species, prevotella brevis, and that strains related  to b14t, which have dna g + c contents between 39 and 43 mol%, should be assigned to another new species, prevotella bryantii. most of the isolates formerly classified as p. ruminicola subsp. ruminicola strains produced cmcase and had dna g + c contents between 45 and 51 mol%, and we propose that these organisms should be placed in the redefined species p. ruminicola. a small group of isolates that  have lower g + c contents are assigned to another new species, prevotella albensis. most p. brevis and p. bryantii strains produced abundatn extracellular  dnase activity. proteinase activities (as determined by [14c]casein hydrolysis) varied widely between strains, and p. brevis strains exhibited the highest mean activity. all strains produced dipeptidyl peptidase activity, but the relative activities against different peptide substrates exhibited by p. bryantii, p. albensis, and p. brevis differed systematically. the phenotypic differences among the newly defined species suggest that they may occupy distinct niches within the rumen ecosystem.
TIHT== 
ABHT== 

