@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 22324467
TI  == impact of periodontal therapy on the subgingival microbiota of severe periodontitis: comparison between good responders and individuals with refractory periodontitis using the human oral microbe identification microarray.
AB  == background: this study compares the changes to the subgingival microbiota of individuals with "refractory" periodontitis (rp) or treatable periodontitis (good responders [gr]) before and after periodontal therapy by using the human oral microbe identification microarray (homim) analysis. methods: individuals with chronic periodontitis were classified as rp (n = 17) based on mean attachment loss (al) and/or >3 sites with al >/=2.5 mm after scaling and root planing, surgery, and systemically administered amoxicillin and metronidazole or as gr (n  = 30) based on mean attachment gain and no sites with al >/=2.5 mm after treatment. subgingival plaque samples were taken at baseline and 15 months after  treatment and analyzed for the presence of 300 species by homim analysis. significant differences in taxa before and post-therapy were sought using the wilcoxon test. results: the majority of species evaluated decreased in prevalence in both groups after treatment; however, only a small subset of organisms was significantly affected. species that increased or persisted in high frequency in  rp but were significantly reduced in gr included bacteroidetes sp., porphyromonas endodontalis, porphyromonas gingivalis, prevotella spp., tannerella forsythia, dialister spp., selenomonas spp., catonella morbi, eubacterium spp., filifactor alocis, parvimonas micra, peptostreptococcus sp. ot113, fusobacterium sp. ot203,  pseudoramibacter alactolyticus, streptococcus intermedius or streptococcus constellatus, and shuttlesworthia satelles. in contrast, capnocytophaga sputigena, cardiobacterium hominis, gemella haemolysans, haemophilus parainfluenzae, kingella oralis, lautropia mirabilis, neisseria elongata, rothia  dentocariosa, streptococcus australis, and veillonella spp. were more associated  with therapeutic success. conclusion: persistence of putative and novel periodontal pathogens, as well as low prevalence of beneficial species was associated with chronic refractory periodontitis.
TIHT== 
ABHT== 

PMID== 19722792
TI  == comparisons of subgingival microbial profiles of refractory periodontitis, severe periodontitis, and periodontal health using the human oral microbe identification microarray.
AB  == background: this study compared the subgingival microbiota of subjects with refractory periodontitis (rp) to those in subjects with treatable periodontitis (grs = good responders) or periodontal health (ph) using the human oral microbe identification microarray (homim). methods: at baseline, subgingival plaque samples were taken from 47 subjects with periodontitis and 20 individuals with ph and analyzed for the presence of 300 species by homim. the subjects with periodontitis were classified as having rp (n = 17) based on mean attachment loss (al) and/or more than three sites with al >or=2.5 mm after scaling and root planing, surgery, and systemically administered amoxicillin and metronidazole or  as grs (n = 30) based on mean attachment gain and no sites with al >or=2.5 mm after treatment. significant differences in taxa among the groups were sought using the kruskal-wallis and chi(2) tests. results: more species were detected in patients with disease (gr or rp) than in those without disease (ph). subjects with rp were distinguished from grs or those with ph by a significantly higher frequency of putative periodontal pathogens, such as parvimonas micra (previously peptostreptococcus micros or micromonas micros), campylobacter gracilis, eubacterium nodatum, selenomonas noxia, tannerella forsythia (previously t. forsythensis), porphyromonas gingivalis, prevotella spp., treponema spp., and eikenella corrodens, as well as unusual species (pseudoramibacter alactolyticus,  tm7 spp. oral taxon [ot] 346/356, bacteroidetes sp. ot 272/274, solobacterium moorei, desulfobulbus sp. ot 041, brevundimonas diminuta, sphaerocytophaga sp. ot 337, shuttleworthia satelles, filifactor alocis, dialister invisus/pneumosintes,  granulicatella adiacens, mogibacterium timidum, veillonella atypica, mycoplasma salivarium, synergistes sp. cluster ii, and acidaminococcaceae [g-1] sp. ot 132/150/155/148/135) (p <0.05). species that were more prevalent in subjects with ph than in patients with periodontitis included actinomyces sp. ot 170, actinomyces spp. cluster i, capnocytophaga sputigena, cardiobacterium hominis, haemophilus parainfluenzae, lautropia mirabilis, propionibacterium propionicum, rothia dentocariosa/mucilaginosa, and streptococcus sanguinis (p <0.05). conclusion: as determined by homim, patients with rp presented a distinct microbial profile compared to patients in the gr and ph groups.
TIHT== 
ABHT== 

PMID== 18436030
TI  == microbial analysis of canals of root-filled teeth with periapical lesions using polymerase chain reaction.
AB  == the objective of the present study was to investigate the presence of nine bacterial species in root-filled teeth associated with periapical lesions using a polymerase chain reaction analysis and to correlate these species with clinical features of the cases. dna was extracted from 45 canal samples of root-filled teeth with periapical lesions. a pcr assay using species-specific primers of 16s  rdna and the downstream intergenic spacer region was used for microbial detection. enterococcus faecalis was the most prevalent species, detected in 77.8% of the study teeth, followed by peptostreptococcus micros, detected in 51.1%. porphyromonas gingivalis, porphyromonas endodontalis, prevotella intermedia, and prevotella nigrescens were detected in 35.6%, 22.2%, 11.1%, and 11.1% of the sampled teeth, respectively. moreover, pcr detected filifactor alocis in 26.7%, treponema denticola in 24.4%, and tannerella forsythia in 4.4% of the samples. t. denticola and p. micros were statistically associated with tenderness to percussion (p < 0.05). p. nigrescens was associated with the presence of spontaneous pain and abscess (p < 0.05). p. endodontalis and p. nigrescens were associated with purulent exudates (p < 0.05). synergistic relationship was also observed between some species. the results of this study indicated that e. faecalis was the most frequently identified test species by pcr in teeth with failing endodontic treatment.
TIHT== 
ABHT== 

PMID== 16476021
TI  == molecular analysis of bacteria in asymptomatic and symptomatic endodontic infections.
AB  == the purpose of the present study was to use terminal restriction fragment length  polymorphism analysis and the 16s rrna gene clone library to investigate the diversity of the microbiota associated with asymptomatic and symptomatic endodontic infections and to compare the bacterial community structure in these two clinical conditions. samples were taken from asymptomatic endodontic infections associated with chronic periradicular lesions and from symptomatic infections clinically diagnosed as acute abscesses. 16s rrna genes from dna isolated from clinical samples were used to construct clone libraries or were subjected to terminal restriction fragment length polymorphism analysis. sequence analysis of 186 clones revealed 42 taxa; 23 (55%) were uncultivated phylotypes, of which seven were unique to endodontic infections. clone sequencing and terminal restriction fragment length polymorphism analysis revealed that the most commonly detected taxa were fusobacterium nucleatum (including terminal restriction fragment types 1 and 2), peptostreptococcus micros/peptostreptococcus sp. oral clone aj062/bs044/fg014, prevotella species, dialister species, mogibacterium species, lachnospiraceae oral clone 55a-34, filifactor alocis, megasphaera sp. oral clone cs025/bs073, and veillonella sp. oral clone bp1-85/veillonella dispar/v. parvula. bacteroides-like sp. oral clone x083/bacteroidales oral clone mce7_20 and dialister sp. oral clone bs016/mce7_134 were detected only in asymptomatic teeth. on the other hand, f. nucleatum terminal restriction fragment type 2, prevotella intermedia, dialister pneumosintes, and some phylotypes were exclusively detected in symptomatic samples. bacterial profiles of symptomatic endodontic infections generated by terminal restriction fragment length polymorphism analysis were clearly different from those of asymptomatic infections. overall, the average number of terminal restriction fragments in symptomatic samples was significantly larger than in asymptomatic samples. molecular analysis of the microbiota associated with symptomatic or asymptomatic endodontic infections indicates that the endodontic bacterial diversity is greater than previously described by culture methods and that the structure of the microbiota differ significantly between asymptomatic and symptomatic infections.
TIHT== 
ABHT== 

