@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23498179
TI  == monitoring the succession of the biota grown on a selective medium for pseudomonads during storage of minced beef with molecular-based methods.
AB  == in the present study, the succession of the biota grown on a selective medium for pseudomonads (pseudomonas agar based medium - pab) during the storage of meat under different conditions was monitored. thus, minced beef was stored aerobically and under modified atmosphere packaging in the presence (map+) and absence (map-) of oregano essential oil at 0, 5, 10 and 15 degrees c. a total of  267 pure cultures were recovered from pab throughout the storage period and subjected to pcr-denaturing gradient gel electrophoresis (pcr-dgge) for their differentiation. in parallel, the direct analysis of the whole cultivable community (wcc) from the same medium was applied. these two approaches were used  in order to indicate the lack of selectivity. fifteen different dgge fingerprints were obtained after pcr - dgge analysis of the isolates, which were assigned to pseudomonas putida (3 fingerprints), pseudomonas fragi and pseudomonas fluorescens, pseudomonas spp., serratia liquefaciens (2), citrobacter freundii, serratia grimesii, hafnia alvei (3), rahnella spp. and morganella morganii. twelve of them occurred during the direct analysis of the wcc. the biota succession found to be affected from the different storage conditions. however, the outcome of the two strategies was quite different, which is leading to the use of different appropriated molecular approaches in order to widen the knowledge of bacterial succession of meat.
TIHT== 
ABHT== 

PMID== 18944847
TI  == occurrence of indole-3-acetic acid-producing bacteria on pear trees and their association with fruit russet.
AB  == abstract a relatively high percentage of epiphytic bacteria on pear leaf and fruit surfaces had the ability to produce indole-3-acetic acid (iaa) in culture media supplemented with tryptophan. while over 50% of the strains produced at least small amounts of iaa in culture, about 25% of the strains exhibited high iaa production as evidenced by both colorimetric and high-performance liquid chromatography analysis of culture supernatants. a majority of the strains that produced high amounts of iaa were identified as erwinia herbicola (pantoea agglomerans), while some strains of pseudomonas syringae, pseudomonas viridiflava, pseudomonas fluorescens, pseudomonas putida, and rahnella aquaticus  that produced high amounts of iaa also were found on pear. fruit russeting was significantly increased in 39 out of 46 trials over an 8-year period in which iaa-producing bacteria were applied to trees compared with control trees. a linear relationship was observed between fruit russet severity and the logarithm  of the population size of different iaa-producing bacteria on trees in the 30 days after inoculation, when normalized for the amount of iaa produced by each strain in culture. on average, the severity of fruit russet was only about 77% that on control trees when trees were treated at the time of bloom with pseudomonas fluorescens strain a506, which does not produce iaa. both total bacterial populations on pear in the 30-day period following full bloom and fruit russet severity varied greatly from year to year and in different commercial orchards over a 10-year period. there was a strong linear correlation between the logarithm of total bacterial population sizes and fruit russet severity.
TIHT== 
ABHT== 

PMID== 12324317
TI  == differences in attachment of salmonella enterica serovars and escherichia coli o157:h7 to alfalfa sprouts.
AB  == numerous salmonella enterica and escherichia coli o157:h7 outbreaks have been associated with contaminated sprouts. we examined how s. enterica serovars, e. coli serotypes, and nonpathogenic bacteria isolated from alfalfa sprouts grow on  and adhere to alfalfa sprouts. growth on and adherence to sprouts were not significantly different among different serovars of s. enterica, but all s. enterica serovars grew on and adhered to alfalfa sprouts significantly better than e. coli o157:h7. e. coli o157:h7 was essentially rinsed from alfalfa sprouts with repeated washing steps, while 1 to 2 log cfu of s. enterica remained attached per sprout. s. enterica newport adhered to 3-day-old sprouts as well as  pantoea agglomerans and 10-fold more than pseudomonas putida and rahnella aquatilis, whereas the growth rates of all four strains throughout seed sprouting were similar. s. enterica newport and plant-associated bacteria adhered 10- to 1,000-fold more than e. coli o157:h7; however, three of four other e. coli serotypes, isolated from cabbage roots exposed to sewage water following a spill, adhered to sprouts better than e. coli o157:h7 and as well as the pseudomonas and rahnella strains. therefore, attachment to alfalfa sprouts among e. coli serotypes is variable, and nonpathogenic strains of e. coli to be used as surrogates for the study of pathogenic e. coli may be difficult to identify and should be selected carefully, with knowledge of the biology being examined.
TIHT== 
ABHT== 

PMID== 11131069
TI  == role of yersinia intermedia and pseudomonas putida in the development of a fruity off-flavour in pasteurized milk.
AB  == analysis by gas chromatography-mass spectrometry of pasteurized milk with a fruity (pineapple like) off odour and a sour, rancid and soapy taste indicated the presence of concentrations at microg/ml levels of ethyl butanoate, ethyl hexanoate, ethyl octanoate, ethyl decanoate, octanoic acid, decanoic acid and dodecanoic acid. the off-odour and taste were attributed to the presence of these compounds in the milk. microbiological examination confirmed that the milk was also contaminated with a series of psychrotrophic bacteria including yersinia intermedia, pseudomonas putida and rahnella aquatilis. growth of isolates of these bacteria in uht milk at 23 degrees c for 7 d showed that yer. intermedia produced significant quantities of the c4-c12 alkanoic acids; ps. putida produced only small quantities of these acids and rah. aquatilis produced none. in addition, yer. intermedia and ps. putida also produced small but significant quantities of the corresponding ethyl esters. in milk inoculated with both yer. intermedia and ps. patida, the quantity of ethyl esters produced was greater than that found in cultures containing only one of the isolates. these studies indicated that yer. intermedia was the principal source of the alkanoic acids in  the tainted milk and that the major producer of the corresponding ethyl esters was ps. patida. this is the first report that yer. intermedia and ps. putida can  cause an off-odour or taste in dairy products.
TIHT== 
ABHT== 

