@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25533144
TI  == nature of the antimicrobial activity of lactobacillus caseibifidobacterium bifidum and bifidobacterium animalis against foodborne pathogenic and spoilage microorganisms.
AB  == the antimicrobial activities as well as the nature of the inhibitory compounds obtained from lactobacillus casei, bifidobacterium bifidum and bifidobacterium animalis strains were assayed on foodborne pathogenic - staphyloccoccus aureus subsp. aureus (ccug atcc(r) 25926) and escherichia coli (atcc(r) 25922) - and spoilage microorganisms - pseudomonas aeruginosa (atcc(r) 27853). test producer strains showed inhibitory effect on all indicator microorganisms in diffusion of  cell-free concentrated supernatant by agar in well methods (10.0-22.5 mm) in periods of 24, 48 and 72 h. inhibitory compounds showed no sensitivity to the action of proteolytic enzyme trypsin and were completely inactivated by adjusting the ph of the cell-free 20 x concentrated supernatant to 7.0. the results demonstrated that antimicrobial substances do not have proteinaceous nature and are caused by the action of organic acids with decreasing medium ph.
TIHT== 
ABHT== 

PMID== 23538205
TI  == in vitro assessment of functional properties of lactic acid bacteria isolated from faecal microbiota of healthy dogs for potential use as probiotics.
AB  == lactic acid bacteria were isolated and identified in the faeces of chinese crested and yorkshire terrier pups and their probiotic features were investigated in vitro. thirty seven isolates were identified as lactobacillus or enterococcus. out of these isolates, 31 were lactic acid bacteria (lab) and belonged to the species lactobacillus reuteri (16/37; 43.3%), lactobacillus animalis (7/37; 18.9%), lactobacillus acidophilus (3/37; 8.1%), lactobacillus sanfranciscensis (2/37; 5.4%), lactobacillus murinus (2/37; 5.4%), and lactobacillus paraplantarum (1/37; 2.7%), while six other lab isolates were enterococcus spp. (6/37; 16.2%).  strains were tested for resistance to gastric acidity (ph 2.5 for 3 h) and bile salts (0.3% ox gall), cell surface hydrophobicity by microbial adhesion to solvents, antagonism against pathogenic bacteria (staphylococcus aureus, enterococcus faecalis, bacillus cereus, pseudomonas aeruginosa, escherichia coli, salmonella enterica serovar typhimurium and listeria monocytogenes), production of hydrogen peroxide, and antibiotic susceptibility. thirty four strains were highly resistant to acidic conditions with slight (18 strains) to moderate (16 strains) growth inhibition by bile salts. seven isolates had highly hydrophobic cellular surfaces and 28 strains exhibited strong antagonism against the bacterial pathogens tested, although 8 isolates tested against leptospira interrogans had no effect on pathogen growth. all isolates produced low rates of  hydrogen peroxide. based on these results, two lactobacillus strains showed promising probiotic-related features and merit investigation as probiotics for dogs.
TIHT== 
ABHT== 

PMID== 21740724
TI  == incorporation of probiotic bacteria in whey cheese: decreasing the risk of microbial contamination.
AB  == for dairy products that are consumed fresh, contamination by spoilage microorganisms and pathogens from the environment is a major concern. contamination has been associated with a number of outbreaks of foodborne illnesses; however, consistent data pertaining to the microbial safety of whey cheeses specifically have not been reported. hence, the goals of this research effort were (i) to manufacture a probiotic whey cheese with bifidobacterium animalis and lactobacillus casei and (ii) to assess the antimicrobial activity of these probiotics against a set of foodborne pathogens (listeria innocua, salmonella enteritidis, and staphylococcus aureus) and food spoilage microorganisms (pseudomonas aeruginosa and escherichia coli). three ranges of these microbial contaminants were used for inoculation of cheeses: 10(3) to 10(4), 10(4) to 10(6), and 10(6) to 10(8) cfu/g. inoculation in plain culture medium served as a control. the inhibition produced by the probiotics was calculated, and the major effect was found to be bacteriostatic. in specific cases, full inhibition was observed, i.e., by b. animalis against p. aeruginosa and by l. casei against salmonella enteritidis and l. innocua. conversely, the least inhibition was detected for l. casei against p. aeruginosa. our results suggest that use of these probiotic strains can extend the shelf life of whey cheeses and make them safer by delaying or preventing growth of common contaminant bacteria.
TIHT== 
ABHT== 

PMID== 20364710
TI  == [probiotic properties of industrial strains of lactobacilli and bifidobacteria].
AB  == lactic acid bacteria and bifidobacteria were isolated from the samples of dry microbial substance "vivolac" and identified. the lactic acid bacteria were identified as lactobacillus acidophilus. l. delbrueckii subsp. bulgaricus, l. paracasei. bifidobacteria belonged to the species bifidobacterium animalis. manifestation of biological activity of all studied strains was investigated. it  was shown, that adhesive activity of the studied strains depended on the genus of the strain: lactobacilli manifested medium adhesiveness to buccal epithelium (medium adhesive index 2.07-2.26), bifidobacteria manifested high adhesiveness (medium adhesive index 4.11-4.76). antagonism against pathogenic and opportunistic reference strains was manifested to a greater extent to pseudomonas aeruginosa. lactobacilli and bifidobacteria were resistant to aminoglycosides. sensitivity of the studied strains to antibiotics did not depend on the genus and species of microorganism. lactobacillus and bifidobacterium strains were capable  to survive in gastric juice and at different concentration of bile, which is promising for development of probiotic preparations on the basis of these strains.
TIHT== 
ABHT== 

