@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25313216
TI  == inhibition of salmonella enterica biofilm formation using small-molecule adenosine mimetics.
AB  == biofilms have been widely implicated in chronic infections and environmental persistence of salmonella enterica, facilitating enhanced colonization of surfaces and increasing the ability of the bacteria to be transmitted to new hosts. salmonella enterica serovar typhi biofilm formation on gallstones from humans and mice enhances gallbladder colonization and bacterial shedding, while salmonella enterica serovar typhimurium biofilms facilitate long-term persistence in a number of environments important to food, medical, and farming industries. salmonella regulates expression of many virulence- and biofilm-related processes  using kinase-driven pathways. kinases play pivotal roles in phosphorylation and energy transfer in cellular processes and possess an atp-binding pocket required  for their functions. many other cellular proteins also require atp for their activity. here we test the hypothesis that pharmacological interference with atp-requiring enzymes utilizing adenosine mimetic compounds would decrease or inhibit bacterial biofilm formation. through the screening of a 3,000-member atp  mimetic library, we identified a single compound (compound 7955004) capable of significantly reducing biofilm formation by s. typhimurium and s. typhi. the compound was not bactericidal or bacteriostatic toward s. typhimurium or cytotoxic to mammalian cells. an atp-sepharose affinity matrix technique was used to discover potential protein-binding targets of the compound and identified groel and deod. compound 7955004 was screened against other known biofilm-forming bacterial species and was found to potently inhibit biofilms of acinetobacter baumannii as well. the identification of a lead compound with biofilm-inhibiting  capabilities toward salmonella provides a potential new avenue of therapeutic intervention against salmonella biofilm formation, with applicability to biofilms of other bacterial pathogens.
TIHT== 
ABHT== 

PMID== 25135473
TI  == evaluation of gram-negative bacterial infection by a stable and conjugative bioluminescence plasmid in a mouse model.
AB  == background: the green fluorescence protein (gfp)-associated fluorescence method and the luciferase-associated bioluminescence method are the two major methods for ivis imaging system to investigate the bacterial infection in animal models.  the aim of this study was to evaluate the infection route of gram-negative bacteria carrying a stable and broad range of conjugative bioluminescence plasmid pse-lux1 in a mouse model. results: both encapsulated and non-encapsulated gram-negative bacteria were used as hosts to evaluate conjugation efficiency and  plasmid stability of pse-lux1, a recombinant of pse34 and luxabcde operon. the plasmid conjugation efficiencies of pse-lux1 ranged from 10(-)(3) to 10(-)(7) in  various gram-negative bacteria. plasmid pse-lux1 maintained in escherichia coli,  klebsiella pneumoniae, and salmonella enterica serovars choleraesues (abbreviated s. choleraesuis) and typhimurium (s. typhimurium), than in acinetobacter baumannii and serratia marcescens, was shown to be of better stability for at least four days. to investigate systemic bacterial infections, k. pneumoniae strain cg354 was intravenously injected, and then was clearly observed to be non-pathogenic to balb/c mice for a long-term bioluminescence monitoring for 6 days. for examining dynamic distributions of gastrointestinal tract infection, the invasion protein sipb-deficient mutant ou5045 big up tri, opensipb and ou5046 big up tri, opensipb of s. serovar typhimurium constructed in this study, compared to wild-type strain ou5045 and its virulence plasmid-less strain ou5046, were of less virulence to mice. conclusions: this is the first study to evaluate  the conjugative and stable bioluminescence vehicle system of pse-lux1 in a wide range of gram-negative bacteria, a system that can provide a useful reporter approach to trace systemic and gastrointestinal bacterial infections in a mouse model.
TIHT== 
ABHT== 

PMID== 25085655
TI  == lethal synergy involving bicyclomycin: an approach for reviving old antibiotics.
AB  == background: one way to address the growing problem of antimicrobial resistance is to revive old compounds that may have intrinsic lethal activity that is obscured  by protective factors. bicyclomycin is an old inhibitor of the rho transcription  terminator that by itself shows little rapid lethal activity. however, bicyclomycin participates in bacteriostatic synergy, which raises the possibility that conditions for lethal synergy may exist, perhaps through a suppression of protective factors. methods: bicyclomycin was combined with bacteriostatic inhibitors of gene expression, and bactericidal activity was measured with several cultured gram-negative pathogens. results: when used alone, bicyclomycin  failed to rapidly kill growing cultures of escherichia coli; however, the additional presence of bacteriostatic concentrations of tetracycline, chloramphenicol or rifampicin led to rapid killing. four other pathogen species,  acinetobacter baumannii, klebsiella pneumoniae, salmonella enterica serotype typhimurium and shigella dysenteriae, also exhibited enhanced killing when bicyclomycin was combined with tetracycline or rifampicin. this lethal synergy was achieved at low concentrations (slightly above the mic) for all agents tested in combinations. follow-up work with e. coli indicated that lethal synergy arose  from a blockage of transcription elongation. moreover, lethal synergy was reduced when bicyclomycin was added 60 min before tetracycline, suggesting that bicyclomycin induces a protective factor. conclusions: the action of bicyclomycin illustrates the potential present in a largely abandoned antibacterial agent; it  exhibits lethal synergy when coadministered with known, bacteriostatic inhibitors of gene expression. the identification of protective factors, which are currently uncharacterized, may reveal new ways to promote the lethal action of some old antibiotics.
TIHT== 
ABHT== 

PMID== 24982074
TI  == a broad-spectrum antibiofilm peptide enhances antibiotic action against bacterial biofilms.
AB  == biofilm-related infections account for at least 65% of all human infections, but  there are no available antimicrobials that specifically target biofilms. their elimination by available treatments is inefficient since biofilm cells are between 10- and 1,000-fold more resistant to conventional antibiotics than planktonic cells. here we describe the synergistic interactions, with different classes of antibiotics, of a recently characterized antibiofilm peptide, 1018, to potently prevent and eradicate bacterial biofilms formed by multidrug-resistant eskape (enterococcus faecium, staphylococcus aureus, klebsiella pneumoniae, acinetobacter baumannii, pseudomonas aeruginosa, and enterobacter species) pathogens. combinations of peptide 1018 and the antibiotic ceftazidime, ciprofloxacin, imipenem, or tobramycin were synergistic in 50% of assessments and decreased by 2- to 64-fold the concentration of antibiotic required to treat biofilms formed by pseudomonas aeruginosa, escherichia coli, acinetobacter baumannii, klebsiella pneumoniae, salmonella enterica, and methicillin-resistant  staphylococcus aureus. furthermore, in flow cell biofilm studies, combinations of low, subinhibitory levels of the peptide (0.8 mug/ml) and ciprofloxacin (40 ng/ml) decreased dispersal and triggered cell death in mature p. aeruginosa biofilms. in addition, short-term treatments with the peptide in combination with ciprofloxacin prevented biofilm formation and reduced p. aeruginosa pa14 preexisting biofilms. pcr studies indicated that the peptide suppressed the expression of various antibiotic targets in biofilm cells. thus, treatment with the peptide represents a novel strategy to potentiate antibiotic activity against biofilms formed by multidrug-resistant pathogens.
TIHT== 
ABHT== 

PMID== 24852171
TI  == broad-spectrum anti-biofilm peptide that targets a cellular stress response.
AB  == bacteria form multicellular communities known as biofilms that cause two thirds of all infections and demonstrate a 10 to 1000 fold increase in adaptive resistance to conventional antibiotics. currently, there are no approved drugs that specifically target bacterial biofilms. here we identified a potent anti-biofilm peptide 1018 that worked by blocking (p)ppgpp, an important signal in biofilm development. at concentrations that did not affect planktonic growth,  peptide treatment completely prevented biofilm formation and led to the eradication of mature biofilms in representative strains of both gram-negative and gram-positive bacterial pathogens including pseudomonas aeruginosa, escherichia coli, acinetobacter baumannii, klebsiella pneumoniae, methicillin resistant staphylococcus aureus, salmonella typhimurium and burkholderia cenocepacia. low levels of the peptide led to biofilm dispersal, while higher doses triggered biofilm cell death. we hypothesized that the peptide acted to inhibit a common stress response in target species, and that the stringent response, mediating (p)ppgpp synthesis through the enzymes rela and spot, was targeted. consistent with this, increasing (p)ppgpp synthesis by addition of serine hydroxamate or over-expression of rela led to reduced susceptibility to the peptide. furthermore, rela and spot mutations blocking production of (p)ppgpp replicated the effects of the peptide, leading to a reduction of biofilm formation in the four tested target species. also, eliminating (p)ppgpp expression after two days of biofilm growth by removal of arabinose from a strain expressing rela behind an arabinose-inducible promoter, reciprocated the effect of peptide added at the same time, leading to loss of biofilm. nmr and chromatography studies showed that the peptide acted on cells to cause degradation of (p)ppgpp within 30 minutes, and in vitro directly interacted with  ppgpp. we thus propose that 1018 targets (p)ppgpp and marks it for degradation in cells. targeting (p)ppgpp represents a new approach against biofilm-related drug  resistance.
TIHT== 
ABHT== 

PMID== 23961431
TI  == antimicrobial activity of amazonian medicinal plants.
AB  == objectives: the aqueous extracts of currently utilized amazonian medicinal plants were assayed in vitro searching for antimicrobial activity against human and animal pathogenic microorganisms. methods: medium resuspended lyophilized aqueous extracts of different organs of amazonian medicinal plants were assayed by in vitro screening for antimicrobial activity. atcc and standardized microorganisms  obtained from oswaldo cruz foundation/brazil were individually and homogeneously  grown in agar plate, and holes previously perforated in the gel were filled with  diluted plant aqueous extracts. inhibition halos were evaluated and controlled by the use of the fluoroquinolone ciprofloxacin. results: the amazonian medicinal plants, hymenelobium petraeum showed inhibitory activity over staphylococcus aureus, enterococcus faecalis, salmonella enterica serovar typhi, acinetobacter baumannii and candida albicans, while vatairea guianensis and symphonia globulifera presented inhibitory activity exclusively for staphylococcus aureus.  also, ptychopetalum olacoides and pentaclethra macroloba inhibited the growth of  klebsiella ozaenae and acinetobacter baumannii. conclusion: the aqueous botanic extracts that showed activity against microroganisms of attc and osvaldo cruz strains had at least 40% of antimicrobial activity when compared to halo inhibition produced by the commercial antibiotic ciprofloxacin utilized as a control. of all plants extracts assayed, the hymenelobium petraeum had the best performance, sometimes exhibiting higher activity than ciprofloxacin. it is not well-defined by the physicians the exact indication of the majority of medicinal  plants in the amazon area in brazil. natives utilize the plants according to their symptoms, based on the traditional knowledge transmitted orally from generation to generation, among amerindians, afrodescendents and ethnic mixed populations. a significant number of amazonian medicinal plants are totally unknown related to their medicinal properties including mechanism of action and therapeutic effects, as very few information is reported in the scientific literature. a tiny amount of data is presented, as the preliminary antimicrobial  properties of the medicinal plants here accessed, under the urgent necessity of new antibiotics in the market and in face of the increased resistance of infectious microorganisms to antimicrobials.
TIHT== 
ABHT== 

PMID== 23209414
TI  == a trade-off between the fitness cost of functional integrases and long-term stability of integrons.
AB  == horizontal gene transfer (hgt) plays a major role in bacterial microevolution as  evident from the rapid emergence and spread of antimicrobial drug resistance. few studies have however addressed the population dynamics of newly imported genetic  elements after hgt. here, we show that newly acquired class-1 integrons from salmonella enterica serovar typhimurium and acinetobacter baumannii, free of associated transposable elements, strongly reduce host fitness in acinetobacter baylyi. insertional inactivation of the integron inti1 restored fitness, demonstrating that the observed fitness costs were due to the presence of an active integrase. the biological cost of harboring class-1 integrons was rapidly  reduced during serial transfers due to inti1 frameshift mutations leading to inactivated integrases. we use a mathematical model to explore the conditions where integrons with functional integrases are maintained and conclude that environmental fluctuations and episodic selection is necessary for the maintenance of functional integrases. taken together, the presented data suggest  a trade-off between the ability to capture gene cassettes and long-term stability of integrons and provide an explanation for the frequent observation of inactive  integron-integrases in bacterial populations.
TIHT== 
ABHT== 

PMID== 21646482
TI  == the pmrcab operon mediates polymyxin resistance in acinetobacter baumannii atcc 17978 and clinical isolates through phosphoethanolamine modification of lipid a.
AB  == the emergence of multidrug resistance among acinetobacter baumannii is leading to an increasing dependence on the use of polymyxins as last-hope antibiotics. here, we utilized genetic and biochemical methods to define the involvement of the pmrcab operon in polymyxin resistance in this organism. sequence analysis of 16 polymyxin b-resistant strains, including 6 spontaneous mutants derived from strain atcc 17978 and 10 clinical isolates from diverse sources, revealed that they had independent mutations in the pmrb gene, encoding a sensor kinase, or in  the response regulator pmra. knockout of the pmrb gene in two mutants and two clinical isolates led to a decrease in the polymyxin b susceptibility of these strains, which could be restored with the cloned pmrab genes from the mutants but not from the wild type. reverse transcription-quantitative pcr (rt-qpcr) analysis also showed a correlation between the expression of pmrc and polymyxin b resistance. characterization of lipid a species from the mutant strains, by thin-layer chromatography and mass spectrometry, indicated that the addition of phosphoethanolamine to lipid a correlated with resistance. this addition is performed in salmonella enterica serovar typhimurium by the product of the pmrc gene, which is a homolog of the pmrc gene from acinetobacter. knockout of this gene in the mutant r2 [pmrb(t235i)] reversed resistance as well as phosphoethanolamine modification of lipid a. these results demonstrate that specific alterations in the sequence of the pmrcab operon are responsible for resistance to polymyxins in a. baumannii.
TIHT== 
ABHT== 

PMID== 21388174
TI  == occurrence, abundance, and diversity of tetracycline resistance genes in 15 sewage treatment plants across china and other global locations.
AB  == activated sludge was sampled from 15 sewage treatment plants (stps) across china  and other global locations to investigate the occurrence, abundance and diversity of tetracycline resistance genes (tet) in the stps. occurrence and abundance of 14 tet genes were determined using polymerase chain reaction (pcr) and quantitative real time pcr. six genes (tet(a), tet(c), tet(g), tet(m), tet(s), and tet(x)) were detected in all the stps, while no sludge sample contained tet(q). total concentration of the 14 genes was significantly different among the stps and average tet abundance of the stps varied greatly among the tet types (p<0.05). tet(g) had the highest concentration in the stps, followed by tet(c), tet(a) and tet(s). phylogenetic diversity of the genes was investigated using dna cloning. blast analysis showed that all of the 450 cloned sequences matched known tet genes, except for tet(g). the 56 tet(g) clones were grouped into 14 genotypes, among which type g24 had an identical sequence to tet(g) carried by salmonella enterica or acinetobacter baumannii, while the other sequences had low similarity to the known genes in genbank. the results of this study might be useful to understand the diversity of these resistance genes in stps.
TIHT== 
ABHT== 

PMID== 21382699
TI  == high burden of antimicrobial resistance in asia.
AB  == antimicrobial resistance is associated with high mortality rates and high medical costs. marked variations in the resistance profiles of bacterial and fungal pathogens as well as the quality of public hygiene have had a considerable impact on the effectiveness of antimicrobial agents in asian countries. in asia, one of  the epicentres of antimicrobial drug resistance, there is an alarming number of antibiotic-resistant species, including penicillin- and erythromycin-resistant streptococcus pneumoniae, ampicillin-resistant haemophilus influenzae, multidrug-resistant (mdr) acinetobacter baumannii, extended-spectrum beta-lactamase (esbl)-producing klebsiella pneumoniae (particularly mediated by ctx-m-9, ctx-m-14 and ctx-m-15), new delhi metallo-beta-lactamase 1 (ndm-1)-producing enterobacteriaceae, mdr salmonella enterica serotypes choleraesuis and typhi, carbapenem-resistant a. baumannii (oxa-58 and oxa-23 carbapenemases) and azole-resistant candida glabrata. a few clones of mdr a. baumannii and hospital-acquired meticillin-resistant staphylococcus aureus (mrsa) have been widely disseminated in hospital settings in asia, and k. pneumoniae carbapenemase (kpc)-producing k. pneumoniae strains have been widely distributed  in china. in addition, the emergence of extensively drug-resistant mycobacterium  tuberculosis (xdr-tb) has illustrated the need for regular monitoring of resistance profiles of clinical isolates as well as the deliberative use of fluoroquinolones. continuous surveillance of resistance data from clinical isolates as well as implementation of strict infection control policies in healthcare settings are required to mitigate the progression of antimicrobial resistance.
TIHT== 
ABHT== 

PMID== 21146239
TI  == effects on salmonella shell contamination and trans-shell penetration of coating  hens' eggs with chitosan.
AB  == chitosan is a biopolymer with antimicrobial activity and film-forming properties. in this study, the effects on salmonella shell contamination and trans-shell penetration of coating hens' eggs with chitosan was evaluated. a chitosan was selected from eight types (four non-commercial and four commercial) based on its  antimicrobial activity against salmonella enterica serovar enteritidis (s. enteritidis). for this purpose, a contact plate method was developed and chitosans were applied at a concentration of 0.25% (w/v). a commercial type with  a molecular weight of 310-375 kda and a deacetylation degree of 75% that reduced  s. enteritidis by 0.71 log(10) colony forming units compared to the control (without chitosan) was selected for further studies. the chitosan was shown to have antimicrobial activity against other egg borne bacteria, i.e., acinetobacter baumannii, alcaligenes sp., carnobacterium sp., pseudomonas sp., serratia marcescens and staphylococcus warneri, and against s. enterica serovar typhimurium, escherichia coli and listeria monocytogenes. the effects of various  concentrations of the selected chitosan (0.25%, 1% and 2%) on salmonella shell contamination and trans-shell penetration were assessed using the agar molding technique. effective reduction of eggshell contamination could not be demonstrated, but trans-shell penetration was significantly reduced in the presence of a 2% chitosan eggshell coating, with only 6.1% of the eggs being penetrated compared to 24.5% of the uncoated eggs. it was concluded that the 2% chitosan coating has the potential to reduce contamination of egg contents resulting from trans-shell penetration by s. enteritidis.
TIHT== 
ABHT== 

PMID== 20802073
TI  == sensitization of microcin j25-resistant strains by a membrane-permeabilizing peptide.
AB  == microcin j25 (mccj25) is a plasmid-encoded, 21-amino-acid, antibacterial peptide  produced by escherichia coli. mccj25 inhibits rna polymerase and the membrane respiratory chain. mccj25 uptake into e. coli-sensitive strains is mediated by the outer membrane receptor fhua and the inner membrane proteins tonb, exbb, exbd, and sbma. this peptide is active on some e. coli, salmonella, and shigella  species strains, while other gram-negative bacteria, such as clinical isolates of enterobacter cloacae, citrobacter freundii, klebsiella pneumoniae, pseudomonas aeruginosa, acinetobacter baumannii, moraxella catarrhalis, and salmonella enterica serovar typhimurium, are completely resistant. in the present work, we demonstrated that the membrane-permeabilizing peptide (kff)(3)k made some resistant strains sensitive to mccj25, among them s. typhimurium, where the antibiotic inhibits in vitro cell growth and bacterial replication within macrophages. the results demonstrate that the membrane permeabilization induced by (kff)(3)k allows mccj25 penetration in an fhua and sbma-independent manner and suggest that the combination of both peptides could be considered as a therapeutic agent against pathogenic salmonella strains.
TIHT== 
ABHT== 

PMID== 19641057
TI  == detection of enterobacter sakazakii and other pathogens associated with infant formula powder by use of a dna microarray.
AB  == pathogen detection is critical to the process of generating and testing powdered  infant formula (pif). an obstacle associated with pif microbial surveillance is that most current procedures are time-consuming and labor-intensive. we have developed a rapid, dna microarray-based detection technique to identify 10 different pathogenic bacteria associated with pif contamination based on the 16s-23s rrna gene internal transcribed spacer (its) sequences and wzy (o antigen  polymerase) gene. using this procedure, enterobacter sakazakii, salmonella enterica, klebsiella pneumoniae, klebsiella oxytoca, serratia marcescens, acinetobacter baumannii, bacillus cereus, listeria monocytogenes, staphylococcus  aureus, and escherichia coli o157 were identified. one hundred eighty-five strains were used to validate the microarray assay (including 134 target pathogen strains and 51 closely related bacteria). twenty-seven probes reproducibly detected multiple pathogens with high specificity and sensitivity (0.100 ng genomic dna or 10(4) cfu/ml). twenty-one real pif samples were tested by the microarray with 100% accuracy. the data presented reveal that the designed oligonucleotide microarray is a promising method for basic microbiology, clinical diagnosis, food safety, and epidemiological surveillance.
TIHT== 
ABHT== 

PMID== 17265855
TI  == biofilm formation by multidrug-resistant salmonella enterica serotype typhimurium phage type dt104 and other pathogens.
AB  == the biofilm-forming capability of salmonella enterica serotypes typhimurium and heidelberg, pseudomonas aeruginosa, listeria monocytogenes, escherichia coli o157:h7, klebsiella pneumoniae, and acinetobacter baumannii isolated from humans, animal farms, and retail meat products was evaluated by using a microplate assay. the tested bacterial species showed interstrain variation in their capabilities to form biofilms. strong biofilm-forming strains of s. enterica serotypes, e. coli o157: h7, p. aeruginosa, k. pneumoniae, and a. baumannii were resistant to at least four of the tested antibiotics. to understand their potential in forming biofilms in food-processing environments, the strong biofilm formers grown in beef, turkey, and lettuce broths were further investigated on stainless steel and glass surfaces. among the tested strains, salmonella typhimurium phage type dt104 (salmonella typhimurium dt104) isolated from retail beef formed the strongest biofilm on stainless steel and glass in beef and turkey broths. k. pneumoniae, l. monocytogenes, and p. aeruginosa were also able to form strong biofilms on the tested surface materials. salmonella typhimurium dt104 developed a biofilm on stainless steel in beef and turkey broths through (i) initial attachment to the surface, (ii) formation of microcolonies, and (iii) biofilm maturation. these findings indicated that salmonella typhimurium dt104 alongwith other bacterial pathogens could be a source of cross-contamination during handling and processing of food.
TIHT== 
ABHT== 

PMID== 16822571
TI  == eggshell factors influencing eggshell penetration and whole egg contamination by  different bacteria, including salmonella enteritidis.
AB  == trans-shell infection routes and whole egg contamination of 7 selected bacterial  strains; staphylococcus warneri, acinetobacter baumannii, alcaligenes sp., serratia marcescens, carnobacterium sp., pseudomonas sp. and salmonella enteritidis, recovered from egg contents, were studied. the first objective was to correlate bacterial eggshell penetration with various eggshell characteristics and bacterial strains. an agar approach was used to assess the eggshell penetration. the second objective was to assess the contamination of whole eggs with the bacterial strains; whole intact eggs were used in this case. the intact  shells of agar-filled and whole eggs were inoculated with 10(3) -10(4) cfu of the selected strains. during 3 weeks storage at 20 degrees c and 60% relative humidity, the bacterial eggshell penetration was regularly monitored. the whole egg contamination was only analyzed after 3 weeks. the eggshell characteristics such as area eggshell, shell thickness and number of pores did not influence the  bacterial eggshell penetration. for each individual bacterial strain the mean cuticle deposition was lower for penetrated compared to non-penetrated eggshells. for the individual strain carnobacterium sp. and for the global results of all strains this difference was statistical significantly. the whole egg contamination was not influenced by neither the area of the eggshell nor the porosity of the eggshell. the results of the agar approach indicate that the gram-negative, motile and non-clustering bacteria penetrated the eggshell most frequently; pseudomonas sp. (60%) and alcaligenes sp. (58%) were primary invaders followed by s. enteritidis (43%). all selected strains were able to penetrate; penetration was observed most frequently after ca. 4-5 days. particularly s. enteritidis was a primary invader of whole eggs: the membranes and/or the content of 32% of the whole eggs was contaminated. the remaining bacterial eggshell contamination with the selected strain was determined after 3 weeks storage. penetrated eggshells and contaminated whole eggs showed a significantly higher bacterial contamination on the eggshell compared to non-penetrated eggshells and  non-contaminated whole eggs respectively (global results of all strains). the influence of hen age on bacterial eggshell penetration and egg content contamination was not significant. while the agar approach is suitable to study the influence of the eggshell characteristics on the bacterial eggshell penetration, the intact egg approach gives an estimation of the penetration of the shell followed by the probability of survival and migration in whole eggs.
TIHT== 
ABHT== 

PMID== 15855485
TI  == genetic environment and expression of the extended-spectrum beta-lactamase blaper-1 gene in gram-negative bacteria.
AB  == the genetic location of the gene coding for the expanded-spectrum beta-lactamase  per-1 was analyzed in a series of gram-negative isolates. it was identified as part of a composite transposon bracketed by two novel insertion elements, ispa12  and ispa13, belonging to the is4 family that possess transposases that share 63%  amino acid identity and that are chromosomally located in pseudomonas aeruginosa, providencia stuartii, and acinetobacter baumannii. on the contrary, the bla(per-1) gene was identified just downstream of an ispa12 element but not within a composite transposon when it was located on a plasmid in salmonella enterica serovar typhimurium and a. baumannii isolates. in both cases, expression of the bla(per-1) gene was driven by promoter sequences located in ispa12.
TIHT== 
ABHT== 

