@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25752235
TI  == potential probiotic attributes of a new strain of bacillus coagulans cgmcc 9951 isolated from healthy piglet feces.
AB  == a new strain of bacillus coagulans cgmcc 9551, which has a broad range of antibacterial activities against six main pathogenic bacteria including escherichia coli o8, staphylococcus aureus, salmonella enterica subsp. enterica serovar enteritidis, streptococcus suis, listeria monocytogenes and pasteurella multocida, was isolated from healthy piglet feces. in adhesion assay, the isolate exhibited a stronger adhesion to pig intestinal mucus than that of b. subtilis jt143 and l. acidophilus ly24 respectively isolated from bioplus((r))2b and florafit((r)) probiotics (p < 0.05). the adhesion activity reached 44.5 +/- 3.2,  48.9 +/- 2.6, 42.6 +/- 3.3 and 37.6 +/- 2.4 % to jejunum, ileum, transverse colon and sigmoid colon, separately. the survival rate of b. coagulans cgmcc 9551 was reduced by only 20 % at 4 h exposure under 0.9 % w/v bile salt. the strain was fully resistant to ph 2 for 2 h with 90.1 +/- 3.5 % survival and susceptible to 15 antibiotics commonly used in veterinary medicine. additionally, the bacteria showed amylase, protease and cellulase activities. the safety assessment demonstrated the lack of toxicity potential in b. coagulans cgmcc 9551 by ligated rabbit ileal loop assay, acute and subchronic toxicity test. these results implied that that the new strain of b. coagulans cgmcc 9951 isolated from healthy piglet feces has promising probiotic characteristics and offers desirable opportunities for its successful commercialization as one excellent candidate probiotic.
TIHT== 
ABHT== 

PMID== 22214451
TI  == inhibition of bacterial carbonic anhydrases and zinc proteases: from orphan targets to innovative new antibiotic drugs.
AB  == zinc-containing enzymes, such as carbonic anhydrases (cas) and metalloproteases (mps) play critical functions in bacteria, being involved in various steps of their life cycle, which are important for survival, colonization, acquisition of  nutrients for growth and proliferation, facilitation of dissemination, invasion and pathogenicity. the development of resistance to many classes of clinically used antibiotics emphasizes the need of new antibacterial drug targets to be explored. there is a wealth of data regarding bacterial cas and zinc mps present  in many pathogenic species, such as neisseria spp., helycobacter pylori escherichia coli, mycobacterium tuberculosis, brucella spp., streptococcus pneumoniae, salmonella enterica, haemophilus influenzae, listeria spp, vibrio spp., pseudomonas aeruginosa, legionella pneumophila, streptomyces spp., clostridium spp., enterococcus spp., etc. some of these enzymes have been cloned, purified and characterized by crystallographic techniques. however, for the moment, few potent and specific inhibitors for bacterial mps have been reported except for clostridium histolyticum collagenase, botulinum and tetanus neurotoxin and anthrax lethal factor, which will be reviewed in this article. bacteria encode alpha-,beta-, and/or gamma-ca families, but up to now only the first two classes have been investigated in some detail in different species. the alpha-cas from neisseria spp. and h. pylori as well as the beta-class enzymes from e. coli, h. pylori, m. tuberculosis, brucella spp., s. pneumoniae, s. enterica and h. influenzae have been cloned and characterized. the catalytic/inhibition mechanisms of these cas are well understood as x-ray crystal structures are available for some of them, but no adducts of these enzymes with inhibitors have  been characterized so far. in vitro and in vivo studies with various classes of inhibitors, such as anions, sulfonamides and sulfamates have been reported. only  for neisseria spp., h. pylori, b. suis and s. pneumoniae cas it has been possible to evidence inhibition of bacterial growth in vivo. thus, bacterial cas and mps represent at this moment very promising targets for obtaining antibacterials devoid of the resistance problems of the clinically used such agents but further  studies are needed to validate these and other less investigated enzymes as novel drug targets.
TIHT== 
ABHT== 

PMID== 21779249
TI  == bacterial carbonic anhydrases as drug targets: toward novel antibiotics?
AB  == carbonic anhydrases (cas, ec 4.2.1.1) are metalloenzymes which catalyze the hydration of carbon dioxide to bicarbonate and protons. many pathogenic bacteria  encode such enzymes belonging to the alpha-, beta-, and/or gamma-ca families. in  the last decade, the alpha-cas from neisseria spp. and helicobacter pylori as well as the beta-class enzymes from escherichia coli, h. pylori,mycobacterium tuberculosis, brucella spp., streptococcus pneumoniae, salmonella enterica, and haemophilus influenzae have been cloned and characterized in detail. for some of  these enzymes the x-ray crystal structures were determined, and in vitro and in vivo inhibition studies with various classes of inhibitors, such as anions, sulfonamides and sulfamates reported. although efficient inhibitors have been reported for many such enzymes, only for neisseria spp., h. pylori, b. suis, and  s. pneumoniae enzymes it has been possible to evidence inhibition of bacterial growth in vivo. thus, bacterial cas represent promising targets for obtaining antibacterials devoid of the resistance problems of the clinically used such agents but further studies are needed to validate these and other less investigated enzymes as novel drug targets.
TIHT== 
ABHT== 

PMID== 21731180
TI  == microbiological identification and analysis of swine tonsils collected from carcasses at slaughter.
AB  == the primary objective of this 7-month study was to determine the prevalence of porcine pathogens of the tonsil of the soft palate of swine at slaughter. additional objectives were to determine if sampling the carcasses of normal or abnormal hogs provided different microbiological profiles and if the slaughter plant provides a feasible sampling frame and environment for detecting and monitoring important pathogens in tonsils that have health implications for both  swine and humans. a total of 395 samples were collected from 264 farms. of these, 180 tonsils were collected from normal carcasses and 215 tonsils were collected from carcasses that were diverted to the hold rail. laboratory testing included bacteriological culture and identification as well as real time-polymerase chain  reaction (pcr) testing for porcine reproductive and respiratory syndrome virus (pprsv) and immunohistochemistry (ihc) for porcine circovirus-2 (pcv-2). the most commonly isolated bacteria included: streptococcus suis (53.7%), arcanobacterium  pyogenes (29.9%), pasteurella multocida (27.3%), and streptococcus porcinus (19.5%). virus screening revealed evidence of prrsv and pcv-2 in 22.0% and 11.9%  of the samples, respectively. salmonella typhimurium and yersinia enterocolitica  were isolated in 0.5% and 1.8% of the samples, respectively. tonsils collected from the hold rail were more likely to be positive for staphylococcus hyicus [odds ratio (or) = 7.51, confidence interval (ci) = 2.89 to 19.54], streptococcus porcinus (or = 9.93, ci = 4.27 to 23.10), and streptococcus suis (or = 2.16, ci = 1.45 to 3.24). tonsils collected from abnormal carcasses were less likely to be positive for staphylococcus aureus (or = 0.05, ci = 0.005 to 0.482).
TIHT== 
ABHT== 

PMID== 19267155
TI  == purified recombinant phage lysin lysmp: an extensive spectrum of lytic activity for swine streptococci.
AB  == bacteriophage lysin has attracted considerable attentions as possible antimicrobial agents for solution of antibiotic resistance. smp was a streptococcus suis serotype 2 bacteriophage isolated from nasal swabs of healthy  bama minipigs. the putative smp bacteriophage lysin, designated lysmp, was recombinantly expressed in escherichia coli bl21, and chromatographically purified. treated with 0.8% of beta-mercaptoethanol, lysmp exhibited an extensive lysin spectrum than those of whole phage against bacteria investigated. s. suis serotype 2, s. suis serotype 7 and s. suis serotype 9 strains were recovered from diseased pigs between 1998 and 2005 in china. fifteen of seventeen strains of s.  suis serotype 2 could be lysed, as well as s. suis serotype 7 and 9, streptococcus equi ssp. zooepidemicus and staphylococcus aureus. but e. coli and  salmonella enterica were not affected. purified lysmp showed high degrading efficiency against pmsf or lysozyme treated cells comparing to pbs washed cells.  optimum ph and temperature conditions for the lysin were investigated by turbidity reduction assay. the lysin exerted efficient lysis activity at 37 degrees c, ph 5.2. the turbidity of bacterium investigated was observed to decrease by 1.2-68% in 30 min. result indicated that putative lysmp could be a candidate antimicrobial agent in controlling s. suis infection.
TIHT== 
ABHT== 

PMID== 15145504
TI  == efficacy of vaccines against bacterial diseases in swine: what can we expect?
AB  == this paper discusses what can be expected with regard to efficacy of antibacterial vaccines used in swine, based on the present knowledge of pathogen-host interactions. first, vaccination against bacteria that mainly cause disease by production of exotoxins is considered. vaccines containing the inactivated toxin or a non-toxic but antigenic recombinant protein derived from the exotoxin can be expected to provide protection against disease. the degree of protection induced by such vaccines varies, however, depending amongst other things on the pathogenesis of the disease. vaccination against clostridial infections, actinobacillus pleuropneumoniae infections, progressive atrophic rhinitis and enterotoxigenic escherichia coli, is considered. the second part of  the article deals with vaccination against extracellular bacteria. protection against these bacteria is generally mediated by antibodies against their surface  antigens and certain secreted antigens, but cellular immunity may also play a role. efficacy of vaccines against swine erysipelas, streptococcus suis infections, mycoplasma hyopneumoniae infections and swine dysentery is discussed. finally, vaccination against facultatively intracellular bacteria is considered.  for protection against these bacteria cell-mediated immunity plays an important role, but antibodies may also be involved. it is generally accepted that live-attenuated vaccines are more suitable for induction of cell-mediated immunity than inactivated vaccines, although this also depends on the adjuvant used in the vaccine. as an example, vaccination against salmonella enterica serotype typhimurium is discussed.
TIHT== 
ABHT== 

PMID== 11796113
TI  == toward a structural understanding of the dehydratase mechanism.
AB  == dtdp-d-glucose 4,6-dehydratase (rmlb) was first identified in the l-rhamnose biosynthetic pathway, where it catalyzes the conversion of dtdp-d-glucose into dtdp-4-keto-6-deoxy-d-glucose. the structures of rmlb from salmonella enterica serovar typhimurium in complex with substrate deoxythymidine 5'-diphospho-d-glucose (dtdp-d-glucose) and deoxythymidine 5'-diphosphate (dtdp), and rmlb from streptococcus suis serotype 2 in complex with dtdp-d-glucose, dtdp, and deoxythymidine 5'-diphospho-d-pyrano-xylose (dtdp-xylose) have all been solved at resolutions between 1.8 a and 2.4 a. the structures show that the active sites are highly conserved. importantly, the structures show that the active site tyrosine functions directly as the active site base, and an aspartic  and glutamic acid pairing accomplishes the dehydration step of the enzyme mechanism. we conclude that the substrate is required to move within the active site to complete the catalytic cycle and that this movement is driven by the elimination of water. the results provide insight into members of the sdr superfamily.
TIHT== 
ABHT== 

PMID== 10568807
TI  == cloning and characterization of the gene encoding o-acetylserine lyase from streptococcus suis.
AB  == we have cloned and sequenced a gene encoding o-acetylserine lyase from streptococcus suis. the gene encodes a protein of 309 amino acids with a calculated molecular mass of 32,038 da. the deduced amino acid sequence showed more extensive similarities to the cysk proteins than to the cysm proteins of other bacteria. the cloned gene was inserted into a ptrchisb histidine hexamer expression vector. a 38-kda fusion protein was expressed in a cysmk auxotrophic mutant of salmonella typhimurium and complemented the auxotrophic properties of the mutant. furthermore, the transformants could grow in minimal defined media supplemented with not only sulfide but also thiosulfate as a sole sulfur source.  these data indicated that the cloned gene encodes a protein that was a functional homolog of the cysm in s. typhimurium.
TIHT== 
ABHT== 

