@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 24441515
TI  == tolerance of anaerobic bacteria to chlorinated solvents.
AB  == the aim of this research was to evaluate the effects of four chlorinated aliphatic hydrocarbons (cahs), perchloroethene (pce), carbon tetrachloride (ct),  chloroform (cf) and 1,2-dichloroethane (1,2-dca), on the growth of eight anaerobic bacteria: four fermentative species (escherichia coli, klebsiella sp.,  clostridium sp. and paenibacillus sp.) and four respiring species (pseudomonas aeruginosa, geobacter sulfurreducens, shewanella oneidensis and desulfovibrio vulgaris). effective concentrations of solvents which inhibited growth rates by 50% (ec50) were determined. the octanol-water partition coefficient or log po/w of a cah proved a generally satisfactory measure of its toxicity. most species tolerated approximately 3-fold and 10-fold higher concentrations of the two relatively more polar cahs cf and 1,2-dca, respectively, than the two relatively  less polar compounds pce and ct. ec50 values correlated well with growth rates observed in solvent-free cultures, with fast-growing organisms displaying higher  tolerance levels. overall, fermentative bacteria were more tolerant to cahs than  respiring species, with iron- and sulfate-reducing bacteria in particular appearing highly sensitive to cahs. these data extend the current understanding of the impact of cahs on a range of anaerobic bacteria, which will benefit the field of bioremediation.
TIHT== 
ABHT== 

PMID== 19486208
TI  == effect of 2,4-dinitrotoluene on the anaerobic bacterial community in marine sediment.
AB  == aims: to study the impact of added 2,4-dinitrotoluene (dnt) on the anaerobic bacterial community in marine sediment collected from an unexploded ordnance dumping site in halifax harbour. methods and results: marine sediment was spiked  with 2,4-dnt and incubated under anaerobic conditions in the presence and absence of lactate. indigenous bacteria in the sediment removed 2,4-dnt with subsequent formation of its mono- and diamino-derivatives under both conditions. pcr-dgge and nucleotide sequencing were used to monitor the change in the bacterial population in sediment caused by the presence of 2,4-dnt. the results showed that denaturing gradient gel electrophoresis banding patterns of sediment microcosms treated with 2,4-dnt were different from controls that did not receive 2,4-dnt. bacteroidetes, firmicutes and delta-proteobacteria were present in sediment incubated in the absence of 2,4-dnt. however, several gamma-proteobacteria became dominant in sediment in the presence of 2,4-dnt, two of which were 99% similar to shewanella canadensis and shewanella sediminis. in the presence of both 2,4-dnt and lactate, two additional delta-proteobacteria were enriched, one closely related (98% similarity) to desulfofrigus fragile and the other affiliated (96% similarity) to desulfovibrio sp. in contrast, none of the above four proteobacteria were enriched in sediment incubated with lactate alone. conclusions: presence of 2,4-dnt led to a significant change in bacterial population of marine sediment with the enrichment of several gamma- and delta-proteobacteria. significance and impact of the study: our results provided  the first evidence on the impact of the pollutant 2,4-dnt on the indigenous bacterial community in marine sediment, and provided an insight into the composition of bacterial community that degrade 2,4-dnt.
TIHT== 
ABHT== 

PMID== 18634895
TI  == application of molecular techniques to evaluate the methanogenic archaea and anaerobic bacteria in the presence of oxygen with different cod:sulfate ratios in a uasb reactor.
AB  == in this paper, the microbial characteristics of the granular sludge in the presence of oxygen (3.0+/-0.7 mg o2 l(-1)) were analyzed using molecular biology  techniques. the granules were provided by an upflow anaerobic sludge blanket (uasb) operated over 469 days and fed with synthetic substrate. ethanol and sulfate were added to obtain different cod/so4(2-) ratios (3.0, 2.0, and 1.6). the results of fluorescent in situ hybridization (fish) analyses showed that archaeal cells, detected by the arc915 probe, accounted for 77%, 84%, and 75% in  the cod/so(4)(2-) ratios (3.0, 2.0, and 1.6, respectively). methanosaeta sp. was  the predominant acetoclastic archaea observed by optical microscopy and fish analyses, and confirmed by sequencing of the excised bands of the dgge gel with a similarity of 96%. the sulfate-reducing bacterium desulfovibrio vulgaris subsp. vulgaris (similarity of 99%) was verified by sequencing of the dgge band. others  identified microorganism were similar to shewanella sp. and desulfitobacterium hafniense, with similarities of 95% and 99%, respectively. these results confirmed that the presence of oxygen did not severely affect the metabolism of microorganisms that are commonly considered strictly anaerobic. we obtained mean  efficiencies of organic matter conversion and sulfate reducing higher than 74%.
TIHT== 
ABHT== 

