@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25583717
TI  == in vitro spectrum of pexiganan activity when tested against pathogens from diabetic foot infections and with selected resistance mechanisms.
AB  == pexiganan, a 22-amino-acid synthetic cationic peptide, is currently in phase 3 clinical trials as a topical antimicrobial agent for the treatment of mild infections associated with diabetic foot ulcers. bacterial isolates from the 2013 sentry antimicrobial surveillance program designated as pathogens from diabetic foot infections (dfi) and gram-negative and -positive pathogens from various infection types that harbored selected resistance mechanisms/phenotypes were tested against pexiganan in reference cation-adjusted mueller-hinton broth. the mic50 and mic90 against all organisms tested from dfi were 16 and 32 mug/ml, respectively. escherichia coli, klebsiella pneumoniae, citrobacter koseri, enterobacter cloacae, acinetobacter species, and pseudomonas aeruginosa mic values ranged from 8 to 16 mug/ml. pexiganan mic values among staphylococcus aureus (methicillin-resistant s. aureus [mrsa] and methicillin-susceptible s. aureus [mssa]), beta-hemolytic streptococci, and enterococcus faecium ranged from 8 to 32 mug/ml. pexiganan activity was not adversely affected for members of the  family enterobacteriaceae or p. aeruginosa that produced beta-lactamases or resistance mechanisms to other commonly used antimicrobial agents. decreased susceptibility to vancomycin did not affect pexiganan activity against s. aureus  or e. faecium. enterococcus faecalis appears to be intrinsically less susceptible to pexiganan (mic, 32 to 256 mug/ml). the "all organism" mic90 of 32 mug/ml for pexiganan in this study was >250-fold below the pexiganan concentration in the cream/delivery vehicle being developed for topical use.
TIHT== 
ABHT== 

PMID== 24480966
TI  == intraoperative vancomycin use in spinal surgery: single institution experience and microbial trends.
AB  == study design: retrospective case series. objective: to demonstrate the microbial  trends of spinal surgical site infections in patients who had previously received crystallized vancomycin in the operative bed. summary of background data: prior large, case control series demonstrate the significant decrease in surgical site  infection with the administration of vancomycin in the wound bed. methods: a single institution, electronic database search was conducted for all patients who underwent spinal surgery who had received prophylactic crystalline vancomycin powder in the wound bed. patients with a prior history of wound infection, intrathecal pumps, or spinal stimulators were excluded. results: a total of 981 consecutive patients (494 males, 487 females; mean age, 59.4 yr; range, 16-95 yr) were identified from january 2011 to june 2013. the average dose of vancomycin powder was 1.13 g (range, 1-6 g). sixty-six patients (6.71%) were diagnosed with  a surgical site infection, of which 51 patients had positive wound cultures (5.2%). of the 51 positive cultures, the most common organism was staphylococcus  aureus. the average dose of vancomycin was 1.3 g in the 38 cases where a gram-positive organism was cultured. a number of gram-negative infections were encountered such as serratia marcescens, enterobacter aerogenes, bacteroides fragilis, enterobacter cloacae, citrobacter koseri, and pseudomonas aeruginosa. the average dose of vancomycin was 1.2 g in 23 cases where a gram-negative infection was cultured. fifteen of the 51 positive cultures (29.4%) were polymicrobial. eight (53%) of these 15 polymicrobial cultures contained 3 or more distinct organisms. conclusion: prophylactic intraoperative vancomycin use in the wound bed in spinal surgery may increase the incidence of gram-negative or polymicrobial spinal infections. the use of intraoperative vancomycin may correlate with postoperative seromas, due to the high incidence of nonpositive cultures. large, randomized, prospective trials are needed to demonstrate causation and dose-response relationship.
TIHT== 
ABHT== 

PMID== 21500161
TI  == identification of bacteria isolated from nasal polyps and their ability to produce superantigens and biofilms in lebanese patients.
AB  == staphylococcus aureus superantigens and bacterial biofilms have been implicated in the development of chronic rhinosinusitis and nasal polyps. we conducted a study of 32 lebanese patients-21 males and 11 females, aged 15 to 71 years (mean: 39)-to identify bacteria isolated from nasal polyps and to determine if these bacteria produced superantigens and biofilms. polyps were surgically removed, homogenized, and subjected to bacteriologic studies. the presence or absence of s aureus enterotoxin a, b, c, and d (superantigen) genes was determined in all isolates by polymerase chain reaction. biofilm production by coagulase-negative staphylococci and pseudomonas aeruginosa was assessed by tissue culture plate assay. a total of 34 bacterial species/groups were isolated from the nasal polyps. of these, only 3 (8.8%) were s aureus, and only 1 possessed an enterotoxin-coding gene (enterotoxin b). moreover, of the 21 coagulase-negative staphylococci isolates that were found, none possessed the investigated genes, and only 1 had a strong biofilm-formation property. our results could not confirm that s aureus enterotoxins (superantigens) or biofilm-producing bacteria play a role in the development of nasal polyps in the lebanese group studied.
TIHT== 
ABHT== 

PMID== 20503587
TI  == antimicrobial resistant bacteria among health care workers in intensive care units at ain shams university hospitals.
AB  == fifty hcws in icus of internal medicine, chest, neonatology and burn were included in prospective cohort study. collection of nasal, hand and rectal swabs, proper biochemical identification, culture media and antibiotic sensitivity tests were used to detect methicillin-resistant staphylococcus aureus (mrsa); vancomycin-resistant enterococci (vre) & extended spectrum beta-lactamase producing gram -ve bacilli (esbls). s. aureus was isolated from 34% of hcws; 28%  were nasal carriers, 4% were hand carriers and 2% had s. aureus at both sites. nasal and hand carriage rates of mrsa were 20% & 4% respectively, with an overall rate of 22%. gram -ve bacilli were isolated from 8% of hcws hand swabs & showed citrobacter koseri, escherichia coli, klebsiella pneumoniae and pseudomonas aeruginosa. hand carriage rate of esbls was 2%. hand contamination with gram -ve  bacilli and s. aureus was in 14% of hcws. vre carriage rate was 9.5%. esbls carriage rate in rectal swabs was 21.43%. k. pneumoniae was the most common esbls producing isolate (33.3%), followed by e. coli (18.75%). in combined disc method, aztreonam was the most sensitive (90%) in detecting esbls. burn icu had highest % of mrsa & esbls carriage. neonatal icu showed highest % of vre carriage. an insignificant association was between infection control training or antimicrobial intake and carriage of antimicrobial resistant bacteria.
TIHT== 
ABHT== 

PMID== 20453188
TI  == elephantiasis nostras verrucosa (env): a complication of congestive heart failure and obesity.
AB  == congestive heart failure (chf) and obesity are common medical conditions that have many complications and an increasing incidence in the united states. presented here is a case of a disfiguring skin condition that visually highlights the dermatologic consequences of poorly controlled chf and obesity. this condition will probably become more common as chf and obesity increase in the us.
TIHT== 
ABHT== 

PMID== 19762956
TI  == prognostic serum tumor necrosis factor-alpha in paediatric patients with sepsis.
AB  == objective: to study the association of tumor necrosis factor-alpha (tnf-alpha) in paediatric patients with different etiological agents and levels of sepsis. methodology: seventy-nine patients with sepsis were studied. blood cultures, along with other relevant specimens, were processed for bacterial and fungal etiology. tnf-alpha was detected by enzyme immunoassay. results: in total, 42 (53.2%) of the patients had a microbiologically documented cause for sepsis. of the gram-negative bacilli, escherichia coli was the most common isolate followed  by klebsiella pneumoniae. enterobacter spp. serratia marscecens as well as citrobacter koseri. streptococcus pneumoniae and staphylococcus aureus predominated among the gram-positive cocci. patients with a positive culture had  significantly higher tnf-alpha levels than patients with a negative culture (70 pg/ml vs. 33 pg/ml p = 0.01). patients with a pure gram-negative infection had significantly higher tnf-alpha levels than those with pure gram-positive infection (83 pg/ml vs.52 pg/ml). the geometric mean tnf-alpha concentrations in  patients with severe sepsis and those with late septic shock were 47 pg/ml (range 5-2720) and 59 pg/ml (range 5-3310) respectively. conclusion: tnf-alpha was significantly raised in culture-positive cases in general and in gram-negative infections in particular. it can be used as a surrogate marker of sepsis and aggressive treatment initiated in patients with elevated levels of tnf alpha.
TIHT== 
ABHT== 

PMID== 18760086
TI  == [infectious complications of surgically treatment pelvic fractures].
AB  == based on case histories, the authors draw attention to important infectious complications in patients surgically treated for pelvic injuries. these complications were recorded in four out of 75 patients (5.3%) undergoing surgery  for pelvic fracture in the period from 2001 to 2005. the chief risk factors for the development of infection included the poor state of health of a polytraumatized patient in combination with a long stay in an acute care unit, and severe trauma and bleeding of soft tissue structures in b and c types of pelvic injury. bacteriological findings showed the presence of several pathogenic species (enterobacter cloacae, citrobacter koseri, pseudomonas aeruginosa and klebsiella oxytoca) or multi-resistant bacteria (methicillin-resistant staphylococcus aureus).
TIHT== 
ABHT== 

PMID== 18447206
TI  == [nationwide surveillance of parenteral antibiotics containing meropenem activities against clinically isolated strains in 2006].
AB  == the antibacterial activity of meropenem (mepm) and other parenteral antibiotics against clinical isolates of 876 strains of gram-positive bacteria, 1764 strains  of gram-negative bacteria, and 198 strains of anaerobic bacteria obtained from 30 medical institutions during 2006 was measured. the results were as follows; 1. mepm was more active than the other carbapenem antibiotics tested against gram-negative bacteria, especially against enterobacteriaceae and haemophilus influenzae. mepm was also active against most of the species tested in gram-positive and anaerobic bacteria, except for multi-drug resistant strains including methicillin-resistant staphylococcus aureus. 2. as for pseudomonas aeruginosa, all of the mepm-resistant strains were resistant to imipenem (ipm). mepm showed low cross-resistant rate both againt ipm-resistant p. aeruginosa (41.8%) and ciprofloxacin-resistant p. aeruginosa (33.3%). 3. the proportion of extended-spectrum beta-lactamase (esbl) strains was 4.3% (6 strains) in escherichia coli, 1.1% (1 strain) in citrobacter freundii, 21.7% (5 strains) in citrobacter koseri, 3.1% (4 strains) in klebsiella pneumoniae, 3.3% (3 strains) in enterobacter cloacae, 0.8% (1 strain) in serratia marcescens, and 4.9% (2 strains) in providencia spp. the proportion of metallo-beta-lactamase strains was 3.1% (10 strains) in p. aeruginosa. 4. of all species tested, there were no species, which mic90 of mepm was more than 4-fold higher than those in our previous study. therefore, there is almost no significant decrease in susceptibility of clinical isolates to meropenem. in conclusion, the results from this surveillance study suggest that mepm retains its potent and broad antibacterial activity and therefore is a clinically useful carbapenem at present, 11 years after available for commercial use.
TIHT== 
ABHT== 

PMID== 17088753
TI  == [clinical results of resection arthroplasty for infected shoulder arthroplasty].
AB  == purpose of the study: infection is a rare complication of shoulder arthroplasty.  various therapeutic solutions have been proposed: antibiotics alone, one-stage or two-stage reimplantation, surgical or arthroscopic cleaning without prosthesis removal, scapulohumeral arthrodesis or simple arthroscopic resection. we evaluated the mid-term clinical outcome after resection arthroplasty for the treatment of infected shoulder arthroplasty. material and methods: the series included ten infected arthroplasties in ten patients. mean duration of implantation was two years seven months (range nine months to five years). bacteriological diagnosis was established from intraoperative articular samples or systematic samples taken during surgical revision procedures: meti-s staphylococcus aureus strains (n=4), coagulase-negative staphylococcus (n=5 including three s. epidermidis) streptococcus mitis (n=1) and citrobacter koseri  (n=1). the mean constant score before revision was 58 (range 23-77). subjective patient satisfaction before surgical revision was rated good in six cases, fair in one and poor in three. surgery associated removal of the implant, complete resection of the cement, resection of the fistular tracts, wide debridement of infected tissues and total synovectomy. results: patients were seen at an average follow-up of three years eight months. the objective functional outcome measured  with the constant score was only fair, 28 points (range 20.6-36), and corresponded to a loss of 29 points compared with the preoperative score. this was explained mainly by lower scores for joint motion, function and muscle force  but with persistently satisfactory scores for pain. all patients remained pain-free (daytime and nighttime). patient satisfaction was rated good for two, fair for five and mediocre for three. clinical and biological proof of eradicated infection was obtained in all patients. discussion: infection remains a serious devastating problem for shoulder arthroplasty with an important functional impact. resection only has a modest clinical effect. precise identification of the causal germ with institution of adapted antibiotic therapy is required for eradication of the infection. early diagnosis is probably the most important parameter affecting clinical outcome and surgical options. functional results after resection arthroplasty are modest. this procedure should be reserved for patients with reduced functional demands. improved management of the infectious load and reduction of diagnostic delay should help improve functional outcome and favor use of stow-stage procedures for reinsertion.
TIHT== 
ABHT== 

PMID== 16968290
TI  == ft-ir microspectroscopy for early identification of some clinically relevant pathogens.
AB  == aims: to investigate the potentials and limitations of fourier transform-infrared (ft-ir) microspectroscopy as a tool to identify, at the level of microcolonies, pathogenic bacteria frequently isolated in the clinical environment. methods and  results: a total of 1570 ft-ir spectra from 164 gram-positive and gram-negative bacteria isolated from patients were recorded from 6 to 10-h old microcolonies of 50-150 microm size. a classification of 100% was obtained for the most frequent gram-positive bacteria, such as staphylococcus aureus, staphylococcus epidermidis, enterococcus faecalis, and enterococcus faecium at the species level. an average accuracy of about 80% was reached with gram negative bacteria from the enterobacteriaceae and pseudomonaceae families; enterobacter aerogenes,  enterobacter cloacae, klebsiella spp., and citrobacter koseri; and proteus mirabilis and escherichia coli. results were comparable with ft-ir measurements on dried suspensions from 18-h cultures. conclusions: early identification of young microcolonies is feasible with ft-ir microscopy with a very high accuracy for gram-positive bacteria. some improvement in the transfer of microcolonies is  necessary to increase the accuracy for gram-negative bacteria. significance and impact of the study: combination of ft-ir microscopy and multivariate data analysis could be a complementary, rapid, and reliable tool for screening and discriminating, at species and subspecies level, micro-organisms of clinical, food-borne, or environmental origins.
TIHT== 
ABHT== 

PMID== 16521347
TI  == [nationwide surveillance of parenteral antibiotics containing meropenem activities against clinically isolated strains in 2004].
AB  == the antibacterial activity of meropenem (mepm) and other parenteral antibiotics against clinical isolates of 907 strains of gram-positive bacteria, 1790 strains  of gram-negative bacteria, and 192 strains of anaerobic bacteria obtained from 30 medical institutions during 2004 was measured. the results were as follows; 1. mic90 of mepm for almost all of enterobacteriaceae and haemophilus influenzae were 4-fold to 32-fold lower than those of other carbapenems. mepm was more active than other carbapenem antibiotics against gram-negative bacteria, especially against enterobacteriaceae and h. influenzae. mepm were active against most of the species tested in gram-positive and anaerobic bacteria, except for multi-drug resistant strains including methicillin-resistant staphylococcus aureus. 2. as for pseudomonas aeruginosa, imipenem (ipm) showed high cross-resistant rate againt meropenem-resistant p. aeruginosa (87.9%). mepm showed low cross-resistant rate both againt ipm-resistant p. aeruginosa (49.2%) and ciprofloxacin-resistant p. aeruginosa (38.0%). 3. the proportion of extended-spectrum beta-lactamase (esbl) strains was 3.1% (4 strains) in escherichia coli, 8.0% (2 strains) in citrobacter koseri, 2.5% (3 strains) in klebsiella pneumoniae, 2.5% (2 strains) in enterobacter cloacae, 0.9% (1 strains) in serratia marcescens, and 2.2% (2 strains) in proteus mirabilis. the proportion of metallo-beta-lactamase strains was 1.6% (5 strains) in p. aeruginosa. 4. of all species tested, peptostreptococcus spp. was the only species, which mic90 of  mepm was more than 4-fold higher than that in our previous study using clinical isolates during 2002 (0.25 microg/ml --> 1 microg/ml). therefore, there is almost no siginificant decrease in susceptibility of clinical isolates to meropenem. in  conclusion, the results from this surveillance study suggest that mepm retains its potent and broad antibacterial activity and therefore is a clinically useful  carbapenem at present, 9 years after available for commercial use.
TIHT== 
ABHT== 

