@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 24071026
TI  == role of probiotics in the prevention and treatment of meticillin-resistant staphylococcus aureus infections.
AB  == meticillin-resistant staphylococcus aureus (mrsa) is a multidrug-resistant micro-organism and is the principal nosocomial pathogen worldwide. following initial in vitro experiments demonstrating that lactobacillus acidophilus cl1285((r)) and lactobacillus casei lbc80r((r)) commercial strains exhibit antibacterial activity against clinical mrsa isolates, we conducted a literature  search to find any evidence of probiotic efficacy in decolonisation or treatment  of s. aureus infection. as summarised below, many strains of lactobacilli and bifidobacteria isolated from a variety of sources inhibited the growth of s. aureus and clinical isolates of mrsa in vitro. the most active strains were lactobacillus reuteri, lactobacillus rhamnosus gg, propionibacterium freudenreichii, propionibacterium acnes, lactobacillus paracasei, l. acidophilus, l. casei, lactobacillus plantarum, lactobacillus bulgaricus, lactobacillus fermentum and lactococcus lactis. their effects were mediated both by direct cell competitive exclusion as well as production of acids or bacteriocin-like inhibitors. l. acidophilus also inhibited s. aureus biofilm formation and lipase  production. in vitro antimicrobial activity did not necessarily assure efficacy in vivo in animal infectious models, e.g. s. aureus 8325-4 was most sensitive in  vitro to l. acidophilus, whilst in vivo bifidobacterium bifidum best inhibited experimental intravaginal staphylococcosis in mice. on the other hand, l. plantarum, which showed the highest inhibition activity against s. aureus in vitro, was also very effective topically in preventing skin wound infection with  s. aureus in mice. very few clinical data were found on the interactions between  probiotics and mrsa, but the few identified clinical cases pointed to the feasibility of elimination or reduction of mrsa colonisation with probiotic use.
TIHT== 
ABHT== 

PMID== 16735744
TI  == staphylococcus aureus adheres to human intestinal mucus but can be displaced by certain lactic acid bacteria.
AB  == there is increasing evidence that staphylococcus aureus may colonize the intestinal tract, especially among hospitalized patients. as staph. aureus has been found to be associated with certain gastrointestinal diseases, it has become important to study whether this bacterium can colonize the intestinal tract and if so, whether it is possible to prevent colonization. adhesion is the first step in colonization; this study shows that staph. aureus adheres to mucus from resected human intestinal tissue. certain lactic acid bacteria (lab), mainly commercial probiotics, were able to reduce adhesion and viability of adherent staph. aureus. in displacement assays the amount of adherent staph. aureus in human intestinal mucus was reduced 39-44% by lactobacillus rhamnosus gg, lactococcus lactis subsp. lactis and propionibacterium freudenreichii subsp. shermanii. moreover, adherent lactobacillus reuteri, lc. lactis and p. freudenreichii reduced viability of adherent staph. aureus by 27-36%, depending on the strain, after 2 h incubation. this was probably due to the production of organic acids and hydrogen peroxide and possibly in the case of l. reuteri to the production of reuterin. this study shows for the first time that staph. aureus can adhere to human intestinal mucus and adherent bacteria can be displaced and killed by certain lab strains via in situ production of antimicrobial substances.
TIHT== 
ABHT== 

PMID== 9757558
TI  == production of a mixture of antimicrobial organic acids from lactose by co-culture of bifidobacterium longum and propionibacterium freudenreichii.
AB  == the antimicrobial activities of standard solutions of three organic acids (lactic, acetic, and propionic acids) were compared using micrococcus luteus, pseudomonas sp. and staphylococcus aureus as test microorganisms. at the same concentrations of the undissociated form, the antimicrobial activities of acetic  and propionic acids were higher than that of lactic acid, irrespective of test microorganisms. in a single cultivation of bifidobacterium longum, a mixture of lactic (17 g/l) and acetic (20 g/l) acids was produced from 50 g/l lactose and its antimicrobial activities against m. luteus, pseudomonas sp., and s. aureus correspond to that of 32, 19, and 25 g/l of acetic acid, respectively. to increase the total antimicrobial activity, a co-culture of b. longum and propionibacterium freudenreichii, in which lactic acid produced once from lactose by b. longum was converted to acetic and propionic acids by p. freudenreichii, was done using tpy medium containing commercially available peptones as a nitrogen source. by the sequential conversion of lactose using the two microorganisms, the culture supernatant containing a mixture of acetic (27 g/l) and propionic (13 g/l) acids without lactic acid was produced. the antimicrobial  activities of the mixture against m. luteus, pseudomonas sp., and s. aureus were  35, 30, and 26 g/l as a concentration of acetic acid, respectively, higher than that obtained in the cultivation of b. longum alone. when the medium containing an enzymatic hydrolyzate of whey proteins with a protease was used in the co-culture of b. longum and p. freudenreichii, the culture supernatant containing the mixture of organic acids was also obtained in the same manner as the co-culture using tpy medium and the activities were 43, 29, and 29 g/l as a concentration of acetic acid for m. luteus, pseudomonas sp. and s. aureus, respectively.
TIHT== 
ABHT== 

