@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25616316
TI  == comparison of species identification of endocarditis associated viridans streptococci using rnpb genotyping and 2 maldi-tof systems.
AB  == streptococcus spp. are important causes of infective endocarditis but challenging in species identification. this study compared identification based on sequence determination of the rnpb gene with 2 systems of matrix-assisted laser desorption ionization-time of flight mass spectrometry, maldi biotyper (bruker) and vitek ms ivd (biomerieux). blood culture isolates of viridans streptococci from 63 patients with infective endocarditis were tested. the 3 methods showed full agreement for all 36 isolates identified in the anginosus, bovis, and mutans groups or identified as streptococcus cristatus, streptococcus gordonii, or streptococcus sanguinis. none of the methods could reliably identify the 23 isolates to the species level when designated as streptococcus mitis, streptococcus oralis, or streptococcus tigurinus. in 7 isolates classified to the mitis group, the rnpb sequences deviated strikingly from all reference sequences, and additional analysis of soda and groel genes indicated the occurrence of yet unidentified streptococcus spp.
TIHT== 
ABHT== 

PMID== 24048531
TI  == evaluation of the nanosphere verigene gram-positive blood culture assay with the  versatrek blood culture system and assessment of possible impact on selected patients.
AB  == the verigene gram-positive blood culture (bc-gp) assay (nanosphere, northbrook, il) is a molecular method for the rapid identification of gram-positive organisms and resistance markers directly from blood culture bottles. a total of 148 versatrek redox 1 40-ml aerobic bottles demonstrating gram-positive bacteria were tested. results were compared with those from conventional biochemical and matrix-assisted laser desorption ionization-time of flight (maldi-tof) identifications. we obtained isolates of methicillin-resistant staphylococcus aureus (mrsa) (24), methicillin-susceptible staphylococcus aureus (mssa) (14), methicillin-resistant staphylococcus epidermidis (mrse) (17), methicillin-susceptible staphylococcus epidermidis (msse) (9), other coagulase-negative staphylococci (19), streptococcus salivarius (5), streptococcus parasanguinis (2), streptococcus sanguinis (1), streptococcus cristatus (1), the streptococcus bovis group (5), streptococcus agalactiae (9), the streptococcus anginosus group (1), streptococcus pneumoniae (6), vancomycin-resistant enterococcus faecium (vre fcm) (16), vancomycin-susceptible  enterococcus faecalis (3), aerococcus viridans (2), bacillus (6), corynebacterium (8), lactobacillus (2), micrococcus (2), neisseria mucosa (1), escherichia coli (3), candida tropicalis (1), propionibacterium (1), and rothia (1). overall agreement with the culture results was 95%. a total of 137 of 138 (99%) monomicrobial cultures were concordant. we tested 9 polymicrobial samples and found 33% agreement. a chart review of 31 patients with mrsa, mssa, or vre demonstrated that the nanosphere bc-gp assay might have led to more appropriate antibiotic selection for these patients an average of 42 h earlier. additionally, contact isolation could have been initiated an average of 37 h earlier for patients with mrsa or vre. the bc-gp assay may have a positive impact on patient  care, health care costs, and antibiotic stewardship.
TIHT== 
ABHT== 

PMID== 19880633
TI  == partial recn gene sequencing: a new tool for identification and phylogeny within  the genus streptococcus.
AB  == partial sequences of the recn gene (1249 bp), which encodes a recombination and repair protein, were analysed to determine the phylogenetic relationship and identification of streptococci. the partial sequences presented interspecies nucleotide similarity of 56.4-98.2 % and intersubspecies similarity of 89.8-98 %. the mean dna sequence similarity of recn gene sequences (66.6 %) was found to be  lower than those of the 16s rrna gene (94.1 %), rpob (84.6 %), soda (74.8 %), groel (78.1 %) and gyrb (73.2 %). phylogenetically derived trees revealed six statistically supported groups: streptococcus salivarius, s. equinus, s. hyovaginalis/s. pluranimalium/s. thoraltensis, s. pyogenes, s. mutans and s. suis. the 'mitis' group was not supported by a significant bootstrap value, but three statistically supported subgroups were noted: streptococcus sanguinis/s. cristatus/s. sinensis, s. anginosus/s. intermedius/s. constellatus (the 'anginosus' subgroup) and s. mitis/s. infantis/s. peroris/s. oralis/s. oligofermentans/s. pneumoniae/s. pseudopneumoniae. the partial recn gene sequence comparison highlighted a high percentage of divergence between streptococcus dysgalactiae subsp. dysgalactiae and s. dysgalactiae subsp. equisimilis. this observation is confirmed by other gene sequence comparisons (groel, gyrb, rpob and soda). a high percentage of similarity was found between s. intermedius and s. constellatus after sequence comparison of the recn gene. to study the genetic  diversity among the 'anginosus' subgroup, recn, groel, soda, gyrb and rpob sequences were determined for 36 clinical isolates. the results that were obtained confirmed the high genetic diversity within this group of streptococci.
TIHT== 
ABHT== 

