@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 24484531
TI  == 16s rdna-based metagenomic analysis of dental plaque and lung bacteria in patients with severe acute exacerbations of chronic obstructive pulmonary disease.
AB  == background and objective: acute exacerbations of chronic obstructive pulmonary disease (ae-copd) are leading causes of mortality in hospital intensive care units. we sought to determine whether dental plaque biofilms might harbor pathogenic bacteria that can eventually cause lung infections in patients with severe ae-copd. material and methods: paired samples of subgingival plaque biofilm and tracheal aspirate were collected from 53 patients with severe ae-copd. total bacterial dna was extracted from each sample individually for polymerase chain reaction amplification and/or generation of bacterial 16s rdna sequences and cdna libraries. we used a metagenomic approach, based on bacterial  16s rdna sequences, to compare the distribution of species present in dental plaque and lung. results: analysis of 1060 sequences (20 clones per patient) revealed a wide range of aerobic, anaerobic, pathogenic, opportunistic, novel and uncultivable bacterial species. species indistinguishable between the paired subgingival plaque and tracheal aspirate samples (97-100% similarity in 16s rdna  sequence) were dental plaque pathogens (aggregatibacter actinomycetemcomitans, capnocytophaga sputigena, porphyromonas gingivalis, tannerella forsythia and treponema denticola) and lung pathogens (acinetobacter baumannii, klebsiella pneumoniae, pseudomonas aeruginosa and streptococcus pneumoniae). real-time polymerase chain reaction of 16s rdna indicated lower levels of pseudomonas aeruginosa and porphyromonas gingivalis colonizing the dental plaques compared with the paired tracheal aspirate samples. conclusion: these results support the  hypothesis that dental bacteria may contribute to the pathology of severe ae-copd.
TIHT== 
ABHT== 

PMID== 20826648
TI  == bacterial 16s sequence analysis of severe caries in young permanent teeth.
AB  == previous studies have confirmed the association of the acid producers streptococcus mutans and lactobacillus spp. with childhood caries, but they also  suggested these microorganisms are not sufficient to explain all cases of caries. in addition, health-associated bacterial community profiles are not well understood, including the importance of base production and acid catabolism in ph homeostasis. the bacterial community composition in health and in severe caries of the young permanent dentition was compared using sanger sequencing of the ribosomal 16s rrna genes. lactobacillus species were dominant in severe caries, and levels rose significantly as caries progressed from initial to deep lesions.  s. mutans was often observed at high levels in the early stages of caries but also in some healthy subjects and was not statistically significantly associated  with caries progression in the overall model. lactobacillus or s. mutans was found either at low levels or not present in several samples. other potential acid producers observed at high levels in these subjects included strains of selenomonas, neisseria, and streptococcus mitis. propionibacterium fma5 was significantly associated with caries progression but was not found at high levels. an overall loss of community diversity occurred as caries progressed, and species that significantly decreased included the streptococcus mitis-s. pneumoniae-s. infantis group, corynebacterium matruchotii, streptococcus gordonii, streptococcus cristatus, capnocytophaga gingivalis, eubacterium ir009,  campylobacter rectus, and lachnospiraceae sp. c1. the relationship of acid-base metabolism to 16s rrna gene-based species assignments appears to be complex, and  metagenomic approaches that would allow functional profiling of entire genomes will be helpful in elucidating the microbial pathogenesis of caries.
TIHT== 
ABHT== 

