@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 26033167
TI  == microbial dynamics during conversion from supragingival to subgingival biofilms in an in vitro model.
AB  == the development of dental caries and periodontal diseases result from distinct shifts in the microbiota of the tooth-associated biofilm. this in vitro study aimed to investigate changes in biofilm composition and structure, during the shift from a "supragingival" aerobic to a "subgingival" anaerobic profile. biofilms consisting of actinomyces oris, candida albicans, fusobacterium nucleatum, streptococcus oralis, streptococcus mutans and veillonella dispar were aerobically grown in saliva-containing medium on hydroxyapatite discs. after 64 h, campylobacter rectus, prevotella intermedia and streptococcus anginosus were further added along with human serum, while culture conditions were shifted to microaerophilic. after 96 h, porphyromonas gingivalis, tannerella forsythia and treponema denticola were finally added and the biofilm was grown anaerobically for another 64 h. at the end of each phase, biofilms were harvested for species-specific quantification and localization. apart from c. albicans, all other species gradually increased during aerobic and microaerophilic conditions,  but remained steady during anaerobic conditions. biofilm thickness was doubled during the microaerophilic phase, but remained steady throughout the anaerobic phase. extracellular polysaccharide presence was gradually reduced throughout the growth period. biofilm viability was reduced during the microaerophilic conversion, but was recovered during the anaerobic phase. this in vitro study has characterized the dynamic structural shifts occurring in an oral biofilm model during the switch from aerobic to anaerobic conditions, potentially modeling the  conversion of supragingival to subgingival biofilms. within the limitations of this experimental model, the findings may provide novel insights into the ecology of oral biofilms. this article is protected by copyright. all rights reserved.
TIHT== 
ABHT== 

PMID== 25412607
TI  == oral bacterial dna findings in pericardial fluid.
AB  == background: we recently reported that large amounts of oral bacterial dna can be  found in thrombus aspirates of myocardial infarction patients. some case reports  describe bacterial findings in pericardial fluid, mostly done with conventional culturing and a few with pcr; in purulent pericarditis, nevertheless, bacterial pcr has not been used as a diagnostic method before. objective: to find out whether bacterial dna can be measured in the pericardial fluid and if it correlates with pathologic-anatomic findings linked to cardiovascular diseases. methods: twenty-two pericardial aspirates were collected aseptically prior to forensic autopsy at tampere university hospital during 2009-2010. of the autopsies, 10 (45.5%) were free of coronary artery disease (cad), 7 (31.8%) had mild and 5 (22.7%) had severe cad. bacterial dna amounts were determined using real-time quantitative pcr with specific primers and probes for all bacterial strains associated with endodontic disease (streptococcus mitis group, streptococcus anginosus group, staphylococcus aureus/staphylococcus epidermidis,  prevotella intermedia, parvimonas micra) and periodontal disease (aggregatibacter actinomycetemcomitans, porphyromonas gingivalis, treponema denticola, fusobacterium nucleatus, and dialister pneumosintes). results: of 22 cases, 14 (63.6%) were positive for endodontic and 8 (36.4%) for periodontal-disease-associated bacteria. only one case was positive for bacterial culturing. there was a statistically significant association between the relative amount of bacterial dna in the pericardial fluid and the severity of cad (p=0.035). conclusions: oral bacterial dna was detectable in pericardial fluid and an association between the severity of cad and the total amount of bacterial  dna in pericardial fluid was found, suggesting that this kind of measurement might be useful for clinical purposes.
TIHT== 
ABHT== 

PMID== 24949828
TI  == colonisation of gingival epithelia by subgingival biofilms in vitro: role of "red complex" bacteria.
AB  == objectives: biofilm formation on tooth surface results in colonisation and invasion of the juxtaposed gingival tissue, eliciting strong inflammatory responses that lead to periodontal disease. this in vitro study investigated the  colonisation of human gingival multi-layered epithelium by multi-species subgingival biofilms, and evaluated the relative effects of the "red complex" species (porphyromonas gingivalis, tannerella forsythia and treponema denticola). methods: the grown biofilm consisted of fusobacterium nucleatum, campylobacter rectus, veillonella dispar, p. gingivalis, prevotella intermedia, t. forsythia, t. denticola, actinomyces oris, streptococcus anginosus and streptococcus oralis, or its variant lacking the "red complex". after 48h in co-culture with the gingival epithelia, the bacterial species in the biofilm were quantified, whereas their localisation on the cell surface was investigated by combining confocal-laser scanning microscopy (clsm) and fluorescence in situ hybridisation  (fish), as well as by scanning electron microscopy (sem). results: exclusion of the "red complex" quantitatively affected s. oralis, but not other species. the "red-complex" species were all able to colonise the gingival epithelial cells. a  co-localisation trend was observed between p. gingivalis and t. denticola, as determined by fish. however, in the absence of all three "red complex" bacteria from the biofilm, an immense colonisation of streptococci (potentially s. oralis) was observed on the gingival epithelia, as confirmed by both clsm and sem. conclusions: while the "red complex" species synergise in colonizing gingival epithelia, their absence from the biofilm enhances streptococcal colonisation. this antagonism with streptococci reveals that the "red complex" may regulate biofilm virulence, with potential implications in periodontal pathogenesis.
TIHT== 
ABHT== 

PMID== 24340084
TI  == impact of early colonizers on in vitro subgingival biofilm formation.
AB  == the aim of this study was to investigate the impact of early colonizing species on the structure and the composition of the bacterial community developing in a subgingival 10-species biofilm model system. the model included streptococcus oralis, streptococcus anginosus, actinomycesoris, fusobacterium nucleatum subsp.  nucleatum, veillonella dispar, campylobacter rectus, prevotella intermedia, porphyromonas gingivalis, tannerella forsythia, and treponema denticola. based on literature, we considered streptococcus oralis, streptococcus anginosus, and actinomyces oris as early colonizers and examined their role in the biofilms by either a delayed addition to the consortium, or by not inoculating at all the biofilms with these species. we quantitatively evaluated the resulting biofilms by real-time quantitative pcr and further compared the structures using confocal  laser scanning microscopy following fluorescence in situ hybridisation. the absence of the early colonizers did not hinder biofilm formation. the biofilms reached the same total counts and developed to normal thickness. however, quantitative shifts in the abundances of individual species were observed. in the absence of streptococci, the overall biofilm structure appeared looser and more dispersed. moreover, besides a significant increase of p. intermedia and a decrease of p. gingivalis , p. intermedia appeared to form filamented long chains that resembled streptococci. a. oris, although growing to significantly higher abundance in absence of streptococci, did not have a visible impact on the biofilms. hence, in the absence of the early colonizers, there is a pronounced effect on p. intermedia and p. gingivalis that may cause distinct shifts in the structure of the biofilm. streptococci possibly facilitate the establishment of p. gingivalis into subgingival biofilms, while in their absence p. intermedia became more dominant and forms elongated chains.
TIHT== 
ABHT== 

PMID== 23278531
TI  == validation of a quantitative real-time pcr assay and comparison with fluorescence microscopy and selective agar plate counting for species-specific quantification  of an in vitro subgingival biofilm model.
AB  == background and objective: subgingival biofilms are the prime etiological factor of periodontal disease. owing to their complex polymicrobial nature, quantification of individual bacterial species within the biofilm for research and diagnostic purposes can be methodologically challenging. the aims of this study were to establish a quantitative real-time pcr (qpcr) assay to quantify the bacteria used in our 10-species in vitro 'subgingival' biofilm model and to compare the quantitative outcome with fluorescence microscopy and colony-forming  unit (cfu) counts on selective agar plates. material and methods: the 10 species  included in the in vitro biofilm were streptococcus oralis, streptococcus anginosus, veillonella dispar, fusobacterium nucleatum, treponema denticola, tannerella forsythia, actinomyces oris, campylobacter rectus, porphyromonas gingivalis and prevotella intermedia. the numbers of each species were quantified at two time points using qpcr, microscopy counting following fluorescence in-situ hybridization (fish) or immunofluorescence staining, and counting of cfus after growth on selective agar plates. results: all 10 species were successfully quantified using qpcr and fish or immunofluorescence, and the eight species culturable on selective agar plates were also quantified by counting the numbers  of cfus after growth on selective agar. in early biofilm cultures, all methods showed a significant correlation, although the absolute numbers differed between  methods. in late biofilm cultures, measurements obtained using qpcr and fish or immunofluorescence, but not by cfu counts, maintained significant correlation. cfu counts yielded lower values than did measurements made using the other two methods. conclusion: quantitative pcr and epifluorescence microscopy can be easily combined with each other to determine species-specific bacterial numbers within biofilms. however, conventional bacterial cultures cannot be as efficiently combined using these molecular detection methods. this may be crucial in designing and selecting appropriate clinical diagnostic methods for subgingival biofilm samples.
TIHT== 
ABHT== 

PMID== 23163048
TI  == [role of infectious agents in the emergence of malignant tumors].
AB  == according to the data of the international agency for research on cancer (iarc),  at least 6 virus species (hpv, ebv, hhv-8/kshv, htlv-1, hbv, hcv), 4 helminthes species (schistosoma haematobium and japonicum, opisthorchis viverrini, clonorchis sinensis) and i bacterium species (helicobacter pylori) have been proved to be capable of causing the development of cancer. the analysis of the data available shows that merkel cell polyomavirus (mcv), herpes simplex virus (hsv), john cunningham polyomavirus (jcv), monkey virus 40 (sv40), cytomegalovirus (cmv), xenotropic murine leukemia virus (xmrv), helicobacter bilis and hepaticus, campylobacter jejuni, fusobacterium varium, enteropathogenic escherichia coli, enterotoxigenic bacteroides fragilis, bacteroides vulgatus, prevotella spp., streptococcus bovis and anginosus, treponema denticola, salmonella typhi, paratyphi and typhimurium, borrelia burgdorferi, bartonella spp., mycobacterium tuberculosis, chlamydia pneumoniae, trachomatis and psittaci, neisseria gonorrhoeae, propionibacterium acnes, tropheryma whippelii, schistosoma mansoni, opistorchis felineus, strongyloides stercoralis, taenia solium, candida  spp., paracoccidioides brasiliensis, histoplasma capsulatum and trichomonas vaginalis can also be potential etiological agents of cancer. apparently, detection of new associations between infectious agents and risk of the development of cancer will facilitate progress in elaboration of prophylaxis measures, early diagnostic methods and, probably, methods of treatment of malignant tumors.
TIHT== 
ABHT== 

PMID== 23060013
TI  == subgingival microflora in inflammatory bowel disease patients with untreated periodontitis.
AB  == objective: to analyze the subgingival microflora composition of inflammatory bowel disease (ibd) patients with untreated chronic periodontitis and compare them with systemically healthy controls also having untreated chronic periodontitis. method: thirty ibd patients [15 with crohn's disease (cd) and 15 with ulcerative colitis (uc)] and 15 control individuals participated in the study. all patients had been diagnosed with untreated chronic periodontitis. from every patient, subgingival plaque was collected from four gingivitis and four periodontitis sites with paper points. samples from the same category (gingivitis or periodontitis) in each patient were pooled together and stored at -70 degrees  c until analysis using a checkerboard dna-dna hybridization technique for 74 bacterial species. results: multiple-comparison analysis showed that the groups differed in bacterial counts for bacteroides ureolyticus, campylobacter gracilis, parvimonas micra, prevotella melaninogenica, peptostreptococcus anaerobius, staphylococcus aureus, streptococcus anginosus, streptococcus intermedius, streptococcus mitis, streptococcus mutans, and treponema denticola (p<0.001). cd  patients had significantly higher levels of these bacteria than uc patients either in gingivitis or in periodontitis sites (p<0.05). cd patients harbored higher levels of p. melaninogenica, s. aureus, s. anginosus, and s. mutans compared with controls both at gingivitis and at periodontitis sites (p<0.05). uc patients harbored higher levels of s. aureus (p=0.01) and p. anaerobius (p=0.05)  than controls only in gingivitis sites. conclusion: our study showed that even with similar clinical periodontal parameters, ibd patients harbor higher levels of bacteria that are related to opportunistic infections in inflamed subgingival  sites that might be harmful for the crucial microbe-host interaction.
TIHT== 
ABHT== 

PMID== 19228092
TI  == does pregnancy have an impact on the subgingival microbiota?
AB  == background: we investigated clinical and subgingival microbiologic changes during pregnancy in 20 consecutive pregnant women > or =18 years not receiving dental care. methods: bacterial samples from weeks 12, 28, and 36 of pregnancy and at 4  to 6 weeks postpartum were processed for 37 species by checkerboard dna-dna hybridization. clinical periodontal data were collected at week 12 and at 4 to 6  weeks postpartum, and bleeding on probing (bop) was recorded at sites sampled at  the four time points. results: the mean bop at week 12 and postpartum was 40.1% +/- 18.2% and 27.4% +/- 12.5%, respectively. the corresponding mean bop at microbiologic test sites was 15% (week 12) and 21% (postpartum; not statistically significant). total bacterial counts decreased between week 12 and postpartum (p  <0.01). increased bacterial counts over time were found for neisseria mucosa (p <0.001). lower counts (p <0.001) were found for capnocytophaga ochracea, capnocytophaga sputigena, eubacterium saburreum, fusobacterium nucleatum naviforme, fusobacterium nucleatum polymorphum, leptotrichia buccalis, parvimonas micra (previously peptostreptococcus micros or micromonas micros), prevotella intermedia, prevotella melaninogenica, staphylococcus aureus, streptococcus anginosus, streptococcus intermedius, streptococcus mutans, streptococcus oralis, streptococcus sanguinis, selenomonas noxia, and veillonella parvula. no changes occurred between weeks 12 and 28 of pregnancy. counts of aggregatibacter actinomycetemcomitans (previously actinobacillus actinomycetemcomitans), porphyromonas gingivalis, tannerella forsythia (previously t. forsythensis), and  treponema denticola did not change. counts of p. gingivalis and t. forsythia at week 12 were associated with gingivitis (p <0.001). conclusions: subgingival levels of bacteria associated with periodontitis did not change. p. gingivalis and t. forsythia counts were associated with bop at week 12. a decrease was found in 17 of 37 species from week 12 to postpartum. only counts of n. mucosa increased.
TIHT== 
ABHT== 

PMID== 12483235
TI  == correlations between bacterial levels in autologous subgingival plaque and saliva of adult sudanese.
AB  == the aim of this study was to assess levels of oral bacteria and their correlations in paired samples of saliva and subgingival plaque in a population of adult sudanese. whole saliva and pooled subgingival plaque samples from six probing sites of one tooth in each jaw were obtained from 56 sudanese adults (mean age 35.2+/-8.9 years). levels of 24 oral bacteria in the autologous saliva  and pooled plaque sample of each subject were assessed by dna probes and checkerboard dna-dna hybridization. there were significantly ( p< or =0.01) higher percentages of subjects with > or =10(5) bacterial cells of prevotella intermedia, campylobacter rectus, veillonella parvula, streptococcus mutans, lactobacillus acidophilus, streptococcus anginosus, streptococcus salivarius, and leptotrichia buccalis and significantly ( p< or =0.01) lower percentages with treponema denticola in saliva than in subgingival plaque. the detection frequencies at > or =10(6) bacterial cells were significantly higher for selenomonas sputigena, s. anginosus, streptococcus sanguis, and s. salivarius and significantly lower for porphyromonas gingivalis in saliva than in subgingival plaque ( p< or =0.01). porphyromonas gingivalis, fusobacterium nucleatum, s. sputigena, s. sanguis, and streptococcus mitis demonstrated significant ( p< or =0.05) positive correlations between their levels in plaque and saliva. this study indicates that the levels of p. gingivalis, f. nucleatum, s. sputigena, s.  sanguis, and s. mitis correlate significantly in saliva and subgingival plaque and that higher accuracy of detection and assessment of the levels of these bacteria in the oral cavity may be achieved by concurrent sampling of saliva and  subgingival plaque.
TIHT== 
ABHT== 

