@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25533634
TI  == construction and validation of a mcherry protein vector for promoter analysis in  lactobacillus acidophilus.
AB  == lactobacilli are widespread in natural environments and are increasingly being investigated as potential health modulators. in this study, we have adapted the broad-host-range vector pnz8048 to express the mcherry protein (prcr) to expand the usage of the mcherry protein for analysis of gene expression in lactobacillus. this vector is also able to replicate in streptococcus pneumoniae  and escherichia coli. the usage of prcr as a promoter probe was validated in lactobacillus acidophilus by characterizing the regulation of lactacin b expression. the results show that the regulation is exerted at the transcriptional level, with lbab gene expression being specifically induced by co-culture of the l. acidophilus bacteriocin producer and the s. thermophilus sty-31 inducer bacterium.
TIHT== 
ABHT== 

PMID== 25054342
TI  == the cation diffusion facilitator protein emfa of rhizobium etli belongs to a novel subfamily of mn(2+)/fe(2+) transporters conserved in alpha-proteobacteria.
AB  == manganese (mn(2+)) plays a key role in important cellular functions such as oxidative stress response and bacterial virulence. the mechanisms of mn(2+) homeostasis are not fully understood, there are few data regarding the functional and taxonomic diversity of mn(2+) exporters. our recent phylogeny of the cation diffusion facilitator (cdf) family of transporters classified the bacterial mn(2+)-cdf transporters characterized to date, streptococcus pneumoniae mnte and  deinococcus radiodurans dr1236, into two monophyletic groups. dr1236 was shown to belong to the highly-diverse metal specificity clade vi, together with ttczrb, a  zn(2+)/cd(2+) transporter from thermus thermophilus, the fe(2+) transporter sll1263 from synechocystis sp and eight uncharacterized homologs whose potential  mn(2+)/zn(2+)/cd(2+)/fe(2+) specificities could not be accurately inferred because only eleven proteins were grouped in this clade. a new phylogeny inferred from the alignment of 197 clade vi homologs revealed three novel subfamilies of uncharacterized proteins. remarkably, one of them contained 91 uncharacterized alpha-proteobacteria transporters (46% of the protein data set) grouped into a single subfamily. the mn(2+)/fe(2+) specificity of this subfamily was proposed through the functional characterization of the rhizobium etli rhe_ch03072 gene. this gene was upregulated by mn(2+), zn(2+), cd(2+) and fe(2+) but conferred only mn(2+) resistance to r. etli. the expression of the rhe_ch03072 gene in an e. coli mntp/zitb/znta mutant did not relieve either zn(2+) or mn(2+) stress but slightly increased its fe(2+) resistance. these results indicate that the rhe_ch03072 gene, now designated as emfa, encodes for a bacterial mn(2+)/fe(2+) resistance cdf protein, having orthologs in more than 60 alpha-proteobacterial species.
TIHT== 
ABHT== 

PMID== 23204467
TI  == sos response activation and competence development are antagonistic mechanisms in streptococcus thermophilus.
AB  == streptococcus includes species that either contain or lack the lexa-like repressor (hdir) of the classical sos response. in streptococcus pneumoniae, a species which belongs to the latter group, sos response inducers (e.g., mitomycin c [mc] and fluoroquinolones) were shown to induce natural transformation, leading to the hypothesis that dna damage-induced competence could contribute to genomic  plasticity and stress resistance. using reporter strains and microarray experiments, we investigated the impact of the sos response inducers mitomycin c  and norfloxacin and the role of hdir on competence development in streptococcus thermophilus. we show that both the addition of sos response inducers and hdir inactivation have a dual effect, i.e., induction of the expression of sos genes and reduction of transformability. reduction of transformability results from two different mechanisms, since hdir inactivation has no major effect on the expression of competence (com) genes, while mitomycin c downregulates the expression of early and late com genes in a dose-dependent manner. the downregulation of com genes by mitomycin c was shown to take place at the level of the activation of the comrs signaling system by an unknown mechanism. conversely, we show that a comx-deficient strain is more resistant to mitomycin c and norfloxacin in a viability plate assay, which indicates that competence development negatively affects the resistance of s. thermophilus to dna-damaging  agents. altogether, our results strongly suggest that sos response activation and competence development are antagonistic processes in s. thermophilus.
TIHT== 
ABHT== 

PMID== 23033471
TI  == occurrence and evolution of the paralogous zinc metalloproteases iga1 protease, zmpb, zmpc, and zmpd in streptococcus pneumoniae and related commensal species.
AB  == the distribution, genome location, and evolution of the four paralogous zinc metalloproteases, iga1 protease, zmpb, zmpc, and zmpd, in streptococcus pneumoniae and related commensal species were studied by in silico analysis of whole genomes and by activity screening of 154 representatives of 20 species. zmpb was ubiquitous in the mitis and salivarius groups of the genus streptococcus and in the genera gemella and granulicatella, with the exception of a fragmented  gene in streptococcus thermophilus, the only species with a nonhuman habitat. iga1 protease activity was observed in all members of s. pneumoniae, s. pseudopneumoniae, s. oralis, s. sanguinis, and gemella haemolysans, was variably  present in s. mitis and s. infantis, and absent in s. gordonii, s. parasanguinis, s. cristatus, s. oligofermentans, s. australis, s. peroris, and s. suis. phylogenetic analysis of 297 zmp sequences and representative housekeeping genes  provided evidence for an unprecedented selection for genetic diversification of the iga, zmpb, and zmpd genes in s. pneumoniae and evidence of very frequent intraspecies transfer of entire genes and combination of genes. presumably due to their adaptation to a commensal lifestyle, largely unaffected by adaptive mucosal immune factors, the corresponding genes in commensal streptococci have remained conserved. the widespread distribution and significant sequence diversity indicate an ancient origin of the zinc metalloproteases predating the emergence of the humanoid species. zmpb, which appears to be the ancestral gene, subsequently duplicated and successfully diversified into distinct functions, is  likely to serve an important but yet unknown housekeeping function associated with the human host. importance: the paralogous zinc metalloproteases iga1 protease, zmpb, zmpc, and zmpd have been identified as crucial for virulence of the human pathogen streptococcus pneumoniae. this study maps the presence of the  corresponding genes and enzyme activities in s. pneumoniae and in related commensal species of the genera streptococcus, gemella, and granulicatella. the distribution, genome location, and sequence diversification indicate that zmpb is the ancestral gene predating the evolution of today's humanoid species. the zmpb  protease may play an important but yet unidentified role in the association of streptococci of the mitis and salivarius groups with their human host, as it is ubiquitous in these two groups, except for a fragmented gene in streptococcus thermophilus, the only species not associated with humans. the relative sequence  diversification of the iga1 protease, zmpb, and zmpd is striking evidence of differences in selection for diversification of these surface-exposed proteins in the pathogen s. pneumoniae compared to the closely related commensal streptococci.
TIHT== 
ABHT== 

PMID== 22921469
TI  == protein domain repetition is enriched in streptococcal cell-surface proteins.
AB  == tandem repetition of domain in protein sequence occurs in all three domains of life. it creates protein diversity and adds functional complexity in organisms. in this work, we analyzed 52 streptococcal genomes and found 3748 proteins contained domain repeats. proteins not harboring domain repeats are significantly enriched in cytoplasm, whereas proteins with domain repeats are significantly enriched in cytoplasmic membrane, cell wall and extracellular locations. domain repetition occurs most frequently in s. pneumoniae and least in s. thermophilus and s. pyogenes. duf1542 is the highest repeated domain in a single protein, followed by rib, cw_binding_1, g5 and hemolysincabind. 3d structures of 24 repeat-containing proteins were predicted to investigate the structural and functional effect of domain repetition. several repeat-containing streptococcal cell surface proteins are known to be virulence-associated. surface-associated tandem domain-containing proteins without experimental functional characterization may be potentially involved in the pathogenesis of streptococci  and deserve further investigation.
TIHT== 
ABHT== 

PMID== 22853653
TI  == stimulation of cadaverine production by foodborne pathogens in the presence of lactobacillus, lactococcus, and streptococcus spp.
AB  == the effect of lactobacillus plantarum (fi8595), lactococcus lactis subsp. cremoris mg 1363), lactococcus lactis subsp. lactis (il 1403), and streptococcus  thermophilus on cadaverine and other biogenic amine production by foodborne pathogens was investigated lysine decarboxylase broth. both of lactic acid bacteria and foodborne pathogens used (especially staphylococcus aureus, e. coli, lc. lactis subsp. lactis and lb. plantarum) had an ability to convert aminoacids  into biogenic amine. the conversion of lysine into cadaverine was the highest (167.11 mg/l) by lactobacillus spp. gram-positive bacteria generally had a greater ability to produce cadaverine with corresponding value of 46.26, 53.76, and 154.54 mg/l for enterococcus faecalis, s. aureus, and listeria monocytogenes, respectively. significant variations on biogenic amine production were observed in the presence of lactic acid bacteria strains (p < 0.05). the role of lactic acid bacteria on biogenic amine production by foodborne pathogens varied depending on strains and specific amine. cadaverine accumulation by enterobactericeae was increased in the presence of lactic acid bacteria strains except for st. thermophilus, which induced 2-fold lower cadaverine production by  s. paratyphi a. lc. lactis subsp. lactis and lc. lactis subsp. cremoris induced 10-fold higher increases in histamine for e. coli and k. pneumoniae, respectively. lactic acid bacteria resulted in strong increases in cadaverine production by p. aeruginosa, although remarkable decreases were observed for histamine, spermidine, dopamine, agmatine, and tma in the presence of lactic acid bacteria in lysine decarboxylase broth . the result of the study showed that amine positive lactic acid bacteria strains in fermented food led to significant  amine accumulation by contaminant bacteria and their accumulation in food product may be controlled by the use of proper starters with amine-negative activity.
TIHT== 
ABHT== 

PMID== 22241050
TI  == deletion of the murein hydrolase cbpd reduces transformation efficiency in streptococcus thermophilus.
AB  == recently it has been shown that streptococcus thermophilus is competent for natural genetic transformation. this property is widespread among streptococci and may include all members of the genus. upon entering the competent state, streptococci start transcribing a number of competence-specific genes whose products are required for binding, uptake and processing of transforming dna. in  addition to the core competence genes, competent streptococci express a number of accessory genes that are dispensable for transformation in the laboratory, but presumably play an important role under natural conditions. in streptococcus pneumoniae, one of these accessory genes encodes a competence-specific murein hydrolase termed cbpd. experimental evidence indicates that pneumococcal cbpd is  part of a predatory mechanism that lyses noncompetent sister cells or members of  closely related species in order to release homologous dna that can be taken up by the competent attacker cells. competent s. thermophilus lmg18311 cells produce a cbpd-like protein, stu0039, which might have the same or a similar function. in the present study we have characterized this protein and shown that it is a murein hydrolase with a novel type of cell surface-binding domain. furthermore, we show that stu0039 is rapidly inactivated by h(2)o(2) produced during aerobic growth of s. thermophilus. we propose that this inactivation mechanism has evolved for self-protection purposes to prevent extensive autolysis in a competent population. interestingly, in contrast to pneumococcal cbpd, which does not affect the transformation properties of the producer strain, deletion of stu0039 reduces the transformability of s. thermophilus.
TIHT== 
ABHT== 

PMID== 21804004
TI  == peptide-regulated gene depletion system developed for use in streptococcus pneumoniae.
AB  == to facilitate the study of pneumococcal genes that are essential for viability or normal cell growth, we sought to develop a tightly regulated, titratable gene depletion system that interferes minimally with normal cellular functions. a possible candidate for such a system is the recently discovered signal transduction pathway regulating competence for natural transformation in streptococcus thermophilus. this pathway, which is unrelated to the comcde pathway used for competence regulation in streptococcus pneumoniae, has not been  fully elucidated, but it is known to include a short unmodified signaling peptide, coms*, an oligopeptide transport system, ami, and a transcriptional activator, comr. the transcriptional activator is thought to bind to an inverted  repeat sequence termed the ecom box. we introduced the comr protein and the ecom  box into the genome of s. pneumoniae r6 and demonstrated that addition of synthetic coms* peptide induced the transcription of a luciferase gene inserted downstream of the ecom box. to determine whether the comrs system could be used for gene depletion studies, the licd1 gene was inserted behind the chromosomally  located ecom box promoter by using the janus cassette. then, the native versions  of licd1 and licd2 were deleted, and the resulting mutant was recovered in the presence of coms*. cultivation of the licd1 licd2 double mutant in the absence of coms* gradually affected its ability to grow and propagate, demonstrating that the comrs system functions as intended. in the present study, the comrs system was developed for use in s. pneumoniae. in principle, however, it should work equally well in many other gram-positive species.
TIHT== 
ABHT== 

PMID== 21702978
TI  == exploring internal features of 16s rrna gene for identification of clinically relevant species of the genus streptococcus.
AB  == background: streptococcus is an economically important genus as a number of species belonging to this genus are human and animal pathogens. the genus has been divided into different groups based on 16s rrna gene sequence similarity. the variability observed among the members of these groups is low and it is difficult to distinguish them. the present study was taken up to explore 16s rrna gene sequence to develop methods that can be used for preliminary identification  and can supplement the existing methods for identification of clinically-relevant isolates of the genus streptococcus. methods: 16s rrna gene sequences belonging to the isolates of s. dysgalactiae, s. equi, s. pyogenes, s. agalactiae, s. bovis, s. gallolyticus, s. mutans, s. sobrinus, s. mitis, s. pneumoniae, s. thermophilus and s. anginosus were analyzed with the purpose to define genetic variability within each species to generate a phylogenetic framework, to identify species-specific signatures and in-silico restriction enzyme analysis. results: the framework based analysis was used to segregate streptococcus spp. previously  identified upto genus level. this segregation was validated using species-specific signatures and in-silico restriction enzyme analysis. 43 uncharacterized streptococcus spp. could be identified using this approach. conclusions: the markers generated exploring 16s rrna gene sequences provided useful tool that can be further used for identification of different species of the genus streptococcus.
TIHT== 
ABHT== 

PMID== 21436217
TI  == clpc acts as a negative regulator of competence in streptococcus thermophilus.
AB  == the alternative sigma factor comx is a key regulator of natural transformation in members of the genus streptococcus. comx controls expression of the late competence genes, which are essential for dna binding, uptake and recombination.  in streptococcus pneumoniae, it has been demonstrated that comx is degraded by clpep at the end of the competence period. in the present study we show that a different clp protease complex, clpcp, contributes to comx degradation in streptococcus thermophilus. mutant strains lacking the clpc chaperone displayed significantly increased transformability compared with the wild-type strain under conditions where comx was expressed at relatively low levels. at higher expression levels, clpcp appears to become saturated and unable to prevent the accumulation of comx. together, our results suggest that the role of clpc is to mediate degradation of comx when the sigma factor is produced in low amounts, i.e. when the environmental stimulus promoting competence development is weak. this would prevent s. thermophilus from developing the competent state at an inappropriate time and/or place.
TIHT== 
ABHT== 

PMID== 21106082
TI  == identification of genes for small non-coding rnas that belong to the regulon of the two-component regulatory system ciarh in streptococcus.
AB  == background: post-transcriptional regulation by small rnas (srnas) in bacteria is  now recognized as a wide-spread regulatory mechanism modulating a variety of physiological responses including virulence. in streptococcus pneumoniae, an important human pathogen, the first srnas to be described were found in the regulon of the ciarh two-component regulatory system. five of these srnas were detected and designated csrnas for cia-dependent small rnas. ciarh pleiotropically affects beta-lactam resistance, autolysis, virulence, and competence development by yet to be defined molecular mechanisms. since ciarh is  highly conserved among streptococci, it is of interest to determine if csrnas are also included in the ciarh regulon in this group of organisms consisting of commensal as well as pathogenic species. knowledge on the participation of csrnas in ciarh-dependent regulatory events will be the key to define the physiological  role of this important control system. results: genes for csrnas were predicted in streptococcal genomes and data base entries other than s. pneumoniae by searching for ciar-activated promoters located in intergenic regions that are followed by a transcriptional terminator. 61 different candidate genes were obtained specifying csrnas ranging in size from 51 to 202 nt. comparing these genes among each other revealed 40 different csrna types. all streptococcal genomes harbored csrna genes, their numbers varying between two and six. to validate these predictions, s. mitis, s. oralis, and s. sanguinis were subjected  to csrna-specific northern blot analysis. in addition, a csrna gene from s. thermophilus plasmid pst0 introduced into s. pneumoniae was also tested. each of  the csrnas was detected on these blots and showed the anticipated sizes. thus, the method applied here is able to predict csrnas with high precision. conclusions: the results of this study strongly suggest that genes for small non-coding rnas, csrnas, are part of the regulon of the two-component regulatory  system ciarh in all streptococci.
TIHT== 
ABHT== 

PMID== 21038480
TI  == increasing competence in the genus streptococcus.
AB  == streptococcus pneumoniae is one of the most important model organisms for studies on natural genetic transformation in bacteria. the prevalence of this gene exchange mechanism in the genus streptococcus has not been subjected to systematic investigations, but it has been known for decades that only a few streptococcal species develop the competent state spontaneously when grown under  laboratory conditions. the recent discovery of a new mechanism regulating natural transformation in streptococcus thermophilus suggested that this property might be more widespread among streptococci than previously thought. this suspicion has been confirmed by mashburn-warren and co-workers, who in the current issue of molecular microbiology report the discovery of a novel competence-inducing pheromone that is conserved in streptococcus mutans and a number of pyogenic streptococci.
TIHT== 
ABHT== 

PMID== 19447907
TI  == the oligopeptide transport system is essential for the development of natural competence in streptococcus thermophilus strain lmd-9.
AB  == in gram-positive bacteria, oligopeptide transport systems, called opp or ami, play a role in nutrition but are also involved in the internalization of signaling peptides that take part in the functioning of quorum-sensing pathways.  our objective was to reveal functions that are controlled by ami via quorum-sensing mechanisms in streptococcus thermophilus, a nonpathogenic bacterium widely used in dairy technology in association with other bacteria. using a label-free proteomic approach combining one-dimensional electrophoresis with liquid chromatography-tandem mass spectrometry analysis, we compared the proteome of the s. thermophilus lmd-9 to that of a mutant deleted for the subunits c, d, and e of the ami operon. both strains were grown in a chemically defined medium (cdm) without peptides. we focused our attention on proteins that  were no more detected in the ami deletion mutant. in addition to the three subunits of the ami transporter, 17 proteins fulfilled this criterion and, among  them, 7 were similar to proteins that have been identified as essential for transformation in s. pneumoniae. these results led us to find a condition of growth, the early exponential state in cdm, that allows natural transformation in s. thermophilus lmd-9 to turn on spontaneously. cells were not competent in m17 rich medium. furthermore, we demonstrated that the ami transporter controls the triggering of the competence state through the control of the transcription of comx, itself controlling the transcription of late competence genes. we also showed that one of the two oligopeptide-binding proteins of strain lmd-9 plays the predominant role in the control of competence.
TIHT== 
ABHT== 

PMID== 19055116
TI  == comparison of clustered, regularly interspaced short palindrome repeats (crisprs) in viridans streptococci (streptococcus gordonii, s. mutans, s. sanguinis, s. thermophilus) and in s. pneumoniae.
AB  == 
TIHT== 
ABHT== 

PMID== 18177738
TI  == crystal structure of the ydjc-family protein tthb029 from thermus thermophilus hb8: structural relationship with peptidoglycan n-acetylglucosamine deacetylase.
AB  == the ydjc-family protein is widely distributed, from human to bacteria, but so far no three-dimensional structure and functional analysis of this family of proteins has been reported. we determined the three-dimensional structure of the ydjc homolog tthb029 at a resolution of 2.9a. the overall structure of the monomer consists of (betaalpha)-barrel fold forming a homodimer. asp21, his60, and his127 residues coordinate to mg(2+) as a possible active site. tthb029 shows structural similarity to the peptidoglycan n-acetylglucosamine deacetylase from streptococcus pneumoniae (sppgda). the active site groove of sppgda includes the  zn(2+) coordinated to asp276, his326, and his330. despite the low sequence identity, metal-binding residues of asp-his-his were conserved among the two enzymes. there were definitive differences, however, in that one of the histidines of the metal-binding site was substituted for the other histidine located on the other loop. moreover, these important metal-binding residues and the residues of the presumed active site are fully conserved in ydjc-family protein.
TIHT== 
ABHT== 

PMID== 18076031
TI  == overexpression, physicochemical characterization, and modeling of a hyperthermophilic pyrococcus furiosus type 2 ipp isomerase.
AB  == in the first step of this study, type 2 isopentenyl diphosphate isomerase (idi2)  from pyrococcus furiosus (pf-idi2), a hyperthermophilic microorganism, was cloned and overexpressed in e. coli. after purification, hyperthermophilic behavior of this protein was approached by means of enzymatic assays and thermal denaturation studies. compared with the mesophilic streptococcus pneumoniae idi2, which unfolds and looses activity above 50 degrees c, pf-idi2 is still folded and active at 80 degrees c. molecular modeling was applied, in a parallel step, to understand the molecular basis of thermal stability. comparison of idi2 from s. pneumoniae, t. thermophilus, and p. furiosus suggested that additional charged residues present in the hyperthermophilic enzyme might contribute to its higher thermal stability. this could increase the number of salt bridges between monomers of idi2 in p. furiosus enzyme and, hence, decrease flexibility of loops  or n-terminal segment, thereby enhancing its thermal stability.
TIHT== 
ABHT== 

PMID== 17275906
TI  == isolation and characterization of a new plasmid pspnp1 from a multidrug-resistant clone of streptococcus pneumoniae.
AB  == a novel streptococcus pneumoniae plasmid (pspnp1; 5413bp) has been isolated from  the multidrug-resistant clone poland(23f)-16, and its complete nucleotide sequence has been determined. sequence analysis predicted seven co-directional open reading frames and comparative analyses revealed that plasmid pspnp1 is different to pdp1, the only previously described pneumococcal plasmid, whereas it is highly similar to pst08, a plasmid from streptococcus thermophilus. a double-stranded origin for replication similar to the replication origin of the pc194/pub110 family was located upstream of the putative rep gene (orf2). it also contained a 144-bp region with over 60% identity to the single-stranded origin type a of the streptococcus agalactiae plasmid pmv158/pls1. detection of single-stranded dna by southern blot analysis indicated that pspnp1 replicates via a rolling circle mechanism. interestingly, the product of orf1 has a putative zonular occludens toxin conserved domain present in toxigenic strains of vibrio cholerae. real-time pcr assays revealed that this orf was expressed. hybridization experiments showed that the pspnp1 replicon was unusual among other examined antibiotic-resistant pneumococcal clones, although the recombinant plasmids based on pspnp1 were able to replicate in bacillus subtilis and lactococcus lactis.
TIHT== 
ABHT== 

PMID== 16966682
TI  == gene gain and gene loss in streptococcus: is it driven by habitat?
AB  == bacterial genomes can evolve either by gene gain, gene loss, mutating existing genes, and/or by duplication of existing genes. recent studies have clearly demonstrated that the acquisition of new genes by lateral gene transfer (lgt) is  a predominant force in bacterial evolution. to better understand the significance of lgt, we employed a comparative genomics approach to model species-specific and intraspecies gene insertions/deletions (ins/del among 12 sequenced streptococcal  genomes using a maximum likelihood method. this study indicates that the rate of  gene ins/del is higher on the external branches and varies dramatically for each  species. we have analyzed here some of the experimentally characterized species-specific genes that have been acquired by lgt and conclude that at least  a portion of these genes have a role in adaptation.
TIHT== 
ABHT== 

PMID== 16932907
TI  == pheromone-induced expression of recombinant proteins in streptococcus thermophilus.
AB  == a locus encoding proteins with high homology to the pneumococcal blpabchr quorum-sensing system was identified in streptococcus thermophilus lmg 18311. the blpabchr system regulates bacteriocin production in streptococcus pneumoniae by monitoring the extracellular concentration of a peptide-pheromone encoded by blpc. the homologous system in s. thermophilus, termed stbabchr, contains a corresponding gene (stbc) encoding a possible peptide-pheromone (stp) that presumably controls bacteriocin production in s. thermophilus. we synthesized this peptide and found that it activates transcription of a gusa reporter gene placed behind the promoter of the bacteriocin-like gene stbd. furthermore, deletion mapping and mutational analysis of the stbd promoter region were used to identify a degenerated direct repeat motif required for stp induced gusa expression. our findings provide strong evidence that stp regulates bacteriocin production in s. thermophilus lmg 18311, and show that the stbabchr quorum-sensing system can be exploited for inducible expression of recombinant proteins in this bacterial species.
TIHT== 
ABHT== 

PMID== 12540416
TI  == ingested probiotics reduce nasal colonization with pathogenic bacteria (staphylococcus aureus, streptococcus pneumoniae, and beta-hemolytic streptococci).
AB  == background: as a bacterial reservoir, the nose may harbor potentially pathogenic  bacteria (ppb: staphylococcus aureus, streptococcus pneumoniae, beta-hemolytic streptococci, and haemophilus influenzae). in patients carrying ppb, antiseptic regimens could be crucial for infection control after major operations on or injuries of the head, nasal sinuses, or lungs. such regimens may also be important for diabetic patients and persons receiving hemodialysis, in intensive  care units, or with impaired immunity due to various other causes. objective: we  tested a possible effect of the ingestion of probiotics on the bacterial flora of the nose. design: in an open, prospective trial, 209 volunteers were randomly assigned to consume either a probiotic, fermented milk drink [65 ml with lactobacillus gg (atcc 53103), bifidobacterium sp b420, lactobacillus acidophilus 145, and streptococcus thermophilus; n = 108] or standard yogurt (180 g; n = 101) daily for 3 wk. nasal microbial flora were analyzed on days 1, 21, and 28. the microbial examination was blinded to the source of the samples. results: we found a significant reduction (19%; p < 0.001) in the occurrence of nasal ppb in the group who consumed the probiotic drink but not in the group who consumed yogurt.  the effect was mainly on gram-positive bacteria, which decreased significantly (p < 0.05). conclusions: the results indicate that regular intake of probiotics can  reduce ppb in the upper respiratory tract. the results also indicate a linkage of the lymphoid tissue between the gut and the upper respiratory tract.
TIHT== 
ABHT== 

PMID== 12086189
TI  == study of the intra- and interlaboratory reproducibility of partial single base c-sequencing of the 16s rrna gene and its applicability for the identification of members of the genus streptococcus.
AB  == the use of single base c-sequencing of the first 500 bases of the 16s rrna-gene (sbcs) combined with capillary electrophoresis was evaluated for the identification of reference strains of 30 different species within the genus streptococcus. for sbcs, only dd-ctp's are used in the sequencing reactions instead of the four dideoxy bases and the primer is fluorescently labeled. the reproducibility, interlaboratory exchangeability and discriminative power of this method were studied by comparing the patterns obtained in three laboratories under highly standardized conditions. the interlaboratory reproducibility proved  to be high, enabling the construction of a common database for the identification of strains belonging to the streptococcal species studied. most of the examined species generated distinguishable profiles. sbcs did not differentiate between the closely related species s. constellatus and s. intermedius. also s. thermophilus and s. vestibularis as well as s. mitis and s. pneumoniae showed highly resembling profiles. the previously reported heterogeneity within the species s. equinus was reflected by sbcs. for all other species, strains belonging to the same species generated indistinguishable patterns. in conclusion, single base c-sequencing of the first 500 bases of the 16s rrna-gene  could be a useful and widely applicable method for the identification of bacteria at the species level, with the added advantage of being more rapid and easier to  automatize than full sequence determination.
TIHT== 
ABHT== 

PMID== 11493012
TI  == solution structure and function of a conserved protein sp14.3 encoded by an essential streptococcus pneumoniae gene.
AB  == streptococcus pneumoniae is a major human pathogen that causes high mortality and morbidity rates and has developed resistance to many antibiotics. the genome of s. pneumoniae has recently been completely sequenced revealing many genes encoding hypothetical proteins of unknown function. we have found that the gene encoding one such conserved protein, sp14.3, is essential for growth of s. pneumonia. since it is essential, sp14.3 represents a potential target for drug discovery. here, we describe the three-dimensional solution structure of sp14.3 as determined by nmr spectroscopy. the structure consists of two domains each with an alpha/beta-fold. the n-terminal domain contains two alpha-helices and a three-stranded beta-sheet, while the c-terminal domain is composed of one alpha-helix and a five-stranded beta-sheet. the n-terminal domain of the protein  contains a highly negatively charged surface and resembles the fold of the n-terminal domain of thermus thermophilus ribosomal protein s3. the c-terminal domain has a protein fold similar to human small nuclear ribonucleoprotein sm d3  and haloarcula marismortui ribosomal protein l21e. the two domains of the protein tumble in solution overall as a whole with an overall molecular rotational correlation time (tau(m)) of 12.9 ns at 25 degrees c. the relative orientation of the two domains is not defined by the nuclear overhauser effect data. indeed, residual dipolar couplings and the structure calculations indicate that the relative orientation of the two domains is not rigidly oriented with respect to one another in solution.
TIHT== 
ABHT== 

PMID== 11283068
TI  == application and evaluation of the interlaboratory reproducibility of trna intergenic length polymorphism analysis (tdna-pcr) for identification of streptococcus species.
AB  == the discriminatory power, speed, and interlaboratory reproducibility of trna intergenic length polymorphism analysis (tdna-pcr) combined with capillary electrophoresis was evaluated for the identification of streptococci. this method was carried out in three different laboratories under highly standardized conditions for 54 strains belonging to 18 different species. it was concluded that interlaboratory reproducibility of tdna fingerprints produced by means of capillary electrophoresis was sufficiently high to permit the exchange between different laboratories and the construction of common libraries which can be consulted for comparison with fingerprints obtained independently in separate laboratories. in a second step, 17 other species were included in the study and examined in one of the participating laboratories. all streptococcus species studied, except s. mitis, s. oralis, s. parasanguinis, s. pneumoniae, s. thermophilus, and s. vestibularis, showed distinguishable tdna fingerprints. a database of well-characterized strains was constructed to enable computer-aided identification of unknown streptococcal isolates.
TIHT== 
ABHT== 

PMID== 11281723
TI  == identification, cloning, and expression of a functional phenylalanyl-trna synthetase (phers) from staphylococcus aureus.
AB  == phenylalanyl-trna synthetase (phers) is unique among aminoacyl trna synthetases in that it is a heterotetrameric enzyme composed of two alpha-subunits and two larger beta-subunits. in prokaryotes, the alpha- and beta-subunits of phers are encoded by the genes phes and phet, respectively. in this report we describe the  isolation of a dna fragment (3.52 kb) containing the phes and phet genes from a staphylococcus aureus (wcuh29) genomic dna library. both genes, found as a part of transcriptional operon, were predicted to encode polypeptides which showed strong primary and structural similarity to prokaryotic phenylalanyl-trna synthetase alpha- and beta- subunits. we describe the high-level overexpression and purification of recombinant s. aureus phers using phes and phet genes as part of an artificial operon in escherichia coli. for comparative analysis we also report a procedure for the purification of native phers from s. aureus (oxford strain) and demonstrate that michaelis-menten parameters for both recombinant and native enzyme, at least for phenylalanine trna aminoacylation are comparable.
TIHT== 
ABHT== 

PMID== 11037234
TI  == dna fingerprinting of thermophilic lactic acid bacteria using repetitive sequence-based polymerase chain reaction.
AB  == dna fingerprints of lactic acid bacteria were generated by polymerase chain reaction using a primer based on the repetitive elements found in the genome of streptococcus pneumoniae (box-pcr). the method made it possible to identify 37 isolates from raw milk. industrial starters and yogurt. differentiation at species, subspecies and strain level was possible for lactobacillus delbrueckii subsp. lactis, lb. delbrueckii subsp bulgaricus and str. thermophilus. box-pcr was also applied to studying the strain composition of a starter culture and the  direct detection of strains in commercial fermented milk.
TIHT== 
ABHT== 

PMID== 10985745
TI  == nucleotide sequence, expression and transcriptional analysis of the bifidobacterium longum mb 219 lacz gene.
AB  == the gene encoding beta-galactosidase was isolated by functional complementation of escherichia coli from bifidobacterium longum mb219, which exhibited the highest activity among ten bifidobacterium strains tested of the species b. longum, b. breve, b. adolescentis, b. indicum, b. animalis and b. cuniculi. the nucleotide sequence of the 5.0-kb fragment conferring the positive beta-galactosidase phenotype to e. coli revealed the presence of a lacz-type gene encoding a 1023-amino-acid protein that was preceded by a ribosome binding site.  a sequence showing 72% identity with the proline trna of bacillus subtilis and a  gene probably encoding the dna-3-methyladenine glycosydase i were located downstream from the lacz gene, after a gap of 30-50 unsequenced base pairs. by primer-extension analysis, the transcription start site of the lacz gene was mapped 65 nt upstream from the start codon, and it enabled identification of the  -10 region of the putative promoter. the nucleotide sequence of lacz and its deduced amino acid sequence were compared with those of beta-galactosidase genes  and enzymes from other microorganisms. high similarity was demonstrated between the b. longum beta-galactosidase and its counterparts in lactobacillus delbruckii subsp. bulgaricus, streptococcus salivarius subsp. thermophilus, e. coli, clostridium acetobutylicum, leuconostoc lactis, klebsiella pneumoniae and kluyveromyces marxianus var. lactis, all belonging to the lacz family. the b. longum mb219 lacz gene was cloned in bifidobacterium and its expression was observed in strains with otherwise low levels of endogenous activity. the expression increased by factors of 1.5-50 and enabled those strains that do not grow on lactose to use this sugar as sole carbon source.
TIHT== 
ABHT== 

PMID== 10515924
TI  == functional analysis of glycosyltransferase genes from lactococcus lactis and other gram-positive cocci: complementation, expression, and diversity.
AB  == sixteen exopolysaccharide (eps)-producing lactococcus lactis strains were analyzed for the chemical compositions of their epss and the locations, sequences, and organization of the eps genes involved in eps biosynthesis. this allowed the grouping of these strains into three major groups, representatives of which were studied in detail. previously, we have characterized the eps gene cluster of strain nizo b40 (group i) and determined the function of three of its  glycosyltransferase (gtf) genes. fragments of the eps gene clusters of strains nizo b35 (group ii) and nizo b891 (group iii) were cloned, and these encoded the  nizo b35 priming galactosyltransferase, the nizo b891 priming glucosyltransferase, and the nizo b891 galactosyltransferase involved in the second step of repeating-unit synthesis. the nizo b40 priming glucosyltransferase gene epsd was replaced with an erythromycin resistance gene, and this resulted in loss of eps production. this epsd deletion was complemented with priming gtf genes from gram-positive organisms with known function and substrate specificity. although no eps production was found with priming galactosyltransferase genes from l. lactis or streptococcus thermophilus, complementation with priming glucosyltransferase genes involved in l. lactis eps and streptococcus pneumoniae  capsule biosynthesis could completely restore or even increase eps production in  l. lactis.
TIHT== 
ABHT== 

PMID== 9987115
TI  == ctsr, a novel regulator of stress and heat shock response, controls clp and molecular chaperone gene expression in gram-positive bacteria.
AB  == clpp and clpc of bacillus subtillis encode subunits of the clp atp-dependent protease and are required for stress survival, including growth at high temperature. they play essential roles in stationary phase adaptive responses such as the competence and sporulation developmental pathways, and belong to the  so-called class iii group of heat shock genes, whose mode of regulation is unknown and whose expression is induced by heat shock or general stress conditions. the product of ctsr, the first gene of the clpc operon, has now been  shown to act as a repressor of both clpp and clpc, as well as clpe, which encodes a novel member of the hsp100 clp atpase family. the ctsr protein was purified and shown to bind specifically to the promoter regions of all three clp genes. random mutagenesis, dnasel footprinting and dna sequence deletions and comparisons were  used to define a consensus ctsr recognition sequence as a directly repeated heptad upstream from the three clp genes. this target sequence was also found upstream from clp and other heat shock genes of several gram-positive bacteria, including listeria monocytogenes, streptococcus salivarius, s. pneumoniae, s. pyogenes, s. thermophilus, enterococcus faecalis, staphylococcus aureus, leuconostoc oenos, lactobacillus sake, lactococcus lactis and clostridium acetobutylicum. ctsr homologues were also identified in several of these bacteria, indicating that heat shock regulation by ctsr is highly conserved in gram-positive bacteria.
TIHT== 
ABHT== 

PMID== 9682492
TI  == small cryptic plasmids of streptococcus pneumoniae belong to the pc194/pub110 family of rolling circle plasmids.
AB  == the dna sequences of two related plasmids ppr1 and ppr3 described previously in streptococcus pneumoniae isolates from germany and spain were now determined. both plasmids belong to a family of rolling circle (rc) plasmids found in a variety of bacteria. their gc content with 32% is lower than that of the s. pneumoniae chromosomal dna. the plasmid ppr3 has a molecular size of 3160 bp with four putative open reading frames, whereas ppr1 contained a deletion of 313 bp that included the 5'-part of orf2 and upstream regions and differed by three bp from ppr3. the predicted protein of orf1 showed high similarity to replication proteins of rc plasmids with 74% identical amino acids to repa of streptococcus thermophilus plasmids. sequences similar to the plus origin of replication of ssdna plasmids were present in both plasmids. they also contained a 152-bp region with over 83% identity to the minus origin of replication of the streptococcus agalacticae plasmid pmv158.
TIHT== 
ABHT== 

PMID== 9499809
TI  == evolution of streptococcus thermophilus bacteriophage genomes by modular exchanges followed by point mutations and small deletions and insertions.
AB  == comparative sequence analysis of 40% of the genomes from two prototype streptococcus thermophilus bacteriophages (lytic group i phage phi sfi19 and the  cos site containing temperate phage phi sfi21) suggested two processes in the evolution of their genomes. in a first evolutionarily distant phase the basic genome structure was apparently constituted by modular exchanges. over the 17-kb-long dna segment analyzed in the present report, we observed clusters of genes with similarity to genes from leuconostoc oenos phage l10, lactococcus lactis phage bk5-t, and streptococcus pneumoniae phage dp-1. a chimeric protein was predicted for orf 1291 which showed similarity to both phage bk5-t and phage  dp-1 proteins. the very large orf 1626 gene product showed similarity to two adjacent genes from the lactobacillus delbrueckii phage ll-h and further phage proteins (lactococcus lactis, bacillus subtills). the similarities were localized to distinct parts of this apparently multifunctional protein. the putative phi sfi19 lysin showed similarity to both lysins of phages and cellular enzymes. in a second, evolutionarily more recent, phase the s, thermophilus phage genomes apparently diversified by point mutations and small deletions/insertions. over the investigated 17-kb dna region phi sfi19 differed from phi sfi21 by 10% base pair changes, the majority of which were point mutations (mainly at the third codon position), while a third of the base pair differences were contributed by small deletions/insertions. the base pair changes were unevenly distributed. over the leuconostoc phage-related dna the change rate was high, while over the lactococcus and s. pneumoniae phage-related dna the change rate was low. we speculate that the degree of base pair change could provide relative time scales  for the modular exchange reactions observed in s. thermophilus phages.
TIHT== 
ABHT== 

PMID== 9431917
TI  == identification of streptococci to species level by sequencing the gene encoding the manganese-dependent superoxide dismutase.
AB  == we have used a pcr assay based on the use of degenerate primers in order to characterize an internal fragment (soda(int)) representing approximately 85% of the genes encoding the manganese-dependent superoxide dismutase in various streptococcal type strains (s. acidominimus, s. agalactiae, s. alactolyticus, s.  anginosus, s. bovis, s. constellatus, s. canis, s. cricetus, s. downei, s. dysgalactiae, s. equi subsp. equi, s. equi subsp. zooepidemicus, s. equinus, s. gordonii, s. iniae, s. intermedius, s. mitis, s. mutans, s. oralis, s. parasanguis, s. pneumoniae, s. porcinus, s. pyogenes, s. salivarius, s. sanguis,  s. sobrinus, s. suis, s. thermophilus, and s. vestibularis). phylogenetic analysis of these soda(int) fragments yields an evolutionary tree having a topology similar to that of the tree constructed with the 16s rrna sequences. we  have shown that clinical isolates could be identified by determining the positions of their soda(int) fragments on the phylogenetic tree of the soda(int)  fragments of the type species. we propose this method for the characterization of strains that cannot be assigned to a species on the basis of their conventional phenotypic reactions.
TIHT== 
ABHT== 

PMID== 8996082
TI  == the cpsabcde genes involved in polysaccharide production in streptococcus salivarius ssp. thermophilus strain ncbf 2393.
AB  == a 4074-bp ecori fragment of streptococcus salivarius ssp. thermophilus (s. thermophilus) chromosomal dna containing genes involved in exocellular polysaccharide (eps) was identified and cloned. the nucleotide sequence of this fragment was determined and found to contain one partial and four complete open reading frames. these were designated cpsa, cpsb, cpsc, cpsd and cpse and encoded proteins of > 130, 243, 230, 246 and 455 amino acids, respectively, that showed homology with the genes of the cps cluster, involved in polysaccharide biosynthesis, in streptococcus pneumoniae type 19f. the cpsa gene is predicted to encode a transcriptional regulator, while cpsc and cpsd are predicted to encode proteins involved in polysaccharide polymerization and export. the cpse gene is likely to encode the phosphate-prenyl glycosyl-1-phosphate transferase catalyzing the first step in polysaccharide biosynthesis in s. thermophilus. southern blot analysis revealed that cpse is found only in polysaccharide producing strains of  s. thermophilus.
TIHT== 
ABHT== 

PMID== 8930919
TI  == disruption of the gene encoding penicillin-binding protein 2b (pbp2b) causes altered cell morphology and cease in exopolysaccharide production in streptococcus thermophilus sfi6.
AB  == genetic and biochemical analysis of exopolysaccharide (eps) production in lactic  acid bacteria has been a growing field of interest in the food industry. we previously identified and characterized a gene cluster composed of 13 genes (epsa to epsm) responsible for eps production in streptococcus thermophilus sfi6. here  we report one further gene, pbp2b, that is connected to eps production. mutants with a gene disruption in pbp2b were no longer able to produce eps, exhibited a reduced growth-rate, and their cell morphology was altered. the predicted gene product showed significant homology to the class b penicillin-binding proteins 2b of streptococcus pneumoniae, streptococcus sanguis and streptococcus mitis involved in peptidoglycan synthesis. upstream of pbp2b, we further identified two genes which showed significant homology to the e. coli fold and urfl, which is an unidentified open reading frame presumed to be involved in dna repair. downstream of pbp2b, we identified a gene that showed homology to the bacillus subtilis and  the escherichia coli recm or recr which, respectively, are involved in the methyl-dependent dna mismatch repair. in s. thermophilus, pbp2b and recm were transcribed from their own promoters as monocistronic mrnas and are therefore organized as independent transcriptional units.
TIHT== 
ABHT== 

PMID== 8830272
TI  == cation and sugar selectivity determinants in a novel family of transport proteins.
AB  == a new family of homologous membrane proteins that transport galactosides-pentoses-hexuronides (gph) is described. by analysing the aligned amino acid sequences of the gph family, and by exploiting their different specificities for cations and sugars, we have designed mutations that yield novel insights into the nature of ligand binding sites in membrane proteins. mutants have been isolated/constructed in the melibiose transport proteins of escherichia coli, klebsiella pneumoniae and salmonella typhimurium, and the lactose transport protein of streptococcus thermophilus which facilitate uncoupled transport or have an altered cation and/or substrate specificity. most of the mutations map in the amino-terminal region, in or near amphipathic alpha-helices ii and iv, or in  interhelix-loop 10-11 of the transport proteins. on the basis of the kinetic properties of these mutants, and the primary and secondary structure analyses presented here, we speculate on the cation binding pocket of this family of transporters. the regulation of the transporters through interaction with, or phosphorylation by, components of the phosphoenolpyruvate:sugar phosphotransferase system is also discussed.
TIHT== 
ABHT== 

PMID== 8626297
TI  == identification and characterization of the eps (exopolysaccharide) gene cluster from streptococcus thermophilus sfi6.
AB  == we report the identification and characterization of the eps gene cluster of streptococcus thermophilus sfi6 required for exopolysaccharide (eps) synthesis. this report is the first genetic work concerning eps production in a food microorganism. the eps secreted by this strain consists of the following tetrasaccharide repeating unit:-->3)-beta-d-galp-(1-->3)-[alpha-d-galp-(1-->6)]-beta-d- d-galp-(1-->3)-alpha-d-galp-d-galpnac-(1-->. the genetic locus the genetic locus  was identified by tn916 mutagenesis in combination with a plate assay to identify eps mutants. sequence analysis of the gene region, which was obtained from subclones of a genomic library of sfi6, revealed a 15.25-kb region encoding 15 open reading frames. eps expression in the non-eps-producing heterologous host, lactococcus lactis mg1363, showed that within the 15.25-kb region, a region with  a size of 14.52 kb encoding the 13 genes epsa to epsm was capable of directing eps synthesis and secretion in this host. homology searches of the predicted proteins in the swiss-prot database revealed high homology (40 to 68% identity) for epsa, b, c, d, and e and the genes involved in capsule synthesis in streptococcus pneumoniae and streptococcus agalactiae. moderate to low homology (37 to 18% identity) was detected for epsb, d, f, and h and the genes involved in capsule synthesis in staphylococcus aureus for epsc, d, and e and the genes involved in exopolysaccharide i (epsi) synthesis in rhizobium meliloti for epsc to epsj and the genes involved in lipopolysaccharide synthesis in members of the  enterobacteriaceae, and finally for eps k and lipb of neisseria meningitidis. genes (epsj, epsl, and epsm) for which the predicted proteins showed little or no homology with proteins in the swiss-prot database were shown to be involved in eps synthesis by single-crossover gene disruption experiments.
TIHT== 
ABHT== 

PMID== 1901904
TI  == analysis of the lacz sequences from two streptococcus thermophilus strains: comparison with the escherichia coli and lactobacillus bulgaricus beta-galactosidase sequences.
AB  == the lacz gene from streptococcus thermophilus a054, a commercial yogurt strain, was cloned on a 7.2 kb psti fragment in escherichia coli and compared with the previously cloned lacz gene from s. thermophilus atcc 19258. using the dideoxy chain termination method, the dna sequences of both lacz structural genes were determined and found to be 3071 bp in length. when the two sequences were more closely analysed, 21 nucleotide differences were detected, of which only nine resulted in amino acid changes in the proteins, the remainder occurring in wobble positions of the respective codons. only three bases separated the termination codon for the lacs gene from the initiation codon for lacz, suggesting that the lactose utilization genes are organized as an operon. the amino acid sequence of  the beta-galactosidase, derived from the dna sequence, corresponds to a protein with a molecular mass of 116860 da. comparison of the s. thermophilus amino acid  sequences with those from lactobacillus bulgaricus, e. coli and klebsiella pneumoniae showed 48, 35 and 32.5% identity respectively. although little sequence homology was observed at the dna level, many regions conserved in the amino acid sequence were identified when the beta-galactosidase proteins from s.  thermophilus, e. coli and l. bulgaricus were compared.
TIHT== 
ABHT== 

PMID== 6409982
TI  == numerical taxonomy of streptococcus.
AB  == a numerical taxonomic study of strains of streptococcus, together with representatives of allied genera, showed 28 reasonably distinct phenons. the major areas, with their phenons, were: (a) enterococcal species group (s. faecalis, s. faecium, 's. avium' and a proposed new species 's. gallinarum'); (b) paraviridans species group (s. bovis, s. equinus, s. salivarius, 's. casseliflavus', s. mutans, s. raffinolactis and an unidentified oral group i); (c) lactic species group (s. lactis including s. cremoris); (d) thermophilic species group (s. thermophilus); (e) viridans species group (s. mitis, s. sanguis, a proposed new species 's. oralis' and 's. milleri'); (f) pyogenic species group (s. agalactiae, s. pyogenes, s. equi, 's. equisimilis' including 's. zooepidemicus, and a cluster of lancefield group b strains of human origin);  (g) parapyogenic species group (s. uberis, 's. dysgalactiae', and a cluster of strains of lancefield groups r, s and t). species of aerococcus, gemella, leuconostoc and pediococcus are very closely related to the streptococci.
TIHT== 
ABHT== 

