@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 21145793
TI  == population structure and characterization of viridans group streptococci (vgs) including streptococcus pneumoniae isolated from adult patients with cystic fibrosis (cf).
AB  == a study was undertaken to examine the population structure of viridans group streptococci (vgs) in the sputum of adult patients with cystic fibrosis (cf). freshly expectorated sputa (n=58) from 45 adult cf patients were examined by selective conventional culture on mitis-salivarius agar and yielded 190 isolates  of vgs. sequence analyses of the rpnb and 16-23s rrna its genes identified these  isolates to belong to 12 species of vgs and included s. anginosus, s. australis,  s. cristatus, s. gordonii, s. infantis, s. mitis, s. mutans, s. oralis, s. parasanguinis, s. pneumoniae, s. salivarius and s. sanguinis. the most frequently vgs organism isolated was s. salivarius (47/190; 24.7%), followed by s. mitis (36/190; 19%), s. sanguinis (25/190; 13.2%), s. oralis (20/190; 11.0%), s. pneumoniae (19/190; 10.0%), s. parasanguinis (16/190; 8.4%), s. infantis (11/190; 5.8%), s. gordonii (7/190; 3.7%), s. anginosus (4/190; 2.1%), s. cristatus (2/190; 1.1%), s. australis (1/190; 0.5%), s. mutans (1/190; 0.5%) and s. agalactiae (1/190; 0.5%). all, but four, patients harboured at least one vgs species, which ranged from one to five streptococcal species, with a mean of 2.85 species per patient. there was no clonality at the subspecies level employing eric rapd pcr. antibiotic susceptibility was determined by minimum inhibitory concentration (mic) testing against penicillin, erythromycin and ciprofloxacin. overall, resistance to penicillin with all vgs was 73/190 (38.4%) and 167/190 (87.9%) for erythromycin. with regard to ciprofloxacin, 27/190 (14.2%) were fully resistant, whilst a further 21/190 (11.1%) showed intermediate resistance, which  equated to approximately three quarters (74.7%) of isolates being fully sensitive to this agent. in addition, as a comparator control population, we examined antibiotic susceptibility, as above, in a non-cf population comprising 12 individuals (50 vgs isolates), who were not receiving chronic antibiotics. in comparison, 8% and 38% of vgs isolates from non-cf individuals were resistant by  disk susceptibility testing to penicillin and erythromycin, respectively. none of the non-cf vgs organisms were resistant to ciprofloxacin, but 42% showed intermediate resistance.
TIHT== 
ABHT== 

PMID== 9838857
TI  == measurement of antibacterial activities of t-2 toxin, deoxynivalenol, ochratoxin  a, aflatoxin b1 and fumonisin b1 using microtitration tray-based turbidimetric techniques.
AB  == various mycotoxins were tested for their antibacterial activity by evaluating growth delays using a fully automated microturbidmetric method. ten different strains of the genera escherichia, streptococcus, staphylococcus, yersinia, salmonella, erysipelothrix and lactobacillus were used as test micro-organisms. t-2 toxin, deoxynivalenol (don), ochratoxin a (ota), aflatoxin b1 (afb1) and fumonisin b1 (fb1) were used as representative mycotoxins. the inhibitory effect  in vitro was defined as the difference between the growth rate without mycotoxins and the growth rate in the presence of a mycotoxin. among the tested strains, streptococcus agalactiae was found to be sensitive to all the toxins, with the exception of ota. t-2 toxin and fb1 were the most effective in slowing down the growth of staphylococcus aureus. afb1 affected the growth of yersinia enterocolitica. the growth rate of escherichia coli and salmonella infantis was decreased by fb1. among the bacterial strains used in this study, only the growth of erysipelothrix rhusiopathiae was inhibited by ota. thus, using appropriate tester strains it should be possible to set up a broad-range microtubidimetry assay for individual mycotoxin screening in vitro. we concluded that the microtitration technique provides a rapid, convenient and high-throughput capacity system to analyse bacteria-mycotoxin interactions.
TIHT== 
ABHT== 

PMID== 9774492
TI  == effects of tamoxifen, melatonin, coenzyme q10, and l-carnitine supplementation on bacterial growth in the presence of mycotoxins.
AB  == the involvement of toxic oxygen intermediates in the bacteriostatic effects of mycotoxins (t-2 toxin, deoxynivalenol, ochratoxin a, aflatoxin b1, and fumonisin  b1) was investigated by producing bacterial growth curves using turbidimetry assays in the presence and absence of oxygen radical-scavenging substances. the strains used in this study included escherichia coli (ft 101), streptococcus agalactiae (ft 311, ft 313, ft 315), staphylococcus aureus (ft 192), yersinia enterocolitica (ft 430), salmonella infantis (ft 431), erysipelothrix rhusiopathiae (ft 432), lactobacillus plantarum (ft234) and lactobacillus casei (ft 232). tamoxifen, melatonin, l-carnitine and coenzyme q10 were used as radical scavengers against oxygen toxicity to the strains studied. tamoxifen was the most effective in inhibiting bacterial growth when used at a high concentration, whereas melatonin and l-carnitine were less effective. a combination of l-carnitine and coenzyme q10 provided better protection against oxygen toxicity caused by the mycotoxins growth than they did individually. it was concluded that oxygen radicals are involved in the killing of bacteria and that there is endogenous formation of toxic oxygen products by mycotoxins. the objective of this study was to determine whether the antioxidants were able to counteract the  toxic effects of the mycotoxins. the data obtained indicate that bacterial growth can be inhibited especially by t-2 toxin, aflatoxin b1 and ochratoxin a and that  this effect can be partially counteracted by antioxidants such as coenzyme q10 plus l-carnitine.
TIHT== 
ABHT== 

PMID== 8989804
TI  == septic sacroiliitis.
AB  == two cases of septic sacroiliac (si) joint arthritis are presented to illustrate the difficulty of diagnosing and treating this uncommon osteoarticular infection. the patients presented are a 68-year-old woman with septic sacroiliitis caused by streptococcus agalactiae and a 20-year-old man with salmonella infantis infection involving the si joint. the recent literature is reviewed and compared with previously published series. of the 177 cases we reviewed, 47 (27%) occurred in pediatric patients. the mean age was 20 years. only six patients (3%) were older  than 60 years of age. magnetic resonance imaging (mri) is most useful for defining extent of infection, osteomyelitis, and abscess formation in the si joint. computed tomography (ct) is valuable for defining the extent of bone involvement and for guidance of percutaneous needle arthrocentesis. other imaging modalities are useful primarily in the initial evaluation of patients with a nonspecific presentation. four to six weeks of intravenous (i.v.) antibiotic therapy is recommended. indications for surgical intervention include abscess formation, osteomyelitis, sequestrum of necrotic bone, and failure to respond to  i.v. antibiotic therapy.
TIHT== 
ABHT== 

