@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 24657864
TI  == salivary microbiota and metabolome associated with celiac disease.
AB  == this study aimed to investigate the salivary microbiota and metabolome of 13 children with celiac disease (cd) under a gluten-free diet (treated celiac disease [t-cd]). the same number of healthy children (hc) was used as controls. the salivary microbiota was analyzed by an integrated approach using culture-dependent and -independent methods. metabolome analysis was carried out by gas chromatography-mass spectrometry-solid-phase microextraction. compared to  hc, the number of some cultivable bacterial groups (e.g., total anaerobes) significantly (p < 0.05) differed in the saliva samples of the t-cd children. as  shown by community-level catabolic profiles, the highest shannon's diversity and  substrate richness were found in hc. pyrosequencing data showed the highest richness estimator and diversity index values for hc. levels of lachnospiraceae,  gemellaceae, and streptococcus sanguinis were highest for the t-cd children. streptococcus thermophilus levels were markedly decreased in t-cd children. the saliva of t-cd children showed the largest amount of bacteroidetes (e.g., porphyromonas sp., porphyromonas endodontalis, and prevotella nanceiensis), together with the smallest amount of actinobacteria. t-cd children were also characterized by decreased levels of some actinomyces species, atopobium species, and corynebacterium durum. rothia mucilaginosa was the only actinobacteria species found at the highest level in t-cd children. as shown by multivariate statistical analyses, the levels of organic volatile compounds markedly differentiated t-cd children. some compounds (e.g., ethyl-acetate, nonanal, and 2-hexanone) were found to be associated with t-cd children. correlations (false discovery rate [fdr], <0.05) were found between the relative abundances of bacteria and some volatile organic compounds (vocs). the findings of this study indicated that cd is associated with oral dysbiosis that could affect the oral metabolome.
TIHT== 
ABHT== 

PMID== 20610294
TI  == surgical endodontic treatment of refractory periapical periodontitis with extraradicular biofilm.
AB  == objective: this study explored the effect of surgical endodontic treatment of refractory periapical periodontitis with extraradicular biofilm. study design: endodontic surgery was conducted on a case of refractory periapical periodontitis with extraradicular biofilm. during the procedure, the samples of periapical tissues were collected for microbiologic analysis. the resected root ends were observed under scanning electron microscope. the patient was recalled every 3 months to evaluate the treatment effect for 1 year. results: the samples yielded  1 type of facultative anaerobic bacteria (streptococcus sanguis) and 2 types of obligate anaerobic bacteria (porphynomonas endodontalis and prevotella oralis). mature bacteria biofilms were formed on the surface of the root apexes. at the 1-year recall visit, the radiograph and the clinic examination showed the refractory periapical periodontitis was cured successfully. conclusions: the periapical bacterial biofilm may contribute to the refractory periapical periodontitis. endodontic surgery is a good option for definitive removal of an established extraradicular infection.
TIHT== 
ABHT== 

PMID== 18793931
TI  == an agar diffusion comparison of the antimicrobial effect of calcium hydroxide at  five different concentrations with three different vehicles.
AB  == the purpose of this study was to determine if varying the percent (by weight) of  aqueous calcium hydroxide or using different vehicles had an effect on its antibacterial efficacy against common endodontic pathogens in a pour plate/traditional streak agar diffusion model. mixtures of calcium hydroxide powder and sterile saline in 40, 50 and 60 percent concentrations and the commercial preparations ultracal xs and vitapex were tested against six known endodontic pathogens with an agar diffusion method. each medicament was placed in one of five wells, in each of 10 agar plates (n = 10), for cultures of each bacterial species. zones of inhibition were measured after 48 hours incubation for aerobes and 96 hours incubation for anaerobes. multiple one-way analyses of variance and post-hoc student neuman keuls evaluated the data at alpha = 0.05. larger zones of inhibition were consistently observed for higher concentrations of calcium hydroxide with statistical significance among the bacteria, particularly between 40% and 60%. vitapex had significantly smaller zones of inhibition than all other medicaments and 35% ultracal xs with methylcellulose was nearly as effective as 50% ca(oh)(2) in inhibitory activity. formulations containing 50-60% ca(oh)(2) or 35% ca(oh)(2) with aqueous methylcellulose are recommended as endodontic interappointment medicaments.
TIHT== 
ABHT== 

PMID== 18278298
TI  == comparative study of the antimicrobial efficacy of chlorhexidine gel, chlorhexidine solution and sodium hypochlorite as endodontic irrigants.
AB  == the purpose of this study was to assess the in vitro the antimicrobial efficacy of chlorhexidine gluconate gel as an endodontic auxiliary chemical substance compared to sodium hypochlorite (naocl) and chlorhexidine gluconate solution. the antimicrobial efficacy of the tested substances was evaluated using the agar diffusion test. the growth inhibition zones produced by 0.2%, 1% and 2% chlorhexidine gel were evaluated against 5 facultative anaerobic bacteria and 4 pigmented gram-negative anaerobes, and compared to the results obtained by naocl  and chlorhexidine solution. the largest growth inhibition zones were produced when the test bacteria were in contact with 2% chlorhexidine gluconate gel (11.79 mm), being significantly different (p<0.05) from the growth inhibition zones produced by all naocl concentrations, including 5.25% (9.54 mm). however, there was no statistically significant difference (p>0.05) between the growth inhibition zones obtained with equal concentrations of chlorhexidine solution and gel. the results of this study indicate that, as far as its antimicrobial properties are concerned, chlorhexidine gel has a great potential to be used as an endodontic auxiliary chemical substance.
TIHT== 
ABHT== 

PMID== 16683687
TI  == in vitro antibacterial efficacy of a new chlorhexidine slow-release device.
AB  == objective: the aim of this study was to evaluate and compare the antibacterial effect of chlorhexidine and calcium hydroxide slow-release devices on oral bacteria. method and materials: the agar diffusion test was used to evaluate the  antibacterial effect of the slow-release devices activ point (chlorhexidine; roeko) and calcium hydroxide plus point (roeko) on 8 anaerobic and 2 facultative  oral bacterial strains, as well as 2 bacterial cultures randomly sampled from necrotic root canals and incubated in anaerobic and aerobic broth for 48 hours. the efficiency of the medicaments against the various strains was evaluated using a nonparametric test (friedman type) and a second nonparametric test (wilcoxon's  signed rank test). results: activ point produced significantly larger inhibition  zones (p < .001) than the calcium hydroxide slow-release device around all tested bacterial strains. conclusion: the chlorhexidine slow-release device (activ point) exhibited significant antibacterial activity in the agar diffusion test and merits study as an intracanal medicament.
TIHT== 
ABHT== 

PMID== 11800436
TI  == antimicrobial activity of four root canal sealers against endodontic pathogens.
AB  == the antibacterial effects of various types of widely used endodontic sealers have not been compared systematically on facultative or obligate anaerobic endodontic  pathogens. the aim of this study was to evaluate the antimicrobial properties of  four commonly used endodontic sealers: two epoxy-resin-based sealers (ah26, ah plus), one zinc-oxide eugenol-based sealer (n2), and one calcium hydroxide-based  sealer (sealapex). the testing microbes were four facultative anaerobic species (streptococcus mutans, streptococcus sanguis, escherichia coli, and staphylococcus aureus) and four obligate anaerobic species (porphyromonas gingivalis, porphyromonas endodontalis, fusobacterium nucleatum, and prevotella intermedia). the freshly mixed sealers were placed into the prepared wells of agar plates inoculated with the test microorganisms. after varying periods of incubation (2 days for facultative anaerobic species and 7 days for obligate anaerobic species), the zones of growth inhibition were observed and measured. all the sealers were distinctly different from each other in their antimicrobial  activity. the sealers showed different inhibitory effects depending on the types  and bacterial strains. n2 containing formaldehyde and eugenol proved to be the most effective against the microorganisms. the extreme antimicrobial potency of this root canal sealer must be weighted against its pronounced tissue toxic effect.
TIHT== 
ABHT== 

PMID== 10716618
TI  == in vitro antimicrobial activity of propolis and arnica montana against oral pathogens.
AB  == arnica and propolis have been used for thousands of years in folk medicine for several purposes. they possess several biological activities such as anti-inflammatory, antifungal, antiviral and tissue regenerative, among others. although the antibacterial activity of propolis has already been demonstrated, very few studies have been done on bacteria of clinical relevance in dentistry. also, the antimicrobial activity of arnica has not been extensively investigated. therefore the aim here was to evaluate in vitro the antimicrobial activity, inhibition of adherence of mutans streptococci and inhibition of formation of water-insoluble glucan by arnica and propolis extracts. arnica montana (10%, w/v) and propolis (10%, w/v) extracts from minas gerais state were compared with controls. fifteen microorganisms were used as follows: candida albicans--ntcc 3736, f72; staphylococcus aureus--atcc 25923; enterococcus faecalis--atcc 29212;  streptococcus sobrinus 6715; strep. sanguis--atcc 10556; strep. cricetus--hs-6; strep. mutans--ingbritt 1600; strep. mutans--omz 175; actinomyces naeslundii--atcc 12104, w 1053; act. viscosus omz 105; porphyromonas gingivalis;  porph. endodontalis and prevotella denticola (the last three were clinical isolates). antimicrobial activity was determined by the agar diffusion method and the zones of growth inhibition were measured. to assess cell adherence to a glass surface, the organisms were grown for 18 h at 37 degrees c in test-tubes at a 30  degree angle. to assay water-insoluble glucan formation, a mixture of crude glucosyltransferase and 0.125 m sucrose was incubated for 18 h at 37 degrees c in test-tubes at a 30 degree angle. arnica and propolis extracts (20 microl) were added to these tubes to evaluate the % of inhibition of cell adherence and water-insoluble glucan formation. the propolis extract significantly inhibited all the microorganisms tested (p < 0.05), showing the largest inhibitory zone for actinomyces spp. the arnica extract did not demonstrate significant antimicrobial activity. cell adherence and water-insoluble glucan formation were almost completely inhibited by the propolis extract at a final concentration of 400 microg/ml and 500 microg/ml, respectively. the arnica extract showed slight inhibition of the adherence of the growing cells (19% for strep. mutans and 15% for strep. sobrinus) and of water-insoluble glucan formation (29%) at these same  concentrations. thus, the propolis extract showed in vitro antibacterial activity, inhibition of cell adherence and inhibition of water-insoluble glucan formation, while the arnica extract was only slightly active in those three conditions.
TIHT== 
ABHT== 

PMID== 8626206
TI  == studies into the microbial spectrum of apical periodontitis.
AB  == this study examined the variety of obligate and facultative anaerobic bacterial species recovered from cases of acute apical periodontitis. a total of 19 root canal samples and 24 periapical granuloma samples were taken from patients suffering pain and discomfort. bacteria were identified by applying the following techniques: culturing on various media, gram-staining and using commercially available biochemical test strips. in addition, prevotella intermedia and porphyromonas endodontalis were differentiated on a molecular genetic level using species-specific oligodeoxynucleotide probes. the most frequently identified bacteria were prevotella intermedia, bifidobacterium spp., streptococcus sanguis, streptococcus milleri-group and bacteroides spp. obligate anaerobes occurred at a rate of 82.3%, and the average number of isolates was 6.4 per sample.
TIHT== 
ABHT== 

