@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25781608
TI  == phytase modulates ileal microbiota and enhances growth performance of the broiler chickens.
AB  == phytase is well studied and explored, however, little is known about its effects  on the microbial ecology of the gastrointestinal tract. in total, 400 one-day-old female ross 308 chicks were randomly distributed to four experimental groups. the dietary treatments were arranged as a 2 x 2 complete factorial design, with the factors being adequate (pc) or insufficient calcium (ca) and digestible phosphor  (dp)(nc) and with or without 5000 phytase units (ftu)/kg of escherichia coli 6-phytase. the gastrointestinal tract ph values, ileal microbial communities and  short-chain fatty acid concentrations in the digesta were determined. the reduction in ca and dp concentration significantly affected ph in the crop and caeca, and addition of phytase to the nc resulted in a ph increase in the ileum.  the reduction in ca and dp concentration significantly lowered, while phytase supplementation increased ileal total bacterial counts. additionally, the deficient diet reduced butyrate- but increased lactate-producing bacteria. the addition of phytase increased lactobacillus sp./enterococcus sp. whereas in case  of clostridium leptum subgroup, clostridium coccoides-eubacterium rectale cluster, bifidobacterium sp. and streptococcus/lactococcus counts, a significant  ca and dp level x phytase interaction was found. however, the recorded interactions indicated that the effects of phytase and ca and dp levels were not  consistent. furthermore, the reduction of ca and dp level lowered clostridium perfringens and enterobacteriaceae counts. the analysis of fermentation products  showed that reducing the ca and dp content in the diet reduced total scfa, dl-lactate, and acetic acid in the ileum whereas phytase increased concentrations of these acids in the nc group. this suggests that p is a factor which limits fermentation in the ileum. it may be concluded that phytase plays a role in modulating the gut microbiota of chicken, however, this is clearly linked with the levels of p and ca in a diet.
TIHT== 
ABHT== 

PMID== 24267574
TI  == time-dependent post mortem changes in the composition of intestinal bacteria using real-time quantitative pcr.
AB  == post mortem or even normal changes during life occurring in major gut bacterial populations are not known. we investigated bacteroides sp., bifidobacterium sp.,  clostridium leptum, clostridium coccoides, streptococcus sp., lactobacillus sp. and enterobacteriacaea ratios in 7 fecal samples from healthy volunteers and in 61 autopsies rectum and cecum samples and studied the effect of post mortem time  using quantitative real-time pcr. bacterial ratios in stool samples from volunteers and rectum samples from autopsy cases were similar and did not change  significantly up to 5 days post mortem. in cecum, significant post mortem time-dependent differences were observed in ratios of bacteroides sp. (p = 0.014) and lactobacillus sp. (p = 0.024). our results showed that ratios of bacteroides  sp., bifidobacterium sp., clostridium leptum, clostridium coccoides, streptococcus sp., lactobacillus sp. and enterobacteriacaea can be investigated in autopsy rectum samples up to 5 days after death.
TIHT== 
ABHT== 

PMID== 22528304
TI  == intestinal bacterial population of healthy rats during the administration of chitosan and chitooligosaccharides.
AB  == the effect of the administration of chitosan (cs) and chitooligosaccharides (cos) on rat fecal microbiota was analyzed in this study. the profile of total bacterial population was monitored during 3 weeks of cs or cos application using  denaturing gradient gel electrophoresis (dgge) analysis of 16s rrna gene amplicons. quantitative pcr was used for monitoring possible changes in the levels of total bacteria and the levels of individual bacterial groups: bifidobacteria, clostridium leptum, enterobacteriaceae, lactobacillus-streptococcus-enterobacter, and bacteroides-prevotella. the dgge profiles revealed a high complexity and individuality of each tested subject, and variations in the composition of band pattern were observed. cs or cos per os administration changed the profile and structure of the microbial ecosystem of the gastrointestinal tract of healthy rats. cos have, in most cases, an opposite  effect compared with cs; only the bacteroides-prevotella bacterial group and enterobacteriaceae were influenced in the same way. the bifidobacteria group was  not influenced by the administration cs and cos.
TIHT== 
ABHT== 

PMID== 12943294
TI  == composition of microbiota in content and mucus from cecae of broiler chickens as  measured by fluorescent in situ hybridization with group-specific, 16s rrna-targeted oligonucleotide probes.
AB  == six group-specific 16s rrna-targeted oligonucleotide probes were used to investigate the composition of the microbiota of cecal content and mucus from broiler chickens. together, the probes hybridized to as many as 94.7% of the bacteria detectable with the universal probe bact338 in the content of the cecum  of 2-d-old chicks. fewer bacteria gave signals with these probes as the birds aged, and coverage was as low as 76% for the bacteria in cecal content of a 6-wk-old chicken. in the cecal content of 2-d-old chicks, approximately 56, 34, and 3% of the bacteria detectable with the universal probe reacted with the probes enter1432 (enterics), lacto722 (lactobacillus/streptococcus/enterococcus), and bif164 (bifidobacteria), respectively. probes clept1240 (clostridium leptum subgroup), erec482 (clostridium coccoides-eubacterium rectale), and bacto1080 (bacteroides groups) did not produce signals. in cecal content from 1-wk-old chicks, all six probes gave signals, and in samples from 6-wk-old birds approximately 3, 9, 6, 32, 22, and 8% of the bacteria detectable with the universal probe hybridized with the probes enter1432, lacto722, bif164, clept1240, erec482, and bacto1080, respectively. at this age, the six probes detected the phylogenetic groups in similar proportions in the microbiota of cecal content and cecal mucus. the exception was the enterics probe because more  bacteria from the mucus fraction than from cecal content gave signals with this probe (13.4 vs. 4.4%, p<0.001).
TIHT== 
ABHT== 

