@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25933689
TI  == aciduric microbial taxa including scardovia wiggsiae and bifidobacterium spp. in  caries and caries free subjects.
AB  == actinobacteria came into focus of being potential caries-associated pathogens and could, together with the established streptococcus mutans and lactobacilli thus function as caries indicator species. here we analyzed the role and diagnostic predictive value of the acidogenic-aciduric species scardovia wiggsiae and bifidobacterium dentium together with s. mutans, lactobacilli and bifidobacteria  in biofilm of non-cavitated (n=20) and cavitated (n=6) caries lesions versus controls (n=30). for the genus bifidobacterium and for b. dentium new sets of primers were designed. based on real-time quantitative pcr and confirmed by dna sequencing we found a higher prevalence (61.5%) of s. wiggsiae in caries lesions  than in controls (40%). however, among the controls we found three individuals with both the highest absolute and relative s. wiggsiae numbers. testing for s. mutans revealed the same prevalence as s. wiggsiae in caries lesions (61.5%) but  in controls its prevalence was only 10%. b. dentium was never found in healthy plaque but in 30.8% of clinical cases, with the highest numbers in cavitated lesions. the bifidobacterium-genus specific pcr had less discriminative power as  more control samples were positive. we calculated the relative abundances and applied receiver operating characteristic analyses. the top results of specificity (93% and 87%) and sensitivity (100% and 88%) were found when the constraint set was "lactobacillus relative abundance >/=0.02%" and "two aciduric  species with a relative abundance of each >/= 0.007%". combinatory measurement of several aciduric taxa may be useful to reveal caries activity or even to predict  caries progression.
TIHT== 
ABHT== 

PMID== 23814571
TI  == lab-test((r)) 4: dental caries and bacteriological analysis.
AB  == dental caries is one of the most common infectious ultifactorial diseases worldwide, characterized by the progressive demineralization of the tooth, following the action of bacterial acid metabolism. the main factors predisposing  the onset of the carious process are: 1) the presence of bacterial species able to lower the ph until critical values of 5.5, 2) the absence of adequate oral hygiene, 3) an inefficient immune response anti-caries, 4) the type of alimentary diet and 5) the structure of the teeth. among the 200 bacterial species isolated  from dental plaque the most pathogenic for dental caries are: streptococcus mutans, streptococcus sobrinus, lactobacillus acidophilus, actinomices viscusus and bifidobacterium dentium. our laboratory (lab((r)) s.r.l., codigoro, ferrara,  italy) has developed a test for absolute and relative quantification of the most  common oral cariogenic bacteria. the test uses specific primers and probes for the amplification of bacteria genome sequences in polymerase chain reaction real  time. the results provide a profile of patient infection, helpful for improving the diagnosis and planning of preventive treatment to reduce the bacterial load.
TIHT== 
ABHT== 

PMID== 23659237
TI  == effect of metalloporphyrins on red autofluorescence from oral bacteria.
AB  == the aim of this study was to assess the red autofluorescence from bacterial species related to dental caries and periodontitis in the presence of different nutrients in the growth medium. bacteria were grown anaerobically on tryptic soy  agar (tsa) supplemented with nutrients, including magnesium-porphyrins from spinach and iron-porphyrins from heme. the autofluorescence was then assessed at  405 nm excitation. on the tsa without additives, no autofluorescence was observed from any of the species tested. on the tsa containing sheep blood, red autofluorescence was observed only from parvimonas micra. when the tsa was supplemented with blood, hemin, and vitamin k, red autofluorescence was observed  from actinomyces naeslundii, bifidobacterium dentium, and streptococcus mutans. finally, on the tsa supplemented with spinach extract, red autofluorescence was observed from aggregatibacter actinomycetemcomitans, a. naeslundii, enterococcus  faecalis, fusobacterium nucleatum, lactobacillus salivarius, s. mutans, and veillonella parvula. we conclude that the bacteria related to dental caries and periodontal disease exhibit red autofluorescence. the autofluorescence characteristics of the tested strains depended on the nutrients present, such as  metalloporphyrins, suggesting that the metabolic products of the oral biofilm could be responsible for red autofluorescence.
TIHT== 
ABHT== 

PMID== 20814202
TI  == resistance to acidic environments of caries-associated bacteria: bifidobacterium  dentium and bifidobacterium longum.
AB  == oral bifidobacteriaceae, bifidobacterium dentium and bifidobacterium longum, are  known to be isolated together with mutans streptococci and lactobacilli from caries lesions, suggesting that these bifidobacteriaceae are caries associated and acid resistant. this study aimed to investigate effects of acidification on b. dentium and b. longum, and to compare them with those on streptococcus mutans, streptococcus sanguinis and lactobacillus paracasei. effects of acidification, growth ability in a complex medium at a ph of 4.0-8.0, cell viability in 2-morpholinoethanesulfonic acid monohydrate (mes)-koh buffer at ph 4.0, as well as stability of intracellular ph (ph(in)) at an extracellular ph of 3.5-8.0 estimated using a fluorescent dye, 5(6)-carboxyfluorescein diacetate n-succinimidyl ester in mes-koh, 3-(n-morpholino)propanesulfonic acid-koh or n,n-bis(2-hydroxyethyl)glycine-koh buffer, were investigated. b. longum grew as well as streptococcus strains over a wide ph range, whereas b. dentium grew best  in the narrow ph range around neutral. the cell viability of b. dentium decreased significantly after 2 h of acidification at a ph of 4.0, but this was significantly less than that of the streptococcus and lactobacillus species, whereas b. longum maintained almost 100% viability. the ph(in) was close to the extracellular ph at ph of 5.5-7.5 in the bifidobacterium and streptococcus strains, while at a ph of <5.0, the ph(in) was higher than the extracellular ph in all the strains, but the ph(in) maintenance ability of bifidobacterium strains was higher than that of the streptococcus strains. the high survival rate and ph(in) maintenance ability of bifidobacteria comparable to that of s. mutans in the acidic environment may account for why bifidobacteria exist as stable species in acidic caries lesions together with mutans streptococci.
TIHT== 
ABHT== 

PMID== 18216213
TI  == bacteria of dental caries in primary and permanent teeth in children and young adults.
AB  == although streptococcus mutans has been implicated as a major etiological agent of dental caries, our cross-sectional preliminary study indicated that 10% of subjects with rampant caries in permanent teeth do not have detectable levels of  s. mutans. our aims were to use molecular methods to detect all bacterial species associated with caries in primary and permanent teeth and to determine the bacterial profiles associated with different disease states. plaque was collected from 39 healthy controls and from intact enamel and white-spot lesions, dentin lesions, and deep-dentin lesions in each of 51 subjects with severe caries. 16s rrna genes were pcr amplified, cloned, and sequenced to determine species identities. in a reverse-capture checkerboard assay, 243 samples were analyzed for 110 prevalent bacterial species. a sequencing analysis of 1,285 16s rrna clones detected 197 bacterial species/phylotypes, of which 50% were not cultivable. twenty-two new phylotypes were identified. proc mixed tests revealed  health- and disease-associated species. in subjects with s. mutans, additional species, e.g., species of the genera atopobium, propionibacterium, and lactobacillus, were present at significantly higher levels than those of s. mutans. lactobacillus spp., bifidobacterium dentium, and low-ph non-s. mutans streptococci were predominant in subjects with no detectable s. mutans. actinomyces spp. and non-s. mutans streptococci were predominant in white-spot lesions, while known acid producers were found at their highest levels later in disease. bacterial profiles change with disease states and differ between primary and secondary dentitions. bacterial species other than s. mutans, e.g., species of the genera veillonella, lactobacillus, bifidobacterium, and propionibacterium, low-ph non-s. mutans streptococci, actinomyces spp., and atopobium spp., likely play important roles in caries progression.
TIHT== 
ABHT== 

