@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 26060535
TI  == comparison of the gut microbiota profile in breast-fed and formula-fed korean infants using pyrosequencing.
AB  == background/objectives: feeding in infancy is the most significant determinant of  the intestinal microbiota in early life. the aim of this study was to determine the gut microbiota of korean infants and compare the microbiota obtained between  breast-fed and formula-fed korean infants. subjects/methods: we analyzed the microbial communities in fecal samples collected from twenty 4-week old korean (ten samples in each breast-fed or formula-fed) infants using pyrosequencing. results: the fecal microbiota of the 4-week-old korean infants consisted of the three phyla actinobacteria, firmicutes, and proteobacteria. in addition, five species, including bifidocbacterium longum, streptococcus salivarius, strepotococcus lactarius, streptococcus pseudopneumoniae, and lactobacillus gasseri were common commensal intestinal microbiota in all infants. the predominant intestinal microbiota in the breast-fed infants (bfi) included the phylum actinobacteria (average 70.55%), family bifidobacteriacea (70.12%), genus  bifidobacterium (70.03%) and species bifidobacterium longum (69.96%). in the microbiota from the formula-fed infants (ffi), the proportion of the phylum actinobacteria (40.68%) was less, whereas the proportions of firmicutes (45.38%)  and proteobacteria (13.85%) as well as the diversity of each taxonomic level were greater, compared to those of the bfi. the probiotic species found in the 4-week-old korean infants were bifidobacterium longum, streptococcus salivarius,  and lactobacillus gasseri. these probiotic species accounted for 93.81% of the microbiota from the bfi, while only 63.80% of the microbiota from the ffi. in particular, b. longum was more abundant in bfi (69.96%) than in ffi (34.17%). conclusions: breast milk supports the growth of b. longum and inhibits others. to the best of our knowledge, this study was the first attempt to analyze the gut microbiota of healthy korean infants according to the feeding type using pyrosequencing. our data can be used as a basis for further studies to investigate the development of intestinal microbiota with aging and disease status.
TIHT== 
ABHT== 

PMID== 23033471
TI  == occurrence and evolution of the paralogous zinc metalloproteases iga1 protease, zmpb, zmpc, and zmpd in streptococcus pneumoniae and related commensal species.
AB  == the distribution, genome location, and evolution of the four paralogous zinc metalloproteases, iga1 protease, zmpb, zmpc, and zmpd, in streptococcus pneumoniae and related commensal species were studied by in silico analysis of whole genomes and by activity screening of 154 representatives of 20 species. zmpb was ubiquitous in the mitis and salivarius groups of the genus streptococcus and in the genera gemella and granulicatella, with the exception of a fragmented  gene in streptococcus thermophilus, the only species with a nonhuman habitat. iga1 protease activity was observed in all members of s. pneumoniae, s. pseudopneumoniae, s. oralis, s. sanguinis, and gemella haemolysans, was variably  present in s. mitis and s. infantis, and absent in s. gordonii, s. parasanguinis, s. cristatus, s. oligofermentans, s. australis, s. peroris, and s. suis. phylogenetic analysis of 297 zmp sequences and representative housekeeping genes  provided evidence for an unprecedented selection for genetic diversification of the iga, zmpb, and zmpd genes in s. pneumoniae and evidence of very frequent intraspecies transfer of entire genes and combination of genes. presumably due to their adaptation to a commensal lifestyle, largely unaffected by adaptive mucosal immune factors, the corresponding genes in commensal streptococci have remained conserved. the widespread distribution and significant sequence diversity indicate an ancient origin of the zinc metalloproteases predating the emergence of the humanoid species. zmpb, which appears to be the ancestral gene, subsequently duplicated and successfully diversified into distinct functions, is  likely to serve an important but yet unknown housekeeping function associated with the human host. importance: the paralogous zinc metalloproteases iga1 protease, zmpb, zmpc, and zmpd have been identified as crucial for virulence of the human pathogen streptococcus pneumoniae. this study maps the presence of the  corresponding genes and enzyme activities in s. pneumoniae and in related commensal species of the genera streptococcus, gemella, and granulicatella. the distribution, genome location, and sequence diversification indicate that zmpb is the ancestral gene predating the evolution of today's humanoid species. the zmpb  protease may play an important but yet unidentified role in the association of streptococci of the mitis and salivarius groups with their human host, as it is ubiquitous in these two groups, except for a fragmented gene in streptococcus thermophilus, the only species not associated with humans. the relative sequence  diversification of the iga1 protease, zmpb, and zmpd is striking evidence of differences in selection for diversification of these surface-exposed proteins in the pathogen s. pneumoniae compared to the closely related commensal streptococci.
TIHT== 
ABHT== 

PMID== 19880633
TI  == partial recn gene sequencing: a new tool for identification and phylogeny within  the genus streptococcus.
AB  == partial sequences of the recn gene (1249 bp), which encodes a recombination and repair protein, were analysed to determine the phylogenetic relationship and identification of streptococci. the partial sequences presented interspecies nucleotide similarity of 56.4-98.2 % and intersubspecies similarity of 89.8-98 %. the mean dna sequence similarity of recn gene sequences (66.6 %) was found to be  lower than those of the 16s rrna gene (94.1 %), rpob (84.6 %), soda (74.8 %), groel (78.1 %) and gyrb (73.2 %). phylogenetically derived trees revealed six statistically supported groups: streptococcus salivarius, s. equinus, s. hyovaginalis/s. pluranimalium/s. thoraltensis, s. pyogenes, s. mutans and s. suis. the 'mitis' group was not supported by a significant bootstrap value, but three statistically supported subgroups were noted: streptococcus sanguinis/s. cristatus/s. sinensis, s. anginosus/s. intermedius/s. constellatus (the 'anginosus' subgroup) and s. mitis/s. infantis/s. peroris/s. oralis/s. oligofermentans/s. pneumoniae/s. pseudopneumoniae. the partial recn gene sequence comparison highlighted a high percentage of divergence between streptococcus dysgalactiae subsp. dysgalactiae and s. dysgalactiae subsp. equisimilis. this observation is confirmed by other gene sequence comparisons (groel, gyrb, rpob and soda). a high percentage of similarity was found between s. intermedius and s. constellatus after sequence comparison of the recn gene. to study the genetic  diversity among the 'anginosus' subgroup, recn, groel, soda, gyrb and rpob sequences were determined for 36 clinical isolates. the results that were obtained confirmed the high genetic diversity within this group of streptococci.
TIHT== 
ABHT== 

