@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 22955450
TI  == oral microbial profile discriminates breast-fed from formula-fed infants.
AB  == objectives: little is known about the effect of diet on the oral microbiota of infants, although diet is known to affect the gut microbiota. the aims of the present study were to compare the oral microbiota in breast-fed and formula-fed infants, and investigate growth inhibition of streptococci by infant-isolated lactobacilli. methods: a total of 207 mothers consented to participation of their 3-month-old infants. a total of 146 (70.5%) infants were exclusively and 38 (18.4%) partially breast-fed, and 23 (11.1%) were exclusively formula-fed. saliva from all of their infants was cultured for lactobacillus species, with isolate identifications from 21 infants. lactobacillus isolates were tested for their ability to suppress streptococcus mutans and s sanguinis. oral swabs from 73 infants were analysed by the human oral microbe identification microarray (homim) and by quantitative polymerase chain reaction for lactobacillus gasseri. results: lactobacilli were cultured from 27.8% of exclusively and partially breast-fed infants, but not from formula-fed infants. the prevalence of 14 homim-detected taxa, and total salivary lactobacilli counts differed by feeding method. multivariate modelling of homim-detected bacteria and possible confounders clustered samples from breast-fed infants separately from formula-fed infants. the microbiota of breast-fed infants differed based on vaginal or c-section delivery. isolates of l plantarum, l gasseri, and l vaginalis inhibited growth of the cariogenic s mutans and the commensal s sanguinis: l plantarum >l gasseri >l  vaginalis. conclusions: the microbiota of the mouth differs between 3-month-old breast-fed and formula-fed infants. possible mechanisms for microbial differences observed include species suppression by lactobacilli indigenous to breast milk.
TIHT== 
ABHT== 

PMID== 21801186
TI  == inhibitory effect of oral lactobacillus against oral pathogens.
AB  == aims: to determine the inhibitory effect of oral lactobacillus against putative oral pathogens. methods and results: total 357 strains comprising 10 species of oral lactobacillus, lactobacillus fermentum (195), lactobacillus salivarius (53), lactobacillus casei (20), lactobacillus gasseri (18), lactobacillus rhamnosus (14), lactobacillus paracasei (12), lactobacillus mucosae (12), lactobacillus oris (12), lactobacillus plantarum (11) and lactobacillus vaginalis (10) were used as producer strains. inhibitory effect against a panel of indicators, periodontitis- and caries-related pathogens, was assessed. most oral lactobacillus was able to inhibit the growth of both periodontitis- and caries-related pathogens. the strongest inhibitory activity was associated with lact. paracasei, lact. plantarum, lact. rhamnosus, lact. casei and lact. salivarius. lactobacillus sd1-sd6, representing the six species with the strong inhibitory effect, inhibited growth of streptococcus mutans atcc 25175 in the biofilm model. also, it was demonstrated that growth of strep. mutans was inhibited in a mixture with lact. paracasei sd1. the inhibition was enhanced in acidic condition and 5% glucose. conclusions: the results have shown that oral lactobacillus sd1-sd6 showed a strong inhibitory effect against strep. mutans and streptococcus sobrinus, as well as, gram-negative periodontal pathogens porphyromonas gingivalis and aggregatibacter actinomycetemcomitans. significance  and impact of the study: the results indicated that lactobacillus may be of benefit as probiotics for the prevention of oral diseases.
TIHT== 
ABHT== 

PMID== 20164496
TI  == microbial risk markers for childhood caries in pediatricians' offices.
AB  == dental caries in pre-school children has significant public health and health disparity implications. to determine microbial risk markers for this infection, this study aimed to compare the microbiota of children with early childhood caries with that of caries-free children. plaque samples from incisors, molars, and the tongue from 195 children attending pediatricians' offices were assayed by 74 dna probes and by pcr to streptococcus mutans. caries-associated factors included visible plaque, child age, race, and snacking habits. species were detected more frequently from tooth than tongue samples. lactobacillus gasseri (p < 0.01), lactobacillus fermentum, lactobacillus vaginalis, and s. mutans with streptococcus sobrinus (all p < 0.05) were positively associated with caries. by  multifactorial analysis, the probiotic lactobacillus acidophilus was negatively associated with caries. prevotella nigrescens was the only species (p < 0.05) significantly associated with caries by the 'false discovery' rate. analysis of the data suggests that selected lactobacillus species, in addition to mutans streptococci, are risk markers for early childhood caries.
TIHT== 
ABHT== 

