@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25479553
TI  == immunomodulatory properties of streptococcus and veillonella isolates from the human small intestine microbiota.
AB  == the human small intestine is a key site for interactions between the intestinal microbiota and the mucosal immune system. here we investigated the immunomodulatory properties of representative species of commonly dominant small-intestinal microbial communities, including six streptococcal strains (four streptococcus salivarius, one s. equinus, one s. parasanguinis) one veillonella parvula strain, one enterococcus gallinarum strain, and lactobacillus plantarum wcfs1 as a bench mark strain on human monocyte-derived dendritic cells. the different streptococci induced varying levels of the cytokines il-8, tnf-alpha, and il-12p70, while the v. parvula strain showed a strong capacity to induce il-6. e. gallinarum strain was a potent inducer of cytokines and tlr2/6 signalling. as streptococcus and veillonella can potentially interact metabolically and frequently co-occur in ecosystems, immunomodulation by pair-wise combinations of strains were also tested for their combined immunomodulatory properties. strain combinations induced cytokine responses in dendritic cells that differed from what might be expected on the basis of the results obtained with the individual strains. a combination of (some) streptococci with veillonella appeared to negate il-12p70 production, while augmenting il-8, il-6, il-10, and tnf-alpha responses. this suggests that immunomodulation data obtained in vitro with individual strains are unlikely to adequately represent immune responses to mixtures of gut microbiota communities in vivo. nevertheless, analysing the immune responses of strains representing the dominant species in the intestine may help to identify immunomodulatory mechanisms that influence immune homeostasis.
TIHT== 
ABHT== 

PMID== 24977706
TI  == comparative genomics of the bacterial genus streptococcus illuminates evolutionary implications of species groups.
AB  == members of the genus streptococcus within the phylum firmicutes are among the most diverse and significant zoonotic pathogens. this genus has gone through considerable taxonomic revision due to increasing improvements of chemotaxonomic  approaches, dna hybridization and 16s rrna gene sequencing. it is proposed to place the majority of streptococci into "species groups". however, the evolutionary implications of species groups are not clear presently. we use comparative genomic approaches to yield a better understanding of the evolution of streptococcus through genome dynamics, population structure, phylogenies and virulence factor distribution of species groups. genome dynamics analyses indicate that the pan-genome size increases with the addition of newly sequenced  strains, while the core genome size decreases with sequential addition at the genus level and species group level. population structure analysis reveals two distinct lineages, one including pyogenic, bovis, mutans and salivarius groups, and the other including mitis, anginosus and unknown groups. phylogenetic dendrograms show that species within the same species group cluster together, and infer two main clades in accordance with population structure analysis. distribution of streptococcal virulence factors has no obvious patterns among the species groups; however, the evolution of some common virulence factors is congruous with the evolution of species groups, according to phylogenetic inference. we suggest that the proposed streptococcal species groups are reasonable from the viewpoints of comparative genomics; evolution of the genus is congruent with the individual evolutionary trajectories of different species groups.
TIHT== 
ABHT== 

PMID== 24625962
TI  == phylogenomics and the dynamic genome evolution of the genus streptococcus.
AB  == the genus streptococcus comprises important pathogens that have a severe impact on human health and are responsible for substantial economic losses to agriculture. here, we utilize 46 streptococcus genome sequences (44 species), including eight species sequenced here, to provide the first genomic level insight into the evolutionary history and genetic basis underlying the functional diversity of all major groups of this genus. gene gain/loss analysis revealed a dynamic pattern of genome evolution characterized by an initial period of gene gain followed by a period of loss, as the major groups within the genus diversified. this was followed by a period of genome expansion associated with the origins of the present extant species. the pattern is concordant with an emerging view that genomes evolve through a dynamic process of expansion and streamlining. a large proportion of the pan-genome has experienced lateral gene transfer (lgt) with causative factors, such as relatedness and shared environment, operating over different evolutionary scales. multiple gene ontology terms were significantly enriched for each group, and mapping terms onto the phylogeny showed that those corresponding to genes born on branches leading to the major groups represented approximately one-fifth of those enriched. furthermore, despite the extensive lgt, several biochemical characteristics have  been retained since group formation, suggesting genomic cohesiveness through time, and that these characteristics may be fundamental to each group. for example, proteolysis: mitis group; urea metabolism: salivarius group; carbohydrate metabolism: pyogenic group; and transcription regulation: bovis group.
TIHT== 
ABHT== 

PMID== 24505091
TI  == activity of oritavancin tested against uncommonly isolated gram-positive pathogens responsible for documented infections in hospitals worldwide.
AB  == objectives: to assess the oritavancin spectrum and activity against 2811 rarer species of coagulase-negative staphylococci (cons), streptococci and other gram-positive species. methods: a total of 2057 cons (14 species), 674 streptococci (7 groups) and 80 other gram-positive species (3 genera) collected over a 5 year period as part of the sentry program (2008-12) were included. isolates were primarily identified by the participating laboratory and identification was confirmed by the reference monitoring laboratory (jmi laboratories, north liberty, ia, usa). isolates were tested for susceptibility by broth microdilution following the clsi m07-a9 and m100-s23 documents. results: overall, oritavancin was active against all cons (mic50/mic90, 0.015/0.06 mg/l),  with mic50 values of </=0.008-0.03 mg/l. streptococci exhibited oritavancin mic50 results of </=0.008 mg/l, except for the streptococcus bovis (0.03 mg/l), streptococcus dysgalactiae (0.06 mg/l) and streptococcus salivarius/vestibularis  (0.06 mg/l) groups. micrococcus spp., listeria monocytogenes and corynebacterium  spp. had oritavancin mic50 results of </=0.008 mg/l. conclusions: this study expands the oritavancin in vitro data against several species of gram-positive organisms.
TIHT== 
ABHT== 

PMID== 24386196
TI  == comparative genomics analysis of streptococcus isolates from the human small intestine reveals their adaptation to a highly dynamic ecosystem.
AB  == the human small-intestinal microbiota is characterised by relatively large and dynamic streptococcus populations. in this study, genome sequences of small-intestinal streptococci from s. mitis, s. bovis, and s. salivarius species-groups were determined and compared with those from 58 streptococcus strains in public databases. the streptococcus pangenome consists of 12,403 orthologous groups of which 574 are shared among all sequenced streptococci and are defined as the streptococcus core genome. genome mining of the small-intestinal streptococci focused on functions playing an important role in the interaction of these streptococci in the small-intestinal ecosystem, including natural competence and nutrient-transport and metabolism. analysis of the small-intestinal streptococcus genomes predicts a high capacity to synthesize amino acids and various vitamins as well as substantial divergence in their carbohydrate transport and metabolic capacities, which is in agreement with observed physiological differences between these streptococcus strains. gene-specific pcr-strategies enabled evaluation of conservation of streptococcus  populations in intestinal samples from different human individuals, revealing that the s. salivarius strains were frequently detected in the small-intestine microbiota, supporting the representative value of the genomes provided in this study. finally, the streptococcus genomes allow prediction of the effect of dietary substances on streptococcus population dynamics in the human small-intestine.
TIHT== 
ABHT== 

PMID== 24048531
TI  == evaluation of the nanosphere verigene gram-positive blood culture assay with the  versatrek blood culture system and assessment of possible impact on selected patients.
AB  == the verigene gram-positive blood culture (bc-gp) assay (nanosphere, northbrook, il) is a molecular method for the rapid identification of gram-positive organisms and resistance markers directly from blood culture bottles. a total of 148 versatrek redox 1 40-ml aerobic bottles demonstrating gram-positive bacteria were tested. results were compared with those from conventional biochemical and matrix-assisted laser desorption ionization-time of flight (maldi-tof) identifications. we obtained isolates of methicillin-resistant staphylococcus aureus (mrsa) (24), methicillin-susceptible staphylococcus aureus (mssa) (14), methicillin-resistant staphylococcus epidermidis (mrse) (17), methicillin-susceptible staphylococcus epidermidis (msse) (9), other coagulase-negative staphylococci (19), streptococcus salivarius (5), streptococcus parasanguinis (2), streptococcus sanguinis (1), streptococcus cristatus (1), the streptococcus bovis group (5), streptococcus agalactiae (9), the streptococcus anginosus group (1), streptococcus pneumoniae (6), vancomycin-resistant enterococcus faecium (vre fcm) (16), vancomycin-susceptible  enterococcus faecalis (3), aerococcus viridans (2), bacillus (6), corynebacterium (8), lactobacillus (2), micrococcus (2), neisseria mucosa (1), escherichia coli (3), candida tropicalis (1), propionibacterium (1), and rothia (1). overall agreement with the culture results was 95%. a total of 137 of 138 (99%) monomicrobial cultures were concordant. we tested 9 polymicrobial samples and found 33% agreement. a chart review of 31 patients with mrsa, mssa, or vre demonstrated that the nanosphere bc-gp assay might have led to more appropriate antibiotic selection for these patients an average of 42 h earlier. additionally, contact isolation could have been initiated an average of 37 h earlier for patients with mrsa or vre. the bc-gp assay may have a positive impact on patient  care, health care costs, and antibiotic stewardship.
TIHT== 
ABHT== 

PMID== 23527301
TI  == insight into the evolution of the histidine triad protein (htp) family in streptococcus.
AB  == the histidine triad proteins (htps), also known as pht proteins in streptococcus  pneumoniae, constitute a family of surface-exposed proteins that exist in many pathogenic streptococcal species. although many studies have revealed the importance of htps in streptococcal physiology and pathogenicity, little is known about their origin and evolution. in this study, after identifying all htp homologs from 105 streptococcal genomes representing 38 different species/subspecies, we analyzed their domain structures, positions in genome, and most importantly, their evolutionary histories. by further projecting this information onto the streptococcal phylogeny, we made several major findings. first, htp genes originated earlier than the streptococcus genus and gene-loss events have occurred among three streptococcal groups, resulting in the absence of the htp gene in the bovis, mutans and salivarius groups. second, the copy number of htp genes in other groups of streptococcus is variable, ranging from one to four functional copies. third, both phylogenetic evidence and domain structure analyses support the division of two htp subfamilies, designated as htp i and htp ii. although present mainly in the pyogenic group and in streptococcus  suis, htp ii members are distinct from htp i due to the presence of an additional leucine-rich-repeat domain at the c-terminus. finally, htp genes exhibit a faster nucleotide substitution rate than do housekeeping genes. specifically, the regions outside the htp domains are under strong positive selection. this distinct evolutionary pattern likely helped streptococcus to easily escape from recognition by host immunity.
TIHT== 
ABHT== 

PMID== 23478959
TI  == early in vitro and in vivo development of high-level daptomycin resistance is common in mitis group streptococci after exposure to daptomycin.
AB  == the development of high-level daptomycin resistance (hldr; mic of >/= 256 mg/liter) after exposure to daptomycin has recently been reported in viridans group streptococcus (vgs) isolates. our study objectives were as follows: to know whether in vitro development of hldr after exposure to daptomycin was common among clinical isolates of vgs and streptococcus bovis; to determine whether hldr also developed during the administration of daptomycin to treat experimental endocarditis caused by the daptomycin-susceptible, penicillin-resistant streptococcus mitis strain s. mitis 351; and to establish whether combination with gentamicin prevented the development of hldr in vitro and in vivo. in vitro  studies were performed with 114 vgs strains (mitis group, 92; anginosus group, 10; mutans group, 8; and salivarius group, 4) and 54 streptococcus bovis strains  isolated from 168 consecutive patients with infective endocarditis diagnosed between 1995 and 2010. hldr was only observed after 24 h of exposure to daptomycin in 27% of the mitis group, including 27% of s. mitis isolates, 47% of  s. oralis isolates, and 13% of s. sanguis isolates. in our experimental model, hldr was detected in 7/11 (63%) and 8/12 (67%) isolates recovered from vegetations after 48 h of daptomycin administered at 6 mg/kg of body weight/24 h  and 10 mg/kg/24 h, respectively. in vitro, time-kill experiments showed that daptomycin plus gentamicin was bactericidal against s. mitis 351 at tested concentrations of 0.5 and 1 times the mic and prevented the development of hldr.  in vivo, the addition of gentamicin at 1 mg/kg/8 h to both daptomycin arms prevented hldr in 21 out of 23 (91%) rabbits. daptomycin plus gentamicin was at least as effective as vancomycin plus gentamicin. in conclusion, hldr develops rapidly and frequently in vitro and in vivo among mitis group streptococci. combining daptomycin with gentamicin enhanced its activity and prevented the development of hldr in most cases.
TIHT== 
ABHT== 

PMID== 21673976
TI  == infective endocarditis: identification of catalase-negative, gram-positive cocci  from blood cultures by partial 16s rrna gene analysis and by vitek 2 examination.
AB  == streptococci, enterococci and streptococcus-like bacteria are frequent etiologic  agents of infective endocarditis and correct species identification can be a laboratory challenge. viridans streptococci (vs) not seldomly cause contamination of blood cultures. vitek 2 and partial sequencing of the 16s rrna gene were applied in order to compare the results of both methods. strains originated from  two groups of patients: 149 strains from patients with infective endocarditis and 181 strains assessed as blood culture contaminants. of the 330 strains, based on  partial 16s rrna gene sequencing results, 251 (76%) were vs strains, 10 (3%) were pyogenic streptococcal strains, 54 (16%) were e. faecalis strains and 15 (5%) strains belonged to a group of miscellaneous catalase-negative, gram-positive cocci. among vs strains, respectively, 220 (87,6%) and 31 (12,3%) obtained agreeing and non-agreeing identifications with the two methods with respect to allocation to the same vs group. non-agreeing species identification mostly occurred among strains in the contaminant group, while for endocarditis strains notably fewer disagreeing results were observed.only 67 of 150 strains in the mitis group strains obtained identical species identifications by the two methods. most vs strains belonging to the groups of salivarius, anginosus, and mutans obtained agreeing species identifications with the two methods, while this only was the case for 13 of the 21 bovis strains. pyogenic strains (n=10), enterococcus faecalis strains (n=54) and a miscellaneous group of catalase-negative, gram-positive cocci (n=15) seemed well identified by both methods, except that disagreements in identifications in the miscellaneous group  of strains occurred for 6 of 15 strains.
TIHT== 
ABHT== 

PMID== 19880633
TI  == partial recn gene sequencing: a new tool for identification and phylogeny within  the genus streptococcus.
AB  == partial sequences of the recn gene (1249 bp), which encodes a recombination and repair protein, were analysed to determine the phylogenetic relationship and identification of streptococci. the partial sequences presented interspecies nucleotide similarity of 56.4-98.2 % and intersubspecies similarity of 89.8-98 %. the mean dna sequence similarity of recn gene sequences (66.6 %) was found to be  lower than those of the 16s rrna gene (94.1 %), rpob (84.6 %), soda (74.8 %), groel (78.1 %) and gyrb (73.2 %). phylogenetically derived trees revealed six statistically supported groups: streptococcus salivarius, s. equinus, s. hyovaginalis/s. pluranimalium/s. thoraltensis, s. pyogenes, s. mutans and s. suis. the 'mitis' group was not supported by a significant bootstrap value, but three statistically supported subgroups were noted: streptococcus sanguinis/s. cristatus/s. sinensis, s. anginosus/s. intermedius/s. constellatus (the 'anginosus' subgroup) and s. mitis/s. infantis/s. peroris/s. oralis/s. oligofermentans/s. pneumoniae/s. pseudopneumoniae. the partial recn gene sequence comparison highlighted a high percentage of divergence between streptococcus dysgalactiae subsp. dysgalactiae and s. dysgalactiae subsp. equisimilis. this observation is confirmed by other gene sequence comparisons (groel, gyrb, rpob and soda). a high percentage of similarity was found between s. intermedius and s. constellatus after sequence comparison of the recn gene. to study the genetic  diversity among the 'anginosus' subgroup, recn, groel, soda, gyrb and rpob sequences were determined for 36 clinical isolates. the results that were obtained confirmed the high genetic diversity within this group of streptococci.
TIHT== 
ABHT== 

PMID== 19878555
TI  == evolutionary relationships among salivarius streptococci as inferred from multilocus phylogenies based on 16s rrna-encoding, reca, seca, and secy gene sequences.
AB  == background: streptococci are divided into six phylogenetic groups, i.e, anginosus, bovis, mitis, mutans, pyogenic, and salivarius, with the salivarius group consisting of only three distinct species. two of these species, streptococcus salivarius and streptococcus vestibularis, are members of the normal human oral microflora whereas the third, streptococcus thermophilus, is found in bovine milk. given that s. salivarius and s. vestibularis share several  physiological characteristics, in addition to inhabiting the same ecosystem, one  would assume that they would be more closely related to each other than to s. thermophilus. however, the few phylogenetic trees published so far suggest that s. vestibularis is more closely related to s. thermophilus. to determine whether  this phylogenetic relationship is genuine, we performed phylogenetic inferences derived from seca and secy, the general secretion housekeeping genes, reca, a gene from a separate genetic locus that encodes a major component of the homologous recombinational apparatus, and 16s rrna-encoding gene sequences using  other streptococcal species as outgroups. results: the maximum likelihood (ml) and maximum parsimony (mp) phylogenetic inferences derived from the seca and reca gene sequences provided strong support for the s. vestibularis/s. thermophilus sister-relationship, whereas 16s rrna-encoding and secy-based analyses could not  discriminate between alternate topologies. phylogenetic analyses derived from the concatenation of these sequences unambiguously supported the close affiliation of s. vestibularis and s. thermophilus. conclusion: our results corroborated the sister-relationship between s. vestibularis and s. thermophilus and the concomitant early divergence of s. salivarius at the base of the salivarius lineage.
TIHT== 
ABHT== 

PMID== 19737768
TI  == antimicrobial resistance of streptococci isolated from mastitic bovine milk samples in korea.
AB  == the aim of this study was to determine the antimicrobial resistance of streptococci isolated from mastitic bovine milk samples. a total of 178 isolates  belonging to 6 different streptococcus species were examined: s. uberis (n = 99), s. bovis (n = 30), s. oralis (n = 24), s. salivarius (n = 13), s. intermedius (n  = 7), and s. agalactiae (n = 5). only 8.9% (16/178) of the isolates were susceptible to all antimicrobial agents tested in this study, and s. agalactiae and s. intermedius isolates were all resistant to at least 1 antimicrobial agent  tested. overall, the most frequently observed resistance was to tetracycline (61.2%), followed by lincomycin (43.2%), gentamycin (35.3%), oxacillin (34.3%), and erythromycin (28.6%). cephalothin and penicillin were the only antimicrobial  agents to which most of the streptococci (>or=92%) were susceptible. wide differences in the prevalence of resistance are apparent among the individual species: s. salivarius displayed exceptionally high resistance to cephalothin (23.0%) and oxacillin (76.9%) and s. agalactiae (20%) and s. intermedius (14.2%)  to penicillin. streptococcus salivarius and s. agalactiae were all susceptible to erythromycin, but others showed various rates of resistance ranging from 12.5% to 42.8%. resistance to 3 or more of 7 antimicrobial agents was observed in all species (37.6%, 67/178).
TIHT== 
ABHT== 

PMID== 19322715
TI  == association of streptococcus pluranimalium with valvular endocarditis and septicaemia in adult broiler parents.
AB  == the genus streptococcus consists of more than 60 species, but only streptococcus  equi subspecies zooepidemicus, streptococcus gallolyticus ssp. gallolyticus, streptococcus gallinaceus, streptococcus dysgalactiae, streptococcus mutans and streptococcus suis have been isolated from poultry. during investigations of the  aetiology of increased mortality in broiler parent stock at the end of production, pure cultures of streptococcal-like organisms that could not be classified among these six species were obtained from 24 cases of septicaemia or  valvular endocarditis and septicaemia. phenotypic characterization using the api20 strep kit identified the isolates as aerococcus viridans (10), aerococcus urinae (2), leuconostoc species (4), streptococcus salivarius (2), streptococcus  bovis ii 3 (1), enterococcus avium (3), enterococcus faecium (1) or gemella morbillorum (1). however, this identification was misleading as subsequent genetic investigations using pulse field gel electrophoresis and sequencing of 16s rrna genes showed that 19 isolates were classified as streptococcus pluranimalium, while the remaining isolates were e. avium (3), e. faecium (1) or  lactobacillus species (1). misidentification by api20 strep was related to the database provided by the manufacturer, as the phenotypic characteristics could identify these organisms as s. pluranimalium. the isolates of s. pluranimalium belonged to at least three different clones as determined by pulsed field gel electrophoresis of smai-digested genomic dna. the capacity that these isolates had to colonize the valvular endothelium was suggested by the occurrence of valvular endocarditis in 12 of 19 cases. demonstration of the same clone in all four houses on a farm suggested the pathogenic potential of this organism.
TIHT== 
ABHT== 

PMID== 17726300
TI  == molecular profiling of lactobacillus, streptococcus, and bifidobacterium species  in feces of active racehorses.
AB  == diversity and compositions of the lactobacillus, streptococcus, and bifidobacterium group in the feces of six healthy, actively racing horses (thoroughbreds) were analyzed by using pcr-denaturing gradient gel electrophoresis (dgge) and real-time pcr with primer sets specific for each group. pcr-dgge analysis of the feces showed that lactobacillus equi, lactobacillus johnsonii, a phylogenetic relative of lactobacillus salivarius, a phylogenetic relative of lactobacillus gastricus, and weissella confusa were predominant in almost all of the feces tested, and streptococcus bovis/streptococcus equinus was predominant in the streptococcus group. the bifidobacterium group was not detected by single-pcr but atypical species of the  group were found in three of the six thoroughbreds tested by nested-pcr. calculation and estimation of lactic acid bacteria and bifidobacteria revealed that lactic acid bacteria were predominant in the feces and bifidobacteria were minor. these results indicate that the community of lactic acid bacteria and bifidobacteria in horse feces are unique because of the presence of specific species for horse feces and a minority of the bifidobacterium group. repeated tests of the feces from the same horse over 3 months showed that the diversity and composition of lactic acid bacteria and bifidobacteria in the feces was basically stable throughout the test period.
TIHT== 
ABHT== 

PMID== 17215341
TI  == identification of alpha-hemolytic streptococci by pyrosequencing the 16s rrna gene and by use of vitek 2.
AB  == alpha-hemolytic streptococci are very difficult to identify by phenotypic methods. in this study, a pyrosequencing method for the identification of streptococcal species based on two variable regions of the 16s rrna gene is described. almost all studied streptococcal species (n = 51) represented by their type strains could be differentiated except for some closely related species of the streptococcus bovis or s. salivarius group. the pyrosequencing results of alpha-hemolytic streptococci isolated from blood (n = 99) or from the normal pharyngeal microbiota (n = 25) were compared to the results obtained by the vitek 2 with gp card (biomerieux, marcy l'etoile, france). as expected, the results of  the two methods did not completely agree, but 93 (75.0%) of the isolates assigned to the same streptococcal group by both methods and 57 (46.0%) reached consistent results at the species level. however, 10 strains remained unidentified by vitek  2, and 4 isolates could not be assigned to any streptococcal group by pyrosequencing. identification of members of the s. mitis and s. sanguinis groups proved difficult for both methods. furthermore, the pyrosequencing analysis revealed great sequence variation, since only 43 (32.3%) of the 133 isolates analyzed by pyrosequencing had sequences identical to a type strain. the variation was greatest in the pharyngeal isolates, slightly lower in the blood culture isolates, and nonexistent in invasive pneumococcal isolates (n = 17) that all had the s. pneumoniae type strain sequence. the resolution of the results obtained by the two methods is impeded by the lack of a proper gold standard.
TIHT== 
ABHT== 

PMID== 16989974
TI  == tigecycline (gar-936) activity against streptococcus gallolyticus (bovis) and viridans group streptococci.
AB  == viridans group streptococci including streptococcus gallolyticus (formerly s. bovis) represent serious invasive pathogens often associated with endocarditis or sepsis among immunocompromised or cancer patients. tigecycline (gar-936), the first clinically studied glycylcycline, has a potent gram-positive activity with  a potential treatment option for these streptococcal infections. the studied collection (848 strains) included 100 isolates each of streptococcus anginosus, streptococcus constellatus, streptococcus intermedius, streptococcus mitis, streptococcus oralis, streptococcus salivarius, streptococcus sanguis, and fewer  strains of s. gallolyticus (98 strains) and streptococcus mutans (50 strains). these strains were isolated from patients on 3 continents in the sentry antimicrobial surveillance program and tested for susceptibility and interpreted  by clinical and laboratory standards institute broth microdilution methods and criteria (< or = 0.25 microg/ml for tigecycline per us food and drug administration). penicillin susceptibility rates for the entire collection varied from 61% (s. sanguis) to 98% (s. constellatus), and macrolide susceptibility was  also compromised (49-88%; average, 69%). tigecycline was active against all isolates tested, in contrast to tetracycline resistance rates of 8-66%, and highest for s. gallolyticus. in conclusion tigecycline was quite active against bacteremic isolates of viridans group streptococci species and s. gallolyticus with an overall mic90 at < or = 0.06 microg/ml; the highest mic was only 0.25 microg/ml.
TIHT== 
ABHT== 

PMID== 16868828
TI  == inflammatory bowel disease and streptococcus bovis.
AB  == evidence suggests a trend for a higher fecal carriage rate of streptococcus bovis in adult patients with inflammatory bowel disease (ibd). this study defines the fecal carriage rate of s. bovis among children with ibd compared to controls. subjects with ibd were prospectively enrolled from the patient population of a pediatric gastroenterology practice. stool samples from ibd patients as well as controls were analyzed within 24 hr for the presence of s. bovis. the study enrolled 47 patients with ibd and 34 controls. among the 47 ibd patients, 3 had a positive stool culture for s. bovis (6%) and 1 had an equivocal result between s. bovis and s. salivarius. including this equivocal result, 8.5% of ibd patients were s. bovis carriers. among the 34 controls, 3 (9%) were found to be fecal carriers of s. bovis. assuming that the equivocal stool was indeed s. bovis, these groups are not statistically different as determined by fisher's exact test (p=0.6). we conclude that the fecal carriage rate of s. bovis is not increased among pediatric patients with ibd compared with controls.
TIHT== 
ABHT== 

PMID== 15902530
TI  == clinical characteristics and significance of streptococcus salivarius bacteremia  and streptococcus bovis bacteremia: a prospective 16-year study.
AB  == the aim of this study was to determine the clinical significance of streptococcus salivarius isolates recovered from blood cultures and compare them with isolates  of streptococcus bovis biotypes i and ii. seventeen of the 52 (32%) s. salivarius isolates recovered were considered clinically significant, compared with 62 of the 64 (97%) s. bovis isolates (p<0.0001). bacteremia caused by s. salivarius occurred mostly in patients who showed relevant disruption of the mucous membranes and/or serious underlying diseases. patients with s. salivarius bacteremia were younger than those with s. bovis bacteremia (57 vs. 67 years; p<0.01). patients with s. salivarius bacteremia and patients with s. bovis ii bacteremia had similar rates of endocarditis, colon tumors, and non-colon cancer. on the other hand, when compared with s. bovis i bacteremia, s. salivarius bacteremia was associated with lower rates of endocarditis (18% vs. 74%, respectively) (p<0.01) and colon tumors (0% vs. 57%, respectively) (p<0.005) and  higher rates of non-colon cancer (53% vs. 9.5%, respectively) (p<0.01). bacteremia caused by s. bovis ii had a hepatobiliary origin in 50% of the patients, while, in contrast, that due to s. salivarius or s. bovis i was less frequently associated with a hepatobiliary origin (12% and 5%, respectively) (p<0.00001). the rate of penicillin resistance was 31% among s. salivarius isolates and 0% among s. bovis isolates (p<0.0001). in conclusion, the clinical characteristics of s. salivarius bacteremia and s. bovis ii bacteremia are similar, and the isolation of s. salivarius in blood should not be systematically regarded as contamination.
TIHT== 
ABHT== 

PMID== 12653214
TI  == no synthesis in human saliva.
AB  == human saliva contains nitrate that is converted into nitrite by the activity of facultative, anaerobic bacteria of the oral cavity. nitrite can be reduced to no  in the acidic gastric milieu; some no may also form in the mouth at acidic ph values. in this paper, we show that bacteria (s. salivarius, s. mitis and s. bovis) isolated from saliva, may contribute to no production in human saliva. no  formation by bacteria occurs at neutral ph values and may contribute to the antibacterial activity of saliva.
TIHT== 
ABHT== 

PMID== 12634348
TI  == 16s-23s rrna intergenic spacer region sequence variation in streptococcus thermophilus and related dairy streptococci and development of a multiplex its-sscp analysis for their identification.
AB  == the 16s-23s rrna internal transcribed spacer (its) region of several streptococcus thermophilus strains and some related dairy streptococci, s. macedonicus, s. salivarius and s. bovis, was analysed by sequence analysis. all the streptococcus species were easily discriminated on the basis of sequence variations principally located upstream and downstream of the region encompassing the double-stranded processing sites and the trna(ala) gene. comparison between trna(ala) gene sequences highlighted a high level of sequence conservation among  the streptococcus species investigated despite their belonging to separated phylogenetic clusters, i.e. the s. salivarius and s. bovis rrna groups. a low but significant degree of variability was detected among the s. thermophilus strains, allowing the identification of four different its sequences. similarity analysis  of the its sequences showed that the streptococcus species were clustered in two  main branches, one containing s. macedonicus and s. bovis strains, and one containing s. thermophilus and s. salivarius strains. with the aim of developing  a rapid tool for the identification of the dairy streptococci species a multiplex its-sscp analysis of two discrete regions within the its locus was carried out.
TIHT== 
ABHT== 

PMID== 12354897
TI  == reevaluation of streptococcus bovis endocarditis cases from 1975 to 1985 by 16s ribosomal dna sequence analysis.
AB  == studies that detected an association between streptococcus bovis endocarditis and colon carcinoma have not taken into account the recently identified genetic diversity among organisms historically classified as s. bovis. with near full-length 16s ribosomal dna sequence analysis, organisms cultured from the blood of endocarditis patients at the mayo clinic from 1975 to 1985 and previously identified as s. bovis or streptococcus group d nonenterococci were shown to represent s. bovis biotypes i (11 isolates) and ii/2 (1 isolate), s. salivarius (1 isolate), and s. macedonicus (1 isolate). two of the s. bovis biotype i cases were associated with colon cancer. whether s. bovis biotype ii or other organisms closely related to and historically identified as s. bovis (e.g., s. macedonicus) are associated with malignant (or premalignant) colon lesions in  humans remains to be definitively determined.
TIHT== 
ABHT== 

PMID== 12202549
TI  == groesl sequence determination, phylogenetic analysis, and species differentiation for viridans group streptococci.
AB  == the full-length sequences of the groesl genes (also known as cpn10/60) of streptococcus anginosus, streptococcus constellatus, streptococcus gordonii, and  streptococcus sanguis and the near full-length sequence of the groesl genes of streptococcus intermedius, streptococcus bovis, streptococcus mitis, streptococcus mutans, streptococcus oralis, and streptococcus salivarius were determined. the lengths of the groes genes from the 10 species listed above ranged from 282 to 288 bp, and the full-length sequences of groel determined for  4 species (s. anginosus, s. constellatus, s. gordonii, and s. sanguis) revealed that each was 1,623 bp. the intergenic region (spacer) between the groes and groel genes varies in size (15 to 111 bp) and sequence between species. the variation of the groes sequences among the species tested was greater (62.1 to 95.1% nucleotide sequence identities) than that of the groel sequences (77.2 to 95.2% nucleotide sequence identities). phylogenetic analysis of the groes and groel genes yielded evolutionary trees similar to the tree constructed by use of  the 16s rrna gene. the intraspecies variation of the spacer was minimal for clinical isolates of some species. the groesl sequence data provide an additional parameter for identification of viridans group streptococcal species.
TIHT== 
ABHT== 

PMID== 11753449
TI  == [susceptibility to penicillin and 13 antimicrobial agents in erythromycin-resistant viridans group streptococci isolated from blood cultures].
AB  == from march 1998 to june 1999, we studied 63 sequential blood culture isolates of  viridans group streptococci which showed a 49% resistance to erythromycin. a high level of resistance to penicillin (46%) was also found. a statistically significant correlation was detected between the two types of resistance. the erythromycin-resistant strains were phenotypically and genotypically characterized, and no differences were found between the resistance to penicillin and the m or mls(b) phenotypes. the penicillin-erythromycin-resistant strains included: 16 s. mitis, five s. sanguis and one s. salivarius. the rank order of activity (% of susceptibility) for all 14 agents against 31 erythromycin- resistant isolates was the following: vancomycin = rifampicin (100) > chloramphenicol (98) > meropenem (65) > cefotaxime (61) > amoxicillin- clavulanic acid (42) > cefepime = ciprofloxacin (39) > tetracycline = trimethoprim-sulfamethoxazole (36) > cefuroxime (32) > penicillin = ampicillin =  cefaclor (29). the species s. milleri and s. bovis were the most susceptible. the most resistant strains were two s. mitis and one s. sanguis and showed multiresistance to six different groups of antimicrobial agents. the frequent association between macrolide resistance and resistance to other antimicrobial agents suggests that the susceptibility of all clinically significant isolates needs to be evaluated and alternative agents for the prevention and treatment of  viridans group streptococci infections should be identified.
TIHT== 
ABHT== 

PMID== 9788817
TI  == speciation of presumptive viridans streptococci from early onset neonatal sepsis.
AB  == twenty isolates resembling viridans streptococci, 16 from blood and four from gastric aspirates, from 17 cases of early onset neonatal sepsis were identified by the api20 strep, rapid id 32 strep and conventional tests plus hydrolysis of methylumbelliferyl glycoside substrates. nineteen of the isolates were identified as species of viridans streptococci and one as a leuconostoc sp. ten of the isolates were streptococcus oralis, three s. mitis biotype 1, two s. mitis biotype 2 and one each of s. sanguis, s. vestibularis, s. salivarius and s. intermedius. the rapid id 32 strep and conventional plus methylumbelliferyl tests gave the same species identity for 17 of the isolates. s. intermedius was identified by the rapid id 32 strep as s. constellatus and s. salivarius as s. equinus, with s. salivarius at lower probability. the api20 strep failed to identify s. vestibularis and identified s. salivarius as s. defectivus. the absence of certain critical tests, including urea hydrolysis, does not allow the  api20 strep to identify all the currently recognised species of viridans steptococci. the species distribution was unexpected and the incidence of s. oralis and other viridans streptococci in vaginal swabs from prenatal patients is being investigated further.
TIHT== 
ABHT== 

PMID== 9431917
TI  == identification of streptococci to species level by sequencing the gene encoding the manganese-dependent superoxide dismutase.
AB  == we have used a pcr assay based on the use of degenerate primers in order to characterize an internal fragment (soda(int)) representing approximately 85% of the genes encoding the manganese-dependent superoxide dismutase in various streptococcal type strains (s. acidominimus, s. agalactiae, s. alactolyticus, s.  anginosus, s. bovis, s. constellatus, s. canis, s. cricetus, s. downei, s. dysgalactiae, s. equi subsp. equi, s. equi subsp. zooepidemicus, s. equinus, s. gordonii, s. iniae, s. intermedius, s. mitis, s. mutans, s. oralis, s. parasanguis, s. pneumoniae, s. porcinus, s. pyogenes, s. salivarius, s. sanguis,  s. sobrinus, s. suis, s. thermophilus, and s. vestibularis). phylogenetic analysis of these soda(int) fragments yields an evolutionary tree having a topology similar to that of the tree constructed with the 16s rrna sequences. we  have shown that clinical isolates could be identified by determining the positions of their soda(int) fragments on the phylogenetic tree of the soda(int)  fragments of the type species. we propose this method for the characterization of strains that cannot be assigned to a species on the basis of their conventional phenotypic reactions.
TIHT== 
ABHT== 

PMID== 9101752
TI  == [evaluation of a rapid method for the identification of the enterococcus genus].
AB  == background: the evaluation of the reliability of a group of three tests: pyrrolidonil-arilamidase, rapid test in nacl esculin broth and group d antistreptococci agglutination for the rapid identification of the enterococcus genus were performed. methods: one hundred fifty-eight strains of streptococci: 110 strains of enterococcus faecalis, 8 e. faecium, 3 e. avium, 16 streptococcus  intermedius, 7 s. salivarius, 4 s. bovis, 4 s. constellatus, 2 s. sanguis and 1 strain of s. equinus, s. mitis, s. uberis and s. mutans were studied. the tests used were: rapid test in nacl- esculin broth, pyrrolidonyl-arilamidase and antigroup d streptococcus agglutination (patho dx strep d/pyr; diagnostic product corporation). all catalase-negative gram-positive cocci or coccibacilli which were positive in the three tests were considered to belong to the enterococcus genus. the usefulness of gram staining in culture in thioglycolate broth was also studied comparing it with the results obtained with solid medium. results: the results of the proposed identification scheme were evaluated calculating different parameters: sensitivity 98%, specificity 100%, positive predictive value, 100%, and negative predictive value 94%. no significant differences were observed between the results obtained with gram staining with thioglycolate broth and those obtained with solid medium except in the case of the streptococcus mutans strain. conclusions: the application of a combination of tests: pyrroidonyl-arilamidase, antistreptococci group d agglutination and rapid test in nacl-esculin broth to catalase-negative gram-positive cocci and coccobacilli allows reliable identification in a maximum of three hours of strains belonging to the enterococcus genus.
TIHT== 
ABHT== 

PMID== 9082078
TI  == [serologic study in patients with streptococcal infective endocarditis].
AB  == background: infective endocarditis is a systemic disease in which there are a continuously antigenic stimulation of immunologic system. streptococcus is still  the most frequent cause of infective endocarditis. patients and methods: we investigated the presence of antibody (ab), total and igm by indirect immune fluorescence technique, in four groups of population: streptococcal infective endocarditis (sie), streptococcal bacteraemia (sb), staphylococcus aureus endocarditis, and healthy people. antigens used were: 1) their own strain isolated from the blood of patients with sie and sb inverted question markhomologous ab inverted question mark, and; 2) seven species of streptococcus: streptococcus intermedius, streptococcus salivarius, streptococcus bovis, streptococcus sanguis i, streptococcus sanguis ii, nutritional dependent streptococci and enterococcus faecalis (heterologous ab). results: homologous antibodies: titers > or = 1/512 were found in all patients with sie and only in 2 with sb (sensitivity 100% and specificity 93%). igm titer (threshold 1/32) was positive only in patients with sie (sensitivity 75,5% and specificity 100%). the  fall of the ab titer was continuous and slow, despite the good clinical evolution of patients. (ab titers were > or = 1/512 and igm > or = 1/64 in 30% of patients  1 year later). heterologous ab: in spite of statistically significant difference  found in sie versus the other groups, sensitivity of this test (threshold 1/256)  is low, confidence interval include expected random value (50%), specificity is 88%. conclusions: the utility of homologous ab for diagnosing infective endocarditis is demonstrated. on the contrary for heterologous ab, antigenic common fractions must be found in the different species.
TIHT== 
ABHT== 

PMID== 8868433
TI  == inducer expulsion and the occurrence of an hpr(ser-p)-activated sugar-phosphate phosphatase in enterococcus faecalis and streptococcus pyogenes.
AB  == inducer expulsion, a phenomenon in which rapidly metabolizable sugars cause cytoplasmic dephosphorylation and efflux of pre-accumulated sugar-phosphates (sugar-p), has been documented for streptococcus pyogenes, streptococcus bovis, and lactococcus lactis, but not for other gram-positive bacteria. using intact cells and membrane vesicles, we show that enterococcus faecalis exhibits both inducer exclusion and inducer expulsion, and that the latter phenomenon is dependent on the metabolite-activated atp-dependent hpr(ser) kinase that phosphorylates ser-46 in hpr of the phosphotransferase system. a small, heat-stable, membrane-associated, hpr(ser-p)-activated sugar-p phosphatase (pase  ii), previously identified only in lc. lactis, is shown to be present in extracts of enterococcus faecalis and streptococcus pyogenes but not in those of staphylococcus aureus, streptococcus mutans, streptococcus salivarius, or bacillis subtilis, organisms that do not exhibit the inducer expulsion phenomenon. further, lactobacillus brevis, an organism that exhibits inducer expulsion by a different mechanism, also apparently lacks pase ii. the results reveal that pase ii is present in those organisms that exhibit the coupled sugar-p hydrolysis/expulsion mechanism but not those that lack this mechanism. they provide correlative evidence that pase ii initiates inducer expulsion in species of enterococci, streptococci and lactococci.
TIHT== 
ABHT== 

PMID== 7716323
TI  == [the isolation of streptococcus morbillorum from vaginal exudates].
AB  == we have tested 195 vaginal secretions sent by gynecology service of this hospital between the years 1988-1990. we achieved positive culture for streptococci in 58  (30%) of these cultures, 26 (44.8%) corresponding to streptococcus morbillorum 9  (15.5%), to gardnerella vaginalis 5 (8.6%), to enterococcus faecalis-durans and to streptococcus agalactiae, 3 (5.1%) to streptococcus mitis and milleri 2 (3.4%), to streptococcus bovis and cremoris, and 1 (1.7%) to streptococcus salivarius, equinus and sanguis ii respectively. we previously found that 52.8% of these patients were positive for vaginal candidiasis. the bacteriological identification done by the api 20 strep system (biomerieux gmbh, nutingen, germany) provides a typical pattern ("good identification") for the streptococcus morbillorum.
TIHT== 
ABHT== 

PMID== 7537076
TI  == determination of 16s rrna sequences of streptococcus mitis and streptococcus gordonii and phylogenetic relationships among members of the genus streptococcus.
AB  == we determined the 16s rrna sequences of the type strains of streptococcus mitis and streptococcus gordonii and calculated the phylogenetic distances between those organisms and other members of the genus streptococcus. the viridans group  streptococci were separated into five phylogenetic groups; we named these groups  the anginosus group, the mitis group, the salivarius group, the bovis group, and  the mutans group. s. mitis and s. gordonii clustered in the mitis group together  with streptococcus pneumoniae, streptococcus oralis, streptococcus sanguis, and streptococcus parasanguis at levels of sequence homology of more than 96%. within this group, s. mitis, s. oralis, and s. pneumoniae exhibited more than 99% sequence homology with each other, although the dna-dna similarity values for their total chromosome dnas were less than 60%.
TIHT== 
ABHT== 

PMID== 7532504
TI  == identification of intracellular amylase activity in streptococcus bovis and streptococcus salivarius.
AB  == the ruminal bacterium streptococcus bovis has been demonstrated to produce an extracellular amylase activity. we previously reported on the cloning of a gene from s. bovis encoding for what was initially believed to be the extracellular amylase. dna sequence analyses indicated that the amylase produced by the cloned  gene did not match the n-terminus amino acid sequence of the purified extracellular amylase and contained no apparent leader sequence for secretion. analyses of crude extracts demonstrated the presence of an intracellular amylase  in s. bovis jb1 that differed in molecular weight (56,000) from that of the extracellular amylase (70,000). the 56,000 molecular weight amylase was identical to the amylase produced by escherichia coli containing the cloned amylase gene. low levels of intracellular amylase activity were also detected in other strains  of s. bovis and also streptococcus salivarius. introduction of the plasmid pva838 containing the cloned amylase gene into s. bovis and s. sanguis resulted in enhanced intracellular amylase production by both organisms. the amylase gene has been sequenced, and analysis of the deduced amino acid sequence for the amylase indicates a high degree of similarity with secreted amylases from bacillus species.
TIHT== 
ABHT== 

PMID== 7811768
TI  == [clinical significance of bacteremia caused by streptococci of the viridans group].
AB  == background: the viridans group streptococcus (svg) include species which may have different pathogenic capacity. this study was aimed at evaluating the clinical significance of bacteremia by different species of svg. patients and methods: one hundred ninety-four clinical records of patients with blood culture(s) isolation  (hemoline/biomerieux) of svg (api 20 strep/biomerieux) over 9 years were reviewed with criteria of clinical significance being established and the results analyzed by the chi square test. results: the most frequent species of svg isolated were:  s. sanguis ii (29.4%), s. mitis (27.3%) and s. anginosus (12.9%). with regard to  the criteria established, 36% of the isolates were clinically significant, associating s. anginosus with significant bacteremia (p = 0.001) and s. mitis with non significant bacteremia (p = 0.04). more than half of the isolations of s. anginosus, s. bovis, s. mutans and s. adjacens were clinically significant with this rate being lower in the remaining species (s. sanguis i, s. sanguis ii, s. mitis, s. salivarius and s. acidominimus). the significant isolations correspond with endocarditis (s. sanguis ii being responsible for 44%; p = 0.05). in 54.3% of the cases followed by abscesses or other localized infections and severe sepsis in patients with a solid or hematologic tumor with a mortality of 20%. the endocarditis/other disease relation was: greater for the existence of endocarditis for s. sanguis ii, s. sanguis i, s. mutans, s. bovis and s. adjacens; similar in both diseases for s. mitis, and greater for the existence of a non endocardic disease for s. anginosus. conclusions: in this series the isolation of svg group was clinically significant in 36% of cases with a probability of clinical significance and disease association related to the species isolated of svg.
TIHT== 
ABHT== 

PMID== 8065473
TI  == [bacteremia caused by streptococcus salivarius and s. milleri, and colonic carcinoma].
AB  == there is a well-known association between colon carcinoma and bacteraemia with streptococcus bovis biotype i. there are also associations, less well known, with other streptococci of the viridans group. in three patients, a man of 44, a woman of 53 and one of 52 years old, colorectal carcinomas were diagnosed in association with bacteraemia with s. salivarius, s. milleri, and s. salivarius respectively.
TIHT== 
ABHT== 

PMID== 7691873
TI  == development of a dna probe for streptococcus bovis by using a cloned amylase gene.
AB  == streptococcus bovis is a normal inhabitant of the rumen but has been implicated as a causative agent for ruminal lactic acidosis and related problems. while rarely isolated from humans, s. bovis has been identified as a causative agent for endocarditis, meningitis, and septicemia. recent reports have also suggested  a correlation between human colonic carcinoma and increased levels of s. bovis. identification of s. bovis strains of human origin has been problematic because of variations in results of biochemical tests compared with results for ruminal strains. we have tested a cloned amylase gene from the ruminal strain s. bovis jb1 as a potential dna probe for rapid and accurate identification of s. bovis strains from all sources. dnas from strains identified as s. bovis, of both human and ruminal origin, were found to hybridize with the probe under stringent conditions. the probe also hybridized with variants of s. bovis that did not grow on starch. the probe did not hybridize with dna isolated from other bacteria of human colonic and ruminal origin, including bacteroides thetaiotaomicron, bacteroides ruminicola, butyrivibrio fibrisolvens, and enterococcus faecalis but  did demonstrate hybridization with streptococcus salivarius.
TIHT== 
ABHT== 

PMID== 1357000
TI  == restriction fragment length polymorphism analysis of 16s ribosomal dna of streptococcus and enterococcus species of bovine origin.
AB  == twelve bacterial species including streptococcus uberis, s. parauberis, s. agalactiae, s. dysgalactiae, s. bovis, s. mitis, s. salivarius, s. saccharolyticus, enterococcus faecium, e. faecalis, e. avium, and aerococcus viridans were examined for their 16s ribosomal dna fingerprint patterns. oligonucleotide primers complementary to 16s rrna genes were used to amplify by the polymerase chain reaction 16s ribosomal gene fragments from genomic dnas. the molecular sizes of the amplified 16s ribosomal dna (rdna) fragments from the 12 species examined ranged from 1,400 to 1,500 bp. restriction fragment length polymorphism analysis of 16s rdna was performed with 11 different restriction endonucleases. all 12 species examined could be differentiated on the basis of characteristic 16s rdna fingerprint patterns by using the restriction endonucleases hhai, rsai, and mspi. a scheme for the differentiation of the 12 species is presented. eleven isolates representing 11 species were obtained from  cows with intramammary infections and were examined by 16s rdna fingerprinting. all 11 species isolated from cows were differentiated by using hhai, rsai, and mspi restriction endonucleases. the results of this study demonstrate the potential application of 16s rdna fingerprinting for the identification and differentiation of bacterial species.
TIHT== 
ABHT== 

PMID== 1399908
TI  == the distribution of homologous enterococcal plasmid dna sequences in human faecal isolates.
AB  == hybridization was used to investigate the distribution of enterococcal plasmid sequences among 306 strains of enterococcus and streptococcus spp. isolated from  faeces of humans of various ages. as dna probes for the survey three plasmids, whose dnas did not hybridize each other and designated as pms13, ptw34 and phk30, were selected from plasmids borne in ent. faecalis. ptw34 dna hybridized only with dnas from enterococci, with high frequency in ent. faecalis and low frequency in ent. faecium. pms13 dna hybridized with dnas of all enterococcus spp. tested and with strep. bovis, strep. equinus and strep. salivarius. eighty-five percent of ent. faecium isolates had sequences homologous to pms13 but in the other species the values were less than 60%. some enterococci had dnas which hybridized with the phk30 probe. the different distribution of the three dna sequences indicates the possibility that plasmid dnas encode advantageous phenotypes for the colonization of bacteria in the lumen of the bowel.
TIHT== 
ABHT== 

PMID== 1882265
TI  == streptococcus salivarius meningitis and colonic carcinoma.
AB  == streptococcus salivarius caused fulminant meningitis in an elderly patient. a gastrointestinal diagnostic workup revealed an asymptomatic colonic adenocarcinoma. this first reported instance of s salivarius sepsis associated with a colonic neoplasm is not unexpected, since the organism is bacteriologically similar to s bovis, the prime bacterial indicator of occult malignancy. exact speciation of streptococcal strains is fraught with technical difficulties, and gastrointestinal investigation may be warranted in an expanded  variety of streptococcal infections.
TIHT== 
ABHT== 

PMID== 1764502
TI  == the presence of two forms of the phosphocarrier protein hpr of the phosphoenolpyruvate:sugar phosphotransferase system in streptococci.
AB  == the protein, hpr, a necessary component of the phosphoenolpyruvate phosphotransferase system (pts) in bacteria, was purified from streptococcus salivarius by column chromatography. the purified preparation gave only one band  when analyzed by sodium dodecylsulfate gel electrophoresis or by isoelectric focusing in polyacrylamide gel (pi = 4.85). however, electrophoresis in tris-containing buffers under non-denaturing conditions revealed 2 bands that could be phosphorylated by pep in the presence of enzyme i of the pts or by atp with the hpr kinase. homogeneous preparations of these 2 forms could be obtained  by preparative electrophoresis. each preparation exhibited only 1 band when analyzed by electrophoresis under non-denaturing conditions, indicating that the  doublet observed before preparative electrophoresis was not an electrophoretic artefact. the electrophoretic mobility of each protein was not modified following heat-treatment at 100 degrees c for 20 min or storage at -40 degrees c for several months. both hpr proteins catalyzed in vitro the pep-dependent phosphorylation of glucose, but at a rate slightly lower than that observed with  a preparation of hpr containing both forms of the protein. both forms were also able to transfer the phosphate group from pep to the other specific pts proteins  known in s salivarius. rabbit polyclonal antibodies directed against each form reacted with both proteins. the presence of the 2 forms of hpr was detected in fresh cellular extracts of s salivarius; however, their intracellular ratio varied according to growth conditions. a doublet was also found in many other streptococcal species tested (s mutans, s sobrinus, s sanguis, s thermophilus, s  bovis, s rattus) and also in l lactis.(abstract truncated at 250 words)
TIHT== 
ABHT== 

PMID== 2344292
TI  == in vivo dental plaque-forming ability and cariogenicity of the bacterium streptococcus bovis in gnotobiotic rats.
AB  == germ-free fisher rats, fed on a high sucrose diet, were monoinfected with streptococcus bovis strains. high levels of fissure caries were formed by three strains; one strain produced moderate levels; another produced only very low levels. no strain could produce approximal or buccal/lingual lesions. all strains could colonize the fissures of teeth in the lower jaw, as shown by scanning electron microscopy. the most cariogenic strains were associated with caries scores similar to those of strep. salivarius and members of the mutants streptococci.
TIHT== 
ABHT== 

PMID== 2640315
TI  == electrophoretic analysis of ureases in streptococcus salivarius and in saliva.
AB  == experimental conditions were established for the extraction, electrophoresis and  detection of urease isoenzymes from streptococcus salivarius. thiol concentrations were critical and ureases from different strains varied in ease of dissociation. a characteristic pattern was obtained for 30 ureolytic s. salivarius strains isolated from; saliva (6), dental plaque (12), artificial dental plaque (6) and non-oral sources (6), and also for a ureolytic streptococcus bovis from artificial plaque. one non-oral s. salivarius strain had ureases with slightly slower mobility. the electrophoretic pattern and mobility of ureases extracted from human mixed salivary bacteria were identical to those from s. salivarius except for an additional set of urease bands from unknown species of bacteria. there were no ureases from saliva matching those from staphylococcus epidermidis--a contributor to ureolysis in artificial plaque. we conclude that there is considerable biochemical homogeneity among s. salivarius ureases and possibly other ureolytic streptococci. in saliva, urea is metabolized mainly by streptococcal ureases.
TIHT== 
ABHT== 

PMID== 2636256
TI  == properties of a phosphocarrier protein (hpr) extracted from intact cells of streptococcus sanguis.
AB  == cells of streptococcus sanguis strain challis were incubated with sodium lauroylsarcosinate to extract surface proteins. a polypeptide of apparent molecular mass 16 kda comprising about 12% of the extract was purified using anion-exchange chromatography. the polypeptide was shown to be a phosphocarrier protein (hpr) that could also be found in the soluble (cytoplasmic) fraction from cells broken by homogenization with glass beads. in vivo labelling of s. sanguis  cells with 32pi showed that the polypeptide carried a heat- and acid-stable phosphorylation and that during sucrose starvation the hpr became dephosphorylated. antiserum raised to the s. sanguis hpr reacted on western blots with hprs from all oral streptococci tested, together with strains of s. pyogenes and s. salivarius, but not with hprs from s. faecalis or s. bovis, nor with proteins from staphylococcus aureus, bacillus subtilis, actinomyces viscosus and  various lactobacilli. the s. sanguis hpr had a high content of alanine (17.2%) and was similar in overall amino acid composition to the hprs from s. mutans an s. salivarius. the n-terminal residues (to 37) of the s. sanguis hpr showed strong sequence identity (82%) with the n-terminal sequence of s. faecalis hpr. it is suggested that hpr in s. sanguis is associated closely with the cytoplasmic membrane. non-disruptive methods of removing cell-surface proteins from streptococci effect release of hpr and possibly other cytoplasmic components.
TIHT== 
ABHT== 

PMID== 2649679
TI  == a physiological classification of viridans streptococci by use of the api-20strep system.
AB  == physiological reactions of viridans streptococci were examined by the api-20strep system and a selection of conventional tests. cluster analysis of these results produced a classification similar to a taxonomic scheme based on that of colman and williams. the organisms could be divided into the six recognised species--streptococcus mutans, s. bovis, s. mitior, s. sanguis, s. salivarius and s. milleri. analysis confirmed that s. mitior and s. sanguis can be distinguished in the api-20strep test by hydrolysis of arginine but not by dextran production.  although s. mutans, s. mitior and s. sanguis can be divided into two further subgroups, the taxonomic significance of this is unclear. with this means of classification, most organisms could be identified easily by a small number of tests. api-20strep is convenient for performing physiological tests on viridans streptococci, but the information provided by the manufacturers in regard to identification and nomenclature is in need of revision.
TIHT== 
ABHT== 

PMID== 2915024
TI  == bacteremia with streptococcus bovis and streptococcus salivarius: clinical correlates of more accurate identification of isolates.
AB  == two biotypes of streptococcus bovis can be identified by laboratory testing and can be distinguished from the phenotypically similar organism streptococcus salivarius. we assessed the clinical relevance of careful identification of these organisms in 68 patients with streptococcal bacteremia caused by these similar species. s. bovis was more likely to be clinically significant when isolated from blood (89%) than was s. salivarius (23%). there was a striking association between s. bovis i bacteremia and underlying endocarditis (94%) compared with that of s. bovis ii bacteremia (18%). bacteremia with s. bovis i was also highly  correlated with an underlying colonic neoplasm (71% of patients overall, 100% of  those with thorough colonic examinations) compared with bacteremia due to s. bovis ii or s. salivarius (17% overall, 25% of patients with thorough colonic examinations). we conclude that careful identification of streptococcal bacteremic isolates as s. bovis biotype i provides clinically important information and should be more widely applied.
TIHT== 
ABHT== 

PMID== 3389348
TI  == identification of viridans streptococci by three commercial systems.
AB  == the api 20s (analytab products, plainview, ny), the gpi card (vitek systems, st.  louis, mo) and the rapstr system (innovative diagnostics, atlanta, ga) were compared with conventional biochemicals for the identification of viridans streptococci. one hundred nine clinical isolates were tested that included the following species: intermedius (38) sanguis ii (20), bovis (variant) (14), mitis  (14), salivarius (11), sanguis i (6), constellatus (3), mutans (2), and uberis (1). with initial testing, a correct species call was made with 72% of the isolates with the gpi card, 62% with the rapstr, and 50% with the api 20s. identifications of viridans streptococci group or those that needed additional biochemicals for species identification occurred with 28% of isolates with the api 20s, 8% with the rapstr, and 9% with the gpi card. incorrect identifications  occurred with 6% of the isolates tested by the gpi card, 20% with the api 20s, and 30% with the rapstr. most discrepancies with the rapstr were with 66% of the  intermedius isolates, whereas most, 55%, of misidentifications with the api 20s were with sanguis ii isolates. no identifications were made with 2% and 13% of isolates with the api 20s and gpi, respectively.
TIHT== 
ABHT== 

PMID== 3216798
TI  == partial characterisation of the inhibitory substances produced by streptococcus oralis and related species.
AB  == the production of inhibitory substances was sought by deferred antagonism. streptococcus oralis, streptococcus mitis and streptococcus sanguis produced bactericidal concentrations of hydrogen peroxide, but no detectable bacteriocin.  actinomycetes and neisseria pharyngis were particularly susceptible to the lethal action of hydrogen peroxide. streptococcus milleri produced bactericidal concentrations of hydrogen peroxide and bacteriocin-like substances. s. oralis strains were inhibited by the bacteriocin-like products of strains of streptococcus bovis, streptococcus faecalis, streptococcus mutans and streptococcus salivarius. inhibition was due neither to complete bacteriophage nor to fermentation end-products. extracellular polysaccharides formed during growth could not protect sensitive strains from the effect of hydrogen peroxide or bacteriocin-like substances.
TIHT== 
ABHT== 

PMID== 3075450
TI  == the bacteria responsible for ureolysis in artificial dental plaque.
AB  == the origin of ureolytic activity in artificial-mouth plaques was established by assessing the contribution to plaque ureolytic activity of the isolated bacteria. to overcome losses of ureolytic activity caused by the unstable presence of urease in oral bacteria, ureolytic bacteria were isolated from an exceptionally active plaque (1 mumol nh3/min per mg protein) in which 63 per cent of the flora  was ureolytic. after their ability to metabolize urea was stabilized, 13 ureolytic bacteria remained: seven strains of streptococcus salivarius, one streptococcus bovis, two staphylococcus epidermidis and three staphylococcus haemolyticus. their urease activity, measured after growth into stationary phase, was reproducible and strain specific with a 20-fold range within each genus. the  mean ureolytic activity of each species, when weighted by its calculated incidence in the original plaque, accounted for 40 per cent of the total plaque ureolytic activity. however, these values for urease levels were only a small fraction of the bacterial ureolytic potential. urease per mg cell protein measured during the growth cycle of a selected strep. salivarius, and staph. epidermidis, varied 10-fold, and reached much higher activities (i.e. 6-8 mumol nh3/min per mg of cell protein) than under the growth conditions that were used to assess the contribution of these species to total plaque ureolysis. thus urea  metabolism in artificial plaque was due mainly to strep. salivarius, with a small contribution from staph. epidermidis. the presence of further unidentified species of ureolytic oral bacteria need not be invoked.
TIHT== 
ABHT== 

PMID== 2965127
TI  == bactericidal activity of teicoplanin in an in-vitro two-compartment kinetic model.
AB  == the bactericidal activity of teicoplanin was studied in a model system in which antibiotic concentration is continuously varied. a two-compartment open model was used to reproduce, in vitro serum pharmacokinetics of teicoplanin in humans during 24 h after iv administration. staphylococcal and streptococcal strains of  various species were tested. teicoplanin showed rapid killing of staphylococcus epidermidis and staph. hominis. all strains of staph. epidermidis were rapidly killed in spite of the high mic values (4-16 mg/l). the killing effect against staph. haemolyticus was less rapid and marked than against staph. epidermidis, with strain to strain variation. a 99.9% kill was achieved for most strains within 22 h, but with other isolates regrowth occurred which was due to the presence of highly resistant cells in the original population. other staphylococci (staph. aureus, staph. saprophyticus) and streptococcus pyogenes, str. bovis and str. salivarius were reduced by 99.9% within 22 h. bactericidal activity against other streptococci (str. mutans, str. agalactiae, str. faecalis, str. faecium) was less marked; against str. sanguis teicoplanin was bacteriostatic.
TIHT== 
ABHT== 

PMID== 4030098
TI  == growth inhibition of streptococcus mutans by cellular extracts of human intestinal lactic acid bacteria.
AB  == the in vitro growth of streptococcus mutans was completely inhibited by water-soluble extracts from cells of various intestinal lactic acid bacteria identified as streptococcus faecium, streptococcus equinus, lactobacillus fermentum, and lactobacillus salivarius. the growth inhibition was dependent on the concentrations of the extracts. in contrast, the extracts did not inhibit the growth of the major indigenous intestinal lactic acid bacteria isolated from humans. these lactic acid bacteria were not acutely toxic in mice.
TIHT== 
ABHT== 

PMID== 3889046
TI  == cross-reactions between alpha-streptococci and omniserum, a polyvalent pneumococcal serum, demonstrated by direct immunofluorescence, immunoelectroosmophoresis, and latex agglutination.
AB  == in recent years several groups have used serological methods to demonstrate pneumococcal capsular antigens in sputum. in the present study 123 strains of alpha-hemolytic streptococci (including 97 strains from sputum or pharyngeal specimens) were tested for cross-reactions with a polyvalent antipneumococcal serum (omniserum). representatives of the following species were included: streptococcus bovis, s. equinus, s. intermedius, s. lactis, s. milleri, s. mitis, s. mutans, s. sobrinus, s. salivarius, s. sanguis, s. suis, and aerococcus viridans. serological reactions were detected by direct immunofluorescence, immunoelectroosmophoresis, and latex agglutination. fifteen (12%) of the strains  gave positive reactions by all three methods. positive reactions were also observed with another 32 strains (26%) with two of the methods, whereas 37 strains (30%) gave positive reactions by just one technique. altogether 84 (68%)  strains gave positive reactions with one or more of the methods. latex agglutination gave positive reactions with 26 (21%) strains compared with 57 (46%) in immunofluorescence and 63 (51%) in immunoelectroosmophoresis. absorption of the antiserum with one alpha-hemolytic strain reduced but did not entirely eliminate the cross-reactions with five tested strains. these findings indicate a potential risk of cross-reactions with polyvalent antipneumococcal serum in tests carried out on sputa or other specimens which may be contaminated with alpha-hemolytic streptococci.
TIHT== 
ABHT== 

PMID== 2410543
TI  == the phylogenetic position of streptococcus and enterococcus.
AB  == streptococcus pyogenes, s. equinus, s. bovis, s. salivarius, s. sanguis, s. mutans, s. rattus, s. cricetus, s. lactis, s. raffinolactis and enterococcus faecalis have been characterized by oligonucleotide cataloguing of their 16s ribosomal rna. all the organisms form a loose but coherent group that is phylogenetically equivalent to those of lactobacilli, bacilli, the brochothrix and listeria group, and related taxa that constitute one of several sublines within the 'clostridium' branch of gram-positive eubacteria. within the steptococcus-enterococcus group, organisms fall into three moderately related clusters defined by enterococcus, the lactic acid streptococci and streptococci of the pyogenic and oral groups, respectively.
TIHT== 
ABHT== 

PMID== 6490838
TI  == evaluation of a rapid latex agglutination test for identification of group d streptococci.
AB  == the serostat latex agglutination test (scott laboratories, inc., fiskesville, r.i.) for identification of group d streptococci was compared with bile-esculin agar and lancefield grouping by using 110 clinical isolates of group d streptococci (s. faecalis, 74; s. bovis, 24; s. durans, 3; s. faecium, 9) and 65  viridans streptococci (s. anginosus-constellatus, 2; streptococcus mg, 15; s. sanguis ii, 14; s. mitis, 7; s. mutans, 5; s. salivarius, 8; s. sanguis i, 8; s.  acidominimus, 1; s. morbillorum, 2; s. pneumoniae, 3). all strains of group d streptococci were bile-esculin positive. serostat reactions were falsely positive with 2 strains of s. sanguisii and 1 strain of streptococcus mg (4.6% of all viridans streptococci tested) and falsely negative with 10 s. bovis, 8 s. faecalis, 1 s. durans, and 6 s. faecium strains (22.7% of all group d streptococci tested). when considered with colonial morphology and hemolytic reaction, serostat is a rapid (60-s) and useful test for recognition of group d streptococci.
TIHT== 
ABHT== 

PMID== 6490816
TI  == identification of streptococcus bovis and streptococcus salivarius in clinical laboratories.
AB  == streptococci identified as streptococcus bovis, s. bovis variant, and streptococcus salivarius were examined with respect to physiological and serological characteristics and cellular fatty acid content. similarities in physiological reactions and problems encountered in serological analysis were noted, suggesting that an expanded battery of physiological tests is needed to definitively identify these streptococci. cellular fatty acid analysis provided an accurate method for distinguishing s. salivarius from s. bovis and s. bovis variant.
TIHT== 
ABHT== 

PMID== 6410069
TI  == streptococci isolated from the bloodstream and gingival crevice of man.
AB  == one hundred and twenty six strains of streptococci isolated from the bloodstreams of 123 hospital in-patients--55 with endocarditis--and 255 strains isolated from  the gingival crevices of 66 volunteers were characterised. species isolated were  streptococcus mitior, s. sanguis, undifferentiated viridans streptococci, s. salivarius, s. milleri, s. mutans, s. bovis and s. faecalis. there was no significant difference between the distribution of species in blood and in the gingival crevice. s. mitior and s. sanguis were found less frequently in blood than their presence in the gingival crevice would have suggested, whereas s. milleri was found more frequently. this may indicate that s. milleri is more invasive or that it enters the bloodstream from sources other than the gingival crevice.
TIHT== 
ABHT== 

PMID== 6840832
TI  == purification and properties of pyruvate kinase from streptococcus sanguis and activator specificity of pyruvate kinase from oral streptococci.
AB  == it was found that pyruvate kinases with two different regulatory characteristics  were distributed among oral streptococci. the pyruvate kinases of streptococcus mutans, streptococcus salivarius, and streptococcus bovis were activated by glucose 6-phosphate, whereas the enzymes of both streptococcus sanguis and streptococcus mitis were activated by fructose 1,6-bisphosphate. pyruvate kinase  (ec 2.7.1.40) from s. sanguis nctc 10904 was purified, giving a single band on sodium dodecyl sulfate-polyacrylamide gel electrophoresis. the enzyme had a molecular weight of 250,000 to 260,000 and consisted of four identical subunits.  whereas the pyruvate kinase from s. mutans was completely dependent on glucose 6-phosphate (k. abbe and t. yamada, j. bacteriol. 149:299-305, 1982), the enzyme  from s. sanguis was activated by fructose 1,6-bisphosphate. in the presence of 0.5 mm fructose 1,6-bisphosphate, the saturation curves for the substrates, phosphoenolpyruvate and adp, were hyperbolic, and the km values were 0.13 and 0.30 mm, respectively. without fructose 1,6-bisphosphate, however, saturation curves for both substrates were sigmoidal. gdp, idp, and udp could replace adp. like the enzyme from s. mutans, the enzyme from s. sanguis required a divalent cation, mg2+ or mn2+, and a monovalent cation, k+ or nh4+, for activity, and it was strongly inhibited by pi. when the concentration of pi was increased, the half-saturating concentration and hill coefficient for fructose 1,6-bisphosphate  increased. the remarkable fluctuation of intracellular levels of fructose 1,6-bisphosphate and phosphoenolpyruvate observed in the cells growing under glucose limitation and nitrogen limitation implies that the intracellular concentration of fructose 1,6-bisphosphate, in cooperation with that of pi, may regulate pyruvate kinase activity in s. sanguis in vivo.
TIHT== 
ABHT== 

PMID== 6409982
TI  == numerical taxonomy of streptococcus.
AB  == a numerical taxonomic study of strains of streptococcus, together with representatives of allied genera, showed 28 reasonably distinct phenons. the major areas, with their phenons, were: (a) enterococcal species group (s. faecalis, s. faecium, 's. avium' and a proposed new species 's. gallinarum'); (b) paraviridans species group (s. bovis, s. equinus, s. salivarius, 's. casseliflavus', s. mutans, s. raffinolactis and an unidentified oral group i); (c) lactic species group (s. lactis including s. cremoris); (d) thermophilic species group (s. thermophilus); (e) viridans species group (s. mitis, s. sanguis, a proposed new species 's. oralis' and 's. milleri'); (f) pyogenic species group (s. agalactiae, s. pyogenes, s. equi, 's. equisimilis' including 's. zooepidemicus, and a cluster of lancefield group b strains of human origin);  (g) parapyogenic species group (s. uberis, 's. dysgalactiae', and a cluster of strains of lancefield groups r, s and t). species of aerococcus, gemella, leuconostoc and pediococcus are very closely related to the streptococci.
TIHT== 
ABHT== 

PMID== 6830220
TI  == fluorogenic selective and differential medium for isolation of fecal streptococci.
AB  == of 44 fluorogenic substrates tested for their ability to differentiate species of fecal streptococci, four yielded species-differentiating reactions. the remaining substrates either yielded uniformly positive, negative, or variable strain-dependent reactions. one substrate, 4-methylumbelliferone-alpha-d-galactoside, was hydrolyzed by streptococcus bovis  and s. faecium and its biotypes. 4-methylumbelliferone-alpha-d-galactoside and a  colorimetric starch substrate were incorporated into the fecal streptococcal selective medium of donnelly and hartman (appl. environ. microbiol. 35:576-581, 1978). three phenotypic groups were identifiable on the new fluorescent gentamicin-thallous-carbonate agar: (i) starch hydrolysis and fluorescence (s. bovis), (ii) no starch hydrolysis but fluorescence (s. faecium and its biotypes), and (iii) no starch hydrolysis or fluorescence (s. faecalis, s. avium, s. equinus, s. mitis, and s. salivarius). of the presumptive identifications from sewage, swine, and bovine samples, 86% were confirmed as being correct. the new medium has potential application in water, food, environmental, and possibly clinical microbiology.
TIHT== 
ABHT== 

PMID== 6823904
TI  == the clinical significance of streptococcal species isolated from cerebrospinal fluid.
AB  == alpha-hemolytic (viridans) streptococci are often isolated from cerebrospinal fluid (csf); however, the significance of such isolates is poorly understood. in  order to clarify the clinical significance of isolating these organisms from csf, we did a retrospective analysis of 43 patients, from whom eight different species of alpha-hemolytic streptococci were recovered. eight patients (19%) had significant infections based on bacteriologic, laboratory, and clinical findings. significant infections were associated with s. sanguis, s. salivarius, s. intermedius, s. faecalis, and s. bovis. thirty-five patient isolates (81%) from csf were considered as contaminants, with s. mitis being the most frequently isolated organism (49%). direct gram stain of csf sediment, csf glucose concentration, and csf cell differential were clearly abnormal in most patients with significant infections, in contrast to patients with streptococci isolated as contaminants. cultures of the lumbar puncture skin site yielded streptococci and other bacteria, suggesting a possible reservoir for contaminants.
TIHT== 
ABHT== 

PMID== 7068219
TI  == purification and certain properties of a bacteriocin from streptococcus mutans.
AB  == an inhibition factor from streptococcus mutans strain c3603 (serotype c) was purified and isolated, and its properties indicated that it was a bacteriocin. bacteriocin c3603 is a basic protein with a pi value of 10 and a molecular weight of 4,800. the activity of this bacteriocin was not affected by ph over a range of 1.0 to 12.0 or by storage at 100 degrees c for 10 min at ph 2.0 to 7.0 or storage at 121 degrees c for 15 min at ph 4.0. pronase; papain, phospholipase c, trypsin, and alpha-amylase had no effect on the activity of the bacteriocin, whereas alpha-chymotrypsin and pancreatin were partially active against it. bacteriocin activity was greater against certain s. mutans strains of serotypes b, c, e, and  f than against certain s. mutans strains of serotypes a, d, and g. bacteriocin c3603 was also effective against selected strains of s. sanguis, s. salivarius, s. bovis, s. faecium, s. lactis, lactobacillus casei, l. plantarum, l. fermentum, bifidobacterium bifidum, bifidobacterium longum, propionibacterium acnes, and bacteroides melaninogenicus, but it was not effective against certain strains of  escherichia coli, klebsiella pneumoniae, corynebacterium parvum, and candida albicans. the inhibition of s. mutans strains bht and ps-14 by bacteriocin c3603  was found to be due to the bacteriocidal activity of the bacteriocin. when water  or a diet containing bacteriocin c3603 was consumed by gnotobiotic and specific pathogen-free rats infected with s. mutans ps-14, the caries score was found to be significantly reduced.
TIHT== 
ABHT== 

PMID== 6784389
TI  == [observations on the fecal streptococcal flora in carnivorous domestic animals (author's transl)].
AB  == from 1200 feces-samples streaks of carnivorous domestic animals (1027 from dogs,  173 from cats) 744 streptococci-strains were isolated and differentiated. 87% proved their, self to be streptococcus group d/enterococcus, 13% falled to 11 others species, much-numerous represented streptococci of viridans-group (sc. mg, sc. milleri, sc. salivarius, sc. viridans), sc. group g (beta-hemolytic biotypes) and sc. lactis (group n). among the group d-spezies the most showed species at dogs was sc. bovis (35%), retinued by sc. faecium and sc. durans (ever about 18%) and the both sc.-faecalis-sub-spezies var. liquefaciens and var. faecalis (ever about 8%). at cats, the relation respecting to group d-shares, especially of sc.  bovis, were strong varying. all together an interesting survey on the qualitative composition of the streptococcal flora in dog- and cat-intestine was obtained.
TIHT== 
ABHT== 

PMID== 7253964
TI  == studies on streptococci. i. distribution of fecal streptococci in man.
AB  == to understand the significance to the host of streptococci as part of the intestinal microflora, we first tried to investigate the distribution of human fecal streptococci on the species level. of the selective media compared, kmn agar was more effective than the other media for the isolation of streptococci from human feces. we made an effort to improve streptococcal classification. especially we used utilization of 1% pyruvate, 1% arginine, and 1% citrate for differentiation between streptococcus faecalis and s. faecium. in a tellurite tolerance test, s. faecalis was distinguished more clearly from s. faecium in the medium containing 0.16 or 0.32% tellurite. we devised methods of presumptive identification of fecal streptococci from the results of the characteristics of 1,442 isolates. these methods enabled us to identify many strains rapidly. different results in the distribution of species of streptococci between children and adults were observed. s. faecalis and s. faecium were isolated constantly from both groups. s. bovis and s. avium were isolated frequently from the feces of children. on the other hand, "viridans" streptococci, e.g. s. salivarius, s. mitis and s. mg-intermedius were present at a high frequency in, and no s. avium  could be isolated from, the feces of adults.
TIHT== 
ABHT== 

PMID== 7011510
TI  == comparison of selective media for the enumeration and identification of fecal streptococci from natural sources.
AB  == five media and procedures were compared for their recovery of fecal streptococci  on membrane filters. growth and numbers of a variety of pure cultures were compared, and recoveries from raw sewage and sewage effluent were determined on the five media. a total of 512 isolates were identified and the specificity of each medium was determined from these results. while ke agar recovered significantly higher numbers of organisms, only 81% of the positive colonies were fecal streptococci. slanetz and bartley (sb) medium showed similarly low specificity and the me procedure gave low recoveries. best overall results were obtained on menterococcus (ment) agar with high (91%) specificity for enterococci, and very good recovery efficiency with low background counts. this medium was also the only one demonstrating any appreciable recovery of other fecal streptococci with 93% of the background colonies being confirmed as fecal streptococci which most were streptococcus bovis, s. equinus, or s. salivarius. pfizer selective enterococcus (pse) agar was second in overall performance with a high (94%) rate of specificity but this medium had lower recovery efficiency and  high background counts. performance of pse agar could be considerably improved, without impairing specificity, by using a total count disregarding esculin hydrolysis.
TIHT== 
ABHT== 

PMID== 637551
TI  == bacteria associated with the gastric epithelium of neonatal pigs.
AB  == light and electron microscopy showed lactobacilli and, to a lesser degree, streptococci to be closely associated with the squamous area of the pig stomach known as the pars esophagea. several different types of extracellular layers were seen on bacteria attached to the epithelial surface. the total number of bacteria per square centimeter did not change with age up to 10 days, and there was no effect of weaning at 2 days. lactobacillus fermentum, l. salivarius, and streptococcus salivarius were isolated more frequently from sucking pigs than from those that were early weaned, whereas the reverse was true of l. acidophilus and s. bovis. all isolates recovered from washed macerated pars esophagea adhered to pig esophageal epithelial cells when tested in vitro.
TIHT== 
ABHT== 

PMID== 22491
TI  == binding of lectins to streptococcus mutans cells and type-specific polysaccharides, and effect on adherence.
AB  == the lectin concanavalin a (con a) agglutinated the cells of 13 of 15 strains of the seven serotypes of streptococcus mutans in an 18-h incubation period. strains of types a, d, f, and g agglutinated within 2 h. strains of a, d, and f were also agglutinated in 2 h by the castor bean lectin rca. s. sanguis, s. salivarius, s.  bovis, actinomyces viscosus, a. naeslundii, and lactobacillus plantarum were agglutinated within 2 h. the s. mutans type f polysaccharide was precipitated by  con a. the a, b, c, d, and e polysaccharides were not precipitated. glucan from d and e strains of s. mutans and dextran t2000 were also precipitated by con a. d-glucose inhibited the agglutination of type f cells by con a and the agglutination of type d cells by d-galactose. the quantity of [acetyl-3h]con a bound was not proportional to the degree of agglutination. cells grown in sucrose medium bound more con a than those grown in glucose medium. after treatment with  dextranase, the sucrose-grown cells bound two- to fourfold more con a. the binding of con a to the type-specific polysaccharide or to teichoic acid could not be determined by the use of specific antibody due to the binding of con a to  the antibody globulin on the cell surface. con a bound to s. mutans cells did not inhibit the activity of cell-bound glucosyltransferase, glucan synthesis, and in  vitro adherence. bound con a also did not inhibit the ability of heat-treated cells to bind glucosyltransferase, synthesize glucan, and produce in vitro adherence.
TIHT== 
ABHT== 

PMID== 22488
TI  == changes in the microflora and physiology of the anterior intestinal tract of pigs weaned at 2 days, with special reference to the pathogenesis of diarrhea.
AB  == the gastrointestinal microflora and gastric physiology of piglets weaned at 2 days was compared with that of piglets allowed to continue sucking the sow. although there was a significantly higher count of escherichia coli in the stomach, duodenum, and jejunum of the early-weaned compared with sow-reared pigs, these differences were not detectable in samples from the ileum. there were no quantitative differences in lactobacilli and in streptococci between the two treatments. lactobacillus fermentum, l. acidophilus, streptococcus salivarius, s. bovis, and related biotypes were isolated from both groups of pigs. l. fermentum  and s. salivarius were isolated more frequently from sow-reared piglets. the weight of digesta in the stomach was greater in weaned than in sucking pigs and was even greater in scouring weaned pigs, suggesting that in scouring pigs there  may be gastric stasis. the gastric ph was higher in the weaned pigs at 4 days of  age, but gradually decreased up to 10 days, during which time the lactic acid concentration rose. in weaned pigs there was a highly significant negative correlation between ph and lactic acid concentration in the stomach digesta, and  also a positive correlation between ph and number of e. coli. these correlations  suggest that lactic acid, from bacterial fermentation, is the major component in  the regulation of gastric ph in weaned pigs. three of twenty sucking pigs, but none of the weaned pigs, were secreting hcl (chloride concentration > 3 mg/g, ph  < 3.5). in sucking pigs there was an inverse relationship between the chloride and lactic acid concentrations in the digesta. in weaned scouring pigs there was  a nonsignificant increase in pepsin concentration in the stomach tissue. there was a threefold increase in the total proteolytic activity of the stomach tissue.
TIHT== 
ABHT== 

PMID== 272380
TI  == the effect of adsorption on the acid production of caries and noncaries-producing streptococci.
AB  == eighteen different streptococcus strains including s mutans, sanguis, mitis, salivarius, bovis, and 2f2, were assayed for their relative adsorption to synthetic hydroxyapatite and for quantities of lactic acid produced while in the  adsorbed state. the results indicated that all s mutans and some s sanguis have an enhanced metabolic activity while adsorbed to hydroxapatite as compared to control suspensions without hydroxyapatite.
TIHT== 
ABHT== 

PMID== 1015013
TI  == susceptibility of viridans streptococci of 27 antimicrobial agents.
AB  == one hundred and eighty strains of viridans streptococci (str. mitis, str. salivarius, str. mg, str. sbe, str. bovis, str. equinus and str. uberis) were isolated from mouth and upper respiratory tract secretions of humans at random in different parts of poland. these strains were tested for susceptibility to 27 antimicrobial agents. analysis of results was performed with special reference to bacterial endocarditis, which is caused mostly by these microorganisms. at low minimal inhibitory concentrations, most effective antibiotics appeared amoxycillin, clindamycin, azidocillin, cephaloridine, ampicillin, erythromycin and penicillin g. susceptibility to other penicillins and cephalosporins was much less pronounced. small part of strains was highly susceptible to tetracyclines, whereas all other antimicrobial agents were practically ineffective.
TIHT== 
ABHT== 

PMID== 819936
TI  == arthritogenicity in rats of cell walls from several streptococci staphylococci and two other bacteria.
AB  == bacterial cell walls from str. bovis, str. lactis, str. mutans, str. thermophilus, str. salivarius, and str. pyogenes were able to produce polyarthritis in rats but str. faecalis cell walls were nonarthritogenic. s. aureus cell walls produced extremely severe disease. it was also shown that cell  walls from s. epidermidis, b. megaterium, and m. lysodeikticus were nonarthritogenic. a close correlation was observed between development of arthritis and the delayed hypersensitivity to bacterial peptidoglycans but not with the ppd hypersensitivity. it was suggested that the adjuvanticity of bacterial cell walls is needed to induce the disease and that arthritogenicity requires a specific antigen in addition to the presence of an adjuvant-inducing agent.
TIHT== 
ABHT== 

PMID== 240810
TI  == glucose-6-phosphate-dependent pyruvate kinase in streptococcus mutans.
AB  == pyruvate kinase of streptococcus mutans jc 2 had an absolute and specific requirement for glucose-6-phosphate. inorganic phosphate was a strong inhibitor.  the enzyme required k+ or nh4+ and mg2+ or mn2+. s. mutans fil and e 49, streptococcus bovis atcc 9809, and streptococcus salivarius atcc 13419 had also glucose-6-phosphate-dependent pyruvate kinases, whereas streptococcus sanguis nctc 10904 had an enzyme activated by fructose-1,6-diphosphate.
TIHT== 
ABHT== 

PMID== 807165
TI  == membrane filter technique for enumeration of enterococci in marine waters.
AB  == a membrane filter procedure is described for the enumeration of enterococci in marine waters. the procedure utilizes a highly selective and somewhat differential primary isolation medium followed by an in situ substrate test for identifying colonies of those organisms capable of hydrolyzing esculin. the procedure (me) was evaluated with known streptococci strains and field samples with regard to its accuracy, sensitivity, selectivity, precision, and comparability to existing methods. essentially quantitative recovery was obtained with seawater-stressed cells of streptococcus faecalis and s. faecium. neither s. bovis, s. equinus, s. mitis, nor s. salivarius grew on the medium. the selectivity of the medium was such that a 10,000-fold reduction in background organisms was obtained relative to a medium which contained no inhibitors and was incubated at 35 c. about 90% of those typical colonies designated as enterococci  confirmed as such and about 12% of the colonies not so designated were, in fact,  identified as enterococci. plate to plate variability across samples approximated that expected by chance alone. verified recoveries of enterococci from natural samples by the me procedure, on the average, exceeded those by the kf method by one order of magnitude.
TIHT== 
ABHT== 

