@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25946126
TI  == oral microbiota shift after 12-week supplementation with lactobacillus reuteri dsm 17938 and pta 5289; a randomized control trial.
AB  == background: lactobacillus spp. potentially contribute to health by modulating bacterial biofilm formation, but their effects on the overall oral microbiota remain unclear. methods and findings: oral microbiota was characterized via 454-pyrosequencing of the 16s rdna hypervariable region v3-v4 after 12 weeks of daily lactobacillus reuteri dsm 17938 and pta 5289 consumption. forty-four adults were assigned to a test group (n = 22) that received lactobacilli lozenges (108 cfu of each strain/lozenge) or a control group that received placebo (n = 22). presence of l. reuteri was confirmed by cultivation and species specific pcr. tooth biofilm samples from 16 adults before, during, and after exposure were analyzed by pyrosequencing. a total of 1,310,292 sequences were quality filtered. after removing single reads, 257 species or phylotypes were identified at 98.5% identity in the human oral microbiome database. firmicutes, bacteroidetes, fusobacteria, proteobacteria, and actinobacteria were the most abundant phyla. streptococcus was the most common genus and the s. oralis/s. mitis/s. mitis bv2/s. infantis group comprised the dominant species. the number of observed species was unaffected by l. reuteri exposure. however, subjects who had consumed l. reuteri were clustered in a principal coordinates analysis relative to scattering at baseline, and multivariate modeling of pyrosequencing microbiota, and culture and pcr detected l. reuteri separated baseline from 12-week samples in test subjects. l. reuteri intake correlated with increased s. oralis/s. mitis/s. mitis bv2/s. infantis group and campylobacter concisus, granulicatella adiacens, bergeyella sp. hot322, neisseria subflava, and sr1 [g-1] sp. hot874 detection and reduced s. mutans, s. anginosus, n. mucosa, fusobacterium periodicum, f. nucleatum ss vincentii, and prevotella maculosa detection. this effect had disappeared 1 month after exposure was terminated. conclusions: l. reuteri consumption did not affect species richness but induced a shift in the oral microbiota composition. the biological relevance of this remains to be elucidated. trial registration: clinicaltrials.gov nct02311218.
TIHT== 
ABHT== 

PMID== 24579284
TI  == effectiveness of crt at measuring the salivary level of bacteria in caries prone  children with probiotic therapy.
AB  == aim: this irb approved clinical trial was to determine the effect of "over the counter" probiotic supplements on the caries risk test- crt- (ivoclar) results of the oral microflora in high caries risk children. study design: sixty subjects 6  to 12 years old with a caries risk assessment (cambra) of moderate to high (caries prone) were evaluated by an analysis of the difference in the salivary levels of pathogenic bacteria (mutans streptococci and lactobacilli). the subjects were randomly selected by randomizing software and assigned to two diferent groups. group a used periobalance (lactobacilli reuteri-cfu of 200 million) lozenges for 28 days. group b used the evorakids (streptococcus uberis kj2, streptococcus oralis kj3, streptococcus rattus jh1 45, > or = 100 million) probiotics chewable tablets for 30 days. salivary samples were collected then incubated for 48 hours for colony counting and ranking. follow up testing with the crt was performed after 60 days at a follow up visit. results: there was a statistically significant diference in the crt results between the pre and post use of the probiotics. periobalance; sm results t= -6. 78, p< .0001, lactobacilli results t= -5.762, p< .0001, evorakids smresults t= -7.33, p< .0001, lactobacilli results t= -2.952, p= .0068. conclusions: the crt values obtained with caries prone children may be significantly affected by probiotic use. based on this study's results the following conclusions can be made: both evorakids and periobalance affected the crt results by significantly decreasing the number of s. mutans and lactobacilli present in the salivary samples.
TIHT== 
ABHT== 

