@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25651071
TI  == microbiology of pelvic lymphocyst infection after lymphadenectomy for malignant gynecologic tumors.
AB  == background: pelvic lymphocyst infection is a rare complication after lymphadenectomy for malignant gynecologic tumors. although medical therapy is a useful addition to surgical drainage, the appropriate antibiotic regimen is unknown because few studies have examined the causative organisms. the purpose of this case series was to identify the micro-organisms infecting pelvic lymphocysts. methods: this was a single-center, retrospective, case-series review conducted at a tertiary-care cancer center between october 2002 and march 2013. the participants included all patients who experienced their first pelvic lymphocyst infection after undergoing pelvic lymphadenectomy for cervical, endometrial, or ovarian cancer and exhibited positive lymphocyst fluid culture. computed tomography- or sonography-guided percutaneous aspiration procedures were performed to obtain lymphocyst fluid for culture. results: during the study period, 878 patients underwent lymphadenectomy for gynecologic malignant tumors,  and 13 developed a pelvic lymphocyst infection documented microbiologically. cultures identified staphylococcus aureus (three patients), s. epidermidis (one patient), streptococcus agalactiae (three patients), enterococcus (two patients), escherichia coli (one patient), and anaerobic bacteria (three patients). they were all monomicrobial infections. conclusions: our study and other smaller ones  suggest that lymphocyst infections following pelvic lymphadenectomy for malignant gynecologic tumors usually are monomicrobial and caused by gram-positive cocci, including staphylococcus, streptococcus, and enterococcus, and anaerobes such as  bacteroides fragilis. these bacteria should be considered when selecting empiric  antibiotic therapy.
TIHT== 
ABHT== 

PMID== 23118301
TI  == proteolytic activity by multiple bacterial species isolated from chronic venous leg ulcers degrades matrix substrates.
AB  == background: a major feature of chronic wounds is the loss of tissue, with the exposure of dermal components preventing primary closure and leading to bacterial colonization. bacterial colonization has been proposed as one of the common underlying pathologies present in chronic wounds. the objective of this exploratory study was to identify bacteria cultured from chronic venous leg ulcers and test for proteolytic activity that degrades matrix substrates. method: bacteria were isolated, cultured, and identified from six subjects (average age = 62.8 years) over 2-10 months under an approved protocol using swabs and microbiological culture media. proteolytic activity against (a) gelatin, (b) an elastin substrate, and (c) a serine/trypsin-sensitive substrate was determined using a colorimetric plate assay with an elisa plate reader and zymography. results: we identified 13 bacteria that expressed proteolytic activity against one or more of the tested substrates. of these, six were gram-positive (staphylococcus aureus, enterococcus faecalis, staphylococcus epidermidis, streptococcus agalactiae, corynebacterium, and streptococcus bovis) and seven were gram-negative (pseudomonas aeruginosa, escherichia coli, proteus mirabilis,  morganella morganii, klebsiella pneumoniae, bacteroides fragilis, and serratia marcescens) organisms. two of these, s. aureus and p. aeruginosa, are recognized  wound pathogens. conclusions: multiple bacteria species isolated from colonized venous leg ulcers have the capacity to secrete proteases capable of degrading components of the extracellular matrix important for wound healing. matrix degradation by bacteria may contribute to delays in tissue deposition and repair, suggesting that treatment of chronic wounds should include appropriate management of colonizing bacteria.
TIHT== 
ABHT== 

PMID== 22524106
TI  == [possible role of enterotoxigenic bacteroides fragilis in the etiology of infectious vaginitis].
AB  == vaginitis is a common gynecologic disorder. it is due to several causes, some even unknown. bacteroides fragilis is the most important anaerobe in clinical bacteriology, some strains of this group are notable for being enterotoxigenic and they have been associated with intestinal and extraintestinal syndromes. they have recently been isolated from patients with vaginitis. the purpose of this study was to investigate a possible association of enterotoxigenic b. fragilis with infectious vaginitis. 265 samples of vaginal exudate were processed, 202 from symptomatic patients and 63 healthy women. the identification of the microorganisms was carried out by conventional methods. in 31.2% of symptomatic patients were identified: gardnerella vaginalis, mobiluncus, candida albicans, mycoplasma hominis, ureaplasma urealyticum and streptococcus agalactiae. b. fragilis was identified in 27 symptomatic patients and 5 healthy women. these strains were cultivated in liquid medium and incubated during 48 h at 36 degrees  c in anaerobe chambers. supernatant activity was assayed in ht-29 cells. eighteen b. fragilis strains isolated from symptomatic patients were enterotoxigenic, because induced alterations in target cell morphology. it was not identified in healthy women (p < 0.05). 77.7% of enterotoxigenic b. fragilis strains were not associated with other specific pathogens. this fact suggests that enterotoxigenic b. fragilis could be a cause for vaginitis. the effect of enterotoxin on e-cadherin of vaginal epithelium could facilitate invasion and its possible pathogenic role in the vagina. this is the first report that associates enterotoxigenic bacteroides fragilis as a possible cause of infectious vaginitis.
TIHT== 
ABHT== 

PMID== 22517004
TI  == [analysis of diversity of vaginal microbiota in healthy chinese women by using dna-fingerprinting].
AB  == objective: to analyze the diversity of healthy women's vaginal dominant flora in  different physiological states with pcr-denaturing gradient gel electrophoresis (pcr-dgge), to establish the basis for the future study of lower genital tract infections, and to provide a theoretical basis for the development of vaginal probiotics adapted to chinese females. methods: women who underwent routine gynecologic examinations in peking university first hospital from october 2009 to january 2010 were enrolled, including 30 at reproductive age and 30 at post menopause age. vaginal samples were collected and then total bacterial dna was extracted. universal bacterial primers were used to amplify the v3 region of 16s  rdna gene. pcr products were analyzed by denatured gradient gel electrophoresis (dgge). featured bands on dgge were recovered, cloned and sequenced. alignment with known sequence was made by using blast on genbank to identify bacterial strains so as to analyze the diversity of healthy women's vaginal dominant flora  in different physiological states. results: (1) vaginal flora in healthy chinese  women at their reproductive age were relatively simple, lactobacillus were the dominant bacteria. common bacteria included: lactobacillus crispatus, lactobacillus iners,and lactobacillus gasseri. while l. iners were the dominant vaginal bacteria that could not be recognized by traditional method. (2) vaginal  bacteria in the women at post menopause age were more complex than in those at reproductive age. common bacteria included: lactobacillus iners, lactobacillus crispatus, escherichia coli, streptococcus agalactiae, streptococcus gallolyticus, veillonella sp., streptococcus intermedius, streptococcus anginosus, prevotella sp., anaerococcus lactolyticus and bacteroides fragilis. conclusion: based on the dgge analysis, the most common vaginal bacteria in chinese healthy women at reproductive age are lactobacillus crispatus, lactobacillus iners,and lactobacillus gasseri. the most common vaginal bacteria in healthy post-menopausal women are lactobacillus iners, lactobacillus crispatus, escherichia coli, streptococcus sp., prevotella sp.,bacteroides fragilis and lactic acid producing veillonella sp. and anaerococcus lactolyticus. meanwhile lactobacillus iners was firstly found by dgge to be the dominant vaginal bacteria in different physiological states.
TIHT== 
ABHT== 

PMID== 22396824
TI  == predictive factors for lower extremity amputations in diabetic foot infections.
AB  == the objective of this study was to evaluate the epidemiology of diabetic foot infections (dfis) and its predictive factors for lower extremity amputations. a prospective study of 100 patients with dfis treated at the national university hospital of singapore were recruited in the study during the period of january 2005-june 2005. a protocol was designed to document patient's demographics, type  of dfi, presence of neuropathy and/or vasculopathy and its final outcome. predictive factors for limb loss were determined using univariate and stepwise logistic regression analysis. the mean age of the study population was 59.8 years with a male to female ratio of about 1:1 and with a mean follow-up duration of about 24 months. all patients had type 2 diabetes mellitus. common dfis included  abscess (32%), wet gangrene (29%), infected ulcers (19%), osteomyelitis (13%), necrotizing fasciitis (4%) and cellulitis (3%). thirteen patients were treated conservatively, while surgical debridement or distal amputation was performed in  59 patients. twenty-eight patients had major amputations (below or above knee) performed. forty-eight percent had monomicrobial infections compared with 52% with polymicrobial infections. the most common pathogens found in all infections  (both monomicrobial and polymicrobial) were staphylococcus aureus (39.7%), bacteroides fragilis (30.3%), pseudomonas aeruginosa (26.0%) and streptococcus agalactiae (21.0%). significant univariate predictive factors for limb loss included age above 60 years, gangrene, ankle-brachial index (abi) <0.8, monomicrobial infections, white blood cell (wbc) count >/= 15.0x10(9)/l, erythrocyte sedimentation rate >/=100 mm/hr, c-reactive protein >/=15.0 mg/dl, hemoglobin (hb) </=10.0g/dl and creatinine >/=150 micromol/l. upon stepwise logistic regression, only gangrene, abi <0.8, wbc >/= 15.0x10(9)/l and hb </=10.0g/dl were significant.
TIHT== 
ABHT== 

PMID== 20226331
TI  == in vitro activity of tigecycline against patient isolates collected during phase  3 clinical trials for diabetic foot infections.
AB  == the in vitro activity of tigecycline and comparative antimicrobial agents was evaluated against 1828 primary baseline pathogens isolated from 844 patients enrolled in the phase 3 clinical trials investigating the efficacy of tigecycline in diabetic foot infection (dfi). the trials were global, enrolling patients in 30 countries. tigecycline was active against the most prevalent pathogens in dfi, including gram-positive and gram-negative isolates of both aerobic and anaerobic  bacteria with 95% of mics < or =2 microg/ml for the entire collection. the spectrum of activity of tigecycline included important pathogens for dfi, such as staphylococcus aureus, enterococcus faecalis, streptococcus agalactiae, escherichia coli, enterobacter cloacae, klebsiella pneumoniae, and bacteroides fragilis. as reported previously, pseudomonas aeruginosa and several pathogens in the proteeae group were generally less susceptible to tigecycline by comparison to other gram-negative pathogens. the excellent in vitro expanded broad-spectrum  activity of tigecycline in the clinical isolates confirmed the potential utility  of tigecycline for pathogens associated with dfis.
TIHT== 
ABHT== 

PMID== 19223149
TI  == in situ replacement with equine pericardial roll grafts for ruptured infected aneurysms of the abdominal aorta.
AB  == we describe surgical in situ replacement using an equine pericardial roll to treat ruptured infected abdominal aortic aneurysms (aaa) in two patients. a 78-year-old man diagnosed with ruptured infected (bacteroides fragilis) aaa underwent in situ replacement of the abdominal aorta using a bifurcated equine pericardial roll graft with concomitant omentum flap wrapping. a 50-year-old man  diagnosed with ruptured infected (streptococcus agalactiae) aaa underwent the same procedure, except the graft was straight. computed tomography of this patient revealed no graft dilation or surrounding fluid accumulation at 48 months after surgery. we therefore suggest that in situ replacement of the abdominal aorta using equine pericardium with concomitant omental flap wrapping may be an option of treating ruptured infected aaas.
TIHT== 
ABHT== 

PMID== 17428930
TI  == multiplexed identification of blood-borne bacterial pathogens by use of a novel 16s rrna gene pcr-ligase detection reaction-capillary electrophoresis assay.
AB  == we have developed a novel high-throughput pcr-ligase detection reaction-capillary electrophoresis (pcr-ldr-ce) assay for the multiplexed identification of 20 blood-borne pathogens (staphylococcus epidermidis, staphylococcus aureus, bacillus cereus, enterococcus faecalis, enterococcus faecium, listeria monocytogenes, streptococcus pneumoniae, streptococcus pyogenes, streptococcus agalactiae, escherichia coli, klebsiella pneumoniae, haemophilus influenzae, pseudomonas aeruginosa, acinetobacter baumannii, neisseria meningitidis, bacteroides fragilis, bacillus anthracis, yersinia pestis, francisella tularensis, and brucella abortus), the last four of which are biothreat agents. the method relies on the amplification of two regions within the bacterial 16s rrna gene, using universal pcr primers and querying the identity of specific single-nucleotide polymorphisms within the amplified regions in a subsequent ldr. the ligation products vary in color and size and are separated by ce. each organism generates a specific pattern of ligation products, which can be used to  distinguish the pathogens using an automated software program we developed for that purpose. the assay has been verified on 315 clinical isolates and demonstrated a detection sensitivity of 98%. additionally, 484 seeded blood cultures were tested, with a detection sensitivity of 97.7%. the ability to identify geographically variant strains of the organisms was determined by testing 132 isolates obtained from across the united states. in summary, the pcr-ldr-ce assay can successfully identify, in a multiplexed fashion, a panel of  20 blood-borne pathogens with high sensitivity and specificity.
TIHT== 
ABHT== 

PMID== 16192439
TI  == identification and antimicrobial susceptibility of micro-organisms recovered from cutaneous lesions of human american tegumentary leishmaniasis in minas gerais, brazil.
AB  == an evaluation of the microbiota present in cutaneous ulcers from 31 patients with a clinical and parasitological diagnosis of american tegumentary leishmaniasis (atl) was carried out by the standard filter paper disc technique, including antimicrobial susceptibility of the bacterial isolates. microbial examination indicated that 21 patients (67.7%) were contaminated with one to four bacteria and some of them also with yeast. a total of 142 micro-organisms were isolated. staphylococcus aureus was the most frequently recovered bacterium (95.2% of positive patients) and was found to produce type b (70% of the staphylococcal isolates) and type c (50%) enterotoxins as well as toxic shock syndrome toxin (60%). proteus mirabilis (33.3% of the positive patients), streptococcus pyogenes (19.0 %), h(2)s-negative proteus species (19.0%), klebsiella oxytoca (14.3%), enterobacter species (9.5%), peptostreptococcus species (9.5%), pseudomonas species (4.8%), prevotella bivia (4.8%), escherichia coli (4.8%), streptococcus agalactiae (4.8%), bacteroides fragilis (4.8%), candida albicans (9.5%) and candida tropicalis (4.8%) were also isolated. surprisingly, staph. aureus isolates were susceptible to almost all tested drugs, although some of them were  resistant to penicillin (69%) and ampicillin + sulbactam (68%). concerning obligate anaerobes, all the gram-negative isolates (25% of the total) were resistant to metronidazole. the results of the present study show that microbial  secondary contaminants, particularly staph. aureus, should be considered in the diagnosis and treatment of atl lesions.
TIHT== 
ABHT== 

PMID== 15482666
TI  == [rapid diagnosis of neonatal sepsis by 16srrna genes pcr amplification and genechip hybridization].
AB  == objective: to explore a method for rapid diagnosis of sepsis in newborn infants.  methods: (1) the primers and oligonucleotide probes were designed and synthesized based on the sequences of bacterial 16srrna gene. the gene chip was prepared through the probes printed onto special glass slides. the gene chip included 18 special probes: universal probe 1, universal probe 2, gram positive bacterial probe, gram negative bacterial probe 1, gram negative bacterial probe 2, staphylococcus aureus, coagulase negative staphylococcus (cons) 1, cons 2, escherichia coli, hemophilus influenzae, listeria monocytogenes, streptococcus pneumoniae, streptococcus agalactiae, bacteroides fragilis, bacillus, meningococcus, corynebacterium, propionibacterium; (2) blood specimens from 285 cases of suspected septicemia were cultured and bacterial 16s rrna gene was detected separately; dna isolated from blood specimens and cerebrospinal fluid was amplified by pcr, and pcr products were hybridized with the probes on the gene chips. hybridization results were scanned and read by laser-scanner. results: (1) of the 285 cases, 17 were positive by pcr and the positive rate (5.96%) was significantly higher than that of blood culture (2.81%) (p < 0.01). when blood culture was taken as control, the sensitivity of pcr was 100% and specificity was 96.75%, the index of accurate diagnosis was 0.968. (2) the 17 specimens which showed positive results by pcr were further hybridized on the gene chip. all were positive by universal probes. among all of them, 5 were positive by e. coli probe; 4 were positive by staphylococcus epidermidis; two were positive by bacillus and propionibacterium probes, separately; 4 were positive by cons. the 8 specimens which showed positive results by both pcr and blood culture, the result of gene chip hybridization coincided with the result of blood culture. conclusion: detection of the bacterial 16srrna genes in clinical specimens by gene chip hybridization technology can diagnose neonatal septicemia  rapidly. this method has higher sensitivity and specificity than blood culture or other methods and can provide a rapid way for the etiological diagnosis of neonatal septicemia. therefore the genechip method may be valuable and practical  in early diagnosis of neonatal septicemia.
TIHT== 
ABHT== 

PMID== 12714813
TI  == in vitro and in vivo antibacterial activities of telithromycin.
AB  == background: telithromycin is one of the ketolides, characterised by a 3-keto group instead of l-cladinose and a c(11)-c(12) carbamate link by an alkyl chain to a pyridinum and imidazolium ring side chain. we evaluated in vitro and in vivo antibacterial activities of telithromycin against gynaecological pathogens. methods: in the vitro study, the antibacterial activity of telithromycin against  180 isolates (isolated in the year 2000) of streptococcus agalactiae (n = 33), enterococcus faecalis (n = 22), neisseria gonorrhoeae (n = 30), peptostreptococcus anaerobius (n = 20), finegoldia magna (n = 20), bacteroides fragilis (n = 25) and prevotella bivia (n = 30) was compared with that of erythromycin a, clarithromycin, azithromycin, ampicillin and levofloxacin. in the in vivo study, the efficacy of telithromycin was evaluated using experimental intra-abdominal abscesses in mice caused by b. fragilis (minimum inhibitory concentration of telithromycin 0.5 mg/l). results: in the in vitro study, telithromycin inhibited more than 50% of clinical isolates of s. agalactiae, e. faecalis, n. gonorrhoeae, p. anaerobius, f. magna, b. fragilis and p. bivia at concentrations of 0.016, 0.063, 0.063, 0.032, 0.032, 0.5 and 0.25 mg/l, respectively. telithromycin inhibited more than 90% of these clinical isolates at concentrations of 0.016, 4, 0.125, 0.063, 0.063, 4 and 1 mg/l, respectively. in the in vivo study, telithromycin inhibited abscess formation and significantly decreased viable cell counts in abscesses in comparison with the untreated group. conclusions: these in vitro and in vivo antibacterial activities suggest that telithromycin could be a potential candidate for the treatment of bacterial infections complicated by chlamydial infection.
TIHT== 
ABHT== 

PMID== 11750868
TI  == production of pro- and anti-inflammatory cytokines of human placental trophoblasts in response to pathogenic bacteria.
AB  == objective: we studied the production of cytokines in purified cultures of human term trophoblasts in the presence of pathogenic strains of escherichia coli, bacteroides fragilis, mycoplasma hominis, staphylococcus aureus, and streptococcus agalactiae, which have been identified in intrauterine infections.  methods: human villous trophoblasts were isolated from term placentas after cesarean section and purified by several steps. after 6, 12, and 24 hours of incubation with the different heat-inactivated bacteria, interleukin-1beta (il-1beta), interleukin-6 (il-6), interleukin-8 (il-8), and interleukin-10 (il-10) as well as tumor necrosis factor-alpha (tnf-alpha) were measured from supernatants by commercially available enzyme-linked immunosorbent assay. expression of cytokine mrnas was determined by semiquantitative reverse transcriptase polymerase chain reaction (rt-pcr). results: in nonstimulated cultures, low (il-1beta and tnf-alpha) and high (il-6, il-8, and il-10) basal secretion of cytokines was detectable. the pathogenic microorganisms induced a dose- and time-dependent release of il-1beta, il-6, il-8, and il-10, whereas tnf-alpha secretion was not elevated. e coli was the most potent inducer followed by b fragilis, s agalactiae, s aureus, and m hominis. transcripts encoding il-1beta, il-6, il-8, or il-10 were elevated in the rt-pcr reactions, suggesting  that transcriptional mechanisms contribute to elevated cytokine expression. conclusion: pathogenic microorganisms stimulated mrna expression and polypeptide  release of pro- and anti-inflammatory cytokines from placental trophoblasts. induction of both inflammation-promoting and inflammation-inhibiting cytokines by bacterial products could play a role in modulating the inflammatory response associated with chorioamnionitis.
TIHT== 
ABHT== 

PMID== 11070819
TI  == [antibacterial activities of piperacillin in several fresh clinical isolates].
AB  == we investigated activity of piperacillin (pipc) in comparison with 8 antibacterial reference drugs against several fresh clinical strains isolated from patients with infectious diseases in the respiratory tract and after surgical interventions in 1999. the following results were obtained: 1. pipc had  its mic90 of 0.12-6 micrograms/ml in gram-positive bacteria (methicillin susceptible staphylococcus aureus, staphylococcus epidermidis, streptococcus pyogenes, streptococcus agalactiae, streptococcus pneumoniae, enterococcus faecalis) and showed its mic of 1 microgram/ml or higher in 9 possible prsp strains out of 38 isolates of s. pneumoniae but there were no possible isolates with evident resistance in other species of bacteria. 2. pipc showed favorable antibacterial activities as its mic90 were 2-8 micrograms/ml in gram-negative bacteria (escherichia coli, klebsiella pneumoniae, serratia marcescens, citrobacter freundii, pseudomonas aeruginosa, moraxella (branhamella) catarrhalis, haemophilus influenzae), except for p. mirabilis in which its mic90  was as high as 64 micrograms/ml. 11 out of 39 isolates of p. mirabilis were resistant to other drugs such as pipc, abpc, ctm and czop. 3. pipc had its mic90  of > 128 micrograms/ml in bacteroides fragilis. from these results, pipc was considered highly effective in several infections in view of maintaining its favorable antibacterial activities in several causative bacteria even today when  20 years had passed since its first application to clinical practice.
TIHT== 
ABHT== 

PMID== 10980177
TI  == in vitro and in vivo antibacterial activities of a new injectable carbapenem, s-4661, against gynaecological pathogens.
AB  == carbapenems are often used to treat infections in obstetrics and gynaecology because of their activity against anaerobes. s-4661, a new injectable carbapenem  antibiotic, has favourable pharmacokinetic properties and is not hydrolysed by dehydropeptidase i. we investigated the in vitro and in vivo antibacterial activities of s-4661 against strains of streptococcus agalactiae, escherichia coli, peptostreptococcus magnus, bacteroides fragilis and prevotella bivia, which are major pathogens in the fields of obstetrics and gynaecology. the mic(50) and  mic(90) of s-4661 for these strains were 0.25 and 1 mg/l, respectively. the in vivo efficacy of s-4661 was evaluated in a rat model of intrauterine infection, namely pyometra caused by e. coli and b. fragilis. the accumulation of neutrophils in the uterus in the s-4661-treated group was less marked and the number of bacteria significantly lower than those in the untreated group. these results suggest that s-4661 may be useful for treating polymicrobial infections in the fields of obstetrics and gynaecology.
TIHT== 
ABHT== 

PMID== 10671758
TI  == in vitro and in vivo antibacterial activities of biapenem in the fields of obstetrics and gynecology.
AB  == biapenem is a new injectable carbapenem antibiotic which has favorable pharmacokinetic properties, and is stable to hydrolysis by dehydropeptidase i. biapenem inhibited more than 90% of clinical isolates of streptococcus agalactiae, escherichia coli, peptostreptococcus magnus, bacteroides fragilis and prevotella bivia at the concentration of 3.13 mg/l. the mic(90) of biapenem against pseudomonas aeruginosa was lower than that of panipenem, equivalent to that of imipenem, and greater than that of meropenem. the in vivo efficacy of biapenem was evaluated using the experimental infection model of uterine endometritis. the accumulation of neutrophils in the uterus in the biapenem- treated group was less marked than in the nontreated group, as well as bacteriological response. these results suggest that the new antimicrobial agent  biapenem might be useful for the treatment of polymicrobial infections in the fields of obstetrics and gynecology.
TIHT== 
ABHT== 

PMID== 10436555
TI  == [trovafloxacin in gynecology].
AB  == presence of microorganisms in the female lower genital tract (lgt) in concentrations that modify the established normal equilibrium produce different symptoms that make necessary to consult the gynecologist. it is currently accepted that infections of the lgt are due to microorganisms that are normally integrating the internal flora, except for the erroneously called "sexually transmitted diseases" that are caused by external microorganisms. this means that all those microorganisms usually present without causing any disease manifestations may, under certain circumstances and determined concentrations, originate or be associated to infections. lactobacillus sp. and corynebacterium sp. are normally the most frequent microorganisms in the vagina together with streptococcus (aerobe), streptococcus agalactiae and others like enterococcus, peptostreptococcus, bacteroides sp., bacteroides fragilis, bacteroides melaninogenicus, pseudomonas, klebsiella, fusobacterium, escherichia coli. different antibiotic schemes are proposed for different infections (bacterial vaginosis, gonococcia, chlamydial infections, pelvic inflammatory disease). they  are discussed in different sections. trovafloxacin has shown to be effective in the treatment of infections due to chlamydia with excellent clinical results and  a good tolerance. it was effective as single dose therapy in the treatment of acute gonococcia with therapeutic success in 99% of the treated patients. new fluoroquinolones are also effective in the treatment of infections due to aerobial pathogens. the use of trovafloxacin in the treatment of pelvic inflammatory disease would present great advantages: on one hand, it would cover  the wide spectrum of microorganisms responsible for the infection and, on the other, would permit an early switch to oral therapy once the acute phase is over.
TIHT== 
ABHT== 

PMID== 10224336
TI  == in vitro activities of pazufloxacin, a novel injectable quinolone, against bacteria causing infections in obstetric and gynecological patients.
AB  == t-3762 is an injectable new quinolone with a broad spectrum of antibacterial activity. pazufloxacin (t-3761) is an active form of t-3762. the minimal inhibitory concentrations (mics) of pazufloxacin for 50% of the clinical isolates tested were 3.13 microg/ml for streptococcus agalactiae, 6.25 microg/ml for gardnerella vaginalis, 0.025 microg/ml for escherichia coli, 0.78 microg/ml for pseudomonas aeruginosa, 6.25 microg/ml for peptostreptococcus magnus, 6.25 microg/ml for bacteroides fragilis and 12.5 microg/ml for prevotella bivia. the mics of t-3762 for 90% of the clinical isolates tested were 3.13 microg/ml for s. agalactiae, 6.25 microg/ml for g. vaginalis, 0.10 microg/ml for e. coli, 12.5 microg/ml for p. aeruginosa, 25 microg/ml for p. magnus, 12.5 microg/ml for b. fragilis and 25 microg/ml for p. bivia. the results of this study suggest that, subject to confirmation by clinical trials, t-3762, in combination with an agent  with reliable activity against anaerobic bacteria, is suitable as an empirical therapy of patients with obstetric and gynecological infections.
TIHT== 
ABHT== 

PMID== 9732148
TI  == in vitro activities of e1101, a novel oral cephalosporin, against bacteria causing infections in obstetric and gynecological patients.
AB  == e1101 is a new oral cephalosporin with a broad spectrum of antibacterial activity. it inhibited more than 90% of clinical isolates of streptococcus agalactiae, escherichia coli and peptostreptococcus magnus at the concentration of 3.13 mg/l. e1101 was the most active agent against s. agalactiae and e. coli.  since none of the compounds was sufficiently active against the bacteroides fragilis and prevotella bivia isolates, they are not appropriate in the treatment of patients with infections caused by these organisms. the results of this study  suggest that, subject to confirmation by clinical trials, e1101, in combination with an agent with reliable activity against anaerobic bacteria, is suitable as empirical therapy of patients with obstetric and gynecological infections.
TIHT== 
ABHT== 

PMID== 9681200
TI  == in vitro and in vivo antibacterial activities of am-1155 in the fields of obstetrics and gynecology.
AB  == am-1155 is a new 8-methoxyquinolonecarboxylic acid with a broad spectrum of antibacterial activity. it inhibited more than 90% of clinical isolates of streptococcus agalactiae, escherichia coli, peptostreptococcus magnus, bacteroides fragilis and prevotella bivia at the concentration of 3.13 mg/l. the  antibacterial activity of am-1155 was almost equal to that of sparfloxacin. the in vivo efficacy of am-1155 was evaluated using a polymicrobial pyometra (e. coli and b. fragilis) model of rats. the accumulation of neutrophils to the uterus in  the am-1155-treated group was less marked than that of the nontreated group, as well as the bacteriological response. these results suggest that the new antimicrobial agent am-1155 might be useful for the treatment of polymicrobial infections in the fields of obstetrics and gynecology.
TIHT== 
ABHT== 

PMID== 9444403
TI  == in vitro and in vivo antibacterial activities of a new carbapenem bo-2727 for use in obstetrics and gynecology.
AB  == the antibacterial activity of bo-2727 against 100 clinical isolates of streptococcus agalactiae (20 strains), escherichia coli (20 strains), peptostreptococcus magnus (20 strains), bacteroides fragilis (20 strains) and prevotella bivia (20 strains) was compared with those of imipenem, panipenem, meropenem, biapenem and ceftazidime (caz). minimal inhibitory concentrations (mics) for 50% of tested strains (mic50s) of bo-2727 against s. agalactiae, e. coli, p. magnus, b. fragilis and p. bivia were 0.05, 0.05, 0.1, 0.78 and 0.78 mg/l, respectively. mic90s of bo-2727 against s. agalactiae, e. coli, p. magnus,  b. fragilis and p. bivia were 0.05, 0.05, 0.1, 0.78 and 0.78 mg/l, respectively.  the efficacy of bo-2727 was evaluated using a polymicrobial pyometra model (e. coli and b. fragilis) in rats. both the inflammatory changes in the uterus, from  the point of view of neutrophil accumulation, and the bacteriological response in the treated group were milder than those in either the nontreated group or the caz-treated group. these results indicate that bo-2727 may be useful for the treatment of polymicrobial infections in patients with pyometra.
TIHT== 
ABHT== 

PMID== 9126690
TI  == tissue penetration of meropenem in patients undergoing gynecologic surgery.
AB  == the purpose of this study was to assess the tissue-penetrating ability of a new beta-lactam antibiotic, meropenem, in 64 patients undergoing elective gynecologic surgery. patients received a single 500-mg dose intravenously before surgery. plasma and tissue concentrations of meropenem were highest at approximately 1 hour, and good tissue penetration was seen in the variety of specimens evaluated. the median plasma concentration at approximately 1 hour was 13.3 micrograms/ml. the median fluid and tissue concentrations at approximately 1 hour were as follows: cervix, 8.5 micrograms/g; endometrium, 2.3 micrograms/g; fallopian tube, 1.9 micrograms/g; myometrium, 3.6 micrograms/g; ovary, 2.3 micrograms/g; and uterus, 2.3 micrograms/g. these tissue concentrations exceed the mics of meropenem for 90% of typical pathogens associated with gynecologic infections. meropenem readily penetrates gynecologic tissue. a single 500-mg dose provides adequate tissue concentrations for treatment of gynecologic infections caused by  susceptible pathogens.
TIHT== 
ABHT== 

PMID== 8957575
TI  == in vitro activity of bay 12-8039, a new 8-methoxyquinolone.
AB  == bay 12-8039 is a new 8-methoxyquinolone with antibacterial activity against gram-positive bacteria which is significantly better than those of sparfloxacin or ciprofloxacin. the minimal inhibitory concentrations (mics) for 90% of methicillin-susceptible staphylococcus aureus and staphylococcus epidermidis were 0.062 and 2 mg/l, respectively. the mic90s for ciprofloxacin-resistant, methicillin-susceptible and methicillin-resistant s. aureus were 8 mg/l. against  the staphylococcal strains tested sparfloxacin was 2-fold and ciprofloxacin > or  = 10-fold less active. mic90s for streptococcus pneumoniae, streptococcus pyogenes and streptococcus agalactiae were 0.125-0.5 mg/l, irrespective of whether strains with diminished ciprofloxacin susceptibility or ciprofloxacin-susceptible strains were tested. against the streptococci sparfloxacin was 2- to 4-fold less active. against gram-negative bacteria bay 12-8039 is almost as active as ciprofloxacin, except for pseudomonas aeruginosa.  against bacteroides fragilis, bacteroides spp. and clostridium spp. bay 12-8039 was as active as metronidazole. the bactericidal activity against s. aureus and s. pneumoniae was in contrast to that of the other quinolones tested, penicillin  g, amoxicillin+/-clavulanate, cefuroxime and clarithromycin, concentration-dependent. as compared to ciprofloxacin, development of resistance  was less pronounced. the spontaneous mutation frequency towards bay 12-8039 resistance was 2.8 x 10(-8) in escherichia coli, 7.06 x 10(-8) in s. aureus and < 1.4 x 10(-9) in s. pneumoniae.
TIHT== 
ABHT== 

PMID== 8843289
TI  == penetration of cefpodoxime into uterine and vaginal secretions from postpartum women after a single oral dose of cefpodoxime proxetil.
AB  == we evaluated the usefulness of cefpodoxime proxetil (cpdx-pr) in the treatment of puerperal infection and obtained the following results. (i) the susceptibilities  of 124 clinical isolates from 85 uterine lochia samples were determined. the mic  at which the growth of streptococcus agalactiae, escherichia coli, and bacteroides fragilis isolates was inhibited by 90% (mic90) was 0.39 micrograms/ml or less. the mic90 for staphylococcus aureus was 3.13 micrograms/ml. (ii) seven puerperal women received 200 mg of cpdx-pr orally. the cpdx concentration in the  lochias in the uterine cavity was not statistically different from that in the vagina, suggesting that the vaginal samples, which can be obtained more safely and aseptically, can be substituted for the uterine samples. the cpdx concentration in cubital venous blood reached a peak of 1.61 micrograms/ml at 3 hours after cpdx-pr administration. the cpdx concentration in the lochias gradually increased and reached a peak of 1.20 micrograms/ml in the uterine cavity and 1.27 micrograms/ml in the vagina at 5 h after drug administration and  gradually declined thereafter. these results suggest that cpdx-pr, with its good  transfer to the lochia and its potent antimicrobial activity, is a promising drug for the prophylactic and therapeutic treatment of puerperal infections caused by  susceptible organisms.
TIHT== 
ABHT== 

PMID== 8205934
TI  == in vitro antibacterial activity of fk037, a new parenteral broad-spectrum cephalosporin, against recent clinical isolates in the fields of obstetrics and gynecology.
AB  == the antibacterial activity of a new parenteral cephalosporin, fk037 was assessed  against recent aerobic and anaerobic strains isolated from patients in the fields of obstetrics and gynecology during the period between january 1992 and june 1993. the mics of fk037 for 90% of the clinical isolates tested were 0.10 microgram/ml for escherichia coli and klebsiella pneumoniae, 0.20 microgram/ml for streptococcus agalactiae, 0.39 microgram/ml for gardnerella vaginalis, 0.78 microgram/ml for staphylococcus epidermidis, peptostreptococcus anaerobius and mobiluncus spp., 1.56 micrograms/ml for peptostreptococcus magnus, 3.13 micrograms/ml for methicillin-sensitive staphylococcus aureus, 25 micrograms/ml for methicillin-resistant s. aureus (mrsa), bacteroides fragilis and prevotella disiens, 100 micrograms/ml for bacteroides thetaiotaomicron and prevotella bivia; and > 100 micrograms/ml for enterococcus faecalis. fk037 was superior in potency  to ceftazidime against all strains except e. faecalis, p. anaerobius and p. bivia. it was 4- to 16-fold more active than cefotaxime against aerobic gram-positive bacteria and p. disiens, and its activity was similar to that of cefotaxime against the other strains. fk037 had 4- to 16-fold stronger activity than flomoxef against mrsa, s. agalactiae and e. coli and a similar activity to flomoxef against the other strains except g. vaginalis and b. fragilis that were  4-fold more sensitive to flomoxef than to fk037.
TIHT== 
ABHT== 

PMID== 8109918
TI  == in vitro antibacterial activities of pd 138312 and pd 140248, new fluoronaphthyridines with outstanding gram-positive potency.
AB  == pd 138312 and pd 140248 are new quinolones with high in vitro activities against  a wide spectrum of bacterial species, notably including gram-positive isolates. the respective mics (in micrograms per milliliter) of pd 138312 and pd 140248 capable of inhibiting > or = 90% of the strains were < or = 0.06 and < or = 0.06  for oxacillin-susceptible and -resistant staphylococci, streptococci (including streptococcus pyogenes, s. agalactiae, s. pneumoniae, and viridans group streptococci), haemophilus influenzae, moraxella catarrhalis, and neisseria gonorrhoeae; 0.125 and 0.03 for legionella pneumophila; 0.25 and 0.125 for listeria monocytogenes; 0.25 and 0.25 for enterococcus faecalis; 0.5 and 0.06 for anaerobic gram-positive cocci; 0.5 and 0.25 for acinetobacter spp.; 0.5 and 0.5 for members of the family enterobacteriaceae (excluding serratia marcescens); 2 and 0.5 for bacteroides fragilis; 2 and 2 for serratia marcescens and ciprofloxacin-resistant staphylococci; and 8 and 4 for pseudomonas aeruginosa.
TIHT== 
ABHT== 

PMID== 8239624
TI  == in vitro activities of bay y3118, ciprofloxacin, ofloxacin, and fleroxacin against gram-positive and gram-negative pathogens from respiratory tract and soft tissue infections.
AB  == bay y3118 was highly active against moraxella catarrhalis, haemophilus influenzae, legionella pneumophila, escherichia coli, klebsiella pneumoniae, staphylococcus aureus (except quinolone-resistant, methicillin-resistant s. aureus), staphylococcus epidermidis, streptococcus pyogenes, streptococcus agalactiae, and streptococcus pneumoniae (mic for 90% of strains tested [mic90],  0.063 micrograms/ml). for enterococcus faecalis and corynebacterium jeikeium, mic90s were 4 and 2 micrograms/ml, respectively. bay y3118 was as active as ciprofloxacin against pseudomonas aeruginosa (mic90, 0.5 micrograms/ml) and had potent activity against bacteroides fragilis (mic90, 0.5 micrograms/ml).
TIHT== 
ABHT== 

PMID== 1289579
TI  == [antibacterial activity of rokitamycin against fresh clinical isolates].
AB  == we obtained bacterial strains which were clinically isolated and identified from  outpatients with various infections in medical institutions throughout japan. possible antibacterial activities of rokitamycin (rkm) were examined against these isolates. minimum inhibitory concentrations (mics) were determined through  a comparative study with reference drugs. the results of the study are summarized as follows. 1. resistance patterns of 400 isolates which were highly resistant to macrolides (mls) with mic values > 100 micrograms/ml were classified into 55 patterns. staphylococcus spp. showed cross resistance to 14-membered ring mls with 100% cross resistance observed between erythromycin (em) and clarithromycin  (cam), and 85.2% between em and oleandomycin (ol). fewer isolates showed strong resistance to 16-membered ring mls than to 14-membered ring mls. cross resistances observed among the staphylococcus isolates were 100% between acetylmidecamycin (mdm-ac) and kitasamycin (leucomycin (lm)), 93.9% between mdm-ac and josamycin (jm), and 53.3% between mdm-ac and rkm. streptococcus spp. and peptococcus spp. showed very similar resistance patterns to both 14- and 16-membered ring mls, but resistance patterns to rkm were quite different. most of anaerobic streptococci and bacteroides fragilis group had similar resistance patterns to 14- and 16-membered ring mls, but in some cases a pattern similar to  that of staphylococcus spp. was observed. 2. when ml-resistant bacteria isolated  during 1975 to 1980 were compared to those isolated in 1986 and 1989, it was observed that resistance of staphylococcus aureus remained almost unchanged, that of streptococcus pyogenes was lower in the later years than during 1975 to 1980,  but that of streptococcus pneumoniae increased. 3. most of ml-resistances of the  resistant isolates were inducible, but extents of induction varied depending on drugs tested. strong inductions were observed when 14-membered ring mls were used, but inductions were minimal with 16-membered ring mls. rkm appeared to induce resistance to the least extent. from these results, it appears that the rkm is quite useful clinically even in the 1990s.
TIHT== 
ABHT== 

PMID== 1489178
TI  == in vitro activity of ru 29246, the active compound of the cephalosporin prodrug ester hr 916.
AB  == the in vitro activity of ru 29246 was compared with those of other agents against 536 recent clinical isolates. the mics of ru 29246 for 90% of members of the family enterobacteriaceae tested (mic90s) were less than 2 micrograms/ml except those for morganella spp. (16 micrograms/ml) and proteus spp. (8 micrograms/ml).  ru 29246 was active against staphylococcus aureus (mic90, < or = 8 micrograms/ml) and against staphylococcus saprophyticus and coagulase-negative staphylococci (mic90s, < or = 2 micrograms/ml). streptococci and neisseria gonorrhoeae were highly susceptible to ru 29246, and the activity of the agent against isolates of streptococcus pneumoniae (mic90, < or = 0.5 micrograms/ml), haemophilus influenzae (mic90, < or = 2 micrograms/ml), and moraxella catarrhalis (mic90, < or = 2 micrograms/ml) was comparable to those of the other cephalosporins tested. ru 29246 was insusceptible to hydrolysis by the common plasmid-mediated beta-lactamases (tem-1 and shv-1). however, hydrolysis by the new extended-spectrum beta-lactamases (tem-3, tem-5, and tem-9) was detected. results of the study suggested that ru 29246 should be investigated clinically for use in the treatment of a wide range of infections.
TIHT== 
ABHT== 

PMID== 1396779
TI  == comparative in vitro activity and beta-lactamase stability of ru29246, the active metabolite of hr916b.
AB  == hr 916b is a new orally absorbed cephalosporin. in tests its active metabolite, ru29246, inhibited streptococcus pyogenes, streptococcus agalactiae and streptococcus pneumoniae at less than or equal to 0.12 micrograms/ml, which is similar to the antibacterial activity of cefuroxime, and was more active than cefaclor. it was also more active (mic 2 micrograms/ml) than cefixime, cefuroxime, cefaclor and cefotaxime against staphylococci. ru29246 inhibited escherichia coli, klebsiella pneumoniae, citrobacter diversus, klebsiella oxytoca, proteus mirabilis, providencia stuartii and salmonella spp. at less than or equal to 1 microgram/ml, thus being more active than cefuroxime and cefaclor,  but was less active than cefixime and cefotaxime. it did not inhibit pseudomonas  aeruginosa and other pseudomonas spp., enterobacter spp., serratia marcescens or  bacteroides fragilis. ru29246 was not hydrolyzed by tem-1, staphylococcus aureus  tem-2 or moraxella catarrhalis beta-lactamases, but was hydrolyzed by tem-3 and the chromosomal beta-lactamases of proteus vulgaris and morganella morganii. plasmid and chromosomal beta-lactamases were inhibited by ru29246.
TIHT== 
ABHT== 

PMID== 1615064
TI  == heterologous gene expression in bacteroides fragilis.
AB  == bacteroides fragilis and other gastrointestinal tract bacteroides are unusual gram-negative eubacteria in that genes from other gram-negative eubacteria are not expressed when introduced into these organisms. to analyze gene expression in bacteroides, expression vector and promoter probe (detection) vector systems were developed. the essential feature of the expression vector was the incorporation of a bacteroides insertion sequence element, is4351, which possesses promoter activity directed outward from its ends. genes inserted into the multiple cloning site downstream from an is4351 dna fragment were readily expressed in b. fragilis. the chloramphenicol acetyltransferase (cat) structural gene from tn9 was tested and conferred chloramphenicol resistance on b. fragilis. both chloramphenicol resistance and cat activity were shown to be dependent on the is4351 promoters. similar results were obtained with the escherichia coli beta-glucuronidase gene (uida) but activity was just 30% of the levels seen with  cat. two tetracycline resistance determinants, tetm from streptococcus agalactiae and tetc from e. coli, also were examined. tetc did not result in detectable tetracycline resistance but the gram-positive tetm gene conferred high-level resistance to tetracycline and minocycline in bacteroides hosts. based on the cat results, promoter probe vectors containing the promoterless cat gene were constructed. these vectors were used to clone random b. fragilis promoters from partial genomic libraries and the recombinants displayed a range of cat activities and chloramphenicol mics in b. fragilis hosts. in addition, known e. coli promoters (ptet, ptac, ptrc, psyn, and p1p2rrnb) were tested for activity in b. fragilis. no chloramphenicol resistance or cat activity was observed in b. fragilis with these promoters.
TIHT== 
ABHT== 

PMID== 1889177
TI  == in vitro antibacterial activities of the fluoroquinolones pd 117596, pd 124816, and pd 127391.
AB  == three new aminopyrrolidine-substituted fluorocyclopropyl quinolones--pd 117596, pd 124816, and pd 127391--were tested for in vitro antibacterial activity against 349 bacterial strains, which are primarily clinical isolates. the minimum inhibitory concentrations (mic) in micrograms/ml required for greater than or equal to 90% of strains were 0.03-0.06 for staphylococci (26 strains); 0.06-0.25  for streptococcus pyogenes, s. agalactiae, s. pneumoniae, and enterococcus faecalis (80); less than or equal to 0.015 for branhamella catarrhalis, haemophilus influenzae, and neisseria gonorrhoeae (42); 0.06 for enterobacteriaceae (97); 0.125-0.25 for acinetobacter spp. (14); 0.5 for pseudomonas aeruginosa (20); 0.125-1.0 for bacteroides fragilis (13); and 0.25-0.5 for anaerobic cocci (11). these activities were generally superior to that of ciprofloxacin, imipenem, ampicillin, penicillin g, oxacillin, cefazolin,  ceftazidime, cefoxitin, cefsulodin, aztreonam, piperacillin, amikacin, spectinomycin, doxycycline, erythomycin, clindamycin, metronidazole, and vancomycin. the activities of the new quinolones were generally unchanged with light, 50% human serum, aerobic/anaerobic atmosphere, 5% sodium choate, cation supplementation, and 100-fold increased or decreased inoculum; as with other quinolones, potency was measurably diminished with decreasing ph (ph less than or equal to 6.0) and in 100% urine.
TIHT== 
ABHT== 

PMID== 2287060
TI  == [susceptibilities of clinical bacterial isolates to antimicrobial agents. a study mainly focused on imipenem. reported by the research group for testing imipenem susceptibility on clinical isolates].
AB  == this study was conducted to investigate susceptibilities of clinical bacterial isolates to imipenem (ipm) and other antibacterial agents at 64 hospital laboratories throughout japan from september to december of 1988. in this study,  identification and susceptibility testing were carried out at each laboratory and the tests were performed according to the disk dilution method recommended by nccls in which susceptibilities are classified into "s", "ms", "i" and "r". ipm showed markedly high in vitro activities against streptococcus pneumoniae, streptococcus pyogenes, streptococcus agalactiae, enterococcus faecalis, haemophilus influenzae, escherichia coli, klebsiella pneumoniae, klebsiella oxytoca, enterobacter aerogenes, enterobacter cloacae, serratia marcescens, salmonella spp., citrobacter freundii, proteus mirabilis, proteus vulgaris, morganella morganii, providencia rettgeri, providencia stuartii, acinetobacter calcoaceticus, moraxella (branhamella) catarrhalis, alcaligenes spp., peptococcus spp./peptostreptococcus spp., bacteroides fragilis and bacteroides spp. ipm also  had strong activities against achromobacter xylosoxidans and pseudomonas aeruginosa, but less active against flavobacterium spp., e. faecium, coagulase-negative staphylococci (cns), staphylococcus aureus and pseudomonas cepacia. in a study in which activities of ipm against bacteria isolated from different clinical sources were compared, differences in susceptibilities were observed among s. aureus, cns, a. calcoaceticus and p. aeruginosa, but such differences were not apparent among s. pneumoniae, e. faecalis, h. influenzae, e. coli, k. pneumoniae, e. cloacae, c. freundii, s. marcescens or p. mirabilis.
TIHT== 
ABHT== 

PMID== 2086814
TI  == [susceptibilities of clinical bacterial isolates to antimicrobial agents. a study mainly focused on imipenem. research group for testing imipenem susceptibility on clinical isolates].
AB  == we investigated susceptibilities of clinical bacterial isolates to imipenem (ipm) and other antimicrobial agents at 459 hospital laboratories throughout japan from september to december of 1988. in this study, identification and susceptibility testing were performed at each hospital laboratory and the tests were carried out according to the 1-dilution or 3-dilution disc technique in which susceptibilities are classified into 4 grades: , ++, + and -. ipm had significantly high activity against streptococcus pneumoniae, streptococcus pyogenes, streptococcus agalactiae, neisseria gonorrhoeae, escherichia coli, klebsiella pneumoniae, klebsiella oxytoca, enterobacter aerogenes, enterobacter cloacae, salmonella spp., citrobacter freundii, proteus mirabilis, providencia rettgeri, acinetobacter calcoaceticus, moraxella catarrhalis, alcaligenes spp., peptococcus spp./peptostreptococcus spp., bacteroides fragilis and bacteroides spp. and should slightly lower activities on coagulase-negative staphylococci (cns), enterococcus faecalis, haemophilus influenzae, serratia marcescens, proteus vulgaris, providencia stuartii and pseudomonas aeruginosa than on the above mentioned bacteria. in a comparative study on activities of ipm against bacteria from different clinical sources, no remarkable differences were found due to different sources among s. pneumoniae, e. faecalis, h. influenzae, e. coli, k. pneumoniae, e. cloacae, c. freundii, p. mirabilis or a. calcoaceticus, whereas slight differences were found among staphylococcus aureus, cns, s. marcescens and p. aeruginosa.
TIHT== 
ABHT== 

PMID== 2664255
TI  == [susceptibilities of clinical isolates to antibacterial agents. a study mainly focused on ofloxacin (the second report). reported by the research group for testing ofloxacin susceptibility on clinical isolates].
AB  == susceptibilities of various clinical isolates to ofloxacin (oflx) and other antibacterial drugs were examined at 128 hospital laboratories in 36 prefectures  throughout japan between april, 1986 and march, 1987. the results were totalized  with an emphasis mainly on oflx and were compared with data obtained in the previous year. in this study, identification and susceptibility tests of the isolates were carried out at each hospital laboratory and the tests were performed according to the 1-dilution or 3-dilution disc method in which susceptibilities are classified into 4 grades: , ++, +, and -. similarly to the study performed in the previous year, species showing susceptibilities to oflx included staphylococcus aureus (4,205 strains), staphylococcus epidermidis (2,009 strains), entercoccus faecalis (1,697 strains), streptococcus pneumoniae (702 strains), escherichia coli (4,097 strains), klebsiella pneumoniae (1,375 strains), enterobacter cloacae (762 strains), enterobacter aerogenes (296 strains), citrobacter freundii (406 strains), proteus mirabilis (613 strains), morganella morganii (320 strains), serratia marcescens (869 strains), haemophilus influenzae (1,282 strains), pseudomonas aeruginosa (4,206 strains), acinetobacter calcoaceticus (351 strains), acinetobacter sp. (415 strains), and campylobacter jejuni (151 strains). neisseria gonorrhoeae (26 strains) were exceptional due to  their smaller number this time than that of the previous year and only the susceptibility to oflx was investigated with this species. as results, oflx showed strong antibacterial activities (similar to the previous year) against s.  aureus, s. epidermidis, n. gonorrhoeae, e. coli, k. pneumoniae, e. cloacae, e. aerogenes, c. freundii, p. mirabilis, m. morganii, h. influenzae, a. calcoaceticus, acinetobacter sp., and c. jejuni. however, when these susceptibilities shown in the present study were compared to those obtained in the previous year, many species showed decreases in the occurrence of or increases in -, though they were rather small changes. the following species were not totalized in the previous year due to their low numbers but were summarized in combination with those examined in this study: streptococcus pyogenes (944 strains), streptococcus agalactiae (815 strains), enterococcus faecium (146 strains), branhamella catarrhalis (135 strains), citrobacter diversus (128 strains), klebsiella oxytoca (873 strains), proteus vulgaris (438 strains), serratia liquefaciens (266 strains), pseudomonas cepacia (433 strains), pseudomonas putida (154 strains), xanthomonas maltophilia (272 strains), vibrio parahaemolyticus (120 strains), bacteroides fragilis (98 strains),
TIHT== 
ABHT== 

PMID== 2769943
TI  == [antibacterial activity of cervical mucus in pregnant or non-pregnant women].
AB  == antibacterial activities of human cervical mucus obtained from non-pregnant and pregnant women were tested using standard blood agar plates. the combined effect  of cervical mucus with cefmetazole (cmz) was also investigated. obtained results  are summarized as follows. 1. cervical mucus specimens obtained from 6 subjects at 9 to 36 weeks of pregnancy showed antibacterial activity to only one strain of bacillus subtilis among organisms tested. the cervical mucus enhanced the activity of cmz against 1 strain of streptococcus pyogenes and 2 strains of micrococcus luteus, but no effect was observed against other organisms tested. 2. cervical mucus specimens obtained from non-pregnant women showed antibacterial activities to 8 of 11 strains (72.7%) of b. subtilis tested. the cervical mucus enhanced the activities of cmz against 1 strain of s. pyogenes and 3 strains of b. subtilis. the tested organisms included staphylococcus aureus, escherichia coli, bacteroides fragilis, s. pyogenes, b. subtilis, m. luteus, streptococcus agalactiae, enterococcus faecalis, and candida albicans, but, as described above, cervical mucus samples showed antimicrobial activities only against b. subtilis (9/17, 52.9%), and specimens obtained only from non-pregnant women or pregnant women with less than 11 weeks of pregnancy showed any antimicrobial activities.
TIHT== 
ABHT== 

PMID== 2712599
TI  == bacteriological findings after premature rupture of the membranes.
AB  == of 243 children born after premature rupture of the membranes (prom) 61 (26%) had the same bacteria in placental arterial blood, in ear swabs (taken deep from the  external auditory canal) and in meconium. the predominant organisms were e. coli, bacteroides fragilis, streptococcus faecalis (enterococci) and streptococcus agalactiae (group b streptococci). the infection rate was only 10% if the membranes had ruptured within 24 h of the onset of labour and 30% if the interval was longer than 24 h. of 131 children born without premature rupture of the membranes but with risk factors for sepsis 9 (7%) had a positive blood culture with the same organism in the ear swabs and in meconium. the organisms were streptococcus agalactiae (6 cases) and e. coli, streptococcus faecalis and klebsiella pneumoniae (one case each). contamination of placental blood cultures  was rare.
TIHT== 
ABHT== 

PMID== 3210303
TI  == [evaluation of imipenem/cilastatin sodium in neonatal infections].
AB  == ten patients with infections (8 neonates and 2 infants) were treated with 10.2 mg/10.2 mg/kg-37.7 mg/37.7 mg/kg of imipenem/cilastatin sodium (ipm/cs) b.i.d. or t.i.d. by a 1-hour intravenous drip infusion. the plasma concentrations of ipm/cs were determined in 5 of the 10 patients and in the cerebrospinal fluid of 1 patient of the 5. 1. the patients studied included 5 with pneumonia and 1 each with urinary tract infection, omphalitis, suspected meningitis, periproctal abscess and suspected septicemia. clinical efficacy was evaluated in 9 patients:  the patient with suspected meningitis was excluded from the clinical evaluation because the infection was doubtfully due to bacteria. responses were excellent in 4 and good in 5 patients. no patient with a poor response was observed. all of the 6 etiological isolates obtained from 5 patients (2 strains of staphylococcus  aureus and 1 each of escherichia coli, enterococcus faecalis, streptococcus agalactiae and bacteroides fragilis) were eradicated. 2. as for side effects, rash was observed in 1 patient and petechiae accompanied by decreases in platelets and reticulocytes and increases in got and gpt were observed in another. other abnormal laboratory test values in addition to the above abnormalities consisted of an increase in gpt in 1 patient and increases in got and gpt in another. these side effects and abnormalities in laboratory test values were mild and normalized after discontinuation or completion of ipm/cs administration.(abstract truncated at 250 words)
TIHT== 
ABHT== 

PMID== 2458746
TI  == bacteroides fragilis lipopolysaccharide and group b streptococcus serotype ii glycocalyx have a common major antigenic determinant.
AB  == a monoclonal antibody (mab) to the beta-1-6-linked digalactose structure in the lipopolysaccharide (lps) of bacteroides fragilis reacted with 47 of 416 group b streptococcus (gbs) strains tested by an immunofluorescence technique (if). the reactivity of mab was, with a few exceptions, limited to type ii gbs. gas chromatography-mass spectrometry analysis demonstrated that an antigen purified by immunoaffinity chromatography using mab from type ii gbs contained galactose,  glucose and fatty acids. this confirmed that mab is directed to the digalactose (which in earlier studies was found to occur) in the capsular lipocarbohydrate specific to type ii gbs. the positive strains yielded a strong, apple-green surface stain by means of the if using mab. various immuno-electron microscopic (iem) methods showed that the determinant was located in the glycocalyx layer of  gbs at a distance of about 15 nm from the streptococcal cell wall. the structure  harbouring the determinant was found to be very loosely attached to the bacteria. however the cross-reactive determinant seemed to maintain its immunoreactivity whether it was extracted by gentle washing with saline or with harsher treatments usually reserved for preparing streptococcal polysaccharide antigens. in conclusion, the study shows that the determinant is an integral part of the type-specific antigen of type ii gbs and that mab has a potential use as a serotyping reagent.
TIHT== 
ABHT== 

PMID== 3372024
TI  == in vitro activity of flomoxef in comparison to other cephalosporins.
AB  == flomoxef and cefazolin had nearly the same activity against staphylococci, which  was stronger than that of other cephalosporins. against streptococcus pyogenes, streptococcus agalactiae and streptococcus pneumoniae, cefotaxime and cefazolin were more active than flomoxef, but the other cephamycins were less active than flomoxef. in comparison to the other cephalosporins, latamoxef and flomoxef had higher activity against branhamella catarrhalis, whereas cefotaxime, latamoxef and cefotetan were more active against haemophilus influenzae. flomoxef was the only drug exhibiting activity against clostridium difficile. the activity of flomoxef and latamoxef against bacteroides fragilis was stronger than that of the other cephalosporins, but bacteroides bivius was resistant to each of these antibiotics.
TIHT== 
ABHT== 

PMID== 3146552
TI  == comparative in-vitro activity of erythromycin, vancomycin and pristinamycin.
AB  == we have studied the in-vitro activity of erythromycin, vancomycin and pristinamycin against 1,006 clinical isolates comprising streptococci, staphylococci, neisseria gonorrhoeae, haemophilus influenzae and anaerobes. in-vitro studies show pristinamycin to inhibit staphylococci and streptococci, including erythromycin highly-resistant organisms, at a concentration of less than or equal to 0.78 mg/l. although pristinamycin's mean mic for streptococci is higher than that of erythromycin, pristinamycin is bactericidal, whereas erythromycin is bacteristatic against streptococcus agalactiae and oral streptococci. enterococci were less uniformly susceptible to pristinamycin: 58 of the 94 enterococcus faecalis tested were resistant (mic greater than or equal to  3.12 mg/l). 14 of the 15 isolates of enterococcus faecium were inhibited by less  than or equal to 1.56 mg/l pristinamycin. pristinamycin showed poor activity against haemophilus influenzae (mode mic 1.56 and mic90 of 3.12 mg/l) but all except two of the 100 neisseria gonorrhoeae tested were inhibited by less than or equal to 0.78 mg/l pristinamycin. pristinamycin inhibited all nine clostridium spp. at less than or equal to 0.39 mg/l and 38 of 40 strains of anaerobic gram-positive cocci at less than or equal to 0.78 mg/l. it was less effective against the bacteroides fragilis group: (mic90 3.12 mg/l). pristinamycin had poor bactericidal activity against the anaerobes tested.
TIHT== 
ABHT== 

PMID== 3301451
TI  == does an intracervical infection influence the fibrinolytic activity and the collagen content of the fetal membranes? a study of ascending infections in pregnant ewes.
AB  == apart from solely mechanical explanations, premature rupture of the membranes (prom) has been suggested to be caused by an ascending infection. in order to investigate the role of infection in the mechanism of prom, pregnant ewes were experimentally inoculated endocervically with either bacteroides fragilis, streptococcus intermedius or group b streptococci. these microorganisms were previously reported to be implicated in prom in humans. the present investigation concerns the possible effect of an experimentally induced ascending infection on  the collagen content and fibrinolytic activity (fa) of the fetal membranes. no relationship was observed between an ascending infection during pregnancy and the collagen content content of the fetal membrane specimens. it was concluded that changes in the collagen content bear no etiological significance in the mechanism of premature membrane rupture irrespective of an ascending infection's being present or not. concerning fa in only one case, experiencing a strept. intermedius amnionitis, was an elevated fa value observed. this finding indicates that the involvement of fa in the process of membrane rupture following ascending infection during pregnancy cannot be ruled out.
TIHT== 
ABHT== 

PMID== 6206719
TI  == gram's stains of tracheal secretions predict neonatal bacteremia.
AB  == the presence of bacteria in tracheal secretions stained by the gram method was evaluated as a method of predicting neonatal bacteremia. the presence of bacteria had a 74% sensitivity and a 47% predictive accuracy in identifying neonates with  bacteremia before 12 hours of age. the specificity in predicting newborns without bacteremia was 98%. in the same neonates, an immature neutrophil-total neutrophil ratio of 0.2 or more had a 77% sensitivity in predicting neonates with bacteremia. neonates with bacteria in their blood and tracheal aspirates, who died shortly after birth, had pneumonia on postmortem examination. in newborns who have respiratory distress and a risk of infection at birth, gram's stains of  tracheal secretions are a practical and useful method of predicting congenital bacteremia.
TIHT== 
ABHT== 

PMID== 6355474
TI  == the frequency and some characteristics of anaerobic bacteria isolated from various forms of bovine mastitis.
AB  == the prevalence of strictly anaerobic bacteria in the secretions from untreated cases of mastitis in lactating dairy cows was investigated. the study involved 147 friesland cows in 12 highveld herds. all herds yielded cows with anaerobic udder infections. no anaerobic bacteria were recovered from cows with normal quarters or those with latent aerobic infections. only anaerobes were present in  10% of so-called 'aseptic' mastitis cases. a variety of anaerobic organisms was isolated concurrently with facultative bacteria from 5,3% and 58,8% of cases classified as subclinical and clinical respectively. peptococcus spp. was associated with corynebacterium pyogenes and bacteroides spp. with staphylococcus aureus and/or streptococcus agalactiae in 80% anaerobic udder infections. gram positive anaerobic species were mostly sensitive to penicillin-g but all the gram negative rods were resistant. in addition, all b. fragilis strains produced beta-lactamase. the ability to produce heparinase was demonstrated in one strain  of peptococcus indolicus and a peptostreptococcus sp.
TIHT== 
ABHT== 

PMID== 6341180
TI  == bacteroides fragilis, streptococcus intermedius and group b streptococci in ascending infection of pregnancy. an animal experimental study.
AB  == by means of bacteriological, histological and immunofluorescence methods, the ascending spread of endocervically inoculated bacteria was studied in 14 pregnant sheep. 8 ewes near term were exposed to group b streptococci, bacteroides fragilis or streptococcus intermedius for 2-4 days. 6 other animals in mid pregnancy were exposed to one of the bacteria mentioned for 30 days. before inoculation, aerobic and anaerobic culture specimens from cervix and amniotic fluid were obtained. at delivery by caesarean section, in addition to culture specimens, membrane and placental tissues were collected. bacterial detection by  means of indirect immunofluorescence showed significant invasion of the membranes and the placentas by the microorganisms inoculated. in one case, inoculated with  s. intermedius, the ascending infection could be shown to pass the intact membranes reaching the amniotic fluid. it is concluded that endocervical bacteria in the indigenous microflora might cause pregnancy complications by establishing  ascending infection. furthermore, as the bacteria tested have been implicated in  premature rupture of the membranes, an aetiological role of ascending infection in this pregnancy complication is postulated.
TIHT== 
ABHT== 

PMID== 7029235
TI  == amniotic fluid activity against bacteroides fragilis and group b streptococci.
AB  == the antimicrobial capacity of amniotic fluid (af) against b. fragilis, group b streptococci and escherichia coli, the latter as a reference indicator, was investigated in samples from 30 patients. in order to study trimester as well as  individual variations in the antibacterial activity, 10 individual samples from each trimester of pregnancy (af1, af2, af3), were separately tested. with b. fragilis all trimester samples showed initial inhibition lasting for 8 h, the bacteria then regaining growth capacity in all af1, and the majority of af2 and af3 specimens. however, 4 af2 and 3 af3 samples showed continued bacteriostatic activity for up to 24 h. group b streptococci exhibited uninhibited growth in all trimester samples. the growth of e. coli in af1 and af2 was not inhibited, whereas in af3 a temporary arrest was observed at 8 h, this being followed by growth to control levels at 24 h. the findings may explain the frequent isolation of b. fragilis from cases of septic abortions during the first trimester. individual variation in the effectiveness of the antibacterial activity against b. fragilis in af2 and af3 may explain why this microorganism, which is often implicated in severe maternal and neonatal infections, is occasionally recovered  from the mother's endocervix without signs of disease. the inefficacy of af in defence against group b streptococci correlates well with the frequent isolation  of these bacteria from cases of severe congenital infections associated with premature delivery.
TIHT== 
ABHT== 

PMID== 7024394
TI  == [the bacteriostatic and bactericidal effect of amniotic fluid (author's transl)].
AB  == the bacteriostatic and bactericidal effect of 100 samples of amniotic fluid (la)  was studied against 5 bacterial species that are responsible for neonatal infections. these results show that there is a bacteriostatic activity in liquor. 52 specimens of liquor amnii (52%) were shown to be active against at least one of the 5 bacterial specimens studied. 32 samples of liquor (32%) were active against listeria monocytogenes, 21 (21%) against flavobacterium meningosepticum,  18 (18%) against escherichia coli, 17 (17%) against group b streptococci and 7 (7%) against bacteroides fragilis. a simultaneous study of the 6 types of germs show a separate characteristics of this activity. in this way the number of samples of liquor that were active against one or at the same time against 2, 3,  4 or 5 bacteria were respectively 24, 19, 5, 2 and 2. the bacteriostatic effect was more frequently active in those samples of liquor which were studied near term (57.5%) than in the samples studied nearer the beginning of pregnancy (31.5%). all the same, this difference is not statistically significant. there was no difference in the antibacterial activity of samples of liquor from normal  and from abnormal pregnancies. the bacterial effect was found only in 12% of samples of liquor, particularly against streptococcus b (8%) and against listeria monocytogenes (4%). this bactericidal effect was only found after the 31st week of amenorrhoea.
TIHT== 
ABHT== 

PMID== 518080
TI  == in vitro activity of ly127935.
AB  == ly127935 is a unique new beta-lactam antibiotic. its activity against 536 clinical isolates was studied by using microdilution methods of susceptibility testing and compared with the activities of cefamandole, cefoxitin, and cephalothin. the lowest concentrations required to inhibit at least 90% of strains tested (mic(90)s) of ly127935 for staphylococcus aureus, streptococcus pyogenes, streptococcus agalactiae, and streptococcus pneumoniae ranged from 2 to 8 mug/ml. the mic(90)s for other staphylococci and streptococci were higher. the  mic(90)s for enterobacteriaceae and pseudomonas species ranged from 0.12 to 8 mug/ml and 8 to >32 mug/ml, respectively. the mic(90)s for anaerobes ranged from  2 to >32 mug/ml. as determined by mic(90)s, ly127935 was consistently the least active antibiotic against facultatively anaerobic gram-positive cocci and the most active against aerobic and facultatively anaerobic gram-negative bacilli. its position with respect to activity against anaerobes varied from being the most active against bacteroides fragilis and clostridium perfringens to the least active against anaerobic cocci. in a population of multidrug-resistant isolates,  concentrations of 8 mug or less of ly127935 per ml inhibited 82% of enterobacteriaceae; concentrations of 32 mug or less per ml inhibited 100% of enterobacteriaceae and 40% of p. aeruginosa. increasing the inoculum size by 100-fold did not increase the minimal inhibitory concentrations of ly127935 or cefoxitin but did increase minimal inhibitory concentrations of cefamandole and cephalothin for some enterobacteriaceae. all four drugs were bactericidal; minimal bactericidal concentrations were the same or one concentration higher than minimal inhibitory concentrations for 91 to 96% of strains tested. the broad spectrum and marked in vitro activity of ly127935 make it a promising new antibiotic.
TIHT== 
ABHT== 

PMID== 319288
TI  == neonatal sepsis at the johns hopkins hospital, 1969-1975: bacterial isolates and  clinical correlates.
AB  == the experience with neonatal sepsis at the johns hopkins hospital during 1969-1975 was reviewed. major pathogens included escherichia coli, group b streptococcus, other streptococci, and klebsiella. nineteen percent of coliform isolates were kanamycin-resistant. the frequency of recovery of e. coli was increased in early-onset sepsis, and the frequency of recovery of klebsiella was  increased in late-onset sepsis. the mortality rate was 23%. the frequency of recovery of e. coli was increased in fatal cases, and mortality was highly correlated with the presence of gastrointestinal catastrophe. ampicillin and gentamicin are the initial antibiotics of choice for neonatal sepsis at this institution; a penicillinase-resistant penicillin should be added when staphylococcus aureus involvement is likely, and addition of chloramphenicol or clindamycin should be considered for infants at increased risk for bacteroides fragilis sepsis.
TIHT== 
ABHT== 

PMID== 793391
TI  == aerobic and anaerobic flora of the cervix during pregnancy and the puerperium.
AB  == comparison of species of bacteria isolated from patients with endometritis with species isolated from normal pregnant and nonpregnant women suggests that bacteria causing infections are indigenous to the genital tract. however, complete studies of the flora of pregnant women, especially anaerobic flora, are  lacking. aerobic and anaerobic cultures of the endocervix were obtained from women in all trimesters of pregnancy and at three days and six weeks post partum. the incidence of occurrence of each species of bacteria and the average number of different species per culture were determined for each period. the most prevalent organisms in each period were aerobic gram-positive rods and cocci and anaerobic  gram-positive cocci. the average number of species of aerobic bacteria per culture remained approximately the same in each culture period. the average number of anaerobic species per culture decreased as pregnancy progressed, peaked on the third postpartum day, and at six weeks post partum returned to a level similar to that of the first trimester.
TIHT== 
ABHT== 

