@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 18397461
TI  == the lower genital tract microbiota in relation to cytokine-, slpi- and endotoxin  levels: application of checkerboard dna-dna hybridization (cdh).
AB  == in the present study the lower genital tract microbiota in asymptomatic fertile women (n=34) was identified and quantified by culturing vaginal secretions. also, vaginal and cervical samples were analyzed by a semiquantitative checkerboard dna-dna hybridization technique (cdh) based on genomic probes prepared from 13 bacterial species (bacteroides ureolyticus, escherichia coli, fusobacterium nucleatum, gardnerella vaginalis, mobiluncus curtisii ss curtisii, prevotella bivia, prevotella disiens, prevotella melaninogenica, atopobium vaginae, lactobacillus iners, staphylococcus aureus ss aureus, streptococcus anginosus, and streptococcus agalactiae). the bacterial species found by either culture or cdh were correlated with proinflammatory cytokines (il-1 alpha, il-1 beta, il-6,  il-8), secretory leukocyte protease inhibitor (slpi), and endotoxin in the cervicovaginal samples. grading the women into healthy, intermediate, or bacterial vaginosis (bv) as based on gram staining of vaginal smears, the viable  counts of lactobacilli (l. gasseri) and of streptococci-staphylococci combined were highest in the intermediate group. in bv, particularly the high concentrations of actinomyces urogenitalis, atopobium vaginae, and peptoniphilus  harei were noted (>or=10(11) per ml). the total viable counts correlated with both cervical il-1 alpha and il-1 beta. a strong negative correlation was observed between l. iners and total viable counts, g. vaginalis, or cervical il-1 alpha, while it correlated positively with slpi. analysis of vaginal and cervical samples from 26 out of the 34 women by cdh showed that anaerobic bacteria were more frequently detected by cdh compared to culture. by this method, a. vaginae correlated with g. vaginalis, and l. iners with s. aureus. with regard to cytokines, b. ureolyticus correlated with both cervical and vaginal il-1 alpha as well as with cervical il-8, while f. nucleatum, s. agalactiae, s. anginosus, or s. aureus correlated with vaginal il-1 alpha. furthermore, all gram-negative bacteria taken together, as measured by cdh, correlated with vaginal endotoxin and inversely with vaginal slpi. the significance of the results is discussed. in summary, mapping of the identity and quantity of vaginal bacterial species and their association with locally produced host innate immune factors will help in defining various types of abnormal vaginal microbiota, developing new ways of assessing the risk of ascending subclinical infections, and in treating them. cdh appears to be a suitable tool for future analyses of large numbers of clinical samples with an extended number of bacterial probes.
TIHT== 
ABHT== 

PMID== 10895689
TI  == proteolysis and utilization of albumin by enrichment cultures of subgingival microbiota.
AB  == subgingival dental plaque consists mainly of microorganisms that derive their energy from amino acid fermentation. their nutrient requirements are met by the subgingival proteolytic system, which includes proteases from microorganism and inflammatory cells, and substrate proteins from sulcus exudate, including albumin. to determine the selective effect of individual proteins on microbiota,  we used albumin as the main substrate for growth. eight subgingval plaque samples from untreated periodontal pockets of patients with adult periodontitis were inoculated in peptone yeast medium with bovine albumin (9 g/l). after three subculture steps, cell yields of the enrichment cultures at the medium with 0, 1.25, 2.5, 5, 10, and 20 g/l albumin were determined. proteolytic activity (u/absorbance at 550 nm) of the enrichment cultures and different isolates derived from the cultures was estimated by the degradation of resorufin-labeled casein. it was observed that the yield of the mixed culture was albumin limited,  and the proteolytic activities of the cultures in albumin broth were higher than  in control (peptone broth). among the isolates from the enrichment cultures, peptostreptococcus micros, prevotella melaninogenica, prevotella buccae and prevotella bivia demonstrated proteolysis. the frequent occurrence of streptococcus gordonii and streptococcus anginosus in the albumin cultures is explained by their ability to utilize arginine as an energy source for growth. albumin in the medium was partly degraded by pure cultures but completely consumed in enrichment cultures, indicating synergy of bacterial proteinases. it  is concluded that the subgingival microbiota possesses proteolytic activity and may use albumin as a substrate for their growth. enrichment cultures on albumin may serve as a relatively simple in vitro model to evaluate the effects of proteinase inhibitors.
TIHT== 
ABHT== 

