@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25761675
TI  == a filifactor alocis-centered co-occurrence group associates with periodontitis across different oral habitats.
AB  == periodontitis is a highly prevalent polymicrobial disease worldwide, yet the synergistic pattern of the multiple oral pathogens involved is still poorly characterized. here, saliva, supragingival and subgingival plaque samples from periodontitis patients and periodontally healthy volunteers were collected and profiled with 16s rrna gene pyrosequencing. different oral habitats harbored significantly different microbiota, and segregation of microbiota composition between periodontitis and health was observed as well. two-step redundancy analysis identified twenty-one otus, including porphyromonas gingivalis, tannerella forsythia and filifactor alocis, as potential pathogens that were significantly associated with periodontitis and with two periodontitis diagnostic parameters (pocket depth and attachment loss) in both saliva and supragingival plaque habitats. interestingly, pairwise correlation analysis among the 21 otus revealed that filifactor alocis was positively correlated with seven other putative pathogens (r > 0.6, p < 0.05), forming a co-occurrence group that was remarkably enriched in all three habitats of periodontitis patients. this bacterial cluster showed a higher diagnostic value for periodontitis than did any individual potential pathogens, especially in saliva. thus, our study identified  a potential synergistic ecological pattern involving eight co-infecting pathogens across various oral habitats, providing a new framework for understanding the etiology of periodontitis and developing new diagnoses and therapies.
TIHT== 
ABHT== 

PMID== 25678835
TI  == anaerobic culture to detect periodontal and caries pathogens.
AB  == background: anaerobic culture has been critical in our understanding of the oral  microbiotas. highlight: studies in advanced periodontitis in the 1970's revealed  microbial complexes that associated with different clinical presentations. taxonomy studies identified species newly-observed in periodontitis as aggregatibacter (actinobacillus) actinomycetemcomitans, campylobacter (wolinella) rectus and other campylobacter species, and tannerella (bacteroides) forsythia. anaerobic culture of initial periodontitis showed overlap in the microbiota with  gingivitis, and added selenomonas noxia and filifactor alocis as putative periodontal pathogens. porphyromonas gingivalis and t. forsythia were found to be associated with initial periodontitis in adults. the dominant microbiota of dental caries differs from that of periodontitis. the major cariogenic species are acidogenic and acid tolerant species particularly streptococcus mutans, and lactobacillus and bifidobacterium species. anaerobic culture of severe early childhood caries revealed a widely diverse microbiota, comparable to that observed using cloning and sequencing. the pcr-based cloning approach, however, underestimated actinobacteria compared with culture. only a subset of the caries-associated microbiota was acid tolerant, with different segments of the microbiota cultured on blood agar compared to a low ph acid agar. while the major caries-associated species was s. mutans, a new species, scardovia wiggsiae, was significantly associated with early childhood caries. higher counts of s. wiggsiae were also observed in initial white spot carious lesions in adolescents. conclusion: in periodontitis and dental caries, anaerobic culture studies of advanced disease provided a comprehensive analysis of the microbiota of these infections. anaerobic culture highlighted the limitation of pcr with standard primers that underestimate detection of actinobacteria.
TIHT== 
ABHT== 

PMID== 25040261
TI  == quantitative analysis of classical and new putative periodontal pathogens in subgingival biofilm: a case-control study.
AB  == background and objectives: a number of species/phylotypes have been newly implicated as putative periopathogens. the objective of this study was to explore associations among classical and new pathogens in subgingival biofilm and to assess their relative importance to chronic periodontitis. material and methods:  pooled subgingival biofilm samples were obtained from 40 patients with chronic periodontitis and 40 healthy controls. taqman q-pcr assays were used to determine the absolute and relative counts of porphyromonas gingivalis, tannerella forsythia, treponema denticola, parvimonas micra, filifactor alocis, oral synergistetes and oral tm7s. microbial associations were assessed using cluster analysis. different statistical models were used to explore associations between  microbial parameters and periodontitis. results: the median log and relative counts were lowest for tm7s (4.4 and 0.0016%, respectively) and highest for oral  synergistetes (7.2 and 1.4%, respectively). oral synergistetes clustered strongly with the red complex, particularly t. forsythia (100% rescaled similarity). all species/phylotypes except tm7s were significantly associated with periodontitis (mann-whitney test; p </= 0.005). however, p. gingivalis and f. alocis lost association after adjusting for confounders (ordinal regression). in receiving operator characteristic curve analysis, the log counts of oral synergistetes were the best markers of periodontitis (82.5% sensitivity and specificity), followed by those of t. forsythia, p. micra and t. denticola. in prediction analysis, however, p. micra was the only microbial predictor of periodontal parameters. conclusions: oral synergistetes are presented here as new members of the red complex, with relative importance to periodontitis exceeding that of the classical members. p. micra is shown as an important periodontal pathogen warranting more attention.
TIHT== 
ABHT== 

PMID== 24579762
TI  == bacteria community study of combined periodontal-endodontic lesions using denaturing gradient gel electrophoresis and sequencing analysis.
AB  == background: the entire microbial population and predominant microflora of root canals (rcs) and adjacent periodontal pockets (pps) from teeth with combined periodontal-endodontic lesions were determined and compared. methods: pooled rc and pp samples were collected from the molars of 20 patients diagnosed with combined periodontal-endodontic lesions. dna was extracted for polymerase chain reaction-based denaturing gradient gel electrophoresis (pcr-dgge), cloning, and sequence analysis. a coefficient of similarity (cs) was used to determine the similarity of the bacterial profiles from rcs and pps. results: significantly fewer bands were produced by pcr-dgge from rcs (5.9 +/- 1.7) than from pps (8.0 +/- 1.8) (p <0.001). the average cs of the rc and pp samples was 93.81% +/- 10.26%. overall, 60 genera/species were identified by sequencing. of these, the predominant genera in rcs were porphyromonas sp. (13.9%), filifactor sp. (12.5%), and parvimonas sp. (11.1%), similar to the genera obtained from pp samples. in total, 43 genera/species were common to the rc and pp samples. the most prevalent bacteria in both the rc and pp samples were (in descending order) filifactor alocis, parvimonas micra, porphyromonas gingivalis, and tannerella forsythia. conclusions: the high similarity in the sets of organisms present in both rc and  pp samples in this study suggests that the pocket could be a source of rc infection. the data also demonstrate that combined periodontal-endodontic lesions consist of a diverse and complex microbial community.
TIHT== 
ABHT== 

PMID== 22326171
TI  == molecular analysis of 16s rrna genes identifies potentially periodontal pathogenic bacteria and archaea in the plaque of partially erupted third molars.
AB  == purpose: small subunit rrna sequencing and phylogenetic analysis were used to identify cultivable and uncultivable microorganisms present in the dental plaque  of symptomatic and asymptomatic partially erupted third molars to determine the prevalence of putative periodontal pathogens in pericoronal sites. materials and  methods: template dna prepared from subgingival plaque collected from partially erupted symptomatic and asymptomatic mandibular third molars and healthy incisors was used in polymerase chain reaction with broad-range oligonucleotide primers to amplify 16s rrna bacterial and archaeal genes. amplicons were cloned, sequenced,  and compared with known nucleotide sequences in online databases to identify the  microorganisms present. results: two thousand three hundred two clones from the plaque of 12 patients carried bacterial sequences from 63 genera belonging to 11  phyla, including members of the uncultivable tm7, sr1, and chloroflexi, and difficult-to-cultivate synergistetes and spirochaetes. dialister invisus, filifactor alocis, fusobacterium nucleatum, porphyromonas endodontalis, prevotella denticola, tannerella forsythia, and treponema denticola, which have been associated with periodontal disease, were found in significantly greater abundance in pericoronal compared with incisor sites. dialister invisus and f nucleatum were found in greater abundance in sites exhibiting clinical symptoms.  the archaeal species, methanobrevibacter oralis, which has been associated with severe periodontitis, was found in 3 symptomatic patients. conclusions: these findings have provided new insights into the complex microbiota of pericoronitis. several bacterial and archaeal species implicated in periodontal disease were recovered in greater incidence and abundance from the plaque of partially erupted third molars compared with incisors, supporting the hypothesis that the pericoronal region may provide a favored niche for periodontal pathogens in otherwise healthy mouths.
TIHT== 
ABHT== 

PMID== 22324467
TI  == impact of periodontal therapy on the subgingival microbiota of severe periodontitis: comparison between good responders and individuals with refractory periodontitis using the human oral microbe identification microarray.
AB  == background: this study compares the changes to the subgingival microbiota of individuals with "refractory" periodontitis (rp) or treatable periodontitis (good responders [gr]) before and after periodontal therapy by using the human oral microbe identification microarray (homim) analysis. methods: individuals with chronic periodontitis were classified as rp (n = 17) based on mean attachment loss (al) and/or >3 sites with al >/=2.5 mm after scaling and root planing, surgery, and systemically administered amoxicillin and metronidazole or as gr (n  = 30) based on mean attachment gain and no sites with al >/=2.5 mm after treatment. subgingival plaque samples were taken at baseline and 15 months after  treatment and analyzed for the presence of 300 species by homim analysis. significant differences in taxa before and post-therapy were sought using the wilcoxon test. results: the majority of species evaluated decreased in prevalence in both groups after treatment; however, only a small subset of organisms was significantly affected. species that increased or persisted in high frequency in  rp but were significantly reduced in gr included bacteroidetes sp., porphyromonas endodontalis, porphyromonas gingivalis, prevotella spp., tannerella forsythia, dialister spp., selenomonas spp., catonella morbi, eubacterium spp., filifactor alocis, parvimonas micra, peptostreptococcus sp. ot113, fusobacterium sp. ot203,  pseudoramibacter alactolyticus, streptococcus intermedius or streptococcus constellatus, and shuttlesworthia satelles. in contrast, capnocytophaga sputigena, cardiobacterium hominis, gemella haemolysans, haemophilus parainfluenzae, kingella oralis, lautropia mirabilis, neisseria elongata, rothia  dentocariosa, streptococcus australis, and veillonella spp. were more associated  with therapeutic success. conclusion: persistence of putative and novel periodontal pathogens, as well as low prevalence of beneficial species was associated with chronic refractory periodontitis.
TIHT== 
ABHT== 

PMID== 19722792
TI  == comparisons of subgingival microbial profiles of refractory periodontitis, severe periodontitis, and periodontal health using the human oral microbe identification microarray.
AB  == background: this study compared the subgingival microbiota of subjects with refractory periodontitis (rp) to those in subjects with treatable periodontitis (grs = good responders) or periodontal health (ph) using the human oral microbe identification microarray (homim). methods: at baseline, subgingival plaque samples were taken from 47 subjects with periodontitis and 20 individuals with ph and analyzed for the presence of 300 species by homim. the subjects with periodontitis were classified as having rp (n = 17) based on mean attachment loss (al) and/or more than three sites with al >or=2.5 mm after scaling and root planing, surgery, and systemically administered amoxicillin and metronidazole or  as grs (n = 30) based on mean attachment gain and no sites with al >or=2.5 mm after treatment. significant differences in taxa among the groups were sought using the kruskal-wallis and chi(2) tests. results: more species were detected in patients with disease (gr or rp) than in those without disease (ph). subjects with rp were distinguished from grs or those with ph by a significantly higher frequency of putative periodontal pathogens, such as parvimonas micra (previously peptostreptococcus micros or micromonas micros), campylobacter gracilis, eubacterium nodatum, selenomonas noxia, tannerella forsythia (previously t. forsythensis), porphyromonas gingivalis, prevotella spp., treponema spp., and eikenella corrodens, as well as unusual species (pseudoramibacter alactolyticus,  tm7 spp. oral taxon [ot] 346/356, bacteroidetes sp. ot 272/274, solobacterium moorei, desulfobulbus sp. ot 041, brevundimonas diminuta, sphaerocytophaga sp. ot 337, shuttleworthia satelles, filifactor alocis, dialister invisus/pneumosintes,  granulicatella adiacens, mogibacterium timidum, veillonella atypica, mycoplasma salivarium, synergistes sp. cluster ii, and acidaminococcaceae [g-1] sp. ot 132/150/155/148/135) (p <0.05). species that were more prevalent in subjects with ph than in patients with periodontitis included actinomyces sp. ot 170, actinomyces spp. cluster i, capnocytophaga sputigena, cardiobacterium hominis, haemophilus parainfluenzae, lautropia mirabilis, propionibacterium propionicum, rothia dentocariosa/mucilaginosa, and streptococcus sanguinis (p <0.05). conclusion: as determined by homim, patients with rp presented a distinct microbial profile compared to patients in the gr and ph groups.
TIHT== 
ABHT== 

PMID== 18436030
TI  == microbial analysis of canals of root-filled teeth with periapical lesions using polymerase chain reaction.
AB  == the objective of the present study was to investigate the presence of nine bacterial species in root-filled teeth associated with periapical lesions using a polymerase chain reaction analysis and to correlate these species with clinical features of the cases. dna was extracted from 45 canal samples of root-filled teeth with periapical lesions. a pcr assay using species-specific primers of 16s  rdna and the downstream intergenic spacer region was used for microbial detection. enterococcus faecalis was the most prevalent species, detected in 77.8% of the study teeth, followed by peptostreptococcus micros, detected in 51.1%. porphyromonas gingivalis, porphyromonas endodontalis, prevotella intermedia, and prevotella nigrescens were detected in 35.6%, 22.2%, 11.1%, and 11.1% of the sampled teeth, respectively. moreover, pcr detected filifactor alocis in 26.7%, treponema denticola in 24.4%, and tannerella forsythia in 4.4% of the samples. t. denticola and p. micros were statistically associated with tenderness to percussion (p < 0.05). p. nigrescens was associated with the presence of spontaneous pain and abscess (p < 0.05). p. endodontalis and p. nigrescens were associated with purulent exudates (p < 0.05). synergistic relationship was also observed between some species. the results of this study indicated that e. faecalis was the most frequently identified test species by pcr in teeth with failing endodontic treatment.
TIHT== 
ABHT== 

PMID== 17949344
TI  == bacterial examination of endodontic infections by clonal analysis in concert with denaturing high-performance liquid chromatography.
AB  == background/aims: the aim of this study was to examine the diversity of bacterial  species in the infected root canals of teeth associated with endodontic abscesses by cloning and sequencing techniques in concert with denaturing high-performance  liquid chromatography. methods: samples collected from five infected root canals  were subjected to polymerase chain reaction (pcr) with universal 16s ribosomal dna primers. products of these pcrs were cloned and sequenced. denaturing high-performance liquid chromatography (dhplc) was used as a screening method to  reduce the number of clones necessary for dna sequencing. results: all samples were positive for the presence of bacteria and a range of 7-13 different bacteria were found per root canal sample. in total, 48 different oral clones were detected among the five root canal samples. olsenella profusa was the only species present in all samples. porphyromonas gingivalis, dialister pneumosintes, dialister invisus, lachnospiraceae oral clone, staphylococcus aureus, pseudoramibacter alactolyticus, peptostreptococcus micros and enterococcus faecalis were found in two of the five samples. the majority of the taxa were present in only one sample, for example tannerella forsythia, shuttleworthia satelles and filifactor alocis. some facultative anaerobes that are frequently isolated from endodontic infections such as e. faecalis, streptococcus anginosus  and lactobacillus spp. were also found in this study. conclusion: clonal analysis of the microflora associated with endodontic infections revealed a wide diversity of oral species.
TIHT== 
ABHT== 

PMID== 17174667
TI  == prevalence of selected bacterial named species and uncultivated phylotypes in endodontic abscesses from two geographic locations.
AB  == evidence is mounting that the prevalence of some putative endodontic pathogens can significantly vary according to the geographic location in which samples were taken. this study aimed to provide additional knowledge on this subject by comparing the frequencies of 10 selected candidate endodontic pathogens in samples of acute apical abscesses obtained from two distinct geographic locations; portland, or, and rio de janeiro, brazil. dna was extracted from aspirates and used as template in nested pcr assays using 16s rrna gene taxon-specific oligonucleotide primers. of the target species/phylotypes, treponema denticola (73% of the cases), porphyromonas endodontalis (70%), and tannerella forsythia (57%) were the most prevalent taxa found in brazilian samples. dialister invisus (70% of the cases), p. endodontalis (63%) and dialister pneumosintes (55%) were the most frequent taxa in the portland, or samples. data analysis revealed that t. denticola and t. forsythia were significantly more detected in brazilian samples than in the portland, or samples. although d. invisus, filifactor alocis, and synergistes oral clone w090  were detected in many more samples from the portland, or patients, differences were not found to be statistically significant. these findings confirmed that some bacterial taxa can markedly differ in the frequencies they occur in samples  from different locations. it remains to be clarified whether this observation translates into relevant therapeutic implications.
TIHT== 
ABHT== 

PMID== 16982268
TI  == molecular analysis of filifactor alocis, tannerella forsythia, and treponema denticola associated with primary endodontic infections and failed endodontic treatment.
AB  == the aim of this study was to investigate the presence of strict anaerobes such as filifactor alocis, tannerella forsythia, and treponema denticola in primary and secondary root-infected canals with periapical lesions by molecular analysis and  the association of these species with specific endodontic signs and symptoms. microbial samples were taken from 100 root canals, 50 with necrotic pulp tissues  (npt, primary infection), and 50 with failed endodontic treatment (fet, secondary infection). dna was extracted from the samples, which were analyzed for the presence of three endodontic pathogens using species-specific primers and pcr. f. alocis were isolated from 23 canals with npt and 12 canals with fet; t. forsythia from 12 canals with npt and three canals with fet; t. denticola from 19 canals with npt and 12 canals with tep. suggested associations were found between primary infection and the presence of f. alocis and t. forsythia (both p < 0.05). in particular, associations were found between: pain and f. alocis; swelling and  f. alocis; tenderness to percussion and t. forsythia; mobility and t. forsythia and t. denticola; wet canals and f. alocis, t. forsythia, and t. denticola; purulent exsudate and f. alocis, t. forsythia and t. denticola; abscess and f. alocis, t. forsythia, and t. denticola (all p < 0.05). the findings of this study indicated that f. alocis, t. forsythia, and t. denticola seem to be associated with endodontic signs and symptoms. additionally, f. alocis and t. forsythia were detected more frequently in teeth with necrotic pulp than in teeth with failing endodontic treatment.
TIHT== 
ABHT== 

PMID== 15829891
TI  == differences in prevalence of selected bacterial species in primary endodontic infections from two distinct geographic locations.
AB  == objective: this study intended to compare the prevalence of 7 putative endodontic pathogens in samples of primary endodontic infections taken from patients of 2 distant geographic locations. study design: samples from infected root canals associated with asymptomatic periradicular lesions or from pus aspirated from acute periradicular abscesses were collected from patients in rio de janeiro, brazil, and seoul, south korea. south korean samples were frozen and delivered to brazil, where all steps in the molecular analysis were performed. dna was extracted and a species-specific nested polymerase chain reaction assay was used  to detect 7 target bacterial species. results: the most prevalent species detected in brazilian samples were porphyromonas endodontalis (79% of the cases)  , treponema denticola (79%), and dialister pneumosintes (76%). the most prevalent species found in south korean samples were fusobacterium nucleatum (38% of the cases) , tannerella forsythia (26%), and treponema maltophilum (24%). overall, p  endodontalis, d pneumosintes, filifactor alocis, t denticola, and t forsythia were significantly more detected in brazilian samples than in south korean samples ( p < .05). conclusions: findings indicated that the prevalence of some species in infections of endodontic origin may significantly differ from one geographic location to another.
TIHT== 
ABHT== 

