@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 1917844
TI  == phylogenetic analysis of the spirochetes.
AB  == the 16s rrna sequences were determined for species of spirochaeta, treponema, borrelia, leptospira, leptonema, and serpula, using a modified sanger method of direct rna sequencing. analysis of aligned 16s rrna sequences indicated that the  spirochetes form a coherent taxon composed of six major clusters or groups. the first group, termed the treponemes, was divided into two subgroups. the first treponeme subgroup consisted of treponema pallidum, treponema phagedenis, treponema denticola, a thermophilic spirochete strain, and two species of spirochaeta, spirochaeta zuelzerae and spirochaeta stenostrepta, with an average  interspecies similarity of 89.9%. the second treponeme subgroup contained treponema bryantii, treponema pectinovorum, treponema saccharophilum, treponema succinifaciens, and rumen strain ca, with an average interspecies similarity of 86.2%. the average interspecies similarity between the two treponeme subgroups was 84.2%. the division of the treponemes into two subgroups was verified by single-base signature analysis. the second spirochete group contained spirochaeta aurantia, spirochaeta halophila, spirochaeta bajacaliforniensis, spirochaeta litoralis, and spirochaeta isovalerica, with an average similarity of 87.4%. the  spirochaeta group was related to the treponeme group, with an average similarity  of 81.9%. the third spirochete group contained borrelias, including borrelia burgdorferi, borrelia anserina, borrelia hermsii, and a rabbit tick strain. the borrelias formed a tight phylogenetic cluster, with average similarity of 97%. the borrelia group shared a common branch with the spirochaeta group and was closer to this group than to the treponemes. a single spirochete strain isolated  fromt the shew constituted the fourth group. the fifth group was composed of strains of serpula (treponema) hyodysenteriae and serpula (treponema) innocens. the two species of this group were closely related, with a similarity of greater  than 99%. leptonema illini, leptospira biflexa, and leptospira interrogans formed the sixth and most deeply branching group. the average similarity within this group was 83.2%. this study represents the first demonstration that pathogenic and saprophytic leptospira species are phylogenetically related. the division of  the spirochetes into six major phylogenetic clusters was defined also by sequence signature elements. these signature analyses supported the conclusion that the spirochetes represent a monophylectic bacterial phylum.
TIHT== 
ABHT== 

PMID== 6292162
TI  == enzymatic activities for interconversion of purines in spirochetes.
AB  == enzymatic activities that catalyze the interconversion of purines and purine derivatives were detected in cell extracts of spirochaeta aurantia, spirochaeta stenostrepta, treponema succinifaciens, and treponema denticola. phosphoribosyltransferase activities present in cell extracts of each of the four spirochete species functioned in the conversion of adenine, hypoxanthine, and guanine to amp, imp, and gmp, respectively. nucleotidase activities in the extracts mediated the formation of nucleosides from nucleotides. the conversion of adenosine, inosine, and guanosine to the respective purine bases was catalyzed by nucleoside phosphorylase and, in some instances, by nucleoside hydrolase activities. guanine deaminase activity was found in both s. aurantia and s. stenostrepta, whereas adenosine deaminase activity was detected only in s. aurantia. adenine deaminase activity in t. succinifaciens extracts was sensitive  to o2 and was relatively resistant to heating. our results indicate that the four species of spirochetes studied possess a broad spectrum of purine interconversion enzymes. it is suggested that these enzymes may function in metabolic processes important for the survival of spirochetes in nutrient-poor natural environments.
TIHT== 
ABHT== 

