@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 23163048
TI  == [role of infectious agents in the emergence of malignant tumors].
AB  == according to the data of the international agency for research on cancer (iarc),  at least 6 virus species (hpv, ebv, hhv-8/kshv, htlv-1, hbv, hcv), 4 helminthes species (schistosoma haematobium and japonicum, opisthorchis viverrini, clonorchis sinensis) and i bacterium species (helicobacter pylori) have been proved to be capable of causing the development of cancer. the analysis of the data available shows that merkel cell polyomavirus (mcv), herpes simplex virus (hsv), john cunningham polyomavirus (jcv), monkey virus 40 (sv40), cytomegalovirus (cmv), xenotropic murine leukemia virus (xmrv), helicobacter bilis and hepaticus, campylobacter jejuni, fusobacterium varium, enteropathogenic escherichia coli, enterotoxigenic bacteroides fragilis, bacteroides vulgatus, prevotella spp., streptococcus bovis and anginosus, treponema denticola, salmonella typhi, paratyphi and typhimurium, borrelia burgdorferi, bartonella spp., mycobacterium tuberculosis, chlamydia pneumoniae, trachomatis and psittaci, neisseria gonorrhoeae, propionibacterium acnes, tropheryma whippelii, schistosoma mansoni, opistorchis felineus, strongyloides stercoralis, taenia solium, candida  spp., paracoccidioides brasiliensis, histoplasma capsulatum and trichomonas vaginalis can also be potential etiological agents of cancer. apparently, detection of new associations between infectious agents and risk of the development of cancer will facilitate progress in elaboration of prophylaxis measures, early diagnostic methods and, probably, methods of treatment of malignant tumors.
TIHT== 
ABHT== 

PMID== 18165360
TI  == factors and selenocysteine insertion sequence requirements for the synthesis of selenoproteins from a gram-positive anaerobe in escherichia coli.
AB  == selenoprotein synthesis in escherichia coli strictly depends on the presence of a specific selenocysteine insertion sequence (secis) following the selenocysteine-encoding uga codon of the respective mrna. it is recognized by the selenocysteine-specific elongation factor selb, leading to cotranslational insertion of selenocysteine into the nascent polypeptide chain. the synthesis of  three different selenoproteins from the gram-positive anaerobe eubacterium acidaminophilum in e. coli was studied. incorporation of (75)se into glycine reductase protein b (grdb1), the peroxiredoxin prxu, and selenophosphate synthetase (seld1) was negligible in an e. coli wild-type strain and was fully absent in an e. coli selb mutant. selenoprotein synthesis, however, was strongly  increased if selb and selc (trna(sec)) from e. acidaminophilum were coexpressed.  putative secondary structures downstream of the uga codons did not show any sequence similarity to each other or to the e. coli secis element. however, mutations in these structures strongly reduced the amount of (75)se-labeled protein, indicating that they indeed act as secis elements. uga readthrough mediated by the three different secis elements was further analyzed using gst-lacz translational fusions. in the presence of selb and selc from e. acidaminophilum, uga readthrough was 36 to 64% compared to the respective cysteine-encoding ugc variant. uga readthrough of secis elements present in desulfomicrobium baculatum (hydv), treponema denticola (seld), and campylobacter  jejuni (selw-like gene) was also considerably enhanced in the presence of e. acidaminophilum selb and selc. this indicates recognition of these secis elements and might open new perspectives for heterologous selenoprotein synthesis in e. coli.
TIHT== 
ABHT== 

PMID== 15295960
TI  == implant therapy following liver transplantation: clinical and microbiological results after 10 years.
AB  == background: the number of immunocompromised patients is increasing as a consequence of successful organ transplantation. placing dental implants in these patients has been questioned because of their increased risk for infections. the  10-year follow-up data of a 71-year-old liver transplant recipient with long-term immunosuppressive therapy is reported. six months after liver transplantation, two interforaminal implants were inserted in the edentulous mandible, and an overdenture using non-rigid telescopic attachments was fabricated 3 months later. methods: oral clinical parameters included the modified plaque index, sulcus fluid flow rate, modified bleeding index, probing depth, distance implant mucosa, attachment level, width of the keratinized mucosa and mobility values. the distance implant bone (dib) was determined on digital panoramic radiographs. the  levels of eight periodontal marker organisms were established using dna probe technology. additionally, swabs of the edentulous oral mucosa were taken for microbiological culture and antimicrobial resistance testing. results: the peri-implant parameters were within normal ranges indicating a stable osseointegration with moderate vertical bone loss. actinobacillus actinomycetemcomitans, tannerella forsythensis, campylobacter rectus, and treponema denticola were not detected. low levels of porphyromonas gingivalis, fusobacterium nucleatum, and eikenella corrodens were found. prevotella intermedia was the only bacterium with a level higher than 10(4). the mucosal swabs indicated the presence of an abundant normal oral flora, including escherichia coli and candida albicans. the antibiogram revealed multiple resistance to antibiotics. conclusion: this case report suggests that immunocompromised patients can be successfully rehabilitated with dental implants.
TIHT== 
ABHT== 

