@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 17870199
TI  == possible involvement of psychrotolerant enterobacteriaceae in blown pack spoilage of vacuum-packaged raw meats.
AB  == recent investigations of blown pack spoilage in new zealand chilled vacuum-packaged meats have found moderate to high numbers of enterobacteriaceae in the spoilage flora, but no clostridia, such as c. estertheticum and c. gasigenes, that are usually associated with blown pack spoilage. this study showed that pyschrotolerant enterobacteriaceae produced gas in a lamb homogenate  model under anaerobic conditions and that these organisms could cause blown pack  spoilage of vacuum-packaged chilled meats. significant gas production was observed with the majority of the psychrotolerant enterobacteriaceae strains tested including presumptive species of enterobacter, serratia, hafnia and rahnella. however, no gas was produced in lamb homogenates inoculated with presumptive species of ewingella americana or yersinia enterocolitica. gas production was also confirmed in vacuum-packaged lamb shoulders stored at 4 degrees c for 21 days after being inoculated with individual representative enterobacteriaceae isolates. biochemical characterisation proved to be more useful than genotype-based typing of 16s rrna genes for discriminating different  psychrotolerant enterobacteriaceae from naturally contaminated meat microflora.
TIHT== 
ABHT== 

PMID== 12384342
TI  == identification of a chromosome-borne expanded-spectrum class a beta-lactamase from erwinia persicina.
AB  == from whole-cell dna of an enterobacterial erwinia persicina reference strain that displayed a penicillinase-related antibiotic-resistant phenotype, a beta-lactamase gene was cloned and expressed in escherichia coli. it encoded a clavulanic-acid-inhibited ambler class a beta-lactamase, erp-1, with a pi value of 8.1 and a relative molecular mass of ca. 28 kda. erp-1 shared 45 to 50% amino  acid identity with the most closely related enzymes, the chromosomally encoded enzymes from citrobacter koseri, kluyvera ascorbata, kluyvera cryocrescens, klebsiella oxytoca, proteus vulgaris, proteus penneri, rahnella aquatilis, serratia fonticola, yersinia enterocolitica, and the plasmid-mediated enzymes ctx-m-8 and ctx-m-9. the substrate profile of the noninducible erp-1 was similar  to that of these beta-lactamases. erp-1 is the first extended-spectrum beta-lactamase from an enterobacterial species that is plant associated and plant pathogenic.
TIHT== 
ABHT== 

PMID== 9464403
TI  == identification of bacterial isolates obtained from intestinal contents associated with 12,000-year-old mastodon remains.
AB  == mastodon (mammut americanum) remains unearthed during excavation of ancient sediments usually consist only of skeletal material, due to postmortem decomposition of soft tissues by microorganisms. two recent excavations of skeletal remains in anoxic sediments in ohio and michigan, however, have uncovered organic masses which appear to be remnants of the small and large intestines, respectively. macrobotanical examinations of the composition of these masses revealed assemblages of plant material radiocarbon dated to approximately  11,500 years before the present and thought to be incompletely digested food remains from this extinct mammal. we attempted to cultivate and identify bacteria from the intestinal contents, bone-associated sediments, and sediments not in proximity to the remains using a variety of general and selective media. in all,  295 isolates were cultivated, and 38 individual taxa were identified by fatty acid-methyl ester (fame) profiles and biochemical characteristics (api-20e). the  taxonomic positions of selected enteric and obligately anaerobic bacteria were confirmed by 16s ribosomal dna (rdna) sequencing. results indicate that the intestinal and bone-associated samples contained the greatest diversity of bacterial taxa and that members of the family enterobacteriaceae represented 41%  of all isolates and were predominant in the intestinal masses and sediments in proximity to the skeleton but were uncommon in the background sediments. enterobacter cloacae was the most commonly identified isolate, and partial rdna sequencing revealed that rahnella aquatilis was the correct identity of strains suggested by fame profiles to be yersinia enterocolitica. no bacteroides spp. or  expected intestinal anaerobes were recovered. the only obligate anaerobes recovered were clostridia, and these were not recovered from the small intestinal masses. microbiological evidence from this study supports other, macrobotanical data indicating the intestinal origin of these masses. whether these organisms are direct descendants of the original intestinal microbiota, however, cannot be  established.
TIHT== 
ABHT== 

