@SUMMARY
INT == 
POS == 
NEG == 
@PAPERS
PMID== 25679309
TI  == pyrosequencing analysis of microbial community and food-borne bacteria on restaurant cutting boards collected in seri kembangan, malaysia, and their correlation with grades of food premises.
AB  == this study adopts the pyrosequencing technique to identify bacteria present on 26 kitchen cutting boards collected from different grades of food premises around seri kembangan, a city in malaysia. pyrosequencing generated 452,401 of total reads of otus with an average of 1.4x10(7) bacterial cells/cm(2). proteobacteria, firmicutes and bacteroides were identified as the most abundant phyla in the samples. taxonomic richness was generally high with >1000 operational taxonomic units (otus) observed across all samples. the highest appearance frequencies (100%) were otus closely related to enterobacter sp., enterobacter aerogenes, pseudomonas sp. and pseudomonas putida. several otus were identified most closely related to known food-borne pathogens, including bacillus cereus, cronobacter sakazaki, cronobacter turisensis, escherichia coli, e. coli o157:h7, hafnia alvei, kurthia gibsonii, salmonella bongori, salmonella enterica, salmonella paratyphi, salmonella tyhpi, salmonella typhimurium and yersinia enterocolitica ranging from 0.005% to 0.68% relative abundance. the condition and grade of the food premises on a three point cleanliness scale did not correlate with the bacterial abundance and type. regardless of the status and grades, all food premises have the same likelihood to introduce food-borne bacteria from cutting boards to their foods and must always prioritize the correct food handling procedure in order to avoid unwanted outbreak of food-borne illnesses.
TIHT== 
ABHT== 

PMID== 21722746
TI  == hygienic quality and antibiotic resistance profile of sliced butchery.
AB  == in order to investigate the microbiological quality of different meat products on the greek market, 200 samples were collected from the following preparations: boiled turkey (n=50), boiled pork ham (n=50), smoked turkey (n=50) and smoked pork ham (n=50). in all cold meat preparations clostridium perfringens vegetative and spore forms, staphylococcus aureus, escherichia coli and other clostridium sp lec(-), as well as lactobacillus, bacillus sp. and salmonella sp. were recovered. for instance bacillus cereus was present in 6% of the samples. l. monocytogenes,  campylobacter jejuni and campylobacter coli were rarely present (1-4%) while yersinia enterocolitica and campylobacter lari were absent. differences in the occurrence of s. aureus, salmonella sp., e. coli and spore forms of c. perfringens in boiled and smoked samples, reflects either the differences in the  processing of the foods or could be associated to the extensive handling by the personnel during the purchasing (storage, slicing, wrapping). antibiotic resistance on specific antibiotics for each pathogen was also studied. a multiresistance antibiotic profile was effective for most bacterial strains, and  pronounced resistance profiles were observed for the commonly used antibiotics as ampicillin, penicillin, cephalothin, streptomycin followed by ceftriaxone and gentamycin. albeit this high observed resistance profile, the tested strains generally conserved their susceptibility to amikacin, aztreonam, chloramphenicol  and tylosin conserved an almost absent resistance. antibiotics commonly used for  therapeutic purposes, as well as antibiotics added to feed stuff of animals for increasing animal flesh production should contribute to the extensive spreading of antibiotic resistance in food and the environment. systematically monitoring of the microbiological quality of cold butchery preparations must be done, in order to preserve food quality, optimizing the processing and elaboration methods of the product and safeguard the public health.
TIHT== 
ABHT== 

PMID== 19957209
TI  == antilisterial activity of a broad-spectrum bacteriocin, enterocin lr/6 from enterococcus faecium lr/6.
AB  == enterocin lr/6, a purified bacteriocin, exhibited broad inhibitory spectrum both  against related as well as some food-borne pathogens such as listeria monocytogenes, yersinia enterocolitica, aeromonas sp., shigella sp., and bacillus licheniformis. in this investigation, we have focused on l. monocytogenes as the  target organism, as it is not only an important pathogen but can also survive over a wide range of environmental conditions such as refrigeration temperature,  low ph, and high-salt concentration. this allows the pathogen to overcome many food preservation and safety barriers and poses a potential risk to human health. the enterocin lr/6 showed a bactericidal action against l. monocytogenes and completely inhibited the growth on agar plates, supplemented with 200 au/ml of enterocin lr/6. the effectiveness of enterocin lr/6 in completely killing a population of acid-adapted (ph 5.2, 2 h) l. monocytogenes exposed to different temperatures (4-37 degrees c), ph (2.5-8.0), and osmotic (up to 30% nacl) stress  is reported here. this paper focuses on the key issue of killing of the acid-adapted l. monocytogenes cells under adverse environmental conditions.
TIHT== 
ABHT== 

PMID== 16437687
TI  == detection and identification of intestinal pathogenic bacteria by hybridization to oligonucleotide microarrays.
AB  == aim: to detect the common intestinal pathogenic bacteria quickly and accurately.  methods: a rapid (<3 h) experimental procedure was set up based upon the gene chip technology. target genes were amplified and hybridized by oligonucleotide microarrays. results: one hundred and seventy strains of bacteria in pure culture belonging to 11 genera were successfully discriminated under comparatively same conditions, and a series of specific hybridization maps corresponding to each kind of bacteria were obtained. when this method was applied to 26 divided cultures, 25 (96.2%) were identified. conclusion: salmonella sp., escherichia coli, shigella sp., listeria monocytogenes, vibrio parahaemolyticus, staphylococcus aureus, proteus sp., bacillus cereus, vibrio cholerae, enterococcus faecalis, yersinia enterocolitica, and campylobacter jejuni can be detected and identified by our microarrays. the accuracy, range, and discrimination power of this assay can be continually improved by adding further  oligonucleotides to the arrays without any significant increase of complexity or  cost.
TIHT== 
ABHT== 

PMID== 15383024
TI  == photochemical treatment of platelet concentrates with amotosalen and long-wavelength ultraviolet light inactivates a broad spectrum of pathogenic bacteria.
AB  == background: bacterial contamination of platelet (plt) concentrates can result in  transfusion-transmitted sepsis. a photochemical treatment (pct) process with amotosalen hcl and long-wavelength ultraviolet light (uva), which cross-links nucleic acids, was developed to inactivate bacteria and other pathogens in plt concentrates. study design and methods: high titers of pathogenic aerobic and anaerobic gram-positive bacteria (10 species), aerobic gram-negative bacteria (7  species), and spirochetes (2 species) were added to single-donor plt concentrates containing 3.0 x 10(11) to 6.0 x 10(11) plts in approximately 300 ml of 35 percent plasma and 65 percent plt additive solution (intersol, baxter healthcare) or saline. after pct with 150 micro mol per l amotosalen and 3 j per cm(2) uva, residual bacterial levels were detected by sensitive microbiologic methods. results: the level of inactivation of viable bacteria was expressed as log reduction. log reduction of gram-positive bacteria for staphylococcus epidermidis was > 6.6; for staphylococcus aureus, 6.6; for streptococcus pyogenes, > 6.8; for listeria monocytogenes, > 6.3; for corynebacterium minutissimum, > 6.3; for bacillus cereus (vegetative), > 5.5; for lactobacillus sp., > 6.4; for bifidobacterium adolescentis, > 6.0; for propionibacterium acnes, > 6.2; and for  clostridium perfringens, > 6.5. log reduction of gram-negative bacteria for escherichia coli was > 6.4; for serratia marcescens, > 6.7; for klebsiella pneumoniae, > 5.6; for pseudomonas aeruginosa, 4.5; for salmonella choleraesuis,  > 6.2; for yersinia enterocolitica, > 5.9; and for enterobacter cloacae, 5.9. log reduction of spirochetes for treponema pallidum was 6.8 to 7.0, and for borrelia  burgdorferi, > 6.9. conclusion: pct inactivates high levels of a broad spectrum of pathogenic bacteria. the inactivation of bacteria in plt concentrates offers the potential to prospectively prevent plt-transfusion-associated bacteremia.
TIHT== 
ABHT== 

PMID== 9615472
TI  == studying the effect of temperature on microbial growth using multiplicative model.
AB  == the specific growth rates of brochothrix thermosphacta, listeria monocytogenes, yersinia enterocolitica, bacillus cereus, escherichia coli o157:h7, salmonella spp., staphylococcus aureus and clostridium perfringens at various temperatures were taken from the food micromodel database, and the data sets of specific growth rate versus temperature were fitted using the multiplicative model (r = a  td, r = specific growth rate; t = temperature; a, d = regression parameters). the exponential d-value derived from microbial growth at suboptimum temperatures reflected the effectiveness of temperature in enhancing growth. a microorganism with a large d-value exhibited a large increment of growth rate as temperature increased. the d-value of a microorganism was related to the temperature range for growth. the temperature range for the growth of psychrotrophs was usually narrow for b. thermosphacta and y. enterocolitica; hence the d-values of these two psychrotrophs were close to 1 whereas d-values of mesophiles, such as b. cereus, e. coli o157:h7, salmonella spp., and s. aureus, were 2.31-2.90, and the  d-value of c. perfringens, a thermophile, was 3.29. the values of parameter a of  the model were affected by extra salt added into cultures. for all the strains mentioned above, the a-values decreased when the cultures contained higher levels of salt. the lowering of the a-value implied that the influence of temperature on the growth rate in the model was reduced. the change of the d-value was dependent on the capability of the microorganism to overcome the obstacle to growth and was affected by the composition of the nutrients and by inhibitory factors in the culture. the influence of environmental factors on the d-value was also found in  chinese sausages. the d-value of a dominant spoilage strain of enterococcus sp. derived from sausages was 0.833 whereas the d-value derived from mrs cultures was 2.36. in refrigerated foods which usually contained some preservatives and were stored at low temperature, the d-value of psychrotrophic spoilage bacteria was around 1. in this case, the linear model could be a reasonable choice for predicting the proliferation of spoilage bacteria.
TIHT== 
ABHT== 

PMID== 7565414
TI  == molecular biology of microbial ureases.
AB  == urease (urea amidohydrolase; ec 3.5.1.5) catalyzes the hydrolysis of urea to yield ammonia and carbamate. the latter compound spontaneously decomposes to yield another molecule of ammonia and carbonic acid. the urease phenotype is widely distributed across the bacterial kingdom, and the gene clusters encoding this enzyme have been cloned from numerous bacterial species. the complete nucleotide sequence, ranging from 5.15 to 6.45 kb, has been determined for five species including bacillus sp. strain tb-90, klebsiella aerogenes, proteus mirabilis, helicobacter pylori, and yersinia enterocolitica. sequences for selected genes have been determined for at least 10 other bacterial species and the jack bean enzyme. urease synthesis can be nitrogen regulated, urea inducible, or constitutive. the crystal structure of the k. aerogenes enzyme has been determined. when combined with chemical modification studies, biophysical and spectroscopic analyses, site-directed mutagenesis results, and kinetic inhibition experiments, the structure provides important insight into the mechanism of catalysis. synthesis of active enzyme requires incorporation of both carbon dioxide and nickel ions into the protein. accessory genes have been shown to be required for activation of urease apoprotein, and roles for the accessory proteins in metallocenter assembly have been proposed. urease is central to the virulence of p. mirabilis and h. pylori. urea hydrolysis by p. mirabilis in the urinary tract leads directly to urolithiasis (stone formation) and contributes to the development of acute pyelonephritis. the urease of h. pylori is necessary for colonization of the gastric mucosa in experimental animal models of gastritis and serves as the major antigen and diagnostic marker for gastritis and peptic ulcer  disease in humans. in addition, the urease of y. enterocolitica has been implicated as an arthritogenic factor in the development of infection-induced reactive arthritis. the significant progress in our understanding of the molecular biology of microbial ureases is reviewed.
TIHT== 
ABHT== 

PMID== 1557802
TI  == visual identification of bacterially contaminated red cells.
AB  == there have been increasing numbers of reports of transfusion-acquired yersinia enterocolitica bacteremia (including several fatal cases). fifteen units of whole blood were inoculated with various concentrations of y. enterocolitica serotype 0:3 and processed into as-3 preserved red cells (rbcs). consistent growth of the  organism was found at inoculum concentrations greater than or equal to 10 colony-forming units per ml. in all 13 units of rbcs that supported the growth of y. enterocolitica, a darkening in color (due to hemolysis and a decrease in po2)  was observed in the bag. the attached sample segments, which were sealed from the main unit, remained sterile and did not darken. this color change was apparent in all the contaminated units by day 35, which was 1.5 to 2 weeks after the bacteria were first detected in cultures of the blood. hence, by comparison of the color of the segment tubing with that of the unit itself, units grossly contaminated with y. enterocolitica can be identified prior to transfusion. moreover, review of photographs on file at the centers for disease control revealed this dramatic  color change in 2 units of blood that caused transfusion-transmitted sepsis (enterobacter agglomerans and an unidentified gram-negative bacillus, not yersinia sp.), which demonstrated that the color change was not limited to y. enterocolitica. this method of visual identification of contaminated units of blood could decrease the incidence of posttransfusion bacterial sepsis.
TIHT== 
ABHT== 

PMID== 6326398
TI  == [effect of solid substrates of microbial colony development].
AB  == bacteria have been found to grow differently at contact sites to both organic and anorganic solids as on pure agar media. of 16 ad hoc selected bacterial strains,  the following species (arranged in decreasing order) responded with stronger colony formation: bacillus subtilis, b. cereus, streptococcus sanguis, s. saprophyticus, s. faecalis, escherichia coli, micrococcus flavus, actinomyces viscosus, veillonella sp., enterobacter liquefaciens, yersinia enterocolitica. lactobacillus casei behaved neutral. proteus vulgaris, y. enterocolitica and chromobacterium violaceum grow on certain media only in the presence of solid particles. the yeasts endomyces lactis, saccharomyces cerevisiae, rhodotorula mucilaginosa and cryptococcus nigricans did not respond to solid particles during colony formation. the kind of protein-animal (meat) or vegetable (soy beans)-did  not influence the behaviour of the microorganisms in these experiments.
TIHT== 
ABHT== 

