@SUMMARY
INT == 0
POS == 0
NEG == 0
@PAPERS
PMID== 23972717
TI  == tunel analysis of dna fragmentation in mouse unfertilized oocytes: the effect of  microorganisms within human follicular fluid collected during ivf cycles.
AB  == recently we reported the presence of bacteria within follicular fluid. previous studies have reported that dna fragmentation in human spermatozoa after in vivo or in vitro incubation with bacteria results in early embryo demise and a reduced rate of ongoing pregnancy, but the effect of bacteria on oocytes is unknown. this study examined the dna within mouse oocytes after 12 hours' incubation within human follicular fluids (n=5), which were collected from women undergoing in vitro fertilization (ivf) treatment. each follicular fluid sample was cultured to detect the presence of bacteria. terminal deoxynucleotidyl transferase mediated dutp nick-end labeling (tunel) was used to label dna fragmentation in ovulated, non-fertilized mouse oocytes following in vitro incubation in human follicular fluid. the bacteria streptococcus anginosus and peptoniphilus spp., lactobacillus gasseri (low-dose), l. gasseri (high-dose), enterococcus faecalis, or propionibacterium acnes were detected within the follicular fluids. the most severe dna fragmentation was observed in oocytes incubated in the follicular fluids containing p. acnes or l. gasseri (high-dose). no dna fragmentation was observed in the mouse oocytes incubated in the follicular fluid containing low-dose l. gasseri or e. faecalis. low human oocyte fertilization rates (<29%) were associated with extensive fragmentation in mouse oocytes (80-100%). bacteria colonizing human follicular fluid in vivo may cause dna fragmentation in mouse oocytes following 12h of in vitro incubation. follicular fluid bacteria may result in poor quality oocytes and/or embryos, leading to poor ivf outcomes.
TIHT== 
ABHT== 

PMID== 23163048
TI  == [role of infectious agents in the emergence of malignant tumors].
AB  == according to the data of the international agency for research on cancer (iarc),  at least 6 virus species (hpv, ebv, hhv-8/kshv, htlv-1, hbv, hcv), 4 helminthes species (schistosoma haematobium and japonicum, opisthorchis viverrini, clonorchis sinensis) and i bacterium species (helicobacter pylori) have been proved to be capable of causing the development of cancer. the analysis of the data available shows that merkel cell polyomavirus (mcv), herpes simplex virus (hsv), john cunningham polyomavirus (jcv), monkey virus 40 (sv40), cytomegalovirus (cmv), xenotropic murine leukemia virus (xmrv), helicobacter bilis and hepaticus, campylobacter jejuni, fusobacterium varium, enteropathogenic escherichia coli, enterotoxigenic bacteroides fragilis, bacteroides vulgatus, prevotella spp., streptococcus bovis and anginosus, treponema denticola, salmonella typhi, paratyphi and typhimurium, borrelia burgdorferi, bartonella spp., mycobacterium tuberculosis, chlamydia pneumoniae, trachomatis and psittaci, neisseria gonorrhoeae, propionibacterium acnes, tropheryma whippelii, schistosoma mansoni, opistorchis felineus, strongyloides stercoralis, taenia solium, candida  spp., paracoccidioides brasiliensis, histoplasma capsulatum and trichomonas vaginalis can also be potential etiological agents of cancer. apparently, detection of new associations between infectious agents and risk of the development of cancer will facilitate progress in elaboration of prophylaxis measures, early diagnostic methods and, probably, methods of treatment of malignant tumors.
TIHT== 
ABHT== 

