@BEGIN::SUMMARY
INTERACTS == 
POSITIVE == 
NEGATIVE == 
@BEGIN::ABSTRACTS
> PMID == 
TI == distribution of genes encoding the microbial non-oxidative reversible hydroxyarylic acid decarboxylases/phenol carboxylases.
AB == bacterial non-oxidative, reversible multi subunit hydroxyarylic acid decarboxylases/phenol carboxylases are encoded by the three clustered genes, b, c, and d, of approximately 0.6, 1.4, and 0.2 kb, respectively. there are more than 160 homologues in the database with significant similarity to gene b (homology to ubix) and c (ubid) distributed in all three microbial domains, however, homologues to gene d, are not numerous ( approximately 15). the occurrence of the entire bcd gene cluster encoding for either identified or presumptive hydroxyarylic acid decarboxylase to date has been revealed in sedimentibacter hydroxybenzoicus (unique genes arrangement cdb), streptomyces sp. d7, bacillus subtilis, b. licheniformis, e. coli o157:h7, klebsiella pneumoniae, enterobacter cloacae, shigella dysenteriae, salmonella enterica, s. paratyphi, s. typhimurium, s. bongori, and s. diarizonae. the corresponding genes from s. hydroxybenzoicus, b. subtilis, streptomyces sp. d7, e. coli o157:h7, k. pneumoniae, and s. typhimurium were cloned and expressed in e. coli dh5alpha (void of analogous genes), and shown to code for proteins exhibiting non-oxidative hydroxyarylic acid decarboxylase activity.
TIHIT == 
ABHIT == 
> PMID == 
TI == isolation, characterization, and u(vi)-reducing potential of a facultatively anaerobic, acid-resistant bacterium from low-ph, nitrate- and u(vi)-contaminated subsurface sediment and description of salmonella subterranea sp. nov.
AB == a facultatively anaerobic, acid-resistant bacterium, designated strain frcl, was  isolated from a low-ph, nitrate- and u(vi)-contaminated subsurface sediment at site fw-024 at the natural and accelerated bioremediation research field research center in oak ridge, tenn. strain frcl was enriched at ph 4.5 in minimal medium with nitrate as the electron acceptor, hydrogen as the electron donor, and acetate as the carbon source. clones with 16s ribosomal dna (rdna) sequences identical to the sequence of strain frcl were also detected in a u(vi)-reducing enrichment culture derived from the same sediment. cells of strain frcl were gram-negative motile regular rods 2.0 to 3.4 micro m long and 0.7 to 0.9 microm in diameter. strain frcl was positive for indole production, by the methyl red test, and for ornithine decarboxylase; it was negative by the voges-proskauer test (for acetylmethylcarbinol production), for urea hydrolysis, for arginine dihydrolase, for lysine decarboxylase, for phenylalanine deaminase, for h(2)s production, and for gelatin hydrolysis. strain frcl was capable of using o(2), no(3)(-), s(2)o(3)(2-), fumarate, and malate as terminal electron acceptors and of reducing u(vi) in the cell suspension. analysis of the 16s rdna sequence of the isolate indicated that this strain was 96.4% similar to salmonella bongori and 96.3% similar to enterobacter cloacae. physiological and phylogenetic analyses suggested that strain frcl belongs to the genus salmonella and represents a new species, salmonella subterranea sp. nov.
TIHIT == 
ABHIT == 
> PMID == 
TI == an improved 16s rrna based pcr method for the specific detection of salmonella enterica.
AB == a molecular method for the detection of salmonella enterica strains based on 16s  rrna sequence analysis was developed by a modification of the previously described pcr primer 16sfi [j. appl. bacteriol. 80 (1996) 659], which was combined with a newly developed primer annealing at the position 66-82. only approximately two thirds of now determined salmonella 16s rrna sequences contained a region identical to the 16sfi primer sequence and the reverse primer 16siii was also not specific. combined, these two primers have been claimed to allow the specific detection of all salmonella; however, in this study, they did not recognize s. bongori and 3 out of 78 tested s. enterica strains. they also identified some of the tested enterobacter cloacae strains as salmonella. on the contrary, the new primer pair, minf and minr, made it possible to recognize correctly all of the 78 tested s. enterica strains, representing 31 different salmonella serovars. none of the 23 non-salmonella strains from the related gamma-proteobacterial genera was incorrectly recognized as belonging to s. enterica.
TIHIT == 
ABHIT == 
