@BEGIN::SUMMARY
INTERACTS == 
POSITIVE == 
NEGATIVE == 
@BEGIN::ABSTRACTS
> PMID == 
TI == short communication: in vitro assessment of antioxidant, antibacterial and phytochemical analysis of peel of citrus sinensis.
AB == antibacterial effect of citrus sinensis peel extracts was evaluated against several pathogenic bacteria associated with human and fish infections viz., escherichia coli, pseudomonas aeruginosa, klebsiella pneumonia, staphylococcus aureus, streptococcus pyogenes, staphylococcus epidermidis, serratia marcesnces, shigella flexneri, enterobacter amnigenus, salmonella typhimurium and serratia odorifera. methanol, ethanol, chloroform and diethyl ether solvents were used for extraction. in vitro antibacterial activity was analyzed by agar well and agar disc diffusion methods. it was found that ethanol extract showed highly significant inhibition of e. coli and k. pneumonia (12.6+/-0.94 mm and 11.6+/-1.2 mm) whereas methanol extract of c. sinensis also showed high zone of inhibition of s. odorifera (10.0+/-2.16 mm). the potential activity of active extracts was assessed and also compared with standard antibiotics through activity index formulation. the order of antioxidant activity through abts.+ and dpph free radical scavenging activity was ethanol>methanol>chloroform>diethyl ether. phytochemical screening of all solvents had determined the presence of terpenoids, alkaloids, steroids, glycosides and flavonoids. it was also found that chloroform/methanol (5:5) and butanol/ethanol/water (4:1:2.2) solvent systems showed significant separation of active phytochemical constituents. these findings reveal the potential use of c. sinensis peel to treat infectious diseases, which are being caused by microorganisms.
TIHIT == 
ABHIT == 
> PMID == 
TI == monitoring and identification of bacteria associated with safety concerns in the  manufacture of sao jorge, a portuguese traditional cheese from raw cow's milk.
AB == the aim of this study was to assess the hygienic quality of raw milk used in the  manufacture of sao jorge, a protected denomination of origin portuguese semihard cheese, as well as to ascertain the sanitary conditions prevailing during its processing. viable counts of enterobacteriaceae and micrococcaceae were accordingly obtained, pertaining to 21 independent batches (including samples of raw milk, curd, and cheeses after 1, 3, and 4 months of ripening), from 7 dairy farms. standard plate counts (log cfu per milliliter or per gram) ranged from 6.1 to 8.6 in raw milk, whereas they ranged from 7.0 to 8.0 in 4-month-old cheeses. viable counts of enterobacteriaceae ranged between 5.9 and 7.0 in raw milk and between 0.0 and 1.3 in 4-month-old cheeses. species identified within this family encompassed klebsiella oxytoca, klebsiella cloacae, klebsiella pneumoniae, enterobacter sakazakii, and escherichia coli; klebsiella ornithinolytica, klebsiella terrigena, and serratia odorifera were detected only in raw milk. no salmonella whatsoever could be detected in any of the samples. viable counts of micrococcaceae ranged between 4.7 and 5.9 and between 1.3 and 3.3 in raw milk and 4-month-old cheeses, respectively. species identified within this family encompassed staphylococcus sciuri, staphylococcus epidermidis, staphylococcus saprophyticus (which was found mainly in ripened cheeses), and staphylococcus aureus (which was not detected in 4-month-old cheeses). accompanying physicochemical analyses included determination of moisture, salt, and ph. statistical analyses revealed a negative correlation between salt content and viable numbers of enterobacteriaceae in cheese, whereas in the case of micrococcaceae, a more negative correlation was found between viable numbers and moisture content than between viable numbers and ph. the results of our study indicate, in general, poor milk handling conditions in all farms, given that the indicators total mesophile and enterobacteriaceae counts were high, between 100- and 1,000-fold those enforced by international standards pertaining to the matrices in question. however, by the time of regular consumption (i.e., after 4 months of ripening), sao jorge cheeses exhibit low levels of contamination by enterobacteriaceae and s. aureus, as well as absence of salmonella.
TIHIT == 
ABHIT == 
> PMID == 
TI == gadolinium-based mr contrast media: potential for growth of microbial contaminants when single vials are used for multiple patients.
AB == objective: to assess potential risk if single-dose vials of gadolinium-based contrast media are used for multiple patients. the use of multidose vials can pose a significant risk if contaminants are accidentally introduced into the vials and proliferate. therefore, we tested the ability of gadolinium-based contrast to support the growth of a variety of microbial pathogens. materials and methods: we collected the unused portions of 15 single-use vials of gadolinium-based contrast media. the residual contrast material was refrigerated after use and checked for sterility prior to inoculation with a selection of gram-positive and gram-negative bacteria and yeast. contrast material was incubated at room temperature and at 4 degrees c, and quantitative cultures were performed at 0, 24, 48, and 72 hr and at 7 days. results: no microbial growth occurred from cultures of the used contrast solutions prior to inoculation. none of the organisms tested in our study proliferated in the contrast material. all test organisms persisted at least 48 hr after inoculation at both temperatures. at 7 days, staphylococcus aureus, streptococcus epidermidis, and corynebacterium jeikeium were recovered in significant quantities. colony counts of serratia odorifera rapidly decreased at room temperature but persisted beyond 7 days at 4 degrees c. conclusion: the risk of contaminating vials of contrast agents punctured aseptically is small. our study demonstrates a lack of proliferation of organisms in the two gadolinium-based compounds tested, suggesting that these solutions could be used for more than one procedure.
TIHIT == 
ABHIT == 
