@BEGIN::SUMMARY
INTERACTS == 
POSITIVE == 
NEGATIVE == 
@BEGIN::ABSTRACTS
> PMID == 
TI == aerobic bacterial microbiota isolated from the cloaca of the european pond turtle (emys orbicularis) in poland.
AB == we conducted a comparative analysis of the aerobic cloacal bacteria of european pond turtles (emys orbicularis) living in their natural environment and juvenile turtles reared under controlled conditions in a breeding center. we included 130 turtles in the study. the aerobic bacteria isolated from the cloaca of the juvenile turtles were less diverse and more prevalent than the bacteria isolated from free-living adults. we isolated 17 bacterial species from juvenile captive turtles, among which the dominant species were cellulomonas flavigena (77/96), enterococcus faecalis (96/96), escherichia coli (58/96), and proteus mirabilis (41/96). from the adult, free-living turtles, we isolated 36 bacterial species, some of which are a potential threat to public health (e.g., salmonella enterica serovars newport, daytona, and braenderup; listeria monocytogenes; yersinia enterocolitica; yersinia ruckeri; klebsiella pneumoniae; vibrio fluvialis; and serratia marcescens), and pathogens that are etiologic agents of diseases of ectothermic animals (e.g., aeromonas sobria, aeromonas caviae, hafnia alvei, edwardsiella tarda, and citrobacter braakii; the last two species were isolated from both groups of animals). the cloacal bacterial biota of the european pond turtle was characterized by numerous species of bacteria, and its composition varied with turtle age and environmental conditions. the small number of isolated bacteria that are potential human pathogens may indicate that the european pond turtle is of relatively minor importance as a threat to public health.
TIHIT == 
ABHIT == 
> PMID == 
TI == acanthamoeba polyphaga, a potential environmental vector for the transmission of  food-borne and opportunistic pathogens.
AB == the endosymbiotic relationship could represent for many bacteria an important condition favouring their spread in the environment and in foods. for this purpose we studied the behaviour of some food-borne and opportunistic pathogens (listeria monocytogenes, staphylococcus aureus, enterococcus faecalis, salmonella enterica serovar enteritidis, aeromonas hydrophila, yersinia enterocolitica) when internalized in acanthamoeba polyphaga. our results confirm the capability of the bacteria tested to grow within amoebal hosts. we can observe two types of interactions of the bacteria internalized in a. polyphaga. the first type, showed by y. enterocolitica and a. hydrophila, was characterized by an early replication, probably followed by the killing and digestion of the bacteria. the second type, showed by e. faecalis and s. aureus was characterized by the persistence and grow inside the host without lysis. lastly, when amoebae were co-cultured with l. monocytogenes and s. enteritidis, an eclipse phase followed by an active intracellular growth was observed, suggesting a third type of predator-prey trend. the extracellular count in presence of a. polyphaga, as a result of an intracellular multiplication and subsequent release, was characterized by an increase of e. faecalis, s. aureus, l. monocytogenes and s. enteritidis, and by a low or absent cell count for y. enterocolitica and a. hydrophila. our study suggests that the investigated food-borne and opportunistic pathogens are, in most cases, able to interact with a. polyphaga, to intracellularly replicate and, lastly, to be potentially spread in the environment, underlining the possible role of this protozoan in food contamination.
TIHIT == 
ABHIT == 
> PMID == 
TI == in-vitro antimicrobial activity and synergistic/antagonistic effect of interactions between antibiotics and some spice essential oils.
AB == spices and herbs have been used for many years by different cultures. the aim of  the present study is (1) to investigate in-vitro antimicrobial effects of different spices and herbs (5 species: rosmarinus officinalis (rosemary), coriandrum sativum (coriander), micromeria fruticosa (l.) druce subsp. brachycalyx p.h. davis (white micromeria), cumium cyminum (cumin), mentha piperita (peppermint) against different bacteria and fungi species, and (2) to discuss the in-vitro possible effects between the plants and antibiotics. the microorganisms used were micrococcus luteus la 2971, bacillus megaterium nrs, bacillus brevis fmc 3, enterococcus faecalis atcc 15753, pseudomonas pyocyaneus dc 127, mycobacterium smegmatis ccm 2067, escherichia coil dm, aeromonas hydrophila atcc 7966, yersinia enterocolitica au 19, staphylococcus aureus cowan 1, streptococcus faecalis dc 74 bacteria, and saccharomyces cerevisiae wet 136, kluvyeromyces fragilis dc 98 fungi in this study. the results indicated that essential oils of rosmarinus officinalis, coriandrum sativum l., micromeria fruticosa (l.) druce subsp. brachycalyx p.h. davis, cumium cyminum l., mentha piperita l. were shown antimicrobial activity in the range of 7-60 mm 2 microl(-1) inhibition zone to the microorganisms tested, using disc diffusion method. standard antibiotic such as gentamicin (10 microg), cephalothin (30 microg), ceftriaxone (10 microg), nystatin (10 u) discs were used for comparison with the antimicrobial activities of essential oils of these plants. in addition, antibacterial activity of essential oils of these plants was researched by effects when it was used together with these standard antibiotics in vitro. however, antibacterial activity changed also by in vitro interactions between these standard antibiotics and essential oils of these plants. synergic, additive or antagonist effects were observed in antibacterial activity.
TIHIT == 
ABHIT == 
> PMID == 
TI == antioxidant, electrochemical, thermal, antimicrobial and alkane oxidation properties of tridentate schiff base ligands and their metal complexes.
AB == in this study, two schiff base ligands (hl(1) and hl(2)) and their cu(ii), co(ii), ni(ii), pd(ii) and ru(iii) metal complexes were synthesized and characterized by the analytical and spectroscopic methods. alkane oxidation activities of the metal complexes were studied on cyclohexane as substrate. the ligands and their metal complexes were evaluated for their antimicrobial activity against corynebacterium xerosis, bacillus brevis, bacillus megaterium, bacillus cereus, mycobacterium smegmatis, staphylococcus aureus, micrococcus luteus and enterococcus faecalis (as gram-positive bacteria) and pseudomonas aeruginosa, klebsiella pneumoniae, escherichia coli, yersinia enterocolitica, klebsiella fragilis, saccharomyces cerevisiae, and candida albicans (as gram-negative bacteria). the antioxidant properties of the schiff base ligands were evaluated in a series of in vitro tests: 1,1-diphenyl-2-picrylhydrazyl (dpph) free radical scavenging and reducing power activity of superoxide anion radical generated non-enzymatic systems. electrochemical and thermal properties of the compounds were investigated.
TIHIT == 
ABHIT == 
> PMID == 
TI == isolation of bacteriocin-like substances producing bacteria from finished cattle-manure compost and activity evaluation against some food-borne pathogenic and spoilage bacteria.
AB == a finished compost sample was examined for bacteriocin-like substance production  against five pathogenic bacteria: salmonella typhimurium ef 85-9, escherichia coli o157:h7 atcc 43888, enterococcus faecalis jcm 8726, staphylococcus aureus jcm 2151, and yersinia enterocolitica jcm 7577. at the preliminary detection of bacterial strains exhibiting antimicrobial activity from the compost sample, thirteen strains could be isolated. screening of the inhibitory activity was done using agar-well diffusion assay and microtiter plate growth assay. six bacterial strains from the compost showed an antimicrobial activity against one or more of the tested indicator strains. four strains (m1-m4) belonged to shigella species and the other two strains (m5 and m6) belonged to salmonella species. the antimicrobial activity was sensitive for alpha-chymotrypsin and papain. the antimicrobial substances from m3, m4 and m6 were heat stable when heated for 15 min at 121 degrees c with 100% relative activity. the bacteriocin-like substance produced by strain m2 was partially characterized. it exhibited an inhibitory activity against the tested food-borne pathogenic and spoilage bacteria, except enterobacter aerogenes jcm 1235 and lactobacillus plantarum subsp. plantarum jcm 1149. it was stable at a wide range of ph (3-11). there was no loss of activity for up to 3 weeks when stored at 4 and -20 degrees c or for up to 2 weeks when stored at 28 and -80 degrees c. this is the first report indicating the presence of bacteriocin-like activity in animal manure compost.
TIHIT == 
ABHIT == 
> PMID == 
TI == antibacterial activity of artemisia nilagirica leaf extracts against clinical and phytopathogenic bacteria.
AB == background: the six organic solvent extracts of artemisia nilagirica were screened for the potential antimicrobial activity against phytopathogens and clinically important standard reference bacterial strains. methods: the agar disk diffusion method was used to study the antibacterial activity of a. nilagirica extracts against 15 bacterial strains. the minimum inhibitory concentration (mic) of the plant extracts were tested using two fold agar dilution method at concentrations ranging from 32 to 512 microg/ml. the phytochemical screening of extracts was carried out for major phytochemical derivatives in a. nilagirica. results: all the extracts showed inhibitory activity for gram-positive and gram-negative bacteria except for klebsiella pneumoniae, enterococcus faecalis and staphylococcus aureus. the hexane extract was found to be effective against all phytopathogens with low mic of 32 microg/ml and the methanol extract exhibited a higher inhibition activity against escherichia coli, yersinia enterocolitica, salmonella typhi, enterobacter aerogenes, proteus vulgaris, pseudomonas aeruginosa (32 microg/ml), bacillus subtilis (64 microg/ml) and shigella flaxneri (128 microg/ml). the phytochemical screening of extracts answered for the major derivative of alkaloids, amino acids, flavonoids, phenol, quinines, tannins and terpenoids. conclusion: all the extracts showed antibacterial activity against the tested strains. of all, methanol and hexane extracts showed high inhibition against clinical and phytopathogens, respectively. the results also indicate the presence of major phytochemical derivatives in the a. nilagirica extracts. hence, the isolation and purification of therapeutic potential compounds from a. nilagirica could be used as an effective source against bacterial diseases in human and plants.
TIHIT == 
ABHIT == 
> PMID == 
TI == effect of mixed antimicrobial agents and flavors in active packaging films.
AB == active packaging is an emerging food technology to improve the quality and safety of food products. many works have been developed to study the antimicrobial activity of essential oils. essential oils have been traditionally used as flavorings in food, so they have an important odor impact but they have as well antimicrobial properties that could be used to protect the food. recent developments in antimicrobial active packaging showed the efficiency of essential oils versus bread and bakery products among other applications. however, one of the main problems to face is the odor and taste they could provide to the packaged food. using some aromas to mask the odor could be a good approach. that is why the main objective of this paper is to develop an antimicrobial packaging material based on the combination of the most active compounds of essential oils (hydrocinnamaldehyde, oregano essential oil, cinnamaldehyde, thymol, and carvacrol) together with some aromas commonly used in the food industry. a study of the concentration required to get the antimicrobial properties, the organoleptic compatibility with typical aroma present in many food systems (vanilla, banana, and strawberry), and the right combination of both systems has been carried out. antimicrobial tests of both the mentioned aromas, the main components of some essential oils, and the combination of both groups were carried out against bacteria (enterococcus faecalis, listeria monocytogenes, bacillus cereus, staphylococcus aureus, salmonella choleraesuis, yersinia enterocolitica, escherichia coli), yeasts (candida albicans, debaryomyces hansenii, zygosaccharomyces rouxii), and molds (botrytis cinerae, aspergillus flavus, penicillium roqueforti, eurotium repens, penicillium islandicum, penicillium commune, penicillium nalgiovensis). the sensory properties of the combinations were evaluated with a triangular test and classification was by an order test; the odor threshold of the aroma compounds was also studied. the results reveal that none of the aromas had antimicrobial properties. the most antimicrobial compounds are thymol, carvacrol, and cinnamaldehyde, but none of them could be combined with banana aroma, whereas only thymol with strawberry aroma gave the right combined organoleptic profile. all of the antimicrobials under study could be combined with vanilla aroma, providing both antimicrobial property and the odor expected.
TIHIT == 
ABHIT == 
> PMID == 
TI == a dna array based assay for the characterization of microbial community in raw milk.
AB == an oligonucleotide array based on pcr method containing a combination of probes for taxonomic markers and species-specific virulence genes was developed for the simultaneous identification of 14 lactic acid bacteria (lab) and food-borne pathogenic bacteria in raw milk. the hypervariable regions v3 and v6 of 16s, together with a variable region of 23s rrna genes and several genes specific for virulence factors were selected. universal primers and multiplex pcr were used for the rapid differentiation of bacterial species and low concentration of specific pathogenic and spoilage bacteria were detected in milk. the dominant species such as streptococcus thermophilus, enterococcus faecalis, lactococcus lactis, andleuconostoc lactis were identified by indirect-labelling reactions based upon incorporation of amino-allyl dutps. the results regarding food-borne pathogens detection showed highly specific hybridisation patterns with the genomic dna from campylobacter jejuni, escherichia coli, salmonella thyphimurium, listeria monocytogenes and yersinia enterocolitica. a clear differentiation of dominant species present in a complex microbial community such as raw milk was achieved by the application of short oligonucleotide probes which discriminate sequences differing by few nucleotides.
TIHIT == 
ABHIT == 
> PMID == 
TI == transport of selected bacterial pathogens in agricultural soil and quartz sand.
AB == the protection of groundwater supplies from microbial contamination necessitates  a solid understanding of the key factors controlling the migration and retention of pathogenic organisms through the subsurface environment. the transport behavior of five waterborne pathogens was examined using laboratory-scale columns packed with clean quartz at two solution ionic strengths (10 mm and 30 mm). escherichia coli o157:h7 and yersinia enterocolitica were selected as representative gram-negative pathogens, enterococcus faecalis was selected as a representative gram-positive organism, and two cyanobacteria (microcystis aeruginosa and anabaena flos-aquae) were also studied. the five organisms exhibit differing attachment efficiencies to the quartz sand. the surface (zeta) potential of the microorganisms was characterized over a broad range of ph values (2-8) at two ionic strengths (10 mm and 30 mm). these measurements are used to evaluate the observed attachment behavior within the context of the dlvo theory of colloidal stability. to better understand the possible link between bacterial transport in model quartz sand systems and natural soil matrices, additional experiments were conducted with two of the selected organisms using columns packed with loamy sand obtained from an agricultural field. this investigation highlights the need for further characterization of waterborne pathogen surface properties and transport behavior over a broader range of environmentally relevant conditions.
TIHIT == 
ABHIT == 
> PMID == 
TI == antimicrobial effects of turkish propolis, pollen, and laurel on spoilage and pathogenic food-related microorganisms.
AB == the antimicrobial activities of propolis extract, pollen extract, and essential oil of laurel (laurus nobilis l.) at concentrations from 0.02% to 2.5% (vol/vol) were investigated on bacteria (bacillus cereus, bacillus subtilis, escherichia coli, salmonella typhimurium, staphylococcus aureus, yersinia enterocolitica, enterococcus faecalis, and listeria monocytogenes), yeasts (saccharomyces cerevisiae and candida rugosa), and molds (aspergillus niger and rhizopus oryzae). pollen has no antimicrobial effects on the bacteria and fungi tested in the concentrations used. propolis showed a bactericidal effect at 0.02% on b. cereus and b. subtilis, at 1.0% on s. aureus and e. faecalis, and at 0.2% on l. monocytogenes. the minimum inhibitory concentration of propolis for fungi was 2.5%. propolis and laurel were ineffective against e. coli and s. typhimurium at the concentrations tested. the results showed that the antimicrobial activity were concentration dependent. propolis and essential oil of laurel may be used as biopreservative agents in food processing and preservation.
TIHIT == 
ABHIT == 
> PMID == 
TI == combined physico-chemical treatments based on enterocin as-48 for inactivation of gram-negative bacteria in soybean sprouts.
AB == enterocin as-48 was tested for decontamination of soybean sprouts against gram-negative bacteria. although treatment with bacteriocin alone had no effect on salmonella enterica, a synergistic antimicrobial effect was detected at ph 9.0 and in combination with moderate heat treatment. greatest inactivation was achieved for sprouts heated for 5 min at 65 degrees c in an alkaline (ph 9.0) enterocin as-48 solution of 25 microg/ml. bactericidal activity against s. enterica increased greatly when enterocin as-48 was used in washing solutions in combination with several chemical compounds: edta, lactic acid, peracetic acid, polyphosphoric acid, sodium hypochlorite, hexadecylpyridinium chloride, propyl-p-hydroxybenzoate, and hydrocinnamic acid. the combined treatment of enterocin as-48 and polyphosphoric acid was tested against several other gram-negative bacteria inoculated on sprouts. the bacteria tested showed great differences in sensitivity to polyphosphoric acid, but synergism with enterocin as-48 was confirmed in all cases. combinations of enterocin as-48 (25 microg/ml) and polyphosphoric acid in a concentration range of 0.1 to 2.0% significantly reduced or inhibited growth of the populations of s. enterica, escherichia coli o157:h7, shigella spp., enterobacter aerogenes, yersinia enterocolitica, aeromonas hydrophila and pseudomonas fluorescens in sprout samples stored at 6 degrees c and 15 degrees c. the combined treatment could therefore be applied to reduce the risks of gram-negative pathogenic as well as spoilage bacteria on sprouts.
TIHIT == 
ABHIT == 
> PMID == 
TI == development of flexible antimicrobial films using essential oils as active agents.
AB == the antimicrobial activity in the vapor-phase of laboratory-made flexible films of polypropylene (pp) and polyethylene/ethylene vinyl alcohol copolymer (pe/evoh) incorporating essential oil of cinnamon ( cinnamomum zeylanicum), oregano ( origanum vulgare), clove ( syzygium aromaticum), or cinnamon fortified with cinnamaldehyde was evaluated against a wide range of microorganisms: the gram-negative bacteria escherichia coli, yersinia enterocolitica, pseudomonas aeruginosa, and salmonella choleraesuis; the gram-positive bacteria listeria monocytogenes, staphylococcus aureus, bacillus cereus, and enterococcus faecalis; the molds penicillium islandicum, penicillium roqueforti, penicillium nalgiovense, eurotium repens, and a spergillus flavus and the yeasts candida albicans, debaryomyces hansenii, and zigosaccharomyces rouxii. films with a nominal concentration of 4% (w/w) of fortified cinnamon or oregano essential oil completely inhibited the growth of the fungi; higher concentrations were required to inhibit the gram-positive bacteria (8 and 10%, respectively), and higher concentrations still were necessary to inhibit the gram-negative bacteria. pp films were more effective than pe/evoh films. the atmospheres generated by the antimicrobial films inside petri dishes were quantitatively analyzed using headspace-single drop microextraction (hs-sdme) in combination with gas chromatography-mass spectrometry (gc-ms). the analyses showed that the oregano-fortified pp films released higher levels of carvacrol and thymol, and the cinnamon-fortified pp films released higher levels of cinnamaldehyde, during the first 3-6 h of incubation, than the corresponding pe/evoh films. shelf-life tests were also performed, demonstrating that the antifungal activities of the films persisted for more than two months after their manufacture. in addition, migration tests (overall and specific) were performed, using both aqueous and fatty simulants, to ensure that the films meet eu regulations regarding food contact materials. following contact with the tested films, the substances that had migrated into the aqueous simulants were recovered by direct immersion-single drop extraction (di-sdme) and then analyzed by gc-ms. the fatty stimulant (isooctane) was directly injected into the chromatographic system.
TIHIT == 
ABHIT == 
> PMID == 
TI == bacteria induce ctgf and cyr61 expression in epithelial cells in a lysophosphatidic acid receptor-dependent manner.
AB == cysteine-rich protein 61 (cyr61/ccn1) and connective tissue growth factor (ctgf/ccn2) are members of the ccn (cyr61, ctgf, nephroblastoma overexpressed gene) family and exert pleiotropic functions such as regulation of adhesion, migration, extracellular matrix deposition, or cell differentiation, and play an important role in wound healing. this study focused on the nature of the so far unknown ctgf and cyr61 mrna expression of epithelial cells after infection with bacteria. we demonstrate that infection of epithelial cells with attenuated yersinia enterocolitica lacking the virulence plasmid pyv leads to the expression of cyr61 and ctgf. virulent y. enterocolitica bearing the pyv virulence plasmid suppressed the mrna expression of these genes. yersinia-mediated inhibition of ctgf and cyr61 mrna expression is partially mediated by the cysteine protease yopt. further characterization of the yersinia factors, which trigger ctgf and cyr61 mrna expression, demonstrated that these factors were secreted and could be enriched in lipid extracts. beside yersinia, several other bacteria such as escherichia coli, pseudomonas aeruginosa, enterococcus faecalis, or staphylococcus aureus, as well as supernatants of these bacteria induced ctgf and cyr61 expression. blocking experiments with the lysophosphatidic acid (lpa) receptor-specific inhibitor ki16425 suggest a general involvement of lpa receptors in bacteria-triggered ctgf and cyr61 expression. these data suggest that lpa receptor-dependent expression of ctgf and cyr61 represents a common host response after interaction with bacteria.
TIHIT == 
ABHIT == 
> PMID == 
TI == vapor-phase activities of cinnamon, thyme, and oregano essential oils and key constituents against foodborne microorganisms.
AB == the aim of the study presented here was to gain knowledge about the vapor-phase antimicrobial activity of selected essential oils and their major putatively active constituents against a range of foodborne bacterial and fungal strains. in a first step, the vapor-phase antimicrobial activities of three commercially available essential oils (eos)-cinnamon (cinnamomum zeylanicum), thyme (thymus vulgaris), and oregano (origanum vulgare)-were evaluated against a wide range of microorganisms, including gram-negative bacteria (escherichia coli, yersinia enterocolitica, pseudomonas aeruginosa, and salmonella choleraesuis), gram-positive bacteria (listeria monocytogenes, staphylococcus aureus, bacillus cereus, and enterococcus faecalis), molds (penicillium islandicum and aspergillus flavus), and a yeast (candida albicans). the minimum inhibitory concentrations (mics) were generally lower for oregano eo than for the thyme and cinnamon eos, especially against the relatively resistant gram-negative. the persistence of the eos' antimicrobial activities over time was assessed, and changes in the composition of the atmosphere they generated over time were determined using single-drop microextraction (sdme) in combination with gas chromatography-mass spectrometry (gc-ms) and subsequent analysis of the data by principal component analysis (pca). more relevant chemicals were selected. in addition, the vapor-phase activities of putatively key constituents of the oils were screened against representative gram-positive (l. monocytogenes) and gram-negative (s. choleraesuis) bacteria, a mold (a. flavus), and a yeast (c. albicans). of the tested compounds, cinnamaldehyde, thymol, and carvacrol showed the strongest antimicrobial effectiveness, so their mics, defined as the minimum vapor concentrations that completely inhibited detectable growth of the microorganisms, were calculated. to check for possible interactions between components present in the eos, cinnamon eo was fortified with cinnamaldehyde and thyme eo with thymol, and then the antimicrobial activities of the fortified oils were compared to those of the respective unfortified eos using fractional inhibitory concentration (fic) indices and by plotting inhibition curves as functions of the vapor-phase concentrations. synergistic effects were detected for cinnamaldehyde on a. flavus and for thymol on l. monocytogenes, s. choleraesuis, and a. flavus. in all other cases the fortification had additive effects, except for cinnamaldehyde's activity against s. choleraesuis, for which the effect was antagonistic. finally, various microorganisms were found to cause slight changes over time to the atmospheres generated by all of the eos (fortified and unfortified) except the fortified cinnamon eo.
TIHIT == 
ABHIT == 
> PMID == 
TI == genotypic and phenotypic diversity of lactococcus lactis isolates from batzos, a  greek pdo raw goat milk cheese.
AB == the genotypic and phenotypic variability of 40 lactococcus lactis isolates obtained from three cheese-making trials of batzos cheese made one in each, winter, spring and summer was investigated. rapd-pcr, plasmid profiling and pfge were used to study the genetic variability and distinguish closely related isolates. results showed a high degree of heterogeneity among strains. according to pfge data, all strains except one were clustered together (at a similarity level of approximately 50%) with the l. lactis subsp. lactis reference strain and eleven groups of isolates consisting of 2-8 strains each were distinguished. plasmid profiling results revealed that there were eight isolates lacking plasmids and nine having unique plasmids. twenty-three isolates were allocated into six groups. there was an interesting similarity between the plasmid profiling groups and those formed according to pfge. clustering of strains according to rapd-pcr was in agreement with results obtained by both plasmid profiling and pfge for the majority of the strains. in addition, results obtained by molecular methods indicate a grouping of most of the strains according to the season of cheese production. all strains inhibited the growth of escherichia coli o157:h7. their ability to affect the growth of yersinia enterocolitica, staphylococcus aureus, bacillus cereus, listeria monocytogenes and enterococcus faecalis was strain dependent. in 42.5% of the isolates high acidifying ability in milk after 24 h was recorded and these were isolates, mainly, from fresh cheese. the 75% of the isolates from winter cheese exhibited higher lys- than leu-aminopeptidase activity while the approximately 67% of the isolates from summer cheese showed higher leu- than lys-aminopeptidase activity. their caseinolytic activity after growth in milk for 24 h was significant with preference for alpha(s)-casein degradation. the majority (90%) of the strains formed methanethiol from methionine and this ability was strain dependent. these results suggest that among the wild lactococcal population from batzos cheese there are interesting strains appropriate to be used as starters for the dairy industry.
TIHIT == 
ABHIT == 
> PMID == 
TI == antimicrobial and toxicological profile of the new biocide akacid plus.
AB == objectives: akacid plus is a new member of the polymeric guanidine family of disinfectants. it was especially developed to enhance the antimicrobial activity of this class with significantly less toxicity. the in vitro activity of akacid plus compared with chlorhexidine digluconate and mupirocin was tested against a total of 369 recent clinical isolates. methods: the organisms tested by clsi reference methods included the following: staphylococcus aureus (98), staphylococcus epidermidis (9), bacillus spp. (2), enterococcus faecalis (32), klebsiella spp. (45), enterobacter spp. (20), escherichia coli (65), salmonella spp. (6), shigella spp. (2), yersinia enterocolitica (1), acinetobacter spp. (4), proteus spp. (7), pseudomonas aeruginosa (59), stenotrophomonas maltophilia (4), candida spp. (10) and aspergillus spp. (7). in vitro selection of resistance to akacid plus was carried out on 24 strains. toxicological analyses were also performed. results: all tested agents were more effective against staphylococcus spp. and bacillus spp. than against e. faecalis and gram-negative bacteria. the mic90s of chlorhexidine and mupirocin showed a 4-fold and 32-fold increase for methicillin-resistant s. aureus in comparison with methicillin-susceptible strains, while mic values of akacid plus were similar for antibiotic-susceptible and multiresistant strains. bactericidal action of akacid plus was observed at 1-2x mic. the in vitro selection of resistance test showed no increase in mic values of akacid plus for any isolate after 30 passages. in addition, akacid plus showed low oral and dermal toxicity. conclusions: these preliminary results demonstrate the broad antimicrobial properties of akacid plus, which makes it a promising tool for topical application in the prophylaxis and treatment of bacterial and fungal infections.
TIHIT == 
ABHIT == 
> PMID == 
TI == comparison of bactericidal activity of six lysozymes at atmospheric pressure and  under high hydrostatic pressure.
AB == the antibacterial working range of six lysozymes was tested under ambient and high pressure, on a panel of five gram-positive (enterococcus faecalis, bacillus subtilis, listeria innocua, staphylococcus aureus and micrococcus lysodeikticus) and five gram-negative bacteria (yersinia enterocolitica, shigella flexneri, escherichia coli o157:h7, pseudomonas aeruginosa and salmonella typhimurium). the lysozymes included two that are commercially available (hen egg white lysozyme or hewl, and mutanolysin from streptomyces globisporus or m1l), and four that were chromatographically purified (bacteriophage lambda lysozyme or lal, bacteriophage t4 lysozyme or t4l, goose egg white lysozyme or gewl, and cauliflower lysozyme or cfl). t4l, lal and gewl were highly pure as evaluated by silver staining of sds-page gels and zymogram analysis while cfl was only partially pure. at ambient pressure each gram-positive test organism displayed a specific pattern of sensitivity to the six lysozymes, but none of the gram-negative bacteria was sensitive to any of the lysozymes. high pressure treatment (130-300 mpa, 25 degrees c, 15 min) sensitised several gram-positive and gram-negative bacteria for one or more lysozymes. m. lysodeikticus and p. aeruginosa became sensitive to all lysozymes under high pressure, s. typhimurium remained completely insensitive to all lysozymes, and the other bacteria showed sensitisation to some of the lysozymes. the possible applications of the different lysozymes as biopreservatives, and the possible reasons for the observed differences in bactericidal specificity are discussed.
TIHIT == 
ABHIT == 
> PMID == 
TI == detection and identification of intestinal pathogenic bacteria by hybridization to oligonucleotide microarrays.
AB == aim: to detect the common intestinal pathogenic bacteria quickly and accurately.  methods: a rapid (<3 h) experimental procedure was set up based upon the gene chip technology. target genes were amplified and hybridized by oligonucleotide microarrays. results: one hundred and seventy strains of bacteria in pure culture belonging to 11 genera were successfully discriminated under comparatively same conditions, and a series of specific hybridization maps corresponding to each kind of bacteria were obtained. when this method was applied to 26 divided cultures, 25 (96.2%) were identified. conclusion: salmonella sp., escherichia coli, shigella sp., listeria monocytogenes, vibrio parahaemolyticus, staphylococcus aureus, proteus sp., bacillus cereus, vibrio cholerae, enterococcus faecalis, yersinia enterocolitica, and campylobacter jejuni can be detected and identified by our microarrays. the accuracy, range, and discrimination power of this assay can be continually improved by adding further oligonucleotides to the arrays without any significant increase of complexity or cost.
TIHIT == 
ABHIT == 
> PMID == 
TI == a study on inhibitory effects of sigla tree (liquidambar orientalis mill. var. orientalis) storax against several bacteria.
AB == in this study, sigla (liquidambar orientalis mill.) storax (styrax) was investigated for antibacterial activity against aeromonas hydrophila, bacillus amyloliquefaciens, b. brevis, b. cereus, b. megaterium, b. subtilis, corynebacterium xerosis, enterobacter aerogenes, enterococcus faecalis, escherichia coli, e. coli o157:h7, klebsiella pneumoniae, listeria monocytogenes, micrococcus luteus, mycobacterium smegmatis, proteus vulgaris, pseudomonas aeruginosa, p. fluorescens, staphylococcus aureus and yersinia enterocolitica. the storax was dissolved in absolute ethanol and was tested at concentrations of 10.0%, 1.0%, 0.4%, 0.2% and 0.1%. pure ethanol was used for the control. the antibacterial activity of the sigla storax was determined by using the agar diffusion method. the growths of a. hydrophila, b. amyloliquefaciens, b. megaterium, e. coli, e. coli o157:h7, l. monocytogenes and y. enterocolitica were not inhibited by any of the concentrations of sigla storax. the results showed that sigla storax has antibacterial activity against many bacteria at concentrations of 10.0% and against some bacteria at concentrations of 1.0%, 0.4% and 0.2%.
TIHIT == 
ABHIT == 
> PMID == 
TI == solid- and vapor-phase antimicrobial activities of six essential oils: susceptibility of selected foodborne bacterial and fungal strains.
AB == the antimicrobial activity of essential oils (eos) of cinnamon (cinnamon zeylanicum), clove (syzygium aromaticum), basil (ocimum basillicum), rosemary (rosmarinus officinalis), dill (anethum graveolens), and ginger (zingiber officinalis) was evaluated over a range of concentrations in two types of contact tests (solid and vapor diffusion). the eos were tested against an array of four gram-positive bacteria (staphylococcus aureus, bacillus cereus, enterococcus faecalis, and listeria monocytogenes), four gram-negative bacteria (escherichia coli, yersinia enterocolitica, salmonella choleraesuis, and pseudomonas aeruginosa), and three fungi (a yeast, candida albicans, and two molds, penicillium islandicum and aspergillus flavus). the rationale for this work was to test the possibility of creating a protective atmosphere by using natural compounds that could extend the shelf life of packaged foodstuffs while minimizing organoleptic alterations. in the solid diffusion tests, cinnamon and clove gave the strongest (and very similar) inhibition, followed by basil and rosemary, with dill and ginger giving the weakest inhibition. the fungi were the most sensitive microorganisms, followed by the gram-positive bacterial strains. the gram-negative strain p. aeruginosa was the least inhibited. the composition of the atmosphere generated by the eos, and their minimum inhibitory concentrations (mics), were determined using a disk volatilization method, in which no inhibition from rosemary or basil was observed. cinnamon and clove, once again, gave similar results for every microorganism. as a general rule, mic (fungi) << mic (bacteria) with no clear differences between gram-positive or -negative strains except for p. aeruginosa, which was not inhibited by any of the eos in the vapor phase. the atmosphere generated from the eos was analyzed by means of solid-phase microextraction combined with gas chromatography-ion trap mass spectrometry. differences among the volatiles in the eos, which may be responsible for the differences in their antimicrobial performances, were found.
TIHIT == 
ABHIT == 
> PMID == 
TI == sensitization of gram-negative and gram-positive bacteria to jenseniin g by sublethal injury.
AB == jenseniin g, a bacteriocin produced by propionibacterium thoenii p126, is active  against related propionibacteria and some lactic acid bacteria and is sporostatic to botulinal spores. the objective of this study was to evaluate the effects of sublethal stress on jenseniin g activity. bacillus cereus, enterococcus faecalis, escherichia coli, listeria monocytogenes, salmonella typhimurium, shigella flexneri, staphylococcus aureus, and yersinia enterocolitica were subjected to temperature, acid, and osmotic stresses in the presence of jenseniin g. the bacteriocin reduced the viability of sublethally injured cultures, although the extent of reduction varied with strain and treatment. e. faecalis was the most sensitive to temperature stress; no reduction of viable counts occurred in the absence of jenseniin g, and a 1.5-log reduction occurred in the presence of jenseniin g. b. cereus, l. monocytogenes, and s. aureus were more sensitive to jenseniin g when exposed to heat stress than when exposed to cold stress, whereas e. coli, salmonella typhimurium, and s. flexneri were more sensitive to jenseniin g when exposed to cold stress than when exposed to heat stress. when comparing an acid stress test alone to a combination of acid stress and jenseniin g, e. faecalis and l. monocytogenes showed the greatest sensitivities with 4.87- and 2.82-log reductions, respectively, after 7 days. all cultures except for s. aureus were adversely affected by the combination of salt stress and jenseniin g. salmonella typhimurium showed the greatest sensitivity to salt stress with jenseniin g (a 1.54-log reduction at day 7) when compared to salt stress alone (a 0.55-log reduction at day 7). jenseniin g, like bacteriocins produced by other gram-positive species, has broader activity against stressed organisms.
TIHIT == 
ABHIT == 
> PMID == 
TI == optimization of pcr-based methods for rapid detection of campylobacter jejuni, campylobacter coli and yersinia enterocolitica serovar 0:3 in wastewater samples.
AB == pcr-based methods were evaluated for their adequacy to assess the removal of pathogens from wastewater samples. for the development and optimization of the methods, samples were taken at two different sites from two different constructed wetlands. campylobacter jejuni/coli and yersinia enterocolitica serogroup 0:3 were selected as model pathogens and enterococcus faecalis as a standard microbiological indicator. the chosen pcr protocols were optimized for wastewater dna extracts in order to obtain high sensitivity and reproducibility independently of the background flora. all pcr protocols were successfully performed and reproducible with a background of up to 10(10) nontarget cells per reaction. five cells of y. enterocolitica, 50 cells of c. jejuni/coli, and 500 cells of e. faecalis per 100ml treated water could be detected. the method detection limit in the settled wastewater was higher: 200 cells per 100ml for y. enterocolitica, 2000 cells per 100ml for c. jejuni/coli, and 20,000 cells per 100ml for e. faecalis. c. jejuni/coli and y. enterocolitica pcrs were adapted to municipal wastewater, with higher loads of potential pcr inhibitors. sensitivity was lower for this type of wastewater: 200 cells of y. enterocolitica and 2000 cells of c. jejuni/coli were detected per 100ml treated wastewater, 2500 cells of y. enterocolitica and 25,000 cells of c. jejuni/coli per 100ml settled wastewater. the developed pcr methods enable the detection of c. jejuni/coli, y. enterocolitica serogroup 0:3 and e. faecalis within 12h. they show specificity, reproducibility and low detection limits for the investigated pathogens.
TIHIT == 
ABHIT == 
> PMID == 
TI == the screening of hydrogen peroxide-producing lactic acid bacteria and their application to inactivating psychrotrophic food-borne pathogens.
AB == lactic acid bacteria were isolated from various food samples and evaluated for hydrogen peroxide (h2o2) production. cells suspended in 0.5% (wt/vol) glucose plus 0.5% (wt/vol) lactate (ph 7.0) were incubated for 5 h at 37 degrees c under aeration. among 193 strains, 27 strains accumulated 201-300 ppm h2o2, and 4 strains accumulated more than 301 ppm h2o2 in the cell suspensions. among the 9 high-level h2o2-producing strains, 8 strains were identified as lactococcus lactis subsp. lactis. the cell-free filtrate from lc. lactis subsp. lactis ai 62, which contained approximately 350 ppm h2o2, was evaluated for antimicrobial activity against enterococcus faecalis, ent. faecium, enterotoxigenic escherichia coli, listeria ivanovii, staphylococcus aureus, yersinia enterocolitica, and aeromonas hydrophila. after 1 h incubation at 30 degrees c in the cell-free filtrate, the initial viable cell counts of the target bacteria (5.53-6.00 log cfu/ml) were reduced by 0.12-5.00 log units, except in the case of enterococci. the sensitivity varied with the bacterial species and ph. the enterococci were resistant to the treatment. our results show that h2o2 accumulated by lactic acid bacteria in a cell suspension is very effective in reducing the viable cell count of food-borne pathogens.
TIHIT == 
ABHIT == 
> PMID == 
TI == screening of bifidobacterium strains isolated from human faeces for antagonistic  activities against potentially bacterial pathogens.
AB == as probiotic bacteria, strains belonging to the genus bifidobacterium colonise the gastro-intestinal tract of humans and animals at the time of birth, and they are found in young as well as in adult individuals in great numbers. moreover, they can interact with the development of enteric infections by the production of antimicrobial metabolites. in this work 281 strains of bifidobacteria were anaerobically isolated from human faecal samples, supplied by volunteers of different ages (youngs, adults, elders), and preliminarly described by microscopic observation. all strains were screened by the fructose 6-phosphate phosphoketolase (f6ppk) test in order to confirm their classification within the genus bifidobacterium. selected strains were used to evaluate their antagonistic activities against escherichia coli, salmonella thyphimurium, staphylococcus lentus, enterococcus faecalis, acinetobacter calcoaceticus, sphingomonas paucimobilis, listeria monocytogenes, yersinia enterocolitica, bacillus cereus, clostridium sporogenes. experiments were performed in vitro by different methods based on the observation of growth inhibition in petri dishes. the strains that showed the highest inhibiting activities were compared by sds-page for total cell proteins, using type strains of human origin as references. representative isolates were metabolically characterised by the biolog system; a specific database was created with strains obtained from our collection and a statistical evaluation for metabolic patterns was carried out.
TIHIT == 
ABHIT == 
> PMID == 
TI == bacterial inactivation by high-pressure homogenisation and high hydrostatic pressure.
AB == the resistance of five gram-positive bacteria, enterococcus faecalis, staphylococcus aureus, lactobacillus plantarum, listeria innocua and leuconostoc dextranicum, and six gram-negative bacteria, salmonella enterica serovar typhimurium, shigella flexneri, yersinia enterocolitica, pseudomonas fluorescens and two strains of escherichia coli, to high-pressure homogenisation (100-300 mpa) and to high hydrostatic pressure (200-400 mpa) was compared in this study. within the group of gram-positive bacteria and within the group of gram-negative bacteria, large differences were observed in resistance to high hydrostatic pressure, but not to high-pressure homogenisation. all gram-positive bacteria were more resistant than any of the gram-negative bacteria to high-pressure homogenisation, while in relative to high hydrostatic pressure resistance both groups overlapped. within the group of gram-negative bacteria, there also existed another order in resistance to high-pressure homogenisation than to high hydrostatic pressure. further it appears that the mutant e. coli lmm1010, which is resistant to high hydrostatic pressure is not more resistant to high-pressure homogenisation than its parental strain mg1655. the preceding observations indicate a different response of the test bacteria to high-pressure homogenisation compared to high hydrostatic pressure treatment, which suggests that the underlying inactivation mechanisms for both techniques are different. further, no sublethal injury could be observed upon high-pressure homogenisation of y. enterocolitica and s. aureus cell population by using low ph (5.5 7), nacl (0 6%) or sds (0-100 mg/l) as selective components in the plating medium. finally, it was observed that successive rounds of high-pressure homogenisation have an additive effect on viability reduction of y. enterocolitica and s. aureus.
TIHIT == 
ABHIT == 
> PMID == 
TI == antibacterial activity of citrate and acetate.
AB == objective: we evaluated citrate salt, acetate salt, and their combinations for antibacterial activity against a sample of common pathogens. methods: bacterial suspensions were added to serial microdilutions of the salts in broth, with final cell concentrations of 10(4-5) colony-forming units per milliliter. after overnight incubation at 35 degrees c, the minimum inhibitory concentration was recorded. bactericidal activity was screened by quantitative subcultures from the minimum inhibitory concentration dilution. results: citrate salt was active against gram-positive species and candida albicans but showed little activity against gram-negative species; acetate salt showed the opposite results. their combination did not show synergism or antagonism. conclusion: it may be feasible to take advantage of the different antibacterial spectra of these two agents and combine them for possible application such as food or medical preservative agents.
TIHIT == 
ABHIT == 
> PMID == 
TI == conserved degp protease in gram-positive bacteria is essential for thermal and oxidative tolerance and full virulence in streptococcus pyogenes.
AB == the degp protease, a multifunctional chaperone and protease, has been shown to be essential for virulence in gram-negative pathogens such as salmonella enterica serovar typhimurium, brucella abortus, yersinia enterocolitica, and pseudomonas aeruginosa. the function of degp in pathogenesis appears to be the degradation of damaged proteins that accumulate as a result of the initial host response to infection, which includes the release of reactive oxygen intermediates. additionally, the degp protease plays a major role in monitoring and maintaining the escherichia coli periplasm and influences e. coli pilus biogenesis. we report here the identification of highly homologous enzymes in streptococcus pyogenes, streptococcus gordonii, streptococcus mutans, staphylococcus aureus, and enterococcus faecalis. moreover, the phenotype of an insertionally inactivated degp allele in s. pyogenes is similar to that reported for e. coli, with temperature sensitivity for growth and enhanced sensitivity to reactive oxygen intermediates. virulence studies in a mouse model of streptococcal infection indicate that a functional degp protease is required for full virulence. these results suggest degp as an attractive broad-spectrum target for future anti-infective drug development.
TIHIT == 
ABHIT == 
> PMID == 
TI == treatment of sanitary-important bacteria by bacteriocin substance v24 in cattle dung water.
AB == quantification of sanitary-important bacteria (e.g. enterobacteriaceae), as well  as indicators of environmental contamination, was assessed in samples of cattle dung from 25 cattle farms in 15 north-eastern slovakia districts. the inhibitory effect of crude bacteriocin extract cbe v24 from enterococcus faecalis v24 against listeria monocytogenes ohio and yersinia enterocolitica ye85 was examined in cattle dung water with the aim of finding a new way of eliminating the health risk of the animal slurry. the following bacterial groups were quantified: salmonella spp., shigella-like spp. , proteus spp., enterobacter spp., citrobacter spp., pseudomonas spp. , escherichia coli, listeria spp., staphylococci, streptococci and enterococci (the average count ranged from 102 up to 104 cfu ml-1). antagonistic effect of the crude bacteriocin from enterococcus faecalis v24 in the range of 100-600 arbitrary units per ml (au ml-1) was shown against the following bacteria: enterobacter cloacae, ent. asburiae, proteus spp., salmonella spp., acinetobacter lwoffi, l. monocytogenes as well as y. enterocolitica ye85. during tests performed to study the inhibitory effect of the crude bacteriocin cbe v24 (concentration 800, 1600 au ml-1) against l. monocytogenes ohio and y. enterocolitica ye85 in experimentally contaminated cattle dung, a reduction of 2.03 and 1.44 log cfu ml-1, respectively, was already noted after 1 h after crude bacteriocin cbe v24 addition.
TIHIT == 
ABHIT == 
> PMID == 
TI == detection and characterization of a novel antibacterial substance produced by a lactobacillus delbrueckii strain 1043.
AB == a novel antibacterial substance produced by a strain isolated from bulgarian yellow cheese was characterized. the producer strain was identified by molecular typing to belong to the species lactobacillus delbrueckii, which is a rare producer of bacteriocins. the inhibitory agent was heat stable and active against lactic acid bacteria species and several food-borne pathogens: listeria monocytogenes, staphylococcus aureus, enterococcus faecalis, escherichia coli, yersinia enterocolitica and y. pseudotuberculosis. its sensitivity to amylolitic enzymes and lipase suggested that a lipid and carbohydrate moiety could be important for the activity. the amino acid content of the purified bacteriocin was estimated to 29 amino acids. the bacteriocin was shown to be small (3.6-6 kda) by three different methods: hplc gel-filtration, sds-page and amino acid contents.
TIHIT == 
ABHIT == 
> PMID == 
TI == resistance to antimicrobial agents used for animal therapy in pathogenic-, zoonotic- and indicator bacteria isolated from different food animals in denmark: a baseline study for the danish integrated antimicrobial resistance monitoring programme (danmap).
AB == this study describes the establishment and first results of a continuous surveillance system of antimicrobial resistance among bacteria isolated from pigs, cattle and broilers in denmark. the three categories of bacteria tested were: 1) indicator bacteria (escherichia coli, enterococcus faecalis, enterococcus faecium), 2) zoonotic bacteria (campylobacter coli/jejuni, salmonella enterica, yersinia enterocolitica), and 3) animal pathogens (e. coli, staphylococcus aureus, coagulase-negative staphylococci (cns), staphylococcus hyicus, actinobacillus pleuropneumoniae). a total of 3304 bacterial isolates collected from october 1995 through december 1996 were tested for susceptibility to all major classes of antimicrobial agents used for therapy in denmark. bacterial species intrinsically resistant to an antimicrobial were not tested towards that antimicrobial. acquired resistance to all antimicrobials was found. the occurrence of resistance varied by animal origin and bacterial species. in general, resistance was observed more frequently among isolates from pigs than from cattle and broilers. the association between the occurrence of resistance and the consumption of the antimicrobial is discussed, as is the occurrence of resistance in other countries. the results of this study show the present level of resistance to antimicrobial agents among a number of bacterial species isolated from food animals in denmark. thus, the baseline for comparison with future prospective studies has been established, enabling the determination of trends over time.
TIHIT == 
ABHIT == 
> PMID == 
TI == surveillance of antimicrobial resistance in bacteria isolated from food animals to antimicrobial growth promoters and related therapeutic agents in denmark.
AB == this study was conducted to describe the occurrence of acquired resistance to antimicrobials used for growth promotion among bacteria isolated from swine, cattle and poultry in denmark. resistance to structurally related therapeutic agents was also examined. three categories of bacteria were tested: 1) indicator bacteria (escherichia coli, enterococcus faecalis, enterococcus faecium), 2) zoonotic bacteria (campylobacter, salmonella, yersinia enterocolitica), and 3) animal pathogens (e. coli, staphylococcus aureus, coagulase-negative staphylococci (cns), staphylococcus hyicus, actinobacillus pleuropneumoniae). all antimicrobials used as growth promoters in denmark and some structurally related therapeutic agents (in brackets) were included: avilamycin, avoparcin (vancomycin), bacitracin, carbadox, flavomycin, monensin, olaquindox, salinomycin, spiramycin (erythromycin, lincomycin), tylosin (erythromycin, lincomycin), and virginiamycin (pristinamycin). bacterial species intrinsically resistant to an antimicrobial were not tested towards that antimicrobial. breakpoints for growth promoters were established by population distribution of the bacteria tested. a total of 2,372 bacterial isolates collected during october 1995 to september 1996 were included in the study. acquired resistance to all currently used growth promoting antimicrobials was found. a frequent occurrence of resistance were observed to avilamycin, avoparcin, bacitracin, flavomycin, spiramycin, tylosin and virginiamycin, whereas resistance to carbadox, monensin, olaquindox and salinomycin was less frequent. the occurrence of resistance varied by animal origin and bacterial species. the highest levels of resistance was observed among enterococci, whereas less resistance was observed among zoonotic bacteria and bacteria pathogenic to animals. the association between the occurrence of resistance and the consumption of the antimicrobial is discussed. the results show the present level of resistance to growth promoters in bacteria from food animals in denmark. they will form the baseline for comparison with future prospective studies, thereby enabling the determination of trends over time.
TIHIT == 
ABHIT == 
> PMID == 
TI == efficacy of ozonated water against various food-related microorganisms.
AB == the antimicrobial effects of ozonated water in a recirculating concurrent reactor were evaluated against four gram-positive and four gram-negative bacteria, two yeasts, and spores of aspergillus niger. more than 5 log units each of salmonella typhimurium and escherichia coli cells were killed instantaneously in ozonated water with or without addition of 20 ppm of soluble starch (ss). in ozonated water, death rates among the gram-negative bacteria--s. typhimurium, e. coli, pseudomonas aeruginosa, and yersinia enterocolitica--were not significantly different (p > 0.05). among gram-positive bacteria, listeria monocytogenes was significantly p < 0.05) more sensitive than either staphylococcus aureus or enterococcus faecalis. in the presence of organic material, death rates of s. aureus compared with l. monocytogenes and e. coli compared with s. typhimurium in ozonated water were not significantly (p > 0.05) affected by ss addition but were significantly reduced (p < 0.05) by addition of 20 ppm of bovine serum albumin (bsa). more than 4.5 log units each of candida albicans and zygosaccharomyces bailii cells were killed instantaneously in ozonated water, whereas less than 1 log unit of aspergillus niger spores was killed after a 5-min exposure. the average ozone output levels in the deionized water (0.188 mg/ml) or water with ss (0.198 mg/ml) did not differ significantly (p < 0.05) but were significantly lower in water containing bsa (0.149 mg/ml).
TIHIT == 
ABHIT == 
> PMID == 
TI == survival, physiological response and recovery of enteric bacteria exposed to a polar marine environment.
AB == survival, sublethal injury, and recoverability of escherichia coli, enterococcus  faecalis, salmonella typhimurium, and yersinia enterocolitica were investigated by using diffusion chambers over 54 to 56 days of in situ exposure to a polar marine environment (-1.8 degrees c; salinity, 34.5 ppt) at mcmurdo station, antarctica. plate counts were used to assess recoverability and injury, whereas direct viable counts (dvcs) and 5-cyano-2,3-ditolyl tetrazolium chloride (ctc) reduction were utilized to determine substrate responsiveness and respiratory activity, respectively. t90 values (times for 10-fold decreases in numbers of recoverable cells) on nonselective medium were ca. 216 to 259 h for e. coli, s. typhimurium, and y. enterocolitica and 432 h for e. faecalis. sublethal injury was greater in populations of indicator bacteria than in pathogens. dvcs, ctc reduction, and plate counts indicated progressive increases in viable but nonculturable cells in e. coli, s. typhimurium, and y. enterocolitica cultures throughout the 54-day exposure. forty-eight-day exposure of e. coli, s. typhimurium, and y. enterocolitica resulted in decreased optimal incubation temperatures for colony formation and inability to form colonies at 37 degrees c. the detection of responsive e. coli, s. typhimurium, and y. enterocolitica by the dvc and ctc methods remained within 1% of inoculum values during 54 days of exposure, indicating some long-term persistence in the viable-but-nonculturable state. percentages of respiring e. coli and s. typhimurium increased significantly upon addition of nutrients at all temperatures tested, indicating that nutrient availability rather than temperature limited enteric bacterial activity in this very cold environment. large nutrient inputs to low-temperature marine environments may thus allow for the long-term persistence of enteric bacteria in a nonrecoverable state.
TIHIT == 
ABHIT == 
> PMID == 
TI == antibacterial spectrum of lactoferricin b, a potent bactericidal peptide derived  from the n-terminal region of bovine lactoferrin.
AB == a physiologically diverse range of gram-positive and gram-negative bacteria was found to be susceptible to inhibition and inactivation by lactoferricin b, a peptide produced by gastric pepsin digestion of bovine lactoferrin. the list of susceptible organisms includes escherichia coli, salmonella enteritidis, klebsiella pneumoniae, proteus vulgaris, yersinia enterocolitica, pseudomonas aeruginosa, campylobacter jejuni, staphylococcus aureus, streptococcus mutans, corynebacterium diphtheriae, listeria monocytogenes and clostridium perfringens. concentrations of lactoferricin b required to cause complete inhibition of growth varied within the range of 0.3 to 150 micrograms/ml, depending on the strain and the culture medium used. the peptide showed activity against e. coli o111 over the range of ph 5.5 to 7.5 and was most effective under slightly alkaline conditions. its antibacterial effectiveness was reduced in the presence of na+, k+, mg2+ or ca2+ ions, or in the presence of various buffer salts. lactoferricin b was lethal, causing a rapid loss of colony-forming capability in most of the species tested. pseudomonas fluorescens, enterococcus faecalis and bifidobacterium bifidum strains were highly resistant to this peptide.
TIHIT == 
ABHIT == 
> PMID == 
TI == potent antagonism of escherichia coli, bacteroides ovatus, fusobacterium varium,  and enterococcus faecalis, alone or in combination, for enteropathogens in anaerobic continuous flow cultures.
AB == interactions between representative strains of four predominant resident bacteria of the human colon, escherichia coli, enterococcus faecalis, bacteroides ovatus, and fusobacterium varium, and strains of seven enteropathogens, yersinia enterocolitica, shigella flexneri, salmonella typhimurium, vibrio parahaemolyticus, v. cholerae serogroup non o1, staphylococcus aureus, and clostridium perfringens, were examined in studies with an anaerobic continuous flow culture system and medium resembling the content of the mouse caecum (mcm). potent unilateral antagonism attributable to synergic activities of the resident bacteria against the enteropathogens was evident. the four resident bacteria persisted at levels of c. 10(6) cfu/ml or more in single and in any mixed cultures of the resident species. the seven enteropathogens also persisted in single cultures. in contrast, y. enterocolitica was excluded in several days in mixed cultures with each of the four resident bacteria. sh. flexneri and staph. aureus were excluded in the presence of e. coli alone. c. perfringens, v. parahaemolyticus and v. cholerae serogroup non o1 were excluded in the presence of e. coli with b. ovatus and, in some cases, with additional species. s. typhimurium was the most resistant; only c. 10(2)-fold reduction of the population level was observed in mixed culture with all four of the resident species. when the amounts of some components in the medium, such as peptone and yeast extract, were increased, c. perfringens grew and persisted even in the presence of the four resident bacteria. sh. flexneri, in contrast decreased steadily, even in enriched media.
TIHIT == 
ABHIT == 
> PMID == 
TI == lymphocyte proliferative responses to bacterial antigens in b27-associated arthropathies.
AB == lymphocyte transformation tests to yersinia enterocolitica 0:3 and 0:6, klebsiella pneumoniae and streptococcus faecalis antigens have been carried out in ankylosing spondylitis, reactive arthritis/reiter's disease and controls. ankylosing spondylitis cases gave significantly lower responses than reactive arthritis/reiter's to yersinia enterocolitica 0:6 (p = 0.003) and klebsiella pneumoniae (p = 0.008), and less than controls to s. faecalis (p = 0.008). it appears, therefore, that within the b27 arthritis population there is heterogeneity of cell-mediated response to certain enteric bacteria, with the hyporesponders manifesting ankylosing spondylitis and the hyper-responders reactive arthritis/reiter's disease.
TIHIT == 
ABHIT == 
