@SUMMARY
INT == 0
POS == 0
NEG == 0
@PAPERS
PMID== 26033167
TI  == microbial dynamics during conversion from supragingival to subgingival biofilms in an in vitro model.
AB  == the development of dental caries and periodontal diseases result from distinct shifts in the microbiota of the tooth-associated biofilm. this in vitro study aimed to investigate changes in biofilm composition and structure, during the shift from a "supragingival" aerobic to a "subgingival" anaerobic profile. biofilms consisting of actinomyces oris, candida albicans, fusobacterium nucleatum, streptococcus oralis, streptococcus mutans and veillonella dispar were aerobically grown in saliva-containing medium on hydroxyapatite discs. after 64 h, campylobacter rectus, prevotella intermedia and streptococcus anginosus were further added along with human serum, while culture conditions were shifted to microaerophilic. after 96 h, porphyromonas gingivalis, tannerella forsythia and treponema denticola were finally added and the biofilm was grown anaerobically for another 64 h. at the end of each phase, biofilms were harvested for species-specific quantification and localization. apart from c. albicans, all other species gradually increased during aerobic and microaerophilic conditions,  but remained steady during anaerobic conditions. biofilm thickness was doubled during the microaerophilic phase, but remained steady throughout the anaerobic phase. extracellular polysaccharide presence was gradually reduced throughout the growth period. biofilm viability was reduced during the microaerophilic conversion, but was recovered during the anaerobic phase. this in vitro study has characterized the dynamic structural shifts occurring in an oral biofilm model during the switch from aerobic to anaerobic conditions, potentially modeling the  conversion of supragingival to subgingival biofilms. within the limitations of this experimental model, the findings may provide novel insights into the ecology of oral biofilms. this article is protected by copyright. all rights reserved.
TIHT== 
ABHT== 

PMID== 25651832
TI  == pulp and plaque microbiotas of children with severe early childhood caries.
AB  == background and objective: bacterial invasion into pulps of primary teeth can lead to infection and premature tooth loss in children. this pilot study aimed to explore whether the microbiota of carious exposures of dental pulps resembles that of carious dentin or that of infected root canals. design: children with severe early childhood caries were studied. children were consented and extent of caries, plaque, and gingivitis measured. bacteria were sampled from carious lesion biofilms and vital carious exposures of pulps, and processed by anaerobic  culture. isolates were characterized from partial sequences of the 16s rrna gene  and identified by comparison with taxa in the human oral microbiome database (http://www.homd.org). the microbiotas of carious lesions and dental pulps were compared using univariate and multivariate approaches. results: the microbiota of cariously exposed pulps was similar in composition to that of carious lesion biofilms except that fewer species/taxa were identified from pulps. the major taxa identified belonged to the phyla firmicutes (mainly streptococci) and actinobacteria (mainly actinomyces species). actinomyces and selenomonas species  were associated with carious lesions whereas veillonella species, particularly veillonella dispar was associated with pulps. other bacteria detected in pulps included streptococcus mutans, parascardovia denticolens, bifidobacterium longum, and several lactobacillus and actinomyces species. by principal, component analysis pulp microbiotas grouped together, whereas those in caries biofilms were widely dispersed. conclusions: we conclude that the microbiota of cariously exposed vital primary pulps is composed of a subset of species associated with carious lesions. vital primary pulps had a dominant firmicutes and actinobacteria microbiota which contrasts with reports of endodontic infections which can harbor a gram-negative microbiota. the microbiota of exposed primary pulps may provide insight into bacterial species at the forefront of caries invasion in dentinal lesions that can invade into the pulp and the nature of species that need suppressing for successful pulp therapy.
TIHT== 
ABHT== 

PMID== 24862495
TI  == the influence of oral veillonella species on biofilms formed by streptococcus species.
AB  == oral veillonella, veillonella atypica, veillonella denticariosi, veillonella dispar, veillonella parvula, veillonella rogosae, and veillonella tobetsuensis are known as early colonizers in oral biofilm formation. to investigate the role  of oral veillonella, biofilms formed by the co-culture of streptococcus gordonii, streptococcus mutans, streptococcus salivarius, or streptococcus sanguinis, with  oral veillonella were examined at the species level. the amount of biofilm formed by s. mutans, s. gordonii, and s. salivarius in the presence of the six veillonella species was greater than that formed in the control experiments, with the exception of s. mutans with v. dispar. in contrast, in the case of biofilm formation by s. sanguinis, the presence of veillonella species reduced the amount of the biofilm, with the exception of v. parvula and v. dispar. the time-dependent changes in the amount of biofilm and the number of planktonic cells were grouped into four patterns over the 24 combinations. only that of s. gordonii with v. tobetsuensis showed a unique pattern. these results indicate that the mode of action of this combination differed from that of the other combinations with respect to biofilm formation. it is possible that there may be  several factors involved in the interaction between streptococcus and veillonella species.
TIHT== 
ABHT== 

PMID== 24773294
TI  == red wine and oenological extracts display antimicrobial effects in an oral bacteria biofilm model.
AB  == the antimicrobial effects of red wine and its inherent components on oral microbiota were studied by using a 5-species biofilm model of the supragingival plaque that includes actinomyces oris, fusobacterium nucleatum, streptococcus oralis, streptococcus mutans and veillonella dispar. microbiological analysis (cfu counting and confocal laser scanning microscopy) of the biofilms after the application of red wine, dealcoholized red wine, and red wine extract solutions spiked or not with grape seed and inactive dry yeast extracts showed that the solutions spiked with seed extract were effective against f. nucleatum, s. oralis and a. oris. also, red wine and dealcoholized wine had an antimicrobial effect against f. nucleatum and s. oralis. additional experiments showed almost complete and early degradation of flavan-3-ol precursors [(+)-catechin and procyanidin b2] when incubating biofilms with the red wine extract. to our knowledge, this is the first study of antimicrobial properties of wine in an oral biofilm model.
TIHT== 
ABHT== 

PMID== 24769315
TI  == salivary pellicle composition and multispecies biofilm developed on titanium nitrided by cold plasma.
AB  == objective: the aim of this study was to evaluate the composition of the salivary  pellicle (sp) and multispecies biofilm developed on titanium nitrided by cold plasma. methods: titanium discs were allocated into a control group (ti) and an experimental group (tin - titanium-nitrided by cold plasma). the disc surface topography was characterized by scanning electron microscopy (sem) and atomic force microscopy (afm). the chemical composition of the disc surface was determined by x-ray photoelectron spectroscopy (xps). stimulated, clarified, and  filtered saliva was used to form pellicles on the discs. proteome analysis of the adsorbed sp proteins was performed by liquid chromatography-mass spectrometry (lc-ms). the surface free energy (sfe) was evaluated before and after sp formation. a multispecies biofilm composed of actinomyces naeslundii, streptococcus oralis, streptococcus mutans, fusobacterium nucleatum, veillonella  dispar, and candida albicans was developed on the sp-coated discs. viable microorganism counts were determined. the biomass and average thickness of biofilms were analyzed by confocal laser-scanning microscopy (clsm) with comstat  software. the biofilm organization was visualized by sem. results: the surface topography was similar in both groups. the sfe of the tin group did not differ from that of the ti group (p>0.05), although the adsorption of pellicle proteins  increased the sfe in both pellicle-coated groups (p<0.001). different proteins were identified on the ti and tin surfaces. the amount of biofilm was similar for both groups (p=0.416), but the counts of f. nucleatum and s. oralis were higher in the tin group (p<0.001). similar biofilms were characterized by the comstat data, clsm images, and sem images. conclusion: the titanium nitrided by cold plasma exhibited differences in sp composition and multispecies microbial biofilm population compared to the control titanium surface.
TIHT== 
ABHT== 

PMID== 16508276
TI  == effects of streptococcus mutans gtfc deficiency on mixed oral biofilms in vitro.
AB  == the aim of this study was to examine the influence of glucosyltransferase-gene-negative (gtf-) streptococcus mutans strains unable to synthesize water-insoluble or soluble glucan on the structure and macromolecular  diffusion properties of in vitro grown mixed oral biofilms. biofilms modeling supragingival plaque consisted of actinomyces naeslundii omz 745, candida albicans omz 110, fusobacterium nucleatum kp-f2, streptococcus oralis sk 248, veillonella dispar atcc 17748t and one of the s. mutans strains ua159, omz 966, omz 937 or omz 977. biofilms were grown anaerobically on sintered hydroxyapatite  disks for 64.5 h at 37 degrees c. to perform confocal laser scanning microscopy analyses, microorganisms were stained with syto 13 and extracellular polysaccharides (eps) with calcofluor. macromolecular diffusion properties were measured following timed biofilm exposure to texas-red-labeled 70-kda dextran. results showed that replacing wild-type s. mutans by a gtfc- mutant led to an increase in the volume fraction occupied by cells from 29 to 48% and a decrease of the eps volume fraction from 51 to 33%. no such changes were observed when the s. mutans wild-type strain was replaced by a gtfb- or gtfd- mutant. the diffusion coefficient of 70-kda dextran in biofilms containing the gtfc- s. mutans was 16-fold higher than in biofilms with the wild-type strain indicating a strong macromolecular sieving effect of gtf c-generated glucans. our data demonstrate the influence of eps on the structure and macromolecular diffusion properties of  an oral biofilm model and uncover our still limited knowledge of the function of  eps in biofilms and plaque.
TIHT== 
ABHT== 

PMID== 15117935
TI  == selection for high-level resistance by chronic triclosan exposure is not universal.
AB  == objectives: to investigate the effect of triclosan exposure on the antimicrobial  susceptibilities of numerically important dental bacteria. methods: a gradient plate technique was used to expose fusobacterium nucleatum, lactobacillus rhamnosus, neisseria subflava, porphyromonas gingivalis, actinomyces naeslundii,  prevotella nigrescens, streptococcus oralis, streptococcus sanguis, streptococcus mutans and veillonella dispar repeatedly to escalating, sublethal concentrations  of triclosan. escherichia coli atcc 8739 was included as an organism showing the  triclosan resistance development trait. mic values towards chlorhexidine, metronidazole and tetracycline were determined before and after biocide exposure. results: n. subflava, pr. nigrescens po. gingivalis and e. coli were highly susceptible to triclosan (mic range 0.1-3.9 mg/l), whereas the lactobacillus and  s. mutans were less susceptible (mic range 15.6-20.8 mg/l). triclosan exposure resulted in a highly significant ( approximately 400-fold) reduction in triclosan susceptibility (p < 0.01) for the positive control e. coli, although its mics towards chlorhexidine, metronidazole and tetracycline were not significantly altered. minor ( approximately two-fold) decreases in triclosan susceptibility (mic) occurred for pr. nigrescens and in s. sanguis and s. oralis (mbc). mean changes in susceptibilities (mic and mbc) of the oral species to chlorhexidine, metronidazole and tetracycline did not exceed two-fold, although chlorhexidine mbcs for s. sanguis were markedly, but transiently, increased. conclusions: these data fail to demonstrate biologically significant drug resistance in triclosan-exposed bacteria and suggest that markedly decreased triclosan susceptibility, although confirmed for e. coli, is not a universal phenomenon. other bacteria possibly possess more susceptible targets than fabi that are highly conserved, which may govern triclosan activity.
TIHT== 
ABHT== 

PMID== 12037363
TI  == effects of glucose and fluoride on competition and metabolism within in vitro dental bacterial communities and biofilms.
AB  == antimicrobial effects of fluoride in vivo remain contentious. previous studies suggested that 1 mm naf reduced acid production from glucose, and prevented the enrichment of bacteria associated with caries in a chemostat model. the present study examines the effects of a lower fluoride concentration (0.53 mm, 10 ppm naf) in both biofilm and planktonic microbial communities. nine oral species were grown at ph 7.0 and pulsed on 10 successive days with glucose; bacterial metabolism was allowed to reduce the ph for 6 h before being returned to neutrality, either in the presence or absence of naf. in addition, 10-day-old mixed culture biofilms were overlaid with glucose, with or without naf, and the ph change followed by microelectrode. after 10 days, chemostat ph dropped to ca.  ph 4.5 following glucose pulses, and the community was dominated by streptococcus mutans (rising from 4 to 23% of total cfu) and veillonella dispar (16 to 73%). in comparison, after 10 days pulsing with glucose + fluoride, the final ph was significantly higher (ca. ph 4.9) (paired t test, p < 0.0001). the culture was predominated by v. dispar (70%) and actinomyces naeslundii (13%), whereas s. mutans proportions were significantly lower (t test, p = 0.04), remaining <3% of  the total flora, compared to the culture without fluoride. biofilm ph fell to only ph 5.55 1 h after glucose/fluoride overlay, compared to 4.55 with glucose alone (paired t test, p < 0.000001). analysis of the data suggests that fluoride  exerts dual antimicrobial modes of action. fluoride prevents enrichment of s. mutans by inhibiting critical metabolic processes (direct effect) and, in an inter-related way, by reducing environmental acidification (indirect effect) in biofilms.
TIHT== 
ABHT== 

PMID== 11054158
TI  == the formation of mixed culture biofilms of oral species along a gradient of shear stress.
AB  == a chemostat mixed culture system was used to produce two distinct ecological states, state-1 (caries-like microcosm) and state-2 (periodontal-like microcosm). eleven bacterial species (streptococcus gordonii, strep. mitis i, strep. mutans,  strep. oralis, actinomyces naeslundii, lactobacillus casei, neisseria subflava, fusobacterium nucleatum, porphyromonas gingivalis, prevotella nigrescens, veillonella dispar) were used to inoculate the planktonic system. a flow cell, designed to produce convergent flow with increasing shear stress, was attached to the chemostat system, and the resultant biofilms developed from the state-1 and state-2 microcosms along the shear stress gradient were examined and compared using image analysis and viable counts. the biofilm produced from state-1 showed  a lower shear stress tolerance (0.146 pa) than the state-2 biofilm (0.236 pa). the biofilm compositions did not vary along the gradient of shear stress and were dependent on the initial inoculum conditions. gram-positive species were predominant in the state-1 biofilm, while gram-negative species were predominant  in state-2.
TIHT== 
ABHT== 

PMID== 9745120
TI  == analysis of ph-driven disruption of oral microbial communities in vitro.
AB  == previously, a mixed culture chemostat system was used to demonstrate that the ph  generated from carbohydrate metabolism, rather than carbohydrate availability per se, was responsible for the shifts observed in the oral microflora which are associated with high carbohydrate diets and the development of dental caries. the aim of this study was to determine more accurately the microbially generated ph at which such shifts occurred. nine oral bacteria were grown in three independent chemostats, and pulsed with glucose on 10 consecutive days. in one chemostat, ph  control was discontinued for 6 h, and the ph fall was restricted to a minimum value of ph 5.5; the ph fall was arrested in the other two chemostats at either ph 5. 0, or at ph 4.5. when the ph was allowed to fall, the numbers and proportions of streptococcus mutans and lactobacillus rhamnosus increased; this increase was directly related to the magnitude of the ph fall. veillonella dispar was the most numerous organism following all glucose pulsing regimes, especially  at low ph. the increase in proportions of acidogenic bacteria was accompanied by  a fall in the proportions of acid-sensitive species (fusobacterium nucleatum, prevotella nigrescens, streptococcus gordonii and streptococcus oralis). the counts of these species were relatively stable between ph 5.5 and 4.5, but were markedly reduced when the ph fell below ph 4.5; neisseria subflava could not persist in the culture at ph 4.5 or below. the data suggest that the disruption of communities associated with glucose metabolism and low ph can be explained in  terms of a two-stage process. a fall in ph to a value between ph 5.5 and 4.5 may  allow the enrichment of potentially cariogenic species, whilst permitting species associated with health to remain relatively unaffected. a further reduction in ph (<ph 4.5) may not only enhance the competitiveness of odontopathogens, but inhibit the growth and metabolism of non-caries-associated species. the results also indicate that species other that mutans streptococci or lactobacilli are competitive at ph values low enough to demineralise enamel, and thus suggest that a broader range of micro-organisms may be associated with caries initiation.
TIHT== 
ABHT== 

PMID== 9676475
TI  == study of root caries in an artificial mouth.
AB  == the object of this project was to develop a laboratory model system to study root and enamel caries. model plaque biofilms containing consortia of four (streptococcus mutans, streptococcus sobrinus, actinomyces naeslundii, and lactobacillus rhamnosus) or six (s mutans, s sobrinus, s mitis, a naeslundii, l rhamnosus, and veillonella dispar) species of caries pathogens were developed in  a artificial mouth. caries lesions similar to those found in vivo were produced on enamel and dentine blocks and in intact root tissues by these consortia more effectively than biofilms of the individual species. fluoride supplied at 5 ppm suppressed enamel caries effectively, less so dentinal lesion formation, but much more so than f incorporated into the mineralised surface of enamel and roots. this is the first direct comparison of the effect on caries of environmental f and tooth mineral f induced by a plaque-like bacterial biofilm.
TIHT== 
ABHT== 

PMID== 8380287
TI  == the effects of triclosan and zinc citrate, alone and in combination, on a community of oral bacteria grown in vitro.
AB  == a mixed-culture chemostat system has been used as a more stringent laboratory system for evaluation of the antimicrobial effects of triclosan and zinc citrate. the inhibitors were added alone, and in combination, as a pulse (a high initial inhibitor concentration which decreased with time) or as a dose (concentration of inhibitor increased with time) to give maximum concentrations of 34.5 mumol/l triclosan and 39.8 mumol/l zinc citrate. when dosed, triclosan inhibited a. viscosus and all five gram-negative species, whereas zinc citrate had less effect, probably due to complexation by media components. similar effects were seen when triclosan was pulsed, except that s. mutans was the most sensitive gram-positive species and v. dispar was unaffected. however, when the inhibitors  were dosed or pulsed in combination, marked complementary and additive inhibitory effects were observed, particularly against gram-negative species, although s. gordonii and s. oralis were relatively unaffected. the data confirm that increased effects can be obtained with suitable combinations of antimicrobial agents and suggest that, under certain conditions, apparently broad-spectrum antimicrobial agents may be acting more selectively than hitherto suspected.
TIHT== 
ABHT== 

PMID== 2059972
TI  == effect of nutrients on defined bacterial plaques and streptococcus mutans c67-1 implantation in a model mouth.
AB  == actinomyces viscosus wvu 627, streptococcus oralis lpa-1 and veillonella dispar omz 193 were cocultured on teeth in a model mouth for 66 h. synthetic saliva containing bovine salivary glycoprotein supported bacterial growth, although the  delivery of an intermittent nutrient supplement, containing 1% (w/v) glucose or sucrose, gave greater bacterial cell and viable counts. when streptococcus mutans c67-1 was super-inoculated onto 24-hour mixed plaques, it became established under all regimens, but there was pronounced colonization resistance. with saliva only, the proportion of s. mutans at 66 h was less than 0.5% of the total cultivable microflora. when a glucose supplement was delivered for 1 h every 6 h, s. mutans attained a final proportion of 2.4%. with sucrose, both s. mutans c67-1 and its non-cariogenic glucan-deficient mutant, c67-25, attained similar proportions of 15-20%. these experiments indicate how this model can be used to study the factors influencing colonizing ability and microbial interactions in biofilms under controlled conditions.
TIHT== 
ABHT== 

PMID== 1775479
TI  == sugar, fluoride, ph and microbial homeostasis in dental plaque.
AB  == factors that may contribute to the maintenance or breakdown of the oral microflora have been studied in the laboratory using a mixed culture chemostat system. carbohydrate type had relatively little influence of the proportions of individual species at neutral ph. in contrast, when the ph was allowed to fall following carbohydrate metabolism, the stability of the microflora was markedly perturbed. the proportions of streptococcus mutans, lactobacillus casei and veillonella dispar increased and they became the predominant species, while levels of other gram-negative organisms and s. gordonii declined. low levels (1 mmol/l) of sodium fluoride (naf) had little effect on the microflora at neutral ph. however, when the ph fell following carbohydrate metabolism, 1 mmol/l of naf  slowed acid production and, in so doing, reduced the inhibition of acid-sensitive species, and suppressed the selection of s. mutans under otherwise favourable conditions. these data (and others) suggest that the mode of action of fluoride in human beings might include a subtle but clinically significant antimicrobial effect. these findings have also led to the proposal of a modified hypothesis (the "ecological plaque hypothesis") to explain the role of the resident oral microflora in dental disease. the hypothesis also has implications for treatment  and prevention strategies.
TIHT== 
ABHT== 

PMID== 2325115
TI  == surface-associated properties of streptococcus milleri group strains and their potential relation to pathogenesis.
AB  == thirty strains from the streptococcus milleri (anginosus) group (smg) obtained from various sources were tested for a range of characters that could be associated with pathogenicity and the results were compared with those for type strains of s. sanguis, s. mutans and s. pyogenes. the smg strains were heterogeneous in all tests. most (18) belonged to one of the lancefield groups with group f predominating. adherence of strains isolated from abscesses to buccal epithelial cells was greater than that of other strains (p = 0.033). compared with strains of s. sanguis, smg strains were generally not aggregated by human saliva. they differed from the type strain of s. pyogenes in their relative ability to bind fibrinogen and fibronectin; they were less effective in binding fibrinogen (0.33-4.28% cf. 22% for s. pyogenes) and generally more effective in binding fibronectin (0.49-12.37% cf. 0.95%). strains isolated from infections were statistically better at binding fibronectin than other strains (p less than  0.001). the ability of strains to adhere to saliva-coated hydroxyapatite (sha) varied 10-fold, from 0.16-16.35%. the amount of fibronectin bound by smg strains  correlated with their ability to adhere to sha (p less than 0.001). the hydrophobicity of the strains, as measured in the hexadecane partition assay, ranged from 0.0% to 99.0%. some strains carried both positive and negative cell-surface charges and some strains with a highly hydrophobic cell surface also possessed a relatively high cell-surface charge. a minority of strains possessed  a net positive cell-surface charge. neither hydrophobicity nor cell-surface charge was related to the capacity of strains to adhere to sha. strains of smg co-aggregated weakly with strains of veillonella parvula, v. dispar, actinomyces  viscosus and a. naeslundii.
TIHT== 
ABHT== 

PMID== 2307751
TI  == colonization resistance of defined bacterial plaques to streptococcus mutans implantation on teeth in a model mouth.
AB  == we investigated the ability of streptococcus mutans c67-1 to colonize simple bacterial plaques and the effects of age and stability of the pre-formed plaque on colonization resistance. mixed-plaques of actinomyces viscosus wvu627, 'streptococcus mitior' lpa-1, and veillonella dispar omz193 were grown on tooth segments, mounted back to back for simulation of approximal sites in a model mouth for 66 h. s. mutans c67-1 was either included in the original inoculum or super-inoculated onto the developing plaque. inclusion of s. mutans c67-1 did not alter the total viable counts, but the proportional composition changed due to inter-species interactions. colonization resistance of the mixed-plaque samples developed within 24 h, although s. mutans c67-1 was always able to colonize these stagnation sites. colonization resistance of 24-hour plaque against a fresh isolate, s. mutans cp3, was also studied. there was greater colonization resistance by the basic plaque to this organism, compared with s. mutans c67-1, although the reasons for this were not clear. these initial experiments demonstrate the way in which the factors involved in bacterial colonization resistance in microbial films on teeth can be studied under controlled conditions.
TIHT== 
ABHT== 

